### ISSUE TITLE
History getrennt

### ISSUE THREAD

**Issue by sigi2345** [Apollon77/ioBroker.alexa2#10]
Hallo,
wäre es möglich die History getrennt für jeden Dot zu machen?

**Comment by Apollon77** [comment]
Nein, da die History die Aktivitäten des Alexa Accounts (generell) abfragt und nicht die eines einzelnen Echos. Es gibt quasi immer das letzte zurück was in der History des Amazon.Accounts auftaucht

**Comment by Apollon77** [comment]
Es ist faktisch die gleiche Liste die Du in der Alexa-App unter "Verlauf "oder so bekommst. Die ist Geräteübergreifend
