### ISSUE TITLE
Summary wird nicht gesetzt.

### ISSUE THREAD

**Issue by JestfulW** [Apollon77/ioBroker.alexa2#1000]
Ich nutze die Summarys, um per Sprache ausgelöste Alexa Routinen abzufangen und weitere Aktionen im ioBroker auszulösen oder um auf bestimmt Wörter in den Befehlen zu reagieren.
Leider wird seit einiger Zeit (evtl seit einem Update?) das Objekt Summary nicht mehr aktualisiert. Nachdem ich den Adapter neu gestartet habe, funktioniert es dann wieder für eine gewisse Zeit, bis es dann irgendwann wieder nicht mehr aktualisiert wird.
Ich nutze das stable repository, falls das noch wichtig sein sollte.

**Comment by Apollon77** [comment]
Welche Version des Adpters wird genutzt?
Was steht im Log? Vllt Fehler das die Push Connection nicht verbunden ist?

**Comment by JestfulW** [comment]
Installierte Version ist 3.23.2
Die Instanz wird ‚grün‘ angezeigt. Push is established und polling disabled.

**Comment by Apollon77** [comment]
Dann bitte Loglevel auf Debug stellen und schauen was passiert. Bei einer sprachinteraktionn sollte ein log kommen von der reinkommenden Push-message über eine Activity und danach wird die summary gelesen ... Bitte Log posten

**Comment by JestfulW** [comment]
Ich habe die Ursache des Problems lokalisiert. Mein Router wurde jede Nacht um 04:00 Uhr neu gestartet. Nach dem Neustart funktionierte der Adapter nicht mehr. Nachdem ich dann die Instanz neu gestartet habe, war wieder alles in Ordnung bis zum nächsten Router Neustart. Ich habe den router Neustart deaktiviert und seitdem gibt es mit dem summary keine Probleme mehr.
