### ISSUE TITLE
Smart Home Geräte filtern/auswählen

### ISSUE THREAD

**Issue by Stormbringer11** [Apollon77/ioBroker.alexa2#1001]
Hallo Apollon,

siehst du irgendeine Möglichkeit, dass man in deinem Adapter im Vorfeld filtert welche Smart Home Geräte in den ioBroker kommen sollen? Ähnlich wie beim UniFi Adapter, wo man die Auswahl hat welche DPs man braucht. 

Hintergrund ist der, dass bei größeres Installationen massig DPs angelegt werden, die man überhaupt nicht braucht. Bisher habe ich das immer mit HASS Adapter umschiffen können aber z. B. für den Amazon Air Quality Sensor jetzt.... Müsste ich den ioBroker mit wirklich 10.200 Objekten "zumüllen" nur wegen ein paar States vom Sensor.

**Comment by Apollon77** [comment]
Ich sage es mal so: Objekte die existieren und nicht geändert werden gzw gepollt werden schaden nichts und tun auch keinem weh ... ioBroker kommt damit klar.
