### ISSUE TITLE
alexa2.0 2023-01-14 11:35:46.265	info	Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted

### ISSUE THREAD

**Issue by Sascha8** [Apollon77/ioBroker.alexa2#1007]
This is a new echodot 5 with clock. I have a second device of this type - here I get no warning message.

Device-type:A2DS1Q2TPDJ48U - echoKueche (DS_VOLUME_SETTING,BT_PAIRING_FLOW_V2,UPDATE_WIFI,GADGETS,CLOCK_FORMAT_24_HR,DISPLAY_ADAPTIVE_BRIGHTNESS,TUNE_IN,EARCONS,ADAPTIVE_LISTENING,EQUALIZER_CONTROLLER_BASS,LEMUR_ALPHA,PERSISTENT_CONNECTION,VOICE_TRAINING,SPEECH_RECOGNIZER_USS,SUPPORT_CALENDAR_ALERT,APPLE_MUSIC,PAIR_BT_SINK,PANDORA,WAKE_WORD_SENSITIVITY,REQUIRES_OOBE_FOR_SETUP,MUSIC_SKILL,AUDIBLE,PAIR_BT_SOURCE,KINDLE_BOOKS,MICROPHONE,SET_TIME_ZONE,AUDIO_PLAYER,MOTION_DETECTION,ASCENDING_ALARM_VOLUME,ALEXA_VOICE,VOLUME_SETTING,FAR_FIELD_WAKE_WORD,AMAZON_MUSIC,TEMPERATURE_SENSOR,MOTION_SENSOR_RANGE_STRING,TAP_GESTURES_SINGLE_TAP,TAP_GESTURES_ROTATE_DISPLAY,TIMERS_AND_ALARMS,EQUALIZER_CONTROLLER_TREBLE,SALMON,SUPPORTS_LOCALE,SUPPORTS_SOFTWARE_VERSION,ACTIVE_AFTER_FRO,TUPLE,EFDCARDS,SUPPORTS_LOCALE_SWITCH,AUDIO_CONTROLS,ALEXA_GESTURES,SLEEP,DISPLAY_POWER_TOGGLE,TAP_GESTURES,CHANGE_NAME,ALEXA_PRESENCE,DEEZER,DREAM_TRAINING,CUSTOM_ALARM_TONE,I_HEART_RADIO,GOLDFISH,DISPLAY_BRIGHTNESS_ADJUST,FLASH_BRIEFING,TAP_GESTURES_RESUME_MEDIA,POPTART,TIDAL,SIRIUSXM,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,SET_LOCALE,DIALOG_INTERFACE_VERSION,MULTI_WAKEWORDS_SUPPORTED,SOUND_SETTINGS,EQUALIZER_CONTROLLER_MIDRANGE,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,TAHOE_BYOD,LOCALIZATION,GUARD_EARCON,DEREGISTER_DEVICE,REMINDERS,TUPLE_CATEGORY_A)

**Comment by Apollon77** [comment]
Ok, what can it do? Cna it execute commands and such or not?

**Comment by Sascha8** [comment]
It works fine as far as I can see 🤷‍♂️. Sometimes the clock display get switched off (on my second EchoDot5 too) but I think its an an EchoDot5 issue
