### ISSUE TITLE
Neue unbekannt Geräte - Echo Show 8 und Echo Dot Gen5

### ISSUE THREAD

**Issue by FabiB97** [Apollon77/ioBroker.alexa2#1008]
Ich habe in meinem Adapter Start Log die beiden neuen Geräte mit deren Funktionen stehen
Können diese Funktionen/Geräte eingebunden werden?

Echo Dot Gen5
> (TUNE_IN,CUSTOM_ALARM_TONE,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,GADGETS,MUSIC_SKILL,BT_PAIRING_FLOW_V2,I_HEART_RADIO,DS_VOLUME_SETTING,CHANGE_NAME,DREAM_TRAINING,TAP_GESTURES_RESUME_MEDIA,TUPLE_CATEGORY_A,TAHOE_BYOD,DISPLAY_ADAPTIVE_BRIGHTNESS,REQUIRES_OOBE_FOR_SETUP,DEEZER,UPDATE_WIFI,SUPPORTS_LOCALE,POPTART,ALEXA_PRESENCE,SLEEP,SIRIUSXM,AMAZON_MUSIC,ALEXA_VOICE,ACTIVE_AFTER_FRO,SET_LOCALE,LEMUR_ALPHA,MICROPHONE,SUPPORTS_LOCALE_SWITCH,ALEXA_GESTURES,TEMPERATURE_SENSOR,MOTION_SENSOR_RANGE_STRING,REMINDERS,AUDIBLE,AUDIO_CONTROLS,KINDLE_BOOKS,TIDAL,PERSISTENT_CONNECTION,DIALOG_INTERFACE_VERSION,WAKE_WORD_SENSITIVITY,DISPLAY_BRIGHTNESS_ADJUST,EARCONS,FLASH_BRIEFING,SALMON,LOCALIZATION,SUPPORTS_SOFTWARE_VERSION,EQUALIZER_CONTROLLER_TREBLE,TAP_GESTURES_SINGLE_TAP,SPEECH_RECOGNIZER_USS,TIMERS_AND_ALARMS,EQUALIZER_CONTROLLER_BASS,VOLUME_SETTING,CLOCK_FORMAT_24_HR,GUARD_EARCON,PAIR_BT_SOURCE,ASCENDING_ALARM_VOLUME,EFDCARDS,GOLDFISH,APPLE_MUSIC,MOTION_DETECTION,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,VOICE_TRAINING,PAIR_BT_SINK,DEREGISTER_DEVICE,FAR_FIELD_WAKE_WORD,DISPLAY_POWER_TOGGLE,AUDIO_PLAYER,PANDORA,SUPPORT_CALENDAR_ALERT,TAP_GESTURES,ADAPTIVE_LISTENING,EQUALIZER_CONTROLLER_MIDRANGE,MULTI_WAKEWORDS_SUPPORTED,SOUND_SETTINGS,SET_TIME_ZONE,TAP_GESTURES_ROTATE_DISPLAY,TUPLE)

Echo Show 8
> (TUNE_IN,CUSTOM_ALARM_TONE,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,MUSIC_SKILL,BT_PAIRING_FLOW_V2,SHARKNADO,I_HEART_RADIO,DS_VOLUME_SETTING,CHANGE_NAME,DREAM_TRAINING,DEEZER,SUPPORTS_LOCALE,POPTART,ALEXA_PRESENCE,VISUAL_GESTURE,SLEEP,SIRIUSXM,LIVE_VIEW,AMAZON_MUSIC,ALEXA_VOICE,SET_LOCALE,LEMUR_ALPHA,MICROPHONE,SUPPORTS_LOCALE_SWITCH,REMINDERS,AUDIBLE,AUDIO_CONTROLS,KINDLE_BOOKS,TIDAL,PERSISTENT_CONNECTION,DIALOG_INTERFACE_VERSION,EARCONS,FLASH_BRIEFING,SALMON,LOCALIZATION,TUPLE_CATEGORY_B,SUPPORTS_SOFTWARE_VERSION,EQUALIZER_CONTROLLER_TREBLE,SPEECH_RECOGNIZER_USS,TIMERS_AND_ALARMS,EQUALIZER_CONTROLLER_BASS,VOLUME_SETTING,CLOCK_FORMAT_24_HR,GUARD_EARCON,ASCENDING_ALARM_VOLUME,EFDCARDS,GOLDFISH,APPLE_MUSIC,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,VOICE_TRAINING,PAIR_BT_SINK,DEREGISTER_DEVICE,FAR_FIELD_WAKE_WORD,PANDORA,AUDIO_PLAYER,SUPPORT_CALENDAR_ALERT,ADAPTIVE_LISTENING,EQUALIZER_CONTROLLER_MIDRANGE,MULTI_WAKEWORDS_SUPPORTED,SOUND_SETTINGS,TUPLE)

Falls weiter Informationen benötigt werden, einfach Bescheid geben was gebraucht wird.

**Comment by vepman** [comment]
Wäre schön.

**Comment by Apollon77** [comment]
closed weil natürlich das relevante im Log fehlt - die andere zeile. Bitte neues issue
