### ISSUE TITLE
Login Prozess geht nicht

### ISSUE THREAD

**Issue by Kaskadeur111** [Apollon77/ioBroker.alexa2#1009]
Im Adapter ist die Push Benachrichtigung aktiviert, aber im Log ist zu erkennen, dass die Push Connection nicht zustande kommt.
![grafik](https://user-images.githubusercontent.com/28257942/214100807-41a280c5-f8bd-4239-83fe-8a8de714a82b.png)

Bisher habe ich folgendes probiert (Kurzform)
- Adapter runterschmeißen und neu installieren -> geht nicht, da bei der Cookie Aktivierung ein 404 Error kommt
- mit neu Installiertem Adapter und händisch eingefügtem Cookie selbes Verhalten, Adapter läuft, nur Push nicht
- iobroker testweise komplett frisch installiert in Debian-VM und nur Alexa Adapter installiert -> selbiges, Cookie lässt sich nicht holen
        Ich klicke auf Cookie holen -> werde auf die Amazon Login Seite geleitet, gebe meine Zugangsdaten ein -> Erhalte den  Bestätigungscode per SMS aufs Handy, und nach dem eingaben des Codes erhalte ich einen Amazon 404 Page not found error.

Mein iobroker ist im Docker installiert, per eigener IP erreichbar und nicht durch eine Firewall geblockt.

Was kann ich noch tun? Ich würde gern wieder die Push Verbindung nutzen um meine Routinen Triggern zu können.

![grafik](https://user-images.githubusercontent.com/28257942/214102760-3bb42b41-bd8a-431b-b4b5-c007ca89cd5f.png)

**Comment by Kaskadeur111** [comment]
Erledigt, Mail mit Log und Videoaufzeichnung ist raus. Schönen Abend! :-)

**Comment by Kaskadeur111** [comment]
Hallo, wie siehts aus? Hast du vielleicht schon eine Idee was ich noch tun könnte? Ich würde gern am Wochenende meinen IObroker auf ein neues System umsetzen. Wär cool wenn ich meiner Frau Eine funktionierende Alexa bieten könnte :-)

**Comment by Apollon77** [comment]
Ich habe noch keine Zeit gehabt ...

**Comment by Kaskadeur111** [comment]
Hi. Kann geschlossen werden. Ich habe auf Amazon die 2FA Authentifizierung einmal aktiviert und wieder deaktiviert. Dann änderte sich der Prozess fürs Cookie holen auch (kein PIN Eingabe sondern bestätigung direkt per Link in der SMS). Das funktionierte auf Anhieb. Die Push Connection läuft jetzt auch wieder. Scheinbar also wiedermal etwas im Amazon Profil schief gewesen. Danke 😀

**Comment by Apollon77** [comment]
Ok, cool ... hatte gestern Abend reingeschaut und dinge gesehen die ich aber auch so prüfen werde ... lass mal noch offen,. Aber gut zu wiss das es nichts akutes ist. Und ja eine Idee wäre auch gewesen 2FA mal zu reaktivieren :-)

**Comment by Phill4563** [comment]
Hi,
leider hat das bei mir nicht geholfen.
Gleiches Problem wie bei [Kaskadeur111]. 2fa aktiviert und wieder deaktiviert.
Leider bekomme ich keinen Link per SMS sondern weiterhin den Code. Gebe ich diese ein kommt ebenfalls der 404.
Grüße
Alexa Adapter: v3.25.2
Nodejs: v3.25.2
Iobroker läuft in einem proxmox container.
greetz Phil

**Comment by Apollon77** [comment]
Der allte SMS "2fa" weg geht nicht ... da ist bei amazon was kaputt. Stelle um auf die neue OTP oder via app ... das was der aktuelle Default ist

**Comment by Tomkeule** [comment]
Hallo,
bei mir ist es im Augenblick auch so das ich einen Code per SMS bekomme und dann auf einer 404-Seite lande.

mfg
Thomas

**Comment by Apollon77** [comment]
Na dannkennst DU ja von den Kommentaren hier die Lösung: 2FA Aktualisieren

**Comment by Benni86** [comment]
Top. Danke. Hat mir sehr geholfen :) 
Mit OTP ging es dann

**Comment by Phill4563** [comment]
Hi, nachdem ich’s nochmal probiert habe, hat es funktioniert.
Nach dem umstellen wie oben beschrieben hat es dann funktioniert.
Vielen Dank
Greetz phil

**Comment by Tomkeule** [comment]
Hallo,
danke für den Tip.
Es läuft wieder. Danke.

mgh

Thomas

**Comment by chrissss77** [comment]
Hallo ich habe ein Problem mit den Login auf der Alexa Seite kommt ja : open  http://............:35039 Witz your Browse and login to Amazon, nur habe ich ein Problem ich kann zwar die Login Daten eingeben, nur dann kommt der Sicherheitscode und da komme ich nicht weiter es kommt dann : Sorry we could find this Page. Was mache ich da falsch hab schon mehrfach versucht es funktionier einfach nicht.

**Comment by Apollon77** [comment]
https://github.com/Apollon77/ioBroker.alexa2#problem-with-cookie-determination-with-sms-based-2fa-flow
