### ISSUE TITLE
version 1.1.0 is crashing after a few seconds

### ISSUE THREAD

**Issue by sabixx** [Apollon77/ioBroker.alexa2#101]
Just upgraded to version 1.1.0 and now the instance of the Alexa adapter is crashing after a few seconds. The adapter restarts automatically but get the same crash every every 2 seconds..

last two crashes from the log:

host.iobroker | 2018-09-19 11:34:07.480 | error | instance system.adapter.alexa2.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2018-09-19 11:34:07.480 | error | by controller[0]:     at process._tickCallback (internal/process/next_tick.js:104:9)
Caught | 2018-09-19 11:34:07.480 | error | by controller[0]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
Caught | 2018-09-19 11:34:07.480 | error | by controller[0]:     at endReadableNT (_stream_readable.js:974:12)
Caught | 2018-09-19 11:34:07.480 | error | by controller[0]:     at IncomingMessage.emit (events.js:185:7)
Caught | 2018-09-19 11:34:07.480 | error | by controller[0]:     at emitNone (events.js:91:20)
Caught | 2018-09-19 11:34:07.480 | error | by controller[0]:     at httpsGet.e  (C:\ioBroker\node_modules\iobroker.alexa2\node_modules\alexa-remote2\alexa-remote.js:1030:47)
Caught | 2018-09-19 11:34:07.480 | error | by controller[0]: TypeError: Cannot create property 'summary' on string '{"summary":"Sports Update"'
host.iobroker | 2018-09-19 11:33:27.834 | error | instance system.adapter.alexa2.0 terminated with code 0 (OK)

Caught | 2018-09-19 11:33:27.834 | error | by controller[0]:     at process._tickCallback (internal/process/next_tick.js:104:9)
Caught | 2018-09-19 11:33:27.834 | error | by controller[0]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
Caught | 2018-09-19 11:33:27.834 | error | by controller[0]:     at endReadableNT (_stream_readable.js:974:12)
Caught | 2018-09-19 11:33:27.834 | error | by controller[0]:     at IncomingMessage.emit (events.js:185:7)
Caught | 2018-09-19 11:33:27.834 | error | by controller[0]:     at emitNone (events.js:91:20)
Caught | 2018-09-19 11:33:27.834 | error | by controller[0]:     at httpsGet.e  (C:\ioBroker\node_modules\iobroker.alexa2\node_modules\alexa-remote2\alexa-remote.js:1030:47)
Caught | 2018-09-19 11:33:27.834 | error | by controller[0]: TypeError: Cannot create property 'summary' on string '{"summary":"Sports Update"'
host.iobroker | 2018-09-19 11:32:46.387 | error | instance system.adapter.alexa2.0 terminated with code 0 (OK)

**Comment by Apollon77** [comment]
Loglevel bitte auf Debug stellen und log posten. Ich brauche die Zeile mit  "response" von davor.

**Comment by Apollon77** [comment]
PS: I hope you are fast enough for the debug. Else make 3 interactions with alexa and the "bad entry" should be no longer in the read history ...

**Comment by sabixx** [comment]
Hi,

sorry ich glaube das war leider zu spät... ich hatte in der zwischenzeit schon andere Sachem mit Alexa gemacht (das waren wohl die 3 Interaktionen). Sorry habe das zu spät gesehen.

Da sind zwar noch Einträge mit "report to developer" aber abstürzen tut es nicht mehr.



alexa2.0 | 2018-09-19 15:10:54.702 | info | {"applianceId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjU2NmQwOWE3LTE5ZGEtNDE0ZS04OTI3LTJiNGMyZDBkMDlmOSIsInN0YWdlIjoibGl2ZSJ9_RINCON_000E587426C001400","endpointTypeId":"SonosTestMDODevice","dri
-- | -- | -- | --
alexa2.0 | 2018-09-19 15:10:54.702 | info | Smarthome-Device Capability Alexa.PlaybackStateReporter unknown. Report  to developer this and next log line from logfile on disk!
alexa2.0 | 2018-09-19 15:10:54.701 | info | {"applianceId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjU2NmQwOWE3LTE5ZGEtNDE0ZS04OTI3LTJiNGMyZDBkMDlmOSIsInN0YWdlIjoibGl2ZSJ9_RINCON_000E58736ED201400","endpointTypeId":"SonosTestMDODevice","dri
alexa2.0 | 2018-09-19 15:10:54.701 | info | Smarthome-Device Capability Alexa.PlaybackStateReporter unknown. Report  to developer this and next log line from logfile on disk!
alexa2.0 | 2018-09-19 15:10:54.699 | info | {"applianceId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjU2NmQwOWE3LTE5ZGEtNDE0ZS04OTI3LTJiNGMyZDBkMDlmOSIsInN0YWdlIjoibGl2ZSJ9_RINCON_000E5873B94001400","endpointTypeId":"SonosTestMDODevice","dri
alexa2.0 | 2018-09-19 15:10:54.699 | info | Smarthome-Device Capability Alexa.PlaybackStateReporter unknown. Report  to developer this and next log line from logfile on disk!
alexa2.0 | 2018-09-19 15:10:54.698 | info | {"applianceId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjU2NmQwOWE3LTE5ZGEtNDE0ZS04OTI3LTJiNGMyZDBkMDlmOSIsInN0YWdlIjoibGl2ZSJ9_RINCON_000E5872BB7201400","endpointTypeId":"SonosTestMDODevice","dri
alexa2.0 | 2018-09-19 15:10:54.698 | info | Smarthome-Device Capability Alexa.PlaybackStateReporter unknown. Report  to developer this and next log line from logfile on disk!
alexa2.0 | 2018-09-19 15:10:54.697 | info | {"applianceId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjU2NmQwOWE3LTE5ZGEtNDE0ZS04OTI3LTJiNGMyZDBkMDlmOSIsInN0YWdlIjoibGl2ZSJ9_RINCON_5CAAFD4F0CB001400","endpointTypeId":"SonosTestMDODevice","dri
alexa2.0 | 2018-09-19 15:10:54.697 | info | Smarthome-Device Capability Alexa.PlaybackStateReporter unknown. Report  to developer this and next log line from logfile on disk!
alexa2.0 | 2018-09-19 15:10:54.696 | info | {"applianceId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjU2NmQwOWE3LTE5ZGEtNDE0ZS04OTI3LTJiNGMyZDBkMDlmOSIsInN0YWdlIjoibGl2ZSJ9_RINCON_000E5873704C01400","endpointTypeId":"SonosTestMDODevice","dri
alexa2.0 | 2018-09-19 15:10:54.696 | info | Smarthome-Device Capability Alexa.PlaybackStateReporter unknown. Report  to developer this and next log line from logfile on disk!
alexa2.0 | 2018-09-19 15:10:54.694 | info | {"applianceId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjU2NmQwOWE3LTE5ZGEtNDE0ZS04OTI3LTJiNGMyZDBkMDlmOSIsInN0YWdlIjoibGl2ZSJ9_RINCON_000E5881ECAA01400","endpointTypeId":"SonosTestMDODevice","dri
alexa2.0 | 2018-09-19 15:10:54.694 | info | Smarthome-Device Capability Alexa.PlaybackStateReporter unknown. Report  to developer this and next log line from logfile on disk!
alexa2.0 | 2018-09-19 15:10:36.756 | info | Alexa-Push-Connection established. Disable Polling
alexa2.0 | 2018-09-19 15:10:29.390 | info | starting. Version 1.1.0 in C:/ioBroker/node_modules/iobroker.alexa2, node: v6.12.0
host.iobroker | 2018-09-19 15:10:28.860 | info | instance system.adapter.alexa2.0 started with pid 8368
host.iobroker | 2018-09-19 15:10:28.843 | info | object change system.adapter.alexa2.0

**Comment by Apollon77** [comment]
kommt mit nächstem Update

**Comment by sabixx** [comment]
Hi Ingo,

wo finde ich die nodejs version?

**Comment by Apollon77** [comment]
hatte mich verschrieben. falscher thread. alles gut brauche nix

**Comment by Brainbug01** [comment]
Ich hab das gleiche Problem:

host.cloud | 2018-11-03 20:16:21.249 | error | instance system.adapter.alexa2.0 terminated with code 0 (OK)
-- | -- | -- | --
host.cloud | 2018-11-03 20:16:21.249 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:104:9)
host.cloud | 2018-11-03 20:16:21.248 | error | Caught by controller[0]: at _combinedTickCallback (internal/process/next_tick.js:80:11)
host.cloud | 2018-11-03 20:16:21.248 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:978:12)
host.cloud | 2018-11-03 20:16:21.247 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:185:7)
host.cloud | 2018-11-03 20:16:21.246 | error | Caught by controller[0]: at emitNone (events.js:91:20)
host.cloud | 2018-11-03 20:16:21.246 | error | Caught by controller[0]: at IncomingMessage.res.on.e (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:653:58)
host.cloud | 2018-11-03 20:16:21.245 | error | Caught by controller[0]: at httpsGet.e (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:1030:47)
host.cloud | 2018-11-03 20:16:21.244 | error | Caught by controller[0]: TypeError: Cannot create property 'summary' on string '{"summary":"Sports Update"'

Das Debug Log brauchst du?

**Comment by Apollon77** [comment]
mach zwei weitere Anfragen ein einen der Echos und der Fehler ist erstmal weg. Fix kommt mit nächstem Update
