### ISSUE TITLE
NPM Warning 

### ISSUE THREAD

**Issue by Fontheweg** [Apollon77/ioBroker.alexa2#1014]
Hi,
I'm not sure if it's the right way but I got the following warning with the installation of the Adapter:

npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

It think there is a requirement in the Adapter wich should be updated.... 

npm ls querystring
iobroker.inst@3.0.0 /opt/iobroker
- iobroker.alexa2@3.23.2
-- alexa-remote2@5.10.1
--- alexa-cookie2@4.1.3
---- querystring@0.2.1 deduped
--- querystring@0.2.1

**Comment by Apollon77** [comment]
It mIght get updated somewhen but for now it works and will not break just because there is a better way :-)
