### ISSUE TITLE
Geräuscherkennung

### ISSUE THREAD

**Issue by BenAhrdt** [Apollon77/ioBroker.alexa2#1019]
Mit den Echos gibt es die Möglichkeit Geräusche zu erfassen.
Ist es auch möglich einen Datenpunkt bei erkennen eines Geräusches zu setzen?
Bspw, wenn man in das Wohnzimmer kommt, dass sozusagen die Anwesenheit erkannt wird und wenn man wieder raus geht, dann meldet der Echo irgendwann kein Geräusch mehr und der datenpunkt wird wieder false.

**Comment by Apollon77** [comment]
Das würde gehen wenn "Smart Home device" States irgendwie gepusht werden, werden Sie aber nicht.

Was geht ist der Workaround: Definiere ein virtuelles Gerät über den iot Adapter als Schalter. Dann lege eine Routine an die auf das gewünschte Geräusch reagiert und dann eine Schaltaktion durchführt - als Gerät den iot Schalter nehmen.

Damit wird dann per iot Adapter und Amazon Cloud und iot Adapter dann quasi bei Geräuscherkennung der schalter geschaltet - und ggf dann wieder ausgeschaltet oder so ... Muss man experimentieren

**Comment by BenAhrdt** [comment]
Ok. Leider bietet die Alexa App nur paar vordefinierte Geräusche, nicht generell irgend ein Geräusch, was auf eine Anwesenheit hin deutet. Schade
