### ISSUE TITLE
I got this warn in log every 5 min.

### ISSUE THREAD

**Issue by maxx3105** [Apollon77/ioBroker.alexa2#102]
Disabling some commands for device because of unknown type. Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
--

Device-type:A2L8KG0CT86ADW (TIMERS_AND_ALARMS,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,KINDLE_BOOKS,DEREGISTER_DEVICE,AUDIBLE,SLEEP,PEONY,MICROPHONE,TUNE_IN,CHANGE_NAME,REMINDERS,GOLDFISH,VOLUME_SETTING
--

**Comment by Apollon77** [comment]
Bitte sende mir die vollständige nicht abgeschnittene Zeile. Was ist das ein für ein gerät? Such es mal bei den Objekten. Über Info.DeviceType solltest du es finden. 

Was kann das Gerät? Kannst du per alexa App zb per Routinen auf dem Gerät Sprache ausgeben?

**Comment by Apollon77** [comment]
Und am besten schalte in den Adapter es Bestellungen die Push Verbindung ein. Dann kommt die Meldung nur einmal beim adapterstart

**Comment by maxx3105** [comment]
In den Objekten ist das Gerät nicht vorhanden.

Device-type:A2L8KG0CT86ADW (TIMERS_AND_ALARMS,PERSISTENT_CONNECTION,SLEEP,DEREGISTER_DEVICE,MICROPHONE,AMAZON_MUSIC,AUDIO_PLAYER,I_HEART_RADIO,GOLDFISH,PEONY,VOLUME_SETTING,TUNE_IN,DREAM_TRAINING,
--

**Comment by Apollon77** [comment]
Muss es. Schau mal die Echo devices durch da jeweils unter Info.deviceType ...

**Comment by maxx3105** [comment]
Habs gefunden das ist mein MagicMirror bzw AVS auf einem Raspberry Pi.

**Comment by Apollon77** [comment]
Hast du noch die capabilities nicht angeschnitten? Aus dem Info.capabilities state

**Comment by Apollon77** [comment]
Hast Du bitte die Capabilities noch vollständig?!

**Comment by maxx3105** [comment]
KINDLE_BOOKS,DREAM_TRAINING,PEONY,VOLUME_SETTING,CHANGE_NAME,PAIR_BT_SINK,SLEEP,I_HEART_RADIO,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,PERSISTENT_CONNECTION,TUNE_IN,TIMERS_AND_ALARMS,MICROPHONE,AUDIBLE,DEREGISTER_DEVICE,GOLDFISH,AUDIO_PLAYER,REMINDERS,AMAZON_MUSIC

**Comment by Apollon77** [comment]
Ääähm ... noch ne Frage: Was genau ist denn das für EIn Gerät und was kann es? Kann es Kommandos (Sprachausgaben oder so über Routinen in der Alexa-App)?

**Comment by maxx3105** [comment]
Das ist mein RaspberryPi (MagicMirror) den ich per Sprache zusätzlich steuern kann. DIY Projekt.

**Comment by Apollon77** [comment]
Warm closed? Kann er Sprachausgaben ... denke eher nicht

**Comment by Apollon77** [comment]
angeblich kann es TUNE_IN und damit Musik Spielen. Wirklich? Kannst du per Alexa App da Musik drauf abspielen oder eine Routine anlegen die dort eine Sprachausgabe drauf macht?

**Comment by maxx3105** [comment]
kann ich per spracheingabe steuern oder per app.

**Comment by Apollon77** [comment]
Die Frage ist ob SprachAUSGABEN oder andere Kommandos die Du per Routinen definieren kannst tun

**Comment by BSaimer** [comment]
Hallo zusammen,
ich habe ein ähnliches Problem mit meinen GGMM Muliroom-Lautsprecher. Kann es sein, dass es daran liegt, dass die Lautsprecher zwar mit Alexa verbunden sind, jedoch nur auf Knopfdruck aufzeichnen und nicht auf "Alexa" triggern?
Hier noch die Fehlermeldung (eine Meldung pro Gerät):
...
Disabling some commands for device because of unknown type. Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
 Device-type:AVJ116KVBJPMC (MICROPHONE,AUDIBLE,GOLDFISH,DREAM_TRAINING,DEREGISTER_DEVICE,AMAZON_MUSIC,TIMERS_AND_ALARMS,MUSIC_SKILL,PEONY,I_HEART_RADIO,SLEEP,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,CHAN
...

**Comment by WilliamTRiker57** [comment]
Ich habe auch diese Fehlermeldungen, bei den Geräten, die diesen Fehler verursachen handelt es sich um folgende:
AP1F6KUH00XPV -- Stereo-Subwooferpaar
AKPGW064GI9HE -- Firestick 4K
AKOAGQTKAS9YB -- Echo Connect

und bei allen Geräten bzw. Gruppen steht im DeviceTypString Unknown.

Gruß
Uwe

**Comment by Apollon77** [comment]
Bitte keine Doppelpostings!
