### ISSUE TITLE
No datas in history>summary

### ISSUE THREAD

**Issue by tiigaaa** [Apollon77/ioBroker.alexa2#1029]
I have a few routines in the Alexa app and that will be checked from IOBROKER , this worked fine since a few dweeks.
Alexa still answers as she should in the routine but in IOBROKER i will not see any data in the History>summary data filed.
(also no data from other commands, its always blank)

Is this a known Issue?

My server:
Debian11 ESXi
Node.js: v18.16.0
NPM: v9.5.1

Thanks for any feedback. :)

**Comment by Apollon77** [comment]
No, and most likely then it is a change from amazon.

Please enable debug logging, let the initializiation proces finish and then execute such a routine (and tell me what kind of routine) and post the debug log generated after that

**Comment by Apollon77** [comment]
Naja also das Losg ist bissl kurz.

Eine interaktion bsteht an sich aud 3 Daten-Interaktionen. Zuerst wenn du das gerät ansprichst, dann das kommando und dann wenn es wieder aus dem zuhör modus rausgeht. ich hab hier nur das vom "Wake world only"  - also das erste.
Und ja bei dem gibts keine Daten.-

Du kannst im adapter einstellen das er solche "leeren" aktionen ignoriert.

Also bitte nochmal (mehr) log oder

**Comment by Rushmed** [comment]
Ich habe das Problem jetzt auch.
Gestern fingen die Probleme an und heute kommt unter History garnichts mehr an.
![image](https://github.com/Apollon77/ioBroker.alexa2/assets/59259796/d84d2c08-c4c9-43f3-8b10-4c616130de76)

**Comment by chris7topher** [comment]
I have the same problem since yesterday. History is not updating anymore.

**Comment by Fontheweg** [comment]
Bei mir das Gleiche.
Wenn ich alexa2.0.History.#trigger auf true setzte, kommen die Daten. Sonst nicht.
Das Ignorieren der History wenn kein Befehl erkannt wurde habe ich ausgehakt.
Probleme begannen am 30.7. oder 31.7.

**Comment by Fontheweg** [comment]
Noch eine Info - habe es gerade probiert:
In den Settings: 
> Push-Verbindungen verwenden deaktivieren
> History-Aktualisierungsintervall auf 60s (empfohlenes Minimum)

Nun kommt die History wieder ... evtl. hat Amazon an den Pushnotifications geschraubt?

**Comment by Gaspode69** [comment]
Im ioBroker Forum und in einem anderen Issue (das inzwischen geschlossen wurde !?) gibt es elegantere Vorschläge für Workarounds:
https://forum.iobroker.net/topic/64495
 Keine Auto-Updates von Todo/Timer/Wcker/"alexa2.0.History.summary" #1045 

Die Kurzform in Javascript:
`on({id: /alexa2.0.Echo-Devices.*.Player.muted/, change: 'any'}, (obj)=> {
    getState("alexa2.0.History.#trigger", (err, state) => {setStateDelayed("alexa2.0.History.#trigger", state ? !state.val : true, 3000, false);});
});`

**Comment by realwax** [comment]
https://github.com/Apollon77/ioBroker.alexa2/issues/1045#issuecomment-1661588047 Mit Echos klappt das. Alexa App, oder Fire Devices, die keinen Player Kanal haben sieht noch ungut aus. Ggf. kann man die fake anlegen, da auch bei Trigger via App, etwas im Adapter ausgelöst wird. PUSH_Volume, aber kein State gesetzt wird. Das kann @Apollon77 sofort beantworten vermute ich, ob es lohnt "fake" states händisch einzupflegen um den Push abzufangen...

**Comment by realwax** [comment]
Für die NICHT echo dot User. Fire Stick oder App:

Alle Devices, die keinen Player Kanal haben und volume, mute, eq, können mit den Hotfixes nicht versehen werden. Je nachdem wie sich das entwickelt, müsstet ihr einen change request an Ingo @Apollon77 stellen, damit er den Hotfix in den Adapter einbaut. Der Adapter selbst erkennt, wenn auch in der Android App, mit Alexa, oder Button getriggert wird. Folgende Zeile erscheint.

alexa2.0 | 2023-08-02 09:06:53.755 | debug | Alexa-Remote WS-MQTT: Command PUSH_VOLUME_CHANGE: ...

Darauf könnte der Adapter selbst mit einem einstellbaren Delay den trigger auslösen um die History zu aktualisieren. Das wäre dann für alle ein Hotfix, bzw. wie es scheint die einzige Lösung für App und Firestick user. Echo dots klappen mit dem Fix im script. 

Testweise habe ich die fehlenden Kanäle, states angelegt, aber die werden beim Adapter start gecleant und sauber gestaltet (Macht Sinn!) somit braucht es @Apollon77 für changes.

**Comment by Gaspode69** [comment]
Ich persönlich hoffe ja immer noch, dass Amazon den alten Zustand wieder herstellt. Die Ursache für das geänderte Verhalten scheint ja noch nicht bekannt zu sein.

**Comment by Apollon77** [comment]
diplocate to #1045
