### ISSUE TITLE
Unknown command PUSH_LIST_ITEM_CHANGE in Push mode

### ISSUE THREAD

**Issue by Garfonso** [Apollon77/ioBroker.alexa2#103]
The log said to send them to developer:

`2018-09-20 07:23:47.236  - info: alexa2.0 Alexa-Push-Connection Unknown Command PUSH_LIST_ITEM_CHANGE - send to Developer: {"destinationUserId":"A1ECZVUSYI429J","listId":"YW16bjEuYWNjb3VudC5BRjQzWU1VUE5BSVhPWExWVVhQRVdGSlJMRjVBLVNIT1BQSU5HX0lURU0=","eventName":"itemCreated","version":1,"listItemId":"2f588321-37b2-4330-9ce2-c1690bcd2e44"}`

`2018-09-20 07:23:47.285  - info: alexa2.0 Alexa-Push-Connection Unknown Command PUSH_LIST_ITEM_CHANGE - send to Developer: {"destinationUserId":"A9O4CXARLEAH6","listId":"YW16bjEuYWNjb3VudC5BSFJOM1JaSkJRWU9LNldGWDJWWk1IQVFDWFVBLVNIT1BQSU5HX0lURU0=","eventName":"itemCreated","version":1,"listItemId":"2f588321-37b2-4330-9ce2-c1690bcd2e44"}`

`2018-09-20 07:24:13.061  - info: alexa2.0 Alexa-Push-Connection Unknown Command PUSH_LIST_ITEM_CHANGE - send to Developer: {"destinationUserId":"A1ECZVUSYI429J","listId":"YW16bjEuYWNjb3VudC5BRjQzWU1VUE5BSVhPWExWVVhQRVdGSlJMRjVBLVNIT1BQSU5HX0lURU0=","eventName":"itemCreated","version":1,"listItemId":"06ddc872-664f-4e9f-a4d4-a046f80b5cad"}`

`2018-09-20 07:24:13.115  - info: alexa2.0 Alexa-Push-Connection Unknown Command PUSH_LIST_ITEM_CHANGE - send to Developer: {"destinationUserId":"A9O4CXARLEAH6","listId":"YW16bjEuYWNjb3VudC5BSFJOM1JaSkJRWU9LNldGWDJWWk1IQVFDWFVBLVNIT1BQSU5HX0lURU0=","eventName":"itemCreated","version":1,"listItemId":"06ddc872-664f-4e9f-a4d4-a046f80b5cad"}`

They happend, when we added two items to the shopping list. Maybe helpful if lists are supported one day? Otherwise probably to be ignored right now. 
Why are there for commands? Only two items were added. But there are two UserIds. There are two users on our alexas, maybe that's the reason.

**Comment by ldittmar81** [comment]
Hmm... Shopping List Support...

https://github.com/Apollon77/alexa-remote/blob/master/alexa-remote.js#L742

*treudooferwauwaublick*... pleaaaase! :)

**Comment by Apollon77** [comment]
info message should be gone in 2.1 from GitHub
