### ISSUE TITLE
Alexa Adapter terminated

### ISSUE THREAD

**Issue by smarteshome2020** [Apollon77/ioBroker.alexa2#1030]
Hallo,

ich bekomme den Alexa Adapter nicht mehr mit Amazon verbunden. Das Cookie wurde schon mehrfach neu gemacht, Leider geht der Link https://www.gehrig.info/alexa/Alexa.html zur Beschreibung wie dies manuell zu machen ist nicht mehr.
Hinweis: Aufgrund Security Problemen musste ich die 2VA bei Amazon aktivieren, wobei es kurz vorher (ohne 2VA) auch nicht mehr  ging.

Ich bitte um Unterstützung.
Adapter: V 3.23.2
iobroker auf Proxmox
node: v18.16.0
js-controller: 4.0.24

`<html>
<body>

alexa2.0 | 2023-05-29 16:43:23.264 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
alexa2.0 | 2023-05-29 16:43:23.263 | debug | Plugin sentry destroyed
alexa2.0 | 2023-05-29 16:43:22.262 | error | Adapter seems to have issues and crashed three times in a row. Disabling!! Please start again and check logs.
alexa2.0 | 2023-05-29 16:43:22.261 | info | Starting Alexa2 adapter ... it can take several minutes to initialize all data. Please be patient! A done message is logged.
alexa2.0 | 2023-05-29 16:43:22.129 | info | starting. Version 3.23.2 in /opt/iobroker/node_modules/iobroker.alexa2, node: v18.16.0, js-controller: 4.0.24
alexa2.0 | 2023-05-29 16:43:22.019 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
alexa2.0 | 2023-05-29 16:43:22.015 | debug | Plugin sentry Initialize Plugin (enabled=true)
alexa2.0 | 2023-05-29 16:43:21.893 | debug | States connected to redis: 127.0.0.1:9000
alexa2.0 | 2023-05-29 16:43:21.825 | debug | States create User PubSub Client
alexa2.0 | 2023-05-29 16:43:21.825 | debug | States create System PubSub Client
alexa2.0 | 2023-05-29 16:43:21.807 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
alexa2.0 | 2023-05-29 16:43:21.783 | debug | Objects connected to redis: 127.0.0.1:9001
alexa2.0 | 2023-05-29 16:43:21.780 | debug | Objects client initialize lua scripts
alexa2.0 | 2023-05-29 16:43:21.737 | debug | Objects create User PubSub Client
alexa2.0 | 2023-05-29 16:43:21.737 | debug | Objects create System PubSub Client
alexa2.0 | 2023-05-29 16:43:21.735 | debug | Objects client ready ... initialize now
alexa2.0 | 2023-05-29 16:43:21.700 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
alexa2.0 | 2023-05-29 16:43:19.671 | info | Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
alexa2.0 | 2023-05-29 16:43:19.671 | debug | Plugin sentry destroyed
alexa2.0 | 2023-05-29 16:43:19.670 | error | Error: Error while checking Authentication: Error: 401 Unauthorized
alexa2.0 | 2023-05-29 16:43:19.670 | debug | Error from Alexa init: Error while checking Authentication: Error: 401 Unauthorized
alexa2.0 | 2023-05-29 16:43:19.669 | debug | Alexa-Remote: Response: 401 Unauthorized
alexa2.0 | 2023-05-29 16:43:19.480 | debug | Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/bootstrap?version=0","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2023-05-29 16:43:19.479 | debug | Alexa-Remote: cookie was provided
alexa2.0 | 2023-05-29 16:43:19.478 | debug | Alexa-Remote: Use as Base-URL: alexa.amazon.de
alexa2.0 | 2023-05-29 16:43:19.478 | debug | Alexa-Remote: Use as Login-Amazon-URL: amazon.de
alexa2.0 | 2023-05-29 16:43:19.478 | debug | Alexa-Remote: Use as API User-Agent Postfix: ioBroAlexa2/3.23.2
alexa2.0 | 2023-05-29 16:43:19.478 | debug | Alexa-Remote: Use as User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
alexa2.0 | 2023-05-29 16:43:19.477 | debug | Update Devices Configuration Interval: 3601s
alexa2.0 | 2023-05-29 16:43:19.477 | debug | Update Device State Interval: 305s
alexa2.0 | 2023-05-29 16:43:19.477 | debug | Update History Interval: 300s
alexa2.0 | 2023-05-29 16:43:19.476 | info | Starting Alexa2 adapter ... it can take several minutes to initialize all data. Please be patient! A done message is logged.
alexa2.0 | 2023-05-29 16:43:19.341 | info | starting. Version 3.23.2 in /opt/iobroker/node_modules/iobroker.alexa2, node: v18.16.0, js-controller: 4.0.24
alexa2.0 | 2023-05-29 16:43:19.213 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
alexa2.0 | 2023-05-29 16:43:19.211 | debug | Plugin sentry Initialize Plugin (enabled=true)
alexa2.0 | 2023-05-29 16:43:19.089 | debug | States connected to redis: 127.0.0.1:9000
alexa2.0 | 2023-05-29 16:43:19.015 | debug | States create User PubSub Client
alexa2.0 | 2023-05-29 16:43:19.014 | debug | States create System PubSub Client
alexa2.0 | 2023-05-29 16:43:18.995 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
alexa2.0 | 2023-05-29 16:43:18.971 | debug | Objects connected to redis: 127.0.0.1:9001
alexa2.0 | 2023-05-29 16:43:18.968 | debug | Objects client initialize lua scripts
alexa2.0 | 2023-05-29 16:43:18.922 | debug | Objects create User PubSub Client
alexa2.0 | 2023-05-29 16:43:18.922 | debug | Objects create System PubSub Client
alexa2.0 | 2023-05-29 16:43:18.921 | debug | Objects client ready ... initialize now
alexa2.0 | 2023-05-29 16:43:18.886 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
alexa2.0 | 2023-05-29 16:40:39.283 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
alexa2.0 | 2023-05-29 16:40:39.282 | debug | Plugin sentry destroyed
alexa2.0 | 2023-05-29 16:40:38.281 | error | Adapter seems to have issues and crashed three times in a row. Disabling!! Please start again and check logs.
alexa2.0 | 2023-05-29 16:40:38.280 | info | Starting Alexa2 adapter ... it can take several minutes to initialize all data. Please be patient! A done message is logged.
alexa2.0 | 2023-05-29 16:40:38.147 | info | starting. Version 3.23.2 in /opt/iobroker/node_modules/iobroker.alexa2, node: v18.16.0, js-controller: 4.0.24
alexa2.0 | 2023-05-29 16:40:38.021 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
alexa2.0 | 2023-05-29 16:40:38.018 | debug | Plugin sentry Initialize Plugin (enabled=true)
alexa2.0 | 2023-05-29 16:40:37.881 | debug | States connected to redis: 127.0.0.1:9000
alexa2.0 | 2023-05-29 16:40:37.810 | debug | States create User PubSub Client
alexa2.0 | 2023-05-29 16:40:37.809 | debug | States create System PubSub Client
alexa2.0 | 2023-05-29 16:40:37.792 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
alexa2.0 | 2023-05-29 16:40:37.768 | debug | Objects connected to redis: 127.0.0.1:9001
alexa2.0 | 2023-05-29 16:40:37.766 | debug | Objects client initialize lua scripts
alexa2.0 | 2023-05-29 16:40:37.723 | debug | Objects create User PubSub Client
alexa2.0 | 2023-05-29 16:40:37.722 | debug | Objects create System PubSub Client
alexa2.0 | 2023-05-29 16:40:37.721 | debug | Objects client ready ... initialize now
alexa2.0 | 2023-05-29 16:40:37.685 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
alexa2.0 | 2023-05-29 16:40:34.572 | debug | Alexa-Remote: Sending Request with {"host":"alexa-comms-mobile-service.amazon.com","path":"/accounts","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2023-05-29 16:40:34.571 | debug | Alexa-Remote: No authentication check needed (time elapsed 141)
alexa2.0 | 2023-05-29 16:40:34.571 | debug | Alexa-Remote: Change Base URL for API calls to na-api-alexa.amazon.de
alexa2.0 | 2023-05-29 16:40:34.570 | debug | Alexa-Remote: Response: {"alexaApiUrl":"https://api.amazonalexa.com","awsRegion":"us-east-1","retailDomain":"amazon.com","retailUrl":"https://www.amazon.com","skillsStoreUrl":"https://skills-store-na.amazon.de","websiteApiUrl":"https://na-api-alexa.amazon.de","websiteUrl":"https://alexa.amazon.com"}
alexa2.0 | 2023-05-29 16:40:34.431 | debug | Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/endpoints","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2023-05-29 16:40:34.430 | debug | Alexa-Remote: Authentication checked: true

</body>
</html>`

**Comment by smarteshome2020** [comment]
Hello, is the adapter dead?

**Comment by Apollon77** [comment]
Did you hear about that even open source developers have private lifes? Did you know that currently is a usual vacation time? Asking that question 3 days after a post is a bit short, or?

But because I'm a really nice and supportive guy I decided to still answer you directly on day 1 of my 10 day vacation. Please delete all files /opt/iobroker/node_modules/iobroker.alexa2/crashCheck-* ... then star the adapter again.they get a new cookie via prox login

**Comment by smarteshome2020** [comment]
@Apollon77 , ich bin nur etwas verzweifelt und Danke Dir für deine Zeit die du in die ganzen Adapter und iob investierst. Bitte verstehe mich nicht falsch, ich versuche schon seit Wochen das Problem in den Griff zu bekommen und egal über welchen weg, Discord, FB, iob Forum bekomme ich "gefühlt" keine Hilfe. Das du das Thema jetzt auf "closed" gesetzt hast kann ich zwar deinerseits verstehen, allerdings hilft es mir weniger. Es lag mir absolut fern dir zu nahe zu treten und natürlich geht das RL vor.

**Comment by Apollon77** [comment]
Hi,

am End emacht halt der Ton die Musik, aber all fine.

Naja im ersten schritt steht die Lösung für den "uups adapter gecrasht ich stoppe mal um nicht in eine restart loop zu laufen" oben drin. Und darum gings hier in der Frage. mehr weiss ich ja nicht.

Falls es darum geht das auch nach einem neuen Cookie holen ein 401 Fehler kommt dann wäre das ein "ich bräuchte ein vollständifges Debug log vom cookie holen und danach ...

**Comment by smarteshome2020** [comment]
Hi,

sorry für die falsche Musik :-) 

Ich habe mehrere Versuche unternommen um das Cookie zu erhalten und meiner Meinung nach klappt das auch. Wenn ich einen anderen Amazon Acc verwendet wird der Adapter "grün". Bei meinem Acc habe ich ein wechelndes Verhalten. Mal 404 und dann keine 404 Meldungen mehr aber er bleibt auf "rot" mit den oben geposteten Meldungen. Aber über welchen weg darf ich dir die Daten schicken? Wenn ich es richtig gesehen haben steht das einige sensible Dinge drin :-)

**Comment by Apollon77** [comment]
Gern per E-Mail an iobroker@fischer-ka.de mit dem nei angelegten GitHub issue wegen den 404/401/whatever Fehlerals Referenz drin

**Comment by smarteshome2020** [comment]
Danke, gewünschte Daten wurden per Mail geschickt.

**Comment by smarteshome2020** [comment]
The Error was found. My Account use the wrong marketplace. Wrong= amazon.com, change to amazon.de and the Adapter work!
Thx for the support!

**Comment by Apollon77** [comment]
Interesting ... need to check log again . I did not noticed that
