### ISSUE TITLE
Lists don't update

### ISSUE THREAD

**Issue by maltdorfer** [Apollon77/ioBroker.alexa2#1032]
**Describe the bug**  
Lists don't update. They only update when I restart the adapter completely, but not at all afterwards.

**To Reproduce**  
1. I add an item on my alexa shopping list through the alexa app
2. I check if a new item will be created in the iobroker object (Lists/Shopping_List/items).
3. I restart the apdapter, the new item shows up in iobroker
4. I also waited already more than 24 hours, nothing changed.
5. I tried to use manual sync instead of push also, no changes.

**Expected behavior**  
I was expecting it updates the shopping list right ahead or at least in the timeframe of a manual pull

**Versions:**  
 - Adapter version: 3.23.2
 - JS-Controller version: 4.0.24
 - Node version: v18.16.0
 - Operating system: linux

**Comment by Apollon77** [comment]
Please verify that the push connection in enabled and also working and that log is not stating any errors regardning the push connection. Please show a debug logfile of a listchange via voice

**Comment by maltdorfer** [comment]
OK, it seems like the push connection is not working.

`

alexa2.0 | 2023-06-16 13:36:17.222 | info | Alexa-Push-Connection disconnected - retry: Retry Connection in 55s
-- | -- | -- | --
alexa2.0 | 2023-06-16 13:35:26.553 | info | Alexa-Push-Connection disconnected - retry: Retry Connection in 50s
alexa2.0 | 2023-06-16 13:34:40.769 | info | Alexa-Push-Connection disconnected - retry: Retry Connection in 45s

`

**Comment by Apollon77** [comment]
Without push connection no updates ... check Readme for instructions on how to fix that
