### ISSUE TITLE
Smart-Home-Devices mit Inhalt füllen

### ISSUE THREAD

**Issue by heitec11** [Apollon77/ioBroker.alexa2#1035]
Die Opjektliste bei Smart-Home-Device am Beispiel "Klima" ist zwar definiert, aber ohne Werte.

![alexa2_klima](https://github.com/Apollon77/ioBroker.alexa2/assets/44260876/b195d2fe-bd93-4313-b460-28181024303b)

Wie könnten Temperatur Werte oder Zustände angezeigt werden?

**Comment by heitec11** [comment]
Laut Changelog des IoT Adapters gibt es Alexa V3

2.0.2 (2023-06-05)
    (bluefox) Added support for amazon alexa v3

Könnte das eine Verbesserung bei der Amazon Anbindung bringen?

**Comment by Apollon77** [comment]
Bitte nichts vermischen! Alexa2 Adapter redet "generisch" mit Amazon. iot Adapter stellt ioBroker Geräte für Alexa zur Verfügung.

Was ist denn "Klima" für ein gerät? Ist das ein ipBroker.eigenes Device über den iot Skill? Dann werden da in Alexa2 NIE werte kommen weilk die hast Du ja schon in ioBroker anders wo.
Falls es ein gerät über einen anderen Skill ist brauche ich ein vollständiges Alexa2-Debug Log vom Start an.

**Comment by Apollon77** [comment]
PS: Bzw ... naja löse doch mal den "query" state aus ... Kommen dann Daten? Falls ja dann liegt es daran das du "includeInqueryAll" auf false hast. Auf true setzen und dann sollte das im eingestellten Interval aktualisiert werden

**Comment by heitec11** [comment]
Klima ist eine TCL - Split Klimaanlage mit dem TCL Skill.

"includeInqueryAll" war der Durchbruch.
Vielen Dank für den Tipp.
