### ISSUE TITLE
Wecker/Alarm nur nach Neustart der Instanz angelegt/geleert

### ISSUE THREAD

**Issue by Makobe** [Apollon77/ioBroker.alexa2#1036]
Hallo, ich habe Scripte, welche auf das Anlegen der Wecker reagieren. Dabei ist aufgefallen, dass diese nicht laufen.

Der Adapter legt automatisch keine Alarme/Wecker mehr an oder bereinigt diese wenn sie entfernt wurden. Erst bei einem Neustart der Instanz wird dies ausgeführt. 
Bereits durchgeführte Maßnahmen ohne Besserung:
- Alle Geräte neu gebootet
- Cookie erneuert
- verwenden der Pushverbindung
- Scripte deaktiviert, die jedoch nur auslesen und nichts "steuern" aber man weiß ja nie..

Anbei einmal das Log, welches nach einem direkten Neustart des Adapters ist. In laufender Instanz und neu angelegtem Wecker erscheint nichts im Log.
[log.txt](https://github.com/Apollon77/ioBroker.alexa2/files/11955503/log.txt)

**Comment by Apollon77** [comment]
Interessant ist ein Log von dem was nicht geht - also dem anlegen eines Weckers. Diese werden im Notrmal fall von Amazon gemeldet über die Push verbindung ... das log sollte das also zeigen ... wenn das fehlt dann kann der Adapter nichts tun.

**Comment by Makobe** [comment]
Das gestaltet sich schwierig, da bei laufender Instanz und stellen eines Weckers nichts passiert.
Leider auch kein Eintrag im Log, weder über Sprache noch über App gestellter Wecker.

**Comment by Makobe** [comment]
Soeben bemerkt, dass ein stellen des Weckers über Sprachbefehl funktioniert und auch eingetragen wird. Jedoch beim stellen über die App nicht funktioniert. Über App ist nichts im Log zu sehen über Sprachbefehl schon.

**Comment by Apollon77** [comment]
Hm ... dann warte mal paar tage ob Amazon was kaputt gemacht hat

**Comment by senger1985** [comment]
Gerade selbst mal getestet, da irgendwas mit meinen Weckern nicht funktioniert hat.
Sie werden tatsächlich nicht direkt angelegt, aber nach wenigen Sekunden/Minuten tauchen sie dann auf.
(Wecker habe ich über die App neu angelegt)

**Comment by Makobe** [comment]
Also bei mir passiert über die App leider gar nichts. Wecker seit gestern gestellt, wird jedoch nicht angezeigt.
Vielleicht hat Amazon ja wieder experimentiert. Daher warte ich mal ab. Über Sprachbefehl funktioniert zum Glück noch alles.

**Comment by sansonifabio** [comment]
Ich kann dieses Problem bestätigen im Log steht nix. 
Es scheint so das über die Push Verbindung keine Änderungen reinkommen über die Datenpunkte vom Wecker erst nach Neustart wird es übernommen.

**Comment by Apollon77** [comment]
duplicate #1045
