### ISSUE TITLE
Set log level to "time out" to WARN instead of INFO?

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#1037]
I had a problem, where sending text to alexa2 announcement sometimes worked immediately and sometimes it took a while till the message was aired.
Recenty I found out (when I set the adapter to DEBUG) that there was a timeout occuring, ie. I sent too many requests to alexa, too fast... O:)
Now I wonder, if it would make sense if this message would be spit out as WARN instead of INFO, so that it gets noticed in more case?
I bet at least in mine it would have, as I seem to be quite sensitive to warnings that show up in my logs. =)

BTW, is there a suggested delay time to commands send to Alexa?
Maybe I have to add some here, to avoid "race conditions" like this in the future. Thanks. 8)

**Comment by Apollon77** [comment]
Can you tell me exactly which logline you refer to?

**Comment by padrino-x** [comment]
Uff, da muss ich erstmal wieder schauen/es reproduzieren. =)
Also, es geht darum, wenn man zu schnell 2 Kommandos an Alexa über den Adapter schickt, z.B. 2x speak, dann kann es sein, dass der zweit von amazon geblockt wird.
Die Info kommt zwar ins Log, aber nur als Info, sprich geht leicht unter, denke es sollte evtl. eher warn sein, damit es hervorsticht und man es schneller bemerkt um dannn evtl. seine scripte entprechend zu fixen und ein paar delays einzuplanen... :)

**Comment by Apollon77** [comment]
Please reopen or open new with details
