### ISSUE TITLE
Echo Show 5 3te Generation

### ISSUE THREAD

**Issue by CommanderXXL** [Apollon77/ioBroker.alexa2#1040]
I'd like to report the requested information for a currently not supported new Echo device:
Echo Show 5 3rd Generation:

Device-type:A11QM4H9HGV71H - Echo BVB (SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,SUPPORTS_SOFTWARE_VERSION,DREAM_TRAINING,SIRIUSXM,TUNE_IN,CUSTOM_ALARM_TONE,TUPLE,ADAPTIVE_LISTENING,SUPPORTS_LOCALE_SWITCH,EQUALIZER_CONTROLLER_TREBLE,FLASH_BRIEFING,ALEXA_PRESENCE,PAIR_BT_SINK,AUDIO_PLAYER,LEMUR_ALPHA,TUPLE_CATEGORY_C,EQUALIZER_CONTROLLER_BASS,DISPLAY_BRIGHTNESS_ADJUST,MICROPHONE,LIVE_VIEW,AUDIO_CONTROLS,KINDLE_BOOKS,SALMON,EARCONS,CLOCK_FORMAT_24_HR,TAP_GESTURES_SINGLE_TAP,SHARKNADO,TIDAL,DISPLAY_ADAPTIVE_BRIGHTNESS,EQUALIZER_CONTROLLER_MIDRANGE,PANDORA,DIALOG_INTERFACE_VERSION,EFDCARDS,REMINDERS,SOUND_SETTINGS,SUPPORT_CALENDAR_ALERT,TIMERS_AND_ALARMS,CHANGE_NAME,DEEZER,AUDIBLE,ASCENDING_ALARM_VOLUME,VOLUME_SETTING,ALEXA_VOICE,DS_VOLUME_SETTING,DISPLAY_POWER_TOGGLE,APPLE_MUSIC,SET_LOCALE,VOICE_TRAINING,BT_PAIRING_FLOW_V2,AMAZON_MUSIC,I_HEART_RADIO,GUARD_EARCON,TAP_GESTURES,MUSIC_SKILL,GOLDFISH,FAR_FIELD_WAKE_WORD,DEREGISTER_DEVICE,SLEEP,SET_TIME_ZONE,SUPPORTS_LOCALE,SPEECH_RECOGNIZER_USS,MULTI_WAKEWORDS_SUPPORTED,ALEXA_GESTURES,PERSISTENT_CONNECTION,TIMERS_ALARMS_NOTIFICATIONS_VOLUME)

**Comment by Apollon77** [comment]
Thank you
