### ISSUE TITLE
Show Temperature on devices with sensor in info

### ISSUE THREAD

**Issue by qwestermaier** [Apollon77/ioBroker.alexa2#1041]
Newer Devices (eg. Echo Dot Gen 5) have a built in temperature-sensor
The temperature can be seen in device-settings in the alexa-app (see screenshot)

it would be nice to see the value in the info-section to be able use it to control heating/cooling-solutions.

Thanks a lot!
I really love you work!

Regards
Quirin

![Screenshot_20230717_215702_Amazon Alexa](https://github.com/Apollon77/ioBroker.alexa2/assets/38330880/5453bd8f-56da-4f5e-8c97-5c22f4b78efe)

**Comment by Apollon77** [comment]
It should be available in the smart home devices section when you also query them and have them activated. Did you checked there?

**Comment by qwestermaier** [comment]
Hi Ingo,

Thanks for your response,
I did not check that before. But I checked it just now and there is nor value (null)...
![grafik](https://github.com/Apollon77/ioBroker.alexa2/assets/38330880/eef92fb9-0508-4337-a6d5-28c00c07f033)

I just rechecked my Alexa-app and there it shows 24.5°C.

I have 3 devices with a temperature-sensor, and none of of theme shows a value (all null)...


IoBroker is running Alexa-adapter 3.23.2.


Regards
Quirin

**Comment by piatho** [comment]
> Hi Ingo,
> 
> Thanks for your response, I did not check that before. But I checked it just now and there is no value (null)... ![grafik](https://user-images.githubusercontent.com/38330880/255513897-eef92fb9-0508-4337-a6d5-28c00c07f033.png)
> 
> I just rechecked my Alexa-app and there it shows 24.5°C.
> 
> I have 3 devices with a temperature-sensor, and none of them shows a value (all null)...
> 
> IoBroker is running Alexa-adapter 3.23.2.
> 
> Regards Quirin

Ich habe die selbe Situation. Insbesondere der detection state (der neue ultraschall-Sensor) wäre für mich auch schön, wenn direkt im IObroker abrufbar wäre

**Comment by piatho** [comment]
Danke. Fällt dann wohl in die Kategorie "wer lesen kann, ist klar im Vorteil". Wenn ich den flag "#includeInAllQuery auf true für meinen EchoDot setze, bekomme ich die Daten. 

Die Routine habe ich mir auch als Lösung überlegt. Ich versuche erstmal zu verstehen, wie der UltraSound Sensor funktioniert. Erwartet hätte ich, das er konstant "true" setzt solange er Bewegung misst. Scheint aber nicht der Fall zu sein. Er löst bei mir nur aus, wenn lange keine Bewegung bemerkt wurde. Ich muss also im IOBROKER auf eine Kombination aus false und true notes reagieren.

**Comment by qwestermaier** [comment]
ich seh schon, ich dachte ich schreib das alles auf englisch damit das andere vielleicht auch verstehen... aber gut... is mir auch lieber so...

also erstmal, danke dir :-) 
hat einwandfrei funktioniert...

cool dass du dir die Zeit nimmt dich mit so blöden Anfragen zu beschäftigen und immer noch freundlich zu bleiben :-)


Kurze Frage noch, wie oft aktualisiert das?
Der Rest meiner Sensoren wird alle 30 Sekunden aktualisiert...
Trifft das auch auf diese Werte zu?

Für eine Steuerung der Fussbodenheizung reicht das absolut, da würde vermutlich sogar einmal alle 30 min reichen...

Danke und viele Grüße
Quirin

**Comment by Apollon77** [comment]
> Kurze Frage noch, wie oft aktualisiert das?

So oft wie du das interval ind er Adapter-Konfiguration einstellst ... gibt aber Minimum-Werte!
