### ISSUE TITLE
IO - Broker erkennt von Alexa gestartete Routinen plötzlich nicht mehr

### ISSUE THREAD

**Issue by RoHo83** [Apollon77/ioBroker.alexa2#1046]
Hallo,

Von einem Tag auf den anderen werden die über Alexa gestarteten Routinen nicht mehr im IO-Broker erkannt. Es wurde kein Update o.ä. ausgeführt. In der Alexa App wird die Routine als ausgeführt erkannt (Protokoll). Aber der Status der Routine ändert sich nicht mehr im IO-Broker Objekt, der letzte Sprachbefehl befindet sich auch nicht im Speak Objekt. Nach dem Start der Alexa Instanz zeigt sich keine Fehlermeldung. Alle Objekte von allen Alexa Geräten im Netzwerk werden eingelesen und sind verfügbar.  Eine Deinstallation und Neuinstallation des Adapters hat keine Veränderung gebracht. Ich hoffe ihr könnt mir helfen. 
Danke

**Versions:**  
starting. Version 3.23.2 in /opt/iobroker/node_modules/iobroker.alexa2, node: v16.17.1, js-controller: 4.0.24

![image](https://github.com/Apollon77/ioBroker.alexa2/assets/137434475/24dbcf53-fcfc-410c-8dbe-356d68b35dbd)

**Comment by heikowe** [comment]
kann ich bestätigen, bei mir exakt das gleiche Problem

**Comment by tiigaaa** [comment]
Hab ich auch...

**Comment by TheIncredibleHorge** [comment]
Bei mir ebenfalls

**Comment by m0rph2k** [comment]
wird warscheinlich das gleiche sein wie hier 
https://github.com/Apollon77/ioBroker.alexa2/issues/1045

**Comment by Apollon77** [comment]
Exakt, duplicate weil keine History Infos mehr kommen
