### ISSUE TITLE
Anmeldung nicht möglich

### ISSUE THREAD

**Issue by Lucas34660** [Apollon77/ioBroker.alexa2#1047]
Moin zusammen,

ich habe leider aktuell das Problem, dass die Anmeldung nicht funktioniert. Wenn ich den link aus der Instanz dazu starte und meine Zugangsdaten eingebe, kommt danach die Abfrage eines Codes der mir per SMS zugeschickt wird. Gebe ich den ein, komme ich auf eine Amazonseite mit "Seite nicht gefunden" und die Verbindung steht danach nicht von der Instanz zu Amazon.

Alexa2 Version: v3.23.2

Kann mir da wer weiterhelfen oder hat einen Ansatz für mich? 

Vielen Dank

Grüße
Lucas

**Comment by amnesia106** [comment]
`<html>
<body>


alexa2.0 | 2023-08-08 06:14:44.763 | debug | Redirect: Final Location ----> http://192.168.2.8:45121/www.amazon.com/404
-- | -- | -- | --
alexa2.0 | 2023-08-08 06:14:44.762 | debug | Redirect: Original Location ----> /404
alexa2.0 | 2023-08-08 06:14:44.762 | debug | Alexa-Cookie: Cookies handled: "grafana_session_expiry=1690361860; grafana_session=7037a6c09eadf3fced4dc2ffeb74e18c; motion_detected_4=false; monitor_info_4=; motion_detected_5=false; monitor_info_5=; monitor_info_2=; capture_fps_4=1.0; motion_detected_2=false; capture_fps_5=1.0; capture_fps_2=1.0; session-id=135-7582457-9803759; ubid-main=134-0756001-6046326; session-token=\"JyvHIIbIPA4lmxIF5qrmoJA/9fPoTm21STqA2vQClLBkl48+Pboph/1o3WU/R8B/jrMOckXHGMyrgK4Beoex0Mlk4K6A9h1F+Bjk1y8vZvRSwqdMwsre+kyHQWPH8nINnQEcqBguJfGS/RjhbNr5eVJf3C5XqIOsMQ3HbcwRSw5PSxkDCvw/nZvG3pk+QKfTOH8dO40FuMMwDzYb6zoGTloQQ4RfFn6CSjqcJwcs/5I=\"; csm-hit=tb:DVPMBVX008VGDSVDWKEG+s-DVPMBVX008VGDSVDWKEG\|1691467922584&t:1691467922584&adb:adblk_yes; session-id-time=2322188077l; frc=nfqitj/hoctqQKduo5V2o/dIRj2cwoZoJRlCU9SSBL9h1ZFkNVCxy/CCZk467Bzh+/gbxnMSxdHqwWbPfFxBhwdSYar4dZh6E0UtgLdUwzt7YJxjQ9VJ8IEAEHCkz1NtBRxeaYJdsGGz98skVQv9KVVWQN750SZlZSjMYdgw614nH3YWDxhwnBQ8XTN7DREE5qzjsXTndTEOq41NhHYnQ5fM9MqOPea0JJnqQ3ZYy0i8eH0jMDYusa/tLaR/hGtX+YypHkc0QdblNI7vifb13BkA1UNVmVpiKfi9dRC/zdRMsniGwh3+i1azMkMxjr+CNGzz8B+IK2F1Ym7s3xMt3YAwHWcYtW0ef284Rl76HLUj5zCAufzvHJ2QyiupTecwSXJXnW87M3O41DLA6UyZgHZk9NyBdDOwMg==; map-md=eyJkZXZpY2VfdXNlcl9kaWN0aW9uYXJ5IjpbXSwiZGV2aWNlX3JlZ2lzdHJhdGlvbl9kYXRhIjp7InNvZnR3YXJlX3ZlcnNpb24iOiIxIn0sImFwcF9pZGVudGlmaWVyIjp7ImFwcF92ZXJzaW9uIjoiMi4yLjQ4NTQwNyIsImJ1bmRsZV9pZCI6ImNvbS5hbWF6b24uZWNobyJ9fQ==; io=HLrfyr1gOttY6NjWAAAo; grafana_session_expiry=1690361860; grafana_session=7037a6c09eadf3fced4dc2ffeb74e18c; motion_detected_4=false; monitor_info_4=\"\"; motion_detected_5=false; monitor_info_5=\"\"; monitor_info_2=\"\"; capture_fps_4=1.0; motion_detected_2=false; io=HLrfyr1gOttY6NjWAAAo; capture_fps_5=1.0; capture_fps_2=1.0; session-id=135-7582457-9803759; ubid-main=134-0756001-6046326; session-token=\"JyvHIIbIPA4lmxIF5qrmoJA/9fPoTm21STqA2vQClLBkl48+Pboph/1o3WU/R8B/jrMOckXHGMyrgK4Beoex0Mlk4K6A9h1F+Bjk1y8vZvRSwqdMwsre+kyHQWPH8nINnQEcqBguJfGS/RjhbNr5eVJf3C5XqIOsMQ3HbcwRSw5PSxkDCvw/nZvG3pk+QKfTOH8dO40FuMMwDzYb6zoGTloQQ4RfFn6CSjqcJwcs/5I=\"; csm-hit=tb:GSA8KC19N4KPWXASD8BA+s-GSA8KC19N4KPWXASD8BA\|1691468069321&t:1691468069321&adb:adblk_yes; session-id-time=2322188077l; frc=nfqitj/hoctqQKduo5V2o/dIRj2cwoZoJRlCU9SSBL9h1ZFkNVCxy/CCZk467Bzh+/gbxnMSxdHqwWbPfFxBhwdSYar4dZh6E0UtgLdUwzt7YJxjQ9VJ8IEAEHCkz1NtBRxeaYJdsGGz98skVQv9KVVWQN750SZlZSjMYdgw614nH3YWDxhwnBQ8XTN7DREE5qzjsXTndTEOq41NhHYnQ5fM9MqOPea0JJnqQ3ZYy0i8eH0jMDYusa/tLaR/hGtX+YypHkc0QdblNI7vifb13BkA1UNVmVpiKfi9dRC/zdRMsniGwh3+i1azMkMxjr+CNGzz8B+IK2F1Ym7s3xMt3YAwHWcYtW0ef284Rl76HLUj5zCAufzvHJ2QyiupTecwSXJXnW87M3O41DLA6UyZgHZk9NyBdDOwMgx==; map-md=eyJkZXZpY2VfdXNlcl9kaWN0aW9uYXJ5IjpbXSwiZGV2aWNlX3JlZ2lzdHJhdGlvbl9kYXRhIjp7InNvZnR3YXJlX3ZlcnNpb24iOiIxIn0sImFwcF9pZGVudGlmaWVyIjp7ImFwcF92ZXJzaW9uIjoiMi4yLjQ4NTQwNyIsImJ1bmRsZV9pZCI6ImNvbS5hbWF6b24uZWNobyJ9fQ==; grafana_session_expiry=1690361860; grafana_session=7037a6c09eadf3fced4dc2ffeb74e18c; motion_detected_4=false; monitor_info_4=\"\"; motion_detected_5=false; monitor_info_5=\"\"; monitor_info_2=\"\"; capture_fps_4=1.0; motion_detected_2=false; io=HLrfyr1gOttY6NjWAAAo; capture_fps_5=1.0; capture_fps_2=1.0; session-id=135-7582457-9803759; ubid-main=134-0756001-6046326; session-token=\"JyvHIIbIPA4lmxIF5qrmoJA/9fPoTm21STqA2vQClLBkl48+Pboph/1o3WU/R8B/jrMOckXHGMyrgK4Beoex0Mlk4K6A9h1F+Bjk1y8vZvRSwqdMwsre+kyHQWPH8nINnQEcqBguJfGS/RjhbNr5eVJf3C5XqIOsMQ3HbcwRSw5PSxkDCvw/nZvG3pk+QKfTOH8dO40FuMMwDzYb6zoGTloQQ4RfFn6CSjqcJwcs/5I=\"; csm-hit=tb:GSA8KC19N4KPWXASD8BA+s-GSA8KC19N4KPWXASD8BA\|1691468069321&t:1691468069321&adb:adblk_yes; session-id-time=2322188077l; frc=nfqitj/hoctqQKduo5V2o/dIRj2cwoZoJRlCU9SSBL9h1ZFkNVCxy/CCZk467Bzh+/gbxnMSxdHqwWbPfFxBhwdSYar4dZh6E0UtgLdUwzt7YJxjQ9VJ8IEAEHCkz1NtBRxeaYJdsGGz98skVQv9KVVWQN750SZlZSjMYdgw614nH3YWDxhwnBQ8XTN7DREE5qzjsXTndTEOq41NhHYnQ5fM9MqOPea0JJnqQ3ZYy0i8eH0jMDYusa/tLaR/hGtX+YypHkc0QdblNI7vifb13BkA1UNVmVpiKfi9dRC/zdRMsniGwh3+i1azMkMxjr+CNGzz8B+IK2F1Ym7s3xMt3YAwHWcYtW0ef284Rl76HLUj5zCAufzvHJ2QyiupTecwSXJXnW87M3O41DLA6UyZgHZk9NyBdDOwMgx==; map-md=eyJkZXZpY2VfdXNlcl9kaWN0aW9uYXJ5IjpbXSwiZGV2aWNlX3JlZ2lzdHJhdGlvbl9kYXRhIjp7InNvZnR3YXJlX3ZlcnNpb24iOiIxIn0sImFwcF9pZGVudGlmaWVyIjp7ImFwcF92ZXJzaW9uIjoiMi4yLjQ4NTQwNyIsImJ1bmRsZV9pZCI6ImNvbS5hbWF6b24uZWNobyJ9fQ==; grafana_session_expiry=1690361860; grafana_session=7037a6c09eadf3fced4dc2ffeb74e18c; motion_detected_4=false; monitor_info_4=\"\"; motion_detected_5=false; monitor_info_5=\"\"; monitor_info_2=\"\"; capture_fps_4=1.0; motion_detected_2=false; io=HLrfyr1gOttY6NjWAAAo; capture_fps_5=1.0; capture_fps_2=1.0; session-id=135-7582457-9803759; ubid-main=134-0756001-6046326; session-token=\"JyvHIIbIPA4lmxIF5qrmoJA/9fPoTm21STqA2vQClLBkl48+Pboph/1o3WU/R8B/jrMOckXHGMyrgK4Beoex0Mlk4K6A9h1F+Bjk1y8vZvRSwqdMwsre+kyHQWPH8nINnQEcqBguJfGS/RjhbNr5eVJf3C5XqIOsMQ3HbcwRSw5PSxkDCvw/nZvG3pk+QKfTOH8dO40FuMMwDzYb6zoGTloQQ4RfFn6CSjqcJwcs/5I=\"; csm-hit=tb:GSA8KC19N4KPWXASD8BAx+s-GSA8KC19N4KPWXASD8BA\|1691468069321&t:1691468069321&adb:adblk_yes; session-id-time=2322188077l; frc=nfqitj/hoctqQKduo5V2o/dIRj2cwoZoJRlCU9SSBL9h1ZFkNVCxy/CCZk467Bzh+/gbxnMSxdHqwWbPfFxBhwdSYar4dZh6E0UtgLdUwzt7YJxjQ9VJ8IEAEHCkz1NtBRxeaYJdsGGz98skVQv9KVVWQN750SZlZSjMYdgw614nH3YWDxhwnBQ8XTN7DREE5qzjsXTndTEOq41NhHYnQ5fM9MqOPea0JJnqQ3ZYy0i8eH0jMDYusa/tLaR/hGtX+YypHkc0QdblNI7vifb13BkA1UNVmVpiKfi9dRC/zdRMsniGwh3+i1azMkMxjr+CNGzz8B+IK2F1Ym7s3xMt3YAwHWcYtW0ef284Rl76HLUj5zCAufzvHJ2QyiupTecwSXJXnW87M3O41DLA6UyZgHZk9NyBdDOwMg==; map-md=eyJkZXZpY2VfdXNlcl9kaWN0aW9uYXJ5IjpbXSwiZGV2aWNlX3JlZ2lzdHJhdGlvbl9kYXRhIjp7InNvZnR3YXJlX3ZlcnNpb24iOiIxIn0sImFwcF9pZGVudGlmaWVyIjp7ImFwcF92ZXJzaW9uIjoiMi4yLjQ4NTQwNyIsImJ1bmRsZV9pZCI6ImNvbS5hbWF6b24uZWNobyJ9fQ==; grafana_session_expiry=1690361860; grafana_session=7037a6c09eadf3fced4dc2ffeb74e18c; motion_detected_4=false; monitor_info_4=\"\"; motion_detected_5=false; monitor_info_5=\"\"; monitor_info_2=\"\"; capture_fps_4=1.0; motion_detected_2=false; io=HLrfyr1gOttY6NjWAAAo; capture_fps_5=1.0; capture_fps_2=1.0; session-id=135-7582457-9803759; ubid-main=134-0756001-6046326; session-token=\"JyvHIIbIPA4lmxIF5qrmoJA/9fPoTm21STqA2vQClLBkl48+Pboph/1o3WU/R8B/jrMOckXHGMyrgK4Beoex0Mlk4K6A9h1F+Bjk1y8vZvRSwqdMwsre+kyHQWPH8nINnQEcqBguJfGS/RjhbNr5eVJf3C5XqIOsMQ3HbcwRSw5PSxkDCvw/nZvG3pk+QKfTOH8dO40FuMMwDzYb6zoGTloQQ4RfFn6CSjqcJwcs/5I=\"; csm-hit=tb:GSA8KC19N4KPWXASD8BAx+s-GSA8KC19N4KPWXASD8BA\|1691468069321&t:1691468069321&adb:adblk_yes; session-id-time=2322188077l; frc=nfqitj/hoctqQKduo5V2o/dIRj2cwoZoJRlCU9SSBL9h1ZFkNVCxy/CCZk467Bzh+/gbxnMSxdHqwWbPfFxBhwdSYar4dZh6E0UtgLdUwzt7YJxjQ9VJ8IEAEHCkz1NtBRxeaYJdsGGz98skVQv9KVVWQN750SZlZSjMYdgw614nH3YWDxhwnBQ8XTN7DREE5qzjsXTndTEOq41NhHYnQ5fM9MqOPea0JJnqQ3ZYy0i8eH0jMDYusa/tLaR/hGtX+YypHkc0QdblNI7vifb13BkA1UNVmVpiKfi9dRC/zdRMsniGwh3+i1azMkMxjr+CNGzz8B+IK2F1Ym7s3xMt3YAwHWcYtW0ef284Rl76HLUj5zCAufzvHJ2QyiupTecwSXJXnW87M3O41DLA6UyZgHZk9NyBdDOwMgx==; map-md=eyJkZXZpY2VfdXNlcl9kaWN0aW9uYXJ5IjpbXSwiZGV2aWNlX3JlZ2lzdHJhdGlvbl9kYXRhIjp7InNvZnR3YXJlX3ZlcnNpb24iOiIxIn0sImFwcF9pZGVudGlmaWVyIjp7ImFwcF92ZXJzaW9uIjoiMi4yLjQ4NTQwNyIsImJ1bmRsZV9pZCI6ImNvbS5hbWF6b24uZWNobyJ9fQx=="
alexa2.0 | 2023-08-08 06:14:44.762 | debug | Alexa-Cookie: Proxy Response from Host: www.amazon.com


</body>
</html>`

**Comment by ossisp1** [comment]
Gleiches Problem habe ich auch. Neuinstallation hat auch nicht geholfen.

**Comment by Apollon77** [comment]
Ja das liegt an dem SMS Flow der irgendwie kaputt ist. Bitte stellt das verfahren auf das aktuelle 2FA bei Amazon um
