### ISSUE TITLE
Adding "Stop" to the commands

### ISSUE THREAD

**Issue by Againstyou** [Apollon77/ioBroker.alexa2#105]
Is it possible to add the "Stop" Command to the Commands? So it would be possible to stop the echo via Script or Dashbutton. This would be great. :) (Not like pause, it would be nice to interupt every speech from echo.)

Also a "listen" button would be nice. Sometimes when im listenig to music, the echo dont hear me proper, it would be nice to set the echo to the listen status via script or Dashbutton.

Thank you for your awesome work.  :)

**Comment by Apollon77** [comment]
Sorry both is not supported by the available APIs.
