### ISSUE TITLE
Routinen und Timer werden nicht mehr aktiviert

### ISSUE THREAD

**Issue by 007Schneiderlein** [Apollon77/ioBroker.alexa2#1052]
Hallo zusammen,

Also erstmal fettes lob an alle Entwickler für diesen Adapter. 🙏❤ ich nutze ihn tagtäglich💪👌, das wird mir aktuell sehr bewusst..., denn leider funktioniert er nicht mehr vollständig seit, ich denke, 2 Wochen.  

Was funktioniert nicht.
ich habe in der Alexa app verschiedenste Routinen angelegt, die ich dann im iobroker als trigger für verschiedenste Szenarien nutze. 
Funktionierte bisher mehr als Klasse ❤
Auch die timer zeit lasse ich mir auf vis anzeigen. Funktioniert leider auch nicht mehr. 😭

Was aktuell noch funktioniert. 
Wenn ich die Routinen im iobroker auf true stelle, reagiert entsprechend Alexa mit dem definierten feedback in der alexa app.
Auch wenn ich das Objekt "speak" über den iobroker triggere, reagiert Alexa ebenso. 

Was habe ich bisher getan

>adapter samt Objekte gelöscht und neu installiert  v3.24.0 (Standardeinstellungen gelassen) 
> cookie x-mal erneuert  
> iobroker  neu aufgesetzt... war dann gefühlt leider auch nötig
> verschiedenste Backups eingespielt... ohne Erfolg...

Hat jemand eine Idee, bzw. Was kann ich denn noch machen? 

Herzlichsten Dank schonmal und nochmal an Euch Entwickler 🙏

Grüße Stefan 

Plattform: linux
Betriebssystem: linux
Architektur: arm64
CPUs: 4
Geschwindigkeit: 1500 MHz
Modell: Cortex-A72
RAM: 3.7 GB
System-Betriebszeit: 00:43:11
Node.js: v20.5.0
time: 1691508222983
timeOffset: -120
Adapter-Anzahl: 488
NPM: 9.8.0
Datenträgergröße: 219.9 GB
Freier Festplattenspeicher: 202.1 GB
Betriebszeit: 00:42:59
Aktive Instanzen: 32
Pfad: /opt/iobroker/
aktiv:

**Comment by Apollon77** [comment]
3.24.1 nutzen

**Comment by 007Schneiderlein** [comment]
ALTER...... 😍
ich bin mehr als begeistert! 
Die Zicke Alexa spricht wieder mit meinem iobroker . 
Noch mehr begeistert mich aber euer qualitativ hochwertiger und effizienter support!  

Aller Besten Dank und Ich gebe ne Runde aus... 🍺🍺🍺🍺 
Grüße Stefan

**Comment by Apollon77** [comment]
Danke!
