### ISSUE TITLE
Nach Update Alexa2 (Amazon Echo)  3.23.2    3.24.1 Iobroker nicht mehr erreichbar

### ISSUE THREAD

**Issue by khkCarport** [Apollon77/ioBroker.alexa2#1055]
**Check if the Bug maybe is with Amazon**  
The adapter is using the same API as the Alexa mobile App. This means:
* If you can not do this what you want with the App then the Adapter also can not do it!
* Also if the App can do it please test if the same effect then the bug also happens with the App (e.g. a speak command do not work on a certain device ... can you do a speak via Alexa App? If not - Amazon problem!)

**Describe the bug**  
A clear and concise description of what the bug is. Especially describe what you verified using the Alexa App (see above).

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Apollon77** [comment]
This sounds more like an adapter unrelated issue ... especially without logs or any details ... please get support in the forum
