### ISSUE TITLE
Amazon change Cookie-Behavior an www.alexa.amazon.de

### ISSUE THREAD

**Issue by JanneW3** [Apollon77/ioBroker.alexa2#1057]
After a clean new installation it's no longer possible to get the session cookie on www.alexa.amazon.de. Page https://www.gehrig.info/alexa/Alexa.html is down. Amazon change website features. Loginpage changed. Comment on site:

`Diese Website unterstützt derzeit nicht alle Amazon-Geräte und Alexa-Funktionen, und die Funktionalität wird im Laufe der Zeit weiter eingeschränkt werden. Bitte lade die neueste Version der Alexa App aus dem iOS App Store oder von Google Play herunter, um den vollen Funktionsumfang zu nutzen.`

**Comment by JanneW3** [comment]
OK, the side ist different. Former you a get the session cookie bei opening www.alexa.amazon.de. Playing by phone a radiostation. Use Entwickler-Tools, look for session cookies... Now ist not possible caused by new page design.

**Comment by Apollon77** [comment]
Yes. It this manual cookie determination way is not needed with the adapter since two or more years. So ... what exactly is not working with the Adapter way? Burbles the page is offline. Seems I need to remove that manual option.

**Comment by JanneW3** [comment]
Now I'm completely lost. In the past, I followed Gehring's instructions. How does it work now? I have already searched the iobroker forum and found nothing. The changes seem to be relativel

**Comment by Apollon77** [comment]
If you open the admin if the adapter you see the cookie status and a link if a new cookie is needed. Click link. Login to you Amazon account. Done. Once and will do need to be done again.

**Comment by JanneW3** [comment]
That's what I did. But the login-page is diffrent. In past it works

**Comment by dj-mib** [comment]
Had the same issue yesterday, after login I received  "Page Not Found" from Amazon.
Changed my login from SMS Authentication to 2SV with Authenticator and it worked.

**Comment by Eldarion85** [comment]
I don't know if it's related, but since yesterday morning I'm not getting any data back from Alexa's history. After a voice output (speek), I check whether something is reported back in the history. The output still works, but there is no longer an answer in the history.
Even if I simply ask Alexa for the time, there is no more information in the history. Restarting and reinstalling didn't help.

**Comment by JanneW3** [comment]
Solved: I needed to aktivate the checkbox at "Amazon-Cookies-Reset"

**Comment by Apollon77** [comment]
@Eldarion85 other issue. See pinned issue
