### ISSUE TITLE
Delete Button for Alarms

### ISSUE THREAD

**Issue by qokaface** [Apollon77/ioBroker.alexa2#106]
Dear developers,

if possible, it would be convenient to have a delete button for alarms which deletes an alarm from the Alexa system. If one deletes the alarm channel, the alarm itself is not deleted and is triggered at the scheduled time. This feature would help to, e.g., transfer alarms which are set on an arbitrary echo device to a specific echo device, e.g., in the bedroom.

A similar feature is available for smart home devices which can be deleted form the Alexa System using ioBroker.

Best regards and thank you in advance

**Comment by Apollon77** [comment]
Technically possible, but how you want to use it? Each created alarm will have its own UUID and so appear dynamically ... so you only could delete it manually ... is this really a use case?

**Comment by qokaface** [comment]
Thank you for your answer.

> Each created alarm will have its own UUID and so appear dynamically ... so you only could delete it manually ... is this really a use case?

I had the use case in mind that I roughly described in the first section (setting an alarm for the bedroom using any echo device in my setup.). The dynamic UUID is not a problem, as it can be collected automatically.

However, I totally agree that this is a very special use case ;)

**Comment by Supermicha81** [comment]
If still interesting...
I maybee have a similar usecase...

You said you collect the UUID dynamically. So you use a scrpit to do so. Why not simply tell the script to deactive the timer with:
`setState("alexa2.0.Echo-Devices.[DeviceID].Alarm.[UUID].enabled", false);`

**Comment by padrino-x** [comment]
As the app offers this feature (at the bottom ;))


![WhatsApp Image 2022-01-27 at 13 15 30](https://user-images.githubusercontent.com/40962599/151357234-d87419eb-9370-4235-bffa-71cd1792bbd0.jpeg)

it would be nice of there was a datapoint(?) for it in Alexa2, too.
Especially as with time it gets very crowded in the data structure as Alexa keeps every single alarm (marked disabled)... :-/

**Comment by Apollon77** [comment]
will be added in next version

**Comment by Apollon77** [comment]
have fun https://forum.iobroker.net/post/824793
