### ISSUE TITLE
Adapter 3.25.1 bringt nach Internet-Ausfall permanent log-Meldungen

### ISSUE THREAD

**Issue by ente34** [Apollon77/ioBroker.alexa2#1063]
**Check if the Bug maybe is with Amazon**  
The adapter is using the same API as the Alexa mobile App. This means:
* If you can not do this what you want with the App then the Adapter also can not do it!
* Also if the App can do it please test if the same effect then the bug also happens with the App (e.g. a speak command do not work on a certain device ... can you do a speak via Alexa App? If not - Amazon problem!)

**Describe the bug**  
Bis auf log-Meldungen kein Fehlverhalten zu beobachten.
Log-Meldungen nach manuellem Restart des Adapters wieder weg.

A clear and concise description of what the bug is. Especially describe what you verified using the Alexa App (see above).

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version:  3.25.1
[Safari 2.pdf](https://github.com/Apollon77/ioBroker.alexa2/files/12583493/Safari.2.pdf)

 - JS-Controller version: 5.012
 - Node version: 18.17.1
 - Operating system: debian bullseye

**Additional context**

**Comment by Apollon77** [comment]
Do you think you can reporoduce such a situation and enable debug log for it to get more details? I can not reproduce it

**Comment by ente34** [comment]
Ich fürchte nicht.Aber solche Provider Wartungen kommen gerade häufiger vor (alle sechs bis acht Wochen), was kann ich beim nächsten Mal tun?Wie bereits gesagt, war ja nicht wirklich ein Problem.Am 12.09.2023 um 09:54 schrieb Ingo Fischer ***@***.***>:﻿
Do you think you can reporoduce such a situation and enable debug log for it to get more details? I can not reproduce it

**Comment by Apollon77** [comment]
Ok, ich bereite mal eine 3.25.2 vor mit ein paar optimierungen ...
