### ISSUE TITLE
Objects alexa2/History/* are empty

### ISSUE THREAD

**Issue by btiegel** [Apollon77/ioBroker.alexa2#1068]
**Describe the bug**  
All objects unter alexa2/History are empty and not updated. Everything else is working fine.

**Expected behavior**  
I use the object alexa2/History/name in scripts to decide in scripts which alexa (i have multible ones) should speak by using the write "speak" object 

**Screenshots & Logfiles**  
I see no errors in the log

**Versions:**  
 - Adapter version: v3.24.1
 - JS-Controller version:  4.0.23
 - Node version: v16.20.2
 - Operating system: PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

**Additional context**

**Comment by Apollon77** [comment]
come on ... why do I pin issues? duplicate #1045
