### ISSUE TITLE
Auslesen des Temperatursensors (zb beim Echo Dot 5)

### ISSUE THREAD

**Issue by tobrog** [Apollon77/ioBroker.alexa2#1077]
Bitte den Temperatursensor von Echo Geräten (zb Echo Dot 5) auch auslesen.
Momentan wird zwar der DP "temperature" bei Geräten und Gruppen unter Smart-Home-Devices erstellt aber nicht befüllt.

**Comment by sauer-m** [comment]
Same here. Ebenfalls Echo Dot Gen 5.

**Comment by enemy2003** [comment]
hänge mich hier mal dran.

gerne irgendwelche Logs oder so…
State Objekt für die Temperatur sehe ich im Admin nicht. Der Echo taucht auch nicht selbst bei Smart Home Devices auf.

Die Alexa Web App gibt es wohl nicht mehr. In der App sieht es so aus, bei Allgemein > Temperatursensor

![IMG_7256](https://github.com/Apollon77/ioBroker.alexa2/assets/17781848/8db1932c-d22d-4458-bc16-bf527a7e232e)

**Comment by sauer-m** [comment]
Wo stellt man denn die Aktualisierung ein?
Ich habe mal den Query-Button gedrückt.

Hier ein paar der Datenpunkte:

![image](https://github.com/Apollon77/ioBroker.alexa2/assets/16384794/7c7f0bf9-89ac-4bcb-9190-e239edcb97cc)
![image](https://github.com/Apollon77/ioBroker.alexa2/assets/16384794/1dc5188f-17af-42c2-85b2-f74ba3184258)

Der Echo Dot aus dem Schlafzimmer wird gar nicht aufgeführt.

Muss ich initial irgendwo etwas aktivieren?
In der Alexa App sieht es bei mir aus wie bei @enemy2003

**Comment by sauer-m** [comment]
EDIT:
Die States oben sind von meinen HmIP Thermostatn 🤦‍♂️

Die Echo States sind erst auf getaucht als ich:

- im Alexa-Adapter die Einstellung "Smart-Home-Geräte synchronisieren" aktiviert habe
- die Query-aktivier/aktuallisiert habe

Außerdem habe ich dann nun den State "#includeInAllQuery" auf true gesetzt, in der Hoffnung, dass die States dann nun aktualisiert werden. 
Vermutlich habe ich mich also einfach nur extrem dämlich angestellt.

**Comment by tobrog** [comment]
So sieht das auch bei mir aus, die Temperatur wird nur durch manuelles triggern aktualisiert. 

Hier noch die states unter Smart-Home-Devices aus dem admin für einen der Echo Dot 5.

![echodot](https://github.com/Apollon77/ioBroker.alexa2/assets/117979025/71dca54c-ce6c-4bbb-972e-b8a700431f76)

**Comment by enemy2003** [comment]
Ah ja kaum richtig eingestellt 🙈
sollte sich das regelmäßig aktualisieren?

**Comment by Apollon77** [comment]
> Außerdem habe ich dann nun den State "#includeInAllQuery" auf true gesetzt,

Der Kandidat hat 1000 Punkte :-)) Sollte auch alles so in der Readme stehen :-)

**Comment by Apollon77** [comment]
Dan bitte settings zeigen und ggf debug log
