### ISSUE TITLE
Datenpunkt history wird nicht aktualisiert

### ISSUE THREAD

**Issue by uwe72** [Apollon77/ioBroker.alexa2#1078]
Kann es sein, dass der history Datenpunkt wieder nicht mehr aktualisiert wird. Zumindest ist dies bei uns so, aktuell, und immer wieder die letzten Tage.

Hat noch jemand das Problem?

**Comment by IchBinSmart** [comment]
#metoo

**Comment by m0rph2k** [comment]
> Scheint endgültig so zu sein, dass ich über den iot Adapter gehen muss. Funktioniert dieser fehlerfrei?

Abwarten, bis jetzt hat es immer wieder funktioniert, wäre weiß was Amazon wieder macht

**Comment by che1000sassa** [comment]
@IchBinSmart : welcher Workaround? Wo finde ich den?

**Comment by flapman** [comment]
> @IchBinSmart : welcher Workaround? Wo finde ich den?

Userdatenpunkt mit false/true erstellen. 
Ein virtuelles Gerät (Schalter) in IOT erstellen mit diesem Datenpunkt. 
Alexa nach neuen Geräten suchen lassen. 
In allen deinen Routinen den Schalter einbinden.
Userdatenpunkt per Skript lesen
Trigger im Historypfad von Alexa ansteuern, wenn der virtuelle Schalter auf wahr geht
Schalter mit 1 sek Verzögerung wieder auf false switchen lassen

**Comment by JestfulW** [comment]
Gleiches Problem. So langsam steigt mir meine Familie aufs Dach weil ständig das SmartHome ausfällt. 
@Apollon77 bist du da im Thema?
Gruß

**Comment by Apollon77** [comment]
Leute ... looocker. Vor 5h issue eröffnet. Ich hab kein debug log. Also Antwort: nein ich bin nicht im Thema. Noch nicht.

**Comment by USKapproved** [comment]
Ich hab das gleiche Problem. In History wird summary nicht aktualisiert. Nach neustart des Adapters geht es für 1-2 Tage aber dann wieder das oben genannte Problem. Im Log hab ich nix auffäliges gesehen :/

**Comment by JestfulW** [comment]
> Leute ... looocker. Vor 5h issue eröffnet. Ich hab kein debug log. Also Antwort: nein ich bin nicht im Thema. Noch nicht. 

Sorry, es sollte nicht klingen als würde ich meckern wollen. Du kannst nichts dafür. Ganz im Gegenteil. Ich bin dir äußerst dankbar für deine Arbeit.
Es ärgert mich nur das Amazon in letzter Zeit vermehrt an den Abfragen herumdreht.

**Comment by Apollon77** [comment]
Also ich habe geprüft und muss leider sagen das Amazon aktuell die "Activity" Messages jetzt auch über den neuen Kanal nicht liefert. Also ja Equilizer und Volume kommen noch - scheinbar Listen und Timer/Alarme kommen ebenso noch.

Ob das ein Fehler oder Absucht ist sehen wir die nächsten Tage ... Ber ja bitte teilt hier nochmals Eure Erfahrungen bezüglich des Workarounds und des "Timing" des selben ... Danke

**Comment by uwe72** [comment]
@Apollon77 Habe folgende Frage: Ich gehe davon aus, dass der Alexa-Adapter keine offizielle API verwendet, welche Amazon bereitstellt? Von da her wird man (bzw. ich) nie eine Garantie haben, dass dies dauerhaft funktioniert. Deshalb überlege ich auf den iot-Adapter umzustellen. Die Frage ist, verwendet dieser eine "offizielle-API", welche verlässlicher ist? Es ist halt viel Aufwand für mich umzustellen, deshalb wäre mir die Antwort hier wichtig. Danke dir und insbesondere auch DANKE für deine Arbeit bis jetzt.

**Comment by Apollon77** [comment]
Der iot Adapter ist die gegenstelle für einen "offiziellen und zertifizierten Skill" von Amazon, also ja das wíst eine offizielle Schnisttselle, aber die kann halt nur Smart Home devices abbilden. lso ja der Weg virtuelle Geräte pro Routine anzulegen und diese zu schalten ist "the way to go"

**Comment by engelsofta** [comment]
> > @IchBinSmart : welcher Workaround? Wo finde ich den?
> 
> Userdatenpunkt mit false/true erstellen. **Ein virtuelles Gerät (Schalter) in IOT erstellen** mit diesem Datenpunkt. Alexa nach neuen Geräten suchen lassen. In allen deinen Routinen den Schalter einbinden. Userdatenpunkt per Skript lesen Trigger im Historypfad von Alexa ansteuern, wenn der virtuelle Schalter auf wahr geht Schalter mit 1 sek Verzögerung wieder auf false switchen lassen

**Comment by engelsofta** [comment]
> > @IchBinSmart : welcher Workaround? Wo finde ich den?
> 
> Userdatenpunkt mit false/true erstellen. Ein virtuelles Gerät (Schalter) in IOT erstellen mit diesem Datenpunkt. Alexa nach neuen Geräten suchen lassen. In allen deinen Routinen den Schalter einbinden. Userdatenpunkt per Skript lesen Trigger im Historypfad von Alexa ansteuern, wenn der virtuelle Schalter auf wahr geht Schalter mit 1 sek Verzögerung wieder auf false switchen lassen

Kostet der IOT Zugang nicht was?

**Comment by JestfulW** [comment]
> Kostet der IOT Zugang nicht was?

Ab einer gewissen Anzahl von Schaltvorgängen ja. Einen minimalen Beitrag. Ich denke für die Arbeit die die Jungs hier hinter den Kulissen haben ist das nicht zu viel verlangt.

**Comment by engelsofta** [comment]
> > Kostet der IOT Zugang nicht was?
> 
> Ab einer gewissen Anzahl von Schaltvorgängen ja. Einen minimalen Beitrag. Ich denke für die Arbeit die die Jungs hier hinter den Kulissen haben ist das nicht zu viel verlangt.

ja ich wollte ja nur diesen einen Schalter anlegen ;-)

**Comment by flapman** [comment]
> Also ich habe geprüft und muss leider sagen das Amazon aktuell die "Activity" Messages jetzt auch über den neuen Kanal nicht liefert. Also ja Equilizer und Volume kommen noch - scheinbar Listen und Timer/Alarme kommen ebenso noch.
> 
> Ob das ein Fehler oder Absucht ist sehen wir die nächsten Tage ... Ber ja bitte teilt hier nochmals Eure Erfahrungen bezüglich des Workarounds und des "Timing" des selben ... Danke

Klappt wie damals ohne Verzögerung.

**Comment by massiemassie** [comment]
Ich verwende einen gefälschten physischen Switch, der auch als ZigBee-Router fungiert: https://it.aliexpress.com/item/1005005242045109.html?spm=a2g0o.order_list.order_list_main.5.5c823696RaRSfc&gatewayAdapt=glo2ita

**Comment by engelsofta** [comment]
> Ich verwende einen gefälschten physischen Switch, der auch als ZigBee-Router fungiert: https://it.aliexpress.com/item/1005005242045109.html?spm=a2g0o.order_list.order_list_main.5.5c823696RaRSfc&gatewayAdapt=glo2ita

Ich einen "gefälschten" Schalter über NodeRed - braucht weniger Strom ;-)

**Comment by Apollon77** [comment]
also triggerst Du nach 500ms? ist das nicht ein bissl schnell?

**Comment by uwe72** [comment]
Hab es aktuell so. Leider funktioniert dies nicht.

```
on({id: [].concat(Array.prototype.slice.apply($("state[id=alexa2.0.Echo-Devices.*.Player.volume]"))), change: "any"}, async function (obj) {

  let value = obj.state.val;
  let oldValue = obj.oldState.val;
  getState("alexa2.0.History.#trigger", function (err, state) {
      setStateDelayed("alexa2.0.History.#trigger"/*Trigger/Rescan*/, state ? !state.val : true, 2000, false);
  });
  setStateDelayed("alexa2.0.History.summary"/*summary*/, '', 2500, false);
});
```

**Comment by coyote9999** [comment]
> also triggerst Du nach 500ms? ist das nicht ein bissl schnell?

Also bei mir funktionieren 500ms zuverlässig.
Musst du bei dir ausprobieren.

**Comment by massiemassie** [comment]
Ich benutze:

on({id: [].concat(['ham.0.Ripetitore-.Switch.On']), change: "any"}, async function (obj) {
  let value = obj.state.val;
  let oldValue = obj.oldState.val;
  setStateDelayed("alexa2.0.History.#trigger"/*Trigger/Rescan*/, true, 1000, false);
  setStateDelayed("alexa2.0.History.summary"/*summary*/, '', 3000, false);
});

**Comment by HartmutKr** [comment]
Hab jetzt alles was ich über die Summary bearbeite in dummy routinen gepackt die dann die Lautstärke auf 40 stellen.
Da man mehrere Auslösesätze in eine Routine packen kann ist das relativ unaufwendig. 
Über ein Blockly wird dann ein trigger ausgelöst.
Funktioniert soweit. 
![bs](https://github.com/Apollon77/ioBroker.alexa2/assets/143587266/1a7ff25b-90ed-4705-bdff-773bd4838479)

**Comment by IchBinSmart** [comment]
Leider gibt es diverse Artikel, dass Alexa mit ifttt eingestellt wird. Das Webinterface von alexa ist bereits abgeschaltet. Es ist also gut möglich, dass Amazon demnächst keinen Pushservice mehr anbietet, damit User nur die offiziellen (zahlungspflichtigen) Apps nutzen. Das ist natürlich nur Spekulation. 

Lob an den Entwickler: Der Alexa Adapter hilft dabei ein viel natürlicheres Spracherlebnis mit Alexa zu haben - die offiziellen Befehle sind sehr oft holprig. Es bleibt abzuwarten, wie lange die Workarounds noch greifen.

**Comment by mcbirne** [comment]
Hallo zusammen,
gibt es einen Lösungsansatz für den Adapter oder muss man demnächst über IOT gehen?

**Comment by uwe72** [comment]
> Hallo zusammen, gibt es einen Lösungsansatz für den Adapter oder muss man demnächst über IOT gehen?

Gute Frage, würde mich auch interessieren, wobei ich für mich entschieden habe auf den iot-Adapter über zu gehen. Bin da auch gerade dabei.

**Comment by martink1979** [comment]
Ja, das Phänomen mit dem "History" Datenpunkt ist schon blöd. Hoffentlich gibt's da bald ein Update auf den Adapter, damit die Funktion wieder gegeben ist

**Comment by flapman** [comment]
> Hallo zusammen, gibt es einen Lösungsansatz für den Adapter oder muss man demnächst über IOT gehen?

Ja siehe oben.

**Comment by flapman** [comment]
> Ja, das Phänomen mit dem "History" Datenpunkt ist schon blöd. Hoffentlich gibt's da bald ein Update auf den Adapter, damit die Funktion wieder gegeben ist

Du kannst auch einfach den Vorschlag von oben umsetzen, dann musst du nicht warten

**Comment by rotodt** [comment]
Nur so als Vorschlag: Anstelle über den IOT Adapter zu gehen, schalte ich einen ungenutzten Switch auf den ich triggere.

**Comment by flapman** [comment]
> Nur so als Vorschlag: Anstelle über den IOT Adapter zu gehen, schalte ich einen ungenutzten Switch auf den ich triggere.

Kannst du das bitte genauer beschrieben. Welcher ungenutzter Switch? Einen physischen? Einen im Broker? Also wie wird dieser Switch ausgelöst. Bitte die Reihenfolge aufschreiben von Sprachbefehl erhalten bis zum verarbeiten im Histroy DP.

**Comment by martink1979** [comment]
@flapman 
Ich habe es jetzt auch so gelöst, das ich mit der Alexa Abfrage (Routine) einen physisch nicht genutzten Schalter (in meinem Fall ein Shelly) schalte, und mit dem Schaltvorgang den "Trigger Rescan" des des Alexa Adapters schalte. Anschließend kann man dann wieder mit dem aktualisierten "summary Wert" aus dem Alexa Adapter weiter arbeiten. Funktioniert soweit super.

**Comment by uwe72** [comment]
> @flapman Ich habe es jetzt auch so gelöst, das ich mit der Alexa Abfrage (Routine) einen physisch nicht genutzten Schalter (in meinem Fall ein Shelly) schalte, und mit dem Schaltvorgang den "Trigger Rescan" des des Alexa Adapters einmal schalte. Anschließend kann man dann wieder mit dem aktualisierten "summary Wert" aus dem Alexa Adapter weiter arbeiten. Funktioniert soweit super.

Ist der Shelly in Alexa eingebunden, oder?

**Comment by martink1979** [comment]
@flapman 
Ja, der ist in Alexa eingebunden.

**Comment by iai2192** [comment]
Hallo zusammen

Ich habe mich nun mit allen Workarounds herum geschlagen und viele funktionierten und andere weniger.
Mein Favorit (einfach und effektiv) ist zur Zeit folgendes Blockly:

![image](https://github.com/Apollon77/ioBroker.alexa2/assets/132922650/624cb13d-782b-474c-b113-96b0d548c498)

ID Selektor von Player.muted: 
alexa2.0.Echo-Devices.XXXX.Player.muted

Ich hoffe jemandem hilfts wie mir.

Grüsse

**Comment by Domi920** [comment]
Hallo, 
habe auch den Workaround mit dem Player.mute Datenpunkt im Einsatz.
Es gibt aber ein großes Problem, das noch nicht erwähnt wurde (oder ich mache einen großen Fehler):

Der Player.mute Datenpunkt wird nur beim Starten der Anfrage aktualisiert.
Nach x Sekunden wird der Datenpunkt Trigger/Rescan ausgeführt und der summary Datenpunkt befüllt.

Das Problem dabei ist allerdings:
Dauert der gesprochene Satz zur Alexa länger als die eingestellte Wartezeit x, so wird der summary Datenpunkt nicht richtig befüllt (weil man noch gar nicht mit den Sprechen fertig geworden ist).

Man könnte natürlich die Wartezeit x erhöhen.
Aber dann wartet man zu lange bis etwas passiert.

Gibt es bei den Workaround auch eine Lösung dafür?


@Apollon77 gibt es bei Dir schon neue Erkenntnisse?
Bzw. hättest Du Zeit, Dir das Problem mal anzusehen?
Im Besten Fall gibt es doch noch einen Weg die Funktionalität wie "früher" herzustellen.

Gruß Dominik

**Comment by JestfulW** [comment]
Es gibt leider noch ein weiteres Problem... Echo Kids löst keine Routinen aus. Damit funktioniert der WorkAround bei den Echo Kids Geräten nicht 🤔 
Ich habe dafür auch noch keinen alternativen Ansatz gefunden.

**Comment by uwe72** [comment]
Gibt's eine offizielle Aussage/Planung zum thema? Ich kann damit leben wenn diese summary Funktionalität nicht mehr unterstützt wird. Denke klarheit wäre gut. Auf diese workarounds wollte ich nicht setzen. Alexa Anbindung ist bei mir die wichtigste Funktionalität rund um dmarthone/iobroker. Ich werde dann auf den iot Adapter umsteigen

**Comment by mcbirne** [comment]
Ich stelle gerade alles auf den IOT Adapter um. Es funktioniert bis jetzt zuverlässig.

**Comment by uwe72** [comment]
> Ich stelle gerade alles auf den IOT Adapter um. Es funktioniert bis jetzt zuverlässig.

Ja, kann ich bestätigen. Was noch schön wäre, hast du aber vermutlich auch keine Lösung. Ich würde gerne, Befehle absetzen wie "Alexa, [Smartnane]", d.h. ohne suffix an,ein,....und ohne workaround Routine?!

**Comment by mcbirne** [comment]
Aktuell sage ich Alexa [einen Satz oder Wortgruppe]. Was dann passiert habe ich in der Alexa App als Routine angelegt. Die Routine schaltet einen virtuellen Schalter, welchen ich über den IOT Adapter mit dem IO Broker verbunden habe. Meine "alten" Alexa Skripte reagieren nun nicht mehr auch eine Wortgruppe sondern auf das true setzten des Schalters.
Zu welcher Alexa ich spreche erfahre ich über ein neues Skript, welches bei allen Alexas reagiert, sobald sich der muted Zeitstempel (Alexa/Plaxer/muted) ändert. Ich schreibe dann die ID der aktuellen Alexa in eine neue Variable. Mit dieser Info kann ich eine Antwort auf dem aktuellen Gerät gewährleisten.
Das Anlegen der Variablen ist etwas mühsam und auch ein Rückschritt zum Auswerten der Sätze. Außerdem muss die Alexa App nun auch mit konfiguriert werden. Aber es läuft wenigstens.

**Comment by Apollon77** [comment]
Ich bin am experimentieren

**Comment by massiemassie** [comment]
Verwenden Sie einen Schalter, real oder virtuell, und fügen Sie ihn in alle Phantomroutinen von Alexa ein. Die Routine des Iobroker ist unveränderlich. Fügen Sie in iobroker dieses Skript hinzu: on({id: [].concat(['Switch']), change: "any"}, async function (obj) {
  let value = obj.state.val;
  let oldValue = obj.oldState.val;
  setStateDelayed("alexa2.0.History.#trigger"/*Trigger/Rescan*/, true, 1000, false);
  setStateDelayed("alexa2.0.History.summary"/*summary*/, '', 3000, false);
});

**Comment by uwe72** [comment]
> Verwenden Sie einen Schalter, real oder virtuell, und fügen Sie ihn in alle Phantomroutinen von Alexa ein. Die Routine des Iobroker ist unveränderlich. Fügen Sie in iobroker dieses Skript hinzu: on({id: [].concat(['Switch']), change: "any"}, async function (obj) { let value = obj.state.val; let oldValue = obj.oldState.val; setStateDelayed("alexa2.0.History.#trigger"/_Trigger/Rescan_/, true, 1000, false); setStateDelayed("alexa2.0.History.summary"/_summary_/, '', 3000, false); });

Für mich stellt sich die Frage wie lange diese Konstrukte noch verfügbar sind?!
/Trigger/Rescan/
alexa2.0.History.summary

**Comment by mcbirne** [comment]
Da ich da auch nicht sicher bin, habe ich diesen Trigger umgangen.

**Comment by flapman** [comment]
> Aktuell sage ich Alexa [einen Satz oder Wortgruppe]. Was dann passiert habe ich in der Alexa App als Routine angelegt. Die Routine schaltet einen virtuellen Schalter, welchen ich über den IOT Adapter mit dem IO Broker verbunden habe. Meine "alten" Alexa Skripte reagieren nun nicht mehr auch eine Wortgruppe sondern auf das true setzten des Schalters. Zu welcher Alexa ich spreche erfahre ich über ein neues Skript, welches bei allen Alexas reagiert, sobald sich der muted Zeitstempel (Alexa/Plaxer/muted) ändert. Ich schreibe dann die ID der aktuellen Alexa in eine neue Variable. Mit dieser Info kann ich eine Antwort auf dem aktuellen Gerät gewährleisten. Das Anlegen der Variablen ist etwas mühsam und auch ein Rückschritt zum Auswerten der Sätze. Außerdem muss die Alexa App nun auch mit konfiguriert werden. Aber es läuft wenigstens.

Kannst du mal den Teil zu welcher Alexa gesprochen wurden einstellen. Das wäre noch was was mir fehlt.

**Comment by massiemassie** [comment]
Ich habe die Iobroker-Skripte noch nicht angerührt und hatte bereits die Ghost-Skripte von Alexa. Ich habe den Schalter auf letzterem und nur das autonome FIZ-Skript auf iobroker hinzugefügt.

**Comment by mcbirne** [comment]
![image](https://github.com/Apollon77/ioBroker.alexa2/assets/38691204/8c105d17-70bd-4af8-8cca-0e5efe0b8950)
- Einmal täglich (0:01 Uhr setzte ich den Zeitstempel zurück.
- Dann gibt es eine Standardroutine "aktive Alexa"
      - Aktuelle Alexa setzen 
      - Zeitstempel aktualisieren
- Da wo Schlafzimmer drüber steht, dass ist die Routine, die aufgerufen wird, wenn der muted Wert geändert wird
      - Wenn der Zeitstempel mindestens 2 Sekunden veraltet ist, dann
            - setzte die Variable aktive Alexa auf die ID der Alexa
            - rufe  "aktive Alexa" auf

**Comment by Apollon77** [comment]
Hey all,

on Github and npm version 3.25.3 of the adapter got now published which should fix the history updates again after the recent Amazon changes.
**Please TURN OFF any additional history-update-trgger scripts you might have used in the meantime!!**

Please update and test this version. You can also turn on debug log to verify that hstory requests are only done when there are interactions and else just if needed.

Please report back if it works.

Donations allowed and welcome as always if you like my work :-)

**Comment by Kaskadeur111** [comment]
Perfekt! Läuft, auch Routinen werden wieder getriggert!

**Comment by iai2192** [comment]
@Apollon77 
Mit dem 3.25.3 funktioniert alles wieder einwandfrei! Herzlichen Dank! Mal schauen wie lange :)

Donate ist unterwegs!

**Comment by JestfulW** [comment]
Herzlichen Dank!
Mein Sponsoring ist dir sicher.

**Comment by JayVee2** [comment]
3.25.4 aus Github: Bei mir kommen keine History Updates nach Sprachbefehl für die Identifikation des letzten Alexa Gerätes...

**Comment by m0rph2k** [comment]
Hi

Sonst noch wer Probleme mit der 3.25.4 Version 3.25.3 geht normal

**Comment by Kaskadeur111** [comment]
Grad die 3.25.4 draufgemacht. Funktioniert genauso wie die 3.25.3.

Ich hab aber n anderes Problem. Dachte es läuft alles, aber Routinen kriegen keine push-Aktualisierung wenn ich ältere Echos anspreche (Echo1, Echo Dot V2 und V3) Lediglich meine Echo Show 8 und 10 werden korrekt gepusht (Routine auf true).

**Comment by JayVee2** [comment]
Also...
3.25.4 funktioniert, im Sinne dass sie Histories bringt. Im Verbund mit mehreren Echo Dots, kamen irgendwelche seltsamen Effekte und teilweise auch leere Histories. Irgendwann mittendrin haben sich die Echos dann heute ein Systemupdate gezogen, seitdem ist die Antwort wieder plausibel.Trotzdem fällt auf, dass die Werte für "domain"bei mir oftmals leer sind.
Auf mich wirkt es so, als wären die history Inhalte nicht ganz ausgegoren und irgendwie unzuverlässig. Früher kam auf eine Schlüsselwort-Anfrage über den iot-Adapter immer zuverlässig "HomeAutomation" in history.domain.

**Comment by LastPerfectTobi** [comment]
> Grad die 3.25.4 draufgemacht. Funktioniert genauso wie die 3.25.3.
> 
> Ich hab aber n anderes Problem. Dachte es läuft alles, aber Routinen kriegen keine push-Aktualisierung wenn ich ältere Echos anspreche (Echo1, Echo Dot V2 und V3) Lediglich meine Echo Show 8 und 10 werden korrekt gepusht (Routine auf true).

Die gleiche Beobachtung hab ich auch gemacht. 
Wenn ich den Echo 1. Gen. anspreche gibts keine Aktualisierung der History Datenpunkte. 
Bei allen anderen Echos die ich habe (DOT 2 z.B.) funktioniert es korrekt wie früher.

**Comment by JayVee2** [comment]
> > Grad die 3.25.4 draufgemacht. Funktioniert genauso wie die 3.25.3.
> > Ich hab aber n anderes Problem. Dachte es läuft alles, aber Routinen kriegen keine push-Aktualisierung wenn ich ältere Echos anspreche (Echo1, Echo Dot V2 und V3) Lediglich meine Echo Show 8 und 10 werden korrekt gepusht (Routine auf true).
> 
> Die gleiche Beobachtung hab ich auch gemacht. Wenn ich den Echo 1. Gen. anspreche gibts keine Aktualisierung der History Datenpunkte. Bei allen anderen Echos die ich habe (DOT 3 z.B.) funktioniert es korrekt wie früher.

Mal die Echos kurz vom Stromnetz nehmen. Da scheint ein Systemupdate anzustehen.

**Comment by Apollon77** [comment]
Wenn das neustarten und ggf updaten so nicht zieht dann würde ich aktuell zum analysieren auch Debug logs per E-Mail (iobroker@fischer-ka.de) nehmen, aber AUSSCHLIESSLICH wenn  in der E-mail genau steht ewas wann (mit ihrzeit) gemacht oder gesagt wurde und was passiert ist aus eurer Sicht und was erwartet worden wäre. Dann schauen wir mal ob wir das ggf noch optimiert bekommen.
Dadurch das das neue verfahren viel auf Raten basiert und ggf Timinetechnisch schwierig sein kann schauen wir mal

**Comment by flapman** [comment]
3.25.4 geht bei mir nicht, wie kann ich die 3.25.3 installieren?

**Comment by Apollon77** [comment]
Wir testen noch eine verbesserung. Kann es sein das Du eine Pause zwischen alexa und dem befehl sagst? Versuch mal nur zu reden ... ggf mit dem Ausfmerksamkeitsmodus. Wenn es da ist sollte das mit der nächsten version besser werden.

**Comment by flapman** [comment]
Um hier nicht zu viel zu schreiben antworte ich im Forum. dann musst du nicht hin und her springen.

**Comment by githubatrkenowde** [comment]
Diese History macht mich komplett Wahnsinnig!
Habe aktuell die Version 3.25.4 in Verwendung. Per Push geht quasi gar nichts.

Bin ich den der einzige Idiot der die History nutzt um diverse Dinge zu triggern?
Gibt es Alternativen die es "lohnt zu prüfen? 

https://github.com/guillaumekln/faster-whisper
https://github.com/rhasspy/rhasspy3

@flapman in welchem Forum?

**Comment by githubatrkenowde** [comment]
Diese History macht mich komplett Wahnsinnig!
Habe aktuell die Version 3.25.4 in Verwendung. Per Push geht quasi gar nicht.

Bin ich den der einzige Idiot der die History nutzt um diverse Dinge zu triggern?
Gibt es Alternativen die es "lohnt zu prüfen? 

https://github.com/guillaumekln/faster-whisper


@flapman in welchem Forum?

**Comment by uwe72** [comment]
> Diese History macht mich komplett Wahnsinnig! Habe aktuell die Version 3.25.4 in Verwendung. Per Push geht quasi gar nicht.
> 
> Bin ich den der einzige Idiot der die History nutzt um diverse Dinge zu triggern? Gibt es Alternativen die es "lohnt zu prüfen?
> 
> https://github.com/guillaumekln/faster-whisper https://github.com/rhasspy/rhasspy3
> 
> @flapman in welchem Forum?

Ja auf den iot Adapter umstellen. Das funktioniert perfekt

**Comment by Apollon77** [comment]
3.25.5 with optimizations on it's way

**Comment by Apollon77** [comment]
@githubatrkenowde ... Also erstmal bitte Geduld und tief durchatmen ... wir versuchen gerade gemeinsam eine neue Logik zu optimieren ... Was "eigenbausystem" angeht bitte nicht in diesem Thread. Danke

**Comment by Megawaldi** [comment]
> > > Grad die 3.25.4 draufgemacht. Funktioniert genauso wie die 3.25.3.
> > > Ich hab aber n anderes Problem. Dachte es läuft alles, aber Routinen kriegen keine push-Aktualisierung wenn ich ältere Echos anspreche (Echo1, Echo Dot V2 und V3) Lediglich meine Echo Show 8 und 10 werden korrekt gepusht (Routine auf true).
> > 
> > 
> > Die gleiche Beobachtung hab ich auch gemacht. Wenn ich den Echo 1. Gen. anspreche gibts keine Aktualisierung der History Datenpunkte. Bei allen anderen Echos die ich habe (DOT 3 z.B.) funktioniert es korrekt wie früher.
> 
> Mal die Echos kurz vom Stromnetz nehmen. Da scheint ein Firmwareupdate anzustehen.

Kannst du ein bisschen mehr dazu sagen. Ich habe mit meinen 1st Gen Alexas noch Probleme.
Bin auf der aktuellsten Firmware.

**Comment by Speedbreaker12** [comment]
Scheint wieder aktuell zu sein, bei mir geht seit heute leider wieder nichts. History wird nicht aktualisiert.

**Comment by gaga191281** [comment]
Arbeite nur noch mit dem virtuellen Device über den iot-Adapter. Aber selbst hier läufts nicht mehr richtig. Zustandsänderungen des virtuellen Devices kommen zwar im iot-Adapter an jedoch werden über das auslösen des #trigger Datenpunktes im Alexa-Adapter die Daten nicht abgeholt.

**Comment by JayVee2** [comment]
Ich habe V 3.26.1 am Laufen mit Schalter "Fragen Sie die Aktivität bei Geräteinteraktion..." gesetzt.
History Meldungen kommen zum Teil stark verzöger (> 10 Sekunden), aber sie kommen meist.

**Comment by Manni-Pi** [comment]
Bekomme auch nur ab und zu Antwort wenn ich den History/trigger auslöse. Automatisch geht hier nichts mehr.

**Comment by Apollon77** [comment]
Versucht mal ob die Sprach-History bei Euch in der Alexa App noch geht ... wenn da auch Fehler kommen dann ist es Amazon, ich fürchte die haben die Abfrage jetzt recht dicht gemacht

**Comment by LastPerfectTobi** [comment]
Also bei mit kommt in der Alexa App der Sprachverlauf. 
Allerdings meldet die App erst einen Fehler beim Laden der Daten, wenn man das bestätigt kommen die Daten dann trotzdem.

**Comment by Apollon77** [comment]
Genau ... also irgendwas hat die App auch Probleme. Theoretisch mal an den support melden das in der App der Fehler kommt *gg*

**Comment by Manni-Pi** [comment]
In der App im Aktivitätsverlauf kommt hier auch immer "Es ist ein Fehler aufgetreten". Werde heute Abend mal versuchen an Amazon zu schreiben wenn ich es zeitlich hin bekomme.

**Comment by Manni-Pi** [comment]
So, der Aktivitätsverlauf in der App geht im Moment Fehlerfrei. Leider sind die Probleme mit der Triggerung geblieben.

**Comment by LastPerfectTobi** [comment]
Gibts eigentlich noch Hoffnung dass die History wieder funktionsfähig wird?

Ich bin mir sicher die Experten kämpfen noch damit. 
Wenns aber keine Hoffnung mehr gibt muss ich so langsam doch versuchen die workarounds umsetzen.

**Comment by JestfulW** [comment]
Also die History summary funktioniert aktuell. Der Datenpubkt wird aktualisiert.

**Comment by Apollon77** [comment]
Jupp aktuellste verion sollte bestmöglich tun ... wenn nicht bitte neues issue öffnen mit detals

**Comment by LastPerfectTobi** [comment]
> Jupp aktuellste verion sollte bestmöglich tun ... wenn nicht bitte neues issue öffnen mit detals

Ich schau mal, wenn sonst keiner ein Problem hat liegts wahrscheinlich an mir. Bei mir aktualisiert die History mit der aktuellsten Version nicht. 
Danke für eure Antworten.

**Comment by Apollon77** [comment]
... Du hattest aber die Install-Info gelesen? Du musst jetzt in den Settings aktivieren das History automatisch abgeholt werden soll. SOllte Admin beim Update explizit angezeigt haben ....

**Comment by LastPerfectTobi** [comment]
Vielleicht deswegen. 
Hinweis habe ich in Admin keinen gesehen. 
Aber so tuts dann wieder. Danke 🙂

**Comment by sahomm** [comment]
> ... Du hattest aber die Install-Info gelesen? Du musst jetzt in den Settings aktivieren das History automatisch abgeholt werden soll. SOllte Admin beim Update explizit angezeigt haben ....

Entschuldigt die Nachfrage! In welchen Settings soll dies eingestellt werden? In den Settings der Alexa2 Instanz Version 3.26.3 finde ich da leider nichts.

**Comment by Apollon77** [comment]
Genau da ist es aber... zeig mal einen Screenshot

**Comment by sahomm** [comment]
Hier der Screenshot:
![Bildschirmfoto 2023-12-15 um 16 09 49](https://github.com/Apollon77/ioBroker.alexa2/assets/11404919/09f66090-2807-4ba0-8f66-675f9593669b)

Vielen Dank!

**Comment by Apollon77** [comment]
Also die Konfig sieht korrekt aus ... dann wäre jetzt ggf ein Debug log interessant wenn es immer noch nicht geht

**Comment by sahomm** [comment]
Vielen Dank für Deine rasche Unterstützung und bitte entschuldige meine späte Antwort!

Du hast vollkommen recht! Mit Echo Dot 3. gen funktioniert die History einwandfrei. Ich habe ursprünglich über die Alexaintegration in die Bose Soundbar 900 probiert (hat vor dem Change immer funktioniert), hier funktioniert die History komischerweise nicht. Denke dies ist ähnlich gelagert wie oben beschrieben dass es mit den echo dot 1. gen nicht funktioniert.

Dies als Feedback und wenn andere ebenso darüber stolpern.

Vielen Dank!

**Comment by Tomili777** [comment]
Hallo,

ich habe die Version 3.26.4 installiert, dei Einstellung vorgenommen.
Bei mir werden keine History Datenpunkte aktualisiert. Geht das nun endgültig nicht mehr?

**Comment by LastPerfectTobi** [comment]
Also bei mir tut es - außer am Echo V1. Der ist wahrscheinlich von Amazon künstlich verschlechtert worden weil er zu alt ist. 

Ansonsten tuts wunderbar bei mir.
