### ISSUE TITLE
Login process replies Error 404 (Page not found)

### ISSUE THREAD

**Issue by maume86** [Apollon77/ioBroker.alexa2#1083]
**Describe the bug**  
After logging in amazon account via local URL (IP from my ioBroker) and putting in the sent code from SMS, i get an error 404 page shown below.

**To Reproduce**  
1. Go to adapter settings
2. Click on 'folgenden Link zur einmaligen Anmeldung im Amazon-Konto'
<img width="1070" alt="image" src="https://github.com/Apollon77/ioBroker.alexa2/assets/55945598/ec0c0166-a059-4b96-8150-7c9f32077b44">

3. In opened window enter amazon credentials
4. Get SMS code and enter in window
5. Get redirected to: Page not found
<img width="1324" alt="image" src="https://github.com/Apollon77/ioBroker.alexa2/assets/55945598/6ea37f49-9f99-4d04-86b0-68691497a203">

**Expected behavior**  
Normal connection between amazon Alexa and ioBroker adapter should been performed

**Versions:**  
 - Adapter version: 3.25.2
 - JS-Controller version: 5.0.12
 - Node version: 18.18.2
 - Operating system: Raspbian GNU/Linux 11 (bullseye)

**Comment by Apollon77** [comment]
See Readme please ... upggrade your SMS "two factor" to the recent/current method. Then it will work
