### ISSUE TITLE
Frage: History-Adapter bei unbekanntem Befehl leer -> Änderung bei Amazon?

### ISSUE THREAD

**Issue by astrakid** [Apollon77/ioBroker.alexa2#1086]
Bisher war es so, dass im History-Adapter alles aufgetaucht ist, was als Sprachbefehl an Amazon übermittelt wurde. Das habe ich genutzt, um einen benutzerdefinierten Befehl auszuwerten.
Das klappt seit den neuesten Änderungen nicht mehr.
Liegt das an Amazon? Oder ist das durch eine Änderung am Adapter verursacht?

gruß,
andre

**Comment by astrakid** [comment]
nachtrag: nach vielen versuchen klappt es irgendwann. komisch. aber sehr unzuverlässig.

**Comment by Steingraeber** [comment]
das habe ich auch festgestellt mit Adapter Version 3.25.2.

**Comment by astrakid** [comment]
so sieht es aus, wenn des nicht funktioniert:

![image](https://github.com/Apollon77/ioBroker.alexa2/assets/5278642/4279f4f0-8b26-4809-b51c-e7cb18d6b1a6)

einen screenshot, wie es aussieht, wenn es funktioniert, liefere ich nach. allerdings wird der befehl in der alexa historie immer sauber angezeigt, nur nicht im adapter. jetzt hat es nach ca. 20 versuchen endlich geklappt, aber im adapter wird de rhistorieneintrag in der iobroker-GUI nicht angezeigt.

**Comment by astrakid** [comment]
hier jetzt der screensho im erfolgsfall:

![image](https://github.com/Apollon77/ioBroker.alexa2/assets/5278642/ca3fa7b7-6ac4-49ed-940f-ae2231d1a17d)

**Comment by astrakid** [comment]
hm. es kommt faktisch der befehl am alexa adapter an, aber taucht nicht im history adapter auf.
wenn ich das in den debug logs richtig sehe, wird der wert in history.summary direkt wieder geleert - und je nachdem, ob der wert, auf den mein javascript triggert, dann noch in dem wert steht, geht es - oder eben (meistens) nicht.

**Comment by astrakid** [comment]
... und manchmal geht es plötzlich einige minuten später...?
hab jetzt einen test gemacht: sprachbefehl abgesetzt laut iobroker-log um 19:00:25... jetzt warte ich ab, bis der wert in history.summary auftaucht.

**Comment by astrakid** [comment]
auffällig ist im erfolgsfall, dass unter "domain" homeautomation aufgeführt ist.

**Comment by Apollon77** [comment]
siehe #1078 ... vor allem letzte Posts. Alles unter 3.25.3 ist broken by definition wegen Amazon change ...

**Comment by astrakid** [comment]
ja, ist mir bewusst, bin auch auf 3.25.4 unterwegs.

**Comment by astrakid** [comment]
nochmal getestet: ich muss quasi glück haben, dass mein javascript (wird getriggert durch änderung von history.summary) noch den richtigen wert erhält. aber scheinbar wird das sofort von amazon wieder geleert.
somit brauche ich viele versuche, bis mein javascript dann mal endlich die zeichenkette entnehmen kann.

**Comment by Apollon77** [comment]
Es gibt vorauss. morgen ein update. testen es aktuell

**Comment by Apollon77** [comment]
3.25.5. auf dem Weg ...

**Comment by astrakid** [comment]
supercool, läuft mit 3.25.5 wieder absolut zuverlässig!!!

**Comment by astrakid** [comment]
donation ist unterwegs. ist leider nicht gegen deinen aufwand aufzuwiegen. aber als kleiner dank...
