### ISSUE TITLE
Echo Pop - Report to developer as GitHub issue with details for device

### ISSUE THREAD

**Issue by Mayflower7482** [Apollon77/ioBroker.alexa2#1088]
Der Neue Alexa Echo Pop
https://amzn.eu/d/gJfwbKz
Mfg

`Device-type:ASQZWP4GPYUT7 - Echo Pop (SET_LOCALE,BT_PAIRING_FLOW_V2,TIMERS_AND_ALARMS,PERSISTENT_CONNECTION,VOICE_TRAINING,TAHOE_BYOD,EFDCARDS,ACTIVE_AFTER_FRO,ALEXA_PRESENCE,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,AMAZON_MUSIC,AUDIBLE,TUPLE_CATEGORY_A,PANDORA,GOLDFISH,REQUIRES_OOBE_FOR_SETUP,REMINDERS,LEMUR_ALPHA,EQUALIZER_CONTROLLER_MIDRANGE,DEREGISTER_DEVICE,SUPPORT_CALENDAR_ALERT,ASCENDING_ALARM_VOLUME,SET_TIME_ZONE,MUSIC_SKILL,LOCALIZATION,SLEEP,EQUALIZER_CONTROLLER_BASS,TAP_GESTURES,SUPPORTS_LOCALE,DIALOG_INTERFACE_VERSION,ALEXA_VOICE,DREAM_TRAINING,DS_VOLUME_SETTING,TIDAL,EARCONS,SUPPORTS_SOFTWARE_VERSION,SIRIUSXM,SUPPORTS_LOCALE_SWITCH,SOUND_SETTINGS,APPLE_MUSIC,MULTI_WAKEWORDS_SUPPORTED,AUDIO_CONTROLS,POPTART,AUDIO_PLAYER,DEEZER,GUARD_EARCON,CHANGE_NAME,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,PAIR_BT_SINK,DISPLAY_BRIGHTNESS_ADJUST,SALMON,ADAPTIVE_LISTENING,SPEECH_RECOGNIZER_USS,KINDLE_BOOKS,FLASH_BRIEFING,FAR_FIELD_WAKE_WORD,TAP_GESTURES_SINGLE_TAP,I_HEART_RADIO,VOLUME_SETTING,TUNE_IN,TUPLE,CUSTOM_ALARM_TONE,MICROPHONE,GADGETS,PAIR_BT_SOURCE,UPDATE_WIFI,EQUALIZER_CONTROLLER_TREBLE)`

**Comment by sansonifabio** [comment]
@Apollon77 falls du Zugang zu meinem Account brauchst sag Bescheid ich habe auch einen Pop und die Daten hier kommen im Moment an:
![image](https://github.com/Apollon77/ioBroker.alexa2/assets/88761140/186d73bb-59c7-4138-ad7a-27f3a8de294f)

**Comment by Apollon77** [comment]
Ok, kann er routinen und kommandos und so? Dann ists ja einfach.

**Comment by sansonifabio** [comment]
Ja du kannst ihm "alles" sagen er führt es aus. Licht an/aus Musik/ Wecker etc. 
Der ist im Angebot für 17 Euro da habe ich mir einen gekauft.

Herzliche Grüße
Fabio
