### ISSUE TITLE
Alexa Connect

### ISSUE THREAD

**Issue by Blackei** [Apollon77/ioBroker.alexa2#109]
Hi,
wäre super wenn die Datenpunkte für den Alexa Connect noch kommen würden. 
Ich würde gerne abfragen können wenn ein Anruf raus oder rein geht um die Musik pausieren zu lassen

**Comment by Blackei** [comment]
Hi,
ich rede von Alexa Connect also dem neuen Alexa Device. Ich verstehe nicht im Ansatz was das mit dem anderen Fall zu tun hat. Für Connect fehlen halt noch die Datenpunkte, aber vielleicht gibt es ja auch keine.

**Comment by Moormerlander** [comment]
Das wäre ne tolle Sache, insbesondere wenn man den Adapter als Anrufbeantworter über ioBroker nutzen oder Alarmanrufe damit auslösen könnte :-)

**Comment by sigi2345** [comment]
Bekomme Heute den Alexa Connect.......ich teste den mal.

**Comment by sigi2345** [comment]
Installiert, das kommt raus:

deviceType:
AKOAGQTKAS9YB

capabilities:
BLOWER,NO_UNITS_AND_TIMEZONES,CHANGE_NAME,PEONY,MICROPHONE,PERSISTENT_CONNECTION,VOLUME_SETTING,DEREGISTER_DEVICE,UPDATE_WIFI,SUPPORTS_SOFTWARE_VERSION

**Comment by Apollon77** [comment]
Und was kann die App diesbezüglich Don? Was zeigt Die ggf an wenn man anruft oder ein Anruf ankommt?

**Comment by sigi2345** [comment]
Bis jetzt noch nichts, teste noch...

**Comment by PixelTomsen** [comment]
ich habe das Teil auch seit gestern und schaue mal  mit nach😉
