### ISSUE TITLE
Alexa Datenpunkte (Routinen und History) werden weiterhin nicht aktualisiert. (3.25.5 )

### ISSUE THREAD

**Issue by 007Schneiderlein** [Apollon77/ioBroker.alexa2#1093]
hi @Apollon77,

leider funktioniert der Adapter 3.25.5 bei mir immer noch nicht. 😭
Ich habe den adapter komplett neu installiert und auch mit dem Konto neu verbunden. Alle bisherigen Workaround Trigger habe ich auch deaktiviert. 
Ich nutze übrigens einen echo 1.Generation...

Grüße Stefan

**Comment by Apollon77** [comment]
Dann Bitte Debug log senden per email an iobrokrt@fischer-ka.de vom gesamten Adapterstart (und bitte wirklich warten bis er ferig ist!!! Da kommt eine Info Logline) und dann eine interation machen, Uhrzeiten aufschreiben und sagen was passiert ist und was hätte sollen. Bitte in der E-Mail auf dieses Issue verweisen.

**Comment by matze939939** [comment]
Hallo, ich kann bei mir die (verspätete) Aktualisierung der Datenpunkte ebenfalls bestätigen. Im Log finde ich dann ff. Meldung: "Alexa-Remote: Response: No body", ggf. hilft dies.
Viele Grüße

**Comment by Megawaldi** [comment]
ich schließe mich dem Problem an.
Auch Echo Gen1 Geräte.
Bei Aufruf einer Routine bleibt der debug Log leer und History wird auch nicht aktualisiert.

**Comment by Manni-Pi** [comment]
Hallo, auch bei mir gehen die alten Gen.1 Geräte nicht. Bei den neuen Generationen ist die Reaktion ab und zu verzögert. Habe im Moment 10 Echo Geräte der verschiedensten Generationen im Haus in Gebrauch. Trotz der Probleme im Moment möchte ich mich für die coole Arbeit hier bedanken. Echt toll was hier geleistet wird und wieviel Hirnschmalz schon in den Adapter geflossen ist.

**Comment by Apollon77** [comment]
We are testing a new version ... in some cses Amazon do not report the voice history infos ...

**Comment by 007Schneiderlein** [comment]
Hi @Apollon77 

sorry ich war die letzten tage etwas Landunter und konnte dir die log nicht senden... Aber es hat sich ja wieder Einiges getan.
Also bei mir läufts wieder mit dem 3.26.1 version, über die Trigger Funktion (via IOT Instance) TOP 👌

Und wieder allerbesten Dank für deinen / euren unermüdlichen Support ! 🙏
Grüße Stefan
