### ISSUE TITLE
Amazon Anmeldung: Cookie Manuell generieren

### ISSUE THREAD

**Issue by thps1990** [Apollon77/ioBroker.alexa2#1097]
Hallo,

die integrierte Funktion zum generieren des Cookies funktioniert bei mir leider nicht mehr. Der Link zum generieren des Cookies scheint nicht richtig generiert zu werden. Es wird lediglich http://192.168.2.2:43291/ als URL hinterlegt, da führt dann in die Alexa App. Das kann natürlich nicht funktionieren.

Deswegen würde ich den Cookie gerne manuell generieren. Der Link dazu in der Dokumentation funktioniert aber nicht mehr. Gibt es die Info auch noch irgendwo anders?

Vielen Dank und viele Grüße

**Comment by Apollon77** [comment]
Was bedeutet "führt in die Alexa app"? Mal versucht auf einem PS und nicht handy zu öffnen?

**Comment by Apollon77** [comment]
Und ja manuelle cookie gehen nicht mehr. Info fliegt beim nächsten Update raus

**Comment by thps1990** [comment]
> Was bedeutet "führt in die Alexa app"? Mal versucht auf einem PS und nicht handy zu öffnen?

Hi Danke für die Antwort. Am PC erwartet mich eine Seite mit dem Hinweis doch bitte die Alexa App zu verwenden:

![image](https://github.com/Apollon77/ioBroker.alexa2/assets/35417595/10cf3551-70e3-4d1d-bc96-cd0ad124a830)

**Comment by thps1990** [comment]
Vielen Dank für die Unterstützung. Da hätte ich auch selbst drauf kommen können

**Comment by Apollon77** [comment]
Der proxy kann es leider nicht verhindern das die App da übernimmt
