### ISSUE TITLE
[Question] Send/say text to reply in the skill 

### ISSUE THREAD

**Issue by lasys** [Apollon77/ioBroker.alexa2#1099]
**Describe the bug**  
When I start a skill with the textCommand, e.g. "TV program tonight" and the skill asks me if I want to know more details, I send "More details" with the textCommand, but then the skill unfortunately aborts.
Should this work or do I have to do something else or does it simply not work? 

**To Reproduce**  
1. Start Skill via 'textCommand', e.g. "Fernsehprogramm heute abend"
2. Wait until Alexa is waiting for user input 
3. Send textCommand e.g. ''Mehr Sender" 
4. Skill aborts 

**Expected behavior**  
Alexa responds to the new "textCommand" and the skill continues to run. 

Thank you very much for your help and support!

**Comment by Apollon77** [comment]
I would hard assume that this will not work because textcommand is for new commands and not "inside a skill interaction" ... But in fact ... no idea. But if you already proofed it not working then this is your answer
