### ISSUE TITLE
Sprachausgabe auf letztes Device

### ISSUE THREAD

**Issue by none007** [Apollon77/ioBroker.alexa2#11]
Hallo Apollon77,

danke für deine Mühe Alexa noch weiter in Iobrocker einzubinden.

Wäre es aber noch möglich eine eigenes Device auf das letzte angesprochene Device zu erstellen.  Dann könnten gesprochene Anweisungen dem Nutzer quasi folgen...

Zum Beispiel rufe ich mit "Alexa schalte Lüften ein" ein Blocklyskript auf, was dann zuerst das letzte Echodevice vom Linuxskript hollt und dann darauf entsprechend die Anwort ausgibt. 

`exec('bash /opt/iobroker/alexa/alexa_remote_control.sh -lastalexa', function (error, result, stderr)`

Mit deinem Adapter müsste ich dann aber für jedes Device eine Abfrage bauen oder?

Danke nochmal für deine Mühe
VG 
none007

**Comment by Apollon77** [comment]
Warum willst du immer noch das shellskript nutzen?
Der Adapter hat den History.#trigger State der dir das Ergebnis liefert in den anderen History datenpunkten. Dort hast du dann das verwendete device.

**Comment by none007** [comment]
Ich will ja das shellskript loswerden. Zur Zeit nutze ich es für die komplette Sprachausgabe.

Das mit dem History-Trigger stimmt schon, aber so wie es jetzt ist müsste für jedes Device ein Wenn/dann-Ast im Skript gebaut werden. Daher meine Frage, ob es möglich ist, ein "Last-Device" als fiktives EchoDevice aufzunehmen. Auf dem man dann einfach die Sprachausgabe, Lautstärke etc. jagen könnte und es würde im Hintergrund automatisch der Historytrigger ausgelöst und das entsprechende Device angesprochen.

Ich hoffe ich habe es verständlich ausgedrückt  ;-)

**Comment by Apollon77** [comment]
Naja das brauchst Du nur weil du "Nur "Blockly einsetzt. Als echtes Javascript baust Du dir den State-Namen zusammen als String und fertig ... Schau mal ins Forum in den alexa2 thread, hab da mal das alte"Licht-An" Skript angepasst

**Comment by Apollon77** [comment]
Nochmal nachgedacht. Wie es jetzt alles ist mit der Push Verbindung, ist das letzte gerät in den History Daten nicht unbedingt das Gerät was man ansprechen möchte. Daher setze ich das nicht um und überlasse es den Usern entsprechende Skripte für ihre Anwendungsfälle zu schreiben
