### ISSUE TITLE
Sonos One and Alexa 2.0 Adapter

### ISSUE THREAD

**Issue by Moormerlander** [Apollon77/ioBroker.alexa2#110]
My problem is that the some Sonos objects in the alexa2 adapter are a bit weird. 

1. I have two Sonos One with Alexa capabilities and sometimes they can be adressed with comands like using a TuneIn radio station or player commands like play or pause can be triggered and they work. But sometimes they just don't and nothing happens. All my other Echos, Dots and so on work just fine with the adapter.

2. The Sonos One devices appear as two diferent objects with all properties.

3. Always to one of the double objects as described in 2. the name is modified automatically. So the system adds the sting "(Sonos One)(Sonos One)(Sonos One)(Sonos One)(Sonos One)(Sonos One)(Sonos One)(Sonos One)(Sonos One)" to the name of the device in the adapter.

**Comment by Moormerlander** [comment]
Ich kann das Problem natürlich auch gerne in deutsch diskutieren ;-)

**Comment by Moormerlander** [comment]
![image](https://user-images.githubusercontent.com/27990424/46657450-9a682800-cbb0-11e8-840f-0f0d090ec16c.png)

Der Befehl wird nicht ausgeführt, obwohl die Objektzuordnung richtig ist

**Comment by Moormerlander** [comment]
![image](https://user-images.githubusercontent.com/27990424/46657765-56c1ee00-cbb1-11e8-8a37-738fde742138.png)

Beispiel für die doppelten Devices und die automatische Benennung.
Nach einer manuellen Änderung sind die "(Sonos One)" Strings wieder drin.

**Comment by Apollon77** [comment]
Wenn Objekte doppelt kommen dann tauchen die plötzlich mit einer anderen Geräte ID auf. AM besten Aalexa2-Adapter einmal neu starten, dann sollte er "alte" Objekte wegräumen. Wann sowas passiert kann ich Dir nicht sagen - weiss vermutlich nur Sonos und Amazon :-( Der Adapter kann nur das haben was Amazon liefert und wenn Die Dinge ändern ist der Adapter machtlos.

Gleiches beim Namen. Der Adapter liesst den ggf von Amazon ein. Er sollte also in deiner Alexa App genau so aussehen. Ich hab den Effekt auch mit einem "Simulator"-Gerät. Lösung habe ich keine.

Ich denke der Effekt das Dinge nicht mehr tun hängt ggf damit zusammen das sich im Hintergrund die ID geändert hat udn Du weiter an die "alte" ID sendest die aber bei Amazon nicht mehr Aktiv ist.

Von daher: Versuch mal neustart vom Adapter und schaue was dann die aktuellen objekte sind.

**Comment by Moormerlander** [comment]
Das mit dem Neustart der Alexa-Instanz war direkt das erste was ich gemacht habe, aber leider brachte das nichts. Hab's vor einer Minute nochmal getestet. Und Du hast natürlich recht: In der Alexa App erscheint das Device genauso: "(Sonos One)(Sonos One)..." 

Ich habe im Script die gleiche Objekt-ID verwendet wie in einem Testscript. Und da sprang TuneIn direkt an, daher ist das so unlogisch für mich. Ich experimentiere weiter und berichte an dieser Stelle wenn das für Dich okay ist.

**Comment by Apollon77** [comment]
Aber klar. Sind denn nam dem Neustart einige doppelte Geräte weg? ggf Admin nochmal neu laden? :-)

Wenn nicht bräuchte ich bitte Debug log, gern auch als Forum PN ...

**Comment by Moormerlander** [comment]
Ich habe sonst keine doppelten Geräte. Ich werde ansonsten mal anders rangehen und beide Sonos One aus dem Netz schmeißen und neu installieren. Mal sehen was dann passiert.

**Comment by Moormerlander** [comment]
Ich handle das bis zur weiteren Klärung über den ioBroker Sonos-Adapter. Darüber kann ich meine gewünschten Funktionen steuern.

**Comment by Apollon77** [comment]
bitte 2.3.3 checken
