### ISSUE TITLE
#trigger not subscribed

### ISSUE THREAD

**Issue by crocri** [Apollon77/ioBroker.alexa2#1101]
Hallo!
Ich beziehe mich auf die letzte Version 3.26.1
Ich würde gerne die History manuell abfragen. In der Konfiguration ist alles abgeschaltet (Checkboxen nicht ausgewählt und alle Intervalle auf 0 gesetzt).
Der History.#trigger reagiert nicht auf erneutes setzen.
Füge ich in der Init Routine (main.js) ein adapter.subscribe("History.#trigger") hinzu, funktioniert es wieder.

Gruß
Crocri

**Comment by Apollon77** [comment]
haben Sie gewartet bis die Initialisierung des Adapters auch fertig war? Da wird eine info Logging ausgegeben ... vorher ist KEIN State subscribed.

**Comment by crocri** [comment]
Klar hatte ich gewartet. Heute noch einmal getestet, und jetzt geht es auch ohne zus. subscribe - aber sehr verwirrend ist das Verhalten des Triggers (vielleicht ist dadurch auch mein Eindruck entstanden, es fehlt das subscribe).

Wenn man ihn auf true setzt (ohne ack), geht er nicht sofort auf false zurück, obwohl die History aktualisiert wurde. Erst beim nächsten Auslösen des Triggers (z.B. durch "Wie spät ist es") springt dieser wieder auf false - inklusive neuer History Einträge.
Wenn man den #trigger nur auf false (ohne ack) setzt, funktioniert es auch - sollte es meiner Meinung nach aber nicht, oder?

Zusammengefasst sollte der #trigger nur dann auslösen, wenn er auf true ohne ack gesetzt wird. Nach erfolgreicher Aktualisierung der History wird er auf false mit ack zurückgesetzt, wenn die Abfrage der Amazon Seite (rvh) nicht erfolgreich war, sollte er auf false ohne ack gesetzt werden. Wäre so mein Verständnis eines Triggers. 

Gruß
Crocri

**Comment by Apollon77** [comment]
Ein "trigger" hier ist ein Button, der muss per Definition mich auf false zurückspringen. Und weiterhin ja "ausschlieslich "ck=false" wird verarbeitet

**Comment by crocri** [comment]
Hm - beim Trigger steht "desc": "Set to true, to start a request", aber genau dies funktioniert eben nicht richtig (zumindest bei mir). Setze ich den Trigger auf false, funktioniert es korrekt.

Beispiel mit true (ohne ack):
Ich frage "wie spät ist es?" und setze den Trigger direkt danach auf true - es passiert nichts
Ich frage noch einmal etwas (das Gleiche oder etwas anderes), dann wird die Historie angezeigt (ohne erneutes triggern).

Beispiel mit false (ohne ack):
Ich frage "wie spät ist es?" und setze den Trigger direkt danach auf false - Historie wird korrekt angezeigt

Dies Verhalten hat eben genau zu meinen ersten Kommentaren geführt, da das Ergebnis so nicht nachzuvollziehen war...

**Comment by Apollon77** [comment]
Ist das automatische Abholen der History. einträge aktiviert? Falls ja dann ist das manuelle gesperrt weil der automatische Prozess läuft um zuviele Requests zu vermeiden. Wenn manuell getriggert werden soll dann bitte das automatsiche Abholen deaktivieren. Sonst brauche ich bitte ein Debug log von so einem versuch
