### ISSUE TITLE
Buttons i.e Flashbriefing not working

### ISSUE THREAD

**Issue by jenbenn** [Apollon77/ioBroker.alexa2#1107]
Some of the  command buttons have suddenly stopped  working  about three weeks ago within iobroker.  When I press  the "flashbriefing" button in iobroker objects   Alexa announces " your flashbriefing is started" ("Ihre tägliche Zusammenfassung wird abgerufen") but then nothing follows.  The flash briefing doesnt start. 

When I start the flash briefing via voice command  on the alexa device everything works as it should and the configured  Tageschau news are played followd by the weather report.

The "joke" button is also no longer responsive.

**Comment by Apollon77** [comment]
If you create a routine in the alexa app and then start this routine via tha "play" button shwon there. does it work then or also not?

**Comment by jenbenn** [comment]
Hi, thanks, same result. I created a routine to play the flash briefing.  When activated from Iobroker  Alexa announces "Ihre tägliche Zusammenfassung wird abgerufen" but then she goes silent and nothing follows.  When I activate the routine  via voice command everything works as it should.

**Comment by Apollon77** [comment]
In fact the adapter can only do what the App can, so if the issue also exoists with a manual routine created via App then the amazon support is your first fruend ... tell them just about the routine in the alexa app and not about ioBroker :-)
