### ISSUE TITLE
keine Suche mehr auf dem Multiroom Device möglich

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#111]
Moin ich kann nichts mehr unter 
`alexa2.0.Echo-Devices.342axxMultiroomxx5b.Music-Provider.Amazon-Music`
eingeben, bzw keine music Ausgabe.

**Comment by Apollon77** [comment]
Adapter mal neu gestartet? Ein anderer umsehest berichtet das einige Geräte neue ids bekommen haben. Es gab Inder neuesten App auch Änderungen bei multiroom. 

Sonst bitte wie üblich debug log von der Aktion ;-)

**Comment by Matten-Matten** [comment]
Neustart und drüber installieren brachte kein erfolg. Ich habe dir mal den gesamten Log geschickt mit der Auslösung. 

 `alexa2.0.Echo-Devices.34xxx455b.Music-Provider.Amazon-Music` 

hab folgendes dort eingegeben: robin schulz

**Comment by sigi2345** [comment]
Funktioniert:

![screenshot 939 _li](https://user-images.githubusercontent.com/41079106/47005001-1fb08700-d133-11e8-9296-e6ac7a510696.jpg)

**Comment by Matten-Matten** [comment]
Bei mir funktioniert es nicht mehr.

**Comment by Apollon77** [comment]
wie ist es eigentlich inzwischen?
