### ISSUE TITLE
Status der Smartdevices

### ISSUE THREAD

**Issue by tommyMX** [Apollon77/ioBroker.alexa2#1116]
Hi,
wäre es nicht mal möglich den Status der Smart Devices zu sehen?
welchen Sinn macht es eigentlich jetzt was man sieht? was kann man damit anfangen.

Hab halt einen Kontaktsensor und da wäre es toll wenn er den Status anzeigt :-)

<img width="1670" alt="Bildschirmfoto 2023-12-11 um 17 13 19" src="https://github.com/Apollon77/ioBroker.alexa2/assets/36209886/695e34bb-2213-4cad-aa1d-e8c8777ea37a">

**Comment by Apollon77** [comment]
Na klar kann man das ... ein klick auf "query" holt den Wert einmalig ab. Wenn Du "includeInAllQuery" auf true setzt dann wird er in dem Interval was in den Settings steht aktualisiert ...

Falls Du Realtime willst muss ich dch aber enttäuschen weil Amazon das vernagelt hat.

Workaround: Lege per iot Adapter ein virtuelles gerät an und eine Reoutine die das gerät schaltet je nachdem was der sensor sagt ... dann geht das per Realitime

**Comment by tommyMX** [comment]
ja wollte realtime weil mein problem ist dass bei HUE noch nicht der neue Kontaktsensor drin ist :-( hatte schon an foxriver geschrieben würde auch unterstützen, weil ich mir 3 bestellt habe, weil diese Aqara und den deconz nicht am laufen bringe :-( 

deinen workaround probier ich nachher gleich :-) das wäre nice wenn das klappt...
