### ISSUE TITLE
Nach Ansprache mit Alexa

### ISSUE THREAD

**Issue by michaelxhoffmann** [Apollon77/ioBroker.alexa2#112]
Möchte ich das TV stumm schalten, damit Alexa nur meine Komandos hört, nicht die „Kommandos“ vom TV Gerät. Ich kann leider nicht Englisch schreiben, wegen der Autokorrektur. 🤔Die Antwort kann gerne auf englisch erfolgen.

**Comment by Apollon77** [comment]
Solche Fragen bitte im Forum bzw da wurde das mehrfach schon behandelt.

Tipp: Schau mal unter https://github.com/Apollon77/ioBroker.alexa2#alexa20history beim Feld "status"
