### ISSUE TITLE
Summary history incomplete

### ISSUE THREAD

**Issue by daniel-lo** [Apollon77/ioBroker.alexa2#1120]
Hi, I am a irritated. I had expected all alexa commands to be listed in the adapters Summary history but I only see very few. In fact I only see one command (bildschirm aus .. for echo show) and "null" a few times. But none of the commands that control e.g. routines. Why is that the case?

I have an additional conflict: When I say "alexa kochen" I want to control a switch in iobroker. Firstly the summary field is not updated with "kochen" (as mentioned above) and secondly alexa tells me that it cannot find a device named "kochen". Formerly this "command" had beed working but at some point it stopped (a while ago).

3.26.3

**Comment by Apollon77** [comment]
History only contains voice commands, not all commands.

Please do not rely on admin showing you the details of actions. there are cases where this updates too fast to see ... use a script to log whats really coming in. Else turn on debug logging to see what he adapter does. post examples here

**Comment by daniel-lo** [comment]
Alexa Starte FireTV --> iobroker skript
Skript wird ausgeführt
Feld Summary wird nicht geupdated --> steht noch "bildschirm aus" von gestern

Logfile (debug):

<html><body>

alexa2.0 | 2023-12-26 13:13:52.218 | debug | Alexa-Remote HTTP2-PUSH: Send Ping
-- | -- | -- | --
alexa2.0 | 2023-12-26 13:13:24.096 | debug | State  changed  alexa2.0.Echo-Devices.G091470400150342.Preferences.equalizerTreble:  {"val":0,"ack":true,"ts":1703592804092,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":1658155313047}
alexa2.0 | 2023-12-26 13:13:24.016 | debug | State  changed  alexa2.0.Echo-Devices.G091470400150342.Preferences.equalizerMidRange:  {"val":0,"ack":true,"ts":1703592804011,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":1658155313040}
alexa2.0 | 2023-12-26 13:13:24.013 | debug | State  changed  alexa2.0.Echo-Devices.G091470400150342.Preferences.equalizerBass:  {"val":0,"ack":true,"ts":1703592804008,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":1658155313033}
alexa2.0 | 2023-12-26 13:13:24.011 | debug | State  changed alexa2.0.Echo-Devices.G091470400150342.Player.muted:  {"val":false,"ack":true,"ts":1703592804007,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":1661702385418}
alexa2.0 | 2023-12-26 13:13:24.010 | debug | State  changed alexa2.0.Echo-Devices.G091470400150342.Player.volume:  {"val":27,"ack":true,"ts":1703592804007,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":1692788123883}
alexa2.0 | 2023-12-26 13:13:24.003 | debug | Alexa-Push-Connection Equalizer change for G091470400150342 -> 0/0/0
alexa2.0 | 2023-12-26 13:13:24.002 | debug | Alexa-Remote HTTP2-PUSH: Command PUSH_EQUALIZER_STATE_CHANGE: {     "dopplerId": {         "deviceSerialNumber": "G091470400150342",         "deviceType": "A30YDR2MK8HMRV"     },     "bass": 0,     "midrange": 0,     "treble": 0,     "destinationUserId": "A6K3TUW50YQL7" }
alexa2.0 | 2023-12-26 13:13:23.998 | debug | Alexa-Push-Connection Device Volume change for G091470400150342 -> 27/false
alexa2.0 | 2023-12-26 13:13:23.998 | debug | Alexa-Remote HTTP2-PUSH: Command PUSH_VOLUME_CHANGE: {     "dopplerId": {         "deviceSerialNumber": "G091470400150342",         "deviceType": "A30YDR2MK8HMRV"     },     "volumeSetting": 27,     "isMuted": false,     "destinationUserId": "A6K3TUW50YQL7" }


</body>
</html>

**Comment by Apollon77** [comment]
Ist es denn aktiviert inn den Settings? Sonst bitte mehr log ... das ist etwas kurz weil bestimmte aktionen einige Sekunden verzögert werden.

**Comment by daniel-lo** [comment]
Ich verstehe die Frage mit den Settings nicht .. wenn "Bildschirm aus" im Summary auftaucht .. dann sollte doch grundsätzlich alles richtig eingestellt sein. Ich schaue direkt ins Summary Feld unter dem History-Zweig .. nicht in die Objekthistory.

Ich musste gestern mein ioBroker allerdings auch auf ein neueres Basisimage portieren und nun fällt mir auf, dass bei Doppelklick auf das Feld im Titel in Rot "(Schreibgeschützt)" steht .. hier scheint es also noch wo zu haken.

Dennoch hab ich nochmal versucht mein "Wohnzimmer an" zu loggen:

<html><body>

alexa2.0 | 2023-12-27 09:21:36.964 | debug | State  changed alexa2.0.Echo-Devices.G091470400150342.Player.muted:  {"val":false,"ack":true,"ts":1703665296963,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":1703611721737}
-- | -- | -- | --
alexa2.0 | 2023-12-27 09:21:36.885 | debug | State  changed alexa2.0.Echo-Devices.G091470400150342.Player.volume:  {"val":27,"ack":true,"ts":1703665296878,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":1703611799304}
alexa2.0 | 2023-12-27 09:21:36.884 | debug | State  changed  alexa2.0.Echo-Devices.G091470400150342.Preferences.equalizerTreble:  {"val":0,"ack":true,"ts":1703665296877,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":1703611718389}
alexa2.0 | 2023-12-27 09:21:36.881 | debug | State  changed  alexa2.0.Echo-Devices.G091470400150342.Preferences.equalizerMidRange:  {"val":0,"ack":true,"ts":1703665296877,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":1703611718377}
alexa2.0 | 2023-12-27 09:21:36.879 | debug | State  changed  alexa2.0.Echo-Devices.G091470400150342.Preferences.equalizerBass:  {"val":0,"ack":true,"ts":1703665296877,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":1703611718370}
alexa2.0 | 2023-12-27 09:21:36.871 | debug | Alexa-Push-Connection Device Volume change for G091470400150342 -> 27/false
alexa2.0 | 2023-12-27 09:21:36.870 | debug | Alexa-Remote HTTP2-PUSH: Command PUSH_VOLUME_CHANGE: {     "dopplerId": {         "deviceSerialNumber": "G091470400150342",         "deviceType": "A30YDR2MK8HMRV"     },     "volumeSetting": 27,     "isMuted": false,     "destinationUserId": "A6K3TUW50YQL7" }
alexa2.0 | 2023-12-27 09:21:36.867 | debug | Alexa-Push-Connection Equalizer change for G091470400150342 -> 0/0/0
alexa2.0 | 2023-12-27 09:21:36.866 | debug | Alexa-Remote HTTP2-PUSH: Command PUSH_EQUALIZER_STATE_CHANGE: {     "dopplerId": {         "deviceSerialNumber": "G091470400150342",         "deviceType": "A30YDR2MK8HMRV"     },     "bass": 0,     "midrange": 0,     "treble": 0,     "destinationUserId": "A6K3TUW50YQL7" }


</body>
</html>

**Comment by daniel-lo** [comment]
Hab im Forum Unterstützung erhalten und bin jetzt insofern schlauer, dass das "Schreibgeschützt" völlig ok ist, weil man nicht selber ins Feld schreiben soll. ABER .. die Kehrseite ist, dass nach der Umstellung auf neues Base und Redis dort gar nichts mehr auftaucht - also auch nicht, der sonst zuverlässige "Bildschirm aus" Befehl.

**Comment by Apollon77** [comment]
Bitte einen Screenshot der Alexa2-Adapter Settings posten

**Comment by daniel-lo** [comment]
![grafik](https://github.com/Apollon77/ioBroker.alexa2/assets/4311558/ef8348fe-691f-48f1-97ed-f440bf7774b4)

**Comment by Apollon77** [comment]
Jupp ... Bitte changelog lesen bzw Upgrade infos ... "Fragen Sie Aktivität bei Geräteinteraktionen automatisch ab" ist deaktiviert ... ergo ... keine automatische History Abfrage ...

**Comment by daniel-lo** [comment]
Ja danke .. hat nicht sofort funktioniert .. aber jetzt geht es. Ist das nicht Push vs. Pull? Hätte gedacht ohne Haken geht es schneller. Außerdem weiß ich nicht genau was "App-Devices" sein sollen. Hört sich stark nach Handy-App an .. aber es ging ja auch ohne Handy nicht. Freue mich aber, dass sich jetzt was tut!
