### ISSUE TITLE
Webui aufruf in Instanzen funktioniert nicht mehr

### ISSUE THREAD

**Issue by Berli1960** [Apollon77/ioBroker.alexa2#1121]
iobroker - Instanzen - Adapter alexa2.0 - instanzlinks alexa2.0
Meldung von Webseite:

Hast du die App nicht installiert?
[Alexa-App herunterladen](market://details?id=com.amazon.dee.app)
[Gehe Zur Alexa-App](https://alexa.amazon.com/)

bitte korrigieren bzw entfernen.

**Comment by Apollon77** [comment]
Dann wird es entfernen weil Amazon die Seite abgeschaltet hat.

**Comment by JLemppi** [comment]
Hallo, ich habe das gleiche Problem.
Nach einer Passwort-Änderung bei Amazon war der Adapter alexa v. 3.26.3 rot. Der Link bei den 'ALEXA LOGIN DATEN' öffnet ein Fenster mit den Amazon Anmeldedaten. Nach Eingabe meiner Daten wird mir ein 6-stelliger Code per sms zugeschickt. Nach dessen Eingabe kommt der Fehler 404 Seite nicht gefunden und oben in der Adresszeile steht die IP-Adresse meines iobrokers gefolgt von ':46605/www.amazon.com/404'. Im Log-File steht nichts.

**Comment by Apollon77** [comment]
@JLemppi Du hast ein ganz anderes Problem. Lösung: RTFM? ;-)
https://github.com/Apollon77/ioBroker.alexa2#problem-with-cookie-determination-with-sms-based-2fa-flow

**Comment by JLemppi** [comment]
Danke Apollon77, das war's. Die 2FA Methode in Amazon aktiviert und schon funktionierte es :-)

**Comment by Apollon77** [comment]
fixed in 3.26.4
