### ISSUE TITLE
Use Login With Amazon for authentication

### ISSUE THREAD

**Issue by thohoj** [Apollon77/ioBroker.alexa2#1122]
**Is your feature request related to a problem? Please describe.**
Amazon strongly recommends that customers do not disclose any account information on pages that do not originate from Amazon itself. For example, users should never enter their password in a webview or web page whose URL does not refer to Amazon.com (de, ...). 
https://www.amazon.de/gp/help/customer/display.html?nodeId=G4CY3HAXTSFLGC22

For getting an the auth cookie I have to enter my credentials in a webview with an URL referring to a local server. This prevents me from using this adapter. 

**Describe the solution you'd like**
The better way would be a Login With Amazon button:
https://developer.amazon.com/de/docs/login-with-amazon/button.html

Wich diects you to an Amazon page to login, see example here:
https://developer.amazon.com/de/docs/login-with-amazon/conceptual-overview.html

After users log in, the client will use one of the [authorization grants](https://developer.amazon.com/de/docs/login-with-amazon/authorization-grants.html) to get an [access token](https://developer.amazon.com/de/docs/login-with-amazon/access-token.html). The client can then use the access token to access a [customer profile](https://developer.amazon.com/de/docs/login-with-amazon/customer-profile.html), specifying an access scope .

**Describe alternatives you've considered**
I tried to find an Amazon access token generator (like the GitHub one), but I haven't found one.

**Comment by Apollon77** [comment]
In theory you are correct, but please consider what this adapter does ... it uses undocumented inofficial APIs that are only used by the Amazon Alexa app to provide the same functionality. This means that no alternative login flow currently will gove you the permissions you need to access these services. Thats why the only way is exactly the approach we chose here. in fact username and password are processed by the adapter at that exact one timepoint where you enter them once to create the cookies and tokens and are NOT stored at all ... You can validate the code to see that this is true.
After this only the tokens received by this nitial login are used.

If you do not like this then you can not use this adapter.
