### ISSUE TITLE
Add datapoint for temperature sensor of Echo Gen. 5 devices

### ISSUE THREAD

**Issue by HanSolo72** [Apollon77/ioBroker.alexa2#1131]
The Echo Dot Generation 5 (the spherical one) provides the current room temperature in the Alexa app. It would be great to have the temperature also in a datapoint like alexa2.0.Echo-Devices.G090LF1180170XXX.Info.temperature.

At example, with that I could set my Fritz radiator controller based on this temperature (more accurate that the ones Fritz provides).

**Comment by Apollon77** [comment]
Look at the Smart Home devices objects in the adapter. it should be there
