### ISSUE TITLE
Alexa2 History Update is not working (since 24.01.2024)

### ISSUE THREAD

**Issue by unclebob1st** [Apollon77/ioBroker.alexa2#1132]
Hi,

when updating "alexa2.0.History.#trigger" (manually in "Objects"-view or by script) following request is send:

`alexa2.0	2024-01-24 19:16:45.780	debug	Alexa-Remote: Sending Request with {"host":"www.amazon.de","path":"/alexa-privacy/apd/rvh/customer-history-records?startTime=1706120145779&endTime=1706206605779&recordType=VOICE_HISTORY&maxRecordSize=3","method":"GET","timeout":10000,"headers":{}} `

causes following response:
`alexa2.0	2024-01-24 19:16:45.939	debug	Alexa-Remote: Response: No/Invalid JSON : <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/> <title>Seite wurde nicht gefunden</title> <style type="text/css"> a:link { font-family: verdana,arial,helvetica,sans-serif; color: #004B91; } a:visited { font-family: verdana,arial,helvetica,sans-serif; color: #996633; } a:active { font-family: verdana,arial,helvetica,sans-serif; color: #FF9933; } </style> </head> <body bgcolor="#FFFFFF" text="#000000" style="font-family: verdana,arial,helvetica,sans-serif;"> <!-- Um über den automatisierten Zugriff auf Amazon-Daten zu sprechen, wenden Sie sich bitte an api-services-support@amazon.com. Weitere Informationen über die Migration zu unseren APIs finden Sie in unseren Marketplace APIs unter https://developer.amazonservices.com/ref=rm_5_sv bzw. in unserer Product Advertising API, wenn es sich um Anwendungsfälle im Rahmen von Werbung handelt: https://affiliate-program.amazon.com/gp/advertising/api/detail/main.html/ref=rm_5_ac. --> <center> <a href="/ref=cs_404_logo"> <img src="https://images-eu.ssl-images-amazon.com/images/G/03/ShoppingPortal/logo._TTD_.png" alt="Amazon" border="0"/> </a> <table border="0" align="center" style="margin-top: 20px;"> <tr> <td> <img src="https://images-eu.ssl-images-amazon.com/images/G/03/x-locale/common/kailey-kitty._TTD_.gif" width="40" height="35" border="0"> </td> <td> <b style="color:#E47911">Suchen Sie etwas?</b> <br/> Tut uns leid.  Die eingegebene Webadresse ist keine funktionsfähige Seite auf unserer Website. <br/><br/> <img src="https://images-eu.ssl-images-amazon.com/images/G/03/x-locale/common/orange-arrow._TTD_.gif" width="10" height="9" border="0"> <b><a href="/ref=cs_404_link">Klicken Sie hier, um zur Amazon-Startseite zurückzukehren.</a></b> </td> </tr> </table> </center> </body></html><!-- 764fd722 -->`

**Problem:**
History is not getting updated 

**Expected behavior**  
"alexa2.0.History" is getting updated when "alexa2.0.History.#trigger" is triggerted

**Versions:**  
Alexa2.0: v3.26.3
Platform       : linux
os             : linux
Architecture   : x64
Node.js        : v18.19.0
NPM            : 10.2.3

**Comment by Apollon77** [comment]
Yes ... it seems amazon changed things, so history is broken right now

**Comment by Apollon77** [comment]
fixed in 3.26.4

**Comment by Ibanese** [comment]
Is history still working? I don't get any updates using the trigger

**Comment by m0rph2k** [comment]
> Is history still working? I don't get any updates using the trigger

same problem

**Comment by Manni-Pi** [comment]
The Trigger Button in History has no funktion. At 2 a clock this morning it worked fine. When i got up this morning there was no more funktion.

**Comment by tomtaz01** [comment]
Same Here

**Comment by fraeggle** [comment]
Same issue. Think Amazon has changed something again.

**Comment by Apollon77** [comment]
wow guys ... really? someone playing the "who find the oldest closed issue to write in"? ;-))

see #1164
