### ISSUE TITLE
Please consider fixing issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [Apollon77/ioBroker.alexa2#1134]
❗ [E506] Word "cookieAlt_info2" is not translated to german in [admin/words.js](https://github.com/Apollon77/ioBroker.alexa2/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations
 ❗ [E506] Word "cookieAlt_info2" is not translated to russian in [admin/words.js](https://github.com/Apollon77/ioBroker.alexa2/blob/master/admin/words.js). You can use https://translator.iobroker.in/ for translations

**Comment by Apollon77** [comment]
fixed locally, will come in next update
