### ISSUE TITLE
Device Type für neuen Echo Plus 2.Gen

### ISSUE THREAD

**Issue by xfjx** [Apollon77/ioBroker.alexa2#114]
Hi,

der Device Type für die neuen Echo Plus 2.Gen ist A18O6U1UQFJ0XK

den Echo Sub kann man eigentlich auch einzeln nutzen (zumindest um Sprache auszugeben?) daher hier auch die passende ID für den Echo Sub A3SSG6GR8UU7SN

Ich werde versuchen einen Pull Request damit zu machen nachdem ich getestet habe ob alles funktioniert.

**Comment by Apollon77** [comment]
Bitte die capabilities mit Posten. Und am Ende ist die Frage was genau per Alexa App geht. Wenn du in der Alexa App Sprachausgaben auf dieses device machen kannst dann gehen Kommandos sonst nicht

**Comment by xfjx** [comment]
Ja das geht - klingt halt nur nicht so gut auf dem Sub da er ja keinen Hochtöner hat. Aber vielleicht will es ja trotzdem wer machen.

Echo Plus 2.Gen: PERSISTENT_CONNECTION,ACTIVE_AFTER_FRO,PAIR_BT_SINK,GADGETS,ASCENDING_ALARM_VOLUME,SET_LOCALE,MICROPHONE,VOLUME_SETTING,AUDIBLE,PAIR_BT_SOURCE,AUDIO_PLAYER,DREAM_TRAINING,FAR_FIELD_WAKE_WORD,UPDATE_WIFI,TUPLE,CUSTOM_ALARM_TONE,REQUIRES_OOBE_FOR_SETUP,EARCONS,KINDLE_BOOKS,SUPPORTS_SOFTWARE_VERSION,ALLOW_LOG_UPLOAD,POPTART,GOLDFISH,DEREGISTER_DEVICE,SLEEP,TAHOE_BYOD,VOICE_TRAINING,SOUND_SETTINGS,CHANGE_NAME,FLASH_BRIEFING,AUX_SETTINGS,REMINDERS,LEMUR_ALPHA,PAIR_REMOTE,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,TUPLE_CATEGORY_A,TIMERS_AND_ALARMS

Echo Sub:
PERSISTENT_CONNECTION,ACTIVE_AFTER_FRO,SET_LOCALE,MICROPHONE,VOLUME_SETTING,AUDIBLE,AUDIO_PLAYER,UPDATE_WIFI,TUPLE,CUSTOM_ALARM_TONE,REQUIRES_OOBE_FOR_SETUP,EARCONS,KINDLE_BOOKS,TUPLE_CATEGORY_C,SUPPORTS_SOFTWARE_VERSION,ALLOW_LOG_UPLOAD,DEREGISTER_DEVICE,SLEEP,SOUND_SETTINGS,CHANGE_NAME,FLASH_BRIEFING,REMINDERS,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,TIMERS_AND_ALARMS

Der Sub hat aber kein Mikro daher wundert es mich, dass "MICROPHONE" in der Liste steht.

Habe die beiden mal in der main.js angelegt und soweit funktioniert alles. Pull request kommt

**Comment by xfjx** [comment]
ich hab die mal von allen geräten die ich hier stehen habe nachgetragen: echo dot 2.gen, echo, echo show, echo plus 2.gen, echo sub (ich bin "all in" bei alexa)

**Comment by Apollon77** [comment]
fixed by #115 Thank you! WIll come official with next update soon (TM) :)
