### ISSUE TITLE
Warnung beim schalten der States über Alexa

### ISSUE THREAD

**Issue by BenAhrdt** [Apollon77/ioBroker.alexa2#1151]
wenn ein state farben UND einen onOff state hat, erscheint beim Befehl:
Alexa, licht aus:

das hier:

`<html>
<body>

iot.0 | 2024-03-17 14:53:00.079 | warn | [ALEXA] Cannot controlOnOff: Error: Won't control alias.0.Talstrasse1A.Logik.stateSpotSideboard as we have a switch available
-- | -- | -- | --

</body>
</html>`

**Comment by Apollon77** [comment]
nothing iot related ... logged by iot
