### ISSUE TITLE
Cookie erstellen geht nicht mehr.

### ISSUE THREAD

**Issue by rsl99de** [Apollon77/ioBroker.alexa2#1162]
das Erstellen eines neuen Cookies funktioniert nicht mehr.
Wenn man versucht über den Link im Adapter einen neuen Cookies zu erzeugen landet man nach dem Login auf einer Amazon-Seite mit der Fehlermeldung 404.
Laut Google hat Amazon ende 2023 die Webversion von alexa.amazon.de abgeschaltet.

Wie komme ich jetzt an einen neuen Cookie ?

**Comment by Matzebhv** [comment]
Selbes Problem hier, nach der Amazon-Störung gestern wird ein neuer Cookie verlangt, das erzeugen funktioniert aber nicht mehr.

**Comment by Matzebhv** [comment]
So, Kommando zurück. Mein Konto war noch mit SMS-Verifizierung versehen. Aus der Anleitung:

If you still use the SMS/E-Mail based 2FA flow, then this might not work. Please update the 2FA/OTP method in the amazon settings to the current process! Not working could also mean that a Error 404/Page not found is shown. ALso then check and upgrade OTP settings!

Nach Umstellung auf MFA mit dem Google-Authenticator funktioniert das wieder einwandfrei.
