### ISSUE TITLE
History is not updating any longer (since 16.4.24)

### ISSUE THREAD

**Issue by IchBinSmart** [Apollon77/ioBroker.alexa2#1164]
**Check if the Bug maybe is with Amazon**  
The adapter is using the same API as the Alexa mobile App. This means:
* If you can not do this what you want with the App then the Adapter also can not do it!
* Also if the App can do it please test if the same effect then the bug also happens with the App (e.g. a speak command do not work on a certain device ... can you do a speak via Alexa App? If not - Amazon problem!)

> I have checked this - alexa app is showing the activities

**Describe the bug**  
Alexa Adapter doesn't provide a history any longer. See debug log attached. In the alexa app it is still working. I tried the following:

1. Get new cookies
2. Trigger the update manually using the DP
3. In Alexa App commands are shown in history
4. Push connection is enabled - everything in adapter is on standard settings.

**To Reproduce**  
Talk to alexa, check if history json or summary gets updated.

**Expected behavior**  
history json or summary should update.

**Screenshots & Logfiles**  
I attached logfiles from debug (start of adapter until voice command)

**Versions:**  
 - Adapter version: 3.26.4
 - JS-Controller version: <js-controller-version> 5.0.19
 - Node version: <node-version> v18.20.2
 - Operating system: Debian

**Additional context**

**Comment by IchBinSmart** [comment]
updating log
[alexa20.pdf](https://github.com/Apollon77/ioBroker.alexa2/files/15000721/alexa20.pdf)

**Comment by IchBinSmart** [comment]
[alexa20.zip](https://github.com/Apollon77/ioBroker.alexa2/files/15000739/alexa20.zip)

... udpdating log file...

**Comment by Apollon77** [comment]
Please try GitHub version ... Release will come as soon as I have one other info that it works again

**Comment by DariusM73** [comment]
@Apollon77 works as before (using workaround to trigger an update)

**Comment by DariusM73** [comment]
@Apollon77 thanks for the hot fix !

**Comment by HartmutKr** [comment]
@Apollon77 funktioniert wieder alles wie gewohnt! Danke Apollon für deine super Arbeit!
