### ISSUE TITLE
Amazon cockie kann nicht generiert werden 

### ISSUE THREAD

**Issue by 007Schneiderlein** [Apollon77/ioBroker.alexa2#1165]
oooohhhh man diese Amazon's...

Hi @Apollon77,

seit gestern hat alexa wieder nicht mit meinem iobroker via History gesprochen.... Da ihr schon fleißig wart 👌💪🙏, habe ich soeben eure Aktualisierung 3.26.5 aufgespielt,  leider ohne Erfolg.
Ich habe dann nochmal meinen Cookie erneuern wollen und bekomme dann diese Fehlermeldung 
<img width="401" alt="image" src="https://github.com/Apollon77/ioBroker.alexa2/assets/109386047/f898ec25-a688-4d80-8f11-50b423273d97">

vielleicht habt ihr ja nochmal Zeit... 

Wieso zerstört Amazon immer wieder diese offizielle API Schnittstelle?  Das ist ja echt frustrierend... insbesondere für Euch. 
Derzeit funktioniert ja diese Api (Aktualisierung der Summary) auch nur mit Hilfe des IOT Adapters, den ich über Routinen an triggere. 

Gibt es denn ggf. eine Kostenpflichtige-Alternative? 

Also nochmal allerbesten Dank für eure unermüdlichen Bemühungen den Adapter immer wieder an die laienhafte Amazon Schnittstelle anzupassen. 

Beste Grüße Stefan

**Comment by Apollon77** [comment]
Das Funktioniert ... Du hast voraussichtlich noch das alte SMS 2FA oder so aktiviert. Bitte das neue nutzen und dann gehts

**Comment by Apollon77** [comment]
hmm ;-)) https://github.com/Apollon77/ioBroker.alexa2?tab=readme-ov-file#problem-with-cookie-determination-with-sms-based-2fa-flow
