### ISSUE TITLE
Problem nach Update

### ISSUE THREAD

**Issue by Henny4184** [Apollon77/ioBroker.alexa2#1168]
**Check if the Bug maybe is with Amazon**  
The adapter is using the same API as the Alexa mobile App. This means:
* If you can not do this what you want with the App then the Adapter also can not do it!
* Also if the App can do it please test if the same effect then the bug also happens with the App (e.g. a speak command do not work on a certain device ... can you do a speak via Alexa App? If not - Amazon problem!)

**Describe the bug**  
A clear and concise description of what the bug is. Especially describe what you verified using the Alexa App (see above).

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Henny4184** [comment]
Kann mir einer helfen habe nach dem Update das Adapters Folgende Fehlermeldung.
Raspi 4 
JS 18.20.2
NPM 10.5.0
Alexa 3.26.5

![grafik](https://github.com/Apollon77/ioBroker.alexa2/assets/66122139/f0603916-7278-4ccd-b476-ab7689a621cd)

**Comment by Kaijur** [comment]
Dem schließe ich mich an:

Raspi 4
JS 18.20.2
NPM 10.5.0
Alexa 3.26.5

Sogar die Fehlermeldung ist identisch.

**Comment by Henny4184** [comment]
Habe alles neue aufgesetzt, nun läuft das ganze wieder ohne Probleme . Es soll wohl Probleme gegeben haben gestern und mir wurde im Forum empfohlen einmal neu aufzusetzen ..
