### ISSUE TITLE
Unknown Device Type AVE5HX13UR5NO

### ISSUE THREAD

**Issue by pixelos-cc** [Apollon77/ioBroker.alexa2#117]
Ich erhalte in den Logs die folgende Meldung zu einem unbekannten Alexa Gerät:
Device-type:AVE5HX13UR5NO (SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,TUNE_IN,MICROPHONE,AUDIO_PLAYER,TIMERS_AND_ALARMS,PEONY,GOLDFISH,DEREGISTER_DEVICE,AUDIBLE,AMAZON_MUSIC,PERSISTENT_CONNECTION,KINDLE_BOOKS,CHANGE_NAME,I_HEART_RADIO,SLEEP,DREAM_TRAINING,VOLUME_SETTING)

Es handelt sich um einen Zero Touch von Logitech. Eine Art kleiner Bluetooth Dongle mit Handy Halterung für's Auto. Damit kann ich im Auto Alexa auf meinem Handy nutzen (nachdem ich den Zero Touch mit einer Geste aktiviert habe).

Brauchst du noch mehr Infos?

**Comment by Apollon77** [comment]
Übernehme ich in nächster Version, gehe aber davom aus das der keine Kommandos haben kann
