### ISSUE TITLE
Wrong type "mixed" for alarm ".enabled"?

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#1173]
I wonder if the type for

alexa2.0.Echo-Devices.XXX.Alarm.???.enabled shouldn't be "boolean" instead of "mixed", as it can be set to "true" and "false"... =)

**Comment by Apollon77** [comment]
In code and also in my system it it boolean with role "switch.enabled". Are you sure? Can ypou please post a screenshot? And please also try a new Alarm

**Comment by padrino-x** [comment]
Have deleted all dead corps and retried and the problem seems gone.
Will close this for now...
Sorry.
