### ISSUE TITLE
Error getting equalizer setting: Error: Timeout

### ISSUE THREAD

**Issue by weindler** [Apollon77/ioBroker.alexa2#1176]
Seit geraumer Zeit bekomme ich hin und wieder diesen Fehler, kann da leider ncihts anfangen.

`Error getting equalizer setting: Error: Timeout`

`Adapter Version 3.26.5`

`Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 4
Geschwindigkeit: 2808 MHz
Modell: Common KVM processor
RAM: 9.7 GB
System-Betriebszeit: 1 T. 08:08:04
Node.js: v18.20.4
time: 1721052959834
timeOffset: -120
NPM: 10.7.0`

Weiß da jemand was?

**Comment by Apollon77** [comment]
That ,eans that the amazon servers did not answred within 10s to the request ... if it comes in between sometimes just ignore because weill be updated later. If it come constantly then might be work to look into it
