### ISSUE TITLE
History is empty

### ISSUE THREAD

**Issue by planetofrock** [Apollon77/ioBroker.alexa2#1178]
Hello,
I haven't used the adapter for a long time and have now brought it back to life. However, I noticed that no value is stored in "History" anymore. In particular "Echo device name" would be important to me. Is this issue known?

**Comment by Ilovegym66** [comment]
To answer the question, we need all informations about the system, the version of the adapter, version of nodejs, js-controller. Additional provide your config in the adapter as a screenshot, too, please.

**Comment by Apollon77** [comment]
Assumption: @planetofrock updated the adapter but did not read the changelog and the warning that appeared on upgrade ... so he has not enabled the "Get history data" option in the settings that exists since roughly a year now :-)

**Comment by planetofrock** [comment]
/usr/bin/nodejs
v18.20.4
/usr/bin/node
v18.20.4
/usr/bin/npm
10.7.0

@Apollon77 I read the changelog and also activated the history in the settings. However, no entries are shown to me
![grafik](https://github.com/user-attachments/assets/d8f68baf-c997-455e-ac39-1a5f20042b62)

**Comment by planetofrock** [comment]
I installed the adapter again and updated the cookies. Now it seems to be working. Sorry for the false report. Something seems to have gone wrong with the update
