### ISSUE TITLE
Echo Dot 3.Generation Command

### ISSUE THREAD

**Issue by PixelTomsen** [Apollon77/ioBroker.alexa2#118]
Ich habe ein kleines Patch hinterlegt für die Erkennung des neuen EchoDot 3.Generation, damit auch dieser 'kommandiert' werden kann. :-)

[0001-Added-Echo-Dot-3.Gen-Icon.zip](https://github.com/Apollon77/ioBroker.alexa2/files/2479497/0001-Added-Echo-Dot-3.Gen-Icon.zip)

**Comment by Apollon77** [comment]
Schick doch einfach einen PR ... einfacher als der Patch ... den kann ich nicht anwenden weil er einige Umlaut im Encoding kaputt macht wie es scheint :-(

**Comment by PixelTomsen** [comment]
ok :-)

**Comment by dude2k** [comment]
Hallo zusammen,
gibt es zu diesem Thema Neuigkeiten? Bisher wird der Echo Dot 3 ebenfalls nur teilweise erkannt. Icon und viel wichtiger der Ordner "Commands" fehlt noch.

Gruß und danke für die Mühe

**Comment by Apollon77** [comment]
Kannst vom Github installieren, dann sollte das erstmal drin sein bis ich dazu komme noch den Rest zu machen

**Comment by dude2k** [comment]
Hat funktioniert, danke!
