### ISSUE TITLE
CLOSED: Unable to have Contacts synched to alexa2.0.Contacts.ContactId.*

### ISSUE THREAD

**Issue by LuxBibi** [Apollon77/ioBroker.alexa2#1187]
Hi all,

First, thanks for this great adapters, you all do set-up for this amazing ioBroker community ... I am an ioBroker since 6 years ... Almost no problems encountered so far ... Top ;-)

This "problem" I now encounter with the ioBroker/alexa2 adapter might be a configuration issue on my side ... 

My initial goal is to have ioBroker being able to light up the **yellow light** on all my 9 echo devices with an message ... as described on the alexa2.0 adapter page.

<html>
<body>
<div class="markdown-heading" dir="auto" style="box-sizing: border-box; position: relative; color: rgb(255, 255, 255); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(1, 4, 9); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 tabindex="-1" class="heading-element" dir="auto" style="box-sizing: border-box; margin-top: var(--base-size-24); margin-bottom: var(--base-size-16); font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25;">alexa2.0.Contacts.ContactId.*</h3><a id="user-content-alexa20contactscontactid" class="anchor" aria-label="Permalink: alexa2.0.Contacts.ContactId.*" href="https://github.com/Apollon77/ioBroker.alexa2?tab=readme-ov-file#alexa20contactscontactid" style="box-sizing: border-box; background-color: transparent; color: var(--fgColor-accent, var(--color-accent-fg)); text-decoration: underline; float: left; padding-right: var(--base-size-4); margin: auto; line-height: 1; position: absolute; top: 12.5px; left: -28px; display: flex; width: 28px; height: 28px; border-radius: var(--borderRadius-medium); opacity: 0; justify-content: center; align-items: center; transform: translateY(-50%); text-underline-offset: 0.2rem;"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z"></path></svg></a></div><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: var(--base-size-16); color: rgb(255, 255, 255); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(1, 4, 9); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">All Alexa-Contacts that can be used to send Text Messages to, including himself. The own contact gets a special "(Self)" after his name.</p><markdown-accessiblity-table data-catalyst="" style="box-sizing: border-box; display: block; color: rgb(255, 255, 255); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(1, 4, 9); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
State name | meaning
-- | --
#clearOwnMessages | Only exists in own contact and a trigger deletes all messages that are send to himself (also includes messages to himself via App or devices!)
textMessage | Sends this text as message to the user. It is shown on all devices of this user with a "yellow ring"

</markdown-accessiblity-table>
</body>
</html>

I therefore need to have the contacts in my object! This seams to be the only solution as far as I was able to find in these week I was searching for any solutions making this feasible.

I am using the alexa adapter since years .. with all the other functionalities .. All worked fin .. So not a basic configuration issue of the ioBroker alexa adapter.

I was looking to ioBroker side, if anything may disable the contacts synchronisation. Nothing found. I was looking at Amazon and Alexa-APP side ... Did not find the magical switch after changing quite a lot .. :-( ...

Today I changed the localisation of all my devices to Amazon.com ... Nope .. I was there even not able to get the adapter starting ... 
So I moved them back to the german Amazon.de .. 

My last chance to either find an alternative to get these yellow rings light up, or to have the contacts synched to my objects is the ioBroker community ... 

Hope this is the right place to submit this kind of "problem" ... as it is more a misconfiguration issue, I presume .. 

Just let me know if some more information is to be posted.

Thanks in adavance,

Luc from Luxemburg

Configuration details ...
- ProxMox Cluster with Buanet/ioBroker docker running in a Debian LXC container.
- Have also tested ioBroker within an LXC container with the [Proxmox VE Helper Scripts template](https://tteck.github.io/Proxmox/#iobroker-lxc), and just activating the Alexa2.0 adapter. (Stopped during the tests, my PROD-Alexa2.0 Adapter)

**Info Copy/Paste from ioBroker-Info:**
Platformoperating system:linux
Architecture:x64
CPUs:8
Speed:4099 MHz
Model:Intel(R) Core(TM) i7-9700T CPU @ 2.00GHz
RAM:62.6 GB
System uptime:9 d. 12:30:43
Node.js:v18.20.4
time:1728119469516
timeOffset:-120
NPM:10.8.2
adapters count:543
Disk size:8.0 GB
Disk free:4.0 GB
Active instances:36
Path:/opt/iobroker/
Uptime:2 d. 22:16:06
alive:true
_nodeCurrent:18.20.4
_nodeNewest:18.20.4
_nodeNewestNext:20.18.0
_npmCurrent:10.8.2
_npmNewest:10.7.0
_npmNewestNext:10.8.2

ioBroke/alexa2.0 adapter (one single instance) v3.26.5

**Objects synched in my ioBroker objects:**
![2024-10-05 12 57 39](https://github.com/user-attachments/assets/eb3f0f34-4141-46b1-ab85-a11e45713627)

**Objects I see in different videos ...** (Maybe this is no more the case with the actual adapter? But I wonder then why it is documented?)
![2024-10-05 13 00 16](https://github.com/user-attachments/assets/76d10a3b-7e60-4d62-b016-f01369821776)

**Comment by Apollon77** [comment]
Please turn loglevel to debug ... let adapter restart ... (will log a lot), then when logging gets ok and all is good (can take some minutes!! an till then no commands are executed!) es muss ein Info log kommen mit states subscribed oder so.

Dann die Aktion(en) versuchen die nicht gehen. Am besten Uhrzeit aufschreiben das ich es direkter suchen kann im Log. Dann das ganze Log mit debug als text attachement an eine mail an mich an iobroker@fischer-ka.de mit Angabe dieses issue links hier ...dann schau ich mal rein

**Comment by LuxBibi** [comment]
Hallo @Apollon77 ,
Danke für die Rückmeldung. Werde ich durchführen. 

Zu Deiner Antwort,
_".... 
Dann die **Aktion(en) versuchen die nicht gehen**. Am besten Uhrzeit aufschreiben das ich es direkter suchen kann im Log. Dann das ganze Log mit debug als text.... "_

Wohl bemerkt, dass alles super funktioniert. Ausser die Kontakte sind nicht verfügbar. Mein "Problem" ist, wie hier oben beschrieben, dass die Kontakte nicht in die ioBroker Objekte ünernommen werden, und ich somit, keine Messages an mich selbst schicken kann. (Möchte an alle meine Echo Devices eine Message schicken, damit der gelbe Ring aufläuchtet)

Falls ich zu diesme spezifischem Problem was zusätzlich Dir schicken soll, dann einfach Bescheid geben.

Luc

**Comment by LuxBibi** [comment]
@Apollon77 
Mail mit Info wurde am iobroker@fischer-ka.de verschickt.

Lass es mich wissen wie ich Dir weiterhelfen kann, die Ursache zu den fehlenden Kontakten in den ioBroker Objekten zu finden.

Luc

**Comment by Apollon77** [comment]
Danke. Schaue nachher ob angekommen. Kann aber paar Tage dauern bis ich wirklich dazu komme rein zu schauen. Solingen Orga frisst grad einiges an Zeit.

**Comment by LuxBibi** [comment]
Hallo @Apollon77 ,
Hoffe die E-Mail ist gut angekommen, und all die von dir benötigten Inhalte sind drin?
Lass es mich wissen, sollte noch was nachgeschoben werden.
M.f.G
Luc

**Comment by LuxBibi** [comment]
Hallo @Apollon77 ,

Ich nehme kurz wieder kontakt mit Dir auf ... Möchte definitiv kein Stress machen! Ich weiß anhand aller Beiträge wo ich Dich referenziert sehe, dass Du gut sehr beschäftigt bist. Jedoch ist die Nutzung dieser Funktion, mir ein Message selbst zu schicken, die einzige Lösung die ich sehe, um alle meine Amazon Echos einzubinden, und den gelben Ring als visuelle LED zu aktivieren
.
Wollte deswegen nur nachfragen, ob anhand Deiner Prioliste, die ja nur du kennst, du bereits jetzt weiß, ob du überhaupt irgendwann die Zeit finden wirst hier kurz reinzuschauen, oder ob dies so eine niedrige Prio hat, dass dies ggfls. nie untersucht wird?

Solltest du dies in Deiner Pipeline haben, und dass es noch dauern wird, so werde ich warten, da ich aktuell keine andere Lösung sehe. 

Danke so weit für den Adapter. Die restlichen Funktionailäten funktionieren hervoragend seit seh langer Zeit ;-) 👍 ..

**Comment by Apollon77** [comment]
Ich habe oben geschrieben das es vor Solingen eher unwahrscheinlich ist. Also frühestens Mitte November nach aktuellem Stand.

**Comment by LuxBibi** [comment]
Hi @Apollon77 ,

Gute Nachrichten meinerseits ;-) .. Die Zeit hast du jetzt gewonnen. ;-) .. 

Ich habe Heute nochmals reingeschaut, und die Lösung gefunden! "Contacts", wie hier unten zu sehen, sind jetzt verfügbar
![2024-12-04 Resolved Contact Issue](https://github.com/user-attachments/assets/8b67fe20-e949-4755-9d70-cf127775699a)

Ich habe auf der Amazon.de Seite alle Alexa Einträge gelöscht! Den Adapter gestoppt. Neues Token angefordert und kontrolliert, dass dieser als Einziger/Erster Eintrag nun auf der Amazon.de/Geräte Seite vorhanden war.

Nach einer Weile sind die Geräte, ... und etwas später auch die Kontakte ...

Hab's jetzt grad fertig Programmiert. Läuft tadellos.

ioBroker ist einfach Spitze, mit der ganzen Flexibilität. Einfach TOP!

Danke an Dir, und der ganzen ioBroker-Entwickler Crew die manchmal bestimmt auch schwierigeren Zeiten so tapfer zu überstehen (Siehe André mit seinem Buanet/ioBroker docker) ... 

Desto flotter ist es, so wie alle an einem Strang ziehen.

Dir alles Gute auf dies Reise ;-)

**Comment by Apollon77** [comment]
Dabke und interessant das es sich selbst gefixt hat ... naja vllt soch ein Amazon Problem .. DANKE für Deine geduld
