### ISSUE TITLE
Frage: Skills ausführen

### ISSUE THREAD

**Issue by Moormerlander** [Apollon77/ioBroker.alexa2#119]
Ich habe mein VIS für den Echo Show angepasst und möchte den Silk-Browser per Adapter-Command aufrufen. Geht das?

**Comment by Apollon77** [comment]
Wenn Du es per Sprachkommando von einem anderen Echo Gerät aus machen kannst dann ja - per Bespeoken. Sonst nicht

**Comment by Moormerlander** [comment]
Wo finde ich das die Objekteigenschaft "bespoken"?

**Comment by Apollon77** [comment]
Musst Du zuerst im Adapter in der Instanzkonfiguration aktivieren

**Comment by Moormerlander** [comment]
OK, vielen Dank.
Habe einen Token und Bespoken aktiviert. 
Leider kann ich Silk nicht auf einem Echo Show starten, aber ich forsche weiter.
