### ISSUE TITLE
Adapter startet nicht mehr nach Update -fixed by 3.26.7

### ISSUE THREAD

**Issue by Kampfratte** [Apollon77/ioBroker.alexa2#1196]
alexa2.0 | 3123 | 2024-10-21 13:28:18.109 | info | starting. Version 3.26.6 in /opt/iobroker/node_modules/iobroker.alexa2, node: v22.5.1, js-controller: 7.0.0

alexa2.0 | 3123 | 2024-10-21 13:28:19.234 | error | uncaught exception: Sentry.configureScope is not a function

alexa2.0 | 3123 | 2024-10-21 13:28:19.235 | error | TypeError: Sentry.configureScope is not a function at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/main.js:557:16) at processImmediate (node:internal/timers:485:21)

alexa2.0 | 3123 | 2024-10-21 13:28:19.236 | error | Sentry.configureScope is not a function

alexa2.0 | 3123 | 2024-10-21 13:28:19.434 | info | terminating

alexa2.0 | 3123 | 2024-10-21 13:28:19.436 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason

alexa2.0 | 3123 | 2024-10-21 13:28:19.939 | info | terminating

host.iobroker |   | 2024-10-21 13:28:20.057 | error | instance system.adapter.alexa2.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

nach Update auf 3.26.6 und Adapter startet auch nicht mehr. Bin wieder auf die 3.26.5 zurück. Da lief er

**Comment by JF62** [comment]
same here

**Comment by zaphod2** [comment]
Bei mir genau das selbe.

**Comment by KhaosRipper** [comment]
gleiche bei mir auch

**Comment by Joylancer** [comment]
bei mir auch, zurück auf 3.26.5 - wieder io

**Comment by de3d0300** [comment]
bei mir auch, bin auch wieder zurück auf 3.26.5

**Comment by McR1983** [comment]
jep, auch zurück dann gehts wieder

**Comment by Apollon77** [comment]
Hey, bitte versucht msl die GitHub version. Also Install from GitHub über Custom install ... Adapter sollte dann neu starten. gehts dann?

**Comment by McR1983** [comment]
> Hey, bitte versucht msl die GitHub version. Also Install from GitHub über Custom install ... Adapter sollte dann neu starten. gehts dann?

Hey nein, immer noch restart loop

2.0
	2024-10-24 13:00:21.132	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
alexa2.0
	2024-10-24 13:00:21.131	info	terminating
alexa2.0
	2024-10-24 13:00:21.115	error	Sentry.configureScope is not a function
alexa2.0
	2024-10-24 13:00:21.115	error	TypeError: Sentry.configureScope is not a function at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/main.js:557:16) at processImmediate (node:internal/timers:485:21)
alexa2.0
	2024-10-24 13:00:21.114	error	uncaught exception: Sentry.configureScope is not a function
alexa2.0
	2024-10-24 13:00:19.037	info	starting. Version 3.26.6 in /opt/iobroker/node_modules/iobroker.alexa2, node: v20.18.0, js-controller: 7.0.1

**Comment by Apollon77** [comment]
Dann hat er nicht aktualisiert ... Zeile 557 siht auf GitHub ganz anders aus. Das ist der alte code

**Comment by McR1983** [comment]
> Dann hat er nicht aktualisiert ... Zeile 557 siht auf GitHub ganz anders aus. Das ist der alte code

sorry hast recht, am Handy aus versehen dann npm install gewählt anstatt git...

Jetzt sieht gut aus, er bleibt grün

**Comment by Apollon77** [comment]
Ok, dann release ich mal
