### ISSUE TITLE
E-Mails with + in them do not work.

### ISSUE THREAD

**Issue by Garfonso** [Apollon77/ioBroker.alexa2#12]
My E-mail for amazon login cotains the + sign. The adapter seems not to encode it correctly. If I enter it just as is in the settings, login fails.
If I replace the + by %2B (i.e. the correct url encoding), then login works.

But now I am stuck at captcha page. I tried the proxy, but it complains: "2018-07-21 22:51:36.224  - error: alexa2.0 Error: Alexa-Cookie: Email entered on Login Page via Proxy differs from set email! You should use the same email to allow automatic cookie retrieval."
Which is because I entered the + sign again, which is of course necessary in the browser, because the browser encodes the + correctly. 

This might affect other symbols in e-mail addresses, too. It seems a lot of stuff is allowed in the local part ( https://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-an-email-address ). But the + is quite common for filtering purposes. Probably similar issues arise if someone tries to use an umlaut domain? I can try that, if you want.

**Comment by Garfonso** [comment]
Ah, ok. Then I misinterpreted the message. I did the login today and you are right, it works fine.

I think you should call encodeURIComponent on the local part of the e-mail address before sending it to amazon.

**Comment by Apollon77** [comment]
I changed exactly that in my local version already. It seems that the used library (querystring) do not encode + at all because considers already encoded (+ -> " ") ... not well documented :-(

Please monitor thread in Forum to get the next oficial update and please remove your cookie and test again. That would be awesome

**Comment by Garfonso** [comment]
Hi,
I did test it again (deleted cookie, added my e-mail with + in instance settings) and it now worked fine. :-)

**Comment by Apollon77** [comment]
Cool, thanks!
