### ISSUE TITLE
Anmeldung nicht möglich

### ISSUE THREAD

**Issue by Domi920** [Apollon77/ioBroker.alexa2#1201]
Hallo,
als vor 3 Tagen die Anmeldung mit dem Alexa Adapter scheiterte, habe ich aus Sicherheitsgründen bis heute gewartet.
Leider klappt die Anmeldung wieder nicht.
Nachdem ich den Adapter starte lese ich schon im Log folgende Meldung:

Error from Alexa init: Please open http://192.162.2.9:35317/ with your browser and login to Amazon. The cookie will be output here after successfull login.

Wenn ich die Seite in einen externen Tab öffne, werde ich auf die Seite zur Eingabe der E-Mail Adresse geleitet.
Anschließend muss man das Passwort eingeben. 
Danach kann man den Code (per SMS Versand) eingeben und wenn man dann auf weiter klickt kommt folgendes Bild:
![image](https://github.com/user-attachments/assets/a963271e-1a10-475b-8ef4-4b5f8b7570b2)

Ich habe auch schon mal die komplette Instanz gelöscht & neu erstellt.
Das Fehlerbild bleibt immer das gleiche.

Das Debug Log habe ich gespeichert & könnte ich per E-Mail versenden.
Aber ich denke dass der Fehler leicht nachsimuliert werden kann.

 Hier noch meine System Daten:
 Adapter Version: 3.26.7 
Plattform
    linux
Betriebssystem
    linux
Architektur
    arm64
CPUs
    4
Geschwindigkeit
    1800 MHz
Modell
    Cortex-A72
RAM
    7.63 GB
System-Betriebszeit
    64 T. 02:20:09
Node.js
    v18.19.0 (Es gibt eine neuere Version: v18.20.4)
time
    1731354443389
timeOffset
    -60
NPM
    10.2.3
Anzahl der Adapter
    545
Datenträgergröße
    458.18 GB
freier Festplattenspeicher
    436.24 GB
Aktive Instanzen
    37
Pfad
    /opt/iobroker/
Betriebszeit
    64 T. 02:30:36
Hostname
    raspberrypi

**Comment by Domi920** [comment]
@Apollon77 wollte kurz nachfragen, ob dir das Anmeldeproblem bekannt ist?
Gruß Dominik

**Comment by RicoAeckerle** [comment]
Ich wollte das auch gerade machen da ich meinen ioBroker neu aufsetze und das Backup mit dem Serverumzug irgendwie nicht zum laufen bekomme... egal.

Bei mir hat es geklappt weil, ich aufm Handy in der Amazon-App gesehen habe, dass es Anmeldeversuche gab, diese beiden Meldungen habe ich dann "genehmigt" und dann habe ich einen weiteren Versuch gestartet. Nach der Eingabe des Passwortes kam dann immer ein 6 stelliger PIN per SMS und diesmal hatte ich aber die Amazon App im Fokus und wollte zwar gerade den PIN eingeben, habe dann aber einfach auf dem wieder auftauchenden Fenster bezüglich Anmeldeversuch auf genehmigen gedrückt. Dadurch musste ich den PIN nicht eingeben, bzw hatte ich das Gefühl dass vor der [ENTER] Taste, die Anmeldung schon erledigt war.

Kurzum, startet mal eure Amazon App aufm Smartphone und schaut ob euch das hilft. Ich bin drin.

**Comment by nschinagl** [comment]
Hi,

Ich hatte das selbe Problem, aber über die Amazon App am Smartphone (Benachrichtigungen) hat es bei mir auch geklappt. Danke.

**Comment by Domi920** [comment]
Vielen Dank für die schnelle Hilfe!

Habe die Amazon App geöffnet und den Anmeldevorgang im Adapter gestartet.
Nach Eingabe der E-Mail Adresse & des Passwortes habe ich in der Amazon App bzw. Benachrichtigung von Amazon auf genehmigen getippt. 
Der Anmeldeprozess war erfolgreich & das SMS Passwort brauchte ich nicht mehr.


Mein Fehler war es immer, erst das Passwort das per SMS geschickt wurde einzugeben & danach auf Genehmigen zu tippen.
Andere Reihenfolge ist richtig & dann funktioniert es auch.


Vielen Dank nochmal!

**Comment by harrysam** [comment]
@Domi920 
Hi, ging es bei dir um diesen Link "Bitte den [folgenden Link zur einmaligen Anmeldung im Amazon-Konto](http://192.168.188.123:35000/) nutzen, um die Adapterverbindung zu Ihren Alexa-Geräten zu aktivieren."? 
Ich habe dann auf der folgenden Seite den Fehler "Proxy-Error: Error: connect ENETUNREACH 18.239.70.223:443 - Local (0.0.0.0:0)". 
Von welcher Amazom-App ist hier die Rede, Amazon Shopping oder Amazon Appstore oder Amazon Assistent oder noch eine andere? 
Bei meinem Anmeldeproblem kannst du mir wohl nicht helfen, aber vielleicht kannst du mir meine letzte Frage beantworten. 
Wenn mir die App nicht weiterhilft, dann muss ich wohl selbst mal ein issue aufmachen. 
Danke im Voraus

**Comment by RicoAeckerle** [comment]
@harrysam also bei mir war es die ganz normale Amazon Shopping app auf meinem Samsung (Android) Smartphone. Dort war ich natürlich mit meinem Account eingeloggt mit welchem ich dann auch die Verbindung vom ioBroker zu Amazon Alexa herstellen wollte.

**Comment by Apollon77** [comment]
Wie wäre es mal Readme zu lesen??

https://github.com/Apollon77/ioBroker.alexa2?tab=readme-ov-file#problem-with-cookie-determination-with-sms-based-2fa-flow

:-))
