### ISSUE TITLE
Echo Plus 2nd Gen - Commands not showing up

### ISSUE THREAD

**Issue by LilaQ** [Apollon77/ioBroker.alexa2#123]
Hi there,

sadly the "Commands" folder is not showing up for my Echo Plus 2nd Gen :/ 
Any quick fix for this?

Thanks in advance

**Comment by Apollon77** [comment]
Please check the logs on start of the adapter. There you should find Infos to send to me ....

**Comment by Apollon77** [comment]
install update vom Githbu
