### ISSUE TITLE
Echo Show 2. Generation Commands / Routines

### ISSUE THREAD

**Issue by beckerpa** [Apollon77/ioBroker.alexa2#125]
Hallo, hoffe ich bin hier richtig...
Habe zwei neue Echo Shows, dort tauchen Commands und Routines nicht im Alexa2 Adapter auf.
Device Type ist: AWZZ5CVHX2CD
capabilities: TUNE_IN,AUDIBLE,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,LEMUR_ALPHA,GADGETS,FLASH_BRIEFING,SHARKNADO,PAIR_BT_SINK,PERSISTENT_CONNECTION,CHANGE_NAME,CUSTOM_ALARM_TONE,TUPLE_CATEGORY_B,EARCONS,I_HEART_RADIO,REMINDERS,SET_LOCALE,DREAM_TRAINING,POPTART,AMAZON_MUSIC,KINDLE_BOOKS,SALMON,FACTORY_RESET_DEVICE,SLEEP,GOLDFISH,ASCENDING_ALARM_VOLUME,SOUND_SETTINGS,ALLOW_LOG_UPLOAD,FAR_FIELD_WAKE_WORD,AUDIO_PLAYER,VOLUME_SETTING,VOICE_TRAINING,TUPLE,TIMERS_AND_ALARMS,SUPPORTS_SOFTWARE_VERSION,PANDORA,MICROPHONE

Vielen Dank für den super Adapter, wäre froh wenn die beiden Shows auch funktionieren würden- möchte diese u.a. für die VIS-Anzeige benutzen.

Gruß
beckerpa

**Comment by LilaQ** [comment]
Lässt sich sonst auch für den Moment in der main.js einfach selbst einfügen. Nach ca. 50 Zeilen sind die ganzen Devices aufgelistet. Da einfach eine neue Zeile, genau wie die anderen auch, Namen anpassen, DeviceID nimmst du deine und commandSupport auf true dann.

**Comment by beckerpa** [comment]
Danke für die schnelle Antwort- bin leider die Woche über nicht zuhause.
Die Idee das selbst zu ändern klingt zwar gut, aber leider weiß ich nichtmal wo ich das in iobroker finde- einfach zu wenig Ahnung davon. Diesen Account habe ich nur angelegt, damit ich den Device Type hier posten kann.
Aus dem iobroker Forum habe ich die Info, dass man hier ein Issue anlegen soll...

Wie gesagt, ich würde es selbst machen, wenn ich wüsste wie das geht.
Ansonsten bleibt mir nur warten auf ein Update, wo dann hoffentlich der neue Echo Show eingearbeitet wurde.

Trotzdem vielen Dank!

**Comment by Apollon77** [comment]
Update vom Github installieren. ist dann drin
