### ISSUE TITLE
Can't login - seems there is a captcha waiting...

### ISSUE THREAD

**Issue by Yali0n** [Apollon77/ioBroker.alexa2#126]
Log output:
Error: Amazon-Login-Error: Wichtige Mitteilung!: Zum besseren Schutz Ihres Kontos geben Sie bitte nochmals Ihr Passwort ein, und geben Sie dann die Zeichen ein, die in der Abbildung unten gezeigt wer...

**Comment by Apollon77** [comment]
Bitte weiterlesen und Anweisungen im Log folgen. Oder was soll dieses Issue bezwecken?

**Comment by Yali0n** [comment]
diese Meldung kommt beim Starten des Moduls.
Wie soll/kann hier beim starten ein captcha ausgefüllt werden wenn sich das alexa2-modul headless anmeldet/anmelden sollte? 
![2018-10-28-22-41-50](https://user-images.githubusercontent.com/23531825/47622217-ba7d6e00-db02-11e8-8f91-4eedb53e1bcf.png)

**Comment by Apollon77** [comment]
LESEN!!!!
(sorry)

Da steht eine URL drin.Ruf die im Browser auf von dem Rechner aus wo Du arbeitest und nutze es ...

**Comment by Yali0n** [comment]
Funktioniert! - Bitte entschuldige die Störung

**Comment by intershopper** [comment]
Gleiches Problem. Aber der Aufruf der URL ist zwar erfolgreich und ich kann mich bei alexa.amazon.com einloggen  aber der Adapter verbindet sich trotzdem nicht. Auch das verwenden des Cookies bringt keine Besserung.
Gruß Frank

**Comment by Moormerlander** [comment]
Lest doch bitte mal die Anleitung!!! Ich hatte das gleiche Problem und wenn man z.B. mit Google Chrome die Schritte den Entwickler Tools richtig durchführ und den Cookie manuell einkopiert läuft wieder alles.
