### ISSUE TITLE
Alexa2.1 Fehlermeldung im Log

### ISSUE THREAD

**Issue by kxn25** [Apollon77/ioBroker.alexa2#129]
Ich habe seit wochen das gleiche problem , im log wird mir immer wieder die warnung angezeigt:

![zwischenablage01](https://user-images.githubusercontent.com/44605046/47711728-362c0780-dc36-11e8-8966-aa8999727773.jpg)

3 - 4 Täglich erscheint das im LOG!
Ich hatte dieses Problem im IOBroker Forum und wurde gebeten es als Issue hier zu öffnen.
Vieleicht hat ja jemand das gleiche Problem oder kann mir dabei helfen.

**Comment by Apollon77** [comment]
"3-4 mal täglich" ... was passiert denn zur gleichen Zeit? Vllt Mann/Frau/Freundin/Kinder mit Apps die irgendwie mit dem Amazon Account verknüpft sind?

**Comment by kxn25** [comment]
Hallo Apollon77,

Also ausser mir ist niemand am Internet beteiligt.
Ich habe einen PI3 mit IOBroker.
Ich habe 2 Alexa Dot und 2 PCs, 1 Tablet und 1 Handy auf denen ich die Alexa App verwende.

Passieren tut das auch nachts um 3 uhr wo ich eigendlich immer Schalfe.
Ich konnte bis heute kein Ereigniss zuordnen wann das passiert.

Zudem hab ich die im IObroker hinterlegten Alexa Geräte IDs verglichen mit den auf PC und Handys "This Device" und auch die der Alexas aber kann keine Übereinstimmung zu dieser ID finde!
Ich verwende auch eine Alexa Gruppe "Überall" die speak Ausgabe macht über ein Blockly Skript.

**Comment by Ilovegym66** [comment]
ich hab das ja auch, und konnte es auch noch nicht zuordnen, welches Gerät/App sich da an/ab meldet...  Bei mir auch Nachts, wo definitiv niemand was macht. 

Das komische ist, dass dieses Gerät nicht in der Liste der Echo-Devices aufgeführt wird.. auch nicht unter Apps.. wie können wir dem denn bei kommen, damit wir herausfinden, was das ist?

Kann das auch ein Skill sein? Ich habe alle 1h und 2min diesen Eintrag im Log.. sieht nach was automatischen aus...

**Comment by Ilovegym66** [comment]
übrigens Issue ist doppelt, siehe #121

**Comment by Apollon77** [comment]
Ja doppelt , damit am besten im anderen issue weiter.

Wenn aber Features nicht mehr gehen kann es sein das sich die ID eines Gerätes geändert hat.

Also im Zweifel Adapter neu starten dann werden die Devices neu gesynct. Wenn es dann wieder auftaucht dann ist es was anderes :-(

Ich kann mit einem nächsten Update nur die Frequenz im Log verringern ...

Ihr könntet Log auf Debug stellen und schauen was genau die eine Nachricht diese Meldung verursacht. Müsste ja eine "Push-Info" sein. Dann wüsste man wenigstens was es auslöst

**Comment by kxn25** [comment]
Also soll ich dieses Issue schliessen?
