### ISSUE TITLE
Login via Amazone 2FA

### ISSUE THREAD

**Issue by derjj2018** [Apollon77/ioBroker.alexa2#130]
Hallo,
gibt es einen einfachen weg sich anzumelden und automatisch den Cokie / Token zu bekommen, wenn Amazon 2 Fakto Authentifizierung genutzt wird?

LG
derJJ2018

**Comment by Apollon77** [comment]
Nein, aktuell nicht. Eine Idee ist demnächst in Arbeit. Nächstes größeres Update abwarten in paar Wochen
