### ISSUE TITLE
[Q] Order of "speak" commands

### ISSUE THREAD

**Issue by LilaQ** [Apollon77/ioBroker.alexa2#131]
Hi there.

Not really an issues, but rather a question. I have to send multiple lines to my Echo to the "say" command. Apparently when I chain them to a complete string, it's too long for Alexa, and it won't say anything at all. 

`//pseudo
speak("intro")
for(0 to x) {
  speak("someOtherText")
}
speak("outro")`

This is what I'm currently doing. But sometimes, the outro is spoken before all the commands from the for-loop are spoken. Is there any way to guarantee the correct order of sentences?

Thanks in advance

**Comment by Apollon77** [comment]
Iobroker Forum is better for questions. 

And Reading the documentation helps too normally ;-)

https://github.com/Apollon77/ioBroker.alexa2/blob/master/README.md#alexa20echo-devicesserialnumbercommands

The text below the table should exactly answer your question.

**Comment by LilaQ** [comment]
Sorry @Apollon77 totally must have missed that paragraph. Skipped through the docs, but missed it totally. Thanks! :)
