### ISSUE TITLE
Adapter startet nicht mehr

### ISSUE THREAD

**Issue by Moormerlander** [Apollon77/ioBroker.alexa2#133]
Der Status vom Adapter bleibt gelb.
Nachfolgend ein Auszug aus dem Log:

![2018-11-02 09_14_55-logs - iobroker](https://user-images.githubusercontent.com/27990424/47901308-e771ae00-de7f-11e8-8af2-d463caada61b.png)

**Comment by consoleman** [comment]
Du musst die Website besuchen so wie der Link da steht... dann bekommst das nötige Cookie

**Comment by Moormerlander** [comment]
Den Cookie habe ich bisher automatisch mit meinen Credentials bekommen. Der Link bezieht sich ja auf eine manuelle Eingabe. Ist das denn neuerdings nötig?

**Comment by consoleman** [comment]
Probier es einfach mal...
Da steht "you can GET the cookie manually" und nicht "you can TYPE IN the Cookie"

**Comment by Moormerlander** [comment]
Schon richtig, aber vielleicht hat Ingo ja noch eine Idee, warum das nicht mehr automatisch geht.

**Comment by consoleman** [comment]
Es liegt an Amazon...

**Comment by Moormerlander** [comment]
Ich checke das heute Abend. Bin nicht im Heimnetz ;-)
Vielen Dank fürs erste.

**Comment by Apollon77** [comment]
Siehe Forum .. Ja Amazon ist scheinbar um einiges penibler geworden ... ich muss mal nach ner Lösung suchen ... dauert aber noch etwas. Ein Cookie hält übrigens immer 14 Tage :-)

**Comment by Apollon77** [comment]
Siehe Forum .. Ja Amazon ist scheinbar um einiges penibler geworden ... ich muss mal nach ner Lösung suchen ... dauert aber noch etwas. Ein Cookie hält übrigens immer 14 Tage :-)

**Comment by Moormerlander** [comment]
Bei mir war der Cookie über viele Monate gültig. Anyway. Bin gespannt ob das "manuell" klappt.

**Comment by Apollon77** [comment]
ne ... er läuft immer nach 14 tagen ab, wird dann aber ggf automatisch erneuert wenn Di Email/Passwort eingetragen hast ... aber genau hier bei der automatischen erneuerung ist Amazon jetzt eine Diva geworden :-(

**Comment by Moormerlander** [comment]
Ah - verstehe. Das bedeutet dass ich das ich von nun an alle 14 Tage den Cookie manuell erneuern muss?

**Comment by Apollon77** [comment]
Vielleicht, vielleicht auch nicht ... (hängt von der Diva ab) ... und wie lange ich brauche mir was schönes auszudenken
