### ISSUE TITLE
Statuslampe Gelb

### ISSUE THREAD

**Issue by Phanthomas01** [Apollon77/ioBroker.alexa2#135]
Hallo, ich habe mir den Alexa 2 Adapter installiert. Nun habe ich das Problem, das die Staus anzeige Verbunden mit Alexa falsch anzeigt. Der Alexa0 Adapter läuft. Kann mir jemand weiterhelfen.

Gruß

**Comment by Apollon77** [comment]
Ja im iobroker Forum lesen oder hier in zu vielen closed issues ... schau bitte ins logfile und folge dem was da steht.
