### ISSUE TITLE
Fehlendes Device Objekt "TuneIn-Station" von gestern auf heute?

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#136]
Folgendes Device Objekt gesten war es noch verfügbar heute ist es verschwunden!
Auch ein Adapterneustart brachte nix.

`alexa2.0.Echo-Devices.xxxxxxxx.Player.TuneIn-Station`

Nur noch die Multiroom Device "Player" Liste ist `TuneIn-Station` drin.

Gruß
Matten Matten

**Comment by Matten-Matten** [comment]
Scheinbar ist es mal wieder ein Problem bei Amazon, denn über die App kann ich auch nichts bedienen.

**Comment by Ilovegym66** [comment]
bei mir gehts, allerdings konnte ich die ganze Zeit die StationNr. eintragen, das geht jetzt auf einmal nicht mehr, sondern nur noch der Name... 
Amazon sorgt mal wieder für Arbeit..

**Comment by Apollon77** [comment]
Aktuell werden die Tunein States erzeugt wenn die capabilities ein TUNE_IN enthalten.
Und da fehlt es wohl ... also wat nu?

Ignorieren und immer anlegen? Meinungen bitte ...

**Comment by Apollon77** [comment]
Auch: https://forum.iobroker.net/viewtopic.php?f=37&t=18230&p=190498#p190498

**Comment by Matten-Matten** [comment]
Moin, ja was soll ich sagen Adapter Neustart heute und das Tunein Objekt ist wieder da.

**Comment by Ilovegym66** [comment]
manche probleme lösen sich von ganz alleine.. wenn man lange genug wartet :-)
Mach das issue hier wieder zu, wir bedanken uns alle bei Amazon, für die unerwartete Arbeit.. 

Hoffentlich bleibts so.
