### ISSUE TITLE
Update Alexa Commands to newest features like Notifications ...

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#137]
Es gibt jetzt die Funktion per Routine eine Nachricht an die Alexa App zu senden. Siehst du eine Möglichkeit das auch im Adapter zu integrieren?
![screenshot_20181107_101458](https://user-images.githubusercontent.com/32074970/48127190-681b1a80-e283-11e8-90f8-b09e5b8af7d2.jpg)
![screenshot_20181107_101531](https://user-images.githubusercontent.com/32074970/48127205-6f422880-e283-11e8-9c04-c1a571f427ca.jpg)
![screenshot_20181107_101548](https://user-images.githubusercontent.com/32074970/48127210-736e4600-e283-11e8-86bf-93fb7cce211d.jpg)
![screenshot_20181107_101621](https://user-images.githubusercontent.com/32074970/48127216-7832fa00-e283-11e8-8eaf-3f452d22fb10.jpg)
![screenshot_20181107_101358](https://user-images.githubusercontent.com/32074970/48127224-7c5f1780-e283-11e8-8498-aed8548ea178.jpg)

**Comment by Apollon77** [comment]
```
}, {
				"@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
				"type": "Alexa.Calendar.PlayToday",
				"operationPayload": {
					"deviceType": "XXX",
					"deviceSerialNumber": "XXX",
					"locale": "de-DE",
					"customerId": "XXX"
				},
				"name": null
			}, {
				"@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
				"type": "Alexa.Calendar.PlayTomorrow",
				"operationPayload": {
					"deviceType": "XXX",
					"deviceSerialNumber": "XXX",
					"locale": "de-DE",
					"customerId": "XXX"
				},
				"name": null
			}, {
				"@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
				"type": "Alexa.Calendar.PlayNext",
				"operationPayload": {
					"deviceType": "XXX",
					"deviceSerialNumber": "XXXX",
					"locale": "de-DE",
					"customerId": "XXXX"
				},
				"name": null
			}, {
				"@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
				"type": "Alexa.Notifications.SendMobilePush",
				"operationPayload": {
					"customerId": "XXXX",
					"notificationMessage": "Test text",
					"alexaUrl": "#v2/behaviors",
					"title": "Amazon Alexa"
				},
				"name": null
			}

```

Routines Version header: 1.1.218665

**Comment by Apollon77** [comment]
max-Length 148 Chars?

**Comment by Apollon77** [comment]
thx

**Comment by Apollon77** [comment]
Benachrichtigungen: Done in 2.1

**Comment by Apollon77** [comment]
Send MobilePush: Done in 2.1

**Comment by Apollon77** [comment]
Open: PlayToday/Tomorrow/Next

**Comment by Matten-Matten** [comment]
funktioniert SUPER! vielen Dank!

**Comment by Apollon77** [comment]
rest will come in 2.2
