### ISSUE TITLE
Feature: Add ability to play mp3

### ISSUE THREAD

**Issue by Marty56** [Apollon77/ioBroker.alexa2#14]
Sound output for Alexa would be desirable

**Comment by Apollon77** [comment]
Can the Alexa App do it? Then adapter can too ... so can App have custom mp3 output possibilities? I do not know of them

**Comment by Apollon77** [comment]
If it can be done via one of the music providers then it is already possible. else I have no idea

**Comment by Marty56** [comment]
I can play music which is in my Amazon library with commands under 'Music Provider'.
Unfortuantely I am have to use a third party skill to play my music. I am using My Media (in German: meine Medien) and therefore I have to tell Alexa that I want to use the Skill. 
"sage meine Medien spiele das Lied help von den Beatles". 
Do you see a change to support calling a skill aswell?

**Comment by Apollon77** [comment]
What eactly is "My media"? Is it listed as a Music-provider? If not then no chance currently because no access to that.

Or: Can oyu dio this as a routine? can you create a routine and choose this skill to play something? If yes I can do it, if not then not

**Comment by Marty56** [comment]
I did not find a way to start a skill via routines.

**Comment by Apollon77** [comment]
if they do it will be easy

**Comment by Marty56** [comment]
yes, thanks for the support.
I'll be patient
