### ISSUE TITLE
Sonos One - Audioaktionen in Routinen werden von diesem Gerät nicht unterstüzt.

### ISSUE THREAD

**Issue by LJSven** [Apollon77/ioBroker.alexa2#140]
Wenn ich eine Routine starte, kommt immer die Meldung "Audioaktionen werden von diesem Gerät nicht untersützt." 
Meine Geräte werden über den Cloud Adapter angesprochen. Kann man die Meldung raus nehmen? Ein anderer User hatte berichtet, daß wenn er das über den Node Red Adapter macht, kommt die Meldung nicht?! Möchte aber ungern so viele verschiedene Adapter installieren.

**Comment by Apollon77** [comment]
Ich habe keine Ahnung was genau über Node-Red wie geht, am Ende ist es aber sehr einfach:

Kannst Du über die Alexa-App eine Routine anlegen die genau das macht was Du willst auf dem Sonos-Gerät? Wenn ja dann sollte es der Adapter können und man muss mal ansehen was los ist.
Wenn es per Alexa-App nicht geht dann geht es mit den Mitteln de der Adapter aktuell einsetzt nicht. Und dann sollte es auch sonst nicht gehen - es sei denn auf irgendeinem anderen Weg.

**Comment by LJSven** [comment]
Hallo Apollon77, der Adapter macht es ja - es kommt aber eine Meldung "Audioaktionen werden von diesem Gerät nicht unterstüzt" - die Routine wird trotzdem ausgeführt, eine Audioaktion ist aber eigentlich nicht in der Routine. Wenn ich die Routine manuell ausführe, kommt die Meldung nicht.

**Comment by Apollon77** [comment]
Interessant. Dann bitte folgendes tun.

- Debug Log einschalten (Instanzen -> Expertenmodus -> Spalte Log Stufe)
- Adapter startet neu
- entsprechende Routine über Alexa2 ausführen. geht es damit ohne die Zusatzmeldung?
- Anderen Weg über Adapter machen

gesamtes Log von File auf Platte unter /opt/iobroker/log/... senden von Debug-Start bis zum Ende. Gern als PN im Forum

**Comment by jansios** [comment]
Hallo, bei mir funktionieren die Sonos One wunderbar. Sowohl per .speak als auch per Routine kann ich Ansagen machen lassen. Nur so, weil die Issue hier irgendwie tot zu sein scheint seitens des Thread-Owners... Gruß, Jan

**Comment by jansios** [comment]
Und nein, ich bekomme nicht diesen Hinweis "Audioaktionen werden von diesem Gerät nicht unterstüzt"

**Comment by Apollon77** [comment]
Dann sorry, die Ausgabe kommt von Amazon ... und damit kann das keine Audioausgabe. 

Sind in den Objekten die speak Commands drin? Wenn ja muss man die ggf rausnehmen.

**Comment by jansios** [comment]
Hi, Du hast mich falsch verstanden - bei mir ist alles in Ordnung bei der Ausgabe per Adapter. Sowohl das Auslösen einer definierten Routine als auch das Verwenden von .speak funktionieren ohne den hier monierten Hinweis.
Die Alexa-App wiederum selbst behauptet "Wir konnten keine Audiogeräte für Sie finden" und gibt auch nichts wieder. Der Adapter funktioniert hier also besser ;)
