### ISSUE TITLE
uncaught exception: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by hecarrara** [Apollon77/ioBroker.alexa2#142]
> host.raspberrypi	2018-11-11 22:06:19.012	error	instance system.adapter.alexa2.0 terminated with code 0 (OK)
Caught	2018-11-11 22:06:19.012	error	by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
Caught	2018-11-11 22:06:19.012	error	by controller[0]: at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
Caught	2018-11-11 22:06:19.012	error	by controller[0]: at emitErrorNT (internal/streams/destroy.js:82:8)
Caught	2018-11-11 22:06:19.012	error	by controller[0]: at TLSSocket.emit (events.js:182:13)
Caught	2018-11-11 22:06:19.011	error	by controller[0]: at TLSSocket.socketErrorListener (_http_client.js:391:9)
Caught	2018-11-11 22:06:19.011	error	by controller[0]: at ClientRequest.emit (events.js:182:13)
Caught	2018-11-11 22:06:19.011	error	by controller[0]: at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
Caught	2018-11-11 22:06:19.011	error	by controller[0]: at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
Caught	2018-11-11 22:06:19.011	error	by controller[0]: TypeError: Cannot read property 'options' of undefined
alexa2.0	2018-11-11 22:06:18.985	warn	Exception: TypeError: Cannot read property 'options' of undefined
alexa2.0	2018-11-11 22:06:18.979	error	at process._tickCallback (internal/process/next_tick.js:63:19)
alexa2.0	2018-11-11 22:06:18.979	error	at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
alexa2.0	2018-11-11 22:06:18.979	error	at emitErrorNT (internal/streams/destroy.js:82:8)
alexa2.0	2018-11-11 22:06:18.979	error	at TLSSocket.emit (events.js:182:13)
alexa2.0	2018-11-11 22:06:18.979	error	at TLSSocket.socketErrorListener (_http_client.js:391:9)
alexa2.0	2018-11-11 22:06:18.979	error	at ClientRequest.emit (events.js:182:13)
alexa2.0	2018-11-11 22:06:18.979	error	at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
alexa2.0	2018-11-11 22:06:18.979	error	at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
alexa2.0	2018-11-11 22:06:18.979	error	TypeError: Cannot read property 'options' of undefined
alexa2.0	2018-11-11 22:06:18.978	error	uncaught exception: Cannot read property 'options' of undefined

**Comment by Apollon77** [comment]
Please provide full debug log of the adapterstart.
Debug log: Instanzen -> Expertenmodus -> Spalte Log Stufe

**Comment by Apollon77** [comment]
Ne lass ... da gab es wohl ein Problem Amazon zu erreichen.

wird gefixt. alexa-cookie 1.0.1
