### ISSUE TITLE
Unknown Device-type:AKPGW064GI9HE ist Fire TV Stick 4K

### ISSUE THREAD

**Issue by mkraemer0** [Apollon77/ioBroker.alexa2#147]
Device-type:AKPGW064GI9HE (FLASH_BRIEFING,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,MICROPHONE,ARTHUR_TARGET,ACTIVE_AFTER_FRO,SUPPORTS_SOFTWARE_VERSION,CHANGE_NAME,VOLUME_SETTING,PERSISTENT_CONNECTION)

**Comment by Apollon77** [comment]
And what is this? What can you do with it? Can you create a routine in Alexa app and make voice output on this device?

**Comment by mkraemer0** [comment]
Das steht doch in der Überschrift.

**Comment by sigi2345** [comment]
`https://github.com/Apollon77/ioBroker.alexa2/issues/77`

**Comment by mkraemer0** [comment]
Der Text ist richtig, aber der Link ist falsch.

Davon abgesehen mag es sein, daß Dein Adapter kein Fire TV unterstützten wird, aber zumindest sollte der Warnhinweis im Log nicht mehr auftauchen. Ich bin ja nur der Aufforderung nachgegangen, was Du Dir in dem Fall im Log wünschst.

**Comment by Apollon77** [comment]
Alles gut, ich habs nur übersehen :-)

**Comment by Garfonso** [comment]
Zur Verfollständigung: den FireTV Stick 4K kann man nicht für Routinen mit Sprachausgabe nutzen.

**Comment by robson80** [comment]
> Hier ein schneller Fix, wenn man sein Log nicht zugemüllt bekommen möchte:
> 
> In der Datei "/opt/iobroker/node_modules/iobroker.alexa2/main.js" nach "because of unknown type" suchen und an der Stelle die beiden Zeilen "adapter.log.warn(..." in "//adapter.log.warn(..." ändern. Danach den alexa2-Adapter neu starten.

Thanks. I changed the log level to "error" for the time it is not fixed. That helps as well.
