### ISSUE TITLE
History zeitweise nicht aktuell

### ISSUE THREAD

**Issue by ingod68** [Apollon77/ioBroker.alexa2#149]
Geräte : Echo Dot 2.Gen und Echo Spot.
Push Verbindung ist eingeschaltet.

alexa2.History wird zeitweise nicht aktualisiert.

Manchmal wird eine Anfrage/Kommando an ECHO1 von ECHO2 beantwortet obwohl ein Skript dieses auswertet und steuert. Beim beobachten der Objekte fiel mir dann auf dass die History dann nicht aktualisiert wurde.

**Comment by Apollon77** [comment]
Dann bitte Debug Log aktivieren, reproduzieren und log senden mit genauen Infos was wann "in wirklichkeit" passiert ist das ich es zuordnen kann

**Comment by ingod68** [comment]
[iobroker.2018-11-21.log](https://github.com/Apollon77/ioBroker.alexa2/files/2606010/iobroker.2018-11-21.log)

**Comment by Apollon77** [comment]
Also im Log sehe ich nur eine Sprachausgabe ... Ich hätte gedacht das es eine "normale" Interaktion gibt und basierend darauf dann eine Sparchausgabe. Dann fehlt die Initiale Aktion aber im Log

**Comment by ingod68** [comment]
Ja, ich habe gestern noch etwas getestet und manchmal passiert es dass die gesamte Aktion des Echos zwar ausgeführt wird aber nicht in der History erscheint. 
Wie du ja im Forum sicher schon gelesen hast treten diese Probleme jetzt wohl auch bei anderen Usern auf. Scheint ein Problem von Amazon/Echo zu sein.

Ich werde nachher nochmal ein kleines Skript basteln um genau diese Funktion zu testen und logge das dann.
