### ISSUE TITLE
Feature: No volume control for text to speech

### ISSUE THREAD

**Issue by Marty56** [Apollon77/ioBroker.alexa2#15]
I did not find volume control for text to speech output.
The volume under "Player-Controls" is only working for media streaming e.g. tuneIn Radio but not for text to speech.

**Comment by Apollon77** [comment]
I only know that one volume option.
And in fact it is easy: Can the Alexa App do it=? Then adfapter can too ... so can App have several volumes?

**Comment by Apollon77** [comment]
setting the volume should work exactly the same then the script

**Comment by Apollon77** [comment]
Ok, what happens if you set the volume and speak a text afterwards. For me this works well. What happens with you?

**Comment by Marty56** [comment]
Ok. I was my silly fault. I had to insert a delay between setting the volume and the speech command.

**Comment by Apollon77** [comment]
:-)) how long it needs to be that it works?
I think we will put into sayit something to also use it and then this could be automated that way

**Comment by Marty56** [comment]
I think it is ok. No need to spend more effort.

**Comment by Apollon77** [comment]
But tell me the delay please, then I can put into docs or such

**Comment by Marty56** [comment]
Hallo Ingo,

Ich verwende ein Delay von 1 Sekunde und das scheint ohne Problem zu funktionieren.

Derzeit habe ich aber den Test des Adapter eingestellt, weil ich Probleme mit der Stabilität meines ioBroker Servers bekommen habe.
Es kann daran liegen, dass ich auf meinem Raspberry zu wenig Memory habe.
Die Datenbank hängt sich auf und ich bekomme 1000 Warnings, dass Datenpunkte nicht mehr existieren.
Komischerweise wird das in Scripts gemeldet, die mit dem Alexa.2 Objekten nichts machen.
Das hatte ich vorher nicht, deshalb vermute ich, dass es mit den Alexa.2 Adapter zusammenhängt.

Wenn das bei anderen Nutzern auch auftritt, müsste das noch mal genauer analysiert werden.
Ansonsten gehe ich zurzeit von fehlenden Ressourcen auf meinem Raspi aus.

Liebe Grüße und danke für Dein Engagement 

Martin

**Comment by Apollon77** [comment]
Am besten beschreibt dein Problem mal im Forum, da finden wir bestimmt eine Lösung.
 Der Adapter sollte nicht der Grund für diese Probleme sein, wurde bisher noch von niemandem berichtet.

**Comment by Apollon77** [comment]
Ansonsten habe ich festgestellt und auch gelesen dass das Setzen der Lautstärke teilweise nicht funktioniert wenn lange nichts abgespielt wurde. Ich habe aber schon eine Alternative gefunden, die ich gerade am probieren bin.
