### ISSUE TITLE
Update auf 1.1.3 fehlgeschlagen

### ISSUE THREAD

**Issue by h3adbang3r** [Apollon77/ioBroker.alexa2#150]
![1926](https://user-images.githubusercontent.com/15799077/48903624-57aa9880-ee5c-11e8-9201-73555fd66687.jpg)
Mahlzeit. ;)

Ich wollte gerade den Adapter aktualisieren, was in einer Fehlermeldung endet:

`Fertig mit Fehler: module.js:550 throw err; ^ Error: Cannot find module 'set-blocking' at Function.Module._resolveFilename (module.js:548:15) at Function.Module._load (module.js:475:25) at Module.require (module.js:597:17) at require (internal/module.js:11:18) at Object. (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/lib/usage.js:7:21) at Module._compile (module.js:653:30) at Object.Module._extensions..js (module.js:664:10) at Module.load (module.js:566:32) at tryModuleLoad (module.js:506:12) at Function.Module._load (module.js:498:3) 
![1926](https://user-images.githubusercontent.com/15799077/48903579-377ad980-ee5c-11e8-9140-8847f5c910a4.jpg)
`

**Comment by Apollon77** [comment]
Sieht so aus als ob da was anderes nicht stimmt.
node Verison? npm Version? Am besten aber ins ioBroker Forum!

**Comment by h3adbang3r** [comment]
Es scheint in der Tat ein größeres Problem zu sein. Ich hatte eigentlich nur den Tuya Adapter deinstalliert und wollte anschließend Alexa2 aktualisieren. 

Wie dem auch sei, ioBroker startet nicht mehr und ich beginne von vorne. 

`@ioBroker-RasPi:~ $ iobroker status
module.js:550
    throw err;
    ^

Error: Cannot find module 'set-blocking'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/lib/usage.js:7:21)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
`

**Comment by Apollon77** [comment]
Support dazu am besten im iobroker Forum!!
