### ISSUE TITLE
Sensoren unter "Smart-Home-Devices" werden nicht angezeigt

### ISSUE THREAD

**Issue by senger1985** [Apollon77/ioBroker.alexa2#152]
Bewegungsmelder, die mit den Plus-Geräten gekoppelt sind, werden, in den Objekten, nicht angezeigt.
Ist das möglich?

**Comment by Apollon77** [comment]
Bitte debug log vom adapterstart senden und Namen der devices nennen wie in Alexa benannt.

**Comment by Apollon77** [comment]
Log am besten vom logfile auf der Platte /opt/iobroker/log/... und als PN im Forum

**Comment by senger1985** [comment]
Habe dir eine PN geschickt.
