### ISSUE TITLE
Timer beenden

### ISSUE THREAD

**Issue by zuldero** [Apollon77/ioBroker.alexa2#153]
Ist es möglich den Timer über den Adapter zu stoppen (also den Datenpunkt Timer.triggered selber auf false zu setzen)?
Also das man nicht jedesmal nach 5sec Alexa sagen muss sie solle den Timer stoppen.

**Comment by Apollon77** [comment]
Wenn das passiert ist der timer bereits abgelaufen. Ich bin nicht sicher ob man die „pieperei” damit beenden könnte. Muss man mal per Alexa App testen.

**Comment by zuldero** [comment]
Wie kann ich dies in der App testen? Ich finde leider nichts. Ev. kann ich es nicht testen, da ich nur zu ner veralteten version der app komme, inder ich beispielsweise noch nicht mal Routinen erstellen kann. (komme aus der Schweiz und dürfte Alexa eig. noch gar nicht verwenden)

**Comment by Apollon77** [comment]
Ok, dann teste ich

**Comment by CrEaK** [comment]
Habs grade mal bei mir in der App gestestet. Man kann das Piepen mit "Timer löschen" abbrechen 👍 Witzigerweise kann man auch mit "Timer anhalten" das Piepen pausieren und mit "Timer fortsetzen" auch weiterpiepen lassen :D

**Comment by Gieskanne** [comment]
👍 Feature request.

**Comment by padrino-x** [comment]
@CrEaK & @Gieskanne 
Wenn Ihr wollte, dass das dies Priorität erhält, dann sollte Ihr dem ersten Beitrag ein "+1" geben.
Nur das zählt - ein paar Daumenhoch Emojis tauchen nicht in der GitHub Statistik auf, soweit ich weiß. ;-)

**Comment by padrino-x** [comment]
Hm, kann es sein, dass amazon das Feature entfernt hat? Ich kann leider nur https://alexa.amazon.de/ nutzen, aber da erscheint kein Kopf zum beenden mehr, wenn ein Timer klingelt. Auch kann ich das Klingeln nicht mehr kurzzeitig durch "anhalten" stumm schalten. Klingelt der Timer, wird "anhalten" ausgegraut. Einen laufenden Timer editieren geht auch nicht (da weiß ich allerdings nicht, ob das jemals ging). :(

**Comment by Gieskanne** [comment]
Während der Timer läuft, kann er mit "Anhalten" angehalten und mit "Abbrechen" beendet werden. Nach Ablauf des Timers kann er mit "Abbrechen" zum Schweigen gebracht werden. Ich denke das deckt alle vorstellbaren Anwendungsfälle ab, oder?
Soweit ich weiß ist dies bisher noch nicht in diesem Adapter abgebildet.

**Comment by Apollon77** [comment]
"Abbrechen" ist quasi "löschen". Was mal ging war das während er piept ihn zu löschen das auch beendet hatte ...

**Comment by padrino-x** [comment]
Ist ewig her, kann sein, dass das schon immer so war, wie es jetzt noch ist. ;)

Also "Abbrechen" geht tatsächlich (noch), wenn der Timer piept, löscht ihn und beendet auch das Piepen.
Also alles noch da. :D

**Comment by Apollon77** [comment]
Next verion will have the following:
1.) State with List of actibve timers as JSON
2.)State with ID of the next triggering timer
3.) State to stop a timer by providing an ID

With this you should be able to do what you want

**Comment by Apollon77** [comment]
have fun https://forum.iobroker.net/post/824793
