### ISSUE TITLE
Falsche Aussprache deutscher Umlaute

### ISSUE THREAD

**Issue by DavidPasch** [Apollon77/ioBroker.alexa2#154]
Mir ist aufgefallen, das seit einigen Tage die Umlaute ö, ä und ü nicht mehr richtig ausgesprochen werden. Es wird z.B. "konnte" statt "könnte" gesagt.

oe, ae und ue statt ö, ä und ü brachten keine Änderung.

**Comment by Apollon77** [comment]
Interessant ... Scheinbar hat Amazon mal wieder was geändert.

**Comment by Jastroger** [comment]
Ist das noch aktuell? Ich habe mittels "Speak" diverse Wörter mit Umlaut getestet - keine Probleme.

**Comment by DavidPasch** [comment]
Ist noch aktuell. Schreib mal "könnte" oder "es könnte ..." in die Speak-Variable. Ich höre hier "konnte".
Andere Umlaute hingegen gehen. "Örtlichkeit", "Küche", "künstlich" laufen super.

**Comment by Apollon77** [comment]
Bitte 2.1 vom Github versuchen

**Comment by DavidPasch** [comment]
Top! Läuft!
