### ISSUE TITLE
Feature request: remote IP oder callback IP

### ISSUE THREAD

**Issue by ceotjoe** [Apollon77/ioBroker.alexa2#158]
Ich lasse ioBroker als Docker Container laufen. Dort werden für die einzelnen Container intern eigene IPs verwendet, nach Außen muß ich aber die IP von dem Host verwenden, auf dem Docker läuft. Das Problem ist jetzt, daß natürlich diese interne Adresse im Proxy Link verwendet wird und nicht die externe. Damit kann ich den Proxy nur aus dem Container selbst erreichen, aber nicht von Außen. In den Homematic Adaptern kann ich dafür in der Konfiguration eine Callback Adresse angeben. Es wäre schön, wenn das auch bei dem Alexa2 Adapter irgendwie möglich wäre. 

Irgendwie scheint sowas ähnliches in der Konfiguration ja schon vorgesehen zu sein. Aber ich kann dort leider nur die internen Docker Adressen auswählen. Also die, die direkt auf dem Interface des Containers liegen.

**Comment by Apollon77** [comment]
Ich sage es mal so ... Da diese Angabe Ausschliesslich für die Anzeige im Log genutzt wird sollte es reichen den Port zugänglich zu machen und einfach die korrekte "äussere" IP zu nutzen und ende. Der Aufwand jetzt hier noch sowas für nur diese Anzeige einzubauen ist echt fraglich ;-) Oder ?!

**Comment by ceotjoe** [comment]
Es geht mir nicht um die Anzeige im Log. Wenn ich die korrekte äußere IP verwende und auf den Proxy über den fest definierten Port zugreife bekomme ich einen redirect vom Proxy wo leider wieder die innere IP drin ist. In diesem redirect müßte die äußere sein, dann wäre es OK.

**Comment by Apollon77** [comment]
Aahh ok ... verstehe. Schaue was ich tun kann

**Comment by ceotjoe** [comment]
Von mir aus muß das nicht weiter verfolgt werden, ich hab mich von Docker bzgl. ioBroker unter macOS verabschiedet. Gibt einfach zu viele Adapter, die das gleiche Problem haben.

**Comment by Wee20x** [comment]
@Apollon77 
Also ich hätte Bedarf an einer Umsetzung, da ich Iobroker über Docker verwende.
Momentan kann ich somit die Proxy Methode nicht benutzen.

Hast du eine grobe Idee wann du Zeit hast dies evtl. umzusetzen?

THX

**Comment by Apollon77** [comment]
ich hoffe demnächst ... Steht auf der Todo liste

**Comment by Apollon77** [comment]
Bitte 2.4.0 vom Github testen. Admin-Instanzeinstellungen haben ein neues Setting, das mit der externen IP füllen. Feedback bitte
