### ISSUE TITLE
unbekanntes Gerät A3TCJ8RTT3NVI7

### ISSUE THREAD

**Issue by JBSullivan** [Apollon77/ioBroker.alexa2#159]
Es handelt sich bei dem unbekannten Gerät ( A3TCJ8RTT3NVI7 ) um eine Smartwatch Typ HUAWEI Watch 2 mit der Android App "Listens for Alexa"

https://play.google.com/store/apps/details?id=com.willblaschko.android.alexalistens

Bitte bei Gelegenheit mal nachpflegen.

**Comment by Apollon77** [comment]
Bitte die Capabiloties noch hierher oder Forum Link Danke

**Comment by Matten-Matten** [comment]
Device-type:A3TCJ8RTT3NVI7 
`(AUDIBLE,DEREGISTER_DEVICE,MICROPHONE,GOLDFISH,CHANGE_NAME,PERSISTENT_CONNECTION,TUNE_IN,SLEEP,AUDIO_PLAYER,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,KINDLE_BOOKS,VOLUME_SETTING,I_HEART_RADIO,DREAM_TRAINING,MUSIC_SKILL,PEONY,AMAZON_MUSIC,TIMERS_AND_ALARMS)`

**Comment by Apollon77** [comment]
kommt in 2.4.1 später heute
