### ISSUE TITLE
Enhance adapter to remove the need for capture workaround

### ISSUE THREAD

**Issue by Marty56** [Apollon77/ioBroker.alexa2#16]
In some situations, the user is getting an error message that asks for the operation of a capture which cannot be done. A workaround is documented in "Troubleshooting" in the documentation.
It would be desirable that the adapter handles this situation without the need of the workaround.

**Comment by Apollon77** [comment]
already build in ... use the proxy.

**Comment by Apollon77** [comment]
PS: Yes I need to update the README
