### ISSUE TITLE
Password differs from set email

### ISSUE THREAD

**Issue by pge** [Apollon77/ioBroker.alexa2#160]
My Instance wont register anymore. I know there are problems, but when i try to manually retrieve the cookie i get the following error message:

`alexa2.0 | 2018-11-29 13:07:17.368 | warn | Alexa-Cookie: Password entered on Login Page via Proxy differs from set email! You should use the same password to allow automatic cookie retrieval.
alexa2.0 | 2018-11-29 13:07:17.351 | warn | Alexa-Cookie: Email entered on Login Page via Proxy differs from set email! You should use the same email to allow automatic cookie retrieval.
alexa2.0 | 2018-11-29 13:07:14.070 | warn | Alexa-Cookie: Password entered on Login Page via Proxy differs from set email! You should use the same password to allow automatic cookie retrieval.`

This is not correct - the login data is exactly the same.

**Comment by Apollon77** [comment]
Will it get green afterwards? Then ignore the message. Will be changed soon anyway.

**Comment by pge** [comment]
Nope, it wont.

**Comment by Apollon77** [comment]
Within 1.1.3? The please post Infos in iobroker Forum. 1.1.3 should work currently when doing with proxy.
