### ISSUE TITLE
Sonos Gruppen - keine .speak Datenpunkte o.ä.

### ISSUE THREAD

**Issue by jansios** [Apollon77/ioBroker.alexa2#163]
Der Adapter kann prima auf Sonos One Geräten Sprachausgaben via .speak oder ausgelöster Routine durchführen (deviceType A2OSP3UA4VC85F, capabilities KINDLE_BOOKS,I_HEART_RADIO,TUNE_IN,DREAM_TRAINING,MICROPHONE,GOLDFISH,VOLUME_SETTING,AUDIBLE,SLEEP,CHANGE_NAME,PERSISTENT_CONNECTION,PEONY,DEREGISTER_DEVICE,REMINDERS,AMAZON_MUSIC,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,TIMERS_AND_ALARMS,AUDIO_PLAYER,MUSIC_SKILL).

Eine Gruppe, in der ein oder mehrere Sonos One Geräte enthalten sind, kann keine Sprachausgaben o.ä. ausführen, weder die entsprechenden Datenpunkte noch die Routine werden aufgelistet (deviceType A15ERDAKK5HQQG, capabilities PEONY,I_HEART_RADIO,TUNE_IN,REMINDERS,AMAZON_MUSIC,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,VOLUME_SETTING,CHANGE_NAME,AUDIO_PLAYER,MUSIC_SKILL,PANDORA).

Cool wäre es, wenn man Ausgaben auf einer Gruppe ausführen könnte.

**Comment by Apollon77** [comment]
ok, in 2.4.1 später heute sind die commands aktiviert
