### ISSUE TITLE
Icon Vorschläge

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#164]
Multiroom / Gruppen: A3C9PE6TNYLTCH
![group](https://user-images.githubusercontent.com/32074970/49598604-4a72cb00-f97f-11e8-93b2-ff37a4cf9e17.png)

Alexa Apps: A2IVLV5VM2W81 ; A2825NDLA7WDZV ; A21Z3CGI8UIP0F ; A1DL2DVDQVK3Q
![apps](https://user-images.githubusercontent.com/32074970/49598817-bead6e80-f97f-11e8-97ed-494100728530.png)

alexa2: A2TF17PFR55MTB
![iobroker](https://user-images.githubusercontent.com/32074970/49598131-4db98700-f97e-11e8-8727-f0240066925f.png)

Alexa Listens: A3TCJ8RTT3NVI7
![a3tcj8rtt3nvi7](https://user-images.githubusercontent.com/32074970/49598411-db957200-f97e-11e8-8361-0beee20429ab.png)

Gruß
Matten Matten

**Comment by Apollon77** [comment]
An other commit incuded this one: https://github.com/Apollon77/ioBroker.alexa2/blob/master/admin/icons/multiroom.png Also ok?

**Comment by Matten-Matten** [comment]
Ja klar.👍

**Comment by Apollon77** [comment]
wird in 2.4.1 drin sein. Danke!
