### ISSUE TITLE
Feature: Benachrichtigungen

### ISSUE THREAD

**Issue by roe19xx** [Apollon77/ioBroker.alexa2#17]
Hallo,

Ich weiß nicht ob sich dieses Feature überhaupt umsetzen läßt, bzw. ob es nicht ggf. nur der Skill Entwicklung vorbehalten ist. Ich habe es auch bei Bluefox für den "ioBroker Custom Skill" schon mal angesprochen. Habe aber darauf bisher noch kein Feedback enthalten.

Vorab:
Ich finde es genial das man nun ein beliebiges Alexa Gerät einen beliebigen Text sprechen lassen kann.
Vielen Dank an dieser Stelle für diesen tollen Adapter.

Feature Request:
Es gibt Situationen in denen man ggf. nicht möchte dass ein Alexa Gerät einfach so losplaudert. Bzw. wenn man mehrere Alexa Geräte im Haus/in der Wohnung verteilt hat, möchte man ggf. nicht einfach alle sprechen lassen nur um einen möglichen Zuhörer zu finden.

Hier wäre die Benachrichtigungsfunktion ein echt tolles Feature (Alexa Notification API).
Sprich das man einen Text nicht direkt als als Sprache ausgeben läßt, sondern diesen in die "Inbox" vom jeweiligen Konto/Benutzer schickt worauf dann alle Alexa Geräte mit einem gelb blinkenden Ring anzeigen das es eine neue Benachrichtigung gibt. Diese kann dann abfragen und erst dann wird/werden die Benachrichtigung(en) abgespielt.

Das natürlich als optionales Feature. Somit kann der Besitzer der jeweiligen ioBroker Lösung entscheiden ob eine Text direkt auf einem (oder mehreren) Alexa Geräten ausgegeben wird, oder als Nachricht in die "Inbox" geschickt wird und visuell (gelb blinkter Ring) auf allen Alexa Geräten angezeigt wird.

Ich bin mir aber nicht sicher ob Dir diese Notification API so überhaupt zur Verfügung steht.
Auf jeden Fall wollte ich die Idee mal platzieren was somit auch geschehen ist :-).

Gruß
Roland

**Comment by Apollon77** [comment]
In der Library ist was drin, aber ich muss das checken und testen. Mal schauen wie ich das mit nur einem Echo hinbekomme :-)

**Comment by roe19xx** [comment]
Das hört sich ja schon mal spannend an.

Im Grunde sollte es keinen Unterschied machen ob nur ein Echo vorhanden ist oder mehrere. Bei einer Benachrichtigung wird auf allen Echo Geräten durch einen gelb blinkenden Ring angezeigt das es eine neue Benachrichtigung gibt und man kann diese dann auf einem bliebigen Echo anhören.

Hätte daher eher vermutet das eine Benachrichtigung an ein Konto und nicht an einzelne Echo Geräte geschickt wird. Aber auf Vermutungen kann man nichts aufbauen, daher warte ich mal was Du noch herausfindest.

Vielen Dank auf jeden Fall für Deine Arbeit und Mühen die Du bei diesem Adapter investierst. Der ist schon jetzt ein echtes ioBroker Highlight für Echo Besitzer :-).

**Comment by Apollon77** [comment]
die gehen sogar an den "amazon user" ... also noch eine ebene höher ... daher testen wird wieder interessant :-) Nach Urlaub

**Comment by roe19xx** [comment]
Interessant ist ja positiv :-). Wünsche Dir einen schönen Urlaub.

**Comment by Panoru84** [comment]
Hallo @Apollon77,

ich wollte diesen Punkt nochmal aufgreifen, gerade in betracht daraufhin, dass du ihn mit issue #109 verbunden hast.

@roe19xx beschreibt oben aber ein anderes ganz Feature.

Die original Amazon Alexa Devices können z.B. in Verbindung mit CustomSkills Notifications "speichern".

Dann leuchtet z.B. am Echo Dot (2.Gen) oder auch am großen Echo der LED Ring permanent gelb auf und auf die Nachfrage "Alexa, was sind die Benachrichtigungen" plappert die Dame los.

Z.B. wird dieses Feature vom  [AbfallkalenderSkill](https://www.amazon.de/Mankei-Abfallkalender/dp/B06XVYJMLM/ref=sr_1_1?s=digital-skills&ie=UTF8&qid=1542883094&sr=1-1&keywords=abfallkalender) benutzt. Dort habe ich meinen Abfallkalender hinterlegt und am Tag vor der Abholung leuchtet der gelbe Ring und wie beschrieben sagt mir Alexa dann auf Nachfrage was Sache ist.

Dieses Feature wäre natürlich für viele ähnlich Funktionen sehr hilfreich. Z.B. Waschmaschine ist fertig, Garagentor ist noch offen, Licht im Flur brennt noch. Dann speichert Alexa die Meldungen quasi zwischen und ich rufe sie bei Bedarf ab. Weil es bringt uns ja nicht viel, wenn Alexa während ich unter der Dusche stehe oder gerade einen Film gucken plötzlich von alleine los plappert. (So ist es z.B. bei mir aktuell).

Nochmal kurz zur Klarstellung, diese Funktion hat (zumindest soweit mir bekannt) nichts mit Telefonieren, Connect, DropIn oder sonstigem zu tun und ich kriege diese Nachrichten auch nicht in der App angezeigt..

Wenn es da Ansätze gibt und ihr Leute zum testen sucht, stehe ich gerne zur Verfügung.

**Comment by Apollon77** [comment]
Ja, du hast Recht.

Das was seit neuestem geht ist https://github.com/Apollon77/ioBroker.alexa2/issues/137 ... das würde aber scheinbar nur Infos an die Apps senden, die Geräte an sich bleiben leider "stumm". Dazu müsste man das hier machen

**Comment by Panoru84** [comment]
Hallo @Apollon77 ,

es gibt mittlerweile einen separaten Skill mit dem man über den Browser Push Benachrichtigungen an die Echo Geräte schicken kann, die dann mit einem gelben Ring diese Notification anzeigen.

Wenn du Zeit hast teste doch mal diesen Skill hier.
https://www.amazon.de/Emil-Thies-Text-Nachricht/dp/B07FDHWT6K

Das ist in meinen Augen ein echtes mega Feature ;-)

Im Englischsprachigen Raum gibt es auch noch Notify Me. Aber das kriegt man hier nicht installiert und wenn man den Account umzieht funktioniert der Rest danach nicht mehr :D http://www.thomptronics.com/notify-me   

Bei Amazon in der Api Doku sieht das folgendermaßen aus:
https://developer.amazon.com/docs/alexa-voice-service/notifications.html

Wie schon erwähnt, wenn du Tester suchst bin ich direkt dabei.

Schönen Gruß

Paul

**Comment by Apollon77** [comment]
Mit genügend Zeit könnte man die Nachrichten-Features der App nachbauen, aber genau diese Zeit fehlt mir im Moment

**Comment by jnsw** [comment]
Push: https://stadt-bremerhaven.de/amazon-alexa-gelber-ring-und-ton-kuendigt-lieferungen-an/

**Comment by Apollon77** [comment]
Das Thema hier ist immer noch das die "gelben Ring Notifications" nicht Device- sondern Userspezifisch sind. Dies bedeutet das zierst die ganze Addressbuchlogik rein muss um dann darüber sowas senden zu können. Das kommt dann bei allen Geräten des Users an und so ...

**Comment by Panoru84** [comment]
Hallo @Apollon77,
es wird dafür aber nicht das "normale" Adressbuch benötigt. Also mit fremden Kontakten.

Das alle Device angesprochen werden ist ja okay und gewollt.
Ich habe jetzt als Notlösung ein Gerät auf einen separaten US Account geswitcht um darauf dann NotifyMe zu nutzen.

**Comment by Apollon77** [comment]
Naja jetzt sind wir bei "in welcher Größe macht ein Feature sinn" :-) Sobald ich es gebaut habe mit "nur an mich selbst senden" verspreche ich das <1 Tag die Issues und wünsche nach "auch fremde Kontakte" kommen ... das weis sich jetzt schon. Und dann muss ich alles nochmal anders konzipieren. Also wenn das richtig

**Comment by jnsw** [comment]
Mir würde das, was [Thomptronics ](https://www.thomptronics.com/about/notify-me) vollkommen ausreichen. Wenn er das doch nur für den deutsch-sprachigen Raum öffnen würde, wäre man sogar unabhängig von ioBroker unterwegs und du hättest weniger Arbeit. Aber natürlich hast du Recht, und das "Feature", dass gleich alle Freunde benachrichtigt werden können, ist für einige sicherlich ein nettes Gimmick.

**Comment by QoSi** [comment]
Hi, habe eine Punktevergabe für Personen über die Alexa eingebaut. Jetzt macht mein Vater nen Witz darüber, dass er Remotezugriff auf meine Alexas bekommen will um auch Punkte zu vergeben. Da kam mir auch der Gedanke, er kann mir ja eine Nachricht schicken und wenn diese ein Textinhalt von wegen "gib xy ein Pluspunkt" enthält, könnte man das für die Pkt.Vergabe abgreifen.  Hoffe Du findest Zeit und weiterhin Motivation für diese Funktion :) Vielen Dank für diese spitzen Alexa Anbindung!

**Comment by Apollon77** [comment]
see 2.6.0 on GitHub

**Comment by Panoru84** [comment]
Hallo @Apollon77 
die Notifications, die ich unter Commands\notification eingebe kommen jetzt als Textnachricht auf meinem Handy an. Ist das so gewollt?

Meine "Wunsch" waren ja die Zwischengespeicherten, abrufbaren Notifications mit dem gelben Ring, wie es mittlerweile ja bei Amazon Lieferungen der Fall ist.

Ich habe als Workaround jetzt 2 Echos auf US Accounts gehängt und nutzte NotifyMe welches ich über ioBroker und IFTTT WebHooks trigger.

**Comment by Apollon77** [comment]
Ich nutze hier die gleichen Namen wie die App.

Notification ist das was aufs Handy kommt.

Das andere geht ab 2.6 vom Adapter indem Du unter "Contacts" den kontakt wählst der eine nachricht bekommen soll (du selbst bist auch gelistet) und dann kannst Du eine Nachricht senden die als gelber ring kommt. Das ist eine Nachricht
