### ISSUE TITLE
Cannot read property 'val' of null

### ISSUE THREAD

**Issue by Mercator18** [Apollon77/ioBroker.alexa2#175]
Hi,

Ich gebe den Anrufernamen vom tr-064 als String auf der Alex-Lautsprecher-Gruppe Überall aus.
Alexa2 Adapter lief soweit auch wie gewünscht, doch nun bekam ich beim Setzen eines Wertes auf Überall ( alexa2.0.Echo-Devices.117ae966eebf4f68b2b38c91e467d51d.Commands.speak) reproduzierbar den Fehler "Caught by controller[0]: TypeError: Cannot read property 'val' of null" und der Adapter startete neu.

Ein de-/install des Adapters hat das Problem momentan gelöst, aber vielleicht kann das als Bugfix in einer künftigen Version ja einfließen.

debug-Log:
alexa2.0	2018-12-30 14:36:49.661	debug	Alexa-Remote: Sending Request with {"host":"alexa-comms-mobile-service.amazon.com","path":"/accounts","method":"GET","timeout":10000,"headers":{}}
alexa2.0	2018-12-30 14:36:49.661	debug	Alexa-Remote: No authentication check needed (time elapsed 1)
alexa2.0	2018-12-30 14:36:49.661	debug	Alexa-Remote: Authentication checked: true
alexa2.0	2018-12-30 14:36:49.660	debug	Alexa-Remote: Response: {"authentication":{"authenticated":true,"canAccessPrimeMusicContent":true,"customerEmail":"xxxx@t-online.de","customerId":"xxx","customerName":"xxx
alexa2.0	2018-12-30 14:36:49.157	debug	Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/bootstrap?version=0","method":"GET","timeout":10000,"headers":{}}
alexa2.0	2018-12-30 14:36:49.157	debug	Alexa-Remote: cookie was provided
alexa2.0	2018-12-30 14:36:49.157	debug	Alexa-Remote: Use as Base-URL: alexa.amazon.de
alexa2.0	2018-12-30 14:36:49.157	debug	Alexa-Remote: Use as Login-Amazon-URL: amazon.de
alexa2.0	2018-12-30 14:36:49.156	debug	Alexa-Remote: Use as User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
alexa2.0	2018-12-30 14:36:49.040	info	starting. Version 1.1.3 in /opt/iobroker/node_modules/iobroker.alexa2, node: v6.16.0
host.ioBroker-Pi	2018-12-30 14:36:48.383	info	instance system.adapter.alexa2.0 started with pid 1967
host.ioBroker-Pi	2018-12-30 14:36:18.364	info	Restart adapter system.adapter.alexa2.0 because enabled
host.ioBroker-Pi	2018-12-30 14:36:18.364	error	instance system.adapter.alexa2.0 terminated with code 6 (uncaught exception)
host.ioBroker-Pi	2018-12-30 14:36:18.364	error	Caught by controller[0]: at Manager.ondata (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:335:16)
host.ioBroker-Pi	2018-12-30 14:36:18.363	error	Caught by controller[0]: at Decoder.add (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-parser/index.js:251:12)
host.ioBroker-Pi	2018-12-30 14:36:18.363	error	Caught by controller[0]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
host.ioBroker-Pi	2018-12-30 14:36:18.363	error	Caught by controller[0]: at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.ioBroker-Pi	2018-12-30 14:36:18.363	error	Caught by controller[0]: at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
host.ioBroker-Pi	2018-12-30 14:36:18.363	error	Caught by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
host.ioBroker-Pi	2018-12-30 14:36:18.363	error	Caught by controller[0]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.ioBroker-Pi	2018-12-30 14:36:18.363	error	Caught by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
host.ioBroker-Pi	2018-12-30 14:36:18.363	error	Caught by controller[0]: at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
host.ioBroker-Pi	2018-12-30 14:36:18.362	error	Caught by controller[0]: at Socket.adapter.getState (/opt/iobroker/node_modules/iobroker.alexa2/main.js:1447:42)
host.ioBroker-Pi	2018-12-30 14:36:18.362	error	Caught by controller[0]: TypeError: Cannot read property 'val' of null
alexa2.0	2018-12-30 14:36:15.575	debug	State changed alexa2.0.Echo-Devices.G2A0QU06819400CS.Player.mediaProgressStr: {"val":"46:16","ack":true,"ts":1546176975574,"q":0,"from":"system.adapter.alexa2.0","lc":1546176975574}
alexa2.0	2018-12-30 14:36:15.575	debug	State changed alexa2.0.Echo-Devices.G2A0QU06819400CS.Player.mediaProgress: {"val":2776,"ack":true,"ts":1546176975572,"q":0,"from":"system.adapter.alexa2.0","lc":1546176975572}
alexa2.0	2018-12-30 14:36:15.573	debug	State changed alexa2.0.Echo-Devices.G2A0QU06819400CS.Player.mediaProgressPercent: {"val":0,"ack":true,"ts":1546176975570,"q":0,"from":"system.adapter.alexa2.0","lc":1546113247114}
alexa2.0	2018-12-30 14:36:13.574	debug	State changed alexa2.0.Echo-Devices.G2A0QU06819400CS.Player.mediaProgressStr: {"val":"46:14","ack":true,"ts":1546176973572,"q":0,"from":"system.adapter.alexa2.0","lc":1546176973572}
alexa2.0	2018-12-30 14:36:13.573	debug	State changed alexa2.0.Echo-Devices.G2A0QU06819400CS.Player.mediaProgress: {"val":2774,"ack":true,"ts":1546176973570,"q":0,"from":"system.adapter.alexa2.0","lc":1546176973570}
alexa2.0	2018-12-30 14:36:13.570	debug	State changed alexa2.0.Echo-Devices.G2A0QU06819400CS.Player.mediaProgressPercent: {"val":0,"ack":true,"ts":1546176973568,"q":0,"from":"system.adapter.alexa2.0","lc":1546113247114}
alexa2.0	2018-12-30 14:36:11.569	debug	State changed alexa2.0.Echo-Devices.G2A0QU06819400CS.Player.mediaProgressStr: {"val":"46:12","ack":true,"ts":1546176971567,"q":0,"from":"system.adapter.alexa2.0","lc":1546176971567}
alexa2.0	2018-12-30 14:36:11.568	debug	State changed alexa2.0.Echo-Devices.G2A0QU06819400CS.Player.mediaProgress: {"val":2772,"ack":true,"ts":1546176971566,"q":0,"from":"system.adapter.alexa2.0","lc":1546176971566}
alexa2.0	2018-12-30 14:36:11.568	debug	State changed alexa2.0.Echo-Devices.G2A0QU06819400CS.Player.mediaProgressPercent: {"val":0,"ack":true,"ts":1546176971565,"q":0,"from":"system.adapter.alexa2.0","lc":1546113247114}
alexa2.0	2018-12-30 14:36:09.576	debug	State changed alexa2.0.Echo-Devices.G2A0QU06819400CS.Player.mediaProgressStr: {"val":"46:10","ack":true,"ts":1546176969568,"q":0,"from":"system.adapter.alexa2.0","lc":1546176969568}
alexa2.0	2018-12-30 14:36:09.569	debug	State changed alexa2.0.Echo-Devices.G2A0QU06819400CS.Player.mediaProgress: {"val":2770,"ack":true,"ts":1546176969565,"q":0,"from":"system.adapter.alexa2.0","lc":1546176969565}

**Comment by Apollon77** [comment]
retry 2.1  von Github
