### ISSUE TITLE
Reminder (Erinnerungen)/Alerts (Wecker) Support

### ISSUE THREAD

**Issue by Apollon77** [Apollon77/ioBroker.alexa2#18]
So what I found out:
- Reminder can be created, changed and are auto-removed when done, but can be deleted before

- Alerts can not be created? (only using device?), but enabled/disabled, changed and deleted

Timer can only be created using device

**Comment by Panoru84** [comment]
Hello and thanks for your great work first!

It would be very helpful to read and set the status of the alexa alarm (Wecker).
This Alarm can be set very easy on Alexa via Voice and I would love to trigger other devices by this alarm, e.g. Lights, Coffee etc.

If you need tester or examples just contact me.

Thank you for this great tool!!!

**Comment by ooooli** [comment]
My use case: get notification / trigger, when a alarm is enabled.
I use e.g. "Alexa, wecke mich morgen früh um 6:30 mit SWR3". When this alarm is starting, I want to trigger my thermostat in the bathroom to heat up.
Currently, I'm realizing this function with IFTTT in ioBroker, unfortunately is it only working with alarm sounds and no music on alarm...

**Comment by Apollon77** [comment]
So you would need an info when the alarm gets triggered?! If this works I‘m not sure. 

We can read created alarms, enable/disable them and change them. 
There is no info on „trigger“. 

But possible should be to create a smart device to an ioBroker State or device to trigger with the alarm.

**Comment by ooooli** [comment]
Triggering a device is a workround that should also be an option.

**Comment by Apollon77** [comment]
Maybe we manage to get the push channel working as in the app then maybe we can do more but it’s not that easy ...

**Comment by Matten-Matten** [comment]
Ich würde die Wecker Funktion auch super finden. 

Gruß 
Matten

**Comment by Apollon77** [comment]
Die 0.5.0 wird folgendes haben: pro evice was es unterstützt neue States für "Reminder" und "Alarm" wo alles existierende gelistet ist, enable/disable, Zeiteinstellung und Änderungen erlaubt. Weiterhin ein State der auf true gesetzt wird wenn der Wecker/Reminder getriggert wird ... geht aber jur wenn Echo und ioBroker-Server zeit zusammenpassen weil der Adapter sich die Zeit raussucht und dann triggert ... bei Zeitunterschieden kommt da also müll raus. Geht aber gerade nicht anders weil es keinen Trigger gibt.
Beim Anlegen von neuen Weckern/Remindern per App oder Sprache werden die States passend angelegt, beim löschen wieder gelöscht.

Ich schaue heute Abend noch ob auch "Timer" darüber gehen, wenn ja kommt das noch rein, wenn nein nicht :-)

Also: Stay tuned

**Comment by Apollon77** [comment]
Timer wollen nicht, 0.5.0 auf Github
