### ISSUE TITLE
Hue Motionsensor - Kein Update 

### ISSUE THREAD

**Issue by Jastroger** [Apollon77/ioBroker.alexa2#181]
Hallo Apollon,

erstmal vielen Dank für deine top Arbeit am Alexa2 Adapter. 
Ich habe folgende Herausforderung: 

Adapter Version 2.0.0 frisch von GitHub 

- neue Hue Motionsensoren (erstmalig eingerichtet) (Model: 9290012607)
- Datenpunkte werden erkannt und angelegt
- Zustand bleibt der zuerst eingelesene bei Instanz start
- Query bringt auch nichts (Update: Hab grad gelesen das du die Abfrage limitiert hast, Query bringt nun doch was wenn man die Zeit einhält)
- Neu anlegen bringt auch nichts (Verhalten wie Neustart des Adapters [Zustand einmalig korrekt])

Vermutung: Abbruch der Abfrage aufgrund vorgelagertem Fehler beim Auslesen des Datenpunkt

Sensor wurde mittels Alexa Routine bereits erfolgreich verwendet. Wollte die Logik jetzt auf iobroker verlagern.

IOBroker habe ich frisch updated & upgraded.

Gruß,
Jan

Folgende Log Infos:

Name | Datum | Debug | Meldung
-- | -- | -- | --
alexa2.0 | 2019-01-06 00:40:03.092 | warn | Smart Home device request blocked for AAA_SonarCloudService_00:17:88:01:03:2A:BC:BD
alexa2.0 | 2019-01-06 00:38:38.448 | info | {"applianceId":"AAA_SonarCloudService_00:17:88:01:03:2A:C1:C7","endpointTypeId":"","driverIdentity":{"namespace":"AAA","identifier":"SonarCloudService"},"manufacturerName":"Philips","friendlyDescript
alexa2.0 | 2019-01-06 00:38:38.448 | info | Smarthome-Device Capability Alexa.EndpointHealth for batteryState unknown. Report to developer this and next log line from logfile on disk!
alexa2.0 | 2019-01-06 00:38:38.447 | info | {"applianceId":"AAA_SonarCloudService_00:17:88:01:03:2A:C1:C7","endpointTypeId":"","driverIdentity":{"namespace":"AAA","identifier":"SonarCloudService"},"manufacturerName":"Philips","friendlyDescript
alexa2.0 | 2019-01-06 00:38:38.447 | info | Smarthome-Device Capability Alexa.MotionSensor for detectionState.detectionState experimentally supported. Please check and report to developer this and next log line from logfile on disk if it works
alexa2.0 | 2019-01-06 00:38:38.446 | info | {"applianceId":"AAA_SonarCloudService_00:17:88:01:03:2A:C1:C7","endpointTypeId":"","driverIdentity":{"namespace":"AAA","identifier":"SonarCloudService"},"manufacturerName":"Philips","friendlyDescript
alexa2.0 | 2019-01-06 00:38:38.445 | info | Smarthome-Device Capability Alexa.BatteryLevelSensor unknown. Report to developer this and next log line from logfile on disk!
alexa2.0 | 2019-01-06 00:38:38.443 | info | {"applianceId":"AAA_SonarCloudService_346aa44d-a4cb-365e-a0eb-4715fd048e1e","endpointTypeId":"","driverIdentity":{"namespace":"AAA","identifier":"SonarCloudService"},"manufacturerName":"Amazon","frie
alexa2.0 | 2019-01-06 00:38:38.442 | info | Smarthome-Device Capability Alexa.AcousticEventSensor unknown. Report to developer this and next log line from logfile on disk!
alexa2.0 | 2019-01-06 00:38:38.441 | info | {"applianceId":"AAA_SonarCloudService_00:17:88:01:03:2A:BC:BD","endpointTypeId":"","driverIdentity":{"namespace":"AAA","identifier":"SonarCloudService"},"manufacturerName":"Philips","friendlyDescript
alexa2.0 | 2019-01-06 00:38:38.441 | info | Smarthome-Device Capability Alexa.EndpointHealth for batteryState unknown. Report to developer this and next log line from logfile on disk!
alexa2.0 | 2019-01-06 00:38:38.440 | info | {"applianceId":"AAA_SonarCloudService_00:17:88:01:03:2A:BC:BD","endpointTypeId":"","driverIdentity":{"namespace":"AAA","identifier":"SonarCloudService"},"manufacturerName":"Philips","friendlyDescript
alexa2.0 | 2019-01-06 00:38:38.439 | info | Smarthome-Device Capability Alexa.MotionSensor for detectionState.detectionState experimentally supported. Please check and report to developer this and next log line from logfile on disk if it works
alexa2.0 | 2019-01-06 00:38:38.439 | info | {"applianceId":"AAA_SonarCloudService_00:17:88:01:03:2A:BC:BD","endpointTypeId":"","driverIdentity":{"namespace":"AAA","identifier":"SonarCloudService"},"manufacturerName":"Philips","friendlyDescript
alexa2.0 | 2019-01-06 00:38:38.428 | info | Smarthome-Device Capability Alexa.BatteryLevelSensor unknown. Report to developer this and next log line from logfile on disk!
alexa2.0 | 2019-01-06 00:38:28.444 | info | Alexa-Push-Connection established. Disable Polling
alexa2.0 | 2019-01-06 00:38:23.381 | info | starting. Version 2.0.0 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.15.0
alexa2.0 | 2019-01-06 00:38:23.201 | info | States connected to redis: 127.0.0.1:6379
host.jarves | 2019-01-06 00:38:21.796 | info | instance system.adapter.alexa2.0 started with pid 3692

**Comment by Apollon77** [comment]
Wenn dein Ziel ist das eine Bewegung live an iobroker gemeldet wird und du darauf reagieren kannst muss ich enttäuschen. Status von Geräten wird nach aktuellem Wissensstand nicht aktiv gemeldet sondern kann nur abgefragt werden. 

Siehst du denn in der Alexa App den Status?

**Comment by sigi2345** [comment]
Hallo, geht mit Node Red......

**Comment by Jastroger** [comment]
Hallo zusammen,

danke für das Feeback. 

@Apollon77 Ja, der Motionsensor gibt eine Rückmeldung in der App ((nicht) erkannt, Zeitstempel)
(siehe Screenshot). Meintest du das?

@sigi2345 Hi Sigi, danke für den Hinweis auf Node-Red. Damit habe ich mich bislang noch gar nicht beschäftigt - sollte ich vielleicht mal jetzt machen 👍 

![screenshot_2019-01-06-11-38-27](https://user-images.githubusercontent.com/46408699/50735002-ff2f2080-11a7-11e9-9999-89efc2b43dd9.png)

**Comment by Apollon77** [comment]
@sigi2345 Was genau mit node-red? Welches Modul? Wie geht es da? Wenn es so geht sollte es möglich sein zu adaptieren

**Comment by Jastroger** [comment]
Vermutlich in Verbindung mit einer Hue-bridge (?). Ich verwende aber aktuell (noch) den integrierten Hub des Echo Plus. Vielleicht wird es Zeit...

Die Lichtsensoren kann ich ja auch nicht sehen/steuern.

Falls euch noch was erleuchtendes einfällt, wäre ich dankbar - allerdings geht das schon in Richtung "off topic" zum vermeintlichen Issue.

**Comment by ceotjoe** [comment]
Also ich hab mit dem Hue Motion Sensor auch schon etwas experimentiert, was das betrifft, aber an einer Hue Bridge. Für mich gab es da keine befriedigende Lösung, weil die Hue Bridge ja gepollt werden muß. Jetzt kann man das Ding natürlich alle paar Sekunden pollen, was aber nicht grade effektiv ist. IMHO kann das NodeRed auch nicht anders machen, als pollen. Ich finde pollen bei nem Motion Sensor aber komplett ineffizient. Meine Meinung! 

Ich hab das jetzt hier nur noch geschrieben, damit Du Dir nicht aus purer Verzweiflung eine Bridge kaufst, die hilft da auch nicht wirklich viel. :-)

**Comment by Jastroger** [comment]
Okay - verrückt - Dabei dachte ich, dass ein "Melder" meldet und nicht nur Informations-Quelle ist. 
Demnach wird die Alexa App wohl auch in regelmäßigen Abständen einen Query absetzen um den Status zu erhalten.

Schade.

**Comment by Jastroger** [comment]
Das kann ich so nicht bestätigen. 
Ich bin mal gerade mit geöffneter Geräte-Seite (Alexa App, Android) des Motion Sensors (Zustand: keine Bewegung erkannt) in den Raum gelaufen - sobald ich drin war wurde der Status auf "Bewegung erfasst" geändert.

**Comment by Apollon77** [comment]
Interessant ... müsste man jetzt mal den Netzwerkverkehr mitschneiden... bzw wenn DU wsowas machst gibt es im ioBroker Log irgendwas? Vllt gibt es ja eine neue Push-Notification die ich noch nicht kenne

**Comment by sigi2345** [comment]
Hallo,

ich habe es von hier:

[https://forum.iobroker.net/viewtopic.php?f=24&t=11751&start=20#p179127](url)

**Comment by Apollon77** [comment]
Naja das ist ja aber auch Anbindung über die Hue bridge bzw Hue und nicht Alexa ...

Also Du kannst gern Alexa2 mal in Debug log  modus schalten und dann starten und wenn das durch ist mal eine bewegung forcieren und schauen ob om Log irgendwas passiert. Wenn ja nehm ich die Info gern.

Sonst bräuchte ich einen zigbee bewegunsgmelder zum selbst testen :-(

**Comment by Jastroger** [comment]
Nachdem ich mir node-Red mal angesehen habe ist mir das leider auch klar geworden. 

Ich werde morgen mal mit dem Debug Mode drauf schauen. Brauchst keine Einkaufstour zu starten. Hab gestern schon mal mit Wireshark mitgeschnitten was vom Sensor wann an Amazon gesendet wird. Muss ich aber auch erst noch auswerten.  

Ich halt dich auf dem laufenden.

**Comment by Apollon77** [comment]
Interessanter wäre was die Alexa App von den Amazon Servern bekommt das Sie den Status "live" anzeigen kann bzw was die App tut damit das klappt.
Falls es Web ist dann eignet sich "Charles Proxy" sehr gut. Die Apps haben aber auch eine Art "Binärverbindung" mit sowas ähnlichem wie MQTT, das würde aber das Alexa2-Adapter Debug Log zeigen weil wir das gleiche tun da wie die App. Es sei denn Sie haben was drittes neues :-)

**Comment by Jastroger** [comment]
So. Wie versprochen Log-file Daten.
Das ist der Motionsensor im Adapter Debug mode wenn ich manuell auf #Query klicke:

Name | Datum | Debug | Meldung
-- | -- | -- | --
alexa2.1 | 2019-01-09 21:50:10.577 | debug | State changed alexa2.1.Smart-Home-Devices.db73f786-a869-4bc5-9a94-7a9967c233c0.connectivity: {"val":true,"ack":true,"ts":1546784693241,"q":0,"from":"system.adapter.alexa2.1","lc":1546784693241}
alexa2.1 | 2019-01-09 21:50:10.574 | debug | State changed alexa2.1.Smart-Home-Devices.db73f786-a869-4bc5-9a94-7a9967c233c0.detectionState: {"val":false,"ack":true,"ts":1547066985393,"q":0,"from":"system.adapter.alexa2.1","lc":1547066712056}
alexa2.1 | 2019-01-09 21:50:10.573 | debug | State changed alexa2.1.Smart-Home-Devices.db73f786-a869-4bc5-9a94-7a9967c233c0.temperature-scale: {"val":"CELSIUS","ack":true,"ts":1547066541407,"q":0,"from":"system.adapter.alexa2.1","lc":1547066541
alexa2.1 | 2019-01-09 21:50:10.572 | debug | State changed alexa2.1.Smart-Home-Devices.db73f786-a869-4bc5-9a94-7a9967c233c0.temperature: {"val":23.87,"ack":true,"ts":1547066541407,"q":0,"from":"system.adapter.alexa2.1","lc":1547066541407}
alexa2.1 | 2019-01-09 21:50:10.557 | debug | unsupported name "Alexa.EndpointHealth.batteryState" for Smart-Home-Devices.db73f786-a869-4bc5-9a94-7a9967c233c0.batteryState
alexa2.1 | 2019-01-09 21:50:10.551 | debug | Alexa-Remote: Response: {"deviceStates":[{"entity":{"entityId":"AAA_SonarCloudService_00:17:88:01:03:2A:C1:C7","entityType":""},"capabilityStates":["{\"namespace\":\"Alexa.TemperatureSensor\",\"name\
alexa2.1 | 2019-01-09 21:50:10.243 | debug | Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/phoenix/state","method":"POST","timeout":10000,"headers":{}}and data={"stateRequests":[{"entityId":"AAA_SonarCloudService_00:
alexa2.1 | 2019-01-09 21:50:10.241 | debug | Alexa-Remote: No authentication check needed (time elapsed 343671)

Und das hier zum Zeitpunkt der Bewegung erkannt/nicht erkannt:

Name | Datum | Debug | Meldung
-- | -- | -- | --
alexa2.1 | 2019-01-09 21:56:13.864 | debug | State changed alexa2.1.Echo-Devices.f83c59e6517e4e6c98dd4a3e29a4eb6b.Player.muted: {"val":false,"ack":true,"ts":1547067373856,"q":0,"from":"system.adapter.alexa2.1","lc":1547066693199}
alexa2.1 | 2019-01-09 21:56:13.864 | debug | State changed alexa2.1.Echo-Devices.f83c59e6517e4e6c98dd4a3e29a4eb6b.Player.volume: {"val":7,"ack":true,"ts":1547067373853,"q":0,"from":"system.adapter.alexa2.1","lc":1547066693196}
alexa2.1 | 2019-01-09 21:56:13.858 | debug | Alexa-Push-Connection Device Volume change for f83c59e6517e4e6c98dd4a3e29a4eb6b -> 7/false
alexa2.1 | 2019-01-09 21:56:13.858 | debug | Alexa-Remote WS-MQTT: Command PUSH_VOLUME_CHANGE: { "destinationUserId": "AJWY7AMV7IX9H", "dopplerId": { "deviceSerialNumber": "f83c59e6517e4e6c98dd4a3e29a4eb6b", "deviceType":
alexa2.1 | 2019-01-09 21:56:13.629 | debug | State changed alexa2.1.Echo-Devices.f83c59e6517e4e6c98dd4a3e29a4eb6b.online: {"val":true,"ack":true,"ts":1547067373620,"q":0,"from":"system.adapter.alexa2.1","lc":1547067373620}
alexa2.1 | 2019-01-09 21:56:13.623 | debug | Alexa-Push-Connection Device Connection change for f83c59e6517e4e6c98dd4a3e29a4eb6b -> ONLINE
alexa2.1 | 2019-01-09 21:56:13.622 | debug | Alexa-Remote WS-MQTT: Command PUSH_DOPPLER_CONNECTION_CHANGE: { "destinationUserId": "AJWY7AMV7IX9H", "dopplerId": { "deviceSerialNumber": "f83c59e6517e4e6c98dd4a3e29a4eb6b", "
alexa2.1 | 2019-01-09 21:56:11.774 | debug | State changed alexa2.1.Echo-Devices.f83c59e6517e4e6c98dd4a3e29a4eb6b.online: {"val":false,"ack":true,"ts":1547067371763,"q":0,"from":"system.adapter.alexa2.1","lc":1547067371763}
alexa2.1 | 2019-01-09 21:56:11.774 | debug | Alexa-Push-Connection Device Connection change for f83c59e6517e4e6c98dd4a3e29a4eb6b -> OFFLINE
alexa2.1 | 2019-01-09 21:56:11.772 | debug | Alexa-Remote WS-MQTT: Command PUSH_DOPPLER_CONNECTION_CHANGE: { "destinationUserId": "AJWY7AMV7IX9H", "dopplerId": { "deviceSerialNumber": "f83c59e6517e4e6c98dd4a3e29a4eb6b", "

Vielleicht reicht dir das schon als Info.

**Comment by Apollon77** [comment]
Sind zwear leider die abgeschnittenen Logs aus Admin aber ok. Naja man sieht halt leider bei der Ändeung nichts. Das was da steht ist das ein Device (denke dein Handy) live gekommen ist ... aber nichts von anderen Dingen :-(

**Comment by Jastroger** [comment]
Okay. Ich logge mal morgen was längeres. Das Log schick ich dir aber dann direkt. Hab auch mal mit Charles mitgeschnitten - leider alles SSL. Da komm ich nicht so ohne Weiteres dazwischen. 
Falls du noch anderes Output brauchst sag mir einfach was ich wie mitschneiden soll. 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 09.01.19, 23:09, Ingo Fischer <notifications@github.com> schrieb:
Sind zwear leider die abgeschnittenen Logs aus Admin aber ok. Naja man sieht halt leider bei der Ändeung nichts. Das was da steht ist das ein Device (denke dein Handy) live gekommen ist ... aber nichts von anderen Dingen :-(



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Apollon77/ioBroker.alexa2","title":"Apollon77/ioBroker.alexa2","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Apollon77/ioBroker.alexa2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Apollon77 in #181: Sind zwear leider die abgeschnittenen Logs aus Admin aber ok. Naja man sieht halt leider bei der Ändeung nichts. Das was da steht ist das ein Device (denke dein Handy) live gekommen ist ... aber nichts von anderen Dingen :-("}],"action":{"name":"View Issue","url":"https://github.com/Apollon77/ioBroker.alexa2/issues/181#issuecomment-452887532"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Apollon77/ioBroker.alexa2/issues/181#issuecomment-452887532",

"url": "https://github.com/Apollon77/ioBroker.alexa2/issues/181#issuecomment-452887532",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Apollon77** [comment]
Charles and SSL: https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/ very easy :-)

**Comment by Jastroger** [comment]
Ich muss doch die Android mit dem Charles Certificate vertraut machen oder? Das ist wie ich lese nicht ganz so trivial. 

Oder versteh ich da jetzt was falsch? 
Am 09.01.19, 23:47, Ingo Fischer <notifications@github.com> schrieb:
Charles and SSL: https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/ very easy :-)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Apollon77/ioBroker.alexa2","title":"Apollon77/ioBroker.alexa2","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Apollon77/ioBroker.alexa2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Apollon77 in #181: Charles and SSL: https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/ very easy :-)"}],"action":{"name":"View Issue","url":"https://github.com/Apollon77/ioBroker.alexa2/issues/181#issuecomment-452898434"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Apollon77/ioBroker.alexa2/issues/181#issuecomment-452898434",
"url": "https://github.com/Apollon77/ioBroker.alexa2/issues/181#issuecomment-452898434",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Apollon77** [comment]
Ja, bei ios sehr simpel. Android weiss ich nicht :-)

**Comment by Jastroger** [comment]
Ich such mal mein IPhone 6. To be continued... :)
Am 09.01.19, 23:55, Ingo Fischer <notifications@github.com> schrieb:
Ja, bei ios sehr simpel. Android weiss ich nicht :-)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Apollon77/ioBroker.alexa2","title":"Apollon77/ioBroker.alexa2","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Apollon77/ioBroker.alexa2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Apollon77 in #181: Ja, bei ios sehr simpel. Android weiss ich nicht :-)"}],"action":{"name":"View Issue","url":"https://github.com/Apollon77/ioBroker.alexa2/issues/181#issuecomment-452900573"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Apollon77/ioBroker.alexa2/issues/181#issuecomment-452900573",
"url": "https://github.com/Apollon77/ioBroker.alexa2/issues/181#issuecomment-452900573",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Jastroger** [comment]
Ping mich mal bitte zwecks weiterer Logs per Mail an - Adresse steht im Profil. 
Danke!

**Comment by Apollon77** [comment]
Ok, Danke für die Logs.
Das Log Zeigt das die Alexa-App alle 3 Sekunden (denke sobald man auf der Device-Seite des Bewegungsmelders ist) eine Statusanfrage an Amazon sendet. Also die nutzen long polling, da ist nichts push :-(

**Comment by Jastroger** [comment]
So kann man auch checken ob jemand die App nutzt ^^ 
Okay. Kannst ja mal überlegen ob  du das ggf. für die Motion Sensoren ohne Rücksicht auf Traffic umsetzen möchtest. Ich fände es ganz gut - dadurch könnte man die Möglichkeiten an einigen Stellen verbessern.

Du hast nicht zufällig eine Rückmeldung vom Device gefunden, die die Lichtmessungsdaten beinhaltet? - Die Hue Melder können das prinzipiell, allerdings bislang nur mit Anbindung an die Bridge (hab ich gelesen)

**Comment by Apollon77** [comment]
naja. ich weiss das es Traffic/Rate Limits bei der API gibt, aber habe keine Ahnung wo die genau liegen. da die App immer nur ein Device im Fokus hat mag es auf die Traffic Limits abgestimmt sein, keine Ahnung wie das mit mehreren Devices aussieht.

die idee ist das in einer nächsten Version das aktuelle query Limit konfigurierbar wird, dann könntest Du selbst entscheidn wie oft du es pollst und auch welches bei mehreren geräten und so

**Comment by Jastroger** [comment]
Klingt nach einem Plan.
Danke fürs Feedback und weiterhin happy coding! Wenn ich nicht so ein ewiger C#er wär, hätte ich dir gern meine Unterstützung angeboten. In JS bin ich nicht ganz so sicher unterwegs. Da würde vermutlich deine Code-Qualität leiden.

**Comment by Apollon77** [comment]
Naja der Adapter ist jetzt von der Code Quality nicht unbedingt preisverdächtig :-) Im zweifel nimm dir was kleineres und mach nen PR ... dann sehen wir es :-)

**Comment by Jastroger** [comment]
Check! Issue closed.
