### ISSUE TITLE
"Login unsuccessfull. Please check credentials" bcs mail format?

### ISSUE THREAD

**Issue by t6a** [Apollon77/ioBroker.alexa2#186]
Getting the error "Login unsuccessfull. Please check credentials.".
But mail and password are correct. Could it be that the E-Mail should not contain a plus "+" character?
(I'am using a xyz+shop@gmail.com address for labelling purposes in gmail)

**Comment by Apollon77** [comment]
The auto login is no longer working because of changes by Amazon. Please start adapter and check logs to get the Proxy-URL to login there- After tjhs adapter should restart and it should work
