### ISSUE TITLE
Stoppt Musikwiedergabe bei Spotify

### ISSUE THREAD

**Issue by tobschn** [Apollon77/ioBroker.alexa2#189]
Guten Tag,
wie oben beschrieben stoppt die Musikwiedergabe über Spotify immer, dann, wenn die Daten über Alexa2 aktualisiert werden. Der Fehler tritt sogut wie immer auf, wenn die Musik auf Multiroom Gruppen wiedergegeben soll. Jedoch passiert es auch ab und zu, wenn nur ein Gerät die Musik abspielen soll. Es werden keine Fehler in die Log geschrieben (oder kann ich irgendwo erweitertes Debugging aktivieren?). Andere Wiedergabequellen, wie tunein sind nicht betroffen.

**Comment by Jastroger** [comment]
Hi,
zum Thema Logging:
- Expertenmodus für Instanzen einschalten 
![image](https://user-images.githubusercontent.com/46408699/51075901-2eef9400-1692-11e9-98b9-a719cbb5a555.png)
- alexa2.x Zeile suchen 
- Log Stufe auf 'debug' stellen

**Comment by Apollon77** [comment]
Im Forum gibts einen Diskussionsthtead dazu. 

Das Problem ist das der Adapter nichts tut was das verursacht. Aktuelle Logs zeigen das der Adapter plötzlich zeitgleich zu der Medien Status Abfrage (die regelmäßig gemacht wird) eine abbruchmeldung der Wiedergabe kommt. 

Bitte mal das Echo gerät neu starten. Passiert es dann immer noch?

**Comment by tobschn** [comment]
Sehr merkwürdig, habe gerade beide Alexa Dots neugestartet, leider tritt das Problem immernoch auf. Brauchst du noch Log-Dateien von mir? Wenn der Adapter deaktiviert ist, funktioniert alles wie es soll.

**Comment by Apollon77** [comment]
Ich schliesse den Bug, DIskussion und Vermutungen und so bitte unter https://forum.iobroker.net/viewtopic.php?f=37&t=18631 ... wenn sich mal etwas wirklich herauskristallisiert was ich tun könnte im Adapter dann können wir ein Issue wieder auf machen
