### ISSUE TITLE
Create object according to capabilities of device

### ISSUE THREAD

**Issue by Marty56** [Apollon77/ioBroker.alexa2#19]
I note that some Alexa device do not support e.g. the speak command.
It would be great if the related objects would not be created if the capabilities do not support command.

**Comment by Apollon77** [comment]
Check 0.2.4 from yesterday. 

It is great if unwound know the meaning of all of the capabilities... do yo know them?!

So please reopen after checking 0.2.4 with details of things not working together with details of the devices.

**Comment by Marty56** [comment]
"unwound", do not understand the word in this context. German translation would be fine swell.

**Comment by Marty56** [comment]
OK. Summary of my findings:
Alexa Speakers have the capabilities
DREAM_TRAINING,CUSTOM_ALARM_TONE,POPTART,EARCONS,PAIR_BT_SINK,DEREGISTER_DEVICE,LEMUR_ALPHA,ACTIVE_AFTER_FRO,SUPPORTS_SOFTWARE_VERSION,PERSISTENT_CONNECTION,CHANGE_NAME,FAR_FIELD_WAKE_WORD,PAIR_BT_SOURCE,TIMERS_AND_ALARMS,GOLDFISH,AUDIO_PLAYER,VOICE_TRAINING,FLASH_BRIEFING,UPDATE_WIFI,SALMON,PANDORA,I_HEART_RADIO,SUPPORTS_CONNECTED_HOME_ALL,SET_LOCALE,REQUIRES_OOBE_FOR_SETUP,DEREGISTER_FACTORY_RESET,SLEEP,VOLUME_SETTING,AMAZON_MUSIC,SUPPORTS_CONNECTED_HOME,TUNE_IN,REMINDERS,PAIR_REMOTE,AUDIBLE,SOUND_SETTINGS,KINDLE_BOOKS
- Everything is working but
- volume control does NOT work for Routines and for everything which is started under Commands

a Songs Speaker which has the capabilities:
AUDIO_PLAYER,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,AMAZON_MUSIC,TUNE_IN,PANDORA,REMINDERS,I_HEART_RADIO,CHANGE_NAME,VOLUME_SETTING,PEONY.
- The player commands and also tuneIn is working. 
- everything which is under Command is NOT working
- Routines are NOT working

2. a multiform group which has the capabilities:
AUDIO_PLAYER,AMAZON_MUSIC,TUNE_IN,SALMON,AUDIBLE,PANDORA,I_HEART_RADIO,KINDLE_BOOKS,VOLUME_SETTING
- The player commands and also tuneIn is working. 
- everything which is under Command is NOT working
- Routines are NOT working

hope this helps.

**Comment by Apollon77** [comment]
thank you, will try to make things better.
Did you already tried 0.2.4 and deleted objects?
In 0.2.4 in some cases already Bluetooth/Commands/Routines should already not be created

**Comment by Apollon77** [comment]
Multiroom: "SALMON", "I_HEART_RADIO", "AMAZON_MUSIC", "TUNE_IN", "VOLUME_SETTING", "AUDIO_PLAYER", "PANDORA", "KINDLE_BOOKS", "AUDIBLE"

* The player commands and also tuneIn is working.
* everything which is under Command is NOT working
* Routines are NOT working

**Comment by Marty56** [comment]
Ok. I have delete all object and restarted the adapter.
I see that in Sonos case the Commands and the Routine objects are regenerated.
In the group although they are now rightfully missing. Although of course it would be great if the could reappear working :-)

**Comment by Apollon77** [comment]
Ok, bevor ich rausfinde welche der Capabilties für was verantwortlich sind machen wir es hart coded nach Typ:

const knownDeviceType = {
    "A3S5BH2HU6VAYF":   {name: "Echo Dot 2.Gen", commandSupport: true},
    "AB72C64C86AW2":    {name: "Echo", commandSupport: true},
    "A7WXQPH584YP":     {name: "Echo 2.Gen", commandSupport: true},
	"A10A33FOX2NUBK":   {name: "Echo Spot", commandSupport: true},
	"A1NL4BVLQ4L3N3":	{name: "Echo Show", commandSupport: true},
    "A15ERDAKK5HQQG":   {name: "Sonos", commandSupport: false},
    "A2E0SNTXJVT7WK":   {name: "Fire TV V1", commandSupport: false},
    "ADVBD696BHNV5":    {name: "Fire TV Stick V1", commandSupport: false},
    "A2LWARUGJLBYEW":   {name: "Fire TV Stick V2", commandSupport: false},
    "A2T0P32DY3F7VB":   {name: "echosim.io", commandSupport: false},
    "AILBSA2LNTOYL":    {name: "reverb App", commandSupport: false},
    "A2M35JJZWCQOMZ":   {name: "Echo Plus", commandSupport: true}
};

**Comment by Apollon77** [comment]
So lange bis jemand genauer weiss wie die capabilities sind ist es ongoing mit dem sammeln von deviceTypen
