### ISSUE TITLE
unknown device type: UE MEGABLAST

### ISSUE THREAD

**Issue by BlueEssi** [Apollon77/ioBroker.alexa2#190]
Device-type:AINRG27IL8AS0  (DEREGISTER_DEVICE,MUSIC_SKILL,KINDLE_BOOKS,CHANGE_NAME,AMAZON_MUSIC,PAIR_BT_SINK,GOLDFISH,PERSISTENT_CONNECTION,DREAM_TRAINING,VOLUME_SETTING,REMINDERS,AUDIBLE,SLEEP,PE

The adapter stops working after some time. Please add the new device type.

**Comment by Apollon77** [comment]
Please add full device info from logfile ... this one above is cutted.

The Missing device is NOT the reason for a stopping of adapter. What exactly you mean? After 14 days?

**Comment by BlueEssi** [comment]
Oh, sorry:
Device-type:AINRG27IL8AS0 (TUNE_IN,KINDLE_BOOKS,PAIR_BT_SINK,TIMERS_AND_ALARMS,MICROPHONE,AUDIBLE,CHANGE_NAME,GOLDFISH,REMINDERS,VOLUME_SETTING,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,DREAM_TRAINING,SLEEP,PERSISTENT_CONNECTION,AMAZON_MUSIC,I_HEART_RADIO,MUSIC_SKILL,PEONY,AUDIO_PLAYER,DEREGISTER_DEVICE)

At the moment the adapter doesn't crash. I have to keep an eye on it.

**Comment by Apollon77** [comment]
What device is it? What it is capable of?

**Comment by BlueEssi** [comment]
https://www.ultimateears.com/de-de/wireless-speakers/megablast.html

**Comment by Apollon77** [comment]
Can you use Routines to output text or such o the device?

**Comment by BlueEssi** [comment]
At the moment unfortunately this isn't possible. I hope it will be possible soon.

**Comment by Apollon77** [comment]
verfügbar später heute in 2.4.1
