### ISSUE TITLE
Unknown device Echo Connect AKOAGQTKAS9YB

### ISSUE THREAD

**Issue by Wildbill-Z** [Apollon77/ioBroker.alexa2#192]
Folgendes taucht im Log auf, seit ich meinen Echo Connect in Betrieb habe:

alexa2.0     Device-type:AKOAGQTKAS9YB (VOLUME_SETTING,PEONY,BLOWER,DEREGISTER_DEVICE,PERSISTENT_CONNECTION,NO_UNITS_AND_TIMEZONES,SUPPORTS_SOFTWARE_VERSION,UPDATE_WIFI,CHANGE_NAME,MICROPHONE)

Gruss, Jürgen

**Comment by Apollon77** [comment]
Kann der Sprachausgaben?, denke eher nicht oder?
