### ISSUE TITLE
Homematic Access Point nimmt keine Werte entgegen

### ISSUE THREAD

**Issue by TobiasF1986** [Apollon77/ioBroker.alexa2#193]
[iobroker.2019-01-13.log](https://github.com/Apollon77/ioBroker.alexa2/files/2758641/iobroker.2019-01-13.log)

Seitdem letzte Woche bei Homematic Wartungsarbeiten stattgefunden haben (vielleicht hängt es damit zusammen), kann ich im ioBroker keine Temperaturwerte mehr via Alexa2 an den Access Point senden. Egal welche Werte ich eingebe, beim AP kommt davon nichts an.
Der Skill bei Amazon läuft scheinbar, denn meinen Echos kann ich SPrachbefehle geben und sie werden umgesetzt. Alle im Echo gesteruerten Lampen und Funksteckdosen klappen übrigens auch via ioBroker und Alexa2 Adapter, nur der Homematic Access Point nimmt nichts an.

- auf einem Raspberry läuft ioBroker in der aktuellen Version
- über den Alexa2 (2.0 und 1.1.3 ausprobiert) Adapter wird ein Homematic IP Access Point gesteuert
- Am Homematic AP läuft ein Heizkörperthermostat und ein Wandthermostat

**Comment by Apollon77** [comment]
Closed weil? Geht wieder?
