### ISSUE TITLE
Update States from Alexa Problem 

### ISSUE THREAD

**Issue by aschmidtlev** [Apollon77/ioBroker.alexa2#194]
Hi

Push Service doesn‘t work.Updated States from Alexa doesn’t take effect.. I can Control everything from Adapter to Alexa but if i change Power on it didn‘t Update in iobroker .

Regards Andy

**Comment by Apollon77** [comment]
yes, bevause you need to treigger "#query" to get new values. They are NOT propagated as push info from Amazon
