### ISSUE TITLE
Playerinfo

### ISSUE THREAD

**Issue by sigi2345** [Apollon77/ioBroker.alexa2#2]
Hallo, 
eine Playerinfo wäre Super:

Interpret
Titel
Senderinfo
Albuminfo
Albumbild
Playtime

`alexa.0	2018-07-12 10:10:29.338	debug	Alexa-Remote: Response: {"playerInfo":{"hint":null,"infoText":{"multiLineMode":false,"subText1":"Triggerfinger","subText2":"Ö3 Greatest Hits Vol.59 [Explicit]","title":"I Follow Rivers (Radio Mix)"},`

**Comment by sigi2345** [comment]
Upps es gibt ja schon so was ähnliches....bitte löschen.

**Comment by Apollon77** [comment]
Ne passt schon ... kannst Du mir mal genauer vorschlagen welche der Felder des Hauke-Skripts wirklich sinnvoll wären?!

**Comment by Pocky2507** [comment]
Ich hoffe, das es der richtige Code aus dem Hauke Skript ist.

/**
 * Ruft die aktuelle PlayerInfo eines Devices per Seriennummer und Type von Amazon ab.
 * Gibt die Antwort an "callback(result)" weiter
 *
 * @param string serialNumber
 * @param string deviceType
 * @param function callback
 */
function getDevicePlayerBySerialAndType(serialNumber, deviceType, callback) {
	httpsReqGet(
		'/api/np/player?deviceSerialNumber=' + serialNumber + '&deviceType=' + deviceType,
		function(result) {		
			// Es kommt vor, dass Geräte nicht antworten, weil sie nicht aktiv sind. Dann greift hier der Dummy-Wert
			if (result == '{"message":null}') {
				result =  JSON.stringify({
					"playerInfo":{
						"hint":null,
						"infoText":null,
						"isPlayingInLemur":false,
						"lemurVolume":null,
						"lyrics":null,
						"mainArt":null,
						"mediaId":null,
						"miniArt":null,
						"miniInfoText":null,
						"playbackSource":null,
						"playingInLemurId":null,
						"progress":null,
						"provider":null,
						"queueId":null,
						"state":null,
						"template":null,
						"transport":null,
						"volume":null
					}
				});
			}	
		
			if(callback !== undefined && typeof callback === 'function') callback(JSON.parse(result).playerInfo);
		}
	);
}

**Comment by Apollon77** [comment]
done in 0.2.0
