### ISSUE TITLE
Instance taucht nicht auf

### ISSUE THREAD

**Issue by Schrader1** [Apollon77/ioBroker.alexa2#201]
Guten Abend

zur Info ich bin "Neuling" in dieser Sache auch in Linux

Habe versucht ein update auf den neuen Alexa Adapter zu machen. Jedoch habe ich mir hier anscheinend irgendwas zerschossen.
Bei den Adaptern taucht er zwar auf als Installiert , jedoch nicht in den instancen und Objekte.
Ich habe den Raspberry komplett  was zum Updaten war geupdatet.

[log22.01.19.txt](https://github.com/Apollon77/ioBroker.alexa2/files/2784896/log22.01.19.txt)

Die vorige Version ist einwandfrei gelaufen.

Jedoch Ohne Erfolg

> host.All-In-One_RasPi	2019-01-22 23:30:13.118	info	Update repository "default" under "http://download.iobroker.net/sources-dist.json"
iobroker	2019-01-22 23:30:12.932	info	exit 0
iobroker	2019-01-22 23:30:12.839	info	upload [0] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/alexa.png alexa.png image/png
iobroker	2019-01-22 23:30:12.777	info	upload [1] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/echo.png icons/echo.png image/png
iobroker	2019-01-22 23:30:12.716	info	upload [2] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/echo2.png icons/echo2.png image/png
iobroker	2019-01-22 23:30:12.647	info	upload [3] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/echo_dot.png icons/echo_dot.png image/png
iobroker	2019-01-22 23:30:12.582	info	upload [4] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/echo_dot3.png icons/echo_dot3.png image/png
iobroker	2019-01-22 23:30:12.517	info	upload [5] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/echo_plus2.png icons/echo_plus2.png image/png
iobroker	2019-01-22 23:30:12.447	info	upload [6] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/echo_show.png icons/echo_show.png image/png
iobroker	2019-01-22 23:30:12.378	info	upload [7] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/echo_show2.png icons/echo_show2.png image/png
iobroker	2019-01-22 23:30:12.310	info	upload [8] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/echo_sub.png icons/echo_sub.png image/png
iobroker	2019-01-22 23:30:12.233	info	upload [9] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/firetab.png icons/firetab.png image/png
iobroker	2019-01-22 23:30:12.172	info	upload [10] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/firetv.png icons/firetv.png image/png
iobroker	2019-01-22 23:30:12.108	info	upload [11] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/multiroom.png icons/multiroom.png image/png
iobroker	2019-01-22 23:30:12.044	info	upload [12] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/raspi.png icons/raspi.png image/png
iobroker	2019-01-22 23:30:11.975	info	upload [13] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/reverb.png icons/reverb.png image/png
iobroker	2019-01-22 23:30:11.914	info	upload [14] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/sonos.png icons/sonos.png image/png
iobroker	2019-01-22 23:30:11.848	info	upload [15] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/spot.png icons/spot.png image/png
iobroker	2019-01-22 23:30:11.786	info	upload [16] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/index.html index.html text/html
iobroker	2019-01-22 23:30:11.720	info	upload [17] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/index_m.html index_m.html text/html
iobroker	2019-01-22 23:30:11.606	info	upload [18] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/words.js words.js application/javascript
iobroker	2019-01-22 23:30:11.578	info	got /opt/iobroker/node_modules/iobroker.alexa2/admin
iobroker	2019-01-22 23:30:11.463	info	
iobroker	2019-01-22 23:30:11.461	info	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
iobroker	2019-01-22 23:30:11.461	info	WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 (node_modules/authenticate-pam):npm WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 install: `node-gyp rebuild`
iobroker	2019-01-22 23:30:11.459	info	npm
iobroker	2019-01-22 23:30:04.552	info	gyp ERR! not ok
iobroker	2019-01-22 23:30:04.541	info	gyp ERR! node-gyp -v v3.8.0
iobroker	2019-01-22 23:30:04.541	info	/opt/iobroker/node_modules/authenticate-pamgyp ERR! node -v v8.15.0
iobroker	2019-01-22 23:30:04.539	info	gyp ERR! cwd
iobroker	2019-01-22 23:30:04.539	info	ERR! System Linux 4.14.79-v7+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
iobroker	2019-01-22 23:30:04.538	info	gyp
iobroker	2019-01-22 23:30:04.538	info	ERR! stack at ChildProcess.emit (events.js:214:7)gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
iobroker	2019-01-22 23:30:04.536	info	gyp
iobroker	2019-01-22 23:30:04.536	info	gyp ERR! stack at emitTwo (events.js:126:13)
iobroker	2019-01-22 23:30:04.536	info	gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
iobroker	2019-01-22 23:30:04.536	info	ERR! build error gyp ERR! stack Error: `make` failed with exit code: 2
iobroker	2019-01-22 23:30:04.532	info	gyp
iobroker	2019-01-22 23:30:04.528	info	make: *** [Release/obj.target/authenticate_pam/authenticate_pam.o] Fehler 1
iobroker	2019-01-22 23:30:04.490	info	compilation terminated.
iobroker	2019-01-22 23:30:04.489	info	^
iobroker	2019-01-22 23:30:04.489	info	../authenticate_pam.cc:30:31: fatal error: security/pam_appl.h: Datei oder Verzeichnis nicht gefunden #include <security/pam_appl.h>
cloud.0	2019-01-22 23:30:01.073	info	Connection changed: connect
cloud.0	2019-01-22 23:30:00.966	info	Trying to connect as system.user.admin
cloud.0	2019-01-22 23:29:00.948	info	Connection changed: io client disconnect
cloud.0	2019-01-22 23:29:00.946	info	Adapter redirected temporally to "https://iobroker.net:10560" in one minute. Reason: command from server
cloud.0	2019-01-22 23:29:00.852	info	Trying to connect as system.user.admin
iobroker	2019-01-22 23:28:45.787	info	npm install https://github.com/Apollon77/ioBroker.alexa2/tarball/master --production --save --prefix "/opt/iobroker" (System call)
hm-rega.0	2019-01-22 23:28:44.631	info	got state values
hm-rega.0	2019-01-22 23:28:44.282	info	request state values
hm-rega.0	2019-01-22 23:28:44.280	info	added/updated 2 objects
hm-rega.0	2019-01-22 23:28:44.140	info	deleted 0 variables
hm-rega.0	2019-01-22 23:28:44.139	info	added/updated 7 variables
iobroker	2019-01-22 23:28:44.111	info	install https://github.com/Apollon77/ioBroker.alexa2/tarball/master

>

**Comment by Apollon77** [comment]
Bei installs von GitHub muss die Instanz na url angelegt werden. Ein + unter Adapter genügt.
