### ISSUE TITLE
No actualisation of smart-home-devices states after sending voice command over Alexa

### ISSUE THREAD

**Issue by pfleiderer** [Apollon77/ioBroker.alexa2#203]
#First of all, big thanks for the great adapter (... and fo the Tuya adapter too)
Works great overall. I just have the problem, that if i send a command to alexa for my tuya - lights the state in the adapter don't changes automaticaly. It changes in the Alexa app and 8t changes in Tuya dapter, but not in the adapter here. 
I have decided to group my lights in Alexa, so i need this adapter to handle groups in VIS...
any help?

excample

i have two lamps Sofa1 ans Sofa2 grouped in Alexa to group Sofa.
If i change she tates of power, RGB and brightness a.s.o in the adapter, the corresponding lamps react emediatelay and the actual state was shown in adapter (objects).
But only the for the states i change in adapter not for the changes i made outside over speech or apps (Alexa or Tuya)

**Comment by Apollon77** [comment]
Yes, as designed, Amazon is not pushing state changes, so it is "polling" only. use the "#query" states to update values
