### ISSUE TITLE
alexa2 warning in log, no commands are working

### ISSUE THREAD

**Issue by overfl0w72** [Apollon77/ioBroker.alexa2#206]
Moin Apollon, hallo liebe Leser,

leider kann ich seit zwei Tagen keine Geräte mehr mit Alexa schalten. Ich habe heute den Cookie erneuert, da dieser scheinbar nicht mehr aktiv war. Nun bekomme ich folgende Warnung in der LOG:

`

alexa2.0 | 2019-01-31 17:34:51.552 | warn | Device-type:AKPGW064GI9HE (FLASH_BRIEFING,PERSISTENT_CONNECTION,CHANGE_NAME,VOLUME_SETTING,SUPPORTS_SOFTWARE_VERSION,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,ACTIVE_AFTER_FRO,ARTHUR_TARGET,MICROPHONE)
-- | -- | -- | --
alexa2.0 | 2019-01-31 17:34:51.551 | warn | Disabling some commands for device because of unknown type. Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted

`

Falls jemand eine Idee hat, danke im Voraus :)
Beste Grüße aus Hannover

**Comment by Apollon77** [comment]
Was ist das denn für ein Gerät?

**Comment by overfl0w72** [comment]
> Was ist das denn für ein Gerät?

Es ist ein ganz normaler Echo der 2. Generation. Bisher lief immer alles super, nur jetzt leider nicht mehr.
In Alexa sind alle Smarthome Geräte als Offline angezeigt. Der Adapter in ioBroker jedoch ist Grün und alle drei Felder sind "Verbunden"
