### ISSUE TITLE
2 Alexa Adapter in einer iobroker Instanz ?!

### ISSUE THREAD

**Issue by DocYester** [Apollon77/ioBroker.alexa2#207]
Sobald ich einen 2ten Alexa Adapter installiere und ihn mit einem anderen Amazon-Account konfiguriere , liefert er die selben Daten/Geräte/Datenpunkte wie der erste Account.
Ist das so gewollt oder kann man das ändern ?
Hier im Haushalt gibt es mehrere "Erwachsenen-Acconts" (4) die ich nicht alle über ein Haushaltsprofil verbunden bekomme, 2x2 würde gehen oder gar 1x2 und 2x1.

**Comment by Apollon77** [comment]
An sich sollte jeden instanz getrennt sein und das liefern was Amazon zurückgibt. Kannst beide mal auf debug setzen vom logging und schauen ob log anders ist

**Comment by DocYester** [comment]
Das Log ist nicht anders, er logt beide immer mit dem zuletzt verwendeten Account ein.
Ich habe gerade beide Adapter gelöscht und neue Instanzen erzeugt.
2ten Adapter mit 2ten Account eingerichtet und eingeloggt (inkl. Cookie) - richtige Daten des 2ten Accounts im 2ten Adapter.
Dann ersten Adapter mit erstem Account eingerichtet (inkl. Cookie) und siehe da er nutzt den Cookie des 2ten Adapters und nimmt nicht die login Daten.
Beim einrichten des 2ten Adapters hat er mich beim Cookie holen zur Amazon Seite geleitet und nochmal aufgefordert User/Pass einzugeben , beim ersten Adapter nicht !

Next Test - 2ter Adapter mit 2ten Account auf Pause gestellt.
Erster Adapter - Cookie und Passwort aus den Einstellungen gelöscht, gespeichert.
Erster Adapter neugestartet - im Log den Cookie geholt - keine Aufforderung zu Amazon , direkt Cookie vom 2ten (pausierten) Adapter bekommen und wieder die Daten vom 2ten Account im ersten Adapter.

Selbst wenn ich zwischen den Einrichtungen der beiden Adapter im Browser schaue ob noch eine ANmeldung an Amazon besteht und ich mich da auslogge , oder den für den nächsten Schritt richtigen Account einlogge , es bleibt das selbe Ergebnis , der zuerst eingerichtete Account wird vom 2ten Adapter aufgegriffen und übernommen.

**Comment by DocYester** [comment]
Selbst nach dem löschen beider Adapter , restart iobroker , neue Adapter-Instanz anlegen ist es egal was ich an LoginDaten im Adapter eingebe - ich bekomme immer den alten Cookie des 2ten Accounts und kann den ersten nicht mehr einstellen.

**Comment by DocYester** [comment]
Nachdem ich den Alexa Adapter einmal komplett entfernt habe (danach neu upload im iobroker), konnte ich den ersten Account wieder einloggen im ersten Account.
Der Versuch dann den 2ten Adapter mit dem 2ten Account anzumelden ging wieder in die Hose - Cookie vom ersten und der erste ist auch im 2ten Adapter

**Comment by Apollon77** [comment]
Aaaaahhhhh sag mal: geht das mit username und Passwort oder musst du dich per Proxy einloggen?

Wenn Proxy dann kann es sein das es so ist. Da müsstest du dich vorher bei Amazon ausloggen bevor du mit Proxy den zweiten einrichtest.

**Comment by DocYester** [comment]
Nachher mal ausprobieren mit verschiedenen browsern und cache löschen - ich hänge grad an einem kleinen Problem mit einem Lämpchen und einem esp8266ex ...

**Comment by Ralf-Niemeier** [comment]
Genau wie oben von  @Ilovegym66 beschrieben funktioniert es bei meinen zwei Amazon-Acconts ebenfalls.
Es ist definitiv möglich mehrer Accounts  zu steuern.

**Comment by DocYester** [comment]
Danke - das war das entscheidende - Cache leeren zwischen dem anlegen der Adapter
