### ISSUE TITLE
Alexa redet nicht auf Echo Plus

### ISSUE THREAD

**Issue by Pocky2507** [Apollon77/ioBroker.alexa2#208]

**Comment by Apollon77** [comment]
Do not disturb ist aus? Bei mir tut alles auf meinem plus. Sieht auch gut aus im log

**Comment by Pocky2507** [comment]
Das ist ein Echo Plus im Account von meinem Sohn.
Der ist über das Haushaltsprofil mit meinem Account verknüpft.
Ich kann über den Alexa Adapter auch so ziemlich alles machen.
Der Adapter erkennt ihn und liest ihn ein.
Musik steuern, History u.s.w.
Das was nicht geht ist alles was mit Stimme zu tun hat.
Wetter, singsong etc. und speak gehen nicht.

**Comment by Apollon77** [comment]
Ok dann brauche ich zusätzlich noch den debug log vom Adapterstart aus dem logfile von der Platte. Gern als PN im Forum

**Comment by Apollon77** [comment]
Bitte 2.3 von github testen und ggf mit debug log neu öffnen
