### ISSUE TITLE
I regularly need to retrieve the cookie again - why?

### ISSUE THREAD

**Issue by LuckyTGX** [Apollon77/ioBroker.alexa2#209]
Hi!

The adapter usually works like a charm, but from time to time it loses connection and the log shows me that I need to retrieve the cookie. I then simply go to the recommended address, http://local-iobroker-ip:52184/, the adapter reconnects and everything is fine again.

I am not sure why this is actually happening.
It is generally not a big deal to do that every 1-2 weeks, but maybe I'm doing something wrong or maybe there's a chance to prevent it from happening.

Thanks in advance for your advice.

Best regards,
Lucky

**Comment by Apollon77** [comment]
Use v2.x from GitHub and the problem is gone ... will become official soon. Also see dapterthread in Forum for 2.x
