### ISSUE TITLE
Volume Commands don't work, if Volume is not multiple of 10.

### ISSUE THREAD

**Issue by simone1999** [Apollon77/ioBroker.alexa2#214]
Hi, if anny of the Volume Points is set to a Number not divideable by 10, the Datapoint does not work. Also if i use the say Datapoint for my Sonos one the Volume rises to the SpeakVolume, but afterwards don't go back to normal Volume if previous Volume was not dividable by 10. I think this shoulb be a quite easy Fix, maybe just internally round every Volume Number to a Multiple of 10? Lots of thanks for this great Adapter by the way!

**Comment by Apollon77** [comment]
What you mean with "does not work"? Please provide debug log.
In my echo devices all values are accepted, but then "rounded to a multiple of 3" (roughly) and then such a value is returned. So it could be that it is device specific, so it will not be that easy to fix.

**Comment by simone1999** [comment]
Hi, thanks for your fast reply.
To be a bit more specific: it does not work when i use the speak Datapoint for my Sonos Ones (have Alexa integrated) while speaking the Volume should go up to the speakvolume (not sure if this is the exact name) and when finished with speaking go back to previouse volume. This works fine if the Volume is dividable by 10, but does not work with other Volumes. Sadly i can only report my logs on the next weekend, hope the more detailed explanation helps you a bit. Have a nice Week and thanks for the great Adapter!

**Comment by Apollon77** [comment]
I understand but as said. Normal echo devices works differently here. So for now i would close it and you simply use volume values dividable by 10 for your setup as needed. I hear it for the first time. And even if I try to detect it a next update by someone on amazon or Spotify side can break it.
