### ISSUE TITLE
Alexa Tap-Steuerung auf Echo-Geräten

### ISSUE THREAD

**Issue by w2kscout** [Apollon77/ioBroker.alexa2#215]
Hallo Apollo 77

Ich hoffe das ich hier richtig bin. Also es geht um folgendes. Ich habe an meinem Haus Arlo Kameras. Wenn ich auf dem Show sie sehen möchte, dann muss ich sagen Alexa zeige mir Garagen Kamera. Ich würde aber gerne es so haben wenn eine Bewegung erkannt wird, dann soll er mir sofort das Bild starten. Nun habe ich mir im Show die Barrierefreiheit bei Alexa eingeschaltet (Alexa Tap-Steuerung auf Echo-Geräten mit Bildschirm verwenden) Nun habe ich die Möglichkeit die Befehle (Alexa zeige mir Garagen Kamera) als Taster zu generieren und mit einem Druck auf dem Show funktioniert das auch. Kannst du die Commands in deinen Skill so erweitern das man auch die Commands sehen kann? Sorry aber anders kann ich es nicht beschreiben. MFG Michael

**Comment by Apollon77** [comment]
Nein kann ich nicht weil ich denke das diese Aktionen lokal ausgeführt werden auf dem gerät und nicht per API verfügbar sind. bzw um Gewissheit zu haben müsste ich so ein Szenario nachstellen können bei mir ... aber auch dann denke ich nicht das das so ist

**Comment by w2kscout** [comment]
Trotzdem Danke!

 

Ach noch was Respekt was du hier machst. Würde gern mal wissen wie du sowas erstellst!

 

MFG Michael

 

Gesendet: Montag, 25. Februar 2019 um 13:16 Uhr
Von: "Ingo Fischer" <notifications@github.com>
An: "Apollon77/ioBroker.alexa2" <ioBroker.alexa2@noreply.github.com>
Cc: w2kscout <nirvana12@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [Apollon77/ioBroker.alexa2] Alexa Tap-Steuerung auf Echo-Geräten (#215)


Nein kann ich nicht weil ich denke das diese Aktionen lokal ausgeführt werden auf dem gerät und nicht per API verfügbar sind. bzw um Gewissheit zu haben müsste ich so ein Szenario nachstellen können bei mir ... aber auch dann denke ich nicht das das so ist
