### ISSUE TITLE
Echo Input wird nicht richtig erkannt! 

### ISSUE THREAD

**Issue by MyzerAT** [Apollon77/ioBroker.alexa2#218]
Im iobroker wird der Echo Input unter Objkte/Alexa2.0/Echo-Devices zwar erkannt aber es fehlen Datenpunkte wie zb. Commands oder Routnies  

![grafik](https://user-images.githubusercontent.com/47501072/53694633-d7c49080-3db1-11e9-8ec3-de03536d489a.png)

![](https://forum.iobroker.net/assets/uploads/files/1551610937992-bbc2c14e-0634-4be5-a6f4-4d610c8e4352-grafik.png)

**Comment by Apollon77** [comment]
Kann der Echo Input denn irgendwas? Kommandos wie Sprachausgaben? Routinen? KannST Du in der Alexa App bei Routinen mit Ausgaben den Echo Input als Ziel wählen?

**Comment by MyzerAT** [comment]
ja er kann Routinen die ich ihm per Handyapp auch zuweisen kann und ja die Sprachausgabe geht über die HiFi Anlage wo er per Sterominiklinke hängt , also Aux . 
[
Link zum FRED ins Forum: ](https://forum.iobroker.net/topic/20503/echo-input-kein-ordner-commands) 

deviceType: A1JJ0KFC4ZPNJ3

capabilities:ACTIVE_AFTER_FRO,TIMERS_AND_ALARMS,SET_LOCALE,TAHOE_BYOD,AUDIBLE,FLASH_BRIEFING,I_HEART_RADIO,GOLDFISH,DREAM_TRAINING,KINDLE_BOOKS,REMINDERS,GADGETS,ALLOW_LOG_UPLOAD,SOUND_SETTINGS,FAR_FIELD_WAKE_WORD,PAIR_BT_SINK,DEREGISTER_DEVICE,AMAZON_MUSIC,LEMUR_ALPHA,VOICE_TRAINING,MICROPHONE,CHANGE_NAME,SUPPORTS_SOFTWARE_VERSION,SALMON,PAIR_BT_SOURCE,CUSTOM_ALARM_TONE,SLEEP,PANDORA,AUDIO_PLAYER,ASCENDING_ALARM_VOLUME,DS_VOLUME_SETTING,POPTART,PERSISTENT_CONNECTION,REQUIRES_OOBE_FOR_SETUP,VOLUME_SETTING,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,MUSIC_SKILL,UPDATE_WIFI,EARCONS,TUNE_IN,SUPPORT_CALENDAR_ALERT

**Comment by beankeeper** [comment]
Same problem, only Info in iobroker, no Commands..., please help! thx

**Comment by smotomike** [comment]
Hi, i have the same Problem, too. 
By the Way, great Work. :-)

**Comment by ideenOG** [comment]
Ich habe den Input seit heute und vermisse die Funktionen schmerzlich.

Der Adapter ist TOP, grosses LOB !!

**Comment by altskavaek** [comment]
I am missing the echo input support as well.

**Comment by ozboss** [comment]
Bluetooth fehlt auch

**Comment by Apollon77** [comment]
will be in 2.3.2 soon later today on Github
