### ISSUE TITLE
alexa2.0.History.name springt wie ein flummi

### ISSUE THREAD

**Issue by nob0dy80** [Apollon77/ioBroker.alexa2#219]
Hallo,
ich habe ein kleines javascript  geschrieben welches die messwerte an jener alexa ausgibt von der auch angefragt wurde.
Man sieht auch wie das Object alexa2.0.History.name auf den richtigen raum springt, danach sich aber entschließt auf irgendeinen anderen umzuschalten (wir haben 4 alexas).

Das Javascript ist so simpel das ich da eigentlich keinen Fehler vermute, aber für den Fall der Fälle sieht es so aus:
var RAUMNAME='Kinderzimmer'
var TEMP1 = getState('netatmo.0.Micha.Kinderzimmer.Temperature.Temperature').val;
var CO1 = getState('netatmo.0.Micha.Kinderzimmer.CO2.CO2').val;
var HUMIDITY1 = getState('netatmo.0.Micha.Kinderzimmer.Humidity.Humidity').val
var LASTALEXA = 'alexa2.0.Echo-Devices.'+getState('alexa2.0.History.serialNumber').val+'.Commands.speak'

if (CO1>1000){
setState(LASTALEXA, '40;Die Temperatur beträgt ' + TEMP1 + ' Grad. Die Luftfeuchtigkeit beträgt ' + HUMIDITY1 + ' Prozent. Das Zimmer sollte gelüftet werden.' ),5000;
             }

else {
setState(LASTALEXA, '40;Die Temperatur beträgt ' + TEMP1 + ' Grad. Die Luftfeuchtigkeit beträgt ' + HUMIDITY1 + ' Prozent. Das Zimmer muss nicht gelüftet werden.' ),5000;
     }
stopScript();`

Kann da jemand helfen? 

PS: Manchmal funktioniert es auch richtig, habe da noch kein Muster erkennen können.
Das Script wird auf jeden Fall über Alexa getriggert, so dass LASTALEXA eigentlich das richtige value zurückliefern müsste. Ich verstehe einfach nicht warum es hin und herspringt.
5 Mal den Befehl im Wohnzimmer per Alexa getriggert wurde ausgegeben in: Badezimmer, Badezimmer, Küche, Badezimmer, Küche.. 
Das soll mir mal einer erklären, der mehr Ahnung vom Programmieren hat als ich :-D

**Comment by Apollon77** [comment]
Ok, kann es sein das mehrere Alexas eine Anfrage hören dann aber ggf verwerfen? Das würde diesen Effekt erklären. ANsonsten müste man sich im Log (Debug) genau ansehen was passiert.

So oder so eine Frage: WIe genau funktioniert dieses Skript? Ich sehe kein Subscribe auf einen Datenpunkt? Sag jetzt bitte nicht das das Skript über scriptsEnabled getriggert wird, das wäre nämlich komplett falsch und erklärt vieles mehr.

Am besten Bitte im iobroker Forum fragen mit exakten Details, da sehen wir gern weiter
