### ISSUE TITLE
New device - Anker Zolo Halo

### ISSUE THREAD

**Issue by TheGulOfDedra** [Apollon77/ioBroker.alexa2#220]
Hi, new device not having Command section. Is that the info you need?

Disabling some commands for device because of unknown type. Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted

Device-type:A1P31Q3MOWSHOD (PEONY,PERSISTENT_CONNECTION,AMAZON_MUSIC,TUNE_IN,MICROPHONE,DREAM_TRAINING,DEREGISTER_DEVICE,KINDLE_BOOKS,MUSIC_SKILL,REMINDERS,AUDIO_PLAYER,GOLDFISH,TIMERS_AND_ALARMS,

Thanks,
Markus

**Comment by TheGulOfDedra** [comment]
Ich denke es wird nicht gehen - habe gerade mal eine Routine probiert und wollte das Gerät als Ziel auswählen - wenn es dort nicht erscheint, dann geht es nicht, oder?

**Comment by WilliamTRiker57** [comment]
Ich habe auch diese Fehlermeldungen, bei den Geräten, die diesen Fehler verursachen handelt es sich um folgende:
AP1F6KUH00XPV -- Stereo-Subwooferpaar
AKPGW064GI9HE -- Firestick 4K
AKOAGQTKAS9YB -- Echo Connect

und bei allen Geräten bzw. Gruppen steht im DeviceTypString Unknown.

Gruß
Uwe

**Comment by Apollon77** [comment]
Dann bitte jeweils noch dioe "capabilities" nennen. Danke

**Comment by adx-git** [comment]
Device-type:AKPGW064GI9HE (ARTHUR_TARGET,PERSISTENT_CONNECTION,VOLUME_SETTING,MICROPHONE,ACTIVE_AFTER_FRO,CHANGE_NAME,FLASH_BRIEFING,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,SUPPORTS_SOFTWARE_VERSION)

**Comment by Apollon77** [comment]
@WilliamTRiker57  Bitte neue einzelne Issues öffnen mit den Capabilities.
@TheGulOfDedra ist in 2.4.1 drin,
