### ISSUE TITLE
uncaught exception: Cannot read property 'namespace' of undefined

### ISSUE THREAD

**Issue by murreni** [Apollon77/ioBroker.alexa2#222]
is anybody able to tell me whats wrong?
![unbenannt](https://user-images.githubusercontent.com/14903548/53957264-3190c780-40de-11e9-950b-bd9d640917b7.png)

**Comment by obodeldog** [comment]
I have the same problem. Is there a solution?

**Comment by Apollon77** [comment]
Which js-Controller Version?

**Comment by obodeldog** [comment]
1.5.7

**Comment by Apollon77** [comment]
Then your error message is different, Please post @obodeldog If also adapter.sj line 5609 then it is js.controller 2.0 some version and then please update from GitHub (why every someone have this version beside developers!! @murreni )

**Comment by obodeldog** [comment]
Ok, this is my error message :-)
![image](https://user-images.githubusercontent.com/35403739/56426370-689af100-62b8-11e9-9cf1-e057f85c7adb.png)

**Comment by Apollon77** [comment]
Ok, this is something different and would be worth an own issue. Will check. Please reinstall fresh from GitHub and restart just that I know that it is really happening in latest GitHub version.

**Comment by obodeldog** [comment]
Unfortunately the same mistake. Thanks.

**Comment by Apollon77** [comment]
Ok, did it ever work? Can you please post The content of the instance object?
Objects -> Expert mode -> no filter, also not in "type" column -> system.adapter.alexa2.0 -> pencil icon -> "Raw Expots only" and post the JSON you see there please. Thank you.
After this please try to remove the instance and create a new one. Do it work then after a first login?

**Comment by obodeldog** [comment]
Hi!
Sorry for delay. I was on vacation.


`{
  "_id": "system.adapter.alexa2.0",
  "type": "instance",
  "common": {
    "name": "alexa2",
    "version": "1.1.3",
    "title": "Alexa2 (Amazon Echo)",
    "desc": "Remote control for Alexa (Amazon Echo)",
    "platform": "Javascript/Node.js",
    "news": {
      "1.1.0": {
        "en": "Bespoken, fixes, optimizations and enhanced smart home devices and group management and control",
        "de": "Bespoken, Fixes, Optimierungen und erweiterte Smart-Home-Geräte und Gruppenmanagement und -steuerung",
        "ru": "Bespoken, исправления, оптимизации и расширенные интеллектуальные домашние устройства, а также управление и контроль групп",
        "pt": "Bespoken, correções, otimizações e dispositivos domésticos inteligentes aprimorados e gerenciamento e controle de grupo",
        "nl": "Bespoken, fixes, optimalisaties en verbeterde smart home-apparaten en groepsbeheer en -controle",
        "fr": "Bespoken, des correctifs, des optimisations et des dispositifs améliorés pour la maison intelligente, ainsi que la gestion et le contrôle des groupes",
        "it": "Bespoken, correzioni, ottimizzazioni e dispositivi smart home avanzati e gestione e controllo di gruppo",
        "es": "Bespoken, arreglos, optimizaciones y dispositivos mejorados para hogares inteligentes y administración y control grupal",
        "pl": "Bespoken, poprawki, optymalizacje i ulepszone inteligentne urządzenia domowe oraz zarządzanie grupą i sterowanie"
      },
      "0.5.2": {
        "en": "fixes, changes, optimizations, add support for reminders and alarms",
        "de": "behebt, ändert, optimiert, fügt Unterstützung für Erinnerungen und Alarme hinzu",
        "ru": "исправления, изменения, оптимизации, добавить поддержку напоминаний и аварийных сигналов",
        "pt": "correções, alterações, otimizações, adicionar suporte para lembretes e alarmes",
        "nl": "fixes, wijzigingen, optimalisaties, ondersteuning toevoegen voor herinneringen en alarmen",
        "fr": "corrections, modifications, optimisations, ajout de la prise en charge des rappels et des alarmes",
        "it": "correzioni, modifiche, ottimizzazioni, aggiungere supporto per promemoria e allarmi",
        "es": "arreglos, cambios, optimizaciones, agregar soporte para recordatorios y alarmas",
        "pl": "poprawki, zmiany, optymalizacje, dodawanie obsługi przypomnień i alarmów"
      },
      "0.4.0": {
        "en": "fixes, changes, introduce push connection to update data in realtime",
        "de": "behebt, ändert, führt eine Push-Verbindung ein, um Daten in Echtzeit zu aktualisieren",
        "ru": "исправления, изменения, внедрение push-соединения для обновления данных в реальном времени",
        "pt": "correções, mudanças, introduza conexão push para atualizar dados em tempo real",
        "nl": "reparaties, wijzigingen, introduceren push-verbinding om gegevens in realtime bij te werken",
        "fr": "corrections, modifications, introduction de la connexion push pour mettre à jour les données en temps réel",
        "it": "correzioni, modifiche, introdurre la connessione push per aggiornare i dati in tempo reale",
        "es": "arregla, cambia, introduce una conexión de inserción para actualizar datos en tiempo real",
        "pl": "poprawki, zmiany, wprowadzenie połączenia push do aktualizacji danych w czasie rzeczywistym"
      },
      "0.3.8": {
        "en": "fixes problems for multi room again",
        "de": "behebt Probleme für mehrere Räume",
        "ru": "исправляет проблемы для многокомнатной комнаты снова",
        "pt": "corrige problemas para multi sala novamente",
        "nl": "lost problemen voor multi-kamer opnieuw op",
        "fr": "résout des problèmes pour plusieurs pièces",
        "it": "risolve di nuovo i problemi per la multi stanza",
        "es": "arregla problemas para multihabitación de nuevo",
        "pl": "naprawia problemy z multi roomem"
      },
      "0.3.4": {
        "en": "fixes for routines and multi room commands and music-providers",
        "de": "Fixes für Routinen und Multiroom-Befehle und Musik-Provider",
        "ru": "исправления для подпрограмм и команд с несколькими комнатами и музыкальных провайдеров",
        "pt": "correções para rotinas e comandos de sala múltipla e provedores de música",
        "nl": "fixes voor routines en multi-room-commando's en muziek-providers",
        "fr": "correctifs pour les routines et les commandes multi-pièces et les fournisseurs de musique",
        "it": "correzioni per routine e comandi multi-room e fornitori di musica",
        "es": "arreglos para rutinas y comandos multi room y proveedores de música",
        "pl": "poprawki dla rutyn i poleceń multi-room oraz dostawców muzyki"
      },
      "0.3.2": {
        "en": "fixes, changes und settings window materialized fixes",
        "de": "Fehlerbehebungen, Änderungen und Einstellungsfenster im Material Design Fehler behoben"
      },
      "0.2.4": {
        "en": "fixes, changes und settings window materialized",
        "de": "Fehlerbehebungen, Änderungen  und Einstellungsfenster im Material Design"
      },
      "0.2.1": {
        "en": "first release as Alexa2",
        "de": "Erste Veröffentlichung als Alexa2"
      },
      "1.1.2": {
        "en": "Alexa Proxy problems fixed and some new devices added",
        "de": "Alexa Proxy Probleme behoben und einige neue Geräte hinzugefügt",
        "ru": "Проблемы с Alexa Proxy исправлены и добавлены новые устройства",
        "pt": "Problemas de Alexa Proxy corrigidos e alguns novos dispositivos adicionados",
        "nl": "Alexa Proxy-problemen opgelost en een aantal nieuwe apparaten toegevoegd",
        "fr": "Problèmes Alexa Proxy résolus et ajout de nouveaux appareils",
        "it": "Problemi di Alexa Proxy risolti e alcuni nuovi dispositivi aggiunti",
        "es": "Se solucionaron los problemas de Alexa Proxy y se agregaron algunos dispositivos nuevos.",
        "pl": "Naprawiono problemy z serwerem Alexa Proxy i dodano nowe urządzenia"
      },
      "1.1.1": {
        "en": "Alexa Proxy problems fixed and some new devices added",
        "de": "Alexa Proxy Probleme behoben und einige neue Geräte hinzugefügt",
        "ru": "Проблемы с Alexa Proxy исправлены и добавлены новые устройства",
        "pt": "Problemas de Alexa Proxy corrigidos e alguns novos dispositivos adicionados",
        "nl": "Alexa Proxy-problemen opgelost en een aantal nieuwe apparaten toegevoegd",
        "fr": "Problèmes Alexa Proxy résolus et ajout de nouveaux appareils",
        "it": "Problemi di Alexa Proxy risolti e alcuni nuovi dispositivi aggiunti",
        "es": "Se solucionaron los problemas de Alexa Proxy y se agregaron algunos dispositivos nuevos.",
        "pl": "Naprawiono problemy z serwerem Alexa Proxy i dodano nowe urządzenia"
      },
      "1.1.3": {
        "en": "cookie handling optimized and errors fixed",
        "de": "Cookie-Handling optimiert und Fehler behoben",
        "ru": "оптимизирована обработка файлов cookie и исправлены ошибки",
        "pt": "manipulação de cookies otimizada e erros corrigidos",
        "nl": "geoptimaliseerde cookieverwerking en fouten opgelost",
        "fr": "gestion des cookies optimisée et correction des erreurs",
        "it": "gestione dei cookie ottimizzata e correzione degli errori",
        "es": "Manejo optimizado de cookies y corrección de errores.",
        "pl": "obsługa plików cookie zoptymalizowana i naprawione błędy"
      },
      "2.1.0": {
        "en": "new commands including ssml speak added, routine triggering fixed and cookie handling  implemented completely new",
        "de": "Neue Befehle einschließlich ssml-Sprache hinzugefügt, Routine-Auslösung behoben und Cookie-Behandlung komplett neu implementiert",
        "ru": "добавлены новые команды, включая ssml Speech, исправлена ​​рутинная активация и реализована обработка файлов cookie.",
        "pt": "novos comandos incluindo ssml speak added, rotina de triggering fixo e manipulação de cookies implementada completamente nova",
        "nl": "nieuwe commando's inclusief ssml speak added, routine triggering fixed en cookie handling volledig nieuw geïmplementeerd",
        "fr": "nouvelles commandes, y compris ssml parlent ajoutées, déclenchement de la routine corrigé et gestion des cookies totalement nouvelle",
        "it": "nuovi comandi incluso ssml speak aggiunto, trigger di routine fisso e gestione dei cookie implementata completamente nuova",
        "es": "Se agregaron nuevos comandos, incluyendo ssml speak, rutinas de activación de rutina y manejo de cookies implementado completamente nuevo",
        "pl": "nowe polecenia, w tym ssml speak added, rutynowe wyzwalanie napraw i obsługa plików cookie całkowicie nowe",
        "zh-cn": "新命令包括添加ssml，固定常规触发和全新实现的cookie处理"
      }
    },
    "keywords": [
      "alexa",
      "amazon",
      "amazon echo",
      "echo dot",
      "echo show"
    ],
    "mode": "daemon",
    "icon": "alexa.png",
    "materialize": true,
    "extIcon": "https://raw.githubusercontent.com/Apollon77/ioBroker.alexa2/master/admin/alexa.png",
    "readme": "https://github.com/Apollon77/ioBroker.alexa2/blob/master/README.md",
    "loglevel": "info",
    "type": "iot-systems",
    "enabled": true,
    "messagebox": true,
    "license": "MIT",
    "installedVersion": "1.1.3",
    "host": "NUC-VISU-PRIVAT-i3",
    "authors": [
      "Apollon77 <iobroker@fischer-ka.de>"
    ],
    "restartSchedule": ""
  },
  "native": {
    "cookie": "session-id=259-8652511-2252827; session-id-time=2184175217l; ubid-acbde=262-0028219-6772538; csrf=1899388999; io=u3tsf8hQb48-6crOAAAI; csm-hit=tb:G4D9RV6WY8E1BZTGB6AY+s-G4D9RV6WY8E1BZTGB6AY|1554720616257&t:1554720616257&adb:adblk_no; session-token=\"kEed6yAz7iqCFQMXUIWJMsXOVT3D+16JLyMNVf1AtMVcT0h0otFFE9D+woBowPl6gVMywZKtc6/EgCJJFjDx+Cb4xlIY1cVjuJ5AbHKhxQvBQL3vTCkAoKyFiB5k0fBBPo8kbuPcnv1o2K2N22zwQzHkUnN7JXUkymha0lIZxRd8uQUbOsHyDS75TtPhEcN7+J/Hg2/H9NKYrYOC+dQj/bIdhe2c0MoR8DBecXoK42Y=\"; x-acbde=\"?PXCFh8x@xgBXkGrhi9KrCJKXaH@LP96\"; at-acbde=Atza|IwEBIC88wjaAMYUJV1T3lLN9AM_2kInJDdUbQdjtoy8xZP5lRgHVP1J-97Z_6R5Hhr6QEdq0Q3bTpezod5ZXXjG_Sz-jONWkue9VZNGLvwU4nLh6-yVa4xATzJiHEhXeWBEWDnM8_YhkM0bcp-IkuhpNOVpEXwkZCKgb4yUavQX9K6YIi5SZLmBIzQZY4uGRKoEAIuQT0P02V5exq08E52CSp8zy8wyrSl0SiLvk99i_aUbDVbeNP8YzL5cEZKBrv91cF9LeMJduahTtjXkt0oc9_bs-rx3BK-EXvRGlvLX5pODpxO7w2DvrrrEvbxScbk4mZmdyrNwjsiXKSMNYBY6wmYlt96LOloGJ1FTI6qLkBeLvQPPjNGtQvv6DXWb_6wpD4dBvreydGqxjnONo2VYfnWlX; sess-at-acbde=\"yFLTVHfG6Dt8VoiLaj4EYccACf7Zc+TU8zsed8/XARg=\"; sst-acbde=Sst1|PQFjBLLB-SdhQir6D5Az1hdiC0D0wlbvr4b2QIf4lz_ibtSb3qdqCZY4RNr3Fm-EL8hfHAUJ9_009N1PlYlZH44xybOBSR8PSYa185Ih4glv8A4wUXcMsnnKZoVv1hZDQKAVKpNsOeFhI2qpCjB2nx5a7C--3-Df4-UgpiwVxeomuPF5T3rwyuOfK3bRVGJa7In7taZsmhUhXUbWPY2QViXM3FrHjxygE3Ac_JdGkLniGT_cGsdOqZX6gTTeNupxHMcSzmu9y0_7AybC8r53cGrfb-nhQSy8GdMLQTj-UIVN8Yxcmb3xMZWHVqLfwaBCO0AxB080C2CGSiQWNbpFQXlUXw",
    "csrf": "1899388999",
    "alexaServiceHost": "",
    "email": "\t^P\u0001\u0002%_XJH\\\u0004",
    "password": "EY\u0000BY\u0004\t\u0004\u0000",
    "userAgent": "",
    "acceptLanguage": "",
    "cookieLoginUrl": "",
    "proxyOwnIp": "10.1.10.160",
    "proxyPort": 0,
    "proxyListenBind": "0.0.0.0",
    "updateStateInterval": 300,
    "updateHistoryInterval": 300,
    "usePushConnection": true,
    "bespokenToken": "",
    "bespokenVoiceId": "Hans",
    "bespokenLocale": "de-DE",
    "cookieData": {}
  },
  "from": "system.adapter.admin.0",
  "ts": 1556212450084,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "user": "system.user.admin",
  "enums": {}
}`

**Comment by Apollon77** [comment]
The object data is from v1.1.3. Please install again fresh from GitHub, execute a "iobroker upload alexa2" and try again please

**Comment by obodeldog** [comment]
Yes, I saw. After deinstallation it works.
