### ISSUE TITLE
Sporadisch keine Reaktion bei Wiedegabe von Tunein Sendern.

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#223]
https://forum.iobroker.net/topic/17158/iobroker-alexa2-v2-0-alpha-status-github-version/323

**Comment by Apollon77** [comment]
Hast DU hier ein Update? Besteht dasd Problem noch?

**Comment by Matten-Matten** [comment]
ich meine das hat sich erledigt. mache erst einmal zu. falls es doch noch kommt melde ich mich.
