### ISSUE TITLE
Alexa Push Connection not working

### ISSUE THREAD

**Issue by Gieskanne** [Apollon77/ioBroker.alexa2#224]
Bei mir taucht im log alle 30 Sekunden die Meldung "Alexa-Push-Connection disconnected - retry: Retry Connection in NaNs" auf. Ist schon so, solange ich den alexa2-Adapter instanziiert habe. Bis auf die Push-Funktionen funktioniert im Adapter alles normal. Aber als ich nun mal den debug-Modus für den Adapter eingeschaltet habe, ist mir erst aufgefallen, was da alle 30 Sekunden passiert. Nun würde ich gerne die Push-Verbindung nutzen, da mir das Pulling zu langsam ist.

Im Anhang ein Ausschnitt aus dem log nach einem sauberen Start vom Adapter (info-Ausgaben und bei "Alexa-Remote WS-MQTT" dann auch die debug-Ausgaben mit Schwärzung in Form von XXXX):
<gelöscht>

Bei den Zeiten nicht so genau hinschauen. Die debug-Ausgaben sind aus einem vorherigen run. (Die Reihenfolge stimmt so.)

Was das mit dem Skill-Fehler auf sich hat, weiß ich nicht. Ich hatte mal den Sonos-Skill aktiviert, diesen aber schon lange wieder deaktiviert und deinstalliert.

**Comment by Apollon77** [comment]
Bitte 2.x vom GitHub nehmen. Da auch defekt?

**Comment by Gieskanne** [comment]
Danke, mit der aktuellen GitHub-Version läufts! Issue kann geschlossen werden.
Wann gibt es ein Release?

**Comment by Gieskanne** [comment]
Läuft mit aktueller GitHub-Version!

**Comment by Apollon77** [comment]
Dann bitte Cookie neu holen. Wenn möglich Instanz löschen und neu anlegen. Alternativ Cookie Daten im Objekt System.adapter.alexa2.0 unter Objekte im expertenmodus rauslöschen.

**Comment by Farmer-cb** [comment]
wird aktuel [hier](https://github.com/Apollon77/ioBroker.alexa2/issues/750) behandelt.

**Comment by Apollon77** [comment]
@LePremier Replying on an 20 month (!!) old issue is normally not really helpful
