### ISSUE TITLE
Feature request: Timer Object

### ISSUE THREAD

**Issue by Gieskanne** [Apollon77/ioBroker.alexa2#226]
Sobald mit Alexa ein Timer gestartet wird, wäre es klasse, wenn in dem Moment ein Objekt mit der verbleibenden Zeit gesetzt wird. Ich habe das wie folgt in der main.js gelöst (nach der bereits vorhandenen debug-Ausgabe in Zeile 1766):

`adapter.log.debug(noti.type + ' ' + noti.id + ' triggered in ' + Math.floor(noti.remainingTime / 1000) + 's');`
`setOrUpdateObject(devId + '.Timer.lastTimerRemainingTime', {common: {type: 'integer', role: 'state', name: 'Remaining time of last timer'}}, Math.floor(noti.remainingTime / 1000), noti.set);`

Funktioniert für mich wunderbar. Vielleicht findet ihr die Idee gut und wir könnten sie professionell für alle umsetzen.

**Comment by Apollon77** [comment]
Bisher habe ich das absichtlich nicht gemacht weil der nutzen fraglich ist. Die timer-ids sind kryptisch und sehr dynamisch. Die Objekte eher kurzlebig. Man kann also Skript technisch nichts sinnvolles damit anfangen (oder was machst du damit exakt?
Am Ende muss man die ganzen Objekte auch wieder aufräumen und löschen sonst müllt man die Objekte zu. 

Daher war der zwischenwarf beim Ablauf eines Timers das generelle Timer Objekt zu triggern das man weiß das ein timer abgelaufen ist.

**Comment by Gieskanne** [comment]
Ich habe eine Uhr gebaut, die mit angesagtem Alexa Timer mitläuft. So habe ich immer im Blick wieviel Zeit noch bleibt (klar kann ich Alexa auch fragen, aber ein Blick auf die Uhr zum Beispiel beim Kochen ist bequemer). Amazon hat mit der "Echo Wall Clock" ähnliches vor, diese gibt es jedoch bisher nur auf dem amerikanischen Markt und hatte zwischenzeitlich auch technische Probleme. Meine läuft ohne Probleme und vergisst auch nicht die Zeit. ;-)

Ich brauche also einfach nur einen Zustand (pro Device), der mit der Timerzeit beim Starten des Timers einmalig gesetzt wird. So, wie in obiger Lösung beschrieben. Ich weiß auch von anderen Bastlern, die z.B. die Summary aus deinem Adapter parsen und daraus die angesagte Zeit extrahieren (z.B. total verrückt und mit Blockly: https://www.elzershark.com/forum/index.php?thread/10-nachbau-der-amazon-echo-wall-clock/ ).

Nebenbei, weißt du warum es 3 Sekunden dauert, vom Setzen des Timers bis der State im ioBroker ankommt? Zeit ist synchron, wird ja im Code durch delay berücksichtigt, das ist also kein Problem. Frage mich nur wo die 3 Sekunden drauf gehen.

**Comment by Apollon77** [comment]
Und was machst du bei mehreren laufenden timern? Nur der letzte wird angezeigt?

3s kommen daher denke das Nach setzen des Timers diese info per Push Info kommt und der Adapter dann die timer abfragt und aktualisiert. Das kostet halt alles Zeit.

**Comment by Gieskanne** [comment]
Meine (analoge) Uhr kann nur einen Timer anzeigen. Habe das noch nicht implementiert, würde aber einfach immer den Timer anzeigen, der als nächstes abläuft. Der alexa-Adapter braucht dafür meinetwegen keine weitere Logik, Ich würde das dann als Skript im iobroker implementieren, oder sogar direkt in der Uhr (ESP8266).

Auf jeden Fall vielen Dank für die viele Arbeit, die du in die verschiedenen Projekte steckst. Ich bin sehr zufrieden mit dem alexa-Adapter und kann ja Anpassungen nach meinem Geschmack vornehmen. Ich dachte nur, vielleicht ist das Feature auch etwas für andere Anwender.

**Comment by Apollon77** [comment]
Die Idee ist gut ... I will see

**Comment by Speedbreaker12** [comment]
Erstmal vielen Dank für den Adapter auch von mir. Ohne deine super Arbeit, könnte ich wahrscheinlich kaum eins meiner Projekte umsetzen! Ich stehe aber gerade vor dem selben Problem, ich habe mir auch eine Uhr mit ESP8266 gebaut und würde gerne Alexa Timer anzeigen könne. Würde es nicht script-technisch Sinn machen, die Timer unter History zu packen? Und dann vielleicht einfach als Werteliste, in EINEM Datenpunkt in der Art: Echo_Wohnzimmer;00:16:00;Echo_Schlafzimmer;00:05:00. So wäre es super einfach per skript oder blockly auszuwerten und das aufräumen wäre auch kein Problem.

**Comment by EddyDsSmartHome** [comment]
Hätte auch Interesse dran :) Oder kann man das irgendwie anders in die Vis einbinden? Also den aktuellen Timer?

**Comment by Gieskanne** [comment]
Falls gewünscht, kann ich die Änderungen an diesem Adapter vornehmen und dann Apollon77 als change request vorschlagen.

**Comment by Apollon77** [comment]
Bitte 3.1.0 vom GitHub mal testen

**Comment by Apollon77** [comment]
Ich habe nochmal nachgedacht: ist es nicht besser die Endzeit als "Date" anzugeben anstelle einer "Restlaufzeit" die man nur bewerten kann wenn man weiss wann Sie gesetzt wurde?

Schnelles Feedback bitte!

**Comment by Gieskanne** [comment]
Ja das stimmt! Vielleicht sind auch beide Ansätze nebeneinander berechtigt. Die Restlaufzeit bekommt ja auch schon automatisch das Datum (Zeitstempel) in ioBroker wann sie gesetzt wurde.

**Comment by Apollon77** [comment]
Ok, dann baue ich vor dem 3.1.0er Release auf ein Date um ... Das mit dem zeitstempel ist wahr aber denke sehr "un-intuitiv" :-)

**Comment by Apollon77** [comment]
Ok, 3.1.1 auf GitHub. Objekt heisst jetzt Device.Timer.nextTimerDate und enthält das Enddatum des als nächsten ablaufenden Timers. Macht sinn?
Davor war es übrigens auch kaputt ... er hat bei mehreren Timern nacheinander alle werte gesetzt. War strange

**Comment by Apollon77** [comment]
Opinions??

**Comment by Gieskanne** [comment]
Habe die Version getestet. Funktioniert für mich einwandfrei!

Um die Sekunden bis zum Ablauf des Timers zu bekommen ziehe ich einfach die aktuelle Zeit von nextTimerDate ab. Man könnte sogar direkt auf das Datum triggern, wenn aktuelles Datum = nextTimerDate, das habe ich aber noch nicht ausprobiert.

**Comment by Apollon77** [comment]
Ein Trigger beim nächsten Timer ist schon möglich über das Timer objekt
