### ISSUE TITLE
V2.2.0 Cookie verliert Gültigkeit

### ISSUE THREAD

**Issue by JayVee2** [Apollon77/ioBroker.alexa2#227]
Erstmal vielen Dank für den guten Adapter.
Habe Version 2.2.0 installiert und keine Probleme ein Cookie zu generieren via  http://192.168.188.40:43317/

Problem ist allerdings, dass Gültigkeit nur auf ein paar Tage begrenzt ist und folgende Log-Einträge erscheinen. Das Cookie kann mit http://192.168.188.40:43317/ manuell neu erstellt werden.

alexa2.0 | 2019-03-19 15:57:12.252 | error | Error: You can try to get the cookie manually by opening http://192.168.188.40:43317/ with your browser.
alexa2.0 | 2019-03-19 15:57:12.249 | error | Error:
alexa2.0 | 2019-03-19 15:56:47.504 | info | starting. Version 2.2.0 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.15.0
host.pi1 | 2019-03-19 15:56:45.264 | info | instance system.adapter.alexa2.0 started with pid 23078
host.pi1 | 2019-03-19 15:56:15.228 | info | Restart adapter system.adapter.alexa2.0 because enabled
host.pi1 | 2019-03-19 15:56:15.228 | error | instance system.adapter.alexa2.0 terminated with code 0 (OK)
Caught | 2019-03-19 15:56:15.228 | error | by controller[1]:     at TCP.done [as _onclose] (_tls_wrap.js:360:7)
Caught | 2019-03-19 15:56:15.228 | error | by controller[1]:     at _handle.close (net.js:561:12)
Caught | 2019-03-19 15:56:15.227 | error | by controller[1]:     at TLSSocket.emit (events.js:211:7)
Caught | 2019-03-19 15:56:15.227 | error | by controller[1]:     at emitOne (events.js:121:20)
Caught | 2019-03-19 15:56:15.227 | error | by controller[1]:     at TLSSocket.socketCloseListener (_http_client.js:377:9)
Caught | 2019-03-19 15:56:15.227 | error | by controller[1]:     at ClientRequest.emit (events.js:211:7)
Caught | 2019-03-19 15:56:15.227 | error | by controller[1]:     at emitOne (events.js:116:13)
Caught | 2019-03-19 15:56:15.227 | error | by controller[1]:     at ClientRequest.<anonymous> (/opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:726:24)
Caught | 2019-03-19 15:56:15.227 | error | by controller[1]:     at /opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:742:20
Caught | 2019-03-19 15:56:15.226 | error | by controller[1]:     at checkAuthentication (/opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:634:53)
Caught | 2019-03-19 15:56:15.226 | error | by controller[1]: TypeError: Cannot read property 'password' of undefined
Caught | 2019-03-19 15:56:15.226 | error | by controller[0]:     at _combinedTickCallback (internal/process/next_tick.js:139:11)
Caught | 2019-03-19 15:56:15.226 | error | by controller[0]:     at emitErrorNT (internal/streams/destroy.js:66:8)
Caught | 2019-03-19 15:56:15.226 | error | by controller[0]:     at TLSSocket.emit (events.js:211:7)
Caught | 2019-03-19 15:56:15.226 | error | by controller[0]:     at emitOne (events.js:116:13)
Caught | 2019-03-19 15:56:15.226 | error | by controller[0]:     at TLSSocket.socketErrorListener (_http_client.js:401:9)
Caught | 2019-03-19 15:56:15.226 | error | by controller[0]:     at ClientRequest.emit (events.js:211:7)
Caught | 2019-03-19 15:56:15.225 | error | by controller[0]:     at emitOne (events.js:116:13)
Caught | 2019-03-19 15:56:15.225 | error | by controller[0]:     at ClientRequest.<anonymous> (/opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:726:24)
Caught | 2019-03-19 15:56:15.225 | error | by controller[0]:     at /opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:742:20
Caught | 2019-03-19 15:56:15.225 | error | by controller[0]:     at checkAuthentication (/opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:634:53)
Caught | 2019-03-19 15:56:15.224 | error | by controller[0]: TypeError: Cannot read property 'password' of undefined
alexa2.0 | 2019-03-19 15:56:12.299 | warn | Exception: TypeError: Cannot read property 'password' of undefined
alexa2.0 | 2019-03-19 15:56:12.297 | error | at TCP.done [as _onclose] (_tls_wrap.js:360:7)
alexa2.0 | 2019-03-19 15:56:12.297 | error | at _handle.close (net.js:561:12)
alexa2.0 | 2019-03-19 15:56:12.297 | error | at TLSSocket.emit (events.js:211:7)
alexa2.0 | 2019-03-19 15:56:12.297 | error | at emitOne (events.js:121:20)
alexa2.0 | 2019-03-19 15:56:12.297 | error | at TLSSocket.socketCloseListener (_http_client.js:377:9)
alexa2.0 | 2019-03-19 15:56:12.297 | error | at ClientRequest.emit (events.js:211:7)
alexa2.0 | 2019-03-19 15:56:12.297 | error | at emitOne (events.js:116:13)
alexa2.0 | 2019-03-19 15:56:12.297 | error | at ClientRequest.<anonymous> (/opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:726:24)
alexa2.0 | 2019-03-19 15:56:12.297 | error | at /opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:742:20
alexa2.0 | 2019-03-19 15:56:12.297 | error | at checkAuthentication (/opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:634:53)
alexa2.0 | 2019-03-19 15:56:12.297 | error | TypeError: Cannot read property 'password' of undefined
alexa2.0 | 2019-03-19 15:56:12.296 | error | uncaught exception: Cannot read property 'password' of undefined
alexa2.0 | 2019-03-19 15:56:12.288 | warn | Exception: TypeError: Cannot read property 'password' of undefined
alexa2.0 | 2019-03-19 15:56:12.277 | info | Alexa-Push-Connection Error: Error: WebSocket was closed before the connection was established
alexa2.0 | 2019-03-19 15:56:12.272 | error | at _combinedTickCallback (internal/process/next_tick.js:139:11)
alexa2.0 | 2019-03-19 15:56:12.272 | error | at emitErrorNT (internal/streams/destroy.js:66:8)
alexa2.0 | 2019-03-19 15:56:12.272 | error | at TLSSocket.emit (events.js:211:7)
alexa2.0 | 2019-03-19 15:56:12.272 | error | at emitOne (events.js:116:13)
alexa2.0 | 2019-03-19 15:56:12.272 | error | at TLSSocket.socketErrorListener (_http_client.js:401:9)
alexa2.0 | 2019-03-19 15:56:12.272 | error | at ClientRequest.emit (events.js:211:7)
alexa2.0 | 2019-03-19 15:56:12.272 | error | at emitOne (events.js:116:13)
alexa2.0 | 2019-03-19 15:56:12.272 | error | at ClientRequest.<anonymous> (/opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:726:24)
alexa2.0 | 2019-03-19 15:56:12.272 | error | at /opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:742:20
alexa2.0 | 2019-03-19 15:56:12.272 | error | at checkAuthentication (/opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:634:53)
alexa2.0 | 2019-03-19 15:56:12.272 | error | TypeError: Cannot read property 'password' of undefined
alexa2.0 | 2019-03-19 15:56:12.271 | error | uncaught exception: Cannot read property 'password' of undefined
```

**Comment by Apollon77** [comment]
Kann es sein das du ein netzwerkproblem hattest oder Verbindung zum
Internet mal kurz weg war? Von wann ist die 2.2.0 Installation? Bitte mal die allerneueste vom GitHub drüber installieren. Und nochmal testen bitte.

**Comment by JayVee2** [comment]
Danke für die Rückmeldung.
Netzwerkproblem ist eher ausgeschlossen, da LAN Verbindung. Eine kurze Internetunterbrechung gab es tatsächlich, aber diese wird sowieso jede Nacht unterbrochen.
Entscheidend ist, auch ein Neustart des Adapters löst das Authentifizierungsproblem nicht. 
Der Aufruf von http://192.168.188.40:43317/ mit anschließendem Neustart dagegen schon.
Die Installation ist 2 oder 3 Wochen alt. Ich werde die allerneuste Version von GitHub drüberinstallieren, kann allerdings erst in einigen Tagen Rückmeldung geben, ob sich das Problem wieder zeigt.

**Comment by Apollon77** [comment]
Die nächtlistebzwabgstrennikg könnte mitspielen. Es sollte aber an sich bei einem restart direkt wieder tun. 

Aber ja da fehlt wohl noch mehr fehlerhandling :-(

**Comment by Yvonne8871** [comment]
Hallo 
kann jmn Tipp geben wie man cookie bei Alexa adapter manuell ermitteln und eintragen kann.
Ich kann leider die im Log die alexa adapter ip nicht im meinem browser aufrufen
Danke

**Comment by Apollon77** [comment]
Warum kannst Du nicht aufrufen? Läuft es ggf im Docker und damit weggekapselt oder wie?

**Comment by Yvonne8871** [comment]
Hey
Ich weiß es nicht wenn ich die IP kopiere und dann im Browser aufrufen möchte kommt nix
Und ich kann die Cookies nicht manuell machen

Von meinem iPhone gesendet

Am 25.03.2019 um 16:10 schrieb Ingo Fischer <notifications@github.com<mailto:notifications@github.com>>:


Warum kannst Du nicht aufrufen? Läuft es ggf im Docker und damit weggekapselt oder wie?

**Comment by Apollon77** [comment]
Ok, dann bitte im Forum diskutieren
