### ISSUE TITLE
fix documentation about "bespoken"

### ISSUE THREAD

**Issue by Marty56** [Apollon77/ioBroker.alexa2#228]
Ich versuche gerade zu verstehen, was der Datenpunkt bespoken bedeutet und verstehe den folgenden Satz leider nicht.
 "By nature of the way it works only commands are possible that do not interact directly with the "Device you speak to", like normal commands that do a certain action and provide an answer. "
Mir ist nicht klar, was "normal commands" sind und was folglich nicht-normale commands sind.

Ich habe auch versucht in unzuformulieren, aber bin gescheitert.

**Comment by markuskobe** [comment]
Normale Befehle, die auf dem Device eine Antwort erzeugen, wäre z.B. „ Wie spät ist es?“ oder „Wie hat Bayern gespielt?“ Das sind Befehle, die eine Antwort erzeugen. Ein Befehl ohne Antwort wäre eine Aktion, wie z.B. „Schalte das Licht im Schlafzimmer an“....so mein Verständnis 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Apollon77** [comment]
Jain ...
Auch ein "Schalte Licht im Schlafzimmer ein" ist ein Kommando was sich nicht auf das angesprochene Gerät bezieht. Das geht auch per Bespoken.

Was nicht geht ist "leiser" (weil man nicht sagen kann "mache Gerät XY leiser") oder "Spiele Sunshine Life" (auch hier kann man aktuell leider nicht sagen auf welchem Gerät das stattfinden soll und das "virtuelle Bespoken Gerät" kann das nicht.

**Comment by Apollon77** [comment]
Am Ende ist es 

> only commands are possible that do not interact directly with the "Device you speak to"
