### ISSUE TITLE
Control devices/groups of alexa smarthome

### ISSUE THREAD

**Issue by timboros** [Apollon77/ioBroker.alexa2#23]
Is it possible to get the control of the smarthome devices and groups in alexa in order to turn them on/off?

**Comment by StyleForceOne** [comment]
das wäre extrem nice! :))
ich glaub dann wäre es der nächtigste adapter den es gibt für iobroker den mit alexa kann man derzeit ja alles verbinden ;) :D

**Comment by Apollon77** [comment]
Sollte möglich sein. Geht heute schon über Routinen
