### ISSUE TITLE
send to Developer (Unknown Command PUSH_MEDIA_PROGRESS_CHANGE)

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#230]
`2019-03-29 07:15:10.584 - info: alexa2.0 Alexa-Push-Connection Unknown Command PUSH_MEDIA_PROGRESS_CHANGE - send to Developer: {"destinationUserId":"A24L5DG6QY5NYD","progress":{"mediaProgress":900025,"mediaLength":0},"dopplerId":{"deviceSerialNumber":"XXXXXXXXX","deviceType":"A3S5BH2HU6VAYF"},"mediaReferenceId":"3e463bfa-88be-4183-a303-1f4ddc1d6462:1"}`

**Comment by zer0point** [comment]
2019-04-01 05:50:52.848 - info: alexa2.0 Alexa-Push-Connection Unknown Command PUSH_MEDIA_PROGRESS_CHANGE - send to Developer: {"destinationUserId":"A2LGBGXLZJHKHO","progress":{"mediaProgress":899906,"mediaLength":0},"dopplerId":{"deviceSerialNumber":"xxxxxxxxxx","deviceType":"A7WXQPH584YP"},"mediaReferenceId":"eb8b9dac-123d-4db8-a1d3-28b86c914507:1"}

**Comment by Michaelnorge** [comment]
info: alexa2.0 Alexa-Push-Connection Unknown Command PUSH_MEDIA_PROGRESS_CHANGE - send to Developer: {"destinationUserId":"A2J8WGSE89GJXQ","progress":{"mediaProgress":8100353,"mediaLength":0},"dopplerId":{"deviceSerialNumber":"G090LF09650303P2","deviceType":"A3S5BH2HU6VAYF"},"mediaReferenceId":"4f278c71-f106-43cc-b4aa-b7c0f232ecb5:1"}

**Comment by MeisterTR** [comment]
alexa2.0 Alexa-Push-Connection Unknown Command PUSH_MEDIA_PROGRESS_CHANGE - send to Developer: {"destinationUserId":"AW74XZ5D0H0UY","progress":{"mediaProgress":12602780,"mediaLength":0},"dopplerId":{"deviceSerialNumber":"xxx","deviceType":"A15ERDAKK5HQQG"},"mediaReferenceId":"a8572789-5129-4b18-893f-8447b9118791:1"}

**Comment by Michaelnorge** [comment]
2019-04-02 21:26:21.396 - info: alexa2.0 Alexa-Push-Connection Unknown Command PUSH_MEDIA_PROGRESS_CHANGE - send to Developer: {"destinationUserId":"A2J8WGSE89GJXQ","progress":{"mediaProgress":8100353,"mediaLength":0},"dopplerId":{"deviceSerialNumber":"xxxxxxxxxxxxxxxx","deviceType":"A3S5BH2HU6VAYF"},"mediaReferenceId":"4f278c71-f106-43cc-b4aa-b7c0f232ecb5:1"}

After restart: 2019-04-02 21:29:49.439 - info: alexa2.0 Alexa-Push-Connection Error: Error: WebSocket was closed before the connection was established

(But adapter/instance still working i think)

**Comment by Apollon77** [comment]
Thank you all, this is just a new "event" that comes and the adapter currently is not handling. Will include in next release

**Comment by kxn25** [comment]
{"applianceId":"AAA_SonarCloudService_d3a882f7-0fd8-329d-802b-............................","endpointTypeId":"","driverIdentity":{"namespace":"AAA","identifier":"SonarCloudService"},"manufacturerName":"Amazon","frien
--
alexa2.0
can only get this as a screenshot!
Is that the same Problem?

![Zwischenablage02](https://user-images.githubusercontent.com/44605046/55753249-18b36300-5a4a-11e9-95c9-fe1436ed9114.jpg)

BTW: Great job to all the People behind these Adapters.

**Comment by Apollon77** [comment]
fixed in 2.3.1
