### ISSUE TITLE
Feature request: Weblink to alexa.amazon

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.alexa2#232]
feature request:
https://forum.iobroker.net/topic/21949/admin-als-generelles-verwaltungstool-f%C3%BCr-das-heimnetz

Ein Link wie im Forum beschrieben zu alexa.amazon.de in der Instanzen-Ansicht

**Comment by Apollon77** [comment]
inckuded in 2.4.1 later today
