### ISSUE TITLE
Error: Login unsuccessfull. Please check credentials.

### ISSUE THREAD

**Issue by xmace** [Apollon77/ioBroker.alexa2#234]
> alexa2.0 | 2019-05-05 12:42:44.636 | error | Error: You can try to get the cookie manually by opening http://10.0.0.2:42070/ with your browser.
> -- | -- | -- | --
> alexa2.0 | 2019-05-05 12:42:44.635 | error | Error: Login unsuccessfull. Please check credentials.

All the time even if the login details are correct. 
Have to update the cookie at least once a week manually. Means to check every few days if the adapter is yellow....

Any advice?

**Comment by Apollon77** [comment]
Please switch to 2.2.0 from GitHub
