### ISSUE TITLE
Difference between ''Announcement'' and ''Speak''

### ISSUE THREAD

**Issue by MattL0** [Apollon77/ioBroker.alexa2#238]
Hi, 

I see that in the ''alexa2.0.History.json'' that 
-when I send a text input to the speak command , it uses the ''simon says''' functionality of Alexa.  So it appears it the history** ( I kind of like this).
-When I send a text input to the Announcement command, it does not use the'' simon says''. And it has a different starting sound before the ''tts''. So what does this use to send a tts?

Is that all the differences? Does the Announcement send a notification somewhere else then on my echo? Like somewhere on my cellphone? Actually I find both option useful so please do not depreciate one haha.

Thank you agin for this very nice plugin. I really love it.

**Comment by MattL0** [comment]
Ha sorry just got my answer https://www.amazon.com/gp/help/customer/display.html?nodeId=GHQLL3HFVRYKFD5C
.

But please do not depreciate any one of the two :P

**Comment by MattL0** [comment]
Just saw that the speak function does not honor the ''do not disturb'' function.

But that's logical. You won't say to an Alexa to repeat what you say after you if you don't want to be bothered after LOL.

**Comment by Apollon77** [comment]
Correct. The main difference is that announcement will play a tone before the text and uses tts mechanism and is so maybe more flexible.
