### ISSUE TITLE
Feature-Request: Speak-Command for Alexa-App-Devices

### ISSUE THREAD

**Issue by do1osc** [Apollon77/ioBroker.alexa2#239]
Hello,

The Alexa-App on mobile-devices is able to record voice-commands.

If i want to return a speak-command on mobile-device (Alexa-App), I think i have to use the "This Device"-Object. But there is no speak-command-object available.

So i think it should be possible to return speak-commands on mobile-device (Alexa-App).

**Comment by Apollon77** [comment]
SOrry, but no it is not possible to send "speak outputs" to Apps
