### ISSUE TITLE
nach Übernahme von einem anderen System wird die IP-Adresse in objects.json nicht angepasst

### ISSUE THREAD

**Issue by tugsi** [Apollon77/ioBroker.alexa2#240]
Ich habe ioBroker in einem Docker-Container auf meinem Synology laufen, anfänglich mit der 192.168.1.1 im HOST-Modus.
Mittlerweile hat Buanet sein Docker upgedatet auf Version 3, dort funktioniert der HOST-Modus nicht mehr und ich habe umgestellt auf MACVLAN mit der IP 192.168.1.3
Die Daten vom alten ioBroker habe ich alle so übernommen.
ioBroker selbst läuft ohne Probleme
In der Adaptereinstellung von Alexa2 hab ich unter Proxy-Einstellungen die 192.168.1.3 eth0 drinstehen. Man kann auch nichts anderes auswählen, nur diese eine Netzwerkkarte.
Und trotzdem schmeisst er mir im Log den ERROR raus, dass ich das Cookie unter 192.168.1.1 manuell setzen soll ...
Problem, in der objects.json steht immer noch unter "proxyOwnIp":"192.168.1.1", sprich die alte IP-Adresse.
Die Instanzeinstellungen sagen aber die neue IP-Adresse.
ich vermute mal, dass der Reiter nicht mit der gespeicherten objects.json gefüllt wird, sondern was das System als Netzwerkkarte hat.
Jetzt muss man durch Änderung zB der Mailadresse ein neu abspeichern der Einstellungen erzwingen, standardmäßig läßt der ioBroker ja kein Speichern zu, wenn sich nichts verändert hat.
Erst nach einer "manuellen" Speicherung, wird die IP-Adresse richtig in objects.json abgespeichert.

**Comment by Apollon77** [comment]
Am besten ändere mal den Wert in Port oder so damit der Speichern Button erscheint :-) Dann kannst Du speichern. Die 2.4.1 später heute wird das besser anzeigen und ändern lassen.
