### ISSUE TITLE
Why no more login

### ISSUE THREAD

**Issue by ManuelW77** [Apollon77/ioBroker.alexa2#243]
Hey there,
why the login with credential is removed?

I figured out, that if the login with credentials is done twice works fine.
Is the same as you try to login with a browser and javascript disabled.

**Comment by Apollon77** [comment]
Because it is not working anymore in most cases because of anti fraud measures from
Amazon. 
But in 2.2 Version from github it is only needed to do the proxy way once and after that cookies can be automatically refreshed. Try it.
