### ISSUE TITLE
Alexa 2

### ISSUE THREAD

**Issue by Jan-2005** [Apollon77/ioBroker.alexa2#244]
Habe eben das Alexa 2 auf Io Broker installiert . Da ist aber keine Login Fenster .

**Comment by Apollon77** [comment]
Bitte nach Adapter Start ins log schauen. Da steht wine url und Infos. Wird bald optimiert.

**Comment by Jan-2005** [comment]
Habe den anweißungen gefolgt , Linkt geht nicht , seite nicht verfügbar. 

Manuel habe ich den cockie auch eingetragen geht auch nicht . Liegt es evl am dockernetzwerk.

**Comment by Apollon77** [comment]
Ja sehr wahrscheinlich. Dann ist die IP ggf falsch weil es die Docker interne ist. Wie du das durchschleifst und so weiss ich leider nicht. Ließ mal im iobroker Forum.
