### ISSUE TITLE
Gelber Leuchtring für Notifications

### ISSUE THREAD

**Issue by jnsw** [Apollon77/ioBroker.alexa2#245]
Amazon hat scheinbar seit kurzem die Möglichkeit Benachrichtigungen mit dem gelben Ring zu Amazon-Bestellungen anzeigen zu lassen. [hier](https://stadt-bremerhaven.de/amazon-alexa-gelber-ring-und-ton-kuendigt-lieferungen-an/)

Gibt es diese Möglichkeit hier auch schon? Habe es nur geschafft, Benachrichtigungen an meine Alexa-App auf dem Handy zu senden.

**Comment by jnsw** [comment]
Gut, ich hätte vielleicht vorher suchen sollen. 

Issue bereits offen: https://github.com/Apollon77/ioBroker.alexa2/issues/17

**Comment by Apollon77** [comment]
Und „Commands.notification“ ist es nicht? Die GitHub Version kann das schon.

**Comment by jnsw** [comment]
Nein, echt nicht. :/ Gerade nochmal ungläubig getestet, aber mehr als eine Handy-Notification ist da bei mir nicht. Frisch installiert mit der 2.2 von Github über das iobroker-Menü. Und auch nach Nachfrage, ob ich denn Benachrichtigungen habe, sagte Alexa mir, es gäbe nichts. 

Muss ich irgendwas zurücksetzen oder so? Die Alexa-Skills mit Notifications wie [diese](https://www.amazon.de/Emil-Thies-Text-Nachricht/dp/B07FDHWT6K) funktionieren aber. Da bekomme ich aber keine Handy-Benachrichtigung zu.

**Comment by Apollon77** [comment]
Nee dann hab ich das verwechselt ... also doch noch offen.

**Comment by Apollon77** [comment]
Ok, also Duplcate zu #17, dann schliesse ich das hier. Problem ist das die "gelben Notifications" nicht Gerätespezifisch schondern "User" spezifisch sind. Das bedeutet das man zuerst das Adressbuch irgendwie lesen und beachten muss, damit man dann Notifications an diesen user senden kann ... ist also nicht alles sio simpel und fügt eine komplette Komplexitätsschicht hinzu für den User. Daher hatte ich das erstmal nach hinten geschoben
