### ISSUE TITLE
Feature Request: Display ausschalten

### ISSUE THREAD

**Issue by ralf-ms** [Apollon77/ioBroker.alexa2#246]
Könnte es ein Kommando (unter alexa2.0.Echo-Devices.*.Commands) geben, mit dem man "Alexa, schalte Bildschirm aus" triggern kann?
Ich fänd' es nützlich, wenn man kurz vor der Bettruhe noch die Displays der Spots und Shows ausschalten könnte, die man nicht im Blick hat...

**Comment by Apollon77** [comment]
Bisher keins bekannt. Die Frage ist: kannst dunes per Amazon app machen? Wenn ja dann geht es vielleicht. Wenn nicht dann leider nein.
