### ISSUE TITLE
Echo Show 2 - Texte auf Display ausgeben

### ISSUE THREAD

**Issue by MichaDebuss** [Apollon77/ioBroker.alexa2#247]
Hallo,

der Alexa2 Adapter läuft bei mir sehr gut. Die Sprachausgabe über Alexa klappt auch.

**Frage:**
Ist es mit dem Adapter auch möglich, bei einem Echo Show (2. Gen.) Texte auf dem Display auszugeben? Also neben der Sprachausgabe auf dem Display weitere Informationen auszugeben? Habe dazu noch nichts gefunden.

Vielen Dank im Voraus für jeden Hinweis.

Gruß

Micha

**Comment by Apollon77** [comment]
Nein das geht nur per Skills die entsprechende „Karten“ definieren und die dann ausgegeben werden. 

Es gilt: kann man es per Alexa Handy App machen sollte es der Adapter können. Wenn nicht dann nicht. Sorry
