### ISSUE TITLE
Nach Migration von IoBroker funktioniert der Adapter nicht mehr komplett richtig

### ISSUE THREAD

**Issue by gruenerpanzer** [Apollon77/ioBroker.alexa2#248]
Hallo zusammen,

ich habe nach einer Migration und dem zurückspielen des IoBroker Backups das Problem, dass der Adapter sich zwar wie gewünscht alle SmartDevices/Groups aus meinem Amazon Alexa Konto zieht, aber sobald ich dann einen Wert unter Objekte-->alexa2.0-->Smart-Home-Devices setzen möchte, wird dieser nicht bestätigt bzw. nichts passiert.

Wenn ich den Adapter im Debug laufen lasse und beispielsweise den Luftbefeuchter im Wohnzimmer anschalten möchte, welcher per Alexa skill aktiv ist, dann kommt folgende fehler:

alexa2.0 | 2019-06-16 17:26:56.333 | debug | Alexa-Remote: Response: {"message":"Forbidden","code":null}
-- | -- | -- | --
alexa2.0 | 2019-06-16 17:26:56.176 | debug | Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/phoenix/state","method":"PUT","timeout":10000,"headers":{}}and data={"controlRequests":[{"entityId":"1bae7ba5-3970-405d-816b-
alexa2.0 | 2019-06-16 17:26:56.176 | debug | Alexa-Remote: No authentication check needed (time elapsed 41438)

Wieso wird der Zugriff verweigert?
Ich versteh es einfach nicht 😞

Grüße,

Alex

**Comment by Apollon77** [comment]
Bitte am besten mal den Cookie neu generieren. Am einfachsten dazu die Instanz löschen und neu erstellen. Stelle auch sicher das die gleiche Version des Adapters installiert ist wie vorher. Hattest du da ggf schon die 2.2.0 vom GitHub drauf oder so?

**Comment by gruenerpanzer** [comment]
Version 1.1.3 benutze ich und hab folgendes durch:

Adapter entfernt und neu Installiert, sowie den Cookie über den Link im Log geladen.
Ergebnis: {"message":"Forbidden","code":null}

Frisches Debian, IoBroker,Alexa und Cloud Adapter installiert.
Cookie wieder über das Log eingelesen
Ergebnis:{"message":"Forbidden","code":null}

Cookie gelöscht und adapter neu gestartet um Cookie über das Log erneut zu laden.
Ergebnis: {"message":"Forbidden","code":null}

Email Adresse im Amazon Konto geändert😵 "Es war eine Verzweiflungstat" 😩
Ergebnis: {"message":"Forbidden","code":null}

Cookie manuel generieren hab ich soweit hinbekommen, das ich den code mit dem cookie schnipsel habe, aber was davon bruche ich den jetzt genau?

Das habe ich aus dem queue-and-play mit chrome herauskopiert (zum posten werte verändert!):
`curl "https://alexa.amazon.de/api/np/player?deviceSerialNumber=123
565953dca643197862eb2b1e53aca1^&deviceType=A3S5BHHHU6VAYF^&screenWidth=1920^&_=1560868314710" -H "Cookie: x-amzn-dat-gui-client-v=1.24.4563023.0; session-id=111-2566600-4538661; ubid-acbde=258-1119222-1234360; csrf=4586343297; x-wl-uid=1RkTqquDgnFyEzMIJEFLKDSJMfW2XvzVkj17YJcvXE+YUH10Sloh+zpsabf+cbAtDobEW2mCraaTmB6450mE94gaA==; i18n-prefs=EUR; s_vnum=19913983376542^%^26vn^%^3D3; s_nr=1560567549999-Repeat; s_dslv=1545213550000; x-acbde=acpxnb2a2WejiqQdIjmma51LCVweEQNT; at-acbde=Atza^|IwEBILWkJUyZegWnoE3Ay6aRis-VCLGba95Ab90kH4DcGqmBBzZuM1od-lddOKgkpYOmb9bWQrglv2wUyCfAw3JucKb5eFo5qg3SwVxLOISmOplLTUF_WwBtn41gERKW92Zi1ZZ-LLbRLC1k0N4lWcqpTKJtumspYTuiBq0HiocpLpxeAN3VQ7dNk688lNb3IEEpP6L8MQ6LiuuHSyDC0LVsro6U-Uklg_H9KZNPedn6am1EHlsFCJ-ImInZw23SA-7r9M00HdbB7lnaBnTU765OkjbKdnw9N1n7v3NW4kHQeHmDnHINGhLLGpTzyrNN2PNN_UwHJtdTjNIrXaf6XVxXQKWvT6zkLHTUZd5BZFOTVnOirFUZSx7i0uqTRSVD1kBE2DOL8kFLCTqyxCmmU-xt_L1e; sess-at-acbde=^\^"yBsLBlgtm2/yizd1LqV1Er4m1J3I+C230TcaR2M9lYk=^\^"; sst-acbde=Sst1^|PQGgsaVgyJtZub5rs3xFy6liCyosDZu5qg-hGzQc5E9gaE1zvLe4S-ivXWcYokDAupr230FAQh2hHZ5dWIoIrnrpNfg33xTB2WSnqlt72jpapg4Zz8NpEuC6I5EmP54C-Vs4RAEkWuAm_xFoh12nk-Qhf-EZvxD09cjVkOwXFfATMULYxzzILOD7UTHizI7B1ApWn51cP6bqvG-XXXXeTPD8t7jl5El_FdhlYn3mmtn476FfnI5E7anoZNSKLyE-jauNJssBeGUjsSd0z8746mujYcJbKQsMMVVUlxcu4jXXxXXYcC4GasQyvOIp92wY-TPKAOys8NV0; session-id-time=2082787201l; session-token=^\^"6LJJyGuj9FonDZA1yPpfYFtgXY9uFjo93Y+hyUiClB3+UcjFYTcOffG1rwVNnf3D5fqVJd5NKVFnk1Eikan1Tbv4mrvzQt9x/ecwyJzuPd4cB/E0B/hqDn+81TacA945P5PGyBHUJeYuKS2WShoEULmm/quNIPgpqvER9i0KTzbgfHvQql3vqVu/QzaRe2DOYOfYwjaWkf6NYdHlp9o87DhWPN3MO7bxD1Z/jEVjz7LJ5ipNzS2D146/MW8ZqedT1mYanNKzEqoE8W+icZ5itg==^\^"" -H "Accept-Encoding: gzip, deflate, br" -H "Accept-Language: en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36" -H "Accept: application/json, text/javascript, */*; q=0.01" -H "Referer: https://alexa.amazon.de/spa/index.html" -H "X-Requested-With: XMLHttpRequest" -H "Connection: keep-alive" --compressed`


Laut Anleitung 

`COOKIE = "Cookie: x-amzn-<.......>.aA="; csrf=-2012345694" `

müsste es ja der Teil sein:

`"Cookie: x-amzn-dat-gui-client-v=1.24.4563023.0; session-id=111-2566600-4538661; ubid-acbde=258-1119222-1234360; csrf=4586343297;`

Ich würde sagen das es dieser Teil ist:

`"Cookie: x-amzn-dat-gui-client-v=1.24.4563023.0; session-id=111-2566600-4538661; ubid-acbde=258-1119222-1234360; csrf=4586343297; x-wl-uid=1RkTqquDgnFyEzMIJEFLKDSJMfW2XvzVkj17YJcvXE+YUH10Sloh+zpsabf+cbAtDobEW2mCraaTmB6450mE94gaA==; i18n-prefs=EUR; s_vnum=19913983376542^%^26vn^%^3D3; s_nr=1560567549999-Repeat; s_dslv=1545213550000; x-acbde=acpxnb2a2WejiqQdIjmma51LCVweEQNT; at-acbde=Atza^|IwEBILWkJUyZegWnoE3Ay6aRis-VCLGba95Ab90kH4DcGqmBBzZuM1od-lddOKgkpYOmb9bWQrglv2wUyCfAw3JucKb5eFo5qg3SwVxLOISmOplLTUF_WwBtn41gERKW92Zi1ZZ-LLbRLC1k0N4lWcqpTKJtumspYTuiBq0HiocpLpxeAN3VQ7dNk688lNb3IEEpP6L8MQ6LiuuHSyDC0LVsro6U-Uklg_H9KZNPedn6am1EHlsFCJ-ImInZw23SA-7r9M00HdbB7lnaBnTU765OkjbKdnw9N1n7v3NW4kHQeHmDnHINGhLLGpTzyrNN2PNN_UwHJtdTjNIrXaf6XVxXQKWvT6zkLHTUZd5BZFOTVnOirFUZSx7i0uqTRSVD1kBE2DOL8kFLCTqyxCmmU-xt_L1e; sess-at-acbde=^\^"`

beides funktioniert aber nicht :( 


KLannst du mir die Stelle mal markieren? :)

**Comment by sigi2345** [comment]
Fehler ist bekannt!

[https://forum.iobroker.net/topic/17158/iobroker-alexa2-v2-0-alpha-status-github-version/467](url)

**Comment by gruenerpanzer** [comment]
> Fehler ist bekannt!
> 
> [https://forum.iobroker.net/topic/17158/iobroker-alexa2-v2-0-alpha-status-github-version/467](url)

Ich kann mich aber verbinden und auch meine in der

**Comment by gruenerpanzer** [comment]
Danke ihr Zwei 🥇
