### ISSUE TITLE
Falsche Anzeige Link zum Cookie

### ISSUE THREAD

**Issue by actionbyte** [Apollon77/ioBroker.alexa2#254]
Nach dem Update auf 2.3.3 wird die Konfigurationsseite zum Einloggen angezeigt.
Dort steht:
`Klicken Sie hier, um <a href="http://192.168.1.11:42911/" target="_blank">sich einmal in Ihrem Amazon-Konto anzumelden und</a> die Adapterverbindung zu Ihren Alexa-Geräten zu aktivieren.`
Kein Link vorhanden wenn ich mit der Maus drüber gehe (mehrere Brwoser probiert).
Habe Link kopiert und manuell aufgerufen. 
Danach korrektes Einloggen und Anzeige von 
**Alexa-Cookies sind aktuell und zuletzt aktualisiert am 22.06.2019**
Wäre schöner wenn der Link funktioniert oder über einen Button aufgerufen werden könnte.
@Apollon77 : Trotzdem Danke für die neue Version! ;-)

**Comment by Apollon77** [comment]
Js bekannt. Brauche hier Unterstützung von anderen devs. Kommt.

**Comment by Apollon77** [comment]
Sollte in 2.4.1 später besser sein
