### ISSUE TITLE
Fehler bei der Ausgabe von Zusammengesetzten Bildern in DP ".Player.imageURL"

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#255]
https://forum.iobroker.net/topic/23373/alexa2-update-2-3-3-verf%C3%BCgbar/30

das Bild wird aus mehreren Bildern zusammen gesetzt, und im debug auch richtig ausgeworfen. aber der Adapter schreibt die Adresse nicht komplett in den Datenpunkt!

**Comment by Apollon77** [comment]
Siehe Rückmeldung im Forum: Ich brauche bitte Debug von der Player-Rückmeldung. An sich macht der Adapter nichts mit dem Wert, es kann aber ggf sein das es im Admin nicht vollständig angezeigt wird aber die URL vollständig da ist. Bitte auch mal per JavaScript Adapter versuchen den State zu lesen ob er da komplett ist

**Comment by Matten-Matten** [comment]
Ich lese den wert ja per java script aus und schreibe es in eine HM Variable.

**Comment by Matten-Matten** [comment]
Ich hab dir im Forum noch einmal neu ein log gesendet.

**Comment by Apollon77** [comment]
> Ich lese den wert ja per java script aus und schreibe es in eine HM Variable.

Und du bist sicher das es HM nicht verschlicjt? Mal den ausgelesenen Wert geloggt auf iobroker seite?

**Comment by Apollon77** [comment]
hm ... Amazon bug I would say, from your log this is the value the adapte reads:
```
{"clientId":"Dee-Domain-Music","contentId":null,"contentType":"CUSTOM_STATION","currentState":"PLAYING","imageURL":"https://images-na.ssl-images-amazon.com/images/I/61X2z+YeiSL.SS500.","isDisliked":false, ...
```
... so cutted here already

**Comment by Matten-Matten** [comment]
Ja bin mir sicher, kann ich aber auch noch Mal als Log testen

**Comment by Apollon77** [comment]
ich baue in die nächste version ein handlign ein "wenn image url mit einem "." endet hänge ein png dran ... mal schauen

**Comment by Matten-Matten** [comment]
OK. Ich nehme erstmal alle Images aus dem Datenpunkt mainArtUrl

**Comment by Apollon77** [comment]
2.4.1 available on github, url fix imageUrl included!!
