### ISSUE TITLE
Support for Compact mode

### ISSUE THREAD

**Issue by Apollon77** [Apollon77/ioBroker.alexa2#257]

**Comment by INgoRah** [comment]
Please create a PR with this patch. Verified that adapter is running in compact mode

[Support-of-compact-mode.patch.txt](https://github.com/Apollon77/ioBroker.alexa2/files/3365755/Support-of-compact-mode.patch.txt)

**Comment by Apollon77** [comment]
Thank you very much, will come the next days in 2.5.0 !
