### ISSUE TITLE
Feature add sync announcement on all device

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#259]
Ich hab auch noch ein Feature in der Routienen Erstellung  in der Alexa APP entdekt:

unter **+ Aktionen hinzufügen** kann man auf **Nachrichten(Speak/announcement)** gehen, dann auf **Ankündigung senden**  gehen  den Text eintragen und zu guter letzt das Gerät auswählen. Dort kann man ****Alle Geräte**** auswählen. 

Und alexa gibt den eingetragenen Text Synchron auf allen Devices wieder. Vielleicht kannst du das im Adapter integrieren? ***Text synchron wiedergeben ist ja das was noch so fehlte.***

Gruß 
Matten Matten

**Comment by dklinger** [comment]
Hi @Apollon77,
ich würde hier ggf. helfen da ich das auch bräuchte (unter anderem wegen #265).
Wenn ich das richtig sehe, müssten doch dazu die devices, an die das Announcement gehen soll, hier (https://github.com/Apollon77/alexa-remote/blob/4830241d3e5f4deafa89feb927e75c63ff8c8d5c/alexa-remote.js#L1461-L1464) eingetragen werden. 
In der Alexa-API stecke ich nicht wirklich drin, daher kann ich meine Vermutung aktuell nicht untermauern, würde mich aber ggf. einarbeiten und einen Pull Request stellen. Gibt es zu der API die du da verwendest eine öffentliche Doku oder ist das aus aus der Erfahrung mit verschiedenen anderen GitHub-Repos zur Alexa-Thematik entstanden?

**Comment by Apollon77** [comment]
Offizielle Doku nicht wirklich :-)
DIe Idee für alexa-remote ist grob hier beschrieben: https://github.com/Apollon77/alexa-remote/issues/28 ... das wäre der erste Teil, danach müsste man die relevanten Teile in alexa2 so umbauen das es keine schleifen über die devices sondern so ein Call ist .

Über jede Zulieferung bin ich froh. beim mir quillt die Todoliste gerade über auch wenn ich gerade gut wegschaffe

**Comment by Apollon77** [comment]
PS: Nur die Definition für "all" muss ich nochmal raussuchen, ich glaube da fehlte das "devices" einfach komplett.

Was Du tun kannst um zu sehen was wie sein muss ist folgendes: Lege Routinen an die das machen was du willst. Dann stelle Alexa2 Adapter auf Debug Log und starte ihn. In dem Log-Wust beim Start werden auch die ganzen Routinen ausgelesen. Das gibt dann ein JSON wo alle Routinen mit Ihren Definitionen drin stehen. Da kannst Du es dann sehen und raussuchen

**Comment by Apollon77** [comment]
Please check 2.6.0 on GitHub
