### ISSUE TITLE
Echo Show 5 wird nicht als solcher erkannt

### ISSUE THREAD

**Issue by DanielHD80** [Apollon77/ioBroker.alexa2#261]
Habe heute meinen Echo Show 5 integriert. Funktioniert, wird aber noch nicht erkannt. Falls Euch das weiterhilft: Device Type: A4ZP7ZC4PI6TO

Gruss Daniel

**Comment by Apollon77** [comment]
Es sollte noch eine Zeile mit den capabilities dabei sein. Die nehm ich bitte auch noch.

**Comment by DanielHD80** [comment]
capabilities:

`FAR_FIELD_WAKE_WORD,AMAZON_MUSIC,LEMUR_ALPHA,MICROPHONE,PANDORA,I_HEART_RADIO,VOLUME_SETTING,EARCONS,PAIR_BT_SINK,DS_VOLUME_SETTING,SOUND_SETTINGS,TIMERS_AND_ALARMS,LOCAL_VOICE,DIALOG_INTERFACE_VERSION,GOLDFISH,SHARKNADO,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,CHANGE_NAME,SUPPORTS_SOFTWARE_VERSION,REMINDERS,AUDIO_PLAYER,SALMON,MUSIC_SKILL,ALLOW_LOG_UPLOAD,TUNE_IN,DREAM_TRAINING,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,ASCENDING_ALARM_VOLUME,AUDIBLE,FACTORY_RESET_DEVICE,FLASH_BRIEFING,SLEEP,SET_LOCALE,PERSISTENT_CONNECTION,VOICE_TRAINING,CUSTOM_ALARM_TONE,KINDLE_BOOKS,SUPPORT_CALENDAR_ALERT`

**Comment by Apollon77** [comment]
kommt in 2.4.4

**Comment by DanielHD80** [comment]
Vielen Dank für die schnelle Umsetzung! Winzig kleiner Fehler noch: Das Icon im Objektbaum fehlt noch. Da habe ich zumindest bei den Dots ein kleines Bild, das ist beim Show 5 noch nicht der Fall. Aber das ist ja definitiv Kür!

**Comment by Apollon77** [comment]
Ich habe für Shows gerade noch kein Icon ... Wenn Du eins bauen magst gern :-))

**Comment by DanielHD80** [comment]
Hab mich an der Datei vom Dot 2 orientiert, hoffe das passt...
![show5](https://user-images.githubusercontent.com/5008845/60279076-c115ec80-9900-11e9-82f9-6395c1836297.png)

**Comment by Apollon77** [comment]
cool Danke. Update mal von Github ... mache jetzt aber deswegen keine offizielle neue Version :-) Kommt ins nächste update rein (oder halt direkt von GitHub)

**Comment by DanielHD80** [comment]
Keine Eile... ;) Ich warte einfach auf das nächste Update... So wichtig sind mir die Bildchen jetzt auch nicht. Wollte es nur der Vollständigkeit halber beisteuern ;)
