### ISSUE TITLE
Commands für Sonos Lautsprecher funktionieren nicht

### ISSUE THREAD

**Issue by Marty56** [Apollon77/ioBroker.alexa2#262]
Ich habe einen Sonos Lautsprecher in der Alexa App eingebunden(Playbar). Er wird unter Echo-Devices gelistet und enthält den Ordner "Commands".

Alle Datenpunkte in Commands funktionieren bei Sonos nicht und der Ordner sollte entfernt werden.

**Comment by Apollon77** [comment]
Dann bitte die Felder device Type und capabilities aus den info States dieses devices hier posten. Dann kann ich das rausnehmen.

**Comment by Marty56** [comment]
![Bildschirmfoto 2019-06-29 um 08 47 09](https://user-images.githubusercontent.com/8623789/60380732-a0f24480-9a4a-11e9-998e-f5734484ee2c.png)
![Bildschirmfoto 2019-06-29 um 08 47 39](https://user-images.githubusercontent.com/8623789/60380735-abacd980-9a4a-11e9-8d57-6e328233240d.png)

Ich hoffe, dass mit den Screenshots ist so ok

**Comment by Apollon77** [comment]
Ne leider nicht. Unter dem device ist ein „Ordner“ Info und da sind States drin. Unter andeeem „deviceType“ und „capabilities“. Die Werte bitte hier her. Aus Screenshot abzutippen ist keine sinnvolle zeitliche Beschäftigung ;-)

**Comment by Marty56** [comment]
capabilities: CHANGE_NAME,AUDIO_PLAYER,PEONY,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,I_HEART_RADIO,VOLUME_SETTING,AMAZON_MUSIC,TUNE_IN,REMINDERS,MUSIC_SKILL,PANDORA

deviceType: 
A15ERDAKK5HQQG

Ich hoffe, Du kannst damit was anfangen.

**Comment by Apollon77** [comment]
Perfekt. Danke
