### ISSUE TITLE
Adapter zeigt keinen URL mehr an für Cookie Ermittlung

### ISSUE THREAD

**Issue by resper** [Apollon77/ioBroker.alexa2#263]
Hallo,

mein Adapter verbindet sich nicht mehr. Im Log gibt es leider keine Hinweise darauf, was genau schief läuft. Er zeigt auch nicht mehr im Log die Adresse an, womit man dann den Cookie erneuern kann. Die einzige Meldung bei einem Neustart des Adapters ist:

> Error: Error while checking Authentication: Error: no body

**Comment by Apollon77** [comment]
Bitte logging auf debug stellen und dann log Posten bitte. 
Dann kann ich da mal genauer reinschauen. 

Danach könnte einfach löschen und neu erstellen der Instanz helfen

**Comment by Apollon77** [comment]
Bitte GitHub Version testen 2.4.5
