### ISSUE TITLE
2.4.4  Error: Error while checking Authentication: Error: no body

### ISSUE THREAD

**Issue by instalator** [Apollon77/ioBroker.alexa2#264]

**Comment by instalator** [comment]
alexa2.0 | 2019-07-01 22:15:38.524 | error | Error: Error while checking Authentication: Error: no body
-- | -- | -- | --
alexa2.0 | 2019-07-01 22:15:38.524 | debug | Alexa-Remote: Response: No body
alexa2.0 | 2019-07-01 22:15:37.682 | debug | Alexa-Remote: Sending Request with {"host":"alexa.amazon.com","path":"/api/bootstrap?version=0","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2019-07-01 22:15:37.682 | debug | Alexa-Remote: cookie was provided
alexa2.0 | 2019-07-01 22:15:37.682 | debug | Alexa-Remote: Use as Base-URL: alexa.amazon.com
alexa2.0 | 2019-07-01 22:15:37.682 | debug | Alexa-Remote: Use as Login-Amazon-URL: amazon.de
alexa2.0 | 2019-07-01 22:15:37.682 | debug | Alexa-Remote: Use as User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by Apollon77** [comment]
please try 2.4.5 from GitHub
