### ISSUE TITLE
Speak/Announcement "überspringt" Echos bei Multiroom

### ISSUE THREAD

**Issue by dklinger** [Apollon77/ioBroker.alexa2#265]
Hi,
super Arbeit die du hier abgeliefert hast.
Bei mir werden allerdings bei der Verwendung mit Speak/Announcement regelmäßig (bis häufig) 1-2 Echos ausgelassen, wenn ich die Commands über eine Multiroom-Gruppe mit 8 Echos laufen lasse.
Hast du eine Ahnung wieso? Ist ggf. ein Delay beim Absenden der Commands sinnvoll?
Beste Grüße,
Daniel

**Comment by Apollon77** [comment]
Ursache ist vorauss Amazon die bei solchen mengen ggf Probleme macht. War zumindestens der bisherige Stand. Fix durch #259

**Comment by dklinger** [comment]
Daher meine Frage ob ggf. ein Delay vor dem Senden der Commands zu Amazon sinnvoll wäre?
Erfahrungsgemäß helfen da oft schon ein paar Millisekunden.
#259 hilft nur bedingt, da dort nur einzelne Echos oder "Alle Geräte", nicht aber Multiroom-Gruppen ausgewählt werden können.

**Comment by Apollon77** [comment]
Was sind denn Multiroom Gruppen? An sich auch nur eine Liste an Geräten, oder? :-) So zumindestens die Idee bisher.
Es ist aktuell absichtlich kein Delay drin weil der Featurewunsch ja bestmögliche synchronität ist ... Muss ich mal überlegen

**Comment by dklinger** [comment]
Ja, klar. 
Was ich meine ist, wenn du das "neue" Announcement-Feature einbaust, das es seit kurzem in DE gibt, lassen sich darüber keine Gruppen (Listen) ansprechen, sondern entweder nur einzelne Geräte oder alle. (Zumindest sofern die API nicht mehr her gibt als aktuell in der Alexa-App möglich ist).
Dadurch kann ich dann nicht z.B. eine Gruppe "Türklingel" haben (die den Echo im Kinderzimmer nicht beinhaltet :D ) und einen Text an diese senden.
Das mit dem Delay probier ich aber mal aus. In einem Test habe ich bereits speak/announcement nicht an die einzelnen Geräte und nicht an die Gruppe gesendet, da hatte ich dasselbe Problem. Wenn ich dasselbe nochmal mache und dort direkt einen Delay einbaue (was in meinem Fall ja ok ist), sollte ich ja rausfinden können ob Amazon da ggf. zickt.
Danke dir.

**Comment by Apollon77** [comment]
Versuch mal in der App. Du kannst mehrere Geräte anhaken wenn du so eine Routine anlegst.

**Comment by dklinger** [comment]
lol. Damit habe ich jetzt nicht gerechnet^^
Manchmal sollte man einfach ein paar mal öfters klicken...
