### ISSUE TITLE
 2.4.5  Alexa-Remote: Response: No body

### ISSUE THREAD

**Issue by instalator** [Apollon77/ioBroker.alexa2#267]
alexa2.0 | 2019-07-05 23:38:20.987 | debug | Alexa-Remote: Response: No body
-- | -- | -- | --
alexa2.0 | 2019-07-05 23:38:20.189 | debug | Alexa-Remote: Sending Request with {"host":"alexa.amazon.com","path":"/api/bootstrap?version=0","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2019-07-05 23:38:20.188 | debug | Alexa-Remote: cookie was provided
alexa2.0 | 2019-07-05 23:38:20.188 | debug | Alexa-Remote: Use as Base-URL: alexa.amazon.com
alexa2.0 | 2019-07-05 23:38:20.184 | debug | Alexa-Remote: Use as Login-Amazon-URL: amazon.de
alexa2.0 | 2019-07-05 23:38:20.182 | debug | Alexa-Remote: Use as User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by Apollon77** [comment]
Ok, next try soon :-)

**Comment by Apollon77** [comment]
I wait for Travis to complete and then punlish 2.4.6, you cound try github version now if you want
