### ISSUE TITLE
Request: Option for killing the cookie manually

### ISSUE THREAD

**Issue by systemofapwne** [Apollon77/ioBroker.alexa2#268]
Hello,
with the latest updates, it is literally impossible to kill the current (valid) cookie in order to request a new one. Before, I just deleted the cookie in the settings and then also killed the alexa-remote service via terminal (if still running). After that, the cookie was void. Now I can't kill that service (it does not seem to spawn) and removing the cookie via iobroker admin (and also by modifying the system.alexa2.0 instance via JS) did not succeed.

**Reason why one wants to use it**: Testing the reaquiring process.
I use nginx for applying SSL and HTTPAUTH on the reaquiring URL and expose it to the internet, so I can reaquire the cookie even when I'm not in my local home network.
Now this rewriting with nginx does not work anymore, so I want to debug, what changed. But for that, I need to void the cookie many many many times.

**Comment by Apollon77** [comment]
In fact this is no longer needed.Get the Cookie once per "proxy Login" and after this adapter will automatically refresh the cookie ... no manual stuff needed anymore

**Comment by systemofapwne** [comment]
The problem, my proxy does not work. There seems to be a problem in my reverse-proxy script due to recent changes on either the amazon-login page or your adapter. In order to fix this issue, I really **need** to void the cookie during the debug process.

**Comment by Apollon77** [comment]
Then easiest way is to delete and re-add the instance

**Comment by systemofapwne** [comment]
Well, I do agree this to be working method, yet it comes with additional time-consuming steps: Remove, wait for iobroker to remove all states (easily 10 seconds), click on adapter-page to add it again (wait like 5 seconds more). Pretty inconvenient :(

**Comment by systemofapwne** [comment]
Not forgetting, to reconfigure the instance again....

**Comment by systemofapwne** [comment]
Anyway, your tip, removing the instance helped me luckily to fix the issue, which was pretty minor: It seems like, lately, the page fell back to _https://www.amazon.com/_ instead of _http://<ip>:<port>/www.amazon.com_ for the HTML-Form. Before, I just rewrote _http://<ip>:<port>_ to _http://MySecureHttpAddress_. Now I added a second subfilter to rewrite _https://www.amazon.com/_ to _http://MySecureHttpAddress/www.amazon.com_ and it works.
I will close this request now and will fall back to this pretty inconvenient method in removing/readding the instance.
