### ISSUE TITLE
Lautstärke bei einem Multiroom Device nicht mehr setzbar

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#27]
Moin, erstmal großartiger Adapter! vielen vielen Dank dafür!!!

seit **_ioBroker.alexa2 Vers. 0.3.0_** kann ich keine Lautstärke bei einem Multiroom Device mehr setzen. Ist das Absicht? Ich fand die Funktion mega gut das man alle Echos mit einmal regeln kann.

Vielen Dank im voraus!

Gruß 
Matten

**Comment by Apollon77** [comment]
Geht nicht mehr weil Datenpunkt weg? Oder geht es generell nicht mehr? Log auf debug level bitte und Debug senden

**Comment by Apollon77** [comment]
Für Featurewunsch bitte eigenes issue anlegen!

**Comment by Matten-Matten** [comment]
`

alexa2.0 | 2018-07-25 13:26:13.871 | debug | State changed  alexa2.0.Echo-Devices.342adf5ea9124407a03fd9834423455b.Player.volume:  {'val':50,'ack':true,'ts':1532517973865,'q':0,'from':'system.adapter.alexa2.0','lc':1532517973865}
-- | -- | -- | --


`

**Comment by Apollon77** [comment]
... UND die Zeilen danach!!!! :-)

**Comment by Matten-Matten** [comment]
das ist so mega viel was er ausspuckt. dann muss ich alles posten 

schicke es per PN

**Comment by Apollon77** [comment]
wird in der 0.3.1 wieder gehen. Bitte Forum Thread beobachten. Poste da
