### ISSUE TITLE
Stopping/Interrupting Alexa does not work anymore

### ISSUE THREAD

**Issue by systemofapwne** [Apollon77/ioBroker.alexa2#271]
I'm not sure, if this is an issue of this adapter of by the Alexa backend itself, but in the past, whenever Alexa was speaking, I have been able to interrupt the current voice output by issuing a "speak" command, which then has been played instead. Now, for a few weeks I think, this does not work anymore. It looks like, that the "speak" command is appended to whatever alexa is currently speaking.
It is of particular interest to me, that I can interrupt whatever alexa is saying by issuing a "speak" command (or any other programming method), since I use alexa only as a speak processor, sending the command to "text2command" and then replying with a custom text via "speak". Now, I have to wait, until alexa stops babbling stuff like "Es tut mir leid, aber ich konnte kein Gerät mit dem Namen Licht finden......" before it finally says "OK".

**Comment by Apollon77** [comment]
Adapter did noch changed anything. So I assume Amazon did changes. Please try if setting up a routine with „stop Musik/audio“ function works and triggering that.

**Comment by systemofapwne** [comment]
"deviceStop" will neither cancel an error like I have descriped, nor does it interrupt a "speak" command :(.
I fear, amazon has tinkered around in the backend and thus has rendered my Alexa somehow useless. Time to get a google home assistant then......

**Comment by Apollon77** [comment]
Seems so .. but google Home is not even that good controllable or allows such custom speak stuff :-(

Did you also played around with announcements, notifications or speak-tts? maybe this still does what you want?

**Comment by systemofapwne** [comment]
After searching around the web, I came to a similar conclusion with GHome. I will further try to find a workaround. For me, Alexa has many upsides but also some downsides which now became more and more pronounced. I simply need a speech to text interpreter. If will find a workareound, I might report back.

**Comment by Apollon77** [comment]
you're welcome!

**Comment by systemofapwne** [comment]
I just want to report back that, apparently, Alexa now seems to work as before again: Newly ordered "speak" commands overwrite any other current voice output instead of getting appended.
