### ISSUE TITLE
Unknown Device: Stereo-Subwooferpaar

### ISSUE THREAD

**Issue by Garfonso** [Apollon77/ioBroker.alexa2#275]
Hi,

I just played a bit with alexa2 2.6.0 and it recognized an unknown device:

`Device-type:AP1F6KUH00XPV (AUDIO_PLAYER,TUNE_IN,SALMON,I_HEART_RADIO,PANDORA,AMAZON_MUSIC,VOLUME_SETTING,MUSIC_SKILL,MICROPHONE)`

The device is a virtual device consisting of two Echos and a subwoofer (ie Stereo + Subwoofer). Usually this is only used for listening to music, all other output comes from the single devices.

The controls act a bit strange here... the music providers do not really work. I don't know what is wrong, the subwoofer mumbles something and that is all that happens. The exact same phrase works on an echo devices (which started music on the subwoofer-stereo device, because configured in that way). The controls like play & pause work fine. The things like weather and flasbriefing and singasong are strange, too... all three speakers start talking but not synchronously like with music and especially the subwoofer give a very strange sound. ;-)

I do not really know what went wrong with the music providers... can't see anything in the log (but did not have debug activated). Do you think that would help?

**Comment by Apollon77** [comment]
I added it to 2.6.1 and disable the commands at least. Music providers are available according to the capablities
