### ISSUE TITLE
Update 2.5.1 - DP werden nur langsam aktualisiert

### ISSUE THREAD

**Issue by LJSven** [Apollon77/ioBroker.alexa2#278]
Ich habe heute Morgen das Update auf 2.5.1 gemacht. Ich habe den Eindruck, daß die States sehr langsam übertragen werden (im Vergleich zum Sonos Adapter) - kann man da was dran ändern?

**Comment by Apollon77** [comment]
Bitte Debug Log senden bzw prüfen

**Comment by LJSven** [comment]
Hier mein Logfile->

[alex.log](https://github.com/Apollon77/ioBroker.alexa2/files/3430314/alex.log)

**Comment by LJSven** [comment]
Hier mein Logfile von ein paar Aktionen ->

[alex.log](https://github.com/Apollon77/ioBroker.alexa2/files/3430320/alex.log)
