### ISSUE TITLE
Control Befehle sind keine Button mehr

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#28]
Seit dem die Control Befehle wie zb. _controlPause, controlPlay_ usw. keine Button mehr sind muss ich erst _controlPlay_ auf _false_ setzen um dann _controlPause_ auf _true_ zu setzen, damit erst was passiert.

Gruß
Matten

**Comment by Apollon77** [comment]
Daran wurde an sich nichts geändert. Welche Rolle ist es denn? Da müsste "button.play/pause" stehen.

kann es sein das Du den Expertenmodus eingeschaltet hast? Dann werden keine Buttons angezeigt sondern kman kann den wert setzen. Aber nochmals "true" geht per dem haken daneben

**Comment by Matten-Matten** [comment]
button.next
 button.pause
 button.play
usw.

**Comment by Matten-Matten** [comment]
![nvidia geforce overlay-25 07 2018_12_51_00](https://user-images.githubusercontent.com/32074970/43196929-e58f5c1e-9009-11e8-90af-5c591e356812.png)

**Comment by Matten-Matten** [comment]
auch bei _**currentState**_ steht bei mir nur noch ein _true_ oder _false_  kein _PLAYING,PAUSED_ mehr

**Comment by Apollon77** [comment]
currentState ist absicht und für Material. Das andere wenn ein Admin bug. Hier aber ganz schnell auf Admin3 bitte :-) Und dort ein issue aufmachen das auch button.* als Button angezeigt wird

**Comment by Matten-Matten** [comment]
Admin3 geupdatet, und ein issue aufgemacht, mal abwarten.

**Comment by Apollon77** [comment]
Danke. Hab bluefox schon informiert.
