### ISSUE TITLE
Echo Show 5 Alexa Tabs

### ISSUE THREAD

**Issue by Mr-Twister72** [Apollon77/ioBroker.alexa2#280]
Das Echo Show 5 bietet ja auch die Möglichkeit Tabs zu erstellen ist es möglich diese in den Commands Datenpunkten mit aufzunehmen ?

**Comment by Apollon77** [comment]
Wie immer gilt? Kann man es per Alexa App steuern dann könnte es der Adapter auch. Also ... kann es die App?

**Comment by Mr-Twister72** [comment]
Indirekt schon sind halt nur Verknüpfungen zu schalter oder Routinen das ganze könnte Bespoken überflüssig machen !
Direkten Zugang auf die Tabs hat mann in der App leider nicht  
Bleibt also zu hoffen das es noch kommt

**Comment by Apollon77** [comment]
Kannst über eine Routine einen der tabs anwählen? Wenn ja könnte man das anschauen.

**Comment by Mr-Twister72** [comment]
Nein die Tabs tauchen bei Routienen leider nicht auf meine Vermutung ist das sie im commands Bereich angelegt werden da die Commands die vom adapter eingelesen werden sind bei den Taps auch vorhanden

**Comment by Apollon77** [comment]
Es gibt bei Alexa keinen Commands Bereich. Der Adapter strukturiert nur bestimmt Kommandos so. Am Ende sind das alles Dinge über Routinen. Aber damit schließe ich hier. Wenn es die App mal kann gern neues issue auf machen.
