### ISSUE TITLE
Send this to developer

### ISSUE THREAD

**Issue by foxriver76** [Apollon77/ioBroker.alexa2#281]
`2019-08-01 06:07:08.216 - info: alexa2.0 Alexa-Push-Connection Unknown Command PUSH_LIST_ITEM_CHANGE - send to Developer: {"destinationUserId":"A1..","listId":"YW16...=","eventName":"itemDeleted","version":2,"listItemId":"3aabdbb4-ddf5-4ffa-8d28-03cf6ea901ed"}`

This occurred while deleting an item from the Alexa-Shopping List on amazon.de website.

**Comment by Apollon77** [comment]
Which adapter version you use?

**Comment by foxriver76** [comment]
Stable

**Comment by Apollon77** [comment]
Should be fixed in GitHub version 3.0.0 ... please check and give feedback (here and/or https://forum.iobroker.net/topic/27930/test-adapter-alexa2-3-0-x)
