### ISSUE TITLE
Temperatur lässt sich nicht einstellen (Thermostat)

### ISSUE THREAD

**Issue by snookerap** [Apollon77/ioBroker.alexa2#282]
Hallo,

nachdem ich es mit dem Tuya-Plugin nicht hinbekommen mein WLAN-Thermostat korrekt einzubinden, habe ich es über den Weg mit dem Alexa-Plugin versucht.
Soweit funktioniert auch alles, die Stadien werden korrekt übertragen.
Das einzige was nicht funktioniert ist, dass, wenn ich in ioBroker bzw. Homekit (mit dem YAHKA-Plugin) die Temperatur verändern will, der Wert zwar an ioBroker übergeben wird, aber nicht an die Alexa-Cloud.

Was kann ich noch tun?

VIele Grüße,

Christian

**Comment by Apollon77** [comment]
Adapter auf Debug Logging setzen und log von so einer set Aktion bitte senden

**Comment by snookerap** [comment]
Ich hoffe es reicht so.
Kann das LOG nicht direkt sichern.

[iobroker.2019-08-05.log.webarchive.zip](https://github.com/Apollon77/ioBroker.alexa2/files/3467565/iobroker.2019-08-05.log.webarchive.zip)

**Comment by Apollon77** [comment]
Sorry kann ich nicht lesen. Ich brauche bite das Log und am besten das von der Platte unter /opt/iobroker/log/...

**Comment by snookerap** [comment]
[iobroker.2019-08-05.log.zip](https://github.com/Apollon77/ioBroker.alexa2/files/3469236/iobroker.2019-08-05.log.zip)

so, habs jetzt.
Der letzte Versuch die Temperatur in Homekit zu ändern war um 22:11Uhr.
Hoffe du kannst was damit anfangen...

Viele Grüße,

Christian

**Comment by Apollon77** [comment]
Ok, der Fehler ist: Validation failed with the following error(s): [InvalidParameters: [StringParameter(value=26), StringParameter(value=CELSIUS)] for action setTargetTemperature]","data":null}]}

Ich muss wissen warum er CELSIUS nicht mag
Dann brauche ich jetzt den Debug Log vom Adapterstart ... wieder aus dem File. Am besten aber (wegen pot. sensitiver Daten) an iobroker@fischer-ka.de

**Comment by snookerap** [comment]
hab das Log per Mail geschickt,
danke

**Comment by Apollon77** [comment]
ALso ich finde nicht wirklich was ...hm ... versuch mal bitte in das feld "targetSetPoint-scale ein "FAHRENHEIT" reinzuschreiben und schick mal die tempaeratur in Fahrenheit als wert ... nur mal ein test. SOnst brauch ich nochmal Deug log von so einen Fehlgeschlagenen set versuch von iobroker aus

**Comment by Apollon77** [comment]
3.0.3 ist auf GitHub ... bitte damit checkwn!
