### ISSUE TITLE
After restart Alexa2 'Unknown Device, but enabling commands' in Log

### ISSUE THREAD

**Issue by CKMartens** [Apollon77/ioBroker.alexa2#283]
After a restart in the Log came this:

```
2019-08-06 18:22:04.909  - info: alexa2.0 Unknown Device, but enabling commands, Try it and report back if commands work.
--
2019-08-06 18:22:04.910  - info:  alexa2.0 Report to developer as GitHub issue with details for device.  Please grab full next line pot. from logfile on disk if cutted
2019-08-06 18:22:04.910  - info: alexa2.0     Device-type:ATH4K2BAIXVHQ (VOLUME_SETTING,PEONY,MICROPHONE)
```

Did you need something else?

Cheers

**Comment by Apollon77** [comment]
Yes Info what this device is ablut ... and if it supports commands or not

**Comment by CKMartens** [comment]
Sorry,

i have since 9 month no new device installed. I dont know whats is it , where is it, an why. I have one echo 1th generation, one echo 2th generation without hub, two echo dot 3th generation and 2 firetv stick 1th generation. the last device i installed wath a echo dot 3th gen 9 month ago.

if you need any logs i can help, but i dont know wich device an wath is it about.

**Comment by Apollon77** [comment]
YOu can check in the Objects of Alexsa2 adapter with this device type from abobe ... can you find that in one of your "info" objects?

**Comment by CKMartens** [comment]
Ok, in the info state i found a match.
Its the Alexa App.

![Bildschirmfoto vom 2019-08-07 10-05-10](https://user-images.githubusercontent.com/19702758/62605681-e8e27200-b8fa-11e9-96af-6c68541c5d2d.png)
