### ISSUE TITLE
Additional Alarm Settings

### ISSUE THREAD

**Issue by drtp** [Apollon77/ioBroker.alexa2#284]
Hi there,

currently, it is only possible to set a new alarm with a predefined time and to activate or deactivate it. Furthermore, one can see if the alarm was triggered. 

Using the Alexa App one can additionally set a repitition and an alarm tone. It would be nice to have these options for the alexa2 adapter as well, if possible.

Best regards,

Thorsten

**Comment by Apollon77** [comment]
alarm tone will be added in next, the repeating logic will be displayed ... setting this in a state form is way too complex ... Only idea is to allow a complete JSON interface to set it but then someone needs to create  (and before I need to document) the JSON format from Amazon ... that might never be current and faster outdated then we think ... so I decdided against that for now

**Comment by Apollon77** [comment]
have fun https://forum.iobroker.net/post/824793
