### ISSUE TITLE
Start Firefox or Silk remotely

### ISSUE THREAD

**Issue by drtp** [Apollon77/ioBroker.alexa2#285]
Although I am afraid, this is not possible, I do post this feature request. ;)

I would love to see an option to start Firefox or Silk remotely in full screen mode with a predefined site. 

Then I can see who is ringing at our door via vis on my Echo Show 5.

**Comment by Apollon77** [comment]
Before opening such a request were you await that it is not possible please check already closed issues. 
So: can you do it via Alexa app? If not then adapter can not do it.
