### ISSUE TITLE
Feature request: Datenpunkt für den Zustand des Echo-Device

### ISSUE THREAD

**Issue by BillyRay83** [Apollon77/ioBroker.alexa2#287]
Ist es möglich, einen weiteren Datenpunkt für jedes Echo-Device einzurichten, der den jeweiligen Zustand eines Geräts analog zum Leuchtring widerspiegelt? Also quasi die Aktivität anzeigt. True, wenn Alexa etwas gefragt wird oder sie spricht (der Ring dreht sich) , ansonsten (der Ring ist aus, bzw. dreht sich zumindest nicht) false.

**Comment by Apollon77** [comment]
nein, diese Information steht nicht wirklich zur Verfügung. Beste näherung sind die History States
