### ISSUE TITLE
 Unknown Command PUSH_DELETE_DOPPLER_ACTIVITIES

### ISSUE THREAD

**Issue by modmax** [Apollon77/ioBroker.alexa2#288]
`2019-08-14` 17:01:47.319 - info: alexa2.0 Alexa-Push-Connection Unknown Command PUSH_DELETE_DOPPLER_ACTIVITIES - send to Developer: {"destinationUserId":"1234","targetCustomerId":"1234","deleteBeforeTimeInclusive":1483919999000,"dopplerId":{"deviceSerialNumber":"858802c88779feaa3da6f481c328f2f7","deviceType":"XYZ"}}`

Hi Apollon,
bei mir tauchte diese Meldung auf, nachdem ich über Amazon (per Web-Interface) das Löschen aller Sorachaufzeichen getriggert hat.
Die Meldung ging erst nach einem Neustart des Alexa-Adapters weg.

Vielleicht könnte m,an aus dem unknown command ja ein known command machen, das dann nicht Fehler in Reihe produziert,

MfG Markus

**Comment by JayVee2** [comment]
Ich bekomme seit einiger Zeit jeden morgen innerhalb von 2 Minuten hunderte dieser Meldungen: PUSH_DELETE_DOPPLER_ACTIVITIES 
Danach ist wieder gut.
Jemand eine Erklärung?

**Comment by Apollon77** [comment]
Naja irgendetwas oder jemand forciert das Löschen von Sprachaufzeichnungen ... wird in der nächsten Version gefixt

**Comment by JayVee2** [comment]
Super, danke,

**Comment by Apollon77** [comment]
Should be fixed in GitHub version 3.0.0 ... please check and give feedback (here and/or https://forum.iobroker.net/topic/27930/test-adapter-alexa2-3-0-x)

**Comment by JayVee2** [comment]
Ist bei mir gelöst mit 3.0.x, danke.
