### ISSUE TITLE
Datenpunkt currentState keine Anzeige mehr

### ISSUE THREAD

**Issue by sigi2345** [Apollon77/ioBroker.alexa2#29]
Hallo,
beim der vorigen Version hatte ich da eine Anzeige mit **PLAYING**
Jetzt nur mehr true.

Datenpunkt:
alexa2.0.Echo-Devices.GXXXXXXXXX.Player.currentState

**Comment by Apollon77** [comment]
Das ist eine Anpassung für Material. true=PLAYING, false=PAUSE
