### ISSUE TITLE
Echo 2 image is 117x117 instead of 128x128 pixels =)

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#290]
As you requested my "echo input" image in the correct size ("as the others"), here's also a correct one to update the currently used one for Echo2. :)

![echo2](https://user-images.githubusercontent.com/40962599/63119018-7418d300-bf9f-11e9-999b-cc30431beffd.png)

**Comment by Apollon77** [comment]
Is this not an Echo Plus 2?

**Comment by padrino-x** [comment]
No, the 2+ Looks like this :D

![zwei_plus](https://user-images.githubusercontent.com/40962599/63122718-b0e8c800-bfa7-11e9-8539-677ce17a076c.png)

**Comment by Apollon77** [comment]
Should be fixed in GitHub version 3.0.0 ... please check and give feedback (here and/or https://forum.iobroker.net/topic/27930/test-adapter-alexa2-3-0-x)

**Comment by padrino-x** [comment]
Seems to me, that still the old 117x117 pixels image and not my 128x128 pixels version from this issue is used. Are is there any chance I need to delete?

**Comment by Apollon77** [comment]
Maybe try a new „iobroker upload alexa2“ and clear your browser cache?! ;-)

**Comment by padrino-x** [comment]
Thanks. The upload fixed it.
