### ISSUE TITLE
Feature request: Data points for Echo Spot

### ISSUE THREAD

**Issue by DoraDeu** [Apollon77/ioBroker.alexa2#292]
I currently switch the display of the Echo Spot off by telling this Alexa when I leave the room and I know that I will be away for a long time (for power saving and other reasons)
It would be cool to have a data point for the Echo Spot that this can be event triggered or time dependent.

**Comment by Apollon77** [comment]
Can you do that also via the Alexa handy app or via a routine? From my knowledge not. If this is still true then adapter also had no chance. Sorry. Please reopen if app/routine can do it.
