### ISSUE TITLE
Bluetooth Toogle weg?

### ISSUE THREAD

**Issue by Blackei** [Apollon77/ioBroker.alexa2#293]
Hallo zusammen,

ist der Bluetooth Toggle weg? Ich bin mir sicher das ich mich früher über den Toggle automatisch mit meinem Phone verbunden habe?

**Comment by Apollon77** [comment]
Zeug mal Die States Dir da sind

**Comment by Diginix** [comment]
Seit Oktober sind bei allen Echo Dots Gen.3 die mit einem Bluetooth Gerät gekoppelt waren die kompletten Knoten und Objekte unterhalb des Echo Dots im Adapter weg, die vorher das gekoppelten BT Geräte und den Status gezeigt haben.

Der Debug Logeintrag dazu fällt schmal aus:
`2019-10-21 06:07:44.398  - [32minfo[39m: alexa2.0 Deleting the following states: ["Smart-Home-Devices.6ffde6a9-1744-47fc-94a5-d31333c57d57","Smart-Home-Devices.268aa17d-bec4-4423-af39-532eb5218846","Smart-Home-Devices.549f97ba-61fb-47f6-bce7-0ebc71059326","Echo-Devices.G090U509********.Bluetooth.bc34c4aa91b41a313ad64231d8e6936314ac7df1b581f9d07335de2c3bcf91f6","Echo-Devices.G090U509********.Bluetooth","Smart-Home-Devices.6ffde6a9-1744-47fc-94a5-d31333c57d57.#delete","Smart-Home-Devices.6ffde6a9-1744-47fc-94a5-d31333c57d57.#enabled","Smart-Home-Devices.268aa17d-bec4-4423-af39-532eb5218846.#delete","Smart-Home-Devices.268aa17d-bec4-4423-af39-532eb5218846.#enabled","Smart-Home-Devices.549f97ba-61fb-47f6-bce7-0ebc71059326.#delete","Smart-Home-Devices.549f97ba-61fb-47f6-bce7-0ebc71059326.#enabled","Echo-Devices.G090U509********.Bluetooth.bc34c4aa91b41a313ad64231d8e6936314ac7df1b581f9d07335de2c3bcf91f6.unpair","Echo-Devices.G090U509********.Bluetooth.bc34c4aa91b41a313ad64231d8e6936314ac7df1b581f9d07335de2c3bcf91f6.connected"]`
