### ISSUE TITLE
Keine Sprachwiedergabe

### ISSUE THREAD

**Issue by MubiTec** [Apollon77/ioBroker.alexa2#295]
Das Skript wird durch alexa über einen Datenpunkt aktiviert. Liest den echo aus, von dem die Anfrage kam und schreibt auch den zu sagen den Text in das Ausgabe Feld. Nur allein es wird nichts abgespielt. Wenn ich dann manuell noch mal in den Datenpunkt gehe unter enter drücke wird es abgespielt...
Jemand eine Idee?

var i;
var txt;
on({id: new RegExp('javascript.0.scriptEnabled.Alexa_.Fenster'), change: "any"}, function (obj)
{
var y=$('zigbee.0*opened');
txt = ''
y.each(function(id, i) {
if(getState(id).val)
{
    txt = txt + getObject(id).common.name + '' ;
}
}
)
txt = txt.substring(txt.length-1,0);
setTimeout (function(){Ausgabe(txt);}, 15000)
})
 
function Ausgabe (Meldung) {
        //setState ('alexa2.0.Echo-Devices.' + getState('alexa2.0.History.serialNumber').val+ '.Commands.speak-volume', 30)
        setState('alexa2.0.Echo-Devices.' + getState('alexa2.0.History.serialNumber').val+ '.Commands.speak',Meldung, true)
}

**Comment by Apollon77** [comment]
Ja bei setState muss der letzte Parameter false lauten.
