### ISSUE TITLE
Keine Powerstate Aktualisierung

### ISSUE THREAD

**Issue by Aruscha** [Apollon77/ioBroker.alexa2#296]
Moin,

Ich hab ein kleines Problem, die powerstates werden bei mir in Iobroker nicht mehr aktualisiert, sage ich z.B. zu Alexa Badezimmer an, so ist Badezimmer zwar an aber in IoBroker immer noch False, auch nach 5 Min wurde der wert nicht geändert.

Es liegt wohl am Alexa Adapter, sonoff Adapter aktualisiert den Wert wie er auch sein soll.
Ein Neustart von iobroker hat nichts gebracht.
Den Skill zu deaktivieren und wieder zu aktivieren brachte auch nichts.
Den cloud Adapter zu aktualisieren brachte nichts.
Cloud Adapter IOT und FREE selbes problem...
Keine Fehler in der Log

Jemand eine Idee woran das liegen kann ?
Im Anhang ein Bild welche states ich meine. 

And now again the whole thing in broken English... 
Moin,

I have a small problem, the powerstates are no longer updated in Iobroker, I say e.g. to Alexa bathroom, so bathroom is on but in IoBroker still False, even after 5 min the value was not changed.

It's probably due to the Alexa adapter, sonoff adapter updates the value as it should be.
A restart of iobroker has brought nothing.
Deactivating and reactivating the skill didn't work either.
Updating the cloud adapter didn't work.
Cloud Adapter IOT and FREE same problem...
No errors in the log

Anyone have any idea what's the matter?
In the appendix a picture which states I mean.

![IMG_20190907_231808_221](https://user-images.githubusercontent.com/49562390/64480405-5c5ff380-d1c7-11e9-9d4e-e92cfbb36c13.jpg)

**Comment by Apollon77** [comment]
Dann bitte Readme lesen. Werte werden von amazon nicht gepusht, daher werden Daten nur durch triggern des #query states abgeholt.

**Comment by Apollon77** [comment]
Und: Alexa2 Adapter hat mit Skill NICHTS zu tun!!

**Comment by Aruscha** [comment]
Trotzdem beantwortet es die Frage nicht wieso es immer ging das er die Werte aktualisiert hat nur jetzt nicht mehr..
Weil anscheinend ist das #query das Problem aber wie löse ich es?

Mit Skill meinte ich den iobroker Skill für alexa

**Comment by Aruscha** [comment]
Ach und das mit Alexa war ein Beispiel, es ist egal wie ich die Steckdose an bzw. ausschalte, der wert in iobroker wird nicht mehr aktualisiert... Gar nicht... Das war aber vorher immer so.

Habe ich per Hand die Steckdose an gemacht so hat sich der Wert in iobroker im Alexa Adapter geändert, jetzt nicht mehr

**Comment by Apollon77** [comment]
Da musst du dich irren. Das ging noch nie automatisch. 

Aber wenn du #query nutzt geht es. Korrekt?

Aber auch: wenn du eh iobroker hast was bringen Dir dann Alexa2 States? Du hast doch die „echten“ States von iobroker.

**Comment by Aruscha** [comment]
Auch #query funktioniert nicht richtig...

Welchen echten states meinst du?
