### ISSUE TITLE
Text2command am Sonos one

### ISSUE THREAD

**Issue by bergjet** [Apollon77/ioBroker.alexa2#297]
Habe den Custom Skill und den iot Skill in Alexa.
Wenn ich nun den Befehl an Alexa gebe "Alexa frage io Broker nach der Aussentemperatur" dann wir mir der Wert auf den Alexa Echo Geräten angesagt, auf den Sonos One aber nicht. Im Log sehe ich aber die Antwort, nur die Sprachausgabe fehlt. Das hat aber bis vor kurzem funktioniert. Ich habe den iot-Adapter neu installiert und den Cloud-Adapter deinstalliert, seitdem dürfte es nicht mehr gehen. Hängt da etwas in der Cloud oder benötige ich zusätzlich den Cloud Adapter?

**Comment by Apollon77** [comment]
Der Alexa2 Adapter hat mich Cloud und iot nichts zu tun. Wenn bei normalen smart Home devices über Alexa keine Sprachausgabe kommt aber bei anderen schon dann liegt das an Amazon. Ein skill funktioniert geräteunabhängig. 

Damit bitte bei Sonos oder Amazon Nachfragen.

**Comment by Apollon77** [comment]
Und falls du meinst das die Sprachausgabe per Adapter Alexa2 erfolgt (was so oben nicht drinsteht für mich) dann gilt: funktioniert die Sprachausgabe wenn du in der Alexa App eine Routine erstellst auf der sonos? Wenn ja dann muss ich es ansehen. Wenn. Ein dann ist das leider so und du wärst wieder bei Amazon und sonos und der Adapter kann nichts tun

**Comment by bergjet** [comment]
Die Sprachausgabe erfolgt mit dem Adapter Alexa2. Wenn ich eine Routine erstelle (Alexa, gute Nacht) mit der Aktion "Wetterbericht vorlesen" und wähle die Ausgabe auf das Gerät von dem sie sprechen, dann höre ich's am Sonos. Allerdings erscheint mir der Sonos nicht in der Auswahlliste auf. Also unter dem Punkt "Alexa antwortet von" steht 1. Das Gerät zu dem Sie sprechen, 2. Echo, Echo Dot.

**Comment by Apollon77** [comment]
Das passt zu schon mehrfach berichteten Effekten. Die Sonos ist hier wohl nicht "vollwertig". Am ENde wäre Wetterbericht auch falsch. Es gibt allgemein die Option zu sagen "Test ausgeben". Ber hier liegt es wohl an der Sonos

**Comment by bergjet** [comment]
Nach etlichen herumprobieren wird mir der Sonos in den Objekten unter alexa2.0 jetzt so angezeigt "Martin's Sonos One (Sonos One) (Sonos One) (Sonos One) (Sonos One) (Sonos One) (Sonos One) (Sonos One)"

**Comment by Apollon77** [comment]
Auch ein Effekt der von Amazon kommt ... :-( Ändere den Namen in der App und Starte Adapter neu

**Comment by bergjet** [comment]
Ok. Und noch eine Eigeheit. Habe in der Alexa App eine Lautsprecher Gruppe erstellt. Im Adapter wird die Gruppe nicht angezeigt.

**Comment by Apollon77** [comment]
In de app ist sie drin oder wie? Dann bitte debug log einschalten und log vom Start des Adapters an Mich senden per E-Mail iobroker@fischer-ka.de

**Comment by bergjet** [comment]
Habe ich gemacht.
