### ISSUE TITLE
Die Objekte von Routinen lassen sich nicht auf true setzen

### ISSUE THREAD

**Issue by zuldero** [Apollon77/ioBroker.alexa2#298]
Kleines Issue. Den Objekte von Routinen ist das schreiben verboten, man kann natürlich jedem Objekt das schreiben erlauben, jedoch ist ihnen beim nächsten "Update" der Daten (neue routine, etwas bearbeitet, usw.) das schriben gleich wieder versagt.

**Comment by eljarno** [comment]
Ich hatte das Problem lösen können indem ich das Objekt in den Einstellungen auf Schreibrechte gesetzt hatte

**Comment by Apollon77** [comment]
thank you for reporting this, will be fixed in. next version

**Comment by Apollon77** [comment]
Should be fixed in GitHub version 3.0.0 ... please check and give feedback (here and/or https://forum.iobroker.net/topic/27930/test-adapter-alexa2-3-0-x)
