### ISSUE TITLE
Funktion "spiele Playlist" zu integrieren?

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#30]
Moin,
ist es möglich die funktion "spiele Playlist" zu integrieren?

Vielen Dank im voraus!

Gruß
Matten

**Comment by zuldero** [comment]
Du kannst schon deine Playlist spielen: schreibe einfach "Playlist" davor. "Playlist *******"
aber ein eigener state wäre schon nicht schlecht. Der einfachheithalber für neue User

**Comment by sigi2345** [comment]
Das geht ja wirklich.....

**Comment by Apollon77** [comment]
Wo kann man das do eingeben? Wusste ich gar nicht.

**Comment by sigi2345** [comment]
![screenshot 319 _li](https://user-images.githubusercontent.com/41079106/43246568-577019f6-90b2-11e8-990d-5d11cacec549.jpg)

**Comment by Pocky2507** [comment]
Gibt es eigentlich eine Möglichkeit beim abspielen von Playlists `Shuffle´ einzustellen.
Per Sprache geht es.
Alexa spiele meine Playlist XXX zufällig.

**Comment by Apollon77** [comment]
Player.controlShuffle ?!

**Comment by Apollon77** [comment]
Debug log bitte von einem Player/media upate und dem shuffle drücken und den player/media updates danach

**Comment by Pocky2507** [comment]
[Neue Textdatei.txt](https://github.com/Apollon77/ioBroker.alexa2/files/2235130/Neue.Textdatei.txt)

**Comment by Apollon77** [comment]
Shuffle: check 0.4.0 from GitHub and https://forum.iobroker.net/viewtopic.php?f=37&t=16095

**Comment by Matten-Matten** [comment]
Hab es bis jetzt nur bei amazon music angewandt, spotify usw. hab ich leider nicht. Da sind die spotify user jetzt gefragt.

**Comment by Apollon77** [comment]
Die kommende 0.5.0 hat pro Provider einen eigenen "Playlist" state wo das automatisch davorgehangen wird. Mal schauen bitte ob das reicht.

Hier Feedback geben

**Comment by zuldero** [comment]
mir ist noch was aufgefallen. wenn ich eine eigene Playlist habe names z.B. Reggae, und ich jetzt die fertige  playlist Reggae von Spotify hören möchte, wählt er immer die eigene. 
also ich brauche dies überhaupt nicht. hauptsache meine playlist wird gespielt. 
aber manchmal ist man über solche infos dann doch froh. 

Playlist davor schreiben klappt auch bei spotify. jedenfalls am anfang (siehe erster kommentar) als ich diesen tipp gab. (bin gerade im urlaub und kann daher leider nicht testen).
