### ISSUE TITLE
Featurerequest: Alarm-Wiederholung

### ISSUE THREAD

**Issue by wassy92x** [Apollon77/ioBroker.alexa2#300]
Ich bräuchte für ein Script, mit welchem ich 30 Minuten vor dem Wecker das Licht einschalten möchte, die Information, an welchen Tagen ein Wecker wiederholt wird.
Wäre es möglich, diese Information mit zu integrieren?

Andere Ideen?

**Comment by qokaface** [comment]
> Ich bräuchte für ein Script, mit welchem ich 30 Minuten vor dem Wecker das Licht einschalten möchte, die Information, an welchen Tagen ein Wecker wiederholt wird.

Kurze Frage, da ich gerade drüber gestolpert bin:

Was bringt dir diese Info für das Einschalten des Lichts? Möchtest du auschließlich das Licht einschalten ohne das der Wecker wirklich losgeht?

LG

**Comment by exaware** [comment]
Hallo @qokaface und @Apollon77. Ich denke mal, dass @wassy92x einen Lichtwecker realisieren möchte. Dazu wird die Lampe 30 Minuten vorher mit einer Helligkeit von 0% eingeschaltet und bis zur eigentlichen Weckzeit auf 100% hochgedimmt.  Damit wird ein Sonnenaufgang simuliert. Das Licht wird vom Körper wahrgenommen (z.B. über die Haut) und der Aufwachprozess beginnt schon früher. Dann ist das Aufstehen einfacher wenn es klingelt. Ich habe das bei mir bereits mit iobroker javascript realisiert. Momentan benutze ich mein Echo Dot nur für das Abspielen von Musik wenn die Weckzeit erreicht ist. Hierzu habe ich mir extra eine Gui gebastelt, wo ich bis zu vier Weckzeiten einstellen kann. Wenn man mit dem Alexa 2.0 Adapter noch mehr Details vom Wecker auslesen könnte, könnte man den Wecker dann einfach über die Alexa-App erstellen und bräuchte nicht eine eigene Gui. Es würde schon reichen, wenn man die Informationen vom Wecker erhält die einem auch in der Alexa-App angezeigt wird. Ich warte auch schon lange auf diese Erweiterung. Das wäre wirklich lieb.

**Comment by exaware** [comment]
@Apollon77 , wie ist hier der Status? Kommt diese gewünschte Funktion in das nächste Release oder ist das Auslesen des Alarmdatums einfach nicht möglich? Es gibt hier einige Tickets dazu, leider aber ohne Info ob etwas kommt oder nicht.

**Comment by Tuborgius** [comment]
Ich teste es gerade mit dieser Erweiterung in der main.js in function createNotificationStates(serialOrName):

`if (noti.recurringPattern){ 
			setOrUpdateObject(notiId + '.recurringPattern', {common: {type: 'mixed', role: 'state', name: noti.reminderLabel ? noti.reminderLabel : displayTime + ' RecurringPattern'}}, noti.recurringPattern, noti.set);
		}`

Es scheint zu gehen. Für die Übersetzung muss man dann aber selber weiter scripten...

**Comment by Apollon77** [comment]
Warum type Mixed? Sollte doch immer ein string sein oder?!

**Comment by Tuborgius** [comment]
Ja, so wie ich es verstehe schon, kann man in string ändern.

**Comment by ammawel** [comment]
Hallo @Tuborgius und @Apollon77,
da ich auch eine Information über den Tag und nicht nur über die Uhrzeit eines gestellten Alarms benötige, hole ich das Thema noch einmal nach vorne.

Tuborgius schrieb am 28. Aug 2020
> Ich teste es gerade mit dieser Erweiterung in der main.js in function createNotificationStates(serialOrName):
> 
> `if (noti.recurringPattern){ setOrUpdateObject(notiId + '.recurringPattern', {common: {type: 'mixed', role: 'state', name: noti.reminderLabel ? noti.reminderLabel : displayTime + ' RecurringPattern'}}, noti.recurringPattern, noti.set); }`
> 
> Es scheint zu gehen. Für die Übersetzung muss man dann aber selber weiter scripten...
- wo finde ich die Datei main.js mit einer function createNotificationStates(serialOrName)? Ich wollte die Erweiterung einbauen, finde aber im Ordner alexa-remote2 nichts.
- kann die Erweiterung von Tuborgius nicht in den Adapter eingepflegt werden, damit sie auch nach Updates verfügbar ist?

Danke und vG
Achim

**Comment by ammawel** [comment]
ohje... falscher Ordner... iobroker.alexa2 muss es natürlich sein.

Das RecurringPattern funktioniert jetzt, es wäre aber schön, wenn es Standard wäre.

Danke und vG

**Comment by ammawel** [comment]
Die Erweiterung habe ich so abgeändert, dass bei einmaligen Alarmen das recurringPattern 0 angezeigt wird - ähnlich wie in fhem.

Wie gesagt: Bitte als Standard, DANKE

**Comment by Apollon77** [comment]
@ammawel Dann mach doch mit dem Code change als Proposal mal einen Pull Request hier bei Github.

gehe auf das File, oben redchts den Stuft klicken, code editieren, runterscrollen und infos ausfüllen und absenden, PR draus machen

**Comment by exaware** [comment]
> Ich teste es gerade mit dieser Erweiterung in der main.js in function createNotificationStates(serialOrName):
> 
> `if (noti.recurringPattern){ setOrUpdateObject(notiId + '.recurringPattern', {common: {type: 'mixed', role: 'state', name: noti.reminderLabel ? noti.reminderLabel : displayTime + ' RecurringPattern'}}, noti.recurringPattern, noti.set); }`
> 
> Es scheint zu gehen. Für die Übersetzung muss man dann aber selber weiter scripten...

Also ich habe die Erweiterung in besagte Funktion einfügen und konnte den Alexa-Adapter fehlerfrei starten. Ich sehe aber keine Änderung in den Alarm-Datenpunkten. Oder habe ich da was falsch verstanden?

**Comment by exaware** [comment]
> Die Erweiterung habe ich so abgeändert, dass bei einmaligen Alarmen das recurringPattern 0 angezeigt wird - ähnlich wie in fhem.
> 
> Wie gesagt: Bitte als Standard, DANKE

Wie hast du das geändert, dass bei einmaligen Alarmen 0 angezeigt wird? Mir ist noch aufgefallen, dass im Pattern nur der letzte Tag erkannt wird. D.h. wenn ich in Alexa einstelle dass jeden Mo. Mi. und Fr. der Alarm auslösen soll, wird im Pattern nur der Freitag angezeigt. kann man das irgendwie anpassen?

**Comment by ammawel** [comment]
Hier meine Erweiterung nach dem Muster von Tuborgius und der Anmerkung zum Typ von Apollon77 - Pull Request habe ich noch nie gemacht, versuche ich vlt. nachher mal

- Datei /opt/iobroker/node_modules/iobroker.alexa2/main.js
- Zeile 2065 einfügen (nach setOrUpdateObject(notiId + '.triggered',.....):
```
let recPat='0';
if (noti.recurringPattern) recPat=noti.recurringPattern;
setOrUpdateObject(notiId + '.recurringPattern', {common: {type: 'string', role: 'state', name: noti.reminderLabel ? noti.reminderLabel : displayTime + ' RecurringPattern'}}, recPat, noti.set); 
```
Die Pattern bedeuten:
0 = einmalig
P1D = täglich
XXXX-WD = an Wochentagen
XXXX-WE = an Wochenenden
XXXX-WXX-1 = jeden Montag
XXXX-WXX-2 = jeden Dienstag
XXXX-WXX-3 = jeden Mittwoch
XXXX-WXX-4 = jeden Donnerstag
XXXX-WXX-5 = jeden Freitag
XXXX-WXX-6 = jeden Samstag
XXXX-WXX-7 = jeden Sonntag

Die Muster werden von Amazon geliefert, es wird lediglich bei einmaligen Weckern null gegen den String "0" getauscht; das lässt sich mMn in Scripts einfacher vergleichen.

@exaware: Wenn Du am Donnerstag einen Wecker für Montag, Mittwoch und Freitag erstellst, sollte der Freitag als nächster Termin angezeigt werden. Ändert sich das dann nicht immer automatisch auf den nächsten aktiven Tag?

**Comment by Apollon77** [comment]
Die nächste Version wird einerseits genauer darstellen wie die Wiederholung ist, aber wird vor allem (und ich denke darum ging es hier) den zeitpunkt des nächsten triggers als State haben ... damit sieht man wann der Alarm/Reminder das nächste mal ausgelöst wird.

**Comment by Apollon77** [comment]
have fun https://forum.iobroker.net/post/824793
