### ISSUE TITLE
New Echo.Dot 3 Version? > "Unknown"

### ISSUE THREAD

**Issue by iNDeX999** [Apollon77/ioBroker.alexa2#302]
Ex. speach command does not work:
alexa2.0.Echo-Devices. deviceType
A1RABVCI4QCIKC

AUDIBLE,CHANGE_NAME,MUSIC_SKILL,GOLDFISH,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,SUPPORTS_SOFTWARE_VERSION,DS_VOLUME_SETTING,PERSISTENT_CONNECTION,SOUND_SETTINGS,UPDATE_WIFI,REMINDERS,REQUIRES_OOBE_FOR_SETUP,KINDLE_BOOKS,SALMON,DEREGISTER_DEVICE,ACTIVE_AFTER_FRO,PAIR_BT_SOURCE,AMAZON_MUSIC,POPTART,ASCENDING_ALARM_VOLUME,TUNE_IN,GADGETS,TAHOE_BYOD,CUSTOM_ALARM_TONE,DIALOG_INTERFACE_VERSION,PANDORA,AUDIO_PLAYER,FLASH_BRIEFING,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,PAIR_REMOTE,FAR_FIELD_WAKE_WORD,TUPLE_CATEGORY_A,SET_LOCALE,MICROPHONE,BT_PAIRING_FLOW_V2,EARCONS,TUPLE,SLEEP,I_HEART_RADIO,VOICE_TRAINING,ALLOW_LOG_UPLOAD,TIMERS_AND_ALARMS,DREAM_TRAINING,PAIR_BT_SINK,SUPPORT_CALENDAR_ALERT,LEMUR_ALPHA,ALEXA_PRESENCE,VOLUME_SETTING

**Comment by Apollon77** [comment]
Speak works fine for me ... ?!
But yes Device needs to be added, duplicate to #299
