### ISSUE TITLE
Probleme mit echo dot 2gen nach firmwareupdate

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#303]
nach pausieren der Wiedergabe läuft die zeit weiter und alexa2.0.Echo-Devices.Player.currentState bleibt auf true

**Comment by Matten-Matten** [comment]
## EDIT 
nach einem erneuten laden des Adapters funktioniert es...

**Comment by Apollon77** [comment]
Jippie ;-)

**Comment by Matten-Matten** [comment]
Leider muss ich das Problem wieder aufgreifen. Wenn ich eine playlist abspielen von Amazon music und dann einen Song abspielen und dann auf nächsten Song spielen gehe wird immer noch der alte song angezeigt aber das Cover ändert sich so wie wenn ich auf Pause drücke wird die Wiedergabe weiter fortgesetzt und der oben genannte state bleibt auf true, auch die prozentangabe des Songfortschritts läuft weiter.

Ich habe bereits den Adapter komplett runtergeworfen und ihn auch noch mal neu installiert mit Instanz aber selbes Problem wieder

**Comment by Matten-Matten** [comment]
ein downgrade auf V 2.5.1 bringt Erfolg. in der 2.5.1 funktioniert es wieder

**Comment by Matten-Matten** [comment]
auch ein js controller neustart brachte kein Erfolg

**Comment by Matten-Matten** [comment]
JS controller
OS: linux
Eingerichtet: 1.5.14

**Comment by Matten-Matten** [comment]
wenn ich Pushverbindung verwenden deaktiviere und das polling auf 3s setze wird es wieder aktualisiert

**Comment by Apollon77** [comment]
Dann kam wohl in dem Fall per Push keine Info zum liedwechsel :-(

**Comment by Apollon77** [comment]
Da bräuchte ich debug log

**Comment by Matten-Matten** [comment]
hast du eine email adresse für mich? das ich dir das log zusenden kann?

**Comment by Apollon77** [comment]
iobroker@fischer-ka.de

Mit Kontext bzw Details was zeitlich wie wo getan wurde bitte

**Comment by Matten-Matten** [comment]
ok, log ist an die obige email versand worden.

**Comment by Apollon77** [comment]
Bitte schau mal ob die App alles korreekt hau und updated. Ich habe berichte das auch die Alexa App nichts korrekt aktualisiert, dann wäre es eher ein Bug bei Amazon

**Comment by Matten-Matten** [comment]
Ich hab das mit der App vergleichen, und in der App wird alles korrekt aktualisiert

**Comment by Apollon77** [comment]
geht das wieder? Ich kann es nicht reproduzieren?

**Comment by Matten-Matten** [comment]
Im Prinzip werden keine Änderungen mehr registriert. Erst nach dem bspw der Titel laut iobroker am Ende angekommen ist wird aktualisiert. Wenn ich aber vorzeitig den Titel ändere wird immer noch der alte angezeigt.
Das selbe ist auch bei node-red-contrib-alexa2. Mit dem ich im Moment arbeite. Hier habe ich den Vorteil daß ich aktuelle palyerstates mir selbst anrufen kann. Das mache ich in dem ich auf Lautstärke und device Änderungen des jeweiligen devices was die Musik abspielt reagiere . Auch Unterschiede ich da ob tuneIn oder Amazon music abgespielt wird. Bei Amazon music hole ich mir manuell alle 6 Sekunden die aktuellen Werte für das jeweilige device bei tuneIn nicht.

**Comment by Apollon77** [comment]
das heisst deine idee wäre bei welchen triggern noch zusätzlich player zu aktualisieren?

Problem ist das ich weder amazon music noch spotify hab und somit ich das so schwiergig nachstellen kann :-(

**Comment by Apollon77** [comment]
und: wie änderst du den titel? Manuell per app oder per voice kommando?

**Comment by Matten-Matten** [comment]
den Title ändere per iobroker befehl aber auch per sprachkommando.

Ich aktualisiere die werte in Nodered bei:
- Audioplayer State Change
- Media Queue Change
- Media Change	
- Volume Change (der ist wichtig weil der auch immer triggert wenn irgend etwas sich veändert)

Ich hole nicht jedes mal im milisecundentakt die werte wenn **Volume Change** anschägt ich habe das ganze auf 2 msg pro 1 sekunde reduziert.

**Comment by Apollon77** [comment]
Also drin ist schon Player Update bei:
* Audioplayer State Change
* Media Queue Change
* media Change
* Content Focus Change

Ich habs jetzt in der 3.0.1 (kommt gleich, siehe Forum) auch bei Volume CHange eingebaut - ist aber gefühlt eeeecht oft ... aber naja

**Comment by Apollon77** [comment]
Bitte mit 3.0.1 vom GitHub neu testen!

PS: Ich hab mal mit den freien Amazon Music Playlsts getestet  (Alexa, spiele Musik aus den 80ern) ... da kommt immer bei Titelwechseln ein PUSH_AUDIO_PLAYER_STATE

**Comment by Matten-Matten** [comment]
bei mir steht zwar immer noch 2.6.4 aber ich würde sagen, das das aktualisieren der Werte wieder funktioniert.

**Comment by Apollon77** [comment]
Upload ausgeführt? Und wo steht 2.6.4? Wenn er startet im log?

**Comment by Matten-Matten** [comment]
Ja und ja. Auch ein Upload brachte nix. Js Controller neu gestartet aber auch ohne Erfolg. Iobroker läuft als Plugin auf raspberrymatic. Ich muss Mal forschen warum ich den Adapter nicht updaten kann. Hatte bisher keine Probleme. Mal schauen vielleicht das System neu starten.

**Comment by Matten-Matten** [comment]
Wenn ich von github install will kommt folgender Fehler:
```
host.ccu3-webui | 2019-12-22 23:28:56.372 | error | iobroker host.ccu3-webui Cannot install https://github.com/Apollon77/ioBroker.alexa2/tarball/master: 1
```

**Comment by Apollon77** [comment]
Siehe Forum: volles log bitte

**Comment by Matten-Matten** [comment]
js-controller 2.1.1

```
undefined2019-12-22 23:50:02.409 - info: host.ccu3-webui iobroker url "https://github.com/Apollon77/ioBroker.alexa2/tarball/master" alexa2
2019-12-22 23:50:05.011 - info: host.ccu3-webui iobroker install https://github.com/Apollon77/ioBroker.alexa2/tarball/master
2019-12-22 23:50:06.557 - info: host.ccu3-webui iobroker NPM version: 6.9.0
2019-12-22 23:50:06.560 - info: host.ccu3-webui iobroker npm install https://github.com/Apollon77/ioBroker.alexa2/tarball/master --unsafe-perm --loglevel error --prefix "/usr/local/addons/hm-iobroker" (System call)
2019-12-22 23:50:17.963 - info: host.ccu3-webui iobroker npm
2019-12-22 23:50:17.965 - info: host.ccu3-webui iobroker ERR! path gitnpm ERR! code ENOENTnpm ERR! errno ENOENTnpm ERR!
2019-12-22 23:50:17.966 - info: host.ccu3-webui iobroker syscall spawn git
2019-12-22 23:50:17.968 - info: host.ccu3-webui iobroker npm
2019-12-22 23:50:17.969 - info: host.ccu3-webui iobroker ERR! enoent Error while executing:npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/Apollon77/alexa-remote.gitnpm ERR! enoent npm ERR! enoent npm ERR! enoent spawn git ENOENTnpm ERR! enoent This is related to npm not being able to find a file.npm
2019-12-22 23:50:17.971 - info: host.ccu3-webui iobroker ERR! enoent
2019-12-22 23:50:17.989 - info: host.ccu3-webui iobroker
2019-12-22 23:50:17.991 - info: host.ccu3-webui iobroker npm ERR! A complete log of this run can be found in:npm ERR! /usr/local/addons/hm-iobroker/npm_io/.npm/_logs/2019-12-22T22_50_17_974Z-debug.log
2019-12-22 23:50:18.014 - error: host.ccu3-webui iobroker host.ccu3-webui Cannot install https://github.com/Apollon77/ioBroker.alexa2/tarball/master: 1
2019-12-22 23:50:19.039 - info: host.ccu3-webui iobroker exit 25
```

**Comment by Apollon77** [comment]
Für die aktuelle Testversion muss git installiert sein. Ist das bei dir der Fall? Falls ja, Der Fehler sagt das er git nicht starten kann

Aber da es gut aussieht mache ich denke ich heute Abend eine offizielle Version über NPM

**Comment by Matten-Matten** [comment]
OK. Merkwürdig, ich bekomme dandere Adapter auch von git geladen...

**Comment by Matten-Matten** [comment]
ich habe das bei meiner Windows installation versucht , aber hier genau das selbe!

```
$ ./iobroker url "https://github.com/Apollon77/ioBroker.alexa2"
install https://github.com/Apollon77/ioBroker.alexa2/tarball/f0e94dd361d237109c4feb1f686536c4818447be
NPM version: 6.11.3
npm install https://github.com/Apollon77/ioBroker.alexa2/tarball/f0e94dd361d237109c4feb1f686536c4818447be --loglevel error --prefix "C:/ioBroker" (System call)
npm
 ERR! code ENOENTnpm ERR! syscall spawn gitnpm ERR! path gitnpm ERR! errno ENOENT
npm 
ERR! enoent Error while executing:npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/Apollon77/alexa-remote.gitnpm ERR! enoent npm ERR! enoent npm ERR! enoent spawn git ENOENTnpm
 ERR! enoent This is related to npm not being able to find a file.npm ERR! enoent 

npm ERR! A complete log of this run can be found in:npm ERR!     C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm-cache\_logs\2019-12-23T08_49_54_057Z-debug.log
ERROR: host.ioBroker Cannot install https://github.com/Apollon77/ioBroker.alexa2/tarball/f0e94dd361d237109c4feb1f686536c4818447be: 1
ERROR: process exited with code 25
```

js-controller
2.1.1

Betriebssystem Windows
Architektur x64
CPUs 4
Geschwindigkeit 1094 MHz
Modell Intel(R) Celeron(R) CPU N3450 @ 1.10GHz
RAM 7.85 GB
Node.js v10.17.0 (Es gibt eine neuere Version: v10.18.0)
NPM 6.11.3

**Comment by Apollon77** [comment]
Git (das Programm) installieren.
