### ISSUE TITLE
Echo Dot keine Button Aktion

### ISSUE THREAD

**Issue by LJSven** [Apollon77/ioBroker.alexa2#304]
Mein Echo Dot lässt sicht nicht über die "controlPause" / "controlPlay" etc. steuern. 

Woran kann das liegen?

**Comment by Apollon77** [comment]
Bitte mal im Forum schreiben und mit den anderen "erforschen". Adapter neu gestartet? Bedienung per Alexa-App tut?

**Comment by LJSven** [comment]
Über die Alexa App geht es - Adapter neugestartet habe ich - dann holt er sich einmal ein Update und das war es.

**Comment by Apollon77** [comment]
geht das wieder? Ich kann es nicht reproduzieren?

**Comment by Apollon77** [comment]
Bitte mit 3.0.1 vom GitHub neu testen!

**Comment by Apollon77** [comment]
Please test with 3.0.3, reopen or comment if still not working
