### ISSUE TITLE
Power states von Smart Home Geräte aktualisiert sich nicht

### ISSUE THREAD

**Issue by eljarno** [Apollon77/ioBroker.alexa2#306]
Hallo,
habe gerade das Problem, dass sich die Power State Objekte von den Smarthome Geräte nicht aktualisieren. Mall kann ich die aktualisierung über # query initieren, das klappt aber nur manchmal und ziemlich willkürlich. Auch der genannte Trick über Trigger History scheint nicht zu funkionieren. Hatte auch schon im Adapter Push Update ausgeschaltet und die Aktualisierung auf 15 Sekunden gesetzt aber auch das scheint nicht zu funkionieren. Jemand das gleiche Problem oder eine Idee?

**Comment by eljarno** [comment]
Nachtrag: Hatte jetzt schon gelesen, dass es wohl hard codiert nur alle 10 Minuten dauert was in meinen Augen gerade für Sensoren absolut unzureichend ist weil im Normalfall auf Zustandsändeurngen sofort reagiert werden soll. In meinem Speziellen Fall handelt es sich um Türsensoren. Auch der Tuya Adapter ist da leider wenig hilfreich, da hier die Zustandsänderung garnicht durch kommt.

Ein eigenes Script mit #query im Minutentakt, so wie von anderen als Workaround genutzt, scheint bei mir oder generell nicht mehr zu funktionieren.

**Comment by Apollon77** [comment]
Status Updates von smart Home devices werden NICHT gepusht zur App oder zum Adapter. Diese können daher nur via #query abgeholt werden. 

Dieses abholen hat aktuell ein rate limiting drin was glaube ich auf 1 request je 5 bzw 10 Minuten gesetzt ist. Ansonsten sollte im log ein Fehler auftauchen der genau darauf hinweist. Das ist schon seid Beginn so. 

Und bevor du fragst: warum bekommt die App zustandsänderungen quasi direkt mit wenn man auf der detailseite des Sensors ist? Weil die dann diesen einen Wert sekündlich selbst abfragen. 

Die Abfrage generell kann kosten beim skill Anbieter generieren die nicht zu vernachlässigen sind, daher ist das so implementiert.
