### ISSUE TITLE
Datenpunkt Fehler ?

### ISSUE THREAD

**Issue by liv-in-sky** [Apollon77/ioBroker.alexa2#307]
hi ingo,

versuche gerade ein script zu entwicklen, welches die datenpunkte von iobroker auf fehler checkt oder nur mal die anzahl pro instanz anzeigt, ...  https://forum.iobroker.net/topic/25846/script-info-%C3%BCber-datenpunkte-sammeln/5

habe ein problem mit dem datenpunkt   Object "alexa2.0.History.domainApplicationname" - bei diesem datenpunkt kommt das script zum "taumeln" 

bei z.b dieser abfrage, wird der datenpunbkt ausgefiltert
`       if (!JSON.stringify(getObject(id)).includes("type")) {
              var valType = typeof getState(id).val;
              htmlDP.push(id+": "+valType);
              htmlMSG.push("<b>missing TYPE !!</b>" );}`

hast du eine idee, was das sein könnte - ich mußte diese abfrage nur wegen diesem datenpunkt einfügen

![Image 1](https://user-images.githubusercontent.com/18462890/67092158-d2844c80-f1ae-11e9-9d51-f967916fb10c.png)

ich wollte eigentlich mit .hasOwnProperty("type") prüfen- aber auch da kommt :
 Error in callback: TypeError: Cannot read property 'type' of undefined

**Comment by Apollon77** [comment]
Also einerseits hast Du nen Fehler gefunden, da war ein Schreibfehler im Alexa2 Adapter weil das Objekt heisst an sich domainApplicationName (grosses N). Es wurden aber mal beide geschrieben. Wird in nächster Version gefixt.

In dem Fall kommt dein Fehler daher das das Objekt zum State nicht existiert - das solltest Du getrennt abfangen weil das ist quasi schlimmer als wenn nur der Typ fehlen würde ;-)

**Comment by liv-in-sky** [comment]
danke dir - das wird auch abgefangen - werd nach deinem  fix nochmal testen und mitteilung machen

**Comment by liv-in-sky** [comment]
sorry ingo - ich glaube ich habe gestern noch nicht begriffen, was du meintest - verstehe ich das richtig:
- anscheinend bekommt meine abfrage mit selektor einen inhalt zurück, zudem es kein object gibt   - es gibt einen state aber kein datenpunkt-object dazu ! und meine abfrage
`if (!JSON.stringify(getObject(id)).includes("type")) { var valType = typeof getState(id).val; htmlDP.push(id+": "+valType); htmlMSG.push("<b>missing TYPE !!</b>" );}` findet das sozusagen (zufällig) heraus. das bedeutet, dass ich mit dieser abfrage eigentlich ein "missing dp-object" und nicht einen missing type finde. davon gibt es auch mehrere z.b im iot,web oder socketio adapter gibt es  solche

![Image 1](https://user-images.githubusercontent.com/18462890/67144891-6a03a100-f27c-11e9-9eb1-d68498dd68d4.png)
![Image 2](https://user-images.githubusercontent.com/18462890/67144892-6cfe9180-f27c-11e9-90d1-cd747db58660.png)
![Image 3](https://user-images.githubusercontent.com/18462890/67144893-72f47280-f27c-11e9-8c99-8c6ce996a205.png)

**Comment by Apollon77** [comment]
Jupp. Genau das findest du gerade. 

Wenn es ab js-Controller 2 immer noch so ist dann issues bei den Betroffenen Adaptern anlegen.

**Comment by liv-in-sky** [comment]
habe 2.0.34 - werde issues anlegen
falls dir etwas einfällt, was noch wichtig zum prüfen wäre(was dir immer wieder auffällt) (und was ich auch "kapiere") - einfach kurz beschreiben
vielen dank

**Comment by Apollon77** [comment]
Das sind super checks!

**Comment by Apollon77** [comment]
Should be fixed in GitHub version 3.0.0 ... please check and give feedback (here and/or https://forum.iobroker.net/topic/27930/test-adapter-alexa2-3-0-x)

**Comment by liv-in-sky** [comment]
@Apollon77 
danke - dp ("lexa2.0.History.domainApplicationname")wird nicht mehr angelegt - ist aber noch in der redis datenbank unter states - wie löscht man den ?

**Comment by Apollon77** [comment]
Löschen an sich nur manuell per redis dB kommando. Kann ich dir sagen wenn du magst

**Comment by liv-in-sky** [comment]
danke - habe mal javascript instanz neu gestartet - jetzt kommt keine fehlermeldung mehr über den state - lag wohl am cache oder so
habe ein redis tool zum lesen der datenbank - ist nicht mehr vorhanden
**kann geschlossen werden**
