### ISSUE TITLE
Feature: Poll Button für Player States

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#308]
Ich wünsche mir:
Einen Poll Button für Player States um Werte manuell zu holen.

[Wie besprochen](https://forum.iobroker.net/topic/23975/aufruf-alexa2-2-6-0-testen/243)

Gruß
Matten Matten

**Comment by Apollon77** [comment]
see https://forum.iobroker.net/post/823454
