### ISSUE TITLE
Bitte nicht stören wird nicht aktualisiert

### ISSUE THREAD

**Issue by ymicky** [Apollon77/ioBroker.alexa2#309]
Die Datenpunkte für den nicht stören Modus können den Modus in Alexa setzen, aber werden nicht aktualisiert, wenn mit Alexa der Modus geändert wird

**Comment by Apollon77** [comment]
Die info wird nicht gepuscht von Alexa. Der Adapter kann also eine Änderung nicht mitbekommen. Müsste man regelmäßig abfragen. Damit geht es in jedem Fall aber halt mit einer Verzögerung.
