### ISSUE TITLE
Listen auslesen via Adapter möglich?

### ISSUE THREAD

**Issue by Againstyou** [Apollon77/ioBroker.alexa2#31]
Ist es möglich gespeicherte Listen via Adapter auszulesen? (ToDo-List, Einkaufsliste)
Falls nicht ist es möglich dieses "Feature" hinzuzufügen? :)

**Comment by Againstyou** [comment]
Als Text/Liste/ArrayList? Weiss nicht genau was möglich ist. Am Ende würde ich mir die Liste z.B. gerne in VIS anzeigen lassen oder per Script versenden können oder ähnliches.

**Comment by Apollon77** [comment]
API technisch geht das alles, aber wie man das über states sinnvoll abbildet bin ich mir gerade nicht sicher. Muss ich nachdenken

**Comment by Againstyou** [comment]
Danke, dass du dir Gedanken machst. 👍 
IOBroker kann nur States(Boolean/Zahlenwert/Text) oder? Sonst wäre ja ein Array oder ArrayList sinnvoll die man via Script durchlaufen und auch Dinge hinzufügen kann.
Bin gespannt ob du eine Lösung findest. :)

**Comment by MiJo112** [comment]
Fände die Idee auch ziemlich genial. Dann kann man die Einkaufliste auf der VIS darstellen.
Scheint auch mit der API zu gehen:
https://developer.amazon.com/de/docs/custom-skills/access-the-alexa-shopping-and-to-do-lists.html#getList

**Comment by liv-in-sky** [comment]
hi ingo,

ist hier "closed" - aber irgendwie check ich nicht, ob du es integrieren würdest, oder ob es zu wenig gefragt wurde - würde mich auch interessieren ! mache das momentan über ifttt (webhooks)- -> join -> nodered -> mysql  - leider ist ifttt so was von langsam beim update und instabil. bitte um kurzes statement - danke

**Comment by Apollon77** [comment]
Das Issue ist noch "offen" (wo siehst Du ein "closed"?).

Mal abgesehen davon das andere Baustellen in den letzten 2 Wochen wichtiger waren und ich als nächstes Alexa2 mit den ganzen Themen der letzten 4 Wochen ggf nochmal updaten will bin ich mir immer noch nicht sicher WIE ich die Daten der Listen verfügbar machen sollte damit man auch etwas sinnvolles damit anfangen kann.

**Comment by liv-in-sky** [comment]
![closed](https://user-images.githubusercontent.com/18462890/46522071-f9acfc00-c881-11e8-91b1-0aca258f5a66.png)
moin,
habe wie im bild closed gesehen!
ja - du bist ganz schön aktiv beim entwickeln - man sieht dich viel im forum- frag mich, wo du die zeit her nimmst - deshalb dachte ich, wenn die daten nur geholt werden, müßte das kein großer programmieraufwand sein. ifttt nervt mich - die brauchen auch schon mal einen tag, bis ein webhook ankommt.
es geht mir gar nicht darum, etwas sinnvolles damit anzufangen  (zu verarbeiten)- eher darum, die daten zu haben , damit sie angezeigt werden können.  alle todos  zu löschen wäre cool - da man dies mündlich direkt mit alexa nicht machen kann (dazu braucht man die app - dann aber könnte über den cloudadapter gelöscht werden). einen punkt hinzufügen wäre nett. 
wie oben erwähnt nutze ich die todoliste nur, um einen neuen punkt über alexa einschreiben (ifttt) zu können - dies wird gesendet und landet in einer eigenen sql datenbank. erst  dadurch kann ich es in der vis sichbar machen und damit arbeiten - zum beispiel im auto, bevor ich austeige und nicht im heimbereich bin,, kommt eine nachricht mit meiner liste (hilfreich beim einkaufen) direkt aufs handy (html popup). ein bild zeigt handy, das andere ist die vis.

ps: habe gestern meine shellys bekommen - grins - bei diesem adapter bist du ja auch involviert.
![sql2](https://user-images.githubusercontent.com/18462890/46523795-18fa5800-c887-11e8-9bf3-9c34cfa164bc.png)
![sql](https://user-images.githubusercontent.com/18462890/46523796-18fa5800-c887-11e8-973d-928005bcbb21.png)

**Comment by Apollon77** [comment]
closed: Ein User hat ein neues issue aufgemacht und das habe ich geclosed mit refeenz auf dieses als duplicate :-)

> es geht mir gar nicht darum, etwas sinnvolles damit anzufangen (zu verarbeiten)- eher darum, die daten zu haben , damit sie angezeigt werden können.

Naja Anzeigen ist "was sinnvolles damit anfangen" :-) In welcher Forum müste man es denn speichern das Vis es sinnvoll anzeigen kann? Reicht JSON oder oder oder? Diese Infos fehlen mir und habe gerade wenig Zeit mich so tief in VIS reinzuarbeiten.

> alle todos zu löschen wäre cool - da man dies mündlich direkt mit alexa nicht machen kann (dazu braucht man die app - dann aber könnte über den cloudadapter gelöscht werden). einen punkt hinzufügen wäre nett.

Naja, das könnte man als State machen (macht das echt sinn? braucht man das so oft? oder als JavaScrit-Funktion die man nur von Skripten aus nutzen kann.
Ich tue mich schwer das alles als States anzulegen ... weil man es immer noch verstehen können muss und es sinn machen sollte ...

**Comment by liv-in-sky** [comment]
um es einfach zu halten -  ein json reicht völlig -  mehr muss es garnicht sein. ein unterpunkt im adapter mit todolist und einkaufliste und ein json dazu - das wär's
ifttt sendet die ganze liste als comma-seperated - ist blöd, da man in den todos keine kommas verwenden kann (in der app) - aber selbst eine solche liste mit kommas wäre cool - das bild zeigt:
arminTODOs ist die liste von ifttt - SQLArmin ist vom sqlserver - für diesen datenpunkt gibt es ein widget im vis (json-table)
![adapt](https://user-images.githubusercontent.com/18462890/46526332-3da5fe00-c88e-11e8-9064-bd972108ae39.png)

**Comment by ldittmar81** [comment]
Also... Alexa hat 2 Listen: Todos und Einkaufsliste. In der Liste werden Einträge gespeichert und haben ein Status true/false. Es würde sich also anbieten, wenn man unter dem Ordner Listen, die Unterordnern Todos & shopping_items hätte und darunter jeweils ein Objekt mit true/false.

Das wäre die eleganteste Lösung, denn dann könnte man im VIS, auch die erledigte Sachen darstellen und diese auch mal switchen (bsp.: Todo -> Fenster putzen ... das könnte dann wöchentlich automatisch wieder auf false gesetzt werden)

Nur eine JSON wäre auch ok, aber es wäre halt für den normalen User nicht so einfach zu handeln.

**Comment by Apollon77** [comment]
Die State id von einem Channel ist dann eine uuid und drunter gibts noch den Text des Todes/Liste als unter State und dein true/false. Und noch einen state zum löschen. Und irgendwie noch States zum anlegen von einem neuen Eintrag ...

Das ist nur wieder für vis so alles andere als sinnvoll zu gebrauchen. Und wegen der UUIDs die quasi dynamisch sind kannst du skriptnutzung effektiv vergessen.

**Comment by ldittmar81** [comment]
Dann wirklich als JSON... Die Listenobjekte müssten aber trotzdem 2 Status haben (Offen/Erledigt) und das müsste dann mit der Alexa synchronisiert werden. Außerdem müsste noch ein neu/gelöscht ebenfalls synchronisiert werden.  Wäre es dann so ein JSON?

{'Brot':false, 'Butter':true, 'Klopapier':false} -> und wenn da was neues rein kommt, wird es in der Liste hinzugefügt bzw wenn was nicht mehr da ist, wird es gelöscht?

**Comment by Apollon77** [comment]
Ääähm ... neeeeeeee enn JSON dann ist das der Read-Only content. zurück syncen per JSON ... neeeeeeeeee, das kann nur schieff gehen

**Comment by ldittmar81** [comment]
:laughing: Tja... aber so ganz von vis losgelöst, wäre es auch cool, wenn man es zB. in Material oder in ioGo zeigen könnte. Dafür müssten es aber Objekte (true/false) sein :thinking: Bezüglich UUIDs... man muss diese nicht Id im ioBroker nehmen... außerdem ist das kein Problem, wenn man Blockly nutzt :stuck_out_tongue:

Mit Objekte als Switch, könnte man auch ganz tolle Sachen machen. Beispiel Todo Liste. Aufgabe wird irgendwann abgehackt und 2 Wochen danach wird es automatisch auf false gestellt, so dass man wieder daran erinnert wird, dass es mal Zeit wird.

**Comment by fabiankrauss** [comment]
Ich fände es auch super wenn es integriert werden könnte. 👍

**Comment by Matten-Matten** [comment]
Ich würde das auch super finden, vieleicht auch in 2 bis drei unterschiedliche Objekte, einmal im json, einmal als einfache Liste mit Zeilenumbruch dazwischen und einmal in Ordnern mit einzelnen Objekten durchnummeriert, Bis max 30 Objekte oder so? -> Diese könnte man dann einzeln mit einem zusätzlichen löschen Objekt erstellen. Und ein einzelnes Objekt, welches beschreibbar ist um etwas der Liste hinzuzufügen.
Das wäre so meine Idee.
Gruß
Matten Matten

**Comment by Matten-Matten** [comment]
Ich würde das auch super finden, vieleicht auch in 2 bis drei unterschiedliche Objekte, einmal im json, einmal als einfache Liste mit Zeilenumbruch dazwischen und einmal in Ordnern mit einzelnen Objekten durchnummeriert, Bis max 30 Objekte oder so? -> Diese könnte man dann einzeln mit einem zusätzlichen löschen Objekt erstellen. Und ein einzelnes Objekt, welches beschreibbar ist um etwas der Liste hinzuzufügen.
Das wäre so meine Idee.
Gruß
Matten Matten
![IMG_20190726_133237](https://user-images.githubusercontent.com/32074970/61949156-2580a600-afaa-11e9-815f-69cb15eff2e8.jpg)

**Comment by LJSven** [comment]
Das ist im Moment noch nicht möglich, oder übersehe ich was? Ich würde es gut finden, daß wenn ich aus dem Haus gehe, mit die Liste per Telegram aufs Handy geschickt wird, oder an der Ausgangtür der Einkaufszettel gedruckt wird.

**Comment by liv-in-sky** [comment]
falls interesse: die listen kann man über ifttt bei änderung, punkt zugefügt,verändert oder gelöscht  an iobroker senden lassen - ein script schiebt dies dann  auf mein handy - ist nur eindimensional - also nur von alexa app zu iobroker

**Comment by LJSven** [comment]
Hast du ein "How-To"?

**Comment by liv-in-sky** [comment]
LJSven - mach doch einen thread im forum auf und setzt mich rein - dann erkläre ich es dir kurz

**Comment by LJSven** [comment]
Done

**Comment by Zefau** [comment]
@liv-in-sky @LJSven habt ihr einen Link zum Thread?

Versuche gerade die Thematik im alexa2 Adapter hinzuzufügen. Auslesen der Listen und das Hinzufügen funktioniert.
Leider scheitere ich aktuell noch am Aktualisieren und am Löschen. Funktioniert das mit IFTTT?

**Comment by liv-in-sky** [comment]
hallo zefau,
https://forum.iobroker.net/topic/25416/alexa-einkaufsliste-via-ifttt/6

**Comment by Zefau** [comment]
Habe die Funktionen für Listen nun in den Adapter (bei mir lokal) implementiert. Mit dem Merge der Dependency (siehe https://github.com/Apollon77/alexa-remote/pull/56), werde ich für das Repository einen Pull Request stellen.

So sieht's bei mir aus:
![image](https://user-images.githubusercontent.com/14368811/69900981-14daa500-137b-11ea-8e43-5b9319a90346.png)

sowie die List-Items:
![image](https://user-images.githubusercontent.com/14368811/69900987-21f79400-137b-11ea-81f5-9bc5f61e827b.png)

**Features**
- Listen werden ausgelesen
- neue Einträge können hinzugefügt werden
- bestehende Einträge (Text und Completed) können bearbeitet werden
- Einträge können gelöscht werden
- Änderungen direkt in Alexa werden in den Adapter synchronisiert (alle zuvor genannten Änderungen)

**Comment by Apollon77** [comment]
Merged, da ich auch gerade an Alexa 2 aktualisiere verbinde ich morgen den alexa2 Github mit der gitHub alexa-remote um schneller iterieren zu können. Damit ginge dein alexa2-PR dann! Also brauchst keine dep ändern, mache ich dann. Dann release ich es im gesamtpaket

**Comment by Zefau** [comment]
alles klar

**Comment by liv-in-sky** [comment]
ihr seid toll :-)

**Comment by Apollon77** [comment]
bzw ... hab jetzt mal alles aktuslisiert ... versuch mal ... aber bitte deinen Fork rebasen bzw mergen wie nötig.
PS: Hast Du Telegram? Haben da eine Dev Gruppe :-) Lust?

@liv-in-sky Aber bitte LAAANGSAAM!! GitHub version ist für die nächsten Tage extrem experimentell und kann komplett kaputt sein. Melde mich im Forum wenn Testbereit :-)

**Comment by liv-in-sky** [comment]
jaja - alles klar - freu mich nur, das es kommen wird - irgendwann !

**Comment by Zefau** [comment]
An der Telegram Gruppe hätte ich Lust. Zefau ist mein Nickname dort.

**Comment by Zefau** [comment]
Hab die v2.7.0 von Github auf meiner Testumgebung installiert. Der Start funktioniert soweit problemlos.

Das Durchtesten der Listen ebenfalls. Ohne Fehler gelingt das Folgende:
- (in ioBroker) das Erstellen eines neuen Listeneintrags
- (in ioBroker) Bearbeiten des States `completed` und des States `value` eines Listeneintrags
- (in ioBroker) Listeneintrag löschen
- (in Alexa) das Erstellen eines neuen Listeneintrags
- (in Alexa) Bearbeiten des States `completed` und des States `value` eines Listeneintrags
- (in Alexa) Listeneintrag löschen

Habe ich einen Testfall vergessen?

**Comment by Zefau** [comment]
@Apollon77 kannst du [main.js#L2525](https://github.com/Apollon77/ioBroker.alexa2/blob/master/main.js#L2525) bitte noch auf `adapter.log.debug` umstellen?

https://github.com/Apollon77/ioBroker.alexa2/blob/31a7f1d33e0ff942d8d298de0b9641f099e7853b/main.js#L2525

**Comment by Apollon77** [comment]
sure

**Comment by Zefau** [comment]
@Apollon77 wie kommst du voran? Brauchst du noch Unterstützung? Ich nutze die aktuelle Github Version seither problemlos.

**Comment by Apollon77** [comment]
Abgelenkt. Bin aber jetzt noch 2 Tage krank geschrieben. Mal schauen. 

Und credits sind bei mir lokal natürlich schon drin ;-) Selbstverständlichkeit!

**Comment by Apollon77** [comment]
Should be fixed in GitHub version 3.0.0 ... please check and give feedback (here and/or https://forum.iobroker.net/topic/27930/test-adapter-alexa2-3-0-x)
