### ISSUE TITLE
Routinen Datenpunkte werden nicht aktualisiert

### ISSUE THREAD

**Issue by ymicky** [Apollon77/ioBroker.alexa2#310]
Wenn nach dem Codewort kurz gewartet und dann eine Routine über Alexa gestartet wird, aktualisiert sich der entsprechende Datenpunkt der Routine.
Hierauf kann also getriggert werden.
Wenn jedoch das Codewort mit dem Rest des Satzes direkt ausgesprochen wird, werden die Datenpunkte nicht aktualisiert.
Auch der DP summary hat beim zweiten Szenario noch das Wort Alexa drin stehen

**Comment by Apollon77** [comment]
Welche Adapter Version?

**Comment by ymicky** [comment]
Schaue ich heute Abend mal nach

**Comment by ymicky** [comment]
@Apollon77 
Die installierte Version ist 2.6.4

**Comment by padrino-x** [comment]
Hi, kann ich mit 2.6.4 teils bestätigen. :)
Da ich kein Android Gerät habe auf dem die Alexa App Routinen unterstützt, kann ich nur auf die die drei default Rountinen zugreifen.

- "Gute Nacht" wird aktualisiert
- "Guten Morgen" wird es nicht
- "preconfigured:alarm_dismissed_with_condition_preconfigured_routine" kann ich nicht testen, da ich nicht weiß, wie man diese aufruft. =)

**Comment by Apollon77** [comment]
Bitte Adapter auf Debug schalten und Log von solchen Sprachkommandos auf dem Logfile senden

**Comment by Apollon77** [comment]
Schau bitte mal in den Routineneinstellungen ... kann es sein das "Guten morgen" keinen Namen hat? Dann zeigt die App eine Option "Routinennamen eingeben" an und in Alexa2 steht als Name der Routine **nicht** "Guten morgen" sondern was englisches

**Comment by Apollon77** [comment]
Please test with 3.0.3, reopen or comment if still not working

**Comment by dunbakkie** [comment]
Hi, I have the same problems with 3.0.7

**Comment by Apollon77** [comment]
No you don't ... you have this problem: https://github.com/Apollon77/ioBroker.alexa2/issues/362

Amazon broke the push connection and so no push events are trsnsmitted for some users at the moment. Hopefully they fix it soon

**Comment by dunbakkie** [comment]
Ah ok thanks. Great work by the way.

Outlook für Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by Apollon77** [comment]
was amazon problem
