### ISSUE TITLE
Echo Flex

### ISSUE THREAD

**Issue by Pocky2507** [Apollon77/ioBroker.alexa2#311]
Moin apollon77,
kannst Du da etwas mit anfangen?
Ist der neue Echo Flex.

`(20710) Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted`

`(20710)     Device-type:A3VRME03NAXFUB (LEMUR_ALPHA,TUNE_IN,EARCONS,ALEXA_PRESENCE,AMAZON_MUSIC,TUPLE,DREAM_TRAINING,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,FLASH_BRIEFING,DIALOG_INTERFACE_VERSION,PAIR_REMOTE,SOUND_SETTINGS,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,UPDATE_WIFI,AUDIBLE,SLEEP,VOLUME_SETTING,GOLDFISH,CHANGE_NAME,SALMON,GADGETS,ACTIVE_AFTER_FRO,PANDORA,ASCENDING_ALARM_VOLUME,PAIR_BT_SINK,KINDLE_BOOKS,VOICE_TRAINING,DS_VOLUME_SETTING,SUPPORT_CALENDAR_ALERT,TAHOE_BYOD,FAR_FIELD_WAKE_WORD,I_HEART_RADIO,SUPPORTS_SOFTWARE_VERSION,PAIR_BT_SOURCE,TUPLE_CATEGORY_A,ALLOW_LOG_UPLOAD,POPTART,SET_LOCALE,TIMERS_AND_ALARMS,BT_PAIRING_FLOW_V2,REQUIRES_OOBE_FOR_SETUP,CUSTOM_ALARM_TONE,REMINDERS,MUSIC_SKILL,DEREGISTER_DEVICE,PERSISTENT_CONNECTION,MICROPHONE,DISPLAY_BRIGHTNESS_ADJUST,AUDIO_PLAYER)`

**Comment by Apollon77** [comment]
Was kann der denn alles so? gehen die Kommandos?

**Comment by Pocky2507** [comment]
Der kann alles was auch ein normaler Echo kann.
Kommandos gehen.
Allerdings hat er unten einen USB Anschluss wo weitere Amazon Geräte eingesteckt werden können.
In meinem Fall ein Bewegungsmelder.
Bei den Routinen werden allerding unknown Einträge angezeigt.

 
![Bildschirmfoto-20191115091952-1055x297](https://user-images.githubusercontent.com/22934504/68928224-dabdb080-0789-11ea-98cb-f97e5adb43ae.png)

**Comment by Apollon77** [comment]
Interessant. Schickst Du mitr mal ein Debug.Log?

Bitte Adapter auf Debug stellen (Instanzen -> Expertenmodus -> Spalte Logstufe, da "debug"

Brauche dann volles log vo  dem Start (ist einiges) aus dem Logfile auf der Platte (/opt/iobroker/log ...)

AM besten per email an iobroker@fischer-ka.de und bitte auf dieses Issue verweisen

**Comment by Pocky2507** [comment]
Mail ist raus.

**Comment by Apollon77** [comment]
Danke, sobald er js-controller 2.0 kram durch ist röume ich bei meinen anderen Adaptern auf :-)

**Comment by Pocky2507** [comment]
Offtopic ON
Der js-controller läuft hier mit 2.44 Perfekt.
Offtopic OFF

**Comment by burghardp** [comment]
Hallo Apollon77, hab heute den neuen Echo Flex bekommen. Er wird auch vom Alexa2 Adapter (Version 2.6.4) erkannt. Leider werden nicht alle Komandos wie bei den anderen Echo Geräten angezeigt. Mache ich da was falsch?
Hier die Liste der Commands, die unter Objekte zum Echo Flex im ioBroker angezeigt werden.
![Echo Flex Commands](https://user-images.githubusercontent.com/58266736/69741141-d0f95d00-113a-11ea-95bc-8dfb06ca0b60.PNG)

**Comment by Apollon77** [comment]
Mal Objekte Reloaded? Was steht im Log wenn Du Adapter startest?

**Comment by burghardp** [comment]
Ja, das war's. Sorry, dummer Anfängerfehler. Vielen Dank für die schnelle Hilfe.

**Comment by Moormerlander** [comment]
Gibt es schon Fortschritte zum Thema USB-Devices (Bewegungsmelder und Nachtlicht) für den Echo Flex? Kann man die Erweiterungen auch über den Adapter ansteuern bzw. Motion triggern?

**Comment by burghardp** [comment]
Der Bewegungsmelder ist heute gekommen. Ist im ioBroker unter Objekte / alexa2.0.Smart-Home-Devices sichtbar. Mal schauen was man damit machen kann.
![Bewegungsmelder](https://user-images.githubusercontent.com/58266736/70053423-b52c0600-15d5-11ea-8c25-cffb3a90ce65.JPG)

**Comment by Apollon77** [comment]
Flex kommt mit nächstem Update rein, Die Bewegungsmelder-Werte werden sich wie andere Dinge nicht automatisch aktualisieren. Musst Du querien ...

**Comment by Apollon77** [comment]
Should be fixed in GitHub version 3.0.0 ... please check and give feedback (here and/or https://forum.iobroker.net/topic/27930/test-adapter-alexa2-3-0-x)
