### ISSUE TITLE
Feature Request: Stimmenerkennung

### ISSUE THREAD

**Issue by Chris-1808** [Apollon77/ioBroker.alexa2#312]
Hallo zusammen,

in der Alexa App habe ich gelesen das es jetzt auch für 3rd party Skills die Möglichkeit besteht die Stimmerkennung zu benutzen.
Wäre super wenn das in den Adapter eingebunden werden könnte.
Ich denke da würde es viele Möglichkeiten geben den Adapter bzw. Alexa wesentlich effizienter zu nutzen.
Z.B. Wenn das Kommando "Gute Nacht" gesagt wird, könnte ich innerhalb eines Skriptes unterschiedliche Abläufe durchführen.

Man könnte das z.B. über ein Objekt in History machen in dem der Name/ID des Sprechers des letzten Kommandos gespeichert ist. Somit könnte man das sehr einfach in die Skripte einbinden.

Was haltet Ihr davon?

Gruß,
Chris

**Comment by Apollon77** [comment]
Link bitte, letzte Tests haben aber ergeben das die Infos nicht bei der App ankommen, maximal bei dem Skill.

**Comment by Chris-1808** [comment]
Ging ja super schnell ;-)

Hier der Link zur Developer Seite [Add Personalization to Your Skill](https://developer.amazon.com/docs/custom-skills/add-personalization-to-your-skill.html).
Geht hier zwar um die Skills, aber ich hoffe dass das auch auf deinen Adapter adaptierbar wäre.

**Comment by Apollon77** [comment]
verified ... Infos zur Stimmenerkennung landen weiterhin nicht in der app, daher keine infos verfügbar
