### ISSUE TITLE
Feature request: zusätzliches item "Wecktage"

### ISSUE THREAD

**Issue by jensgulow** [Apollon77/ioBroker.alexa2#313]
Die Wecker in den Alexa-Devices haben gegebenenfalls programmierte Wiederholungen - wochentags, am Wochenende, montags oder oder oder.
Diese Informationen sind unter "recurring pattern" abgelegt (z.B. XXXX-WE für Wochenende oder XXXX-X1 für montags).
Ich hätte nun gerne diese Information als zusätzliches item für jeden Alarm und MusicAlarm.
![image](https://user-images.githubusercontent.com/5845040/69010320-ce3e8100-095e-11ea-937a-1e60f6f543d5.png)
....hier unterhalb der Zeile triggered

**Comment by gemsli** [comment]
Wäre es so auch möglich, den Tag mit anzugeben, für welchen der Wecker gestellt ist?

Wenn ich beispielsweise einen Wecker für übermorgen um soundsoviel Uhr stelle, dann erscheint im Adapter zwar die korrekte Uhrzeit und enabled steht auf true - feststellen, ob der Wecker aber tatsächlich "heute" oder eben an einem anderen Tag klingelt, kann man aber anscheinend nicht, was entsprechend "vorplanende" Skripte in Abhängigkeit von tatsächlich auslösenden Weckern erschwert.

Für die reminder gilt das natürlich auch.

**Comment by jensgulow** [comment]
Das wäre mein Wunsch.. Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [Apollon77/ioBroker.alexa2] Feature request: zusätzliches item "Wecktage" (#313)Von: gemsli An: "Apollon77/ioBroker.alexa2" Cc: jensgulow ,Author Wäre es so auch möglich, den Tag mit anzugeben, für welchen der Wecker gestellt ist?

Wenn ich beispielsweise einen Wecker für übermorgen um soundsoviel Uhr stelle, dann erscheint im Adapter zwar die korrekte Uhrzeit und enabled steht auf true - feststellen, ob der Wecker aber tatsächlich "heute" oder eben an einem anderen Tag klingelt, kann man aber anscheinend nicht, was entsprechend "vorplanende" Skripte in Abhängigkeit von tatsächlich auslösenden Weckern erschwert.

Für die reminder gilt das natürlich auch.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Apollon77/ioBroker.alexa2/issues/313?email_source=notifications\u0026email_token=ABMTAMDSNVDYJPNRHOF2IK3Q27LIXA5CNFSM4JOKSD72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHYTYYA#issuecomment-569457760",

"url": "https://github.com/Apollon77/ioBroker.alexa2/issues/313?email_source=notifications\u0026email_token=ABMTAMDSNVDYJPNRHOF2IK3Q27LIXA5CNFSM4JOKSD72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHYTYYA#issuecomment-569457760",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Apollon77** [comment]
Next version will expose more infos on recurring and a "nextTriggerTimestamp" state with the next calculated trigger date and time as timestamp

**Comment by Apollon77** [comment]
have fun https://forum.iobroker.net/post/824793
