### ISSUE TITLE
Info for developer

### ISSUE THREAD

**Issue by ihavenonick** [Apollon77/ioBroker.alexa2#314]
Das einzig neue Device ist eine Fitbit Versa2 und seit da kommt diese Meldung:

alexa2.0 | 2019-11-19 03:33:04.007 | info | (COMPACT) Alexa-Push-Connection Unknown Command  PUSH_DELETE_DOPPLER_ACTIVITIES - send to Developer:  {"destinationUserId":"A2FUFEDJDS9VX0","targetCustomerId":"A2FUFEDJDS9
-- | -- | -- | --

**Comment by Zefau** [comment]
Habe den gleichen Fehler mit anderen IDs (mit v2.7.0):
```
2019-12-20 03:52:34.827 - info: alexa2.0 (2237)
Alexa-Push-Connection Unknown Command PUSH_DELETE_DOPPLER_ACTIVITIES - send to Developer:
{
   "destinationUserId":"A12X09QDMWISGT",
   "targetCustomerId":"A12X09QDMWISGT",
   "deleteBeforeTimeInclusive":1565567999000,
   "dopplerId":{
      "deviceSerialNumber":null,
      "deviceType":null
   }
}
```

Um 3:52 sehr sehr oft im Log. Immer mit anderer `deleteBeforeTimeInclusive`.

**Comment by Apollon77** [comment]
Should be fixed in GitHub version 3.0.0 ... please check and give feedback (here and/or https://forum.iobroker.net/topic/27930/test-adapter-alexa2-3-0-x)
