### ISSUE TITLE
Future: Button für Rufannahme 

### ISSUE THREAD

**Issue by Knallochse** [Apollon77/ioBroker.alexa2#315]
Ich würde mir einen Button zur Rufannahme  (Alexa, Anruf annehmen) wünschen.
Ich benutze für meine Türsprechanlage einen Gigaset L800HX Dect Lautsprecher mit Alexa Funktion, welcher unter Objekte die gleichen Datenpunkte wie ein Echo Gerät anzeigt.
Ich möchte gern die Rufannahme über ein Tablet mit der VIS steuern.

**Comment by Apollon77** [comment]
Kann man das per Alexa App machen? Wenn nein, dann geht es auch im Adapter leider nicht. Bitte neu öffnen wenn es in der App geht mit Details dazu

**Comment by Knallochse** [comment]
In der Alexa App unter IOS gibt es eine Rufannahme für Gespräche.
![Alexa2](https://user-images.githubusercontent.com/36857242/69430926-f0594a00-0d36-11ea-8305-a938d9a9f119.jpg)
![Alexa1](https://user-images.githubusercontent.com/36857242/69430927-f0594a00-0d36-11ea-86cf-c38b17c13ab5.jpg)

**Comment by Apollon77** [comment]
Ja dann nimmst DU es aber auf diesem Device an, oder?

Das läuft wenn über die Mobile App Push API ... das sind ganz andere Wege :-( Wüsste gerade nicht wie ich da ran kommen soll
