### ISSUE TITLE
Adapter unable to play local MP3.

### ISSUE THREAD

**Issue by FlexerJR** [Apollon77/ioBroker.alexa2#317]
Hi Appolon, I'm trying to play MP3 files on a NAS via Alexa. Unfortunately this is not possible. Here is the command

<speak>
    test
    <audio src="http://192.168.178.200:8082/mp3-sounds/test.mp3"/> 
</speak>

I have tried the instructions under Audio.

https://developer.amazon.com/de/docs/custom-skills/speech-synthesis-markup-language-ssml-reference.html#audio

**Comment by Apollon77** [comment]
Not supported by the "speak/SSML stuff which is allowed via the App, so for now no chance. It cpuld be possible in a skill or such, so maybe open issue at "iot" to possibly include into the custom skill

**Comment by maddingamer** [comment]
Any updates on this?

**Comment by Apollon77** [comment]
Not that I would know
