### ISSUE TITLE
Feature: Töne in in Alexa2 adapter abspielen

### ISSUE THREAD

**Issue by Marty56** [Apollon77/ioBroker.alexa2#319]
Alexa unterstützt jetzt ja auch in den Routinen die Ausgabe von Tönen. 
Es wäre schön, wenn man diese Töne durch den Alexa Adapter abspielen könnte.

**Comment by Apollon77** [comment]
´´´
{
                        "@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
                        "type": "Alexa.Sound",
                        "skillId": "amzn1.ask.1p.sound",
                        "operationPayload": {
                            "customerId": "A3NSX4MMJVG96V",
                            "deviceType": "ALEXA_CURRENT_DEVICE_TYPE",
                            "deviceSerialNumber": "ALEXA_CURRENT_DSN",
                            "soundStringId": "bell_02",
                            "locale": "de-DE"
                        },
                        "name": null
                    }
´´´

**Comment by Marty56** [comment]
Verstehe die Antwort nicht. Aber interpretiere das jetzt so, dass Du prinzipiell einen Weg gefunden hast und es bald ein Update des Adapters geben wird, der Töne abspielen kann.

**Comment by Apollon77** [comment]
Ja wie es gehen kann weiß ich. Update mal schauen ;-)

**Comment by Marty56** [comment]
sehr schön. Frohe Weihnachten

**Comment by Apollon77** [comment]
Danke. Gibt heute Abend neue Version ... siehe Forum. Ziel ist erstmal die bestandsfunktionen alle wieder laufen zu haben. Neues danach.

**Comment by Apollon77** [comment]
Commands.sound will be available in next version

**Comment by Apollon77** [comment]
see https://forum.iobroker.net/post/823454
