### ISSUE TITLE
Position of Login Data field description with Admin3

### ISSUE THREAD

**Issue by BuZZy1337** [Apollon77/ioBroker.alexa2#32]
When opening the Config screen the Descriptions of the Login-Fields are not on the correct position.

![screenshot - 25 07 2018 15_12_42](https://user-images.githubusercontent.com/6979405/43203307-260cd4b0-901e-11e8-9776-2a7f7cea52f7.png)

**Comment by Apollon77** [comment]
welche version? Aktuelle 0.3.0? Da wurde das eigentlich gefixt

**Comment by Apollon77** [comment]
Btte reopen wenn noch offen

**Comment by BuZZy1337** [comment]
Whoops.. Ja funktioniert jetzt nach update. :+1:
