### ISSUE TITLE
Welche App ist aktiv

### ISSUE THREAD

**Issue by robig** [Apollon77/ioBroker.alexa2#323]
Hallo,

Wenn ich TuneIn nutze wird unter alexa2.0.Echo-Devices.Serialnumber.Player.* korrekt angezeigt was abgespielt wird.
WIr nutzen jedoch oft die Radio App des jew. Radiosenders auf dem Echo Dot.
Wie kann ich erkennen, ob eine App läuft und dies darstellen?

**Comment by Apollon77** [comment]
Du meinst ein Skill? Ich fürchte gar nicht ... oder zeigt es die Alexa-App bei Dir an? Bie mir aktuell nicht (Sie sagt beim versuch lautstärke zu ändern sogar teilweise "wird nichts gespielt". Wenn es Deine App anzeigt (mehr als nur eine "Karte"), dann bitte reopen und screenshots
