### ISSUE TITLE
Echo Show 8

### ISSUE THREAD

**Issue by ingod68** [Apollon77/ioBroker.alexa2#324]
Echo Show 8 is deviceType="unknown"
and has no Commands/Player/Routines in Objects.

**Comment by Apollon77** [comment]
Please provide devicetype and capabilities from info states or logfile. No commands isstrange

**Comment by ingod68** [comment]
deviceType = A1Z88NGR2BK6A2
deviceTypeString = Unknown

capabilities = AUDIBLE,FACTORY_RESET_DEVICE,SHARKNADO,ASCENDING_ALARM_VOLUME,ALLOW_LOG_UPLOAD,FLASH_BRIEFING,TUPLE,CHANGE_NAME,TUNE_IN,PERSISTENT_CONNECTION,TUPLE_CATEGORY_B,SALMON,EARCONS,GOLDFISH,MUSIC_SKILL,DIALOG_INTERFACE_VERSION,SUPPORTS_SOFTWARE_VERSION,VOLUME_SETTING,POPTART,SET_LOCALE,MICROPHONE,SOUND_SETTINGS,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,DREAM_TRAINING,REMINDERS,DS_VOLUME_SETTING,LEMUR_ALPHA,AUDIO_PLAYER,AMAZON_MUSIC,SLEEP,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,PANDORA,CUSTOM_ALARM_TONE,VOICE_TRAINING,KINDLE_BOOKS,I_HEART_RADIO,TIMERS_AND_ALARMS,SUPPORT_CALENDAR_ALERT,PAIR_BT_SINK,FAR_FIELD_WAKE_WORD

**Comment by ingod68** [comment]
OK, added 

'A1Z88NGR2BK6A2':   {name: 'Echo Show', commandSupport: true, icon: 'icons/echo_show.png'},

after Line 120 in "main.js" and it works. :-)

**Comment by Apollon77** [comment]
Should be fixed in GitHub version 3.0.0 ... please check and give feedback (here and/or https://forum.iobroker.net/topic/27930/test-adapter-alexa2-3-0-x)
