### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by smarthomemf** [Apollon77/ioBroker.alexa2#329]
seit ein paar Wochen bekomme ich den Adapter nicht zum laufen.
Der Fehler im Log
`

host.ioBrokernuc | 2019-12-08 13:05:14.357 | info | Restart adapter system.adapter.alexa2.0 because enabled
-- | -- | -- | --
host.ioBrokernuc | 2019-12-08 13:05:14.357 | info | instance system.adapter.alexa2.0 terminated with code 0 (NO_ERROR)
host.ioBrokernuc | 2019-12-08 13:05:14.356 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.ioBrokernuc | 2019-12-08 13:05:14.356 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1143:12)
host.ioBrokernuc | 2019-12-08 13:05:14.356 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:203:15)
host.ioBrokernuc | 2019-12-08 13:05:14.356 | error | Caught by controller[0]: at IncomingMessage.res.on (/opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:752:58)
host.ioBrokernuc | 2019-12-08 13:05:14.356 | error | Caught by controller[0]: at alexa.querySmarthomeDevices (/opt/iobroker/node_modules/iobroker.alexa2/main.js:607:13)
host.ioBrokernuc | 2019-12-08 13:05:14.356 | error | Caught by controller[0]: at updateSmarthomeDeviceStates (/opt/iobroker/node_modules/iobroker.alexa2/main.js:796:58)
host.ioBrokernuc | 2019-12-08 13:05:14.356 | error | Caught by controller[0]: at handleObject (/opt/iobroker/node_modules/iobroker.alexa2/main.js:748:37)
host.ioBrokernuc | 2019-12-08 13:05:14.355 | error | Caught by controller[0]: TypeError: native.valueMap.indexOf is not a function
alexa2.0 | 2019-12-08 13:05:13.607 | info | (27466) Terminated (NO_ERROR): Without reason
alexa2.0 | 2019-12-08 13:05:13.606 | info | (27466) terminating
alexa2.0 | 2019-12-08 13:05:13.585 | error | (27466) TypeError: native.valueMap.indexOf is not a function at handleObject (/opt/iobroker/node_modules/iobroker.alexa2/main.js:748:37) at updateSmarthomeDeviceStates (/opt/iobroker/node_modu
alexa2.0 | 2019-12-08 13:05:13.585 | error | (27466) uncaught exception: native.valueMap.indexOf is not a function
alexa2.0 | 2019-12-08 13:05:13.581 | warn | (27466) Exception: TypeError: native.valueMap.indexOf is not a function

`
Danke

**Comment by Apollon77** [comment]
known, will be fixed in next version

**Comment by Apollon77** [comment]
Workaround could be https://github.com/Apollon77/ioBroker.alexa2/pull/294/files ... but no real solution

**Comment by Apollon77** [comment]
Should be fixed in GitHub version 3.0.0 ... please check and give feedback (here and/or https://forum.iobroker.net/topic/27930/test-adapter-alexa2-3-0-x)
