### ISSUE TITLE
Neu erstellte Routinen erscheinen mit der Bezeichnung "unknown"

### ISSUE THREAD

**Issue by Blackmytj** [Apollon77/ioBroker.alexa2#332]
Seit dem letzen Update der Alexa App auf Mobile Geräten muss bei neu erstellen Routinen ein extra Name eingegeben werden.
Die neu erstellen Routinen erscheinen im Adapter mit der Bezeichnung "unknown"

**Comment by Apollon77** [comment]
Bitte Debug Logs vom Adapter start posten oder an iobroker@fischer-ka.de senden ... alternativ ein Screenshot erst einmal. Bei mir kommen nur neue spezielle Routinen mit Unknown, aber eigene mit einem namen

**Comment by Blackmytj** [comment]
Was meinst du mit speziellen Routinen ? Die bereits erstellten Routinen in der Alexa App sind davon nicht betroffen, nur wenn neue angelegt werden. Bei neu angelegten ist seit dem App Update eine Beschreibung Pflicht.

![Log Objekte](https://user-images.githubusercontent.com/58741706/70685926-1bd2b300-1cab-11ea-9b40-c167f31a1b8b.png)
![Log Adapter](https://user-images.githubusercontent.com/58741706/70685928-1bd2b300-1cab-11ea-847d-1a72554e2838.png)
![IMG_1291](https://user-images.githubusercontent.com/58741706/70686035-5dfbf480-1cab-11ea-8b37-f33dbb5a17c1.jpeg)
![IMG_1292](https://user-images.githubusercontent.com/58741706/70686036-5dfbf480-1cab-11ea-9936-138b2612e5f3.png)

**Comment by Apollon77** [comment]
Ok. Komisch. Dann brauche ich das debug log vom Adapter Start. Am besten mit Verweis auf das issue an iobroker@fischer-ka.de

Debug log: in admin: Instanzen - expertenmodus- Spalte ligature. 

Log bitte aus dem logfile auf disk unter /opt/iobroker/log... rauskopieren als Text. Danke

**Comment by Blackmytj** [comment]
E-Mail ist raus. Sollte etwas nicht passen bitte nochmals melden.
Achse noch zur Info, Adapter wurde natürlich auch schonmal neu installiert

**Comment by Millerdry** [comment]
Hi,
gibt es zu dem Problem schon was neues ?

Gruß Miller

**Comment by Blackmytj** [comment]
> Hi,
> gibt es zu dem Problem schon was neues ?
> 
> Gruß Miller

Hast du das selbe Problem ?
Ich warte auch noch auf Antwort :-)

**Comment by JB1985** [comment]
Haben vermutlich alle seit dem Update der Alexa Geräte. Habe auch das Problem und warte sehnsüchtig nach einem Fix.

**Comment by Millerdry** [comment]
> > Hi,
> > gibt es zu dem Problem schon was neues ?
> > Gruß Miller
> 
> Hast du das selbe Problem ?
> Ich warte auch noch auf Antwort :-)

Ja genau das gleiche, auch aktualisieren sich die Routinen nicht.

Aber ich seit dem Update der Geräte mit dem neuen feature einen eigenen Namen anzulegen, dürften eigentlich alle das Problem haben, wie @JB1985 schon sagte.

Es fällt nicht auf, wenn man an der Routine nichts machen will.

Hatte auch versucht, einen eigenen Namen zu vergeben, doch auch die werden nach einem Neustart des Adapters wieder mit "Unknown" überschrieben.

**Comment by Apollon77** [comment]
Steht recht weit oben auf der Liste. Der Tag hat halt nur 24h und ein großer Teil davon ist dem Real Life vorbehalten ... in der restlichen Zeit tue ich mein bestes ...

**Comment by Blackmytj** [comment]
> Steht recht weit oben auf der Liste. Der Tag hat halt nur 24h und ein großer Teil davon ist dem Real Life vorbehalten ... in der restlichen Zeit tue ich mein bestes ...

Das sollte von meiner Seite aus keine Kritik sein. Finde es top das du dich überhaupt drum kümmerst. 
Waren meine Logs ausreichend ?

**Comment by Apollon77** [comment]
Bin dran, hab die Ursache, denke habe bald GitHub version. Melde mich dann nochmals

**Comment by Blackmytj** [comment]
Super danke, freu mich schon drauf

**Comment by Millerdry** [comment]
> Steht recht weit oben auf der Liste. Der Tag hat halt nur 24h und ein großer Teil davon ist dem Real Life vorbehalten ... in der restlichen Zeit tue ich mein bestes ...

Alles Gut, wir als user sind ja froh das sich eine darum kümmert.

Vielen Dank dafür.

**Comment by Apollon77** [comment]
Should be fixed in GitHub version 3.0.0 ... please check and give feedback (here and/or https://forum.iobroker.net/topic/27930/test-adapter-alexa2-3-0-x)

**Comment by Blackmytj** [comment]
Super :-) Wie kann ich die Testversion einspielen ?

**Comment by Apollon77** [comment]
Admin, Adapter, oben Button mit GitHub Icon (Custom install), dort alexa2 wählen ... installieren. Dann instanz manuell neu starten

**Comment by JB1985** [comment]
Danke! Das Problem hier scheint behoben zu sein. Ich sehe kein "unknown" mehr bei den Routinen.

**Comment by Apollon77** [comment]
Bitte auch prüfen das der state auf true geht wenn du die Routine ansprichst.

**Comment by Millerdry** [comment]
Super vielen Dank @Apollon77 ,
funktioniert wieder...
Kein "Unknown" mehr und der State der Routinen ändert sich.

Nochmals Danke und schöne Feiertage...

**Comment by botak13** [comment]
Hallo.

Ich weiß das Problem ist schon etwas länger gelöst aber kann es sein das es bei einer Routine die als Auslöser den Echo Button hat immer noch das Problem besteht?
Wenn ich z.B. eine Routine erstelle welche ein Sprachbefehl als Auslöser hat funktioniert alles perfekt..

Viele Grüße.
