### ISSUE TITLE
Placement of "online" in objects tree

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#335]
I wonder, shouldn't/couldn't

alexa2.0.Echo-Devices.XXXX.online

be (in)

alexa2.0.Echo-Devices.XXXX.Info.online

**Comment by Apollon77** [comment]
why? Beside changing it would be a breaking change, the info objects were planned to be really additional infos only

**Comment by padrino-x** [comment]
Well, I thought "online yes/no" would be an "info".
Sorry, for asking/suggesting.

**Comment by Apollon77** [comment]
Np each question is allowed ;-)
