### ISSUE TITLE
targetSetpoint Änderung nicht möglich

### ISSUE THREAD

**Issue by Hans-Zwiesel** [Apollon77/ioBroker.alexa2#338]
Hallo,
alexa2.0 Vers. 3.0.3
Wenn ich einen Smart-Home-Device/targetSetpoint mit js 
**setState**("alexa2.0.Smart-Home-Devices.49a600d7-1beb-4f31-8d0f-75c4c148f433.targetSetpoint",22,true)
ändere, dann sehe ich die Änderung in der Objekt Ansicht, jedoch nach 1 oder 2 Minuten ist der Wert wieder wie vor der Änderung.

Wenn ich diesen targetSetpoint in der Objekt Ansicht manuell ändere, dann bleibt die Änderung.

Wäre sehr schön, wenn jemand dafür eine Lösung haben würde.
Vielen Dank

**Comment by Apollon77** [comment]
Bedienfehler!
Kommandos immer mit ack= false (letzter Paraeter9 senden, sonst geht das nicht raus als Kommando

**Comment by Hans-Zwiesel** [comment]
Ich hatte schon gehofft, dass Du antwortest, denn das passt immer!
Vielen Dank.
