### ISSUE TITLE
Bitte wieder Information anzeigen lassen

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#34]
If communication with alexa works
Alexa Cookie
Alexa CSRF

Da ich den alexa2 adapter noch nicht zu 100% übernehmen kann muss ich noch ein script nebenher laufen lassen und da benötige ich Alexa Cookie und Alexa CSRF

Gruß
Matten

**Comment by Matten-Matten** [comment]
alles wieder zurück. das wird angezeigt wenn die Adapterinstanz hinzugefügt wird.

**Comment by Apollon77** [comment]
steht unter info.cookie und info-csrf zur Verfügung

**Comment by Matten-Matten** [comment]
ja hatte aber alle Objekte gelöscht und ein adapter instanz start reicht nicht. info tauchte erst nach der neuinstallation der alexa2.0 instanz wieder auf

**Comment by Apollon77** [comment]
ääähm ja, die "info." sind Instanzobjekte und sind dann weg. In dem Fall "zuviel" gelöscht :-)
