### ISSUE TITLE
Timer von Alexa als DP

### ISSUE THREAD

**Issue by skokarl** [Apollon77/ioBroker.alexa2#340]
Ist es möglich ein DP zu erstellen der die Restlaufzeit in min von einem Alexa Timer anzeigt ?
Damit wäre es möglich einen über Alexa gestarteten Timer in einer View zu visualisieren.

**Comment by sigi2345** [comment]
https://forum.iobroker.net/topic/23694/vorage-blockly-alexa-timer-sichtbar-machen-vis

**Comment by padrino-x** [comment]
Wunsch gibt es schon, Bug #226 .
https://github.com/Apollon77/ioBroker.alexa2/issues/226
Am Besten dort ein "like", eröht due Chancen. =)
