### ISSUE TITLE
Adapter is not starting since update to 3.0.5

### ISSUE THREAD

**Issue by Chris-1808** [Apollon77/ioBroker.alexa2#343]
Hi all,

few minutes ago I updated my Alexa2 adapter, but unfortunately since this it is not starting anymore.
I have a screenshot attached.
![error](https://user-images.githubusercontent.com/57795092/71544374-01712880-297f-11ea-993c-c4dc40b36320.png)

Systeminformation:
Betriebssystem linux
Architektur arm
CPUs 4
Geschwindigkeit 600 MHz
Modell ARMv7 Processor rev 3 (v7l)
RAM 3.86 GB
System Betriebszeit 12 T. 22:26:09
Node.js v10.18.0
NPM 6.13.4
Festplatte Größe 28.98 GB
Festplatte frei 23.8 GB
Anzahl der Adapter 262
Betriebszeit 00:09:54
Aktive Instanzen 12

JS controller: 2.1.1

Hope somebody can help me with that.

Regards,
Chris

**Comment by Apollon77** [comment]
Please install again. Something went wrong during install it seems

**Comment by Chris-1808** [comment]
Many thanks, after reinstalling the adapter it is running fine.
Wish you a happy new year.
