### ISSUE TITLE
Frage zum Adapter

### ISSUE THREAD

**Issue by scripthase** [Apollon77/ioBroker.alexa2#344]
Schönen guten Abend,
ich weiß nicht, ob ich hier richtig bin, aber ich möchte eine Frage stellen.

Ich bin relativ neu in der SmartHome-Szene und möchte gerne diesen Adapter mit meinem Echo Dot verwenden. Da die Cloudlösung, welche von ioBroker angeboten wird, relativ in der Anzahl von Geräten beschränkt ist, würde ich gerne diesen Adapter verwenden.

Meine Frage ist, ob ich zum Beispiel sagen kann: **Alexa, schalte das Wohnzimmerlicht mit 50% ein** .

Ist sowas möglich, mit solchen Variablen, wie zum Beispiel Leuchtstufen oder Temperaturen zu arbeiten oder geht dies nur mit der Cloudlösung?

Entschuldigt mich für diese Frage, aber ich will auch ziemlich viel zu diesem Themengebiet lernen.

Über eure Antworten würde ich mich sehr freuen.

Mit freundlichen Grüßen 
Dennis aka. Scripthase

**Comment by Apollon77** [comment]
Dieser Adapter und ist etwas ganz anderes als eine echte Geräte-Integration via Skills. Und wo ist das Limit bei iot was die Geräteanzahl angeht?
Dieser Adapter steuert ein Alexa Gerät so wie es auch die Alexa Handy App kann - nicht mehr und nicht weniger :-(

Am besten stelle Deine Fragen mal im ioBroker Forum. Da findest Du hilfe.
