### ISSUE TITLE
Feature request - Heos Phrase to play Amazon / Heos Playlist to play with Amazon

### ISSUE THREAD

**Issue by Sweatchcuk** [Apollon77/ioBroker.alexa2#346]
Hallo Apollon77,

ich habe eine Anfrage bzgl. meines Denon AVR. Dieser ist über Heos mit Alexa verbunden und wird mit deinem Adapter unter Echo-Devices erkannt. Es ist auch möglich über den Reiter Player eine Tuneln-Station einzugeben. Dieser wird sofort wiedergeben.

Bei meinen Dots kann ich im Adapter unter Music-Provider diverse Amazon Playlist, oder meine Amazon Playlists aber auch Lieder wiedergeben. Dies funktioniert leider mit dem Heos Device innerhalb deines Adapters nicht. Wäre es möglich diese Funktion zu integrieren?

Mit meine Stimme kann ich problemlos die Playlists, Lieder etc. auf dem Heos Device starten. Die Player-Informationen werden dann im Adapter unter Player auch perfekt angezeigt. 

Im Reiter Info wird der Heos Player unter Info als deviceTypeString mit dem Wert „Apps“ angezeigt.

Ist das Starten (wie mit der Stimme über z.B. dem Dot) von Amazon Music auf dem Heos (Denon AVR) über deinen Adapter möglich? Benötigst du weitere Infos?

P.S. Tuneln funktioniert sehr gut.

Über eine Rückmeldung würde ich mich sehr freuen.

Vielen Dank für dein Arbeit,
Sweatchuck

**Comment by Apollon77** [comment]
Kannst du denn per Alexa App Musik starten auf dem Gerät und so?
Wenn ja: was steht bei den info Punkten als deviceTyp und capabities?

**Comment by Sweatchcuk** [comment]
Hallo Ingo,

vielen Dank für deine schnelle Antwort. Ich habe jetzt einfach über die
Alexa App eine Amazon Playlist gestartet.

Bei capabities wurde folgendes eingetragen:

AMAZON_MUSIC,I_HEART_RADIO,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,LAMBDA_DOWNCHANNEL,TUNE_IN,CHANGE_NAME,VOLUME_SETTING,AUDIO_PLAYER,PANDORA,MUSIC_SKILL

Bei deviceTyp

A21Z3CGI8UIP0F

Hier noch ein Screenshot:


Beste Grüße,
Patrick



Ingo Fischer <notifications@github.com> schrieb am Mo. 30. Dez. 2019 um
00:32:

**Comment by Apollon77** [comment]
Wie hast Du es per App gestartet? Durch anlegen einer Routine oder per "Stimme"? Bitte erusch mal über eine Routine

**Comment by Sweatchcuk** [comment]
Hallo Apollon, 

schön von dir zu hören. Dachte schon das Thema ist für dich abgeschlossen.
Ich habe es einfach im Alexa APP unter Wiedergabe ein Lied gestartet und das Heos Gerät ausgewählt. Das wars... Keine Routine. Geht aber auch vio Stimme wenn ich sage Alexa, spiele Musik auf "Gerätename".

Wäre schön wenn du dir das ansehen könntest. Warte schon lange auf dieses Feature.
