### ISSUE TITLE
A way to stop a alarm or timer

### ISSUE THREAD

**Issue by bebetsch** [Apollon77/ioBroker.alexa2#348]
It would be nice if there was a way to stop a triggered alarm so you can make alexa say something or just kill the alarm if you aren't at home etc. (equally as the "Alexa, Stop" action, or a press of the dot-button on the echo itself)
I know there is the deviceStop button but it doesn't work for alarms (Wecker). It just beginns the getting louder process from 0 again.

**Comment by Apollon77** [comment]
Current known way is gondeltet the timer object which deletes the timer. This is the only known way to do this. 

Else: if alexa App can not do it the adapter can not too.

**Comment by padrino-x** [comment]
@Apollon77 But you know, one can stop the timer through the app. ;)
