### ISSUE TITLE
Smartfriendsjalousiesteuerung setzt keine Befehle um

### ISSUE THREAD

**Issue by derheinrich2019** [Apollon77/ioBroker.alexa2#349]
[iobroker.2020-01-07.log](https://github.com/Apollon77/ioBroker.alexa2/files/4032344/iobroker.2020-01-07.log)
[iobroker.2020-01-07.log](https://github.com/Apollon77/ioBroker.alexa2/files/4032345/iobroker.2020-01-07.log)

Hallo!

Bisher hab ich die Geräte von SmartFriends über den Alexa2 Adapter gesteuert. Ich konnte über "Set Zahl %" den Wert der Jalousie einstellen und das Gerät hat entsprechend reagiert. Leider liess sich nie der aktuelle Status der Jalousie auslesen (wenn von Hand am Gerät selbst geändert)ö

Im neuen Alexa-Skill wird letzteres nun unterstützt.
Nachdem ich den Alexa-Skill für SmartFriends-Geräte aktualisiert hatte, kann ich nun den aktuellen Wert über "Push Button" erhalten - sehr gut.
Leider kann ich nun über "Set Zahl %" nichts mehr steuern. 
Im Log steht dazu folgendes:

`

  |   |   |  
-- | -- | -- | --
alexa2.0 | 2020-01-04 08:19:37.313 | debug | (3002) system.adapter.admin.0: logging true
alexa2.0 | 2020-01-04 07:19:35.913 | debug | (3002) {"applianceId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjMxNzNlYjRjLTQwZDctNGJjNC04MjQwLTMwZjViMDhjMDFmNiIsInN0YWdlIjoibGl2ZSJ9_5577","endpointTypeId":"","driverIdentity":{"namespace":"SKIL
alexa2.0 | 2020-01-04 07:19:35.912 | debug | (3002) Invalid action setPercentage provided for Capability Alexa.PercentageController for percentage. Report to developer this and next log line from logfile on disk!
alexa2.0 | 2020-01-04 07:19:35.904 | debug | (3002) State changed alexa2.0.Smart-Home-Devices.8253fb84-6eb3-4357-a32f-d608b3e71a15.percentage: {"val":5,"ack":false,"ts":1578122375890,"q":0,"from":"system.adapter.admin.0","user":"system.user.adm
alexa2.0 | 2020-01-04 07:19:28.241 | debug | (3002) system.adapter.admin.0: logging false

`

Beste Grüße,
Der Heinrich

**Comment by Mrobelix** [comment]
Hallo,
ich habe genau das selbe Problem.

Seit dem letzen Smart Friends Skill update werden die Rollläden in der App als Typ "Jalousien" erkannt. Wenn ich dann im Alexa2 Adapter den "percentage" wert ändere.

Kommen diese Meldungen im Debugmode:

alexa2.0 | 2020-02-21 19:36:57.889 | debug | (1197) {"applianceId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjMxNzNlYjRjLTQwZDctNGJjNC04MjQwLTMwZjViMDhjMDFmNiIsInN0YWdlIjoibGl2ZSJ9_13186","endpointTypeId":"","driverIdentity":{"namespace":"SKI
-- | -- | -- | --
alexa2.0 | 2020-02-21 19:36:57.889 | debug | (1197) Invalid action setPercentage provided for Capability Alexa.PercentageController for percentage. Report to developer this and next log line from logfile on disk!

Log:
[iobroker.2020-02-21.log](https://github.com/Apollon77/ioBroker.alexa2/files/4237661/iobroker.2020-02-21.log)

Viele Grüße,
Mrobelix/Kevin

**Comment by Apollon77** [comment]
needs anothr check

**Comment by Mrobelix** [comment]
Hallo,

Das Problem besteht leider immer noch, die Meldung ist auch unverändert.

Ich benutze mittlerweile als Übergangslösung Routinen, um meine Rollladen zu steuern.

Meldungen im Debugmode:
alexa2.0 | 2020-06-21 20:22:57.474 | debug | (5198) {"applianceId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjMxNzNlYjRjLTQwZDctNGJjNC04MjQwLTMwZjViMDhjMDFmNiIsInN0YWdlIjoibGl2ZSJ9_13186","endpointTypeId":"","driverIdentity":{"namespace":"SKI
-- | -- | -- | --
alexa2.0 | 2020-06-21 20:22:57.474 | debug | (5198) Invalid action setPercentage provided for Capability Alexa.PercentageController for percentage. Report to developer this and next log line from logfile on disk!

Log:
[iobroker.2020-06-21.log](https://github.com/Apollon77/ioBroker.alexa2/files/4810040/iobroker.2020-06-21.log)

Viele Grüße,
Mrobelix/Kevin

**Comment by Apollon77** [comment]
Please try again with GitHub (will be upcoming v3.14)
