### ISSUE TITLE
Nur 20 Routinen

### ISSUE THREAD

**Issue by SchimmerMediaHD** [Apollon77/ioBroker.alexa2#35]
Hey, 

Ich habe gestern ein Video zu diesem Adapter gemacht...
https://www.youtube.com/watch?v=_8ya1l_Q6Ko&t=458s

Dabei ist mir aufgefallen das ich durch diesen Adapter endlich meine Rollläden von Schellenberg in den ioBroker integrieren kann, und generell ALLES Integrieren kann was sich mit Alexa steuern lässt aber wofür es noch keinen ioBroker Adapter gibt, da man die Routinen hier in voller Form sieht und ansteuern kann.

Das Problem ist, man bekommt nur 20 Routinen angezeigt, ich habe aber über 100 xD

Das ist wahrscheinlich nur eine kleine Änderung im Code, wo man einfach die Anzahl der angezeigten Routinen erhöhen muss oderso. Würde mich freuen wenn das im nächsten Update drin wäre :)

**Comment by Apollon77** [comment]
Zum Video: COOL und Danke, ABER GAAAANZ WICHTIG !!!! Der neue Adapter ist unter https://github.com/Apollon77/ioBroker.alexa2 zu haben. soef ist leider untergetaucht. sein reo wird daher immer bei der 0.3.6 bleiben!!!!! Das solltest Du im Video (ichweiss blöd nachträglich) dringend ändern sonst haben wir ganz  viele Leute die die coolen Features nicht haben.

Routinen: Interessant. Kannst Du mal Debug log vom Adapterstart schicken? Wenn Du es wegen der Daten nicht hier posten willst dann gern als Forum PN

**Comment by SchimmerMediaHD** [comment]
Nein wir können das nachher alles per Mail machen.

Im Video kann und werde ich nix ändern, jedoch habe ich die Links schon überall ausgetauscht 😊👍

Ich würde gern heute noch ein weiteres Video machen wo ich dann zeige wie man ALLE Geräte die man in Alexa hat dank dem adapter auch im
IoBroker hat, das ist ein RIESEN Fortschritt.

Nur dafür muss ich mehr Routinen im Adapter haben 😅

Habe jetzt erstmal einen Termin, wir schreiben danach weiter,

Oder kannst mich auch in Whatsapp Adden wenn du magst... 017660989802

Von meinem iPhone gesendet

**Comment by Ilovegym66** [comment]
Super, in der 0.3.3. first edition funktionieren alle Routinen, und bei mir werden auch wirklich alle angezeigt ( hab ca. 50 ).. jetzt kann iobroker wirklich alles steuern.!!

Noch eine Frage, die Routinen werden in jedem Echo Device gleich angelegt, macht das eigentlich Sinn, muss das sein, oder sollte man die nicht eine Ebene höher anlegen?

**Comment by Apollon77** [comment]
Da Routinen auch Sprachausgabe und Musik und so enthalten braucht es ein device als Fokus. Wenn es weiter oben angelegt wäre, wo kommt die Ausgabe oder die Musik? 

Daher jedes device. ;-)

Macht das Sinn?
