### ISSUE TITLE
Echos bei Musik über Gruppen werden ausgelassen

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#354]
Ich habe im Moment eigentlich nur eine Gruppe - "überall". ;)

Versuche ich darüber Musik abzuspielen, kommt sie nicht auf allen Echos an.

Das betrifft auf jeden Fall
alexa2.0.Echo-Devices.xxxxx.Music-Provider.Amazon-Music
und
alexa2.0.Echo-Devices.xxxxx.Music-Provider.Amazon-Music-Playlist

Logs sind per email raus =)

**Comment by Apollon77** [comment]
Ohne jetzt ins log zu schauen ist das wenn ein Amazon Problem. Der Adapter sendet es an das „Gruppen device“. Dann macht Amazon den Rest. Aber ich checkendes log mal denke aber nicht das ich da was tun kann.

**Comment by thhorkillar** [comment]
Hallo, ich habe ein ähnliches Problem.
Wenn ich meine Playlist starten möchte, passiert bei Gruppen nichts. Bei einzelnen Echos funktioniert es. Gibt es da ein allgemeines Problem ?

**Comment by Apollon77** [comment]
geht es denn per Alexa App als Routine? Sendest Du nur die Playlist? SOnst nichts?Oder noch ein zweites Kommando direkt davor oder danach?

**Comment by thhorkillar** [comment]
Sorry für die späte Antwort. Bin nicht früher dazu gekommen. 

Ich gebe im folgenden Pfad nur die Playliste (W1    oder      Guten Morgen    ) ein.
alexa2.0.Echo-Devices.xxxxxxxxGRUPPExxxxxxxx.Music-Provider.Amazon-Music-Playlist
Danach passiert nichts. Es hat aber schon mal funktioniert.
Es betrifft alle Playlisten unter dem Pfad 
alexa2.0.Echo-Devices.xxxxxxxxGRUPPExxxxxxxx.Music-Provider.

Wenn ich im Pfad 
alexa2.0.Echo-Devices.xxxxxxxx   einzelnes Gerät. ECHO DOT xxxxxxxx.Music-Provider
es versuche, dann funktioniert es. Das Problem tritt also nur bei Gruppen auf. Es hat bis Mitte letzten Jahres funktioniert. / Dann hat es nur noch sporadisch funktioniert. Irgendwann gar nicht mehr.

Wenn ich es als Routine versuche, dann funktioniert es. 
Es betrifft jede Playlist. Egal wie sie heißt.
z.B. Guten Morgen   oder W1
Es kann also auch nicht am "Leerzeichen" liegen.

ich habe folgendes versucht:
- Gruppen löschen und neu anlegen.
- Alle ECHOdot Geräte gelöscht (Werkseinstellungen) - neu anlegt und die Gruppen erneut anlegt.
- Alexa Instanz gelöscht und neu anelegt
- Alexa Adapter gelöscht und neu installiert. 
- (Amazon) Playlisten neu angelegt. / umbenannt

**Comment by Apollon77** [comment]
Ok, wenn Routinen gehen dann bitte folgendes tun:
* Routine anlegen die das tut
* Adapter neu starten im Loglevel Debug
* Einmal die Routine im ioBroker ausführen. Zeit aufschreiben wann das war
* Jetzt alles wieder stoppen und so
* Jetzt Playlist über iobroker starten ... so lange versuchen bis es mal nicht tut ... Zeit merken

ich brauche dann entweder das gesamte Logfile oder großzügige Log Ausschnitte "um die Zeitpunkte drumrum" (vor allem danach natürlich) wo du die beiden Dinge gemacht hat.

Log von Platte NICHT aus Admin kopieren!!

Das dann als email an iobroker@fischer-ka.de mit verweis auf dieses Github Issue hier.

**Comment by Apollon77** [comment]
Passiert das eigentlich immer noch?

**Comment by padrino-x** [comment]
Yep. =)

**Comment by Apollon77** [comment]
kann es sein das die Geräte in mehreren Amazon Accounts hängen oder solche konstrukte? Ich kann das Problem nicht nachvollziehen bei meinen gruppen

**Comment by padrino-x** [comment]
Ne. Gar nicht. Ist ein Account. Eigentlich nix Besonderes.
Ist eine Gruppe ais 2x Echo Dot2 und 1x Echo2.
Per Sprache werden alle in der Gruppe "befeuert".

**Comment by spitfire4all** [comment]
Hi,
Habe das gleiche Problem. Musik wird immer nur auf einem Echo ausgegeben, ich glaube auf dem der zuletzt aktiviert war. Titel und Playlisten werden teilweise nicht gefunden. Gebe ich den Titel auf einem einzelnen Gerät an funktioniert es. In der Spotify App wird das Multi-Room device mehrfach angegeben sobald auf einem anderen Echo die Musik abgespielt wird.

Gruß 
Hans-Dieter

**Comment by Apollon77** [comment]
Wenn die spotify App spinnt ... was hat das mit dem Adapter zu tun? Ist dann nicht die Idee eher das auch bei Amazon way kaputt ist?

**Comment by padrino-x** [comment]
Bin grade am Verzweifeln. :(
Da ich hier noch Geräte in der Gruppe "überall" hatte, die es nicht (mehr) gibt, habe ich gedacht, evtl. liegt es daran.
Rausgelöscht, half nix.
Gruppe komplett gelöscht, alles Echos zurückgesetzt.
Jetzt kann ich überhaupt keine Multiroom Gruppen mehr anlegen. :(

**Comment by spitfire4all** [comment]
> Wenn die spotify App spinnt ... was hat das mit dem Adapter zu tun? Ist dann nicht die Idee eher das auch bei Amazon way kaputt ist?

Das ist als Neuling leider nicht immer so einfach zu erkennen, aber man lernt ja dazu.
Ich beschäftige mich jetzt erst zwei Monate mit dem IOBroker.
Die Doku und der Adapter ist sehr gut, vielen Dank dafür. 

Aus der Spotify PC App können die Echos bei mir angesteuert werden. Beide angezeigten spielen ab. Aus der Alexa App selber, die ich bis jetzt noch nie zum abspielen benutzt habe, ist es aber chaotisch.
Stelle ich da die Multiroom Lautsprecher ein geht es mal , mal kommt es nur auf einem raus, mal wird angezeigt das ein Lautsprecher spielt aber es kommt gar nix raus. Ich habe in jedem Raum auch einen Sonos, ist dieser als Ausgabe im Raum definiert, spielt dieser auch noch die Musik ab, die Echos schweigen auch wenn sich zwei Echos in dem Raum befinden. . Das könnte ja immerhin logisch sein. 

Gruß
Hans-Dieter

**Comment by Apollon77** [comment]
Und jetzt sind wir genau am interessanten Punkt: Wenn es in der Alexa App genau spinnt wie beim Adapter dann kann ich nichts tun :-( Der Adapter kann maximal so gut sein wie die App ... weil er faktisch die exakt gleichen Funktionen benutzt

**Comment by spitfire4all** [comment]
Ja das habe ich mir gedacht.
In Zukunft werde ich es deshalb über die Alexa App testen.
Darf ich noch fragen um welchen Dienst es sich bei handelt:

My-Library | Phrase to play with My Library | Text input
My-Library-Playlist | Playlist to play with My Library | Text input

Gehört das zu Youtube oder irgendeine lokale Library ?

Im Iobroker Forum findet man dazu eigentlich nichts.

Gruß
HDM

**Comment by Apollon77** [comment]
Das sind die Musik-Services die die Alexa API zurückliefert. Ich glaube das ist die Amazon Library

**Comment by padrino-x** [comment]
Ich hatte die Vermutung, "my libraby" sind meine gekauften Titel plus das Angebot, dass mir mit evtl. gebuchtem prime Tarif zur Verfügung steht. =)

**Comment by spitfire4all** [comment]
> Das sind die Musik-Services die die Alexa API zurückliefert. Ich glaube das ist die Amazon Library

Wenn du das nicht auf den Peng weißt dann bin ich ja beruhigt. :-)



> Bin grade am Verzweifeln. :(
> Da ich hier noch Geräte in der Gruppe "überall" hatte, die es nicht (mehr) gibt, habe ich gedacht, evtl. liegt es daran.
> Rausgelöscht, half nix.
> Gruppe komplett gelöscht, alles Echos zurückgesetzt.
> Jetzt kann ich überhaupt keine Multiroom Gruppen mehr anlegen. :(

Habe da mal einen Beitrag im Ibroker Forum gelesen oder in einem Thread hier auf Github.
Der Kollege hatte das gleiche Problem, bei Ihm war es wohl eine veraltete Alexa App.
Ansonsten fällt mir dazu leider auch nichts ein.



> Ich hatte die Vermutung, "my libraby" sind meine gekauften Titel plus das Angebot, dass mir mit evtl. gebuchtem prime Tarif zur Verfügung steht. =)
> 
> "Phrase to play" dürfte "Alexa, spiel das Lied mit dem Text..." entsprechen.

Danke für die gute Erklärung, leider scheint das nirgendwo so eindeutig zu stehen, habe jedenfalls nichts gefunden.

Gruß
HDM

**Comment by spitfire4all** [comment]
So ein Schritt weiter.
Ich habe im Büro, Küche und Bad jeweils einen Echo und einen Sonos Lautsprecher.
Spotify Premium und Amazone Prime.
Meine Idee war es wenn es klingelt auf allen drei Echos Musik abzuspielen.
Wie wir gesehen haben kann man das mit den Multiroom Gruppen vergessen.
So wie ich das sehe lässt Amazon wie Spotify auch nur das Abspielen auf einem Gerät zu.
Bei Spotify gibt es den Trick die Spotify App und die Sonos App zu benutzen, dann geht es auch auf zwei Lautsprechern.
Ich habe zwei Echos mit dem gleichen Lied über den Iobroker gefüttert, hier spielt er random irgendwo ab. Gibt man dem zweiten Eintrag eine Verzögerung von 2 sec. dann meldet Alexa das die Musik bereits auf einem Lautsprecher ausgegeben wird und ob man zu diesem wechseln möchte.
Füttert man Amazon Musik und My Library mit dem gleichen Titel hat man eigentlich das gleiche Problem, löscht man aber die Einträge aus dem Iobroker wird die Musik etwas Zeit verzögert auf beiden Echos ausgegeben.

Das Problem das ich noch habe ist das wenn in der App eingestellt ist das der Sonos das Ausgabegerät ist hier abgespielt wird. Beim Fernsehen spielt er dann die Musik auf meiner Playbar was nicht so toll ist.
Gibt es einen Wert mit dem man das Temporär umstellen kann ?

![image](https://user-images.githubusercontent.com/25489051/77649500-43077480-6f6a-11ea-8c65-30682bc4bec8.png)

Gruß
Hans-Dieter

**Comment by Apollon77** [comment]
Bitte 3.2.x versuchen
