### ISSUE TITLE
Objekte // Smart Home Devices aktualisiert sich nicht

### ISSUE THREAD

**Issue by Knallix** [Apollon77/ioBroker.alexa2#355]
Habe ein Osram Plug über das Zigbee vom Echo eingebunden z.B. "Pumpe"
Dieses kann Ich über die App vom Handy steuern, auch das Schalten über iobroker (alexa2) läuft ohne Probleme.
Leider bekommt der ioBroker den Zustand aus der App nicht mitgeteilt, wenn ich diesen schalte oder wenn ich mit dem Echo spreche. 
Gibt es hier eine Lösung oder ist das grundsätzlich nicht gewollt ?

![d27ef306-affc-44b2-a4c1-4283394ff719](https://user-images.githubusercontent.com/42406048/72222337-e3511e00-3563-11ea-9cf9-fc135dcc94ae.jpg)
![Unbenannt](https://user-images.githubusercontent.com/42406048/72222341-eba95900-3563-11ea-8fb7-388ba7fcc756.JPG)

**Comment by Apollon77** [comment]
Amazon informiert nicht per push über neue werte, daher kann das nicht automatisiert gelesen werden. Dazu gibt es den #query Datenpunkt um ein Update zu triggern
