### ISSUE TITLE
Feature request: Display Datenpunkt: Echo Dot with Clock

### ISSUE THREAD

**Issue by enemy2003** [Apollon77/ioBroker.alexa2#356]
**Update:**
**für alle mit Echo Dot with Clock, die das LED Display ansprechen wollen...**

**habe ich jetzt mal ein Skript gebastelt, das nach einem Adapter Update das Display hinzufügt.**
**Voraussetzung iobroker ist unter /opt/iobroker installiert. Keine Garantie, macht euch eine Sicherung ;) Stand 13.12.2020**

**Shell Script hier im Anhang:**
[alexa2_add_led_display.sh.txt](https://github.com/Apollon77/ioBroker.alexa2/files/5685418/alexa2_add_led_display.sh.txt)

aktuell erstellt es bei allen echo devices die beiden Datenpunkte, ist etwas unschön aber stört nicht. 
...
**orig Post:**

Hab mir den Echo Dot mit Uhr zugelegt. Wäre genial wenn man hier das Display über iobroker ein und ausschalten (oder auch die Helligkeit steuern) könnte. Leider ist das in den Routinen nicht möglich nur per Sprachbefehl bzw. in der App, sonst könnte man ja auch einfach die entsprechende Routine starten.

//
Device-type:A30YDR2MK8HMRV (DISPLAY_POWER_TOGGLE,CHANGE_NAME,TIMERS_AND_ALARMS,BT_PAIRING_FLOW_V2,ACTIVE_AFTER_FRO,AUDIO_CONTROLS,AUDIBLE,PERSISTENT_CONNECTION,SUPPORT_CALENDAR_ALERT,FAR_FIELD_WAKE_WORD,REMINDERS,GUARD_EARCON,I_HEART_RADIO,TAHOE_BYOD,ASCENDING_ALARM_VOLUME,CLOCK_FORMAT_24_HR,DISPLAY_ADAPTIVE_BRIGHTNESS,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,PAIR_REMOTE,VOLUME_SETTING,SUPPORTS_LOCALE_SWITCH,AMAZON_MUSIC,LEMUR_ALPHA,SALMON,VOICE_TRAINING,DEREGISTER_DEVICE,UPDATE_WIFI,PAIR_BT_SINK,ALEXA_PRESENCE,TUPLE_CATEGORY_A,SUPPORTS_SOFTWARE_VERSION,DS_VOLUME_SETTING,POPTART,PAIR_BT_SOURCE,SLEEP,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,PANDORA,DISPLAY_BRIGHTNESS_ADJUST,MUSIC_SKILL,SOUND_SETTINGS,ALEXA_GESTURES,GADGETS,MICROPHONE,KINDLE_BOOKS,FLASH_BRIEFING,TUPLE,AUDIO_PLAYER,REQUIRES_OOBE_FOR_SETUP,GOLDFISH,TUNE_IN,CUSTOM_ALARM_TONE,DREAM_TRAINING,EARCONS,SET_LOCALE)

**Comment by Apollon77** [comment]
Wenn Routinen und App nicht tun dann sorry, geht nicht

**Comment by enemy2003** [comment]
Über die App geht es in den Geräteeinstellungen

**Comment by Apollon77** [comment]
Zeig mal einen Screenshot bitte

**Comment by enemy2003** [comment]
![EE5B50E2-A1C5-4CA5-8FB4-8F9CE603047A](https://user-images.githubusercontent.com/17781848/76830251-28742380-6825-11ea-8e84-8bd080f96547.png)

**Comment by Apollon77** [comment]
Dann ist die Challenge jetzt "nur" rauszufinden wie das API technisch tut ohne so ein Gerät zu haben :-)

**Comment by enemy2003** [comment]
> Dann ist die Challenge jetzt "nur" rauszufinden wie das API technisch tut ohne so ein Gerät zu haben :-)


Wenn ich irgendwie unterstützen kann, testen, tracen... sehr gerne :)

**Comment by Apollon77** [comment]
Ja man müsste App Traffic via Proxy mitschneiden. Ich versuch mal so was rauszubekommen ...

**Comment by enemy2003** [comment]
Hab mich mal die letzte Zeit damit befasst. Leider gibt es den Display Punkt nicht über die Webseite, hier wäre https mitschneiden nicht ganz so schwierig. Unter iOS und mit dem Android Emu habe ich es leider nicht geschafft ein root Zertifikat so einzuschleusen, dass es entschlüsselt werden kann...

Ich habe mir jetzt mal die apk geladen und genauer angeschaut. In den Files findet sich so manches, vielleicht auch hilfreiches.

hier ist es unter DeviceCapability gelistet, das gibt es ja im Adapter schon diverse, vielleicht lassen sich mit diesen Infos die 4 Funktionen für das Display einbauen. Oder zum test auch mal nur einer :)

Also in der App geht folgendes:
- Anzeige an/aus
- Helligkeit 0-100%
- Adaptive Helligkeit an/aus
- 24-Stunden-Uhr an/aus

das deckt sich auch mit den Funktionen im Code. Ist leider nur die App ohne direkten Verweis auf die API aber hier mal die Code Schnipsel, vielleicht ist es ja ähnlich mit bekannten Einstellungen:

displayPower:($||k()).ADselectors.getDeviceSetting('displayPower'),
brightness:($||k()).ADselectors.getDeviceSetting('brightness'),
adaptiveBrightness:($||k()).ADselectors.getDeviceSetting('adaptiveBrightness'),
timeFormat:($||k()).ADselectors.getDeviceSetting('timeFormat')


__d(function(g,r,i,a,m,e,d){Object.defineProperty(e,"__esModule",{value:!0});var _=e.Toggle=void 0;!(function(_){_.ON="ON",_.OFF="OFF"})(_||(e.Toggle=_={}));var E=e.TimeFormat=void 0;!(function(_){_.HOURS_24="24_HOURS",_.HOURS_12="12_HOURS"})(E||(e.TimeFormat=E={}));e.DISPLAY_POWER_TOGGLE='DISPLAY_POWER_TOGGLE',e.DISPLAY_BRIGHTNESS_ADJUST='DISPLAY_BRIGHTNESS_ADJUST',e.DISPLAY_ADAPTIVE_BRIGHTNESS='DISPLAY_ADAPTIVE_BRIGHTNESS',e.CLOCK_FORMAT_24_HR='CLOCK_FORMAT_24_HR',e.CLOCK_FORMAT_SECTION_HEADER='CLOCK_FORMAT_SECTION_HEADER',e.HOUR_CLOCK_24='HOUR_CLOCK_24',e.DISPLAY_PAGE_HEADER='DISPLAY_PAGE_HEADER',e.DISPLAY_TOGGLE_TITLE='DISPLAY_TOGGLE_TITLE',e.ADAPTIVE_BRIGHTNESS_TITLE='ADAPTIVE_BRIGHTNESS_TITLE',e.BRIGHTNESS_SECTION_HEADER='BRIGHTNESS_SECTION_HEADER',e.ADAPTIVE_BRIGHTNESS_DESCRIPTION='ADAPTIVE_BRIGHTNESS_DESCRIPTION'},7652,[]);


case 2:this.props.device.online&&(this.props.device.capabilities.includes((L||q()).

DISPLAY_POWER_TOGGLE)&&(null==this.props.displayPower||t)&&($||k()).ADactions.getDeviceSetting((x||J()).DisplayPowerKey,this.props.device.deviceAccountId,t)(null,null,null),this.props.device.capabilities.includes((L||q()).

DISPLAY_BRIGHTNESS_ADJUST)&&(null==this.props.brightness||t)&&($||k()).ADactions.getDeviceSetting((x||J()).DisplayBrightnessKey,this.props.device.deviceAccountId,t)(null,null,null),this.props.device.capabilities.includes((L||q()).

DISPLAY_ADAPTIVE_BRIGHTNESS)&&(null==this.props.adaptiveBrightness||t)&&($||k()).ADactions.getDeviceSetting((x||J()).DisplayAdaptiveBrightnessKey,this.props.device.deviceAccountId,t)(null,null,null),this.props.device.capabilities.includes((L||q()).

CLOCK_FORMAT_24_HR)&&(null==this.props.timeFormat||t)&&($||k()).ADactions.getDeviceSetting((x||J()).DisplayTimeFormatKey,this.props.device.deviceAccountId,t)(null,null,null));case 3:case"end":return n.stop()}},n,this)}))},n.pullToRefresh=function(){return(f||D()

**Comment by eddie209** [comment]
Hello,
Look at my post (in French), i was able to intercept HTTP REST API : 

`https://github.com/sigalou/jeedom_alexaapi/issues/35`

**Comment by enemy2003** [comment]
that's great, thank you.
Today I got it to work to capture the traffic on my phone and I can confirm it.

> 
> just a simple API to call but you must provide the deviceId of your echo.

how can the deviceId found? A0...


@Apollon77 in the objects there is the deviceType and Serial, but not the ID. Is it already somewhere?



here is my capture output:

> PUT https://alexa.amazon.de/api/v1/devices/A0...B/settings/displayPower HTTP/1.1
> Host: alexa.amazon.de
> Content-Type: application/json; charset=utf-8
> Cookie: ;at-acbde="Atza|IwE...Qtb";sess-at-acbde="PLS...sZY=";session-id=25...13;session-id-time=20...1l;session-token="cO...4Q==";ubid-acbde=26...09;x-acbde="8G...IC";csrf=20...19
> x-amzn-RequestId: fb...89
> Accept-Encoding: gzip, deflate, br
> Connection: keep-alive
> Accept: application/json; charset=utf-8
> User-Agent: Mozilla/5.0 (iPhone; ...
> Accept-Language: de-DE,de-DE;q=1.0,en-US;q=0.9,ru-RU;q=0.8,te-DE;q=0.7
> csrf: 20...19
> Content-Length: 18
> 
> {"value":"\"ON\""}
> 
> oder 
> {"value":"\"OFF\""}
> 
> 
> 
> PUT https://alexa.amazon.de/api/v1/devices/A0...B/settings/adaptiveBrightness HTTP/1.1
> Host: alexa.amazon.de
> Content-Type: application/json; charset=utf-8
> Cookie: ;at-acbde="Atza|IwE...Qtb";sess-at-acbde="PLS...sZY=";session-id=25...13;session-id-time=20...1l;session-token="cO...4Q==";ubid-acbde=26...09;x-acbde="8G...IC";csrf=20...19
> x-amzn-RequestId: 89...94
> Accept-Encoding: gzip, deflate, br
> Connection: keep-alive
> Accept: application/json; charset=utf-8
> User-Agent: Mozilla/5.0 (iPhone; ...
> Accept-Language: de-DE,de-DE;q=1.0,en-US;q=0.9,ru-RU;q=0.8,te-DE;q=0.7
> csrf: 20...19
> Content-Length: 19
> 
> {"value":"\"OFF\""}
> 
> oder 
> {"value":"\"ON\""}
> 
> 
> 
> PUT https://alexa.amazon.de/api/v1/devices/A0...B/settings/timeFormat HTTP/1.1
> Host: alexa.amazon.de
> Content-Type: application/json; charset=utf-8
> Cookie: ;at-acbde="Atza|IwE...Qtb";sess-at-acbde="PLS...sZY=";session-id=25...13;session-id-time=20...1l;session-token="cO...4Q==";ubid-acbde=26...09;x-acbde="8G...IC";csrf=20...19
> x-amzn-RequestId: e0...6f
> Accept-Encoding: gzip, deflate, br
> Connection: keep-alive
> Accept: application/json; charset=utf-8
> User-Agent: Mozilla/5.0 (iPhone; ...
> Accept-Language: de-DE,de-DE;q=1.0,en-US;q=0.9,ru-RU;q=0.8,te-DE;q=0.7
> csrf: 20...19
> Content-Length: 24
> 
> {"value":"\"24_HOURS\""}
> 
> oder 
> {"value":"\"12_HOURS\""}
> 
> 
> 
> PUT https://alexa.amazon.de/api/v1/devices/A0...B/settings/brightness HTTP/1.1
> Host: alexa.amazon.de
> Content-Type: application/json; charset=utf-8
> Cookie: ;at-acbde="Atza|IwE...Qtb";sess-at-acbde="PLS...sZY=";session-id=25...13;session-id-time=20...1l;session-token="cO...4Q==";ubid-acbde=26...09;x-acbde="8G...IC";csrf=20...19
> x-amzn-RequestId: 24...ee
> Accept-Encoding: gzip, deflate, br
> Connection: keep-alive
> Accept: application/json; charset=utf-8
> User-Agent: Mozilla/5.0 (iPhone; ...
> Accept-Language: de-DE,de-DE;q=1.0,en-US;q=0.9,ru-RU;q=0.8,te-DE;q=0.7
> csrf: 20...19
> Content-Length: 30
> 
> {"value":"35.693215339233035"}
>

**Comment by enemy2003** [comment]
habe heute nachdem mein cookie erneuert werden musste mal auf die neueste Version geupdatet. Falls jemand das Display bei sich einbauen will hier mal eine kurze Anleitung. Weiß nicht wie "sauber" das ist, aber es funktioniert. Vielleicht kommt es ja bei einem der nächsten Releases mit :)

**Alexa LED Display zum Adapter hinzufügen:**

Ich habe hier ein/ausschalten und Helligkeit eingefügt, die restlichen Funktionen gehen dann analog dazu. Es wird jeweils ein Objekt benötigt und anschließen sind in folgenden files kleine Einfügungen notwendig.

Zuerst muss man noch die Device ID rausfinden, z.B. indem man den Adapter im debug Logmodus startet
```

Im iobroker die Objekte zum Echo mit LED Display hinzufügen:

alexa2.0.Echo-Devices.G0***.Commands.displayBrightness als text (... %)
alexa2.0.Echo-Devices.G0***.Commands.displayPower als Logikwert (true/false)


In Datei:
/opt/iobroker/node_modules/iobroker.alexa2/main.js

Suche nach:
            setOrUpdateObject(devId + '.Commands.doNotDisturb', {common: {role: 'switch'}}, false, device.setDoNotDisturb);

Hinzufügen:
            setOrUpdateObject(devId + '.Commands.displayPower', {common: {role: 'text'}}, false, device.setDisplayPower);
            setOrUpdateObject(devId + '.Commands.displayBrightness', {common: {role: 'text'}}, '', device.setDisplayBrightness);


In Datei:
/opt/iobroker/node_modules/alexa-remote2/alexa-remote.js

Suche nach:
                    device.setDoNotDisturb = this.setDoNotDisturb.bind(this, device);

Hinzufügen:
                    device.setDisplayPower = this.setDisplayPower.bind(this, device);
                    device.setDisplayBrightness = this.setDisplayBrightness.bind(this, device);


Weiter unten z.B. nach der setDoNotDisturb Funktion noch die Funktionen für setDisplayPower und setDisplayBrightness einfügen:


setDisplayPower(serialOrName, enabled, callback) {
        let dev = this.find(serialOrName);
        if (!dev) return callback && callback(new Error ('Unknown Device or Serial number', null));

        var dispPower='"OFF"';

        if(enabled){
                dispPower='"ON"';
        }

        let flags = {
            data: JSON.stringify({
                value: dispPower
            }),
            method: 'PUT'
        };
        this.httpsGet (`/api/v1/devices/A0***/settings/displayPower`, callback, flags);
    }

    setDisplayBrightness(serialOrName, brvalue, callback) {
        let dev = this.find(serialOrName);
        if (!dev) return callback && callback(new Error ('Unknown Device or Serial number', null));

        let flags = {
            data: JSON.stringify({
                value: '"'+brvalue+'"'
            }),
            method: 'PUT'
        };
        this.httpsGet (`/api/v1/devices/A0***/settings/brightness`, callback, flags);
    }
```

**Comment by Ilovegym66** [comment]
Das ist ja geil :-) 
Es heisst ja immer, alles, was man in der App einstellen kann, kann der Adapter auch.. ist hier auch möglich, bei Geräten mit Display die Funktionen wie in der App zu aktivieren und zu benutzen?
( Tägliche Erinnerungen an/aus, An diesem Tag an/aus, Amazon Photos - Sammlungen verwalten für Startseitenhintergrund, Fotos hochladen - geht bis 10stck. )

**Comment by enemy2003** [comment]
> Das ist ja geil :-)
> Es heisst ja immer, alles, was man in der App einstellen kann, kann der Adapter auch.. ist hier auch möglich, bei Geräten mit Display die Funktionen wie in der App zu aktivieren und zu benutzen?
> ( Tägliche Erinnerungen an/aus, An diesem Tag an/aus, Amazon Photos - Sammlungen verwalten für Startseitenhintergrund, Fotos hochladen - geht bis 10stck. )

Also hier geht es lediglich um das LED Display bei Echo Dot Clock. Ich stelle hier nur das Display heller/dunkler und nachts aus.

Ich habe keinen Echo Show oder ähnliches, da müsste jemand mit Gerät den Datenverkehr mitschneiden um zu sehen was alles möglich ist, prinzipiell sicherlich einiges ist halt auch mit Arbeit verbunden :D

**Comment by Ilovegym66** [comment]
Ah, das mit dem Dot clock ist mir entgangen, aber das mitschneiden sollte kein Problem sein. Ich notiere mir das Mal auf die To-Do 😁👍🏽

**Comment by LupoLucario** [comment]
Statt

>this.httpsGet (`/api/v1/devices/A0***/settings/displayPower`, callback, flags);

und

>this.httpsGet (`/api/v1/devices/A0***/settings/brightness`, callback, flags);

wäre es einfacher

`this.httpsGet (`/api/v1/devices/**${dev.deviceAccountId}**/settings/displayPower`, callback, flags);`
 
und

`this.httpsGet (`/api/v1/devices/**${dev.deviceAccountId}**/settings/brightness`, callback, flags);`

zu benutzen. So hat es bei mir besser geklappt ;)


Außerdem sollte

>setOrUpdateObject(devId + '.Commands.displayPower', {common: {role: 'text'}}, false, device.setDisplayPower);

kein Text sondern switch sein. Also:

setOrUpdateObject(devId + '.Commands.displayPower', {common: {role: '**switch**'}}, false, device.setDisplayPower);




Vielen Dank für das tolle Skript!
Endlich hat dieses Display mit ioBroker einen Sinn :D


LG Lupo

**Comment by ooooli** [comment]
Funktioniert bei mir nicht mit dem Echo Show 8. Weder mit Device ID, noch Platzhalter.
Kann das ggf. als Pull Request in den Code rein?

**Comment by enemy2003** [comment]
> Funktioniert bei mir nicht mit dem Echo Show 8. Weder mit Device ID, noch Platzhalter.
> Kann das ggf. als Pull Request in den Code rein?

Hast wohl nicht so detailliert geschaut, das ist nur für das LED Display am Echo Dot mit Uhr. ;)

Habe mal den Titel angepasst.

**Comment by enemy2003** [comment]
@Apollon77 falls du mal Zeit hast es einzubauen, würden sich einige freuen :) 

ich schließe das issue mal, weitere Kommentare sind glaube ich nicht mehr erforderlich. 
Es funktioniert soweit sehr zuverlässig, wenn auch noch nicht ideal integriert. 

Viele Grüße und Danke für deine Tolle Arbeit.

**Comment by Apollon77** [comment]
naja wenn du es haben willst dann öass es offen ... sonst ists weg

**Comment by sigalou** [comment]
Hallo, ich habe ein Problem mit der Uhranzeige. Haben Sie die gleichen Bedenken?
(Mein Deutsch wird von Google Übersetzer gesponsert)
Danke

**Comment by BassT23** [comment]
Habe seit heute auch einen dot 4 mit uhr (display)
Wäre super, wenn man diese (display) besser steuern könnte.

**Comment by Apollon77** [comment]
Zu wissen wie es gesteuert wird ist super ... jetzt fehlt noch die Erkennung ob das Gerät es hat :-)

melde mich heute Abend. dann bräuchte ich bitte von jemandem eine Debug log vom Adapterstart mit der Info welches Gerät es ist ... Aber noch nicht jetzt!! melde mich

**Comment by BassT23** [comment]
Werde gerne helfen ;)

**Comment by Apollon77** [comment]
Ok, dann Bitte GitHub version und volles Log vom Start an iobroker@fischer-ka.de senden. Mit refernz auf dieses Issue und Logfile aus /opt/iobroker/log bitte nehmen. Und sage bitte den Namen des geräts mit Uhr

**Comment by Apollon77** [comment]
Das Problem ist gerade nicht das ganze einzubauen mit den Infos von oben. Das Problem ist eher das jedes einzelne State scheinbar EIN call ist um es zu lesen ... Das einzige was aktuell gehen würde wäre ein einmaliges lesen und dann kann man es per Adpater setzen, aber wennnmanparallel in der App ändert ist es put of sync ... ist sonst zuviel Traffic

**Comment by Apollon77** [comment]
Am Ende müssen wir mal den Traffic der App mitsniffen ob die wirklich 4 calls macht oder nur einen

**Comment by Apollon77** [comment]
@enemy2003 Can you also sniff the "GET" requests that read out the values and provide here?

**Comment by Apollon77** [comment]
Ok, i giot it ... most likely comes in next version.

**Comment by Apollon77** [comment]
Ok, I will include display on/off and brightness. I think 14/24h and "adaptive brigthness" is still that do notneed to be that dynamically settable in adapter, right?

Consider that each setting is one call per device on init of the adapter ...

**Comment by BassT23** [comment]
Adaptive brightness will also be good, because I can control with my light sensors.

**Comment by Apollon77** [comment]
But adaptive brightness is only on/off ... If there is an other setting appearing when you enable it then I need the name.

But ok willbe in

**Comment by BassT23** [comment]
One of my display echo is nearly build in the furniture, so the display is too dark.
Now I can turn off the adaptive and control the light with the sensors. Otherwise I can control only the max brightness. ;)
Thank you

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/56437/alexa2-adapter-3-18-x-beta
