### ISSUE TITLE
Farbe von RGB-Devices steuern

### ISSUE THREAD

**Issue by Omega236** [Apollon77/ioBroker.alexa2#359]
Ich habe RGB-Komponenten in Alexa über den integrierten Zigbee Hub verbunden und will nun die Farbe über IO-Broker Datenpunkte/Skripte ändern.

Die Datenpunkte für HUE (alexa2.0.Smart-Home-Devices._ID_.color-hue) und Saturation (alexa2.0.Smart-Home-Devices._ID_.color-saturation) sind aktuell nur Readonly.

Die einzigen Datenpunkte die Beschreibar sind:

alexa2.0.Smart-Home-Devices._ID_.colorName => Auflistung von FarbenName zu Nummer (0-144) z.B.   "21": "Light Pink (#ffb5c1)",
  "22": "Gainsboro (#ffffff)",
  "23": "Slate Blue (#856fff)",
  "24": "Light Slate Gray (#c6e1ff)",
und
alexa2.0.Smart-Home-Devices._ID_.colorTemperatureName => Auflistung von FarbenName  zu Nummer (0-18) z.B.   "12": "Cool (7000K)"

Darüber kann ich zwar in Skripten explizit auf Warm/kalt bzw feste Farbe stellen, aber nicht über einen Colorpicker bzw YAHKA.

Habe ich etwas übersehen oder ist das noch nicht möglich?

**Comment by Apollon77** [comment]
Kannst du per Alexa App eine exakte Farbe wählen? Alexa kann nur ausgewählte Farben ansteuern. Und auch die App kann keine freie Auswahl. Damit ist der Adapter auch limitiert. Sorry.

**Comment by Omega236** [comment]
Oh das stimmt leider :( 
Danke für die Antwort
