### ISSUE TITLE
Wiedergabe beenden

### ISSUE THREAD

**Issue by Night2k5** [Apollon77/ioBroker.alexa2#36]
Funktion hinzufügen zum beenden der aktuellen Wiedergabe.
Im Moment regle ich das über die Lautstärke, das ist aber nicht so toll weil Alexa dann im Hintergrund weiter Daten ließt.

**Comment by Ilovegym66** [comment]
dafür gibts doch ControlPause, setz das Objekt auf true und die Wiedergabe stoppt.
alexa2.0.Echo-Devices.G000xxxxxxxxxx.Player.controlPause 

mit 
alexa2.0.Echo-Devices.G000xxxxxxxxxxx.Player.controlPlay
auf true wird die Wiedergabe wieder gestartet. Das funktioniert gut.

**Comment by Night2k5** [comment]
Oh Danke dir!
Hab ich doch tatsächlich übersehen.
