### ISSUE TITLE
Commands.speak spricht zuviel Text

### ISSUE THREAD

**Issue by ploxy** [Apollon77/ioBroker.alexa2#361]
Wenn ein Wert in Commands.speak gesetzt wird, wird vor den eigentlichen Wert noch etwas wie "Amazon Force Unit Selection" gesprochen. Am Ende wird ein "Kleiner als Amazon Force Unit Selection Größer als".
Das ist erst seit ein paar Tagen?!

**Comment by Apollon77** [comment]
Amazon hats kaputt gemacht. passiert auch wenn Du sagst "Alexa sprich mir nach ..." ... Nichts wo wir etwas tun können

**Comment by ploxy** [comment]
Alles klar, danke. Warten wir ab.
