### ISSUE TITLE
alexa2.0.History.summary Objekt ohne Funktion

### ISSUE THREAD

**Issue by Blackmytj** [Apollon77/ioBroker.alexa2#362]
Bei mir ändert sich nach Spracheingabe an Alexa das history.summer Objekt nicht mehr.
Ist das ein allgemeines Problem ?

**Comment by Apollon77** [comment]
Scheinbar bei einigen Usern ... siehr auch Forum ... Die Push Verbindung bekommt keine Daten mehr ... damit leider auch der Adapter nicht Abwarten ob es Amazon wieder fixt oder es so bleibt

**Comment by Blackmytj** [comment]
Danke für die Info. Hoffe es wird gefixt

**Comment by Apollon77** [comment]
lass mal offen, so finden die info auch andere

**Comment by Apollon77** [comment]
was fixed by Amazon

**Comment by Crashoverride87** [comment]
Hallo, leider scheint das Problem nicht gefixt worden zu sein. Seit Samstag habe ich das Problem auch immer wieder. Habe nun auf 3.0.7 von 3.0.5 gewechselt, leider dasselbe Bild. Ich hab mittlerweile ein Script, welches den Adapter in so einem Fall mit exec Befehl neustartet, dann trudeln die ganzen summary Einträge wieder ein. Und immer dieselbe Fehlermeldung.

**Comment by Apollon77** [comment]
Tja, dann baut Amazon wieder Dinge rum :-(

**Comment by n3ucr0n** [comment]
Ich klink mich mal ein - Seit heute Mittag kommt bei mir auch in der History nichts mehr an.
Wenn ich jedoch beispielsweise den "Speak" Datenpunkt nutze, klappt es.
Hat das ebenfalls mit Änderungen von Amazon zu tun oder muss ich das Problem an anderer Stelle suchen?

Danke und liebe Grüße

**Comment by HotLikeShit** [comment]
Selbe Problem seit 02.02.2021 - Kennt man schon die Ursache ?  Ist es wieder die PUSH Benachrichtigung ?

**Comment by Apollon77** [comment]
@n3ucr0n LOL ... du "klinkst dich" in nen fast 1 Jahr alten Thread ein??

-->> #628

**Comment by n3ucr0n** [comment]
Ja wie geschrieben, habe schon gesehen das es dazu aktuelle Beiträge gibt :-D
Hatte nach dem Problem gegoogled und bin auf diese Diskussion gestoßen.
Das es nicht der aktuelle ist, ist mir erst später aufgegangen (daher der Edit) :-)

Ich verfolge den von Dir verlinkten Beitrag bereits voller Interesse.
Danke für die Hilfe (und das Du trotzdem in diesen alten Beitrag antwortest :-) )

**Comment by tim414l** [comment]
Moin,
Ich habe seit 3 Tagen Probleme damit.
Bei mir läuft Garnichts mehr, da alles über summary abgefragt wird.

**Comment by Apollon77** [comment]
@tim414l Hast Du ZWEI Beiträge über deinem mal gelesen???
