### ISSUE TITLE
Routinen sind nicht sichtbar

### ISSUE THREAD

**Issue by MariusLang** [Apollon77/ioBroker.alexa2#369]
Die Routinen sind bei mir in der "Objekte"-Übersicht nicht sichtbar...

**Comment by Apollon77** [comment]
Bitte Screenshot zeigen. Routinen sind Unter den devices ... wenn wirklich nicht da,der Rest aber tut dann bitte debug log vom adapterstart (vom logfile von der Platte nicht aus dem Admin kopiert!!) an iobroker@fischer-ka.de mit Referenz auf das issue hier schicken.
