### ISSUE TITLE
device online status (indicator.reachable) and bluetooth wird nicht aktualisiert

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#37]
Ich hatte ein Echo device vom Strom genommen zum test. dabei hab ich 
festgestellt das der device online status (indicator.reachable) nicht aktualisiert wird.
Erst wenn die Adapter Instanz neu gestartet wird der online status geändert.

Gruß
Matten

**Comment by Apollon77** [comment]
Ja, das ist weil das aktuell nur einmalig ausgelesen wird. Muss ich ändern.

**Comment by liv-in-sky** [comment]
sollte der bluetooth status eigentlich geupdated werden nach der updatetime ? wenn ich bluetooth mit dem adapter verbinde und mit der sprache deaktiviere bekomme ich das disconnect nicht angezeigt - connected bleibt auf true - gruß

**Comment by Apollon77** [comment]
check 0.4.0 from GitHub and https://forum.iobroker.net/viewtopic.php?f=37&t=16095

**Comment by Germi79** [comment]
> Ja, das ist weil das aktuell nur einmalig ausgelesen wird. Muss ich ändern.

device online status (indicator.reachable) wird nicht aktualisiert

Hi, bei mir ist es immer noch so, hast du das denn schon ändern können ?

**Comment by Apollon77** [comment]
lol ... das issue sist seit 6 jahren geschlossen und endet mit "check version X" ... also was denkst du?

reachable ändert sich nur wenn amazon es reported und damit müssen die Push notifications an sein ... irgendwelche fehler davon im Log?
