### ISSUE TITLE
Screen off for Show devices

### ISSUE THREAD

**Issue by daniel-lo** [Apollon77/ioBroker.alexa2#377]
Hi my Echo Show 5 would be so much better if I wouldn't have to give the screen off command after I do anything with this "alarm clock". Is there any way to add this button to the object list .. so I can script this to my purpose.

Thinking on I can tap the screen to view the time but it won't go off without me telling it to. I have no Idea if a tap could be recognized?!

**Comment by Apollon77** [comment]
Can you do it Via Alexa app? If not (and this is my info) then also the adapter can not. Sorry

**Comment by Apollon77** [comment]
Check 3.4.0 with textCommand

**Comment by daniel-lo** [comment]
@Apollon77
getestet .. funktionert .. super .. VIELEN DANK!

**Comment by Apollon77** [comment]
:-)

**Comment by daniel-lo** [comment]
@Apollon77
 Hat bei mir aufgehört zu funktioneren .. finde den Grund noch nicht .. hatte Show5 zurücksetzen müssen .. vielleicht liegt es daran .. wäre nett wenn Du bestätigen könntest, dass es bei Dir noch funktioniert.

**Comment by Apollon77** [comment]
Kann ich nicht, habe keinen Show5 ..., Bitte im Forum melden, da können ggf andere User helfen
