### ISSUE TITLE
Einstellung für "Ton für Benachrichtugung" in Adapter

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#379]
Man kann ja über die App (vermutlich ;)) oder alexa.amazon.de den Ton für Benachrichtigungen an- und ausschalten.
Wäre toll, wenn es dafür einen true/false Datenpunkt gäbe, z.B.

alexa2.0.Echo-Devices.XXXXX.Commands.notificationSound

**Comment by Apollon77** [comment]
Kan. man nicht. EInfach "speak" nutzen (ohne Ton) oder "die benachrichtigungen mit ton

**Comment by Apollon77** [comment]
PS: Oder wo in der App kann man das ausschalten?

**Comment by padrino-x** [comment]
Mir geht es um Benachrichtigungen/Nachrichten (gelber Ring), nicht das ssml announcement. =)
Einstellen kann man hier (im Gerät):
 
![2020-02-17 23 34 18](https://user-images.githubusercontent.com/40962599/74690222-8558cb80-51de-11ea-8989-aa6dec937212.png)

**Comment by padrino-x** [comment]
Ein "do not disturb" würde ja das ganze komplett blockieren.
So könnte schnell in Skripten nur den Ton deaktivieren, aber immer noch alles mitbekommen.

**Comment by Apollon77** [comment]
I need to check this

**Comment by padrino-x** [comment]
Sollte man hier eigentlich Englisch schreiben? =)

Falls es etwas hilft, man findet es unter

https://alexa.amazon.de/spa/index.html#settings/device/sounds/serialNumber/deviceType

**Comment by swilalaa** [comment]
+1 scriptable mute would be great in order to receive text notification but deactivate audio eg. during meetings

**Comment by padrino-x** [comment]
@swilalaa 
If you want to support this, you shoud "+1" the first post.
The (positive) reactions is what counts. ;)

**Comment by Apollon77** [comment]
Do not disturb" mode is already available ... this is something different

**Comment by realwax** [comment]
Since yesterday my say or ssml commands are surrounded by a sinus tone in the beginning and end. Pretty annoying. I guess this is the tone you were talking about. It was not there until yet, haven't changed anything. Is there a way to turn it off? Haven't found a setting in the adapter or object  nor a feature in the app. Thank you!

**Comment by Apollon77** [comment]
will be added in next version

**Comment by Apollon77** [comment]
see https://forum.iobroker.net/post/823454
