### ISSUE TITLE
Drop In vom Echo Dot zum Handy

### ISSUE THREAD

**Issue by LJSven** [Apollon77/ioBroker.alexa2#382]
Kann man vom Echo Dot via Adapter einen Drop In zum Handy machen?

**Comment by Apollon77** [comment]
Kannst Du mit der Alexa App einen Drop in von einem Echo Dot zu nem anderen handy oder Gerät machen? Ich wüsste nicht wie ... vor allem falls mehrere Handies dann welches?

**Comment by LJSven** [comment]
Vom Handy zum Echo geht es ohne Probleme.

**Comment by Apollon77** [comment]
Ja aber nur "von dem handy wo du die app gerade benutzt", korrekt?

**Comment by LJSven** [comment]
Wie meinst du das? 
Handy in die Hand nehmen
Amazaon Alexa öffnen
DropIn Echo auswählen
Verbindung wird hergestellt

So funktioniert es - ich meine ich kann auch eine Verbindung vom Echo zum Handy aufbauen - ob es DropIn ist, oder Call weiß ich nicht. Werde es heute Abend mal probieren.

**Comment by Apollon77** [comment]
Ich meine folgendes: Der Alexa2 Adapter simuliert quasi ein handy und tut so als ob die App darauf läuft. Der Alexa2 Adapter selbst kann aber kein DropIn aufbauen. Und das ist das problem. Dein echtes handy ist quasi ein anderes Gerät als das was der Adapter simuliert.

Damit müsste - damit es mit deinem Hand geht - der Adapter DropIn Verbindungen zwischen anderen geräten aubauen können und selbst raus sein. denke das das nicht geht

**Comment by LJSven** [comment]
Wenn ich vor meinem Echo Dot stehe und sage "Alexa, rufe Sven mobil an" - erscheint folgendes auf meinem Handy - ohne das ich die App geöffnet habe...

![Bildschirmfoto 2020-02-20 um 19 33 49](https://user-images.githubusercontent.com/8560588/74966985-6a719b80-5418-11ea-802e-cac361913867.png)

![Foto 20 02 20, 19 31 02](https://user-images.githubusercontent.com/8560588/74967023-7cebd500-5418-11ea-8238-5da0988ccf4c.png)

**Comment by Apollon77** [comment]
Ja weil das dann der Echo triggert. Das kann nur von einem device getriggert werden. Der Adapter könnte das vllt auch aber hat ja kein Mikrofon und keinen Lautsprecher. Um selbst das Gespräch dann zu führen ...

Was du bräuchtest wäre „Alexa, sage Echo Wohnzimmer den Sven abzuteufen“ und das geht meines Wissens nach halt nicht.

**Comment by Apollon77** [comment]
... und man müsste das über einen Button oder Auswahl in der Alexa App anstoßen können. Dann könnte man es für den Adapter bauen.

**Comment by LJSven** [comment]
Okay, ich will ja einen bestimmten Echo triggern und der hat ein Mikro. Über die Alexa App kann ich den Echo auch anrufen. Finde halt nicht, dass ich das über Routinen steuere... da ist vermutlich das Problem, oder? Wäre halt auch interessant um z.B. einen Notruf abzusetzen.

**Comment by Apollon77** [comment]
Der Adapter ist halt kein echtes Handy :-(

**Comment by Pocky2507** [comment]
Gibt es denn irgendwie die Möglichkeit vom Adapter einen Datenpunkt anlegen zu lassen wenn ein Drop In statt findet? True/False
Dann könnte mann über ein Blockly eine Alarmeldung ausgeben lassen das ein Drop In stattfindet.
Denn ein Drop In ist ja sofort aktiv ohne das extra annehmen zu müssen.

**Comment by Apollon77** [comment]
Zeigt die Alexa App auf einem Handy aktuell an wenn ein dropin zwischen zwei anderen Geräten läuft? Hätte ich noch nicht gesehn. :-( dann leider nicht.

**Comment by Apollon77** [comment]
Ich habe bissl Recherchiert ... sehe aktuell keinen echten Weg

**Comment by Apollon77** [comment]
Check 3.4.0 with textCommand

**Comment by LJSven** [comment]
Gibt es ein Tutorial?

**Comment by Apollon77** [comment]
Nee :-) Wie machst Du nen drop in per SPrache? Sende das als TextCommand ...

**Comment by LJSven** [comment]
Okay! Hatte es am Anfang falsch gedeutet und gedacht du meinst
text2command. Es scheint aber zu gehen! 

Von meinem iPhone gesendet
