### ISSUE TITLE
Leuchtring als Lichtsignal

### ISSUE THREAD

**Issue by Hans-Zwiesel** [Apollon77/ioBroker.alexa2#385]
Hallo Apollon77,
die Alexa Echo Dot´s haben ja so einen schönen Lichtring mit allen Farben.

Ist es denn nicht möglich, diesen Lichtring mit ioBroker anzusteuern, für Alarm bzw.
sonstige Benachrichtigungen?

VG
hanss

**Comment by Apollon77** [comment]
Kannst Du es mit der Alexa App?? Ich kenne leider keinen Weg

**Comment by Hans-Zwiesel** [comment]
Nein, leider nicht. Es gibt aber einen Alexa Skill "Nachtlicht" der das kann, wenn auch nicht
mit verschiedenen Farben.

**Comment by padrino-x** [comment]
@Hans-Zwiesel 
Soweit ich das zu wissen glaube ;) trickst "Nachtlicht" auch nur indem einfach "Stille" sendet und das Leuchten ist die "stumme Sprachausgabe". :)

**Comment by Hans-Zwiesel** [comment]
> 
> 
> @Hans-Zwiesel
> Soweit ich das zu wissen glaube ;) trickst "Nachtlicht" auch nur indem einfach "Stille" sendet und das Leuchten ist die "stumme Sprachausgabe". :)
> Amazon gewährt Entwicklickern wohl leider keinen Zugriff auf den Leuchtring, bzw. dessen Farben.

Ich habe mich der Hoffnung hingegeben, dass jemand, der die Fähigkeit hat einen Alexa Adapter zu
schreiben, einen Draht zu Amazon hat und das dort evtl. anzuregen.

**Comment by Apollon77** [comment]
Hehe ... nicht wirklich. Der Adapter basiert auf Reverse Engineering der Alexa App und nutzt unerlaubter Weise die gleichen Schnittstellen. Daher: was die Alexa App kann geht mit dem Adapter. Mehr nicht.

**Comment by Hans-Zwiesel** [comment]
"Reverse Engineering"
Hallo Frühaufsteher - ich hatte früher auch einmal mit Disassembler zu tun und weiß wie
mühsam das ist. Hut ab, großartig.
