### ISSUE TITLE
Add alexa2.0.Echo-Devices.XXXX.Info.firmwareVersion

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#398]
Would be a nice addition, if the installed firmware version c/would be display under "Info" of Alexa2. =)

**Comment by Apollon77** [comment]
In the devices data only a "softwareVersion":"651614420" is in ... no idea if this really brings that much of an benefit

**Comment by padrino-x** [comment]
Well, that's exactely what I was looking for. ;)
If it wouldn'T be too hard to implement, I think an addition to info wouldn't hurt. =)

**Comment by Apollon77** [comment]
done in 3.1.2, on GitHub
