### ISSUE TITLE
Alexa Steuerung über Blockly

### ISSUE THREAD

**Issue by AlexStephenLytton** [Apollon77/ioBroker.alexa2#40]
Hallo zusammen!

Wenn ich versuche, testhalber in Blockly jede Minute eine Sprachausgabe über meinen Echo Dot zu realisieren finde ich im Log folgenden Fehler:

javascript.0 | 2018-07-27 09:08:00.500 | warn | at Object.<anonymous> (script.js.common.Alexa:2:3)
-- | -- | -- | --
javascript.0 | 2018-07-27 09:08:00.500 | warn | Wrong type of alexa2.0.Echo-Devices.G090LF0970340A6F.Commands.speak: "number". Please fix, while deprecated and will not work in next versions.

Sprachausgabe erfolgt leider keine, teilweise stürzt der Alexa2 Adapter auch ab. Installiert ist die Version 0.3.4

ioBroker läuft auf Windows 10

**Comment by AlexStephenLytton** [comment]
Nachtrag:

Der Fehlermeldung geht auch eine weitere Fehlermeldung voraus:


alexa2.0 | 2018-07-27 09:11:34.866 | warn | Device-type:A81PNL0A63P93 (VOLUME_SETTING,AUDIO_PLAYER,AUDIBLE,CHANGE_NAME,PERSISTENT_CONNECTION,KINDLE_BOOKS,SLEEP,TUNE_IN,DREAM_TRAINING,I_HEART_RADIO,PEONY,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,TI
-- | -- | -- | --
alexa2.0 | 2018-07-27 09:11:34.866 | warn | Disabling some commands for device because of unknown type. Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted

**Comment by Apollon77** [comment]
Zur ersten Meldung von Javascript: Was schreibst Du denn rein? Der Datentyp des "speak" States ist Sting, also bitte auch eine Zeichenkette reinschreiben und keine Zahl!

>teilweise stürzt der Alexa2 Adapter auch ab

Welche Fehlermeldung? Kann sein das es daran liegt das Du einen Falschen Datentyp reinschreibst. Fixen bitte

Die andere Meldung ist ok, wird in nächste Version aufgenommen. hat aktuell nur die AUswirkung das einige States bei Dir nicht da sind.
Was ist das denn für ein Device? Gib mal Infos dazu bitte

**Comment by AlexStephenLytton** [comment]
Ich habe im Blocklyscript 2 verschiedene Dinge versucht:

1) zuerst wollte ich den Temperaturwert der Netatmo Wetterstation auslesen lassen - schlug fehl... Laut der Fehlermeldung dachte ich auch daran, das es vielleicht daran liegt, das es kein string ist und habe dann
2) einfach nur einen Text ("Dies ist ein Test") versucht ausgeben zu lassen... es war zwar das Textfeld in Blockly, ich hab trotzdem versucht das ganze mit und ohne Anführungszeichen zu schreiben - beide male kein Erfolg!

Welches Device meinst Du?

Die Fehlermeldung zum Absturz:


host.Win10ServerHome | 2018-07-27 09:38:00.125 | info | Restart adapter system.adapter.alexa2.0 because enabled
-- | -- | -- | --
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | instance system.adapter.alexa2.0 terminated with code 0 (OK)
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: at tryOnImmediate (timers.js:768:5)
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: at runCallback (timers.js:810:20)
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: at Immediate._onImmediate (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:3429:38)
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: at Adapter.emit (events.js:214:7)
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: at emitTwo (events.js:126:13)
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: at Adapter.adapter.on (C:\ioBroker\node_modules\iobroker.alexa2\main.js:184:77)
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: at Object.setOrUpdateObject [as Echo-Devices.G090LF0970340A6F.Commands.speak] (C:\ioBroker\node_modules\iobroker.alexa2\main.js:734:108)
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: at AlexaRemote.Alexa.iterateMultiroom (C:\ioBroker\node_modules\iobroker.alexa2\main.js:567:16)
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: at iterateMultiroom (C:\ioBroker\node_modules\iobroker.alexa2\main.js:734:172)
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: at AlexaRemote.sendSequenceCommand (C:\ioBroker\node_modules\iobroker.alexa2\node_modules\alexa-remote2\alexa-remote.js:804:35)
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: TypeError: value.replace is not a function
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: at tryOnImmediate (timers.js:768:5)
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: at runCallback (timers.js:810:20)
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: at Immediate._onImmediate (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:3429:38)
host.Win10ServerHome | 2018-07-27 09:38:00.125 | error | Caught by controller[1]: at Adapter.emit (events.js:214:7)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[1]: at emitTwo (events.js:126:13)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[1]: at Adapter.adapter.on (C:\ioBroker\node_modules\iobroker.alexa2\main.js:184:77)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[1]: at Object.setOrUpdateObject [as Echo-Devices.G090LF0970340A6F.Commands.speak] (C:\ioBroker\node_modules\iobroker.alexa2\main.js:734:108)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[1]: at AlexaRemote.Alexa.iterateMultiroom (C:\ioBroker\node_modules\iobroker.alexa2\main.js:567:16)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[1]: at iterateMultiroom (C:\ioBroker\node_modules\iobroker.alexa2\main.js:734:172)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[1]: at AlexaRemote.sendSequenceCommand (C:\ioBroker\node_modules\iobroker.alexa2\node_modules\alexa-remote2\alexa-remote.js:804:35)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[1]: TypeError: value.replace is not a function
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[0]: at tryOnImmediate (timers.js:768:5)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[0]: at runCallback (timers.js:810:20)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[0]: at Immediate._onImmediate (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:3429:38)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[0]: at Adapter.emit (events.js:214:7)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[0]: at emitTwo (events.js:126:13)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[0]: at Adapter.adapter.on (C:\ioBroker\node_modules\iobroker.alexa2\main.js:184:77)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[0]: at Object.setOrUpdateObject [as Echo-Devices.G090LF0970340A6F.Commands.speak] (C:\ioBroker\node_modules\iobroker.alexa2\main.js:734:108)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[0]: at AlexaRemote.Alexa.iterateMultiroom (C:\ioBroker\node_modules\iobroker.alexa2\main.js:567:16)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[0]: at iterateMultiroom (C:\ioBroker\node_modules\iobroker.alexa2\main.js:734:172)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[0]: at AlexaRemote.sendSequenceCommand (C:\ioBroker\node_modules\iobroker.alexa2\node_modules\alexa-remote2\alexa-remote.js:804:35)
host.Win10ServerHome | 2018-07-27 09:38:00.109 | error | Caught by controller[0]: TypeError: value.replace is not a function

**Comment by Apollon77** [comment]
ja liegt daran das es kein String ist. Also Zahlen sind böse. Kann ich in einem Update abfangen.

zeichenkette sollte tun, Wichtig in Blockly "STEURE" vrwenden als block zum schreiben!!

**Comment by AlexStephenLytton** [comment]
Auch dahingehend hab ich schon Steuer und aktualisiere ausprobiert...

**Comment by Apollon77** [comment]
Es muss "steure sein" und ein String.

Bitte versuchen und im zweifel Debug-Log (aus dem Logfile auf Platte unter /opt/iobroker/log!!) senden von so einer Änderung Da steht dann ein "state changed" mit dem Wert der ankam. Wenn da nicht das richtige drin steht was Du reinschreibst dann machst Du da was falsch. SOnst sind die Zeilen danach dann interessant

**Comment by AlexStephenLytton** [comment]
So... nochmal getestet....

Blockly script (in code angezeigt) : 

schedule("* * * * *", function () {
  setState("alexa2.0.Echo-Devices.G090LF0970340A6F.Commands.speak"/*speak*/, 'Dies ist ein Test');
});

Log gibt folgendes her:


  |   |   |  
-- | -- | -- | --
javascript.0 | 2018-07-27 10:52:00.956 | warn | script.js.common.Alexa_Test: setForeignState(id=alexa2.0.Echo-Devices.G090LF0970340A6F.Commands.speak, state=24.5) - was not executed, while debug mode is active
javascript.0 | 2018-07-27 10:52:00.956 | warn | at Object.<anonymous> (script.js.common.Alexa_Test:3:3)
javascript.0 | 2018-07-27 10:52:00.956 | warn | Wrong type of alexa2.0.Echo-Devices.G090LF0970340A6F.Commands.speak: "number". Please fix, while deprecated and will not work in next versions.
javascript.0 | 2018-07-27 10:52:00.956 | warn | script.js.common.Alexa_Test: setForeignState(id=alexa2.0.Echo-Devices.G090LF0970340A6F.Commands.speak, state="Dies ist ein Test") - was not executed, while debug mode is active
host.Win10ServerHome | 2018-07-27 10:52:00.110 | info | Restart adapter system.adapter.alexa2.0 because enabled
host.Win10ServerHome | 2018-07-27 10:52:00.110 | error | instance system.adapter.alexa2.0 terminated with code 0 (OK)
host.Win10ServerHome | 2018-07-27 10:52:00.110 | error | Caught by controller[2]: at tryOnImmediate (timers.js:768:5)
host.Win10ServerHome | 2018-07-27 10:52:00.110 | error | Caught by controller[2]: at runCallback (timers.js:810:20)
host.Win10ServerHome | 2018-07-27 10:52:00.110 | error | Caught by controller[2]: at Immediate._onImmediate (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:3429:38)
host.Win10ServerHome | 2018-07-27 10:52:00.110 | error | Caught by controller[2]: at Adapter.emit (events.js:214:7)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[2]: at emitTwo (events.js:126:13)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[2]: at Adapter.adapter.on (C:\ioBroker\node_modules\iobroker.alexa2\main.js:184:77)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[2]: at Object.setOrUpdateObject [as Echo-Devices.G090LF0970340A6F.Commands.speak] (C:\ioBroker\node_modules\iobroker.alexa2\main.js:734:108)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[2]: at AlexaRemote.Alexa.iterateMultiroom (C:\ioBroker\node_modules\iobroker.alexa2\main.js:567:16)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[2]: at iterateMultiroom (C:\ioBroker\node_modules\iobroker.alexa2\main.js:734:172)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[2]: at AlexaRemote.sendSequenceCommand (C:\ioBroker\node_modules\iobroker.alexa2\node_modules\alexa-remote2\alexa-remote.js:804:35)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[2]: TypeError: value.replace is not a function
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[1]: at tryOnImmediate (timers.js:768:5)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[1]: at runCallback (timers.js:810:20)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[1]: at Immediate._onImmediate (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:3429:38)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[1]: at Adapter.emit (events.js:214:7)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[1]: at emitTwo (events.js:126:13)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[1]: at Adapter.adapter.on (C:\ioBroker\node_modules\iobroker.alexa2\main.js:184:77)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[1]: at Object.setOrUpdateObject [as Echo-Devices.G090LF0970340A6F.Commands.speak] (C:\ioBroker\node_modules\iobroker.alexa2\main.js:734:108)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[1]: at AlexaRemote.Alexa.iterateMultiroom (C:\ioBroker\node_modules\iobroker.alexa2\main.js:567:16)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[1]: at iterateMultiroom (C:\ioBroker\node_modules\iobroker.alexa2\main.js:734:172)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[1]: at AlexaRemote.sendSequenceCommand (C:\ioBroker\node_modules\iobroker.alexa2\node_modules\alexa-remote2\alexa-remote.js:804:35)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[1]: TypeError: value.replace is not a function
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[0]: at tryOnImmediate (timers.js:768:5)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[0]: at runCallback (timers.js:810:20)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[0]: at Immediate._onImmediate (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:3429:38)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[0]: at Adapter.emit (events.js:214:7)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[0]: at emitTwo (events.js:126:13)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[0]: at Adapter.adapter.on (C:\ioBroker\node_modules\iobroker.alexa2\main.js:184:77)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[0]: at Object.setOrUpdateObject [as Echo-Devices.G090LF0970340A6F.Commands.speak] (C:\ioBroker\node_modules\iobroker.alexa2\main.js:734:108)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[0]: at AlexaRemote.Alexa.iterateMultiroom (C:\ioBroker\node_modules\iobroker.alexa2\main.js:567:16)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[0]: at iterateMultiroom (C:\ioBroker\node_modules\iobroker.alexa2\main.js:734:172)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[0]: at AlexaRemote.sendSequenceCommand (C:\ioBroker\node_modules\iobroker.alexa2\node_modules\alexa-remote2\alexa-remote.js:804:35)
host.Win10ServerHome | 2018-07-27 10:52:00.094 | error | Caught by controller[0]: TypeError: value.replace is not a function



Achso übrigens (vielleicht hilft's ja) aus Deinen Pfadangaben bin ich mir nicht ganz sicher ob Du das im eingangspost gelesen hast - das ganze läuft auf ner Win10 Maschine - NICHT Linux

**Comment by Apollon77** [comment]
will be fixed in 0.3.5 ... denke der crash kommt immer noch wegen der Nummer und nicht wegen dem text ... aber bitte mit 0.3.5 neu testen wenns drausssen ist. Info im Forum kommt dann
