### ISSUE TITLE
Got a lot of error in the log 

### ISSUE THREAD

**Issue by MattL0** [Apollon77/ioBroker.alexa2#403]
alexa2.0 | 2020-03-13 15:20:42.961 | info | (27925) Subscribing to states...
-- | -- | -- | --
alexa2.0 | 2020-03-13 15:20:30.929 | info | (27925) Device-type:A3NWHXTQ4EBCZS (MICROPHONE,VOLUME_SETTING)
alexa2.0 | 2020-03-13 15:20:30.929 | info | (27925) Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-03-13 15:20:30.929 | info | (27925) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-03-13 15:20:27.662 | info | (27925) Proxy IP not set, use first network interface (192.168.1.xxx) instead
alexa2.0 | 2020-03-13 15:20:27.596 | info | (27925) starting. Version 3.0.7 in /opt/iobroker/node_modules/iobroker.alexa2, node: v10.19.0
alexa2.0 | 2020-03-13 15:20:21.360 | info | (22058) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
alexa2.0 | 2020-03-13 15:20:21.358 | info | (22058) Got terminate signal TERMINATE_YOURSELF
alexa2.0 | 2020-03-13 15:20:21.357 | info | (22058) Alexa-Push-Connection Error: Error: WebSocket was closed before the connection was established
alexa2.0 | 2020-03-13 15:15:52.290 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 15:15:52.290 | info | (22058) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 15:15:47.139 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 15:10:23.437 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 15:10:23.437 | info | (22058) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 15:10:18.372 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 15:10:18.372 | info | (22058) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 15:10:13.214 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 15:07:17.541 | info | (22058) Alexa-Push-Connection established. Disable Polling
alexa2.0 | 2020-03-13 15:06:49.341 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 15:06:49.341 | info | (22058) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 15:06:44.186 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 15:04:38.587 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:58:14.106 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:42:44.133 | info | (22058) Alexa-Push-Connection established. Disable Polling
alexa2.0 | 2020-03-13 14:42:38.849 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:42:38.849 | info | (22058) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:42:33.719 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:42:33.718 | info | (22058) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:42:28.647 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:42:28.647 | info | (22058) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:42:23.575 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:42:23.575 | info | (22058) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:42:18.483 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:42:18.483 | info | (22058) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:42:13.416 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:42:13.415 | info | (22058) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:42:08.351 | info | (22058) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:41:49.598 | info | (22058) Deleting the following states: ["Smart-Home-Devices.151e3d69-dfeb-4d0c-a1b0-95cb04a186db","Smart-Home-Devices.c93f7f1e-57f7-4864-8640-a00cb927e4fd","Smart-Home-Devices.4e719857-d03c-4c13-b5a0
alexa2.0 | 2020-03-13 14:41:49.597 | info | (22058) Subscribing to states...
alexa2.0 | 2020-03-13 14:41:38.684 | info | (22058) Device-type:A3NWHXTQ4EBCZS (VOLUME_SETTING,MICROPHONE)
alexa2.0 | 2020-03-13 14:41:38.684 | info | (22058) Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-03-13 14:41:38.683 | info | (22058) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-03-13 14:41:35.833 | info | (22058) Proxy IP not set, use first network interface (192.168.1.3) instead
alexa2.0 | 2020-03-13 14:41:35.777 | info | (22058) starting. Version 3.0.7 in /opt/iobroker/node_modules/iobroker.alexa2, node: v10.19.0
alexa2.0 | 2020-03-13 14:41:05.189 | info | (21904) Terminated (NO_ERROR): Without reason
alexa2.0 | 2020-03-13 14:41:05.189 | info | (21904) terminating
alexa2.0 | 2020-03-13 14:41:05.178 | error | at TLSSocket.socketOnData (_http_client.js:451:20)
alexa2.0 | 2020-03-13 14:41:05.178 | error | at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
alexa2.0 | 2020-03-13 14:41:05.178 | error | at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
alexa2.0 | 2020-03-13 14:41:05.178 | error | at ClientRequest.EventEmitter.emit (domain.js:448:20)
alexa2.0 | 2020-03-13 14:41:05.178 | error | at ClientRequest.emit (events.js:203:15)
alexa2.0 | 2020-03-13 14:41:05.178 | error | at ClientRequest.req.on (/opt/iobroker/node_modules/alexa-remote2/node_modules/ws/lib/websocket.js:578:27)
alexa2.0 | 2020-03-13 14:41:05.178 | error | at WebSocket.EventEmitter.emit (domain.js:448:20)
alexa2.0 | 2020-03-13 14:41:05.178 | error | at WebSocket.emit (events.js:198:13)
alexa2.0 | 2020-03-13 14:41:05.178 | error | at WebSocket.websocket.on (/opt/iobroker/node_modules/alexa-remote2/alexa-wsmqtt.js:127:111)
alexa2.0 | 2020-03-13 14:41:05.178 | error | at JSON.stringify (<anonymous>)
alexa2.0 | 2020-03-13 14:41:05.178 | error | (21904) TypeError: Converting circular structure to JSON
alexa2.0 | 2020-03-13 14:41:05.177 | error | (21904) uncaught exception: Converting circular structure to JSON
alexa2.0 | 2020-03-13 14:41:05.174 | info | (21904) Alexa-Push-Connection Error: Error: WebSocket was closed before the connection was established
alexa2.0 | 2020-03-13 14:41:05.173 | warn | (21904) Exception: TypeError: Converting circular structure to JSON
alexa2.0 | 2020-03-13 14:40:59.820 | info | (21904) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:40:59.820 | info | (21904) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:40:54.760 | info | (21904) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:40:54.760 | info | (21904) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:40:49.700 | info | (21904) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:40:49.700 | info | (21904) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:40:44.595 | info | (21904) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:40:44.595 | info | (21904) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:40:41.605 | info | (21904) Subscribing to states...
alexa2.0 | 2020-03-13 14:40:39.494 | info | (21904) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:40:39.494 | info | (21904) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:40:34.434 | info | (21904) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:40:34.433 | info | (21904) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:40:30.520 | info | (21904) Device-type:A3NWHXTQ4EBCZS (VOLUME_SETTING,MICROPHONE)
alexa2.0 | 2020-03-13 14:40:30.520 | info | (21904) Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-03-13 14:40:30.519 | info | (21904) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-03-13 14:40:29.367 | info | (21904) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:40:29.366 | info | (21904) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:40:27.008 | info | (21904) Proxy IP not set, use first network interface (192.168.1.3) instead
alexa2.0 | 2020-03-13 14:40:26.943 | info | (21904) starting. Version 3.0.7 in /opt/iobroker/node_modules/iobroker.alexa2, node: v10.19.0
alexa2.0 | 2020-03-13 14:39:56.293 | info | (21676) Terminated (NO_ERROR): Without reason
alexa2.0 | 2020-03-13 14:39:56.293 | info | (21676) terminating
alexa2.0 | 2020-03-13 14:39:56.282 | error | at TLSSocket.socketOnData (_http_client.js:451:20)
alexa2.0 | 2020-03-13 14:39:56.282 | error | at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
alexa2.0 | 2020-03-13 14:39:56.282 | error | at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
alexa2.0 | 2020-03-13 14:39:56.282 | error | at ClientRequest.EventEmitter.emit (domain.js:448:20)
alexa2.0 | 2020-03-13 14:39:56.282 | error | at ClientRequest.emit (events.js:203:15)
alexa2.0 | 2020-03-13 14:39:56.282 | error | at ClientRequest.req.on (/opt/iobroker/node_modules/alexa-remote2/node_modules/ws/lib/websocket.js:578:27)
alexa2.0 | 2020-03-13 14:39:56.282 | error | at WebSocket.EventEmitter.emit (domain.js:448:20)
alexa2.0 | 2020-03-13 14:39:56.282 | error | at WebSocket.emit (events.js:198:13)
alexa2.0 | 2020-03-13 14:39:56.282 | error | at WebSocket.websocket.on (/opt/iobroker/node_modules/alexa-remote2/alexa-wsmqtt.js:127:111)
alexa2.0 | 2020-03-13 14:39:56.282 | error | at JSON.stringify (<anonymous>)
alexa2.0 | 2020-03-13 14:39:56.282 | error | (21676) TypeError: Converting circular structure to JSON
alexa2.0 | 2020-03-13 14:39:56.282 | error | (21676) uncaught exception: Converting circular structure to JSON
alexa2.0 | 2020-03-13 14:39:56.279 | info | (21676) Alexa-Push-Connection Error: Error: WebSocket was closed before the connection was established
alexa2.0 | 2020-03-13 14:39:56.278 | warn | (21676) Exception: TypeError: Converting circular structure to JSON
alexa2.0 | 2020-03-13 14:39:50.746 | info | (21676) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:39:50.745 | info | (21676) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:39:45.690 | info | (21676) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:39:45.690 | info | (21676) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:39:42.915 | info | (21676) Deleting the following states: ["Smart-Home-Devices.151e3d69-dfeb-4d0c-a1b0-95cb04a186db","Smart-Home-Devices.c93f7f1e-57f7-4864-8640-a00cb927e4fd","Smart-Home-Devices.4e719857-d03c-4c13-b5a0
alexa2.0 | 2020-03-13 14:39:42.914 | info | (21676) Subscribing to states...
alexa2.0 | 2020-03-13 14:39:40.618 | info | (21676) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:39:40.617 | info | (21676) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:39:35.546 | info | (21676) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:39:35.546 | info | (21676) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:39:31.979 | info | (21676) Device-type:A3NWHXTQ4EBCZS (VOLUME_SETTING,MICROPHONE)
alexa2.0 | 2020-03-13 14:39:31.979 | info | (21676) Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-03-13 14:39:31.979 | info | (21676) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-03-13 14:39:30.472 | info | (21676) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 14:39:30.472 | info | (21676) Alexa-Push-Connection Error: Error: read ECONNRESET
alexa2.0 | 2020-03-13 14:39:28.411 | info | (21676) Proxy IP not set, use first network interface (192.168.1.3) instead
alexa2.0 | 2020-03-13 14:39:28.347 | info | (21676) starting. Version 3.0.7 in /opt/iobroker/node_modules/iobroker.alexa2, node: v10.19.0

**Comment by Apollon77** [comment]
Seems that Amazon had problems ... I can fix that one logging bug

**Comment by MattL0** [comment]
did you mean can't or can?

**Comment by MattL0** [comment]
a little different if that can helps 


alexa2.0 | 2020-03-13 19:48:42.716 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
-- | -- | -- | --
alexa2.0 | 2020-03-13 19:48:42.716 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:48:37.664 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:48:37.663 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:48:32.613 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:48:32.612 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:48:27.480 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:48:27.479 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:48:22.395 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:48:22.395 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:48:17.384 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:48:17.384 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:48:12.334 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:48:12.334 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:48:07.316 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:48:07.316 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:48:02.304 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:48:02.304 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:47:57.251 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:47:57.251 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:47:52.242 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:47:52.242 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:47:47.230 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:47:47.230 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:47:42.216 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:47:42.216 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:47:37.166 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:47:37.165 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:47:32.154 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:47:32.154 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:47:27.046 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:47:27.046 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:47:21.909 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:47:21.909 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:47:16.898 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:47:16.897 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:47:11.886 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:47:11.886 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:47:06.874 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:47:06.873 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:47:01.859 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:47:01.859 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:46:56.849 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:46:56.849 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:46:51.838 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:46:51.837 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:46:46.828 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:46:46.827 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:46:41.815 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:46:41.815 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:46:36.769 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:46:36.769 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:46:31.758 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:46:31.758 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:46:26.746 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:46:26.746 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:46:21.626 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:46:21.626 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:46:16.616 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:46:16.615 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:46:11.605 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:46:11.604 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:46:06.548 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:46:06.548 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:46:01.537 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:46:01.537 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:45:56.526 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:45:56.526 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:45:51.515 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:45:51.515 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:45:46.505 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:45:46.505 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:45:41.493 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:45:41.493 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:45:36.481 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:45:36.481 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:45:31.469 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:45:31.469 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:45:26.415 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:45:26.415 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:45:21.304 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:45:21.304 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:45:16.290 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:45:16.290 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:45:11.280 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:45:11.280 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443
alexa2.0 | 2020-03-13 19:45:06.270 | info | (14819) Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
alexa2.0 | 2020-03-13 19:45:06.270 | info | (14819) Alexa-Push-Connection Error: Error: connect ECONNREFUSED 127.0.0.1:443

**Comment by Apollon77** [comment]
I will. But this only fixes the crash. The reconnections ob the websockets connection to amazon was a Network thing or their services down.

**Comment by MattL0** [comment]
ok understood.  yes seems to be back since 1 hour.


alexa2.0 | 2020-03-13 19:57:46.559 | info | (14819) Alexa-Push-Connection established. Disable Polling
-- | -- | -- | --

**Comment by Apollon77** [comment]
that hie tries to connect to 127.0.0.1 seems to be an DNS problem or such ... but if works now great !:-)

**Comment by MattL0** [comment]
so you think i should check my local dns config files ?

**Comment by Apollon77** [comment]
if it now works again ... it's ok

**Comment by MattL0** [comment]
Thanks
