### ISSUE TITLE
unknown device / unbekanntes Gerät erkannt

### ISSUE THREAD

**Issue by ioBroker22** [Apollon77/ioBroker.alexa2#409]
Der Adapter scheint die 3. Generation des Echo (der große) noch nicht zu kennen und bittet mich freundlich um eine Issue Erstellung bei GitHub.
Um dieses Gerät handelt es sich:
https://www.amazon.de/dp/B07P64LFFH/ref=s9_acsd_al_bw_c2_x_2_i?pf_rd_m=A3JWKAKR8XB7XF&pf_rd_s=merchandised-search-2&pf_rd_r=017CSP4CAVMQB99XSBC9&pf_rd_t=101&pf_rd_p=e5ef179b-096b-48cc-8558-71f4057a0963&pf_rd_i=14100226031&th=1

Es reagiert genauso wie meine älteren Geräte auf die wenigen Befehle, die ich nutze (Lautstärke, Sprachausgabe).

Device-type:A3FX4UWTP28V1P (SET_LOCALE,TIMERS_AND_ALARMS,EARCONS,VOLUME_SETTING,AUX_SETTINGS,GOLDFISH,CHANGE_NAME,TUNE_IN,UPDATE_WIFI,KINDLE_BOOKS,DEREGISTER_DEVICE,PAIR_BT_SINK,PANDORA,SLEEP,AUDIO_CONTROLS,EQUALIZER_CONTROLLER_MIDRANGE,MUSIC_SKILL,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,TUPLE,SOUND_SETTINGS,PAIR_BT_SOURCE,AMAZON_MUSIC,EQUALIZER_CONTROLLER_TREBLE,MICROPHONE,FAR_FIELD_WAKE_WORD,BT_PAIRING_FLOW_V2,REQUIRES_OOBE_FOR_SETUP,ASCENDING_ALARM_VOLUME,PAIR_REMOTE,SUPPORT_CALENDAR_ALERT,REMINDERS,GADGETS,DREAM_TRAINING,GUARD_EARCON,ACTIVE_AFTER_FRO,SALMON,SUPPORTS_LOCALE_SWITCH,DS_VOLUME_SETTING,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,CUSTOM_ALARM_TONE,TUPLE_CATEGORY_A,POPTART,SUPPORTS_LOCALE,AUDIO_PLAYER,VOICE_TRAINING,ALEXA_PRESENCE,AUDIBLE,TAHOE_BYOD,EQUALIZER_CONTROLLER_BASS,DIALOG_INTERFACE_VERSION,SUPPORTS_SOFTWARE_VERSION,FLASH_BRIEFING,I_HEART_RADIO,LEMUR_ALPHA,PERSISTENT_CONNECTION)

Werden noch mehr Informationen benötigt?

**Comment by Apollon77** [comment]
Will be in 3.1.2 thank you!
