### ISSUE TITLE
Shuffle Playlists

### ISSUE THREAD

**Issue by Pocky2507** [Apollon77/ioBroker.alexa2#41]
Log vom abspielen einer Playlist und dann schalten auf Shuffle

[Neue Textdatei.txt](https://github.com/Apollon77/ioBroker.alexa2/files/2235135/Neue.Textdatei.txt)
[Neue Textdatei2.txt](https://github.com/Apollon77/ioBroker.alexa2/files/2235309/Neue.Textdatei2.txt)

**Comment by Apollon77** [comment]
Error found ... never worked :-( will come in 0.3.5 later today
