### ISSUE TITLE
Alexa Adapter schaltet automatisch Songs weiter

### ISSUE THREAD

**Issue by martingarber** [Apollon77/ioBroker.alexa2#411]
Hallo,

habe bemerkt, dass der Adapter Songs automatisch nach ca 5 Sekunden weiterschaltet, wenn sie über eine Multiroom Gruppe abgespielt werden.
Auch wenn die Wiedergabe über Alexa direkt gestartet wird.
Sobald ich den Adapter Alexa beende, werden die Songs wieder normal abgespielt. Starte ich den Adapter wieder, werden die Songs wieder automatisch nach Beginn weitergeschaltet.

Die Wiedergabe auf einzelne Echo funktioniert ohne Probleme.

Evtl. kann ich gerne Logs usw liefern.

Vielen Dank

lg

Martin

**Comment by Apollon77** [comment]
Der adapter macht nichts dergleichen. Er fragt maximal den Player Status ab und das hat manchmal Arg komische Auswirkungen.  Scheinbar ein bug bei Amazon. Bitte mal Version 3.3.1 vom GitHub Versuchen

**Comment by martingarber** [comment]
Hallo Ingo,

Danke für deine Antwort.
Leider macht die Version 3.1.2 von Github dasselbe. Sobald ich den Alexa Adapter stoppe, tritt das Problem nicht mehr auf. Starte ich ihn wieder, wird nach ca 10 Sekunden der Song weitergeschaltet. Anschließend  alle ca. 5 Sekunden.
Das Problem habe ich eigentlich erst seit Anfang dieser Woche.
Ich habe auch schon versucht alle Adapter, welche in Verbindung kommen könnten (Javascript usw.) zu deaktivieren. Leider ohne Erfolg.
Andere Musik Provider sind nicht betroffen.
Ich kann dir evtl. auch gerne sämtliche Logs zukommen lassen.

lg

Martin

**Comment by Apollon77** [comment]
Ja bitte debug log an iobroker@fischer-ka.de mit angabe dieser Issue nummer und genaue zeitpunkte dazuschreiben oder logzeilen wo er weitergeschaltet hat.

**Comment by martingarber** [comment]
Hi,

habe nun eine neue Gruppe erstellt. Problem tritt nicht mehr auf. Es hat mit der alten Gruppe zu tun.. Ich vermute mal es könnte mit den Umlauten zu tun haben, oder dass ich eine Gruppe hatte, welche Alexa als Standard schon hat. Der Name war "Überall".

p.s. Die Temperatur von den Alexas echo plus ist nicht möglich per adapter auszulesen, oder?

Viele Dank

lg

**Comment by xmace** [comment]
Bei mir genau das selbe!

Hab jetzt den Adapter komplett gelöscht und neu installiert. 
Passiert weiterhin auf beiden Mulitroomgruppen "Überall" und "Wohnung" -> Hat also nichts mit den Umlauten zu tun.

Lg,
Matze

**Comment by Apollon77** [comment]
Auch in der neuesten Version?

**Comment by martingarber** [comment]
Hi Ingo,

bei mir tritt das Problem leider auch wieder auf.. Somit hat es sicher
nichts mit dem namen zu tun. Meine Gruppe heisst zurzeit "Zuhause".
Adapter nutze ich die Version 3.1.2.
Das Problem legt sich auf einmal wieder und tritt dann wieder sporadisch
auf.
Ich hatte letztens das Problem 2 mal. einmal nach einem Stromausfall (alle
alexas wurden neu gestartet, ioBroker nicht, da er auf USV läuft) und
einmal gestern Abend als ich 2 Echos neu gestartet habe.
Weiß nicht ob es mit den Neustarts zusammenhängt, möchte dir diese Info
aber trotzdem zukommen lassen.

Sobald das Problem bei mir erneut auftritt, werde ich Logs liefern.

lg

Martin

Am Mi., 25. März 2020 um 23:59 Uhr schrieb Ingo Fischer <
notifications@github.com>:

**Comment by martingarber** [comment]
Hallo Ingo,

Problem ist soeben wieder aufgetreten. Habe dir die Debug logs per Email geschickt.

Vielen Dank

lg

Martin

**Comment by xmace** [comment]
Also ich habe meine Multiroom Gruppen gelöscht und neu angelegt, seitdem keine Probleme mehr.
Lg

**Comment by xmace** [comment]
> Auch in der neuesten Version?

ja Problem gab es bei mir erst seit dem Update auf die neuste Version. Bin dann zurück auf die Version davor, Problem bestand aber weiterhin.

**Comment by Apollon77** [comment]
neu war? alt ist? Versionsnummern bitte :-) letzte ist 3.1.2 ...

**Comment by xmace** [comment]
Sorry war vorher unterwegs.

Problem aufgetreten seit upgrade von 3.0.8 auf 3.1.2
Dann downgrade auf 3.0.8 - Problem bestand weiterhin
Wieder upgrade auf 3.1.2 - Problem bestand weiterhin
Dann Multiroom Gruppen gelöscht und mit identischem Namen neu angelegt -> Problem gelöst

**Comment by xmace** [comment]
Problem ist bei mir auch seit einigen Wochen wieder zurück.

Der Alexa Adapter ist leider für micht aktuell unbenutzbar weil Musik hören über Spotify in der Wohnung nicht mehr geht ohne dass alle 2 Sekunden das Lied weitergeschaltet wird.

AdapterVersion: 3.1.2

**Comment by xmace** [comment]
Player Info Aktualisierung deaktivieren mit "0" Sekunden funktioniert leider auch nicht. Wird weiterhin upgedated?

Thxx

**Comment by Apollon77** [comment]
> Wird weiterhin upgedated?

Ja

**Comment by xmace** [comment]
Sorry falsch ausgedrückt: Wie kann ich die Aktualisierung des Player Status deaktivieren?
Vielleicht löst es das Problem fürs erste

**Comment by Apollon77** [comment]
Sobald ich zeit neben den andern 50 ioBroker Baustellen finde.

**Comment by Apollon77** [comment]
hopefully duplicate of #447 please reopen if not fixed by next version (3.2+)
