### ISSUE TITLE
Echo-Device-Name of Virtual Devices (Handy,...) not shown in history

### ISSUE THREAD

**Issue by do1osc** [Apollon77/ioBroker.alexa2#414]
Hello,

If you use the Alexa-app on iPhone, and press PTT, the input-Text will not registered by the History "Echo-Device-Name" datapoint.

Is it possible to see external devices (mobile phones) in the history, too ?

**Comment by Apollon77** [comment]
If it is not in the datapoint then the data are not delivered by amazon ... you can enable debug mode and try it and you should see in the log what’s available at all ...
