### ISSUE TITLE
Alexa übergibt keine Spotify Informationen mehr

### ISSUE THREAD

**Issue by fabe1999** [Apollon77/ioBroker.alexa2#415]
Hallo,
Als erstes mal Danke für diesen super tollen Adapter!
Leider habe ich seit ca 3 Wochen ein Problem mit dem auslesen von Songinformationen aus Spotify.
Ich habe bereits einiges probiert wie Neuinstallation und Neuanmeldung des Adapters, leider immer ohne Erfolg. Die Objektknoten im ioBroker bleiben leer.
Habe jetzt mal das Log angeschaut und gesehen das Alexa keine Informationen mehr übergibt:
`alexa2.0	2020-03-21 16:21:38.619	debug	(1600) State changed alexa2.0.Echo-Devices.G50488473DH.Player.currentTitle: {"val":"","ack":true,"ts":1584804098576,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":15847081`
Das gilt für die meißten infos. Play/Pause funktioniert aber nach wie vor und auch die Shuffle funktion wird richtig angezeigt.
Leider kann ich es nicht mit amazon Musik versuchen, bei Radiowiedergabe über TuneIn scheint es allerdings noch zu funktionieren.
Weitere Logdaten sind angehängt.

Danke und viele Grüße
fabe1999
[log.txt](https://github.com/Apollon77/ioBroker.alexa2/files/4363210/log.txt)

**Comment by Apollon77** [comment]
Bitte vollständges Log aus dem Logfile  auf Platte liefern - Admin scheidet Zeilen ab. Der erste Blick zeigt allerdings das in den von Amazon zurückgegebenen Daten einfach alles leer ist. Also sollte auch die Amazon Alexa App keine Daten anzeigen , oder ist da was da?

**Comment by fabe1999** [comment]
[iobroker_2020-03-22.log](https://github.com/Apollon77/ioBroker.alexa2/files/4365075/iobroker_2020-03-22.log)
Hier einmal das Logfile, 
habe den Anfang abgeschnitten da Alexa dort die ganzen Kontaktionformationen übergeben hatte...
Die App selbst scheint keine Daten an zu zeigen:
![Alexa-App](https://user-images.githubusercontent.com/62475207/77247937-0c61ef00-6c36-11ea-870d-9bdc5bccea9e.jpeg)
Auf dem TV sehe ich allerdings die Informationen die Spotify bereitstellt:
![TV](https://user-images.githubusercontent.com/62475207/77247951-24397300-6c36-11ea-90b4-77c42c926a94.jpeg)
Ich weiß nicht ob das etwas ändert doch ich benutze einen Fire TV Cube und kein Echo gerät.
Allerdings hat es damit ja bereits funktioniert.

Hoffe ich konnte etwas weiterhelfen.
Grüße 
Fabe1999

**Comment by Apollon77** [comment]
Bitte 3.2.x versuchen

**Comment by fabe1999** [comment]
Hallo,
Ich habe soeben das Update auf 3.2.4 durchgeführt und es erneut versucht.
Leider sind nach wie vor keine Informationen über die Lieder vorhanden, allerdings sehe ich im Logfile auch keine Datenübergabe mehr. Die Datenfelder im letzten Test waren leer. Jetzt scheinen sie vollkommen zu fehlen.
[iobroker.2020-06-23.log](https://github.com/Apollon77/ioBroker.alexa2/files/4820394/iobroker.2020-06-23.log)

Grüße
Fabe1999

**Comment by Apollon77** [comment]
Jupp, wenn leer dann liefert Amazon nichts ... daher die Frage: Siehst Du in der Alexa App infos wenn du etwas via Spotify abspielt?

**Comment by fabe1999** [comment]
In der Alexa App sehe ich nach wie vor keine Informationen über die Aktuelle Wiedergabe.
Wie bereits gesagt sehe ich allerdings die Informationen über den angeschlossenen Fernseher.

> Auf dem TV sehe ich allerdings die Informationen die Spotify bereitstellt:

Ich weiß nicht ob es eventuell damit zusamen hängt das es sich um ein Fire TV Cube handelt und nicht um ein reines Echo gerät.

Was mich jedoch verwundert hat:
Bei dem ersten Logfile hatte ich Tonnenweise Statusmeldungen im Logfile welche die Songinformation aktuallisiert haben
`[...] State changed alexa2.0.Echo-Devices.G50488473DH.Player.currentTitle: {"val":"", [...]`
Die Felder blieben zwar leer da von Amazon keine "val" übergeben wurde.
In dem neuen Logfile sehe ich allerdings keine dieser State changes Abfragen mehr.
Sprich die Songinformationen wurden auch nie geändert, unabhängig davon ob Text drin steht oder nicht.
Oder habe ich da etwas falsch verstanden?

Grüße
Fabe1999

**Comment by Apollon77** [comment]
> Auf dem TV sehe ich allerdings die Informationen die Spotify bereitstellt:

Spotify != Alexa ... oder !?

In der aktuellsten Version ist für Spotify eine Änderung drin das diese Daten gar nicht mehr abgefragt werden weil es wohl teilweise verursacht hat das das Wiedergaben abgebrochen wurden. Und da Spotify eh nix liefert :-)
