### ISSUE TITLE
listen löschen funktioniert nicht immer

### ISSUE THREAD

**Issue by liv-in-sky** [Apollon77/ioBroker.alexa2#420]
wie im forum beschrieben, werden manchmal durch das ausführen des #delete dp nicht alle datenpunkte (listeinträge gelöscht - log files sind im forum.

https://forum.iobroker.net/post/401753

**Comment by Apollon77** [comment]
Please try again with upcoming 3.2.x

**Comment by Apollon77** [comment]
Bitte GitHub version versuchen

**Comment by Apollon77** [comment]
fixed in 3.11.0
