### ISSUE TITLE
Speak und nachfolgende Aktion ausführen

### ISSUE THREAD

**Issue by zamanis** [Apollon77/ioBroker.alexa2#421]
Hallo, 
besteht die Möglichkeit, vom Adapter einen response per auswertbarem Datenpunkt zu bekommen, wenn der Text fertig gesprochen wurde ?
Die Relevanz liegt darin, dass man beim Ausführen mehrerer Aktionen die vorherige Aktion löscht. D.h. wenn man nacheinander per javascript ein Textkommando und dann einen Datenpunkt für das Abspielen einer Radiostation sendet, der Text vorher nicht mehr gesprochen wird. 
So könnte man den nächsten Teil erst auf Triggern eines response ausführen, und alexa würde erst fertig sprechen. 
Vielen Dank im Voraus für die Bearbeitung!
Viele Grüße
Andreas

**Comment by Apollon77** [comment]
Du meinst das ausführen von Kommando Sequenzen. Die Library kann das grundsätzlich. Ich habe noch keinen sinnvollen Weg gefunden das für den Adapter bereitzustellen - wenn ginge das mit einem JavaScript und messages aber das ist recht komplex am Ende. 

Am einfachsten wenn es „statisch“ ist sind Routinen anzulegen und die zu starten.

**Comment by zamanis** [comment]
Hallo Ingo,

 

ja genau, Kommando-Sequenzen meinte ich. Da sich die Ansprache bei mir eher dynamisch zusammensetzt, habe ich das jetzt versucht, mit Timeouts zu lösen, was einigermaßen klappt, wenn man die Timeoutzeit ebenfalls vorher dynamisch generiert. 

Vielen Dank trotzdem und viele Grüße

 

Andreas

 

Von: Ingo Fischer [mailto:notifications@github.com] 
Gesendet: Sonntag, 29. März 2020 20:06
An: Apollon77/ioBroker.alexa2
Cc: zamanis; Author
Betreff: Re: [Apollon77/ioBroker.alexa2] Speak und nachfolgende Aktion ausführen (#421)

 

Du meinst das ausführen von Kommando Sequenzen. Die Library kann das grundsätzlich. Ich habe noch keinen sinnvollen Weg gefunden das für den Adapter bereitzustellen - wenn ginge das mit einem JavaScript und messages aber das ist recht komplex am Ende.

Am einfachsten wenn es „statisch“ ist sind Routinen anzulegen und die zu starten.

**Comment by padrino-x** [comment]
@zamanis 
Also, ich habe eine Skript, mit dem ich Alexa individuelle Texte auf einem anderen Echo sprechen lassen kann.
Dabei wir geprüft ob der Ziel Echo etwas am Abspielen ist. Ist das der Fall wird er pausiert.
Die Pause ist bei mir die Länge des Strings mal 80 Millisekunden.
Finde, das passt hier ganz gut.
Vielleicht ja auch eine passende Möglichkeit für Dich?

**Comment by Apollon77** [comment]
Also generell fällt mir noch ein Weg ein den man bauen könnte in Zusammenhang mit dem iot Adapter und "Smart Assistenten". Man könnte ein Switch Gerät anlegen odfer einen Taster den man per ipt bei Alexa als "Gerät" anlegt und so auf der Gegenstelle in ioBroker einen State hat der dann betätigt wird. Jetzt könnte man ans Ende der Sprachausgaben ein weiteres Kommando (ist ja eh eine Sequenz an dingen die passieren) anhängen was dann diesen State getätigt. Idealerweise einen State pro Alexa-Gerät damit man es noch genauer hat.

Keine Ahnung ob sowas nicht zu komplex für die Meisten User ist .. Naja ok die Datenpunkte und "iot Konfig" könnte der Alexa2 Adapter machenm, sodas  man es nur suchen müsste in Alexa das es da wäre ...
