### ISSUE TITLE
Probleme mit der Sync

### ISSUE THREAD

**Issue by giftstaub** [Apollon77/ioBroker.alexa2#425]
Hallo zusammen,

Der Adapter Syncronisiert nicht mehr von ( True/False ).

Solch einen Device-type:A1AM2A6B0C0KCR habe ich nicht?

alexa2.0 | 2020-04-09 15:27:58.163 | info | (1331)     Device-type:A1AM2A6B0C0KCR  (DIALOG_INTERFACE_VERSION,AUDIO_PLAYER,REMINDERS,TUNE_IN,KINDLE_BOOKS,AMAZON_MUSIC,GOLDFISH,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,DEREGISTER_DEVICE,MICROPHONE,CHANG
-- | -- | -- | --
alexa2.0 | 2020-04-09 15:27:58.162 | info | (1331) Report to developer as GitHub issue with details for device.  Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-04-09 15:27:58.162 | info | (1331) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-04-09 15:27:57.878 | info | (1331) Alexa-Push-Connection established. Disable Polling
alexa2.0 | 2020-04-09 15:27:52.143 | info | (1331) starting. Version 3.1.2 in /opt/iobroker/node_modules/iobroker.alexa2, node: v10.20.0
alexa2.0 | 2020-04-09 15:27:47.641 | info | (1015) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason

gibt es vllt Probleme mit der neuen node: v10.20.0 in zusammen spiel mit dem Adapter?

Lg

**Comment by Apollon77** [comment]
Was bedeutet Probleme mit Sync? Was tut nicht!

**Comment by giftstaub** [comment]
Also ich bin mit dem Alexa Adapter sowie mit dem Skill iot verbunden.

Jedoch werden mir meine Smart Home Devices von Alexa 2.0 nicht umgestellt.

Wenn ich sage Alexa schalte Blabla bla aus dann steht unter Objekte trotzdem noch true und nicht false.

**Comment by Apollon77** [comment]
Du meinst das sich die Smart devices im Alexa2 nicht aktualisieren? Das haben Sie noch nie automatisch getan. Muss per #query getriggert werden
