### ISSUE TITLE
Fire HD 10 Tablet - kein Commands Datenpunkt

### ISSUE THREAD

**Issue by D3ltorohd** [Apollon77/ioBroker.alexa2#426]
Hallo,

ich scheine hier ein Problem zu haben, das Tablet wird nicht vollständig im Adapter angezeigt, heißt mir fehlt der Datenpunkt "Commands" dieser war ganz kurz zu sehen, nachdem ich das Tablet eingerichtet hatte. Ich wollte dann Testhalber unter speak einen Text senden, als ich den Text eingeben wollte, sah ich wie einige Datenpunkte verschwanden. Seither habe ich hier keine Möglichkeit mehr das Tablet sprechen zu lassen.

Das Tablet funktioniert, ich kann auch übe die Alexa dort meine Geräte im ioB schalten. Auch sehe ich unter Infos, Daten zum Tablet, angepingt werden kann es auch. Ich habe alles probiert, NUC neustart, Adapter neustart, strg+F5, admin Adapter neustart, Tablet Datenpunkte gelöscht und neu anlegen lassen, nichts. Es gibt keinen Ordner mit dem Namen commands.

In der Log sehe ich so leider auch nichts. Keine Ahnung was ich noch machen soll.

Grüße,

**Comment by Apollon77** [comment]
Was steht bei dem Gerät im Adapter unter Info für dein device type und was bei capabilities?

**Comment by Apollon77** [comment]
Und: kannst du in der Alexa App bei Routinen eine Routine erstellen die auf dem Gerät time Sprachausgaben macht?

**Comment by D3ltorohd** [comment]
> Was steht bei dem Gerät im Adapter unter Info für dein device type und was bei capabilities?

![image](https://user-images.githubusercontent.com/2923944/78925694-2441cb80-7a9c-11ea-9895-3babe4808311.png)

capabilities :: VOLUME_SETTING,MICROPHONE,PEONY,CUSTOM_ALARM_TONE,ASX_TIME_ZONE,MICROPHONE,PERSISTENT_CONNECTION,SOUND_SETTINGS,DIALOG_INTERFACE_VERSION,REMINDERS,SUPPORTS_SOFTWARE_VERSION,ASCENDING_ALARM_VOLUME

**Comment by D3ltorohd** [comment]
> Und: kannst du in der Alexa App bei Routinen eine Routine erstellen die auf dem Gerät time Sprachausgaben macht?

Verstehe ich nicht ganz, ich habe kein Gerät das Time heißt. Oder meinst du ich solle eine Routine erstellen, die auf meinem Tablet eine Sprachausgabe abspielt ?

**Comment by D3ltorohd** [comment]
Hm, ka was ich noch tun soll. Habe noch mal alles gelöscht. in ioB das Tablet aus den Datenpunkten, Adapter deaktiviert, Tablet zurückgesetzt. FritzBox neu gestartet, Tablet neu eingerichtet und auch noch mal eine andere IP vergeben. Danach den Adapter wieder gestartet, aber nichts es fehlen die wichtigen Datenpunkte. Habe keine Ahnung, warum das nicht funktioniert. Was auch komisch ist, auf der Webseite von Alexa, steht das Tablet weder mit on oder offline drin, auch komisch ? Bei meinen anderen Geräten ist dies schon der Fall. Komisch ist, als ich das erste mal in den Adapter schaute, nachdem das Tablet da war, waren die Punkte alle vorhanden, ich wollte dann gerade die Sprachausgabe testen und dann sind sie vor meinen Augen verschwunden.

**Comment by Apollon77** [comment]
Die Frage ist immer noch ib Du per Alexa App auf diesem gerät eine Sprachausgabe triggern kannst. Bisherige Erfahrung ist das Apps üblicherweise keine Sprachausgabe erlauben!

**Comment by D3ltorohd** [comment]
> Die Frage ist immer noch ib Du per Alexa App auf diesem gerät eine Sprachausgabe triggern kannst. Bisherige Erfahrung ist das Apps üblicherweise keine Sprachausgabe erlauben!

Jetzt hab ich verstanden, quasi etwas ausführen und dann soll sie auch noch was sagen auf dem Tablet ? Kann ich gleich testen.

Die Sache ist aber die, das wenn ich mir ein zweites Tablet bestelle und das auch anmelde, das dieses dann funktioniert. Ich kann dann per ioB Sprachausgabe senden. Melde ich nun das erste ab, geht auch das zweite nicht mehr. Melde ich jetzt wieder das erste an, geht dies wieder aber das zweite nicht. Irgendwas stimmt da wohl bei Amazon nicht.

Des weiteren scheint es nur die neuste Generation zu betreffen... Bei der alten Generation also die vor der 9. geht das wunderbar.

**Comment by Apollon77** [comment]
Ok, nochmal Strukturiert:

Es gibt im Adapter und auch in der App "Sprachausgabe" und es gibt Ankündigungen (und im Adapter zusätzlich noch SSML als Sonderform). Also was tut jetzt per Routine in der App wie?

**Comment by D3ltorohd** [comment]
Ok, also wenn ich dem Tablet was sage, gibt er mir den Text als Sprache aus, wenn ich das so in der Routine hinterlegt habe.

Ich konnte auch schon über ioBroker, das Tablet sprechen lassen, aber nur wenn das zweite Tablet auch angemeldet ist. Da stimmt irgendwas bei Amazon nicht, oder die haben da was geändert in der FW von der 9. Generation.

**Comment by Apollon77** [comment]
ja eher Amazon
