### ISSUE TITLE
alexa2.0.Echo-Devices.Serialnumber.online wird nicht aktualisiert

### ISSUE THREAD

**Issue by TomBo1969** [Apollon77/ioBroker.alexa2#432]
Moin,
ich verwende den Adapter in der Version 3.1.2 und möchte den Online-Status meiner Echos überwachen, allerdings wird dieser nur beim Neustart des Adapters aktualisiert, nicht nach dem eingestellten Datenaktualisierungsintervall...
Beste Grüße, Tom

PS. Der Adapter ist großartig, vielen Dank dafür!!

**Comment by Apollon77** [comment]
Im Aktualisierungsinterval werden nicht alle Werte neu geladen. Das wäre zu heftig. Connection info wird beim initialem Start aktualisiert oder wenn via push Verbindung von Amazon gemeldet. Also an sich müsste zeitnah nach dem ausschalten da etwas kommen. Bitte mal log auf debug Stellen und dann schauen.

**Comment by TomBo1969** [comment]
Ah ok, nach einer Stunde ändert sich tatsächlich der Status, Danke!
