### ISSUE TITLE
Geräte außerhalb von Alexa-Routinen steuern?

### ISSUE THREAD

**Issue by meisterwerk89** [Apollon77/ioBroker.alexa2#44]
Ich besitze mehrere Homatic-IP-Geräte. Diese lassen sich leider nicht in Routinen intigrieren. So ist es beispielsweise nur möglich die Homatic-Rolladen-Steuerung per Sprachbefehl "Alexa, setzte die Rolladen auf 70%. Ist es möglich diesen Befehl über diesen Adapter an den Echo zu senden?

**Comment by Apollon77** [comment]
nein bisher ist dazu keine schnittstelle bekannt, sorry

**Comment by Apollon77** [comment]
bitte schön: https://forum.iobroker.net/viewtopic.php?f=37&t=16095&p=173376#p173376 ob die verzögerung für den anwendungsfall sinn macht weiss ich nicht.
