### ISSUE TITLE
kiene Verbindung mehr mit Amazon möglich

### ISSUE THREAD

**Issue by Flashy-GER** [Apollon77/ioBroker.alexa2#442]
Folgende Fehler  im Log:

``
ost.iobroker	2020-04-25 16:44:01.377	info	Restart adapter system.adapter.alexa2.0 because enabled
host.iobroker	2020-04-25 16:44:01.376	error	instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker	2020-04-25 16:44:01.376	error	Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:84:21)
host.iobroker	2020-04-25 16:44:01.375	error	Caught by controller[0]: at endReadableNT (_stream_readable.js:1218:12)
host.iobroker	2020-04-25 16:44:01.375	error	Caught by controller[0]: at IncomingMessage.EventEmitter.emit (domain.js:485:12)
host.iobroker	2020-04-25 16:44:01.374	error	Caught by controller[0]: at IncomingMessage.emit (events.js:327:22)
host.iobroker	2020-04-25 16:44:01.374	error	Caught by controller[0]: at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:110:36)
host.iobroker	2020-04-25 16:44:01.373	error	Caught by controller[0]: TypeError: Cannot read property 'end' of null
alexa2.0	2020-04-25 16:43:59.781	info	(3581) Terminated (NO_ERROR): Without reason
alexa2.0	2020-04-25 16:43:59.781	debug	(3581) Plugin sentry destroyed
alexa2.0	2020-04-25 16:43:59.779	info	(3581) terminating
alexa2.0	2020-04-25 16:43:59.758	error	at processTicksAndRejections (internal/process/task_queues.js:84:21)
alexa2.0	2020-04-25 16:43:59.758	error	at endReadableNT (_stream_readable.js:1218:12)
alexa2.0	2020-04-25 16:43:59.758	error	at IncomingMessage.EventEmitter.emit (domain.js:485:12)
alexa2.0	2020-04-25 16:43:59.758	error	at IncomingMessage.emit (events.js:327:22)
alexa2.0	2020-04-25 16:43:59.758	error	at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:110:36)
alexa2.0	2020-04-25 16:43:59.758	error	(3581) TypeError: Cannot read property 'end' of null
alexa2.0	2020-04-25 16:43:59.758	error	(3581) uncaught exception: Cannot read property 'end' of null
alexa2.0	2020-04-25 16:43:59.756	warn	(3581) Exception: TypeError: Cannot read property 'end' of null
alexa2.0	2020-04-25 16:43:59.745	debug	(3581) Alexa-Cookie: Response (200)
``` 
h

---

**System data:**

Platform: linux
Distribution: Raspbian GNU/Linux
Architecture: arm
Model: ARMv7 Processor rev 3 (v7l)
RAM: 3.81 GB
Node.js: v14.0.0
NPM: 6.14.4
JS-Controller (1): 3.0.18
Admin: 4.0.9
Alexa2 (Amazon Echo): 3.1.2

> *created by ioBroker.info*

**Comment by Flashy-GER** [comment]
Fehler ist aufgetreten mit node: v14.0.0.0, js-controller: 3.0.18.
habe jetzt wieder auf: node: v12.16.2, js-controller: 3.0.18 downgegraded.
Nun funktioniert wieder alles ohne Probleme. Keine Fehler mehr.

**Comment by Apollon77** [comment]
Yes nodejs 13 removed one property of an object. Update will come soon.

**Comment by CptBlueT** [comment]
Hallo Apo

> Yes nodejs 13 removed one property of an object. Update will come soon.

Wann können wir den mit dem Update rechnen? Oder ist das doch was grösseres?
Ich habe meinen Server neu aufgesetzt und will nicht schon wieder downgraden.

**Comment by Apollon77** [comment]
Sobald ich Zeit finde. Sorry

**Comment by Dreamboy74de** [comment]
Also bis Nodejs. 13.14.0 funktionierte der Adapter ohne Probleme. Ich mache immer mal ein Clone meiner SD-Karte und probiere "Neuere Versionen" um das stabile System nicht zu zerhauen.

**Comment by Apollon77** [comment]
duplicate #441
