### ISSUE TITLE
Alexa Input erscheint nicht in ioBroker

### ISSUE THREAD

**Issue by n3ucr0n** [Apollon77/ioBroker.alexa2#448]
Hallo,

ich habe heute über die Alexa App einen Alexa Input hinzugefügt.
Betrachte ich rein die Alexa App auf IOS, funktioniert alles wie gewünscht.

Mit Blick auf den ioBroker erkenne ich jedoch probleme. 
Das Alexa-Device (Modell: Alexa Input, Name: Alexa Input Kinderzimmer) wird vom ioBroker nicht erkannt.
Es wird unter "Alexa2.0.Echo-Devoces" nicht angezeigt und über den Input gesprochene Sätze kommen in der History nicht an.

Betrachte ich die Alexa App unter IOS ist alles korrekt hinzugefügt und funktioniert auch entsprechen.

Der Alexa2 Adapter sowie der komplette Raspberry wurden bereits neu gestartet.

Adapter Versionen:
Alexa2; 3.0.5
Admin: 3.7.8

Danke und liebe Grüße 

Screenshots:

![IMG_7658](https://user-images.githubusercontent.com/63336916/80654437-8c247a00-8a7c-11ea-9c5f-1b8a737ead73.JPEG)
![IMG_7659](https://user-images.githubusercontent.com/63336916/80654440-8cbd1080-8a7c-11ea-8800-3fce8f813bc1.JPEG)
![Adapterversionen](https://user-images.githubusercontent.com/63336916/80654442-8d55a700-8a7c-11ea-8871-b5960db69cda.PNG)
![ioBroker Datenpunkte](https://user-images.githubusercontent.com/63336916/80654443-8dee3d80-8a7c-11ea-96f9-918cdc96a106.PNG)

**Comment by n3ucr0n** [comment]
Anscheinend hat es einfach recht lange gedauert, bis das Echo Gerät im ioBroker war. Jetzt ist es jedenfalls vorhanden. Issue Closed =)

**Comment by Apollon77** [comment]
Oooohhhkkkkk ;-)

**Comment by n3ucr0n** [comment]
Ach Du grüne Neune. Ich guck mir grade die angehängten Screenshots an und sehe, dass das Gerät auch schon auf dem Screenshot war.
Was hab ich denn da angestellt!? Naja - Issue ist ja bereits geschlossen. Bitte vergiss diesen Eintrag gerne komplett.

**Comment by Apollon77** [comment]
Hä, war was?!
