### ISSUE TITLE
Ani api that knows when we start to talks to alexa and know when alexa finish to talk?

### ISSUE THREAD

**Issue by MattL0** [Apollon77/ioBroker.alexa2#449]
I mean that ways, we could mute all the device that is making noise in the same room of the alexa we are talking to, so alexa will hear us better . 

This is similar to the ducking issue with sonos... Seems like the issue got resolved... so if Sonos has an api to be able to lower volume selected sonos within a group while a specified alexa echo is activated.. the Api might also be available for us( if someone find this api)

**Comment by Apollon77** [comment]
Nop, not possible and the adapter is using the API that is used by the ALexa App .. so far away from other internal APIs
