### ISSUE TITLE
Rückmeldung für controlRepeat

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#45]
Ich hätte gerne noch eine Rückmeldung ob die Repeat Funktion ein/aus ist also als status

**Comment by Apollon77** [comment]
0.3.8 ... betraf auf play, pause und shuffle Wurd ebeim Umbenennen von repeat in controlRepeat übersehen. Also der controlRepeat enthält mit akc=true auch den aktuellen Status
