### ISSUE TITLE
Speak Commands bleiben stumm

### ISSUE THREAD

**Issue by bfelizardo** [Apollon77/ioBroker.alexa2#450]
Seit gestern 01.05.2020 bekomme ich keine Ausgabe mehr über meine Sonos ONE Lautsprecher. Was bisher immer wunderbar funktioniert hat. Habe einige Skripte geschrieben wo ich die Commands > Speak Objekte nutze. Jedoch geht seit gestern nix mehr. Habe auch manuell bei Objekt was eingetragen uns es kommt kein Ton. Lautstärke ist an und doNotDisturb auf false. Aber es ist nur bei den Sonos Geräten über den FireTV Stick geht es weiterhin.
Hat jemand eine Idee? Hat Amazon da was geändert und man darf das nicht mehr über Fremdgeräte?

Danke für eure Hilfe!

**Comment by bergjet** [comment]
Habe das selbe Problem.

**Comment by robertogresia** [comment]
Habe das selbe Problem.

**Comment by bfelizardo** [comment]
Danke für eure Antworten! Einerseits gut, dann liegt es nicht an meiner lokalen Installation. Anderseits bedeutet dies aber, dass entweder Amazon was geändert hat und man am Adapter was anpassen muss oder Amazon hier generell dicht gemacht hat. @Apollon77 kannst du helfen? Hast du eine Idee an was das liegen könnte? Danke schonmal!

**Comment by Apollon77** [comment]
Ich kann nur wieder fragen: geht eine Sprachausgabe per routine in der Alexa App auf dem Gerät? Wenn ja dann kann ich vllt was tun. Wenn nein dann bitte an Amazon wenden.

**Comment by bergjet** [comment]
Kommunikation "Ausgabe auf allen Geräten" funktioniert. Routine "Wetter" sagt das Wetter an.

**Comment by bfelizardo** [comment]
Hallo @Apollon77, danke dass du dich eingeklinkt hast. Über Routinen in der Alexa App kann man ja keine Sonos Geräte wählen. Somit auch keine Sprachausgabe auf diesen Geräten mit Routinen. Dies ging leider noch nie. Daher kann ich es so nicht testen. Announcements gehen aber wie gewohnt. Diese gehen auf allen Geräten auch Sonos. Kann ich es sonst irgendwie testen oder was machen um die Fehlersuche einzugrenzen?

**Comment by Apollon77** [comment]
> Kommunikation "Ausgabe auf allen Geräten" funktioniert. Routine "Wetter" sagt das Wetter an.

Es ging nicht um Wetter sondern um eine custom Sprachausgabe auf den geräten bzw auf dem speziellen einzelnen Gerät!

**Comment by Apollon77** [comment]
Sagen wir mal so: Wenn der Adapter nicht geändert wurde und es plötzlich nicht tut kann nur Amazon oder Sonos "schuld" sein. Wenn die Amazon Alexa App noch nie "offiziell" das Feature konnte ist es durchaus "Glück" das es tut ... und keine wird Euch irgendwie helfen können wenn es plötzlich nicht mehr tut. Sorry aber ich kann da nichts tun

**Comment by ApolloSK** [comment]
Hallo Apollon77,

die Sprachausgabe funktioniert auch auf den normalen Echo Geräten nicht mehr. Die im Feld alexa2.0.Echo-Devices.XXX....Commands.speak werden nicht mehr auf dem gewählten Gerät ausgegeben. Die Sprachausgabe per Routine in der Alexa App funktioniert auf dem entsprechenden Gerät. "Singasong" funktioniert, wenn man dieses auf true setzt.

Ich habe den Adapter bereits neu installiert und neu mit Alexa verbunden.

Zum System:
Node.js: 12.16.3
Admin: 4.1.1
Alexa: 3.1.2

**Comment by totti1171** [comment]
Schliesse mich hier an - seit kurzem keine Sprachausgabe mehr auf Sonos Beam / One.

(alle anderen Alexa Befehle im Adapter, wie Wetter oder Traffic oder "Singen" funktionieren!!!)

Allerdings - bestimmt für die Fehlersuche interessant: Auf meinem LG-TV (Alexa build in) das gleiche Verhalten!
eventuell betrifft das ja mehrere "Fremdgeräte" ?!?

**Comment by speedmaster1** [comment]
Habe das gleiche Probleme und schon viel recherchiert, leider ohne Erfolg

**Comment by Apollon77** [comment]
Scheinbar haben Amazon bzw Sonos etwa geändert. Ich kann da nichts tun.

**Comment by bfelizardo** [comment]
Bei mir geht es wieder. Habe heute alle Adapter geupdated, da sind einige updates dabei gewesen und nun geht es wieder. Vermute hier einen Zusammenhang.

**Comment by Apollon77** [comment]
nope, Nix da updates, Amazon und Sonos!
