### ISSUE TITLE
Kein Speak Output bei Sonos Beam

### ISSUE THREAD

**Issue by zwicknoob** [Apollon77/ioBroker.alexa2#451]
Hallo, war hier gestern nicht noch ein Issue bezüglich des Themas? Habe seit ungefähr 4 Tagen das Problem das ich keine eigenen Speak Ansagen über den Alexa2 Adapter aus meiner Sonos Beam bekomme. Bei Eintrag in den Speak Datenpunkt bleibt meine Sonos stumm. Kann hier jemand helfen?

Danke

**Comment by Apollon77** [comment]
Ja das issue habe ich geschlossen Weil ich bzw der Adapter nichts diesbezüglich tun kann. 

Die sonos Geräte sind für diese Art der Kommandos (Sprachausgabe) in der Alexa App nicht einmal auswählbar ... von daher ist’s „Glück“ das es tat. Kannst dich ggf wegen einem feature request das Sprachausgaben cool wären gern an Amazon oder Sonos wenden aber bin nicht sicher ob das was bringt.

**Comment by bfelizardo** [comment]
@zwicknoob ja ich hatte dazu ein Issue gepostet. Da scheint nun Amazon dicht gemacht zu haben. Ist echt ärgerlich, habe es täglich zuverlässig genutzt und dass schon seit einer Ewigkeit. Glaube nicht das es "Glück" oder Zufall ist dass es je geklappt hat. Sondern eher das Amazon oder Sonos was geändert haben. 
Falls du was rausbekommst dann würde ich mich freuen wenn du mir schreibst. Ich halte dich auch auf dem laufenden. Gebe da noch nicht auf ;-)

**Comment by Apollon77** [comment]
Ich hab da leider wenig Möglichkeiten aber ich höre mich mal um

**Comment by bfelizardo** [comment]
> Ich hab da leider wenig Möglichkeiten aber ich höre mich mal um

Vielen Dank @Apollon77

**Comment by zwicknoob** [comment]
Ich denke das liegt an Sonos. Ich habe das Problem erst seit ca 5 Tagen. Da wurde auch mal wieder automatisch die Firmware geupdatet....

**Comment by bfelizardo** [comment]
@zwicknoob bei mir geht es wieder. Habe heute alle Adapter geupdated, da sind einige updates dabei gewesen und nun geht es wieder. Vermute hier einen Zusammenhang.

**Comment by zwicknoob** [comment]
@bfelizardo bei mir geht es auch wieder. Habe aber noch keinen Adapter geupdated. War bestimmt wieder von Sonos gemachtes Problem.
