### ISSUE TITLE
Unknown Device, but enabling commands - Report to developer

### ISSUE THREAD

**Issue by FabianHM** [Apollon77/ioBroker.alexa2#452]
Hello,

After each restart, I receive the following message from the alexa2 adapter. Can you please check this?

alexa2.0 | 2020-05-04 12:04:47.060 | info | (13573) Subscribing to states...
-- | -- | -- | --
alexa2.0 | 2020-05-04 12:04:07.048 | info | (13573)     Device-type:A3L0T0VL9A921N (MICROPHONE,VOLUME_SETTING,ASX_TIME_ZONE,NO_TIME_ZONE_SETTING,SUPPORTS_SOFTWARE_VERSION,ASX_TIME_ZONE,MICROPHONE)
alexa2.0 | 2020-05-04 12:04:07.047 | info | (13573)  Report to developer as GitHub issue with details for device. Please  grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-05-04 12:04:07.045 | info | (13573) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-05-04 12:04:03.512 | info | (13573) starting. Version 3.1.2 in /opt/iobroker/node_modules/iobroker.alexa2, node: v12.16.3, js-controller: 3.0.20

I cannot find this Device in my Amazon Device Selection.

**Comment by Apollon77** [comment]
If you can not find the dive the it is hard to do something ... I would need to know what kind of decice it is. Please reopen if you have more details
