### ISSUE TITLE
Echo Studio Bereich Player ohne Daten & Funktion

### ISSUE THREAD

**Issue by TJJochen** [Apollon77/ioBroker.alexa2#453]
Unter dem Bereich Player des Echo Studio werden keine Daten mehr dargestellt (currentTitle, currentAlbum,...)  und man kann keine Kommandos mehr absetzen (zb. controlNext). Alle anderen Echos (Dot oder Echo Plus) funktionieren einwandfrei

**Comment by Apollon77** [comment]
Bitte unter den device bei den Objekte unter info bitte deviceType und capabilities posten

**Comment by TJJochen** [comment]
Device Type:
`A3RBAYBE7VM004`

Capabilities:
`MUSIC_SKILL,FAR_FIELD_WAKE_WORD,TAHOE_BYOD,DIALOG_INTERFACE_VERSION,TUPLE_CATEGORY_A,REQUIRES_OOBE_FOR_SETUP,UPDATE_WIFI,SUPPORTS_SOFTWARE_VERSION,EQUALIZER_CONTROLLER_TREBLE,LOCAL_VOICE,ASCENDING_ALARM_VOLUME,SET_LOCALE,FLASH_BRIEFING,PAIR_REMOTE,EQUALIZER_CONTROLLER_BASS,GADGETS,PERSISTENT_CONNECTION,AUDIO_CONTROLS,GUARD_EARCON,SUPPORTS_LOCALE_SWITCH,VOICE_TRAINING,EQUALIZER_CONTROLLER_MIDRANGE,EARCONS,SLEEP,PAIR_BT_SINK,CUSTOM_ALARM_TONE,SOUND_SETTINGS,GOLDFISH,ACTIVE_AFTER_FRO,AUDIO_PLAYER,LEMUR_ALPHA,CHANGE_NAME,DEREGISTER_DEVICE,PAIR_BT_SOURCE,SUPPORT_CALENDAR_ALERT,POPTART,DS_VOLUME_SETTING,VOLUME_SETTING,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,DEREGISTER_FACTORY_RESET,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,SUPPORTS_LOCALE,TIMERS_AND_ALARMS,REMINDERS,DREAM_TRAINING,MICROPHONE,TUPLE`

**Comment by Apollon77** [comment]
The device type is not known by the adapter, so commands should be enabled. Please tyr current version of adapter.
