### ISSUE TITLE
synchronisierter Datenpunkt Contacts erzeugt  Fehler in Admin Filterfunktion 

### ISSUE THREAD

**Issue by Knallochse** [Apollon77/ioBroker.alexa2#456]
Wie im Admin-Issues [hier](https://github.com/ioBroker/ioBroker.admin/issues/486)
bereits beschrieben, kann ein fehlerhaft erzeugter Datenpunkt die Filterfunktion aus dem Tritt bringen. In meinem Fall war es ein Kontakt.
`

  | "alexa2.0.Contacts.AFW7KD72AHR5MTCXLR5PXC7BFHOA": {
-- | --
  | "type": "channel",
  | "common": {
  | "name": null, -hier fehlen meiner Meinung nach ""
  | "read": true,
  | "write": false
  | },
  | "native": {},
  | "from": "system.adapter.alexa2.0",
  | "user": "system.user.admin",
  | "ts": 1588183933814,
  | "_id": "alexa2.0.Contacts.AFW7KD72AHR5MTCXLR5PXC7BFHOA",
  | "acl": {
  | "object": 1636,
  | "owner": "system.user.admin",
  | "ownerGroup": "system.group.administrator"

`

**Comment by Apollon77** [comment]
v 3.2.x will make sure no null names are created
