### ISSUE TITLE
Nodejs 14 - Login geht nicht mehr (Cookie)

### ISSUE THREAD

**Issue by JayVee2** [Apollon77/ioBroker.alexa2#457]
Hallo zusammen,
Lief Monate lang gut, heute nicht mehr, ständig Fehler.
Testweise alexa2.0 Adapter gelöscht und neu installiert. Cookie mehrfach geholt. Trotzdem Fehler:

`

host.PI3 | 2020-05-09 13:38:30.172 | error | instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.PI3 | 2020-05-09 13:38:30.172 | error | Caught by controller[2]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
host.PI3 | 2020-05-09 13:38:30.171 | error | Caught by controller[2]:     at endReadableNT (_stream_readable.js:1223:12)
host.PI3 | 2020-05-09 13:38:30.171 | error | Caught by controller[2]:     at IncomingMessage.EventEmitter.emit (domain.js:485:12)
host.PI3 | 2020-05-09 13:38:30.171 | error | Caught by controller[2]:     at IncomingMessage.emit (events.js:327:22)
host.PI3 | 2020-05-09 13:38:30.170 | error | Caught by controller[2]:     at IncomingMessage.<anonymous>  (/opt/iobroker/node_modules/alexa-cookie2/alexa-cookie.js:110:36)
host.PI3 | 2020-05-09 13:38:30.170 | error | Caught by controller[2]: TypeError: Cannot read property 'end' of null
host.PI3 | 2020-05-09 13:38:30.170 | error | Caught by controller[1]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
host.PI3 | 2020-05-09 13:38:30.170 | error | Caught by controller[1]:     at endReadableNT (_stream_readable.js:1223:12)
host.PI3 | 2020-05-09 13:38:30.169 | error | Caught by controller[1]:     at IncomingMessage.EventEmitter.emit (domain.js:485:12)
host.PI3 | 2020-05-09 13:38:30.169 | error | Caught by controller[1]:     at IncomingMessage.emit (events.js:327:22)
host.PI3 | 2020-05-09 13:38:30.169 | error | Caught by controller[1]:     at IncomingMessage.<anonymous>  (/opt/iobroker/node_modules/alexa-cookie2/alexa-cookie.js:110:36)
host.PI3 | 2020-05-09 13:38:30.168 | error | Caught by controller[1]: TypeError: Cannot read property 'end' of null
host.PI3 | 2020-05-09 13:38:30.168 | error | Caught by controller[0]: (Use `node --trace-deprecation ...` to show where the warning was created)
host.PI3 | 2020-05-09 13:38:30.167 | error | Caught by controller[0]: (node:31446) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

`

Jemand eine Idee?

Grüße
-jayvee

**Comment by Apollon77** [comment]
Ja, nodejs 14 ist aktuell noch nicht unterstützt.

**Comment by JayVee2** [comment]
nodejs 12?

**Comment by Apollon77** [comment]
should work

**Comment by JayVee2** [comment]
OK, downgraded to nodesj12, reinstalled and restored ioBroker. Seems to work now. Great!
Vielen Dank!! Please close issue.

Das hat eine ganze Weile mit dem alten Cookie aus einem restore mit nodejs14 funktioniert. Erst mit der Aktualisierung des Cookies ist das Problem wohl aufgetreten.

**Comment by henkhb** [comment]
Same issue here. Won't be able to downgrade at the moment.
Can we expect a fix soon? Thanks for your great work. 

host.DietPi-ioBroker | 2020-05-18 08:48:50.887 | error | instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.DietPi-ioBroker | 2020-05-18 08:48:50.886 | error | Caught by controller[1]: at processTicksAndRejections (internal/process/task_queues.js:84:21)
host.DietPi-ioBroker | 2020-05-18 08:48:50.886 | error | Caught by controller[1]: at endReadableNT (_stream_readable.js:1225:12)
host.DietPi-ioBroker | 2020-05-18 08:48:50.885 | error | Caught by controller[1]: at IncomingMessage.EventEmitter.emit (domain.js:485:12)
host.DietPi-ioBroker | 2020-05-18 08:48:50.885 | error | Caught by controller[1]: at IncomingMessage.emit (events.js:327:22)
host.DietPi-ioBroker | 2020-05-18 08:48:50.885 | error | Caught by controller[1]: at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:110:36)
host.DietPi-ioBroker | 2020-05-18 08:48:50.884 | error | Caught by controller[1]: TypeError: Cannot read property 'end' of null
host.DietPi-ioBroker | 2020-05-18 08:48:50.884 | error | Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:84:21)
host.DietPi-ioBroker | 2020-05-18 08:48:50.883 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1225:12)
host.DietPi-ioBroker | 2020-05-18 08:48:50.883 | error | Caught by controller[0]: at IncomingMessage.EventEmitter.emit (domain.js:485:12)
host.DietPi-ioBroker | 2020-05-18 08:48:50.882 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:327:22)
host.DietPi-ioBroker | 2020-05-18 08:48:50.882 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:110:36)
host.DietPi-ioBroker | 2020-05-18 08:48:50.881 | error | Caught by controller[0]: TypeError: Cannot read property 'end' of null
alexa2.0 | 2020-05-18 08:48:50.619 | info | (9595) Terminated (NO_ERROR): Without reason

**Comment by WebOscar** [comment]
I had the same issue after System-update/upgrade. I was able to solve it by downgrading nodejs to V12, like @JayVee2 did.

**Comment by henkhb** [comment]
Not possible for my system. Hope to see a bugfix in the future. Thanks for the great work!

**Comment by Apollon77** [comment]
duplicate #441
