### ISSUE TITLE
Phrase to play Amazon Music does not work with multiroom Music

### ISSUE THREAD

**Issue by Marty56** [Apollon77/ioBroker.alexa2#46]
Since speech and volume is working with multiroom music device maybe there is a chance to get also music to work with multiroom music devices.

**Comment by Apollon77** [comment]
enable debug loglevel please, here I see nothing - or do you mean the devices that are listed as "Unknown device types" and that the music provider objects are missing there?

```
Device-type:A12GXV8XMS007S (CHANGE_NAME,MICROPHONE,SUPPORTS_SOFTWARE_VERSION,ARTHUR_TARGET,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,ACTIVE_AFTER_FRO,FLASH_BRIEFING,VOLUME_SETTING)
```

What are there for devices? Are they multiroom or what is this?

**Comment by Marty56** [comment]
I have enabled the log level of the alexa adapter and then created the log.
What else can I do?

I have no idea what A12GXV8XMS007S is.
I have looked in the object tree but cannot find it now.

**Comment by Marty56** [comment]
[log.txt](https://github.com/Apollon77/ioBroker.alexa2/files/2238058/log.txt)

Maybe I have sent the wrong log. sorry

**Comment by Apollon77** [comment]
The device Typ can be found in Infos area from the devices. Can you match now?

**Comment by Apollon77** [comment]
Zurück zum Thema: Multihost play amazon music auf "Haus".

Also im Log sehe ich das Du versucht hast auf dem Echo "Haus" (d293435ad98b451390cd2976b85a1e50) "spiele das Lied Signalhorn" zu machen. Keine Ahnung ob das so sinnmmacht, ich hätte eher "Signalhorn" erwartet weil er intern schon selbst noch ein "spiele das Lied" oder so davorzimmert.
In dem Fall hat er das gemacht was er sollte. Er hat das erste Device dieser Multigruppe genommen (90F00818720400KN) und an dieses den Text "spiele das Lied Signalhorn auf Haus music" für AmazonMusic gegeben. SO haben wir herausgefunden das es an sich tun sollte.

Wenn Du das "spiele das Lied" weglässt? geht das?

Und die ID A12GXV8XMS007S habe ich dazugenommen. nächstes Update nach meinem Urlaub. Was können die in der Amazon App? Routinen? Kommandos?

**Comment by Apollon77** [comment]
check 0.4.0 from GitHub and https://forum.iobroker.net/viewtopic.php?f=37&t=16095
