### ISSUE TITLE
Cookie invalid after 7 days; high traffic afterwards

### ISSUE THREAD

**Issue by githtz** [Apollon77/ioBroker.alexa2#460]
Hi guys,
I'm using an extracted cookie to log into my Amazon account via the alexa2 adapter. After about seven days the cookie seems to be invalid and if I forget to supply a new cookie to the alexa2 adapter it starts causing pretty high traffic (up to a few gigabyte per hour!), probably polling the hell out of Amazon? 

Has anyone else had this kind of issue and is there anything I can do about it? Many thanks in advance!

Hallo Leute,
ich benutze ein extrahiertes Cookie um den alexa2-adapter in meinem Amazon-Account einzuloggen. Nach etwa sieben Tagen scheint das Cookie seine Gültigkeit zu verlieren. Wenn ich dann vergesse im Adapter ein neues Cookie einzutragen verursacht der Adapter sehr viel Traffic (mehrere Gigabyte pro Stunde!), vermutlich werden andauernd ungültige Anfragen an Amazon geschickt?

Hat sonst jemand schon mal dieses Problem gehabt und falls ja, was kann ich dagegen tun? Vielen Dank im Voraus!

**Comment by Apollon77** [comment]
Please provide debug log of such a case.

**Comment by githtz** [comment]
> Please provide debug log of such a case.

I'll try to. Will report back once it happens again.

**Comment by githtz** [comment]
I'm a little embarrassed, the problem has apparently already been fixed. I apologize for any inconvenience this may have caused. Can be closed :)
