### ISSUE TITLE
Routinen werden nicht getriggerd

### ISSUE THREAD

**Issue by MariusLang** [Apollon77/ioBroker.alexa2#462]
Seit heute morgen werden die Alexa Routinen im ioBroker nicht mehr getriggerd. Also ich meine, dass der Wert (true/false) nicht mehr aktualisiert wird. Ich kann meinen Echo Dot jedoch ansteuern und ihn etwas sprechen lassen. Ich habe bereits einmal eine neue Routine erstellt, diese wird auch gelistet, kann aber ebenfalls nicht ausgelöst werden. 

Das System lief nun längere Zeit ohne weitere Probleme.

In der Log sind keinerlei Fehler. 

Mfg,
Marius

**Comment by Apollon77** [comment]
duplicate to #461 ?

Bitte Debug log aktivieren und prüfen ob "push infos" reinkommen ... sonst hat es Amazon mal wieder kaputt gemacht

**Comment by MariusLang** [comment]
Tatsache!
Entschuldigung!

Nein, keinerlei Push Infos!
Schade Amazon :(

Na gut, ich warte mal ab und schreib wann es wieder geht!

**Comment by Apollon77** [comment]
Laut Forum geht es Bei einigen wieder.

**Comment by MariusLang** [comment]
Ja, kann ich auch bestätigen. Ist schade was Amazon da immer anstellt :(

Vielen Dank für deine Arbeit!
