### ISSUE TITLE
In der V3.1.2 reagiert nicht immer die Summary

### ISSUE THREAD

**Issue by guergen1** [Apollon77/ioBroker.alexa2#464]
In der V3.1.2 reagiert nicht immer die Summary, erst nach einem Neustart des Adapters geht es mal wieder für einige Zeit.
Debuglog ist jetzt eingeschaltet und ich sende das Log, sobald es wieder nicht mehr funktioniert!
js-controller 3.1.4
Node.js 12.16.3
NPM 6.14.4

**Comment by Apollon77** [comment]
Die letzten Tage gab es Probleme bei Amazon. Ansonsten wie genau triggerst du denn? An sich ist das gefixt.

**Comment by guergen1** [comment]
Wenn ich Alexa anspreche wird in der History-Summary der Text nicht eingeblendet und daher reagieren Scripte nicht.
Allerdings habe ich grade überhaupt keine Verbindung zu iot und alexa. Bin noch auf der suche...

**Comment by Apollon77** [comment]
Was meinst Du mit "History-Summary der Text nicht eingeblendet" ? Wenn Du im Admin "zuschaust" kann es sein das manchmla änderungen so schnell kommen das Dunichts siehst und amEnde kopmmt manchmal ein lerer String.

Daher ist das eher für Skript verarbeitbar

**Comment by guergen1** [comment]
Ich habe es ja getestet... Nach einem Neustart wird das ja eingeblendet... Ich denke es lag wohl im Moment an Amazon, da ich jetzt wieder überall zugriff drauf habe.
Spreche ich Alexa an, wird der Text auch in der Summary eingeblendet, habe es auch mit einem Debug-Log im Script überprüft, da kam nix!

**Comment by guergen1** [comment]
Jetzt kommt was in der Summary an, aber das Script regiert nicht. Die normalen Befehle über iot gehen. Muss ich jetzt ein Issue im javascript aufmachen... ist die Version von heute morgen vom update

**Comment by Apollon77** [comment]
Es „meint“ Alexa und wie? Ich habe keine Ahnung was du aktuell wie tust. Wir raten hier gerade wild. 

Zeig doch mal dein Skript.

**Comment by guergen1** [comment]
Alexa sagt, dass ich die Netzwerkverbindung zum Gerät und die Stromversorgung prüfen soll.
Das Script ist das selbe, wie in einem anderen Problem...:
`var Lautst_C3_A4rke_zwischenspeichern;


on({id: 'alexa2.0.History.summary', change: "any"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  if ((obj.state ? obj.state.val : "").indexOf('fernsehe') + 1 >= 1 && ((obj.state ? obj.state.val : "").indexOf('an') + 1 >= 1 || (obj.state ? obj.state.val : "").indexOf('einschalten') + 1 >= 1)) {
    setState("sonoff.0.TV-Steckdose.POWER1"/*TV-Steckdose POWER1*/, true);
    setState("enigma2.0.main_command.WAKEUP_FROM_STANDBY"/*Wakeup form Standby*/, true);
    Lautst_C3_A4rke_zwischenspeichern = getState("alexa2.0.Echo-Devices.G090LF1174170RP2.Commands.speak-volume").val;
    setStateDelayed("alexa2.0.Echo-Devices.G0+++++174170RP2.Commands.speak-volume"/*Volume to use for speak commands*/, 50, 100, false);
    setStateDelayed("alexa2.0.Echo-Devices.G0+++++174170RP2.Commands.speak"/*speak*/, ('Der Fernseher ist jetzt an'), 1000, false);
    setStateDelayed("alexa2.0.Echo-Devices.G0+++++174170RP2.Commands.speak-volume"/*Volume to use for speak commands*/, Lautst_C3_A4rke_zwischenspeichern, 3000, false);
  } else if ((obj.state ? obj.state.val : "").indexOf('fernsehe') + 1 >= 1 && ((obj.state ? obj.state.val : "").indexOf('aus') + 1 >= 1 || (obj.state ? obj.state.val : "").indexOf('ausschalten') + 1 >= 1)) {
    setState("sonoff.0.TV-Steckdose.POWER1"/*TV-Steckdose POWER1*/, false);
    setState("enigma2.0.main_command.STANDBY"/*Standby*/, true);
  }
});`

**Comment by Apollon77** [comment]
äääähhmmm ... Du sagst der Alex airgendwas was du per Summary abfängst ... und Alexa sagt die soetwas ohne das das einer Deiner texte ist? Na dann mach doch mal was Alex sagt ... was sollte das denn mit Skripten oder dem Alexa2 Adapter zu tun haben?
Bitte such den Fehler erstmal da wo es am einfachsten ist

**Comment by guergen1** [comment]
Es hat ja bis zum Update gestern einwandfrei funktioniert.... Oder es liegt an Amazon....
