### ISSUE TITLE
Gerätestatus wird nicht aktualisiert

### ISSUE THREAD

**Issue by ChristianHohman** [Apollon77/ioBroker.alexa2#465]
Hallo, wenn mein Fenster geöffnet ist, kann ich den richtigen status mit Alexa erfragen.
Alexa2 zeigt mir jedoch immer an, dass es geschlossen ist. Die Information wird nicht aktualisiert.
Habe bereits Iobroker + Alexa2 komplett neuinstalliert.

Jemand eine Idee? Danke

**Comment by Apollon77** [comment]
Ja. Triggered den #query befinden gerät bei den States.  Alexa Änderungen werden nicht von Alexa bei Änderung gepuscht. Dafür ist das System da nicht ausgelegt. Daher: für solche Art von Geräten Und dem Wunsch echtzeit Updates zu bekommen ist das nicht geeignet.
