### ISSUE TITLE
Alexa kann kein Komma mehr...

### ISSUE THREAD

**Issue by R3play13** [Apollon77/ioBroker.alexa2#466]
Hi,

Habe seit einigen Tagen das Problem, dass meine Sprachausgabe über Alexa ohne jegliche Beachtung von Satzzeichen geschieht.

Texte die bei "Speak" des jeweiligen Echodevice eingegeben werden, werden ohne Punkt und Komma ausgesprochen. Wenn ich per SSML ein Text eingebe und eine "break time="1s"/" einfüge  ist die Pause da.

**Comment by R3play13** [comment]
Nach Update auf Latest Version 3.1.2 funktioniert es wieder.

**Comment by Apollon77** [comment]
ne das update hat es garantiert nicht gelöst ... Amazon hatte was geändert und scheinbar wieder zurück

**Comment by R3play13** [comment]
Okay, dann war es Zufall das es direkt nach dem Update wieder funktioniert hat....
