### ISSUE TITLE
Status von Alexa kompatiblen Geräten

### ISSUE THREAD

**Issue by ChristianHohman** [Apollon77/ioBroker.alexa2#467]
Hallo nochmal vielleicht war mein letzter post zu unverständlich.

Als ich erstmals alexa2 installiert habe hat er regelmäßig die Änderungen von Alexa kompatibelsten Geräten angezeigt, zb Schalter oder Licht.
Beim log bekomme ich kein Fehler aber ich kann den Status der Geräte in iobroker über Alexa 2 nicht abfragen, da der Status immer aus ist. Kann irgendwie anders den Status der Geräte die in Alexa implementiert sind Abfragen? Dafür ist doch alexa2 gedacht oder?

Vielen dank

**Comment by ChristianHohman** [comment]
(Es muss nicht direkt Echtzeit sein, aber er zeigt gar nicht mehr Änderungen an obwohl die Lampe zb an ist)

**Comment by Apollon77** [comment]
Der Adapter hat noch nie automatisch Gerte stati aktualisiert!

Auch jetzt geht das icht. Jedes Gerät hat aber einen #query Datenpunkt.Wenn DU den auf true setzt dann wird das abgeholt. Oder was genau geht da nicht? Bitte mal ein Beispiel zeigen
