### ISSUE TITLE
Fire HD 10 und Fire TV Cube fehlen die Commands

### ISSUE THREAD

**Issue by Ridesa** [Apollon77/ioBroker.alexa2#47]
Fire TV Cube 
device-type A3HF4YRA2L7XGC
capabilities
{
"from": "system.adapter.alexa2.0",
"ts": 1532728399397,
"common": {
"name": "capabilities",
"role": "text",
"type": "string",
"def": "FLASH_BRIEFING,TUNE_IN,PANDORA,FAR_FIELD_WAKE_WORD,DREAM_TRAINING,AMAZON_MUSIC,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,AUDIBLE,SUPPORTS_SOFTWARE_VERSION,PAIR_BT_SINK,CHANGE_NAME,AUDIO_PLAYER,VOICE_TRAINING,SET_LOCALE,EARCONS,SOUND_SETTINGS,SALMON,ACTIVE_AFTER_FRO,SLEEP,I_HEART_RADIO,TIMERS_AND_ALARMS,CUSTOM_ALARM_TONE,PERSISTENT_CONNECTION,ARTHUR_TARGET,KINDLE_BOOKS,REMINDERS",
"write": false,
"read": true
},
"native": {},
"acl": {
"object": 1636,
"owner": "system.user.admin",
"ownerGroup": "system.group.administrator",
"state": 1636
},
"_id": "alexa2.0.Echo-Devices.G090P00981360K1N.Info.capabilities",
"type": "state"
}

Fire HD 10
device-type A3R9S4ZZECZ6YL
capabilities
{
"from": "system.adapter.alexa2.0",
"ts": 1532728399935,
"common": {
"name": "capabilities",
"role": "text",
"type": "string",
"def": "SUPPORTS_SOFTWARE_VERSION,ASX_TIME_ZONE,PEONY,VOLUME_SETTING,ASCENDING_ALARM_VOLUME",
"write": false,
"read": true
},
"native": {},
"acl": {
"object": 1636,
"owner": "system.user.admin",
"ownerGroup": "system.group.administrator",
"state": 1636
},
"_id": "alexa2.0.Echo-Devices.G000N6078203072D.Info.capabilities",
"type": "state"
}

**Comment by Apollon77** [comment]
Auf Github schon drauf. einfach updaten. Versionsnummer ist aber noch die letzte

**Comment by Ridesa** [comment]
Danke
