### ISSUE TITLE
"Timer.triggered" is triggered for timers deleted with "Alexa, Lösche alle Timer"

### ISSUE THREAD

**Issue by Gaspode69** [Apollon77/ioBroker.alexa2#471]
Steps to reproduce:
Start a new timer with "Alexa, timer in 10 Sekunden"
Immediately delete this timer with "Alexa, lösche alle Timer"
If the 10 seconds are over, you will get three events for "Timer.triggered": val= false, val=false, val=true

**Comment by Apollon77** [comment]
will be fixed in 3.2.x
