### ISSUE TITLE
Alexa 2.0 termination loop after update to node: v14.4.0, js-controller: 3.1.4

### ISSUE THREAD

**Issue by FraatRamski** [Apollon77/ioBroker.alexa2#473]
Alexa 2.0 is in a termination loop after update to node: v14.4.0, js-controller: 3.1.4.
Tried also with deinstallation which don't have solved the issue.

`

host.stariobroker | 2020-06-07 13:37:13.501 | info | Restart adapter system.adapter.alexa2.0 because enabled
-- | -- | -- | --
host.stariobroker | 2020-06-07 13:37:13.501 | info | instance system.adapter.alexa2.0 terminated with code 0 (NO_ERROR)
host.stariobroker | 2020-06-07 13:37:13.501 | error | Caught by controller[1]:     at main (/opt/iobroker/node_modules/iobroker.alexa2/main.js:2618:11)
host.stariobroker | 2020-06-07 13:37:13.501 | error | Caught  by controller[1]:     at AlexaRemote.init  (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:139:9)
host.stariobroker | 2020-06-07 13:37:13.501 | error | Caught  by controller[1]:     at getCookie  (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:133:21)
host.stariobroker | 2020-06-07 13:37:13.501 | error | Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:146:18
host.stariobroker | 2020-06-07 13:37:13.500 | error | Caught  by controller[1]:     at AlexaRemote.checkAuthentication  (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:800:14)
host.stariobroker | 2020-06-07 13:37:13.500 | error | Caught  by controller[1]:     at AlexaRemote.httpsGetCall  (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:754:19)
host.stariobroker | 2020-06-07 13:37:13.500 | error | Caught by controller[1]:     at Object.request (/opt/iobroker/node_modules/@sentry/node/dist/integrations/http.js:65:18)
host.stariobroker | 2020-06-07 13:37:13.500 | error | Caught by controller[1]:     at Object.request (https.js:310:10)
host.stariobroker | 2020-06-07 13:37:13.500 | error | Caught by controller[1]:     at new ClientRequest (_http_client.js:249:14)
host.stariobroker | 2020-06-07 13:37:13.500 | error | Caught by controller[1]:     at ClientRequest.setHeader (_http_outgoing.js:536:3)
host.stariobroker | 2020-06-07 13:37:13.500 | error | Caught by controller[1]: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["csrf"]
host.stariobroker | 2020-06-07 13:37:13.500 | error | Caught  by controller[0]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected
alexa2.0 | 2020-06-07 13:37:12.991 | info | (857) Terminated (NO_ERROR): Without reason
alexa2.0 | 2020-06-07 13:37:12.990 | info | (857) terminating
alexa2.0 | 2020-06-07 13:37:12.943 | error | (857) TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["csrf"]     at ClientRequest.setHeader (_http_outgoing.js:536:3)     at new ClientRequest (_http_client.js:249:14)     at Objec
alexa2.0 | 2020-06-07 13:37:12.943 | error | (857) unhandled promise rejection: Invalid character in header content ["csrf"]
alexa2.0 | 2020-06-07 13:37:12.943 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
alexa2.0 | 2020-06-07 13:37:12.906 | info | (857) starting. Version 3.0.5 in /opt/iobroker/node_modules/iobroker.alexa2, node: v14.4.0, js-controller: 3.1.4

`

**Comment by FraatRamski** [comment]
Hallo, the same issue with:
 Version 3.0.5 in /opt/iobroker/node_modules/iobroker.alexa2, node: v12.18.0, js-controller: 3.1.4

**Comment by Apollon77** [comment]
With nodejs 12 is can not be the same issue

**Comment by FraatRamski** [comment]
Hallo,

deinstalled alexa and reinstalled.

Version 3.1.2 in /opt/iobroker/node_modules/iobroker.alexa2, node: v12.18.0, js-controller: 3.1.4
Is working now fine!

Thanks for the great connector!!!
