### ISSUE TITLE
Idea: Fork an http:// API like node-sonos-http-api

### ISSUE THREAD

**Issue by hblaschka** [Apollon77/ioBroker.alexa2#474]
Hi Apollon77,

just an idea to open up your work on that adapter. Why not wrapping an http:// APi (like e.g. node-sonos-http-api) around and forking that, so that others might feel invited to contribute and opening up (all or parts) of this great work for others to use via Webhooks?

**Comment by Apollon77** [comment]
This might be an idea for the underlying libraries but not for this iobroker adapter. And in fact you are free to do such an independent project for this.
