### ISSUE TITLE
Problem mit Speak

### ISSUE THREAD

**Issue by BenjaminHolzmueller** [Apollon77/ioBroker.alexa2#478]
Leider habe ich seit kurzem das Problem, dass Speak nicht funktioniert.
Die anderen Funktionen scheinen zu funktionieren. Nur egal was ich bei Speak eintrage wird es nicht mehr ausgesprochen.

Ist dieser Fehler bekannt?

**Comment by Apollon77** [comment]
Do not disturb Modus ist aus?
Geht Speak noch über eine Routine in der Alexa App?

**Comment by Apollon77** [comment]
Bitte erneut versuchen, es gab meldungen das es jetzt wieder geht. war wohl ein Amazon Problem
