### ISSUE TITLE
Problem beim Anmelden bei Amazon Alexa

### ISSUE THREAD

**Issue by melon-1999** [Apollon77/ioBroker.alexa2#479]
Hallo, wenn ich mich bei der Proxy URL anmelde kommt immer wieder die Fehlermeldung "Bitte aktivieren Sie Cookies, um fortzufahren". Ich habe Cookies für alle Websiten zugelassen auch mehrmals gelöscht und auch mehrmals eine neue Instanz erstellt. Habe es mit Google Chrome und Edge versucht aber immer der gleiche Fehler. Habe auch schon verschiedene Proxy Einstellungen versucht daran liegt es aber glaube ich nicht. Wäre schön falls jemand eine Lösung hätte.
LG
Janis

**Comment by jabosammy** [comment]
Schließe mich an - Geht seit gestern Abend nicht mehr und leider noch immer nicht.

**Comment by canim60** [comment]
Ich schließe mich auch an, hab das selbe problem, für ne Lösung wäre ich dankbar!

**Comment by DavidPasch** [comment]
Problem kann ich bestätigen. Gestern System neu aufgesetzt - alles händisch neu interlegt. Alexa2 verweigert den Dienst. Es kommt immer der Amazon-Login, der - egal welchen PW man nimmt - auf die "Cookie aktivieren" Seite geht.

**Comment by melon-1999** [comment]
Ich habe auch schon öfters versucht manuell den Cookie zu erstellen aber das hat auch nicht funktioniert.

**Comment by rokestar** [comment]
Ich schließe mich ebenfalls an. Gestern das System neu aufgesetzt und nun der gleiche Fehler. Wäre ebenfalls dankbar für eine Lösung :)

**Comment by awillrich** [comment]
gleiches hier...

**Comment by Apollon77** [comment]
bin dran, wird aber eher morgen

**Comment by nachtschatt3n** [comment]
bei mir gehts auch nicht .. .ich habe den cookie manuell geholt und die erste Seite sagt auch gut aber verbinden kann ich mich trozdem nicht

**Comment by canim60** [comment]
> bin dran, wird aber eher morgen

ehrenmann

**Comment by downspath** [comment]
i have the same problem like melon-1999

**Comment by Selyria** [comment]
Jo ich kann dem ganzen nur zustimmen habe das gleiche prob wie alle hier

**Comment by tagelang** [comment]
Ja bei mir ist genau das selbe problem. Kann mich den zich anderen leuten hier anschließen :D

**Comment by mpffh1** [comment]
Hi ich hab genau das und eine Lösung (schmutzig aber wirkungsvoll) . Löscht als erstes den Alexa2 Adapter. Dann Instaliert ihr diesen: https://github.com/AntonTrojer/ioBroker.alexa2 (ist ein alter Fork).
Erzeugt eine Instanz , gebt eure Zugangsdaten ein ,kontrolle ob grün und dann einfach Adapter Update anstoßen

**Comment by Apollon77** [comment]
Also ob das mit dem Login tut ist reines Glück.

**Comment by mpffh1** [comment]
Mag schon sein ,aber wens hilft hast du erst mal Zeit zum fehler suchen gewonnen. 
MfG

**Comment by Backfire-FF** [comment]
Bei mir hilft es leider nicht.

**Comment by downspath** [comment]
Short term solution: go to adapters, activate expert mode (to be able to install old versions), click on alexa2 > install old version. Now choose version 1.1.3 or below.

after downgrading, go to instances and type your login data to the alexa settings. after that wait until the light stays green. 

now you can update to the most recent version again.

**Comment by mpffh1** [comment]
@downspath  **delet** Alexa2 **completly** and than get the clean V1.10  https://github.com/AntonTrojer/ioBroker.alexa2 don´t downgrad directly ,that don´t work
cu

**Comment by Apollon77** [comment]
Ich habe die Ursache gefunden ... Amazon hat eine Kleinigkeit in den HTTP-Headern geändert was dann dazu geführt hat das dir wichtigen Cookies blockiert wurden.

ich bereite jetzt mal alles vor und denke morgen gibt es eine neue Verison (bin aber jetzt zu müde und will es sauber testen)

**Comment by tagelang** [comment]
Also ich kann mich
![15922389433242352998219960294897](https://user-images.githubusercontent.com/66916100/84683175-18103980-af37-11ea-9355-888576c84cc3.jpg)
 aktuell immernochnicht anmelden. Nachdem ich meine anmeldedaten angegeben habe zeigt mir das fenster an das die seite nicht erreichbar ist

**Comment by Backfire-FF** [comment]
Noch hat @Apollon77 noch keinen neuen Release hochgeladen! ☝🏼

**Comment by tagelang** [comment]
Achso. Ich habe mich schon gewundert das mir ein update für den adapter angezeigt wird

**Comment by Backfire-FF** [comment]
Bei mir hat es jetzt funktioniert:

Alexa2 Adapter löschen, ioBroker neustarten.
3.1.2 direkt über Github installieren und anmelden.

Vllt funktioniert es bei dem einen oder anderen ebenfalls.

**Comment by Apollon77** [comment]
Ja, alle Github issues durchzugehen und so ist etwas aufwändiger gewesen als gedacht und dann wars zu spät. Ich hoffe ich kriege es heute Abend finalisiert

**Comment by AlexKusnezov** [comment]
bei mir hats auch funktioniert nach der Anleitung von @Backfire-FF

**Comment by Heisenberg2018** [comment]
Hat bei mir auch mit der Installation von GitHub funktioniert, muss ich irgendwas machen wenn wieder normale Updates kommen?

**Comment by Apollon77** [comment]
fixed in 3.2.0

**Comment by OlafWalther1969** [comment]
Super vielen, Dank! Die Anmeldung des Alexa2 Adapters funktioniert wieder mit den Amazon Zugangsdaten.
Ich musste erst den Alexa2 Adapter löschen und auch aus der IoBroker Bibliothek entfernen und danach die neuste Version von GitHub installieren. Anschließend wurde erst der neueste Alex2 Adapter (3.2.4) angezeigt.
Vielleicht hilft das noch Jemanden, der so eine "Einsteiger" ist wie ich.

Liebe Grüße

**Comment by Apollon77** [comment]
Ja die 3.4.3 ist noch nicht im Stable Repo. kommt aber heute abend
