### ISSUE TITLE
getIdByName not working in Kombination with Alexa

### ISSUE THREAD

**Issue by Marty56** [Apollon77/ioBroker.alexa2#48]
I am not sure where to place this issue but since it is appearing when I am instantiating Alexa.2 I am putting it here.

I like to work with getIdByName
e.g. getIdByName('AS_Temperature.TEMPERATURE') 
I have also setup a smart device in the cloud adapter pointing to the device. 

when I am invoking 
log(getIdByName('AS_Temperature.TEMPERATURE')) I am getting

hm-rpc.0.LEQ0567712.1.TEMPERATURE,alexa2.0.Smart-Home-Devices.5b7be6ca-f4bd-4cc8-872f-f3c3f834e661

I would expect hm-rpc.0.LEQ0567712.1.TEMPERATURE alone.
Disabling alexa.2,removing all alexa.2  related objects and restarting javascript delivers in the expected result.

**Comment by Marty56** [comment]
[log.txt](https://github.com/Apollon77/ioBroker.alexa2/files/2237889/log.txt)

**Comment by Apollon77** [comment]
If this is an issue (is the name maybe identical?) then it is an issue with JavaScript adapter. 

Please open issue the together with the object definition (pencil right in object list and then raw json) of both objects found.

**Comment by Marty56** [comment]
Those two object both have the same name.
`Homematic Temperature Messer

{
  "from": "system.adapter.hm-rpc.0",
  "ts": 1532358244874,
  "common": {
    "name": "AS_Temperature.TEMPERATURE",
    "type": "number",
    "unit": "°C",
    "role": "value.temperature",
    "def": 0,
    "min": -40,
    "max": 80,
    "read": true,
    "write": false,
    "custom": {
      "history.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "1000",
        "maxLength": "960",
        "retention": "2678400",
        "changesRelogInterval": 0,
        "changesMinDelta": 0
      }
    },
    "smartName": {
      "de": "Außen",
      "smartType": "THERMOSTAT"
    }
  },
  "native": {
    "AutoconfRoles": "WEATHER",
    "ID": "TEMPERATURE",
    "TYPE": "FLOAT",
    "UNIT": "�C",
    "DEFAULT": 0,
    "FLAGS": 1,
    "MAX": 80,
    "MIN": -40,
    "OPERATIONS": 5,
    "TAB_ORDER": 0
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "hm-rpc.0.LEQ0567712.1.TEMPERATURE",
  "type": "state"
}

Smart device
{
  "from": "system.adapter.hm-rpc.0",
  "ts": 1532358244874,
  "common": {
    "name": "AS_Temperature.TEMPERATURE",
    "type": "number",
    "unit": "°C",
    "role": "value.temperature",
    "def": 0,
    "min": -40,
    "max": 80,
    "read": true,
    "write": false,
    "custom": {
      "history.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "1000",
        "maxLength": "960",
        "retention": "2678400",
        "changesRelogInterval": 0,
        "changesMinDelta": 0
      }
    },
    "smartName": {
      "de": "Außen",
      "smartType": "THERMOSTAT"
    }
  },
  "native": {
    "AutoconfRoles": "WEATHER",
    "ID": "TEMPERATURE",
    "TYPE": "FLOAT",
    "UNIT": "�C",
    "DEFAULT": 0,
    "FLAGS": 1,
    "MAX": 80,
    "MIN": -40,
    "OPERATIONS": 5,
    "TAB_ORDER": 0
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "hm-rpc.0.LEQ0567712.1.TEMPERATURE",
  "type": "state"
}
`

**Comment by Apollon77** [comment]
Naja damit ist klar warum es doppelt gefunden wird. Also kein bug. 

Es gibt keinerlei Definition das Adapter (wie In dem Fall - wo es sogar passt weil gleiches Gerät) nicht gleiche Namen wie ander devices vergeben. 

Der getIdByName Ansatz geht sehr gut wenn du die Objekt Namen unter Kontrolle hast - also bei eigenen Objekten ;-)

Der alexa Adapter bekommt die Namen von alexa wie sie da heißen. Du kannst die Geräte in alexa umbenennen dann sollten die Namen hier auch anders sein. 

Geplant sind „virtuelle“ devices ... da könnte man mehr kontrolle haben.

**Comment by Marty56** [comment]
Ok. I have patch raw section of the smart device.
The error is gone for the time being.
But it should be fixed TMHO:

**Comment by Marty56** [comment]
Unfortunately the patch is overwritten after every restart of iobroker.

**Comment by Marty56** [comment]
Shall I still open an issue in the Javascript Adapter?
Maybe you could had an extension to the name when creating the smart device object to avoid this collision.

**Comment by Apollon77** [comment]
What patch You did and where?

No issue with js is not needed because no bug. 

I do not think an adapter should do this. (In general) In this case the adapter gets the names from Alexa data and just use it as it was there. This is the expected behavior. Names are not changed!! This would confuse people. See it from this direction please. 

So: rename in alexa app or change in your Skripts that it is handled or such.

**Comment by Marty56** [comment]
I think you did not full understand the bug.
the name in my example "AS_Temperature.TEMPERATURE" is generated by the cloud adapter when I am creating a smart Alexa device which controls  a sensor (in my case the homematic sensor).

Therefore it is impossible for me to avoid this double naming.
What I can do is 
1. delete all the smart devices from the Alexa.2 object tree
2. rename the smart device in the Alexa.2 object tree.

All those "patches" are only temporary because the double naming will return after each restart of iobroker.

Currently I can only omit the use of the getIdByName function in such cases. 
Which is sad because it would be fixed easily.
Instead of just copying the name from the cloud adapter smart object, you could create a smart object in your object tree having a slightly modified name. e.g. instead of "AS_Temperature.TEMPERATURE" you could create e.g. "As_Temperature.Temperature.Alexa"

It was not a problem before because the cloud adapter smart objects did not appear in the object tree. Therefore the getIdByName function resulted only into one identifier.

**Comment by Apollon77** [comment]
You can rename the devices in Alexa app too. 

This case where objects are created by ioBroker and then come back via a second adapter is kind of special. 

Problem is that People want to have correct names in Alexa app to be able to match the smart home devices there to the real ones. 

And as separate topic when using Alexa adapter you need to be able to match too (and consider that other people also have other devices there) yoinked to be ablehnte match the names too. 

So I stay with my opinion (but will internally discuss with other core developer too): Adapter should not change names (in both cases)

What you easily can do is to create a global script with your own getById function that checks if more then one result game and maybe sort out those starting with alexa2 or such and return a unique value. Then use this function in all your scripts.

**Comment by Marty56** [comment]
I can rename the device in the Alexa app but this is no solution because the name of the identifier in the Alexa app is listed under "Beschreibung" and this cannot be changed.

The second solution by processing the result of the getById is a very poor workaround and I think we should avoid this.

**Comment by Apollon77** [comment]
I thought again and not this is not a workaround, this is the solution!

Each adapter for itself is working completely correct.
* Cloud is handing over the object names as they are so that people can match in Alexa App
* Alexa adapter uses the names from Alexa to allow matching to Alexa-App
* Javascript getById is correct and returns both objects with the name

The only "incorrect" thing is the main assumption in your scripts that "object names" are unique in the whole system. This is a simply wrong assumption! Nowhere it is stated that this is the case - and by design it can not be the case because the object id is the ONLY unique thing.
So the assumption in your scripts now breaks because you come in this special case ... so where we need to fix it? Not tin the adapters ...

Because of this (and I see this logical from a overall system standpoint, yes maybe for you and your scripts it is suboptimal) the place to fix it is the one place that uses a wrong assumption!
Becaus eof this it is completely valid to create a custom getById function for your scripts that makes sure that the assumption stays valid by checking for the return value and if multiple object names are returned need to select "the" valid one.

**Comment by Marty56** [comment]
Thanks for this elaborate statements. I see your points.
I also understand that your adapter should not fix weakness which have been created in the cloud adapter.
From the system standpoint I see not good reason that the cloud adapter is creating the same names  for different things without good reasons.

I will be using direct ids for those device I want to control with Alexa. So it is not really worth discuss further.

Thanks for your time.
