### ISSUE TITLE
HomeMatic einzelne Geräte werden nicht mehr in Alexa angezeigt - Nur noch Räume schaltbar

### ISSUE THREAD

**Issue by sometimestoday** [Apollon77/ioBroker.alexa2#480]
Seit dem 10.06. werden nur noch Räume in Alexa erkannt. Einzelne Geräte z.B. Steckdosen werden nicht mehr als Geräte erkannt und lassen sich somit nicht einzeln schalten. Blind-Schalter wie Rollos oder Dimmer werden jedoch angezeigt. Ebenso lassen sich noch Scripte steuern. Jemand eine Idee?

**Comment by Apollon77** [comment]
Adapter mal neu gestartet?

**Comment by sometimestoday** [comment]
Alles reebotet - Raspberry mit ioBroker und CCU. 
Alle Adapter auf der neusten Version. 
Node.js auf v12.18.0
DEBUG.LOG gibt auch keine weitern Auskünfte.
Im ioBroker sind alle Geräte vorhanden.
Skill deaktiviert, wieder aktiviert und neu verbunden. Mehrfach neu suchen lassen. Leider alles ohne Erfolg. Räume und Script werden angezeigt und lassen sich bedienen. Nur die einzelnen Geräte werden nicht mehr gefunden.

**Comment by Apollon77** [comment]
Äääähmmm... langsam. Was ist das Problem? Geräte aus iobroker sind in alexa nicht mehr gelistet und sind nicht mehr per Sprache bedienbar?? Dann hat das nichts mit dem Alexa2 adapter zu tun. Dann im iot Adapter prüfen das da alles korrekt ist.

Oder wie kommen die „homematic Geräte“ in den Alexa2 Adapter wenn sie aus iobroker kommen?

Bist du beim richtigen Adapter?

**Comment by sometimestoday** [comment]
Besten Dank - ich versuche es dann mit dem iot. Mal sehen ob ich da zum Erfolg komme.
