### ISSUE TITLE
New Device und neuerdings speak command Probleme (Lenovo Smart Tab M10)

### ISSUE THREAD

**Issue by vito6666** [Apollon77/ioBroker.alexa2#481]
Moin Moin, seit ca. 1-2 Wochen funktioniert die Sprachausgabe auf meinem Lenovo Smart Tab M10 nicht mehr. Alles andere (speak-volume, traffic,...) funktioniert und wenn das speak command getriggert wird, wird die Lautstärkeleiste eingeblendet aber es erfolgt keine Sprachausgabe. "Bitte nicht stören" ist aus und ich habe den Show Modus schon komplett gelöst, deinstalliert und neu eingerichtet. Getestet habe ich Version 3.0.5 und 3.1.2 mit Node.js v12.18.0 und NPM 6.14.4. Auf meinem Echo Dot funktioniert "speak" einwandfrei.

New Device: 
info: alexa2.0 (13553) Device-type:A2J0R2SD7G9LPA (KINDLE_BOOKS,AUDIO_PLAYER,FAR_FIELD_WAKE_WORD,SOUND_SETTINGS,VOICE_TRAINING,TIMERS_AND_ALARMS,POPTART,CHANGE_NAME,I_HEART_RADIO,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,FLASH_BRIEFING,SET_LOCALE,DREAM_TRAINING,MICROPHONE,TUNE_IN,EARCONS,SHARKNADO,SLEEP,AUDIBLE,AMAZON_MUSIC,SALMON,REMINDERS,GADGETS,GOLDFISH,SUPPORTS_LOCALE_SWITCH,SUPPORTS_LOCALE,PANDORA,MUSIC_SKILL,ASCENDING_ALARM_VOLUME,PERSISTENT_CONNECTION,VOLUME_SETTING,CUSTOM_ALARM_TONE)

**Comment by Apollon77** [comment]
Geht es denn noch per Alexa App? Gibt der Adapter Ausgaben zu dem Gerät wenn er startet?

**Comment by vito6666** [comment]
Hi Apollon, im Log stehen "nur" die Einträge mit "Report new device, ...". Sorry, dass ich das nicht früher gemeldet habe, aber da es bisher funktioniert hat habe ich den Logeintrag jetzt erst bemerkt.

Die "Amazon Alexa - Show-Modus für Lenovo" App läuft. Alexa kann man ganz normal bedienen und auch z.B. der Button im "traffic" Objekt sorgt für die passende Sprachausgabe. Alles bis auf "speak" läuft.

Gruß
Vito

**Comment by Apollon77** [comment]
Die frag ist ob du per Alexa App auf einem anderen Handy auf dem fraglichen device eine sprachausgabe machen kannst. Am Ende ist es so das der Adapter nur die gleiche api nutzt wie die App. Und am Ende entscheidet Amazon was geht und was nicht. Da kann ich im Zweifel nichts tun. 

Wenn die Meldung im log vom Gerät kommt dann sind die Kommandos freigeschaltet. Also gehen sie zu Amazon.

**Comment by vito6666** [comment]
Ja, meine Nachricht über die App habe ich gehört. Sie wurde auf dem Lenovo Tablet vorgelesen wie bisher meine ioBroker Texte.
![Screenshot_20200614-211255_Amazon Alexa](https://user-images.githubusercontent.com/52350854/84601899-dffbee80-ae83-11ea-842e-155d6a9fbb7f.jpg)

**Comment by Apollon77** [comment]
"Ankündigung" ist aber nicht "speak"!!! Am Ende gibt es aktuell 3 Wege für SPrachausgaben:
* Speak
* SSML
* Announcement

Ankündigung ist letzteres! Tut das vllt?

**Comment by vito6666** [comment]
Oh sorry, speak funktioniert über ein Handy auch nicht auf dem Tablet (auf dem Dot schon), da muss Amazon wohl irgendwas "optimiert" haben. Die Ankündigung funktioniert allerdings über das Handy auf dem Tablet, aber nicht über das Objekt im ioBroker. Das wäre zwar eine Notlösung, wenn es funktionieren würde aber eine unschöne, weil der Echo Show Modus dann eingeblendet wird. 
Vielen dank für deinen Support!

**Comment by Apollon77** [comment]
> Die Ankündigung funktioniert allerdings über das Handy auf dem Tablet, aber nicht über das Objekt im ioBroker. 

Ok dann bitte:
* EIne Routine mit so einer ankündigung in der alexa app anlegen und testen
* iobroker Adapter neu starten, vor debug log aktivieren
* jetzt per ioBroker die angelegte Routine starten - sagen ob es geht (Zeit notiern damit ich es im Log zuordnen kann)
* jetzt per Command Datenpunkt eine Ankündigung machen
* Log von der Platte holen von der ganzen Aktion und mit senden per email an iobroker@ficher-ka.de mit referenz auf dieses Github issue hier!

**Comment by vito6666** [comment]
Da gibt es leider ein Problem. Ich kann bei der Routine als Ankündigung nur meinen Echo Dot oder "Alle Geräte" auswählen (bei Say kann ich auch das Tablet oder die FireTVs auswählen). Wenn ich als Ankündigung "Alle Geräte" auswähle kommt die Ausgabe nur aus dem Dot. Über "Kommunikation -> Ankündigung" wird die Ankündigung auch auf den Tablet vorgelesen.

**Comment by Apollon77** [comment]
Nachrichten - Ankündigung ist commands.Announcement im Adater
Aleca sagt - Benutzerdefinier ist commands.speak

Also was tut jetzt wie wenn Du es per App machst? Und wie per Adapter?

**Comment by vito6666** [comment]
Ich habe jetzt alles noch einmal durchgetestet:
1. Weder bei announcement noch speak über den Adapter wird Sprache auf dem Tablet ausgegeben
1.1 Es erscheint aber in dem Moment am Displayrand vom Tablet der Lautstärkebalken, der bisher immer zusammen mit der Sprachausgabe kam. Die Kommunikation funktioniert also prinzipiell.
2. Wenn ich über die App eine Ankündigung über "Kommunikation" mache, wird sie wiedergegeben auf Tablet und Echo
3. Wenn ich eine App Routine baue mit einer Ankündigung auf alle Geräte (Tablet steht nicht zur Wahl) wird sie nur auf dem Echo wiedergegeben
4. Wenn ich eine App Routine baue mit "sag" steht zwar das Tablet zur Auswahl, es erfolgt allerdings keine Sprachausgabe am Tablet (und auch keine Einblendung des Lautstärkebalkens).

**Comment by Apollon77** [comment]
zu 2.) Das ist eine Notification (der Gelbe ring) korrekt? Das ist per Adapter eine "Notification". Geht das?

zu 3./4. also wie beim Adapter? Die Lautstärke kommt nur weil du garantiert eine "speak-volume" angegeben hast und damit setzt er die Lautstärke, macht die Sprachausgabe und setzt die Lautstärke zurück.

Bedeutete also: Der Adapter kann (wenn 2. auch tut) das gleiche was die App kann ... und genau das ist das maximale was geht.

Also: Wende dich an Amazon das Du gern auf Deinem Tablet auch eine Sprachansagen willst.

**Comment by vito6666** [comment]
Zu 2.) Nein, der Echo Ring blinkt hell und dunkel blau und auf dem Tablet wird die "Echo Show für Lenovo" Oberfläche eingeblendet. Wenn ich das Objekt Tablet -> Commands -> notification ändere bekomme ich auf dem Handy eine Pushnachricht. alles andere bleibt stumm und es wird nichts angezeigt.

zu 3./4.) Genau und du hast recht, die Einblendung kommt nicht bei leerem speak-volume.

Bis auf die "globale" Ankündigung, die aus der App funktioniert hast du recht. Ich habe das Konstrukt leider erst durch deine Posts hier durchblickt und hoffe dich nicht zu sehr genervt zu haben. Vielen dank auch für deine anderen Adapter! Ich melde mich jetzt mal bei Amazon. 

Gruß
Vito
