### ISSUE TITLE
Neuer device Type A30YDR2MK8HMRV 

### ISSUE THREAD

**Issue by RK62** [Apollon77/ioBroker.alexa2#482]
Report to developer as GitHub issue with details for device. 
Please grab full next line pot. from logfile on disk if cutted

Gruß, Ralf

`alexa2.0 (32693)     Device-type:A30YDR2MK8HMRV (DREAM_TRAINING,DISPLAY_BRIGHTNESS_ADJUST,SUPPORTS_LOCALE,TUNE_IN,TUPLE_CATEGORY_A,KINDLE_BOOKS,ALEXA_PRESENCE,GOLDFISH,I_HEART_RADIO,DEREGISTER_DEVICE,DIALOG_INTERFACE_VERSION,CHANGE_NAME,UPDATE_WIFI,AUDIO_CONTROLS,TUPLE,REMINDERS,EQUALIZER_CONTROLLER_TREBLE,GADGETS,SUPPORTS_LOCALE_SWITCH,TIMERS_AND_ALARMS,ALEXA_GESTURES,EQUALIZER_CONTROLLER_MIDRANGE,AUDIO_PLAYER,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,SUPPORTS_SOFTWARE_VERSION,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,POPTART,SOUND_SETTINGS,ACTIVE_AFTER_FRO,PANDORA,DS_VOLUME_SETTING,PERSISTENT_CONNECTION,SLEEP,GUARD_EARCON,SUPPORT_CALENDAR_ALERT,EQUALIZER_CONTROLLER_BASS,AUDIBLE,EARCONS,FLASH_BRIEFING,PAIR_REMOTE,CUSTOM_ALARM_TONE,CLOCK_FORMAT_24_HR,DISPLAY_POWER_TOGGLE,REQUIRES_OOBE_FOR_SETUP,MICROPHONE,MUSIC_SKILL,FAR_FIELD_WAKE_WORD,VOICE_TRAINING,TAHOE_BYOD,PAIR_BT_SOURCE,PAIR_BT_SINK,AMAZON_MUSIC,SALMON,ASCENDING_ALARM_VOLUME,BT_PAIRING_FLOW_V2,LEMUR_ALPHA,SET_LOCALE,DISPLAY_ADAPTIVE_BRIGHTNESS,VOLUME_SETTING)
`

**Comment by Apollon77** [comment]
> Report to developer as GitHub issue with details for device.

Please add these details about the device! Wht is it? What can it do?

**Comment by RK62** [comment]
This is the "Echo Dot (3. Gen.) – smarter Lautsprecher mit Uhr und Alexa, Sandstein Stoff" and it works fine with your adapter. See https://www.amazon.de/amazon-echo-dot-3-gen-smarter-lautsprecher-mit-uhr-alexa/dp/B07NQCVHQ6

It has the same functions as the normal echo dot, additional:
- Time display
- Stop watch display
- Temperature display

**Comment by Apollon77** [comment]
Danke kommt in nächste version rein
