### ISSUE TITLE
Command Speak is not working

### ISSUE THREAD

**Issue by goedelmann** [Apollon77/ioBroker.alexa2#489]
Hi Apollon77,

After whole Upgrade of iobroker and Adapters the Speak Command of the alexa2 Adapter is not working any more.
Problem seems to be related to all media.tts Commands.
All other Commands are working fine.

At the moment I am running Version 3.2.4

Can you please help.

Ciao

Gogo

**Comment by Apollon77** [comment]
The adapter gets green? Other commands do work?
Can you do spark/announcememts via the Alexa App?

For me and many others everything work still

**Comment by goedelmann** [comment]
Hi,

Adapter is green.
All other commands are working fine.

I will try your suggestion to test spark/announcements.
Good Idea.

Many Thanks.

Perhaps it is related to SONOS.
The "Alexa Device" that should speek is a SONOS One.

Ciao

Gogo

**Comment by Apollon77** [comment]
ahhh Sonos? Then sorry bt it seems that Amazon/Sonos killed that ... You should also not be able to do it via Alexa App ... see Forum or other "closed" issues here ...
