### ISSUE TITLE
Routines where not updated

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.alexa2#49]
Hi, 
I created some new routines, and deleted in the alexa-app some old ones.. but the adapter don't update it. 
My workaround was to stop the adapter, delete the complete object-directory, and restart the adapter.

**Comment by Apollon77** [comment]
Restart is enough to recreate new routines but yes old ones are not removed.  Will take this on todo also for devices and everything ...

**Comment by Apollon77** [comment]
check 0.4.0 from GitHub and https://forum.iobroker.net/viewtopic.php?f=37&t=16095
