### ISSUE TITLE
Alexa Command Speak on Sonos One doesn't work anymore

### ISSUE THREAD

**Issue by MrRo-de** [Apollon77/ioBroker.alexa2#490]
**Check if the Bug maybe is with Amazon**  
the speak command during the amazon app works fine on every device.

**Describe the bug**  
The Command Speak doesn't work anymore on the Sonos One. It doesn't matter if I type "Hallo" in the speak command or do it with a node program. And even in the node program where I use a loop the sonos one says nothing and the echo dot version 1 says it only one time. Before the last update everything worked fine. 

**To Reproduce**  
1. Go to a Sonos One Device to 'command.speak'
2. type in what you want 'hallo'
3. See error .. nothing happened

**Versions:**  
Everything is up to date
 - Adapter version: 3.2.4
 - JS-Controller version: <iobroker -v = 3.1.5>
 - Node version: <v12.18.1>
 - Operating system: raspberry pi 4 - linux

**Comment by Apollon77** [comment]
Did you tried if it works in the Alexa App? Current info is that Amazon/Sonos changed something and broke it - Adapter can not do anything
