### ISSUE TITLE
http://10.0.3.2:42431/ not reachable

### ISSUE THREAD

**Issue by TrippleP** [Apollon77/ioBroker.alexa2#492]
Whenever I try to connect the Adapter to Amazon, accessing the URL http://10.0.3.2:42431/ fails with not available, same from any device

1. Go to ioBroker -> Adapter
2. Start Adapter 
3. open Adapter settings
4. Click on Link to coneect Amazon
5. Error "ERR_CONNECTION_TIMED_OUT"

Versions:
 - Adapter version: 3.2.4
 - JS-Controller version: 2.2.9
 - Node version: <node-version> 10.20.1
 - Operating system: Debian

**Comment by Apollon77** [comment]
I assume you use Docker? Then you need to use Admin Setting of Alexa2 Adapter to set a hard port and define the "external docker IP" and then make sure this port can e accessed from outside
