### ISSUE TITLE
V3.0.5: Datenpunkt "online" wird mit Verzögerung von mehreren Stunden aktualisiert

### ISSUE THREAD

**Issue by JayVee2** [Apollon77/ioBroker.alexa2#495]
Hallo zusammen,

ich überwache den Datenpunkt alexa2.0.Echo-Devices.[xxx].online.
Wird Alexa offline (power off), dauert es Stunden, bis das Flag "online" auf FALSE gesetzt wird. Nach Power On entsprechend.

Kann man da einfach was machen, damit das aschneller reagiert, also z.B. innerhalb von ein 2 Minuten.

Grüße Jayvee

**Comment by Apollon77** [comment]
Das Online Flag wird aktualisiert wenn Amazon via Push Message dazu eine Meldung sendet. Mach gern mal Debug Log an und du solltest sehen wann die Meldungen via Push kommen. Schneller kann der Adapter nicht sein.

**Comment by JayVee2** [comment]
Danke für die Rückmeldung.
Verstehe ich das richtig, dass der Adapter nur mit dem Amazon Alexa Service kommuniziert, nicht jedoch mit den Alexa Geräten selbst?
Verstehe ich auch richtig, dass es damit keine einfach Möglichkeit gibt festzustellen, ob eine Alexa Geräte online ist?

**Comment by Apollon77** [comment]
>  Verstehe ich das richtig, dass der Adapter nur mit dem Amazon Alexa Service kommuniziert, nicht jedoch mit den Alexa Geräten selbst?

Korrekt. Es gibt keine Lokalen Schnittstellen

>  Verstehe ich auch richtig, dass es damit keine einfach Möglichkeit gibt festzustellen, ob eine Alexa Geräte online ist?

Korrekt. Ich würde keine kennen.

**Comment by JayVee2** [comment]
Danke.
Ich prüfe quick&dirty auf Alexa online dann via 
nmap <ip> -PN -F
und im Code:
let online = (out.match("PORT     STATE SERVICE") !== null);
Das scheint zu gehen.
