### ISSUE TITLE
Datenpunkt "powerState"  wird  nicht aktualisiert

### ISSUE THREAD

**Issue by swa00** [Apollon77/ioBroker.alexa2#496]
Hallo  Ingo,

ich  versuche  eben mit SimpleAPI  die mit Alexa  angelegten Gruppen aus deinem Adapter auszulesen,
um zu schauen ,welche  Gruppen an/ausgeschaltet worden sind. (Zwecks  Steuerung mit eigener App)
Leider aktualisiert  sich  im Adapter unter der angezeigten Gruppe nicht der  entsprechende  Datenpunkt "powerState".
Manuelles  setzen funktioniert allerdings.
(Interval resp. Push-Änderungen im Setup  haben nichts  gebracht)  

Mach ich einen grundsätzlichen Denkfehler  , um mein Projekt  umzusetzen ?
Alternativen ?

Lieben Dank an  Dich

**Comment by Apollon77** [comment]
Smart devices werden nicht automatisch aktualisiert. Bitte den #query Datenpunkt nutzen um zu aktualisieren.

**Comment by swa00** [comment]
Ich  danke  Dir  für deine Mühe Ingo !! :-)

 

 

 

Gesendet: Donnerstag, 25. Juni 2020 um 20:56 Uhr
Von: "Ingo Fischer" <notifications@github.com>
An: "Apollon77/ioBroker.alexa2" <ioBroker.alexa2@noreply.github.com>
Cc: "swa00" <stwitr@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [Apollon77/ioBroker.alexa2] Datenpunkt "powerState" wird nicht aktualisiert (#496)


 

Smart devices werden nicht automatisch aktualisiert. Bitte den #query Datenpunkt nutzen um zu aktualisieren.
