### ISSUE TITLE
Wechsel zu Spotify wird Gerät umbenannt

### ISSUE THREAD

**Issue by mikiline** [Apollon77/ioBroker.alexa2#5]
Wenn ich über TuneIn Radio höre und dann per Sprachbefehl zu spotify wechsel, wird das gerät in "volume" umbenannt.

**Comment by Apollon77** [comment]
Hast Du bitte Debug log von so einem vorkommnis?

**Comment by mikiline** [comment]
Leider nein, es wird kein Log bei dem Wechsel erzeugt

**Comment by Apollon77** [comment]
:-( Dann am besten echt mal log anlassen und schauen wann es nochmal passiert ... ich muss wissen was da genau passiert.
Strange ist das an sich (weil der Adapte rja kein Polling macht) bei einem Wechsel per Sprache zu Spotify der Adapter davon nichts mitbekommt

**Comment by Apollon77** [comment]
Bitte erneut versuchen, wenn es immer noch passiert sollte der Adapter fast raus sein.Falls doch bitte mit Log mneu aufmachen
