### ISSUE TITLE
[Wunche] Alexa Triger Auslösen

### ISSUE THREAD

**Issue by dochardi** [Apollon77/ioBroker.alexa2#50]
Hallo

erstmal super Script

Ich hat aber ein idee wiso kann man nicht noch die function ein bauhen da mann alexe comandos gehben kann  wie zb Wits oder sprich wie yoda oder start horoskope etc

so das man sie ihr nicht sagen muss sonder sie starten per script, den so könnte man ein mogen routine starten wie zb erst erzehlte sie ein witze dan tages infos dan die termine und infos aus den iobroker

also ein copy von der "sprich mir nach" function nur halte ohne das er automatich das "sprich mir nach" das vor macht

wurde mich freuen wen ihr das machen könnted

**Comment by ooooli** [comment]
Kommandos via ioBroker statt Stimmer wären prima.
In meinem Fall könnte ich Alexa Stop gut gebrauchen.

**Comment by Apollon77** [comment]
An der Stelle gilt: wenn es die alexa App auf Handy oder im Browser kann dann kann es der Adapter ggf auch wenn man es baut. 

„Sprich mir nach“ ist Commands.speak 

Ansonsten kann man leider keinerlei „wie man es auch gesagt hätte“ Kommandos senden. Daher mache ich das issue zu. 

Falls ich das Thema nicht korrekt verstanden habe dann bitte nochmal genauer beschreiben.

**Comment by ooooli** [comment]
In der App geht’s, den Wecker zu deaktivieren -> aktueller Wecker ist eingeschaltet, solange er klingelt. Durch deaktivieren geht der Ton aus. Bin mal gespannt auf die Alarmunsetzung im Adapter, sollte ja dann auch gehen, sofern die Weckzeiten deaktivierbar ist

**Comment by Apollon77** [comment]
"start Horoskop" oder "Stop" sind textanfragen an Alexa ... das geht stand heute nicht, es sei denn du kannst das in einer routine machen.
Also: Wenn es möglich ist eine Routine anzulegen die irgendwie das horoskop startet ... dann debug log vom adapterstart her und ich kann es nachbauen

**Comment by Apollon77** [comment]
schaut mal https://forum.iobroker.net/viewtopic.php?f=37&t=16095&p=173376#p173376
