### ISSUE TITLE
invalid E-Mail adress

### ISSUE THREAD

**Issue by MBM1982** [Apollon77/ioBroker.alexa2#503]
Hi!

After I did a new setup of my Raspi and IoBroker I am not able to connect the adapter to Amazon. It tells me invalid e-mail address.
I double-checked it more than once. Did copy and paste... 
After I click on the "...connect to your Amazon account once..." it opens a new window with the IP of the Raspi at port 37113.
I type in my e-mail and my password. after that I am stuck. yesterday I was once redirectet to an amazon page with a "oops we are sorry we didn't find the  site you are looking for" or similar.

Any clues how to solve this? Is it a problem with amazon or the adapter, or my system?

**Comment by TTShadoX** [comment]
Hi,
i have the same issue. I have just installed the Alexa2 adapter and wanted to connect to Amazon. But it always tells me, that me email address is invalid. I have double-checked it several times.
Any ideas?
Thanks,

**Comment by Apollon77** [comment]
Yes it seems that Amazon changed things ... we need to check what we can do ... "in progress"

**Comment by HeinHan** [comment]
Adapter steht auf GELB, Anmeldung bei Amazon nicht mehr möglich, entweder falsche Mail-Adresse oder Passwort. Bei mehrmaligen Versuch taucht eine Fehlermeldung auf: "Cookie's" zulassen" oder eine andere Meldung Adresse Amazon Link gibt es nicht. Dies zur nfo

**Comment by MrRo-de** [comment]
Gibt es hier irgendwelche Neuigkeiten?

**Comment by Apollon77** [comment]
Wir analysieren noch ...

**Comment by totti1171** [comment]
Bei mir das gleiche Problem - noch als info: bei Node red das gleiche Bild/Problem

**Comment by Apollon77** [comment]
> bei Node red das gleiche Bild/Problem
Jupp, gleiche Library in Verwendung

**Comment by Apollon77** [comment]
Ein Adapter 3.2.5 kommt jetzt ... WICHTIG! Bevor Ihr es damit nochmal versucht wartet mindestens 12h nach eurem letzten Versuch davor!!

**Comment by JuergenHorvath** [comment]
musste auch das System neu machen. Alexa/Amazon hat mich dann 30 min im Kreis geschickt. Dachte es liegt an mir. Darf man fragen wann in etwa der Adapter wieder OK ist?

**Comment by Apollon77** [comment]
Liess mal exakt den kommentar eine Zeile über Deinem post

**Comment by JuergenHorvath** [comment]
danke. ich wusste nicht, dass jetzt auch "jetzt in diesem Moment" bedeutet. ;-) war nicht bös gemeint.

**Comment by Apollon77** [comment]
version should be in latest already

**Comment by totti1171** [comment]
Leider bei mir immer noch das gleiche Problem...
getestet hab ich mit meinem alten Docker - Image und auch mit nem neuen - Browser auch alle durch.

Noch einen Tipp für mich?

**Comment by Dragondrummer** [comment]
Hi, Ich hab auch noch das gleiche Problem. Habe über 12 Stunden gewartet. Bei mir läuft es auch in einem Docker Container. Was mir noch aufgefallen ist, wenn die Fehlermeldung angezeigt wird, springt die Adresse auf www.amazon.com/ap/signin. Ist "com" hier richtig? oder funktioniert es deshalb nicht.

**Comment by totti1171** [comment]
> Hi, Ich hab auch noch das gleiche Problem. Habe über 12 Stunden gewartet. Bei mir läuft es auch in einem Docker Container. Was mir noch aufgefallen ist, wenn die Fehlermeldung angezeigt wird, springt die Adresse auf [www.amazon.com/ap/signin](http://www.amazon.com/ap/signin). Ist "com" hier richtig? oder funktioniert es deshalb nicht.

Dies hab ich auch beobachtet...
Das wäre meine nächste Frage gewesen! ;-) Habe es auch schon über den Cookie-Weg probiert - hier bekam ich nach einiger Zeit die Alexa-Geräte angezeigt - allerdings ohne die Möglichkeit etwas an den Objekten zu tun.

**Comment by MrRo-de** [comment]
Hat geklappt, danke. @totti1171 @Dragondrummer habt ihr auch die richtige Version installiert? Mit 3.2.5 hat es sofort geklappt.

**Comment by Dragondrummer** [comment]
> 
> 
> Hat geklappt, danke. @totti1171 @Dragondrummer habt ihr auch die richtige Version installiert? Mit 3.2.5 hat es sofort geklappt.

Ja ich hab die 3.2.5. - bei mir das gleiche Fehlerbild wie vorher.

**Comment by MBM1982** [comment]
Erst einmal vielem DANK!
Im IoBroker steht noch die 3.2.4. das aktualisiert sich ja sicher auch noch. Bin noch unterwegs, vielleicht hat er bis dahin ja die 3.2.5.
Vielen Dank für deine Mühen

**Comment by Apollon77** [comment]
Kurz: Ja das war noch nicht die Lösung für alle ... sind noch dran

Lang:
Also wir sind inzwischen einen Schritt weiter ... Es scheint so das ein Datenfeld was bisher einfach "Random Daten" waren jetzt irgendeiner Struktur folgend muss. Bedeutet: einige gehen scheinbar und andere nicht. mit der Info wird die 3.2.5 bei einigen tun, bei anderen nicht ... und da ich mir (aus anderen gründen ) diese generierten Daten jetzt merke, wird es bei denen wo es tut so beiben und andersrum ebenso.

Bei denen es _nicht_ tut können gern Adapter beenden, schauen ob die Datei
/opt/iobroker/node_modules/alexa-cookie2/lib/formerDataStore.json 
ODER
/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/lib/formerDataStore.json 

existiert und diese löschen. Dann Adapter neu starten und neu versuchen.
Es gibt Berichte das es nach einer gewissen Anzahl versuchen dann plötzlich tut ... es gibt aber auch Berichte das man nach einer gewissen Anzahl versuche in weitere Amazon-SIcherheitsmechanismen rennt und dann sein Passwort zurücksetzen muss ... also AUF EIGENE GEFAHR!

**Comment by JuergenHorvath** [comment]
also hier das selbe Fehlerbild. Habe Alexa Adapter runter. dann die aktuelle 3.2.5 rauf. Adapter gelb. keine gültige email Adresse. Adapter stop. terminal Datei wie beschrieben gelöscht, Adapter neu gestartet. Selber Fehler wie davor.

**Comment by Apollon77** [comment]
Bitte 3.2-6 versuchen. SOllte ab morgen früh im Latest sein ... wir glauben wir habens wieder hinbekommen. Bitte Feedback geben!

**Comment by Dragondrummer** [comment]
> 
> 
> Bitte 3.2-6 versuchen. SOllte ab morgen früh im Latest sein ... wir glauben wir habens wieder hinbekommen. Bitte Feedback geben!

Super schnelle Arbeit - erstmal Danke für die Mühe. Ich komme jetzt zwar weiter aber es funktioniert trotzdem nicht. Ich kann mich jetzt erfolgreich einloogen und dann versucht er die Seite /IP/cookie-success zuerreichen -> Seiten Fehler.
Im log findet man folgendes:
alexa2.0	2020-07-15 01:49:55.409	error	(18179) Error: no csrf found
alexa2.0	2020-07-15 01:49:55.409	error	(18179) Error: no csrf found. Check configuration of cookie

**Comment by Jibbonator** [comment]
Guten morgen. ich habe es auch gerade ausprobiert und bekomme immernoch die falsche E-Mail Anzeige.

**Comment by Apollon77** [comment]
@Jibbonator Hattest Du die 3.2.5 versucht? Dann bitte

Bei denen es nicht tut können gern Adapter beenden, schauen ob die Datei
/opt/iobroker/node_modules/alexa-cookie2/lib/formerDataStore.json
ODER
/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/lib/formerDataStore.json

existiert und löschen bitte

**Comment by Apollon77** [comment]
@Dragondrummer Keine ahnung wads da bei dir kaputt ist ... Auch bitte nachder genannten Datei schauen. Instanz löschen und neu anlegen. Sonst bitte mal screenshot und vollständigeres Debug log

**Comment by Apollon77** [comment]
@JuergenHorvath Bitte mal paar Stunden warten, dann nochmal File löschen falls da und neu versuchen. Falls wieder nciht geht bitte mal Inhalt des Files hier posten

**Comment by Apollon77** [comment]
Generell: Wenn Ihr vorher schon oft versucht habt versucht bitte mal im Privaten Browser Modus!

**Comment by Dragondrummer** [comment]
> 
> 
> @Dragondrummer Keine ahnung wads da bei dir kaputt ist ... Auch bitte nachder genannten Datei schauen. Instanz löschen und neu anlegen. Sonst bitte mal screenshot und vollständigeres Debug log



Im Browser ist nach erfolgreicher Anmeldung folgendes zu sehen:
![grafik](https://user-images.githubusercontent.com/68281671/87525129-5f4e2f00-c689-11ea-90ab-fd56ee19f45d.png)

hier die Log-Meldungen nach:
- Stop Adapter
- deinstallation
- neuinstallation direkt auf 3.2.6
- Instanzerzeugen
- Anmelden bei Amazon

![grafik](https://user-images.githubusercontent.com/68281671/87524887-0d0d0e00-c689-11ea-9ce2-23d97d8ac644.png)

**Comment by MBM1982** [comment]
So sieht es bei mir auch aus

> > @Dragondrummer Keine ahnung wads da bei dir kaputt ist ... Auch bitte nachder genannten Datei schauen. Instanz löschen und neu anlegen. Sonst bitte mal screenshot und vollständigeres Debug log
> 
> Im Browser ist nach erfolgreicher Anmeldung folgendes zu sehen:
> ![grafik](https://user-images.githubusercontent.com/68281671/87525431-c835a700-c689-11ea-8570-3057410a85b2.png)
> 
> hier die Log-Meldungen nach:
> 
> * Stop Adapter
> * deinstallation
> * neuinstallation direkt auf 3.2.6
> * Instanzerzeugen
> * Anmelden bei Amazon
> 
> ![grafik](https://user-images.githubusercontent.com/68281671/87524887-0d0d0e00-c689-11ea-9ce2-23d97d8ac644.png)


So sieht es bei mir auch aus. Will aber noch einmal die 12h warten

**Comment by gitzorro** [comment]
@Apollon77 : Danke für die Mühen immer wieder bei Amazon-Änderungen nachzubessern:

Leider: Gestern die 3.2.5 probiert - heute (nach 12h) auch die 3.2.6 - aktuell bei mir leider auch dasselbe Verhalten:
Die lokale Webseite endet mit Anzeige der '/cookie-success' Page und dem Verbindung fehlgeschlagen-Fehler' - und der Error-Log bemäkelt 'Error: no csrf found'

**Comment by Apollon77** [comment]
Ok, nochnmal alles mit der 3.2.7 ... kommt gerade auf npm und dann zeitnah ins latest ... Github Install geht auch

**Comment by Dragondrummer** [comment]
> 
> 
> Ok, nochnmal alles mit der 3.2.7 ... kommt gerade auf npm und dann zeitnah ins latest ... Github Install geht auch
Super 👍 - Besten Dank jetzt hat's funktioniert 😃 - alles grün 🟢

**Comment by Dragondrummer** [comment]
> 
> 
> Ok, nochnmal alles mit der 3.2.7 ... kommt gerade auf npm und dann zeitnah ins latest ... Github Install geht auch

Super 👍 - Besten Dank jetzt hat's funktioniert 😃 - alles grün 🟢

**Comment by JuergenHorvath** [comment]
Perfekte Arbeit.... Hat mit 3.2.7 jetzt auch hier auf Anhieb geklappt. RIESEN Lob an den/die Entwickler. Super Support hier.

**Comment by totti1171** [comment]
Anmeldung mit der 3.2.7 sofort geklappt (nix gelöscht oder so)

**Comment by Jibbonator** [comment]
Mahlzeit, ich musste die Instanz und den Adapter löschen. Dann habe ich 3.2.7 installiert und es hat auf Anhieb funktioniert.

**Comment by Apollon77** [comment]
Hey, wenn es für Euch tut helft bitte mal kurz mit. Sucht mal das FIle

/opt/iobroker/node_modules/alexa-cookie2/lib/formerDataStore.json
ODER
/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/lib/formerDataStore.json

Und postet den inhalt (oder am Ende reicht die "deviceId") hier... Wir müssen noch was prüfen. Danke!!

**Comment by sigi2345** [comment]
`/* jshint -W097 */
/* jshint -W030 */
/* jshint strict: false */
/* jslint node: true */
/* jslint esversion: 6 */
"use strict";

const modifyResponse = require('http-proxy-response-rewrite');
const express = require('express');
const proxy = require('http-proxy-middleware').createProxyMiddleware;
const querystring = require('querystring');
const cookieTools = require('cookie');
const fs = require('fs');
const path = require('path');

const FORMERDATA_STORE_VERSION = 2;

function addCookies(Cookie, headers) {
    if (!headers || !headers['set-cookie']) return Cookie;
    const cookies = cookieTools.parse(Cookie);
    for (let cookie of headers['set-cookie']) {
        cookie = cookie.match(/^([^=]+)=([^;]+);.*/);
        if (cookie && cookie.length === 3) {
            if (cookie[1] === 'ap-fid' && cookie[2] === '""') continue;
            cookies[cookie[1]] = cookie[2];
        }
    }
    Cookie = '';
    for (let name in cookies) {
        if (!cookies.hasOwnProperty(name)) continue;
        Cookie += name + '=' + cookies[name] + '; ';
    }
    Cookie = Cookie.replace(/[; ]*$/, '');
    return Cookie;
}

function customStringify(v, func, intent) {
    const cache = new Map();
    return JSON.stringify(v, function (key, value) {
        if (typeof value === 'object' && value !== null) {
            if (cache.get(value)) {
                // Circular reference found, discard key
                return;
            }
            // Store value in our map
            cache.set(value, true);
        }
        if (Buffer.isBuffer(value)) {
            // Buffers not relevant to be logged, ignore
            return;
        }
        return value;
    }, intent);
}

function initAmazonProxy(_options, callbackCookie, callbackListening) {
    const initialCookies = {};

    if (!_options.formerRegistrationData) {
        try {
            if (fs.existsSync(path.join(__dirname, 'formerDataStore.json'))) {
                const formerDataStore = JSON.parse(fs.readFileSync(path.join(__dirname, 'formerDataStore.json'), 'utf8'));
                if (typeof formerDataStore === 'object' && formerDataStore.storeVersion === FORMERDATA_STORE_VERSION) {
                    _options.formerRegistrationData = _options.formerRegistrationData || {};
                    _options.formerRegistrationData.frc = _options.formerRegistrationData.frc || formerDataStore.frc;
                    _options.formerRegistrationData['map-md'] = _options.formerRegistrationData['map-md'] || formerDataStore['map-md'];
                    _options.formerRegistrationData.deviceId = _options.formerRegistrationData.deviceId || formerDataStore.deviceId;
                    _options.logger && _options.logger('Proxy Init: loaded temp data store ass fallback former data');
                }
            }
        } catch (_err) {
            // ignore
        }
    }

    if (!_options.formerRegistrationData || !_options.formerRegistrationData.frc) {
        // frc contains 313 random bytes, encoded as base64
        const frcBuffer = Buffer.alloc(313);
        for (let i = 0; i < 313; i++) {
            frcBuffer.writeUInt8(Math.floor(Math.random() * 255), i);
        }
        initialCookies.frc = frcBuffer.toString('base64');
    }
    else {
        _options.logger && _options.logger('Proxy Init: reuse frc from former data');
        initialCookies.frc = _options.formerRegistrationData.frc;
    }

    if (!_options.formerRegistrationData || !_options.formerRegistrationData["map-md"]) {
        initialCookies['map-md'] = Buffer.from('{"device_user_dictionary":[],"device_registration_data":{"software_version":"1"},"app_identifier":{"app_version":"2.2.223830","bundle_id":"com.amazon.echo"}}').toString('base64');
    }
    else {
        _options.logger && _options.logger('Proxy Init: reuse map-md from former data');
        initialCookies['map-md'] = _options.formerRegistrationData['map-md'];
    }

    let deviceId = '';
    if (!_options.formerRegistrationData || !_options.formerRegistrationData.deviceId) {
        for (let i = 0; i < 3; i++) {
            deviceId += Math.floor(Math.random() * 9).toString();
        }
        deviceId += '34c4643374c3541464b';
    }
    else {
        _options.logger && _options.logger('Proxy Init: reuse deviceId from former data');
        deviceId = _options.formerRegistrationData.deviceId;
    }

    try {
        const formerDataStore = {
            'storeVersion': FORMERDATA_STORE_VERSION,
            'deviceId': deviceId,
            'map-md': initialCookies['map-md'],
            'frc': initialCookies.frc
        };
        fs.writeFileSync(path.join(__dirname, 'formerDataStore.json'), JSON.stringify(formerDataStore), 'utf8');
    }
    catch (_err) {
        // ignore
    }

    let proxyCookies = "";

    // proxy middleware options
    const optionsAlexa = {
        target: `https://alexa.${_options.baseAmazonPage}`,
        changeOrigin: true,
        ws: false,
        pathRewrite: {}, // enhanced below
        router: router,
        hostRewrite: true,
        followRedirects: false,
        logLevel: _options.proxyLogLevel,
        onError: onError,
        onProxyRes: onProxyRes,
        onProxyReq: onProxyReq,
        headers: {
            'user-agent': "Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 PitanguiBridge/2.2.345247.0-[HARDWARE=iPhone10_4][SOFTWARE=13.5.1]",
            'accept-language': _options.acceptLanguage,
            'authority': `www.${_options.baseAmazonPage}`
        },
        cookieDomainRewrite: { // enhanced below
            "*": ""
        }
    };
    optionsAlexa.pathRewrite[`^/www.${_options.baseAmazonPage}`] = '';
    optionsAlexa.pathRewrite[`^/alexa.${_options.baseAmazonPage}`] = '';
    optionsAlexa.cookieDomainRewrite[`.${_options.baseAmazonPage}`] = _options.proxyOwnIp;
    optionsAlexa.cookieDomainRewrite[_options.baseAmazonPage] = _options.proxyOwnIp;
    if (_options.logger) optionsAlexa.logProvider = function logProvider(_provider) {
        return {
            log: _options.logger.log || _options.logger,
            debug: _options.logger.debug || _options.logger,
            info: _options.logger.info || _options.logger,
            warn: _options.logger.warn || _options.logger,
            error: _options.logger.error || _options.logger
        };
    };
    let returnedInitUrl;

    function router(req) {
        const url = (req.originalUrl || req.url);
        _options.logger && _options.logger('Router: ' + url + ' / ' + req.method + ' / ' + JSON.stringify(req.headers));
        if (req.headers.host === `${_options.proxyOwnIp}:${_options.proxyPort}`) {
            if (url.startsWith(`/www.${_options.baseAmazonPage}/`)) {
                return `https://www.${_options.baseAmazonPage}`;
            } else if (url.startsWith(`/alexa.${_options.baseAmazonPage}/`)) {
                return `https://alexa.${_options.baseAmazonPage}`;
            } else if (req.headers.referer) {
                if (req.headers.referer.startsWith(`http://${_options.proxyOwnIp}:${_options.proxyPort}/www.${_options.baseAmazonPage}/`)) {
                    return `https://www.${_options.baseAmazonPage}`;
                } else if (req.headers.referer.startsWith(`http://${_options.proxyOwnIp}:${_options.proxyPort}/alexa.${_options.baseAmazonPage}/`)) {
                    return `https://alexa.${_options.baseAmazonPage}`;
                }
            }
            if (url === '/') { // initial redirect
                returnedInitUrl =  `https://www.${_options.baseAmazonPage}/ap/signin?openid.return_to=https%3A%2F%2Fwww.${_options.baseAmazonPage}%2Fap%2Fmaplanding&openid.assoc_handle=amzn_dp_project_dee_ios${_options.baseAmazonPageHandle}&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_dp_project_dee_ios${_options.baseAmazonPageHandle}&accountStatusPolicy=P1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns.oa2=http%3A%2F%2Fwww.${_options.baseAmazonPage}%2Fap%2Fext%2Foauth%2F2&openid.oa2.client_id=device%3A${deviceId}&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.oa2.response_type=token&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&language=${_options.amazonPageProxyLanguage}`;
                _options.logger && _options.logger('Alexa-Cookie: Initial Page Request: ' + returnedInitUrl);
                return returnedInitUrl;
            }
            else {
                return `https://www.${_options.baseAmazonPage}`;
            }
        }
        return `https://alexa.${_options.baseAmazonPage}`;
    }

    function onError(err, req, res) {
        _options.logger && _options.logger('ERROR: ' + err);
        res.writeHead(500, {
            'Content-Type': 'text/plain'
        });
        res.end('Proxy-Error: ' + err);
    }

    function replaceHosts(data) {
        //const dataOrig = data;
        const amazonRegex = new RegExp(`https?://www.${_options.baseAmazonPage}:?[0-9]*/`.replace(/\./g, "\\."), 'g');
        const alexaRegex = new RegExp(`https?://alexa.${_options.baseAmazonPage}:?[0-9]*/`.replace(/\./g, "\\."), 'g');
        data = data.replace(/&#x2F;/g, '/');
        data = data.replace(amazonRegex, `http://${_options.proxyOwnIp}:${_options.proxyPort}/www.${_options.baseAmazonPage}/`);
        data = data.replace(alexaRegex, `http://${_options.proxyOwnIp}:${_options.proxyPort}/alexa.${_options.baseAmazonPage}/`);
        //_options.logger && _options.logger('REPLACEHOSTS: ' + dataOrig + ' --> ' + data);
        return data;
    }

    function replaceHostsBack(data) {
        const amazonRegex = new RegExp(`http://${_options.proxyOwnIp}:${_options.proxyPort}/www.${_options.baseAmazonPage}/`.replace(/\./g, "\\."), 'g');
        const alexaRegex = new RegExp(`http://${_options.proxyOwnIp}:${_options.proxyPort}/alexa.${_options.baseAmazonPage}/`.replace(/\./g, "\\."), 'g');
        data = data.replace(amazonRegex, `https://www.${_options.baseAmazonPage}/`);
        data = data.replace(alexaRegex, `https://alexa.${_options.baseAmazonPage}/`);
        if (data === `http://${_options.proxyOwnIp}:${_options.proxyPort}/`) {
            data = returnedInitUrl;
        }
        return data;
    }

    function onProxyReq(proxyReq, req, _res) {
        const url = req.originalUrl || req.url;
        if (url.endsWith('.ico') || url.endsWith('.js') || url.endsWith('.ttf') || url.endsWith('.svg') || url.endsWith('.png') || url.endsWith('.appcache')) return;
        //if (url.startsWith('/ap/uedata')) return;

        _options.logger && _options.logger('Alexa-Cookie: Proxy-Request: ' + req.method + ' ' + url);
        //_options.logger && _options.logger('Alexa-Cookie: Proxy-Request-Data: ' + customStringify(proxyReq, null, 2));

        if (typeof proxyReq.getHeader === 'function') {
            _options.logger && _options.logger('Alexa-Cookie: Headers: ' + JSON.stringify(proxyReq.getHeaders()));
            let reqCookie = proxyReq.getHeader('cookie');
            if (reqCookie === undefined) {
                reqCookie = "";
            }
            for (var cookie in initialCookies) {
                if (!initialCookies.hasOwnProperty(cookie)) continue;
                if (!reqCookie.includes(cookie + '=')) {
                    reqCookie += '; ' + cookie + '=' + initialCookies[cookie];
                }
            }
            if (reqCookie.startsWith('; ')) {
                reqCookie = reqCookie.substr(2);
            }
            proxyReq.setHeader('cookie', reqCookie);
            if (!proxyCookies.length) {
                proxyCookies = reqCookie;
            } else {
                proxyCookies += '; ' + reqCookie;
            }
            _options.logger && _options.logger('Alexa-Cookie: Headers: ' + JSON.stringify(proxyReq.getHeaders()));
        }

        let modified = false;
        if (req.method === 'POST') {
            if (typeof proxyReq.getHeader === 'function' && proxyReq.getHeader('referer')) {
                let fixedReferer = replaceHostsBack(proxyReq.getHeader('referer'));
                proxyReq.setHeader('referer', fixedReferer);
                _options.logger && _options.logger('Alexa-Cookie: Modify headers: Changed Referer: ' + fixedReferer);
                modified = true;
            }
            if (typeof proxyReq.getHeader === 'function' && proxyReq.getHeader('origin') !== 'https://' + proxyReq.getHeader('host')) {
                proxyReq.setHeader('origin', `https://www.${_options.baseAmazonPage}`);
                _options.logger && _options.logger('Alexa-Cookie: Modify headers: Delete Origin');
                modified = true;
            }

            let postBody = '';
            req.on('data', chunk => {
                postBody += chunk.toString(); // convert Buffer to string
            });
        }
        _options.proxyLogLevel === 'debug' && _options.logger && _options.logger('Alexa-Cookie: Proxy-Request: (modified:' + modified + ')' + customStringify(proxyReq, null, 2));
    }

    function onProxyRes(proxyRes, req, res) {
        const url = req.originalUrl || req.url;
        if (url.endsWith('.ico') || url.endsWith('.js') || url.endsWith('.ttf') || url.endsWith('.svg') || url.endsWith('.png') || url.endsWith('.appcache')) return;
        if (url.startsWith('/ap/uedata')) return;
        //_options.logger && _options.logger('Proxy-Response: ' + customStringify(proxyRes, null, 2));
        let reqestHost = null;
        if (proxyRes.socket && proxyRes.socket._host) reqestHost = proxyRes.socket._host;
        _options.logger && _options.logger('Alexa-Cookie: Proxy Response from Host: ' + reqestHost);
        _options.proxyLogLevel === 'debug' && _options.logger && _options.logger('Alexa-Cookie: Proxy-Response Headers: ' + customStringify(proxyRes.headers, null, 2));
        _options.proxyLogLevel === 'debug' && _options.logger && _options.logger('Alexa-Cookie: Proxy-Response Outgoing: ' + customStringify(proxyRes.socket.parser.outgoing, null, 2));
        //_options.logger && _options.logger('Proxy-Response RES!!: ' + customStringify(res, null, 2));

        if (proxyRes && proxyRes.headers && proxyRes.headers['set-cookie']) {
            // make sure cookies are also sent to http by remove secure flags
            for (let i = 0; i < proxyRes.headers['set-cookie'].length; i++) {
                proxyRes.headers['set-cookie'][i] = proxyRes.headers['set-cookie'][i].replace('Secure', '');
            }
            proxyCookies = addCookies(proxyCookies, proxyRes.headers);
        }
        _options.logger && _options.logger('Alexa-Cookie: Cookies handled: ' + JSON.stringify(proxyCookies));

        if (
            (proxyRes.socket && proxyRes.socket._host === `www.${_options.baseAmazonPage}` && proxyRes.socket.parser.outgoing && proxyRes.socket.parser.outgoing.method === 'GET' && proxyRes.socket.parser.outgoing.path.startsWith('/ap/maplanding')) ||
            (proxyRes.socket && proxyRes.socket.parser.outgoing && proxyRes.socket.parser.outgoing.getHeader('location') && proxyRes.socket.parser.outgoing.getHeader('location').includes('/ap/maplanding?')) ||
            (proxyRes.headers.location && (proxyRes.headers.location.includes('/ap/maplanding?') || proxyRes.headers.location.includes('/spa/index.html')))
        ) {
            _options.logger && _options.logger('Alexa-Cookie: Proxy detected SUCCESS!!');

            const paramStart = proxyRes.headers.location.indexOf('?');
            const queryParams = querystring.parse(proxyRes.headers.location.substr(paramStart + 1));

            proxyRes.statusCode = 302;
            proxyRes.headers.location = `http://${_options.proxyOwnIp}:${_options.proxyPort}/cookie-success`;
            delete proxyRes.headers.referer;

            _options.logger && _options.logger('Alexa-Cookie: Proxy catched cookie: ' + proxyCookies);
            _options.logger && _options.logger('Alexa-Cookie: Proxy catched parameters: ' + JSON.stringify(queryParams));

            callbackCookie && callbackCookie(null, {
                "loginCookie": proxyCookies,
                "accessToken": queryParams['openid.oa2.access_token'],
                "frc": initialCookies.frc,
                "map-md": initialCookies['map-md'],
                "deviceId": deviceId
            });
            return;
        }

        // If we detect a redirect, rewrite the location header
        if (proxyRes.headers.location) {
            _options.logger && _options.logger('Redirect: Original Location ----> ' + proxyRes.headers.location);
            proxyRes.headers.location = replaceHosts(proxyRes.headers.location);
            if (reqestHost && proxyRes.headers.location.startsWith('/')) {
                proxyRes.headers.location = `http://${_options.proxyOwnIp}:${_options.proxyPort}/` + reqestHost + proxyRes.headers.location;
            }
            _options.logger && _options.logger('Redirect: Final Location ----> ' + proxyRes.headers.location);
            return;
        }

        modifyResponse(res, (proxyRes && proxyRes.headers ? proxyRes.headers['content-encoding'] || '' : ''), function(body) {
            if (body) {
                const bodyOrig = body;
                body = replaceHosts(body);
                if (body !== bodyOrig) {
                    _options.logger && _options.logger('Alexa-Cookie: MODIFIED Response Body to rewrite URLs');
                    _options.logger && _options.logger('');
                    _options.logger && _options.logger('');
                    _options.logger && _options.logger('');
                }
            }
            return body;
        });
    }

    // create the proxy (without context)
    const myProxy = proxy('!/cookie-success', optionsAlexa);

    // mount `exampleProxy` in web server
    const app = express();

    app.use(myProxy);
    app.get('/cookie-success', function(req, res) {
        res.send('<b>Amazon Alexa Cookie successfully retrieved. You can close the browser.</b>');
    });
    let server = app.listen(_options.proxyPort, _options.proxyListenBind, function() {
        _options.logger && _options.logger('Alexa-Cookie: Proxy-Server listening on port ' + server.address().port);
        callbackListening && callbackListening(server);
        callbackListening = null;
    }).on('error', err => {
        _options.logger && _options.logger('Alexa-Cookie: Proxy-Server Error: ' + err);
        callbackListening && callbackListening(null);
        callbackListening = null;
    });

}

module.exports.initAmazonProxy = initAmazonProxy;
`

**Comment by Apollon77** [comment]
ääähm sigi ... falsches file :-)

**Comment by sigi2345** [comment]
> ääähm sigi ... falsches file :-)

Hm,  die habe ich nicht:

formerDataStore.json

**Comment by Apollon77** [comment]
Hast du nur wenn du mit der 3.2.7 neu verknüpft hast. Wenn nicht alles ok und freu dich ;-)

**Comment by Dragondrummer** [comment]
@Apollon77 Die device ID aus dem der formerDataStore.json ist wie folgt:
"deviceId":"75134c4643374c3541464b"

**Comment by JuergenHorvath** [comment]
ich würde euch auch gern diese ID posten, wenn mir wer erklärt "WIE". Leider bin ich mit Linux nicht so auf du und du.
:-)

**Comment by Apollon77** [comment]
@JuergenHorvath sh auf den iobroker rechner, dann 
```
cat /opt/iobroker/node_modules/alexa-cookie2/lib/formerDataStore.json
cat /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/lib/formerDataStore.json
```
eins von den beiden sollte es geben. inhalt hier posten

**Comment by JuergenHorvath** [comment]
Perfekt. Mach ich dann am Abend. Bin noch auf Arbeit. 👍

**Comment by Jibbonator** [comment]
Version 3.2.7: "deviceId":"14634c4643374c3541464b",

**Comment by Apollon77** [comment]
ok 3.2.8 hat nochmal was anders ... vllt noch besser

**Comment by JuergenHorvath** [comment]
so jetzt von mir bei 3.2.7. --> "deviceId":"08534c4643374c3541464b"

**Comment by gitzorro** [comment]
THX - mit 3.2.8 klappt's nun :-)
Bei mir etwas länger...
"deviceId":"705077665524472860136787835774750471431418646363004231363347358334c4643374c3541464b"
