### ISSUE TITLE
Alexa Befehl per Objekt ausführen

### ISSUE THREAD

**Issue by xXHamtaroXx** [Apollon77/ioBroker.alexa2#504]
Hallo,
es wäre cool wenn man ein Objekt hat wo man, das was man zu alexa sagen würde, eintragen kann... Z.B "Welche Wecker sind gestellt".

Vielen Dank an die Entwicklung.

Mit freundlichem Gruß

Hamtaro

**Comment by Apollon77** [comment]
Das geht nur bedingt. Bespoken im Adapter kann das und gibt die ANtwort als Text zurück. Alles andere geht aktuell nicht. Die Alexa APp kann es ja auchnicht

**Comment by xXHamtaroXx** [comment]
Ich habe keinen Datenpukt Bespoken.

Ingo Fischer <notifications@github.com> schrieb am So., 12. Juli 2020,
21:58:

**Comment by Apollon77** [comment]
Dann bitte in der Konfiguration lesen und aktivieren. Die Readme hilft auch

**Comment by MattL0** [comment]
I am getting this with version : 3.2.5


  |   |   |  
-- | -- | -- | --
alexa2.0 | 2020-07-13 19:56:48.869 | error | (80010) Error: No tokens in Register response

**Comment by MattL0** [comment]
now I get this: 


  |   |   |  
-- | -- | -- | --
alexa2.0 | 2020-07-13 20:17:00.407 | error | (86307) Error: no csrf found
alexa2.0 | 2020-07-13 20:17:00.406 | error | (86307) Error: no csrf found. Check configuration of cookie

**Comment by MattL0** [comment]
ok got it by selecting ''copy request header '' instead of curl

**Comment by MattL0** [comment]
but the card is not updating, i have to mannually press the trigger button to poll it.

**Comment by Apollon77** [comment]
If you have isues please open a new issue here and do not comment on a closed ticket.

**Comment by MattL0** [comment]
Sorry
