### ISSUE TITLE
Echo Studio unknown device

### ISSUE THREAD

**Issue by vaaarg** [Apollon77/ioBroker.alexa2#507]
Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted

`Device-type:A3RBAYBE7VM004 (FAR_FIELD_WAKE_WORD,VOLUME_SETTING,LOCAL_VOICE,TIMERS_AND_ALARMS,MUSIC_SKILL,AUDIO_CONTROLS,REMINDERS,REQUIRES_OOBE_FOR_SETUP,AUDIO_PLAYER,GOLDFISH,DIALOG_INTERFACE_VERSION,SUPPORTS_SOFTWARE_VERSION,MICROPHONE,TUPLE,PAIR_REMOTE,EARCONS,ASCENDING_ALARM_VOLUME,DEREGISTER_DEVICE,DS_VOLUME_SETTING,CUSTOM_ALARM_TONE,DREAM_TRAINING,LEMUR_ALPHA,POPTART,PERSISTENT_CONNECTION,EQUALIZER_CONTROLLER_MIDRANGE,PAIR_BT_SOURCE,FLASH_BRIEFING,GUARD_EARCON,SUPPORTS_LOCALE_SWITCH,GADGETS,UPDATE_WIFI,DEREGISTER_FACTORY_RESET,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,PAIR_BT_SINK,SUPPORTS_LOCALE,TAHOE_BYOD,SUPPORT_CALENDAR_ALERT,ACTIVE_AFTER_FRO,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,EQUALIZER_CONTROLLER_BASS,CHANGE_NAME,SOUND_SETTINGS,EQUALIZER_CONTROLLER_TREBLE,SLEEP,TUPLE_CATEGORY_A,VOICE_TRAINING,SET_LOCALE)`

commands work

**Comment by Apollon77** [comment]
PR existing #500

**Comment by Apollon77** [comment]
fixed in 3.2.7
