### ISSUE TITLE
Login funktioniert nicht mehr

### ISSUE THREAD

**Issue by OberstVonGatow** [Apollon77/ioBroker.alexa2#509]
Hallo, leider habe ich seit kurzem das Problem, dass ich mich nichtmehr anmelden kann.
Nach dem ersten Login Bildschirm (mit IP im eigenen Netzwerk) werde ich weitergeleitet auf https://www.amazon.com/ap/signin und bekomme dann einen Fehler das meine E-Mail Adresse nicht korrekt ist. Wenn ich manuell mich versuche einzuloggen kommen ich von https://www.amazon.de/ap/signin also der deutschen Domain. Hat sich da was bei Amazon oder bei mir geändert? (die Troubleshooting Anleitung zum Cookie habe ich leider ohne erfolg druchgeführt).

**Comment by OberstVonGatow** [comment]
Mhh sieht aber leider so aus als ob ich im Moment beim normalen Login immer ein Captcha und manchmal sogar per Email bestätigen muss. Eventuell liegt es also auch daran...

**Comment by Apollon77** [comment]
Bitte neueste verison 3.2.8 nutzen !

**Comment by OberstVonGatow** [comment]
Danke für die schnelle Antwort. Funktioniert bei mir leider auch mit 3.2.8 nicht. Evtl. auch wegen zu vielen Versuchen. Beim normalen Login kommt jetzt immer ein Captcha. Beim Login über den Adapter werde ich nur auf http://192.168.178.2:36515/www.amazon.com/ap/signin weitergeleitet und hier steht dann das die E-Mail nicht passt.
![grafik](https://user-images.githubusercontent.com/6384996/87779483-20f17500-c82d-11ea-9158-0eabfc995774.png)

**Comment by OberstVonGatow** [comment]
Wenn ich den Cookie manuell eintrage bekomme ich einen Fehler im Log: 
`alexa2.0 | 2020-07-17 13:11:57.189 | error | (4794) Error: Error while checking Authentication: Error: no JSON`

Den Cookie habe ich so wie in der Anleitung kopiert "Cookie: x-amzn-dat-gui-client-v=....... csrf=...."

**Comment by Apollon77** [comment]
Bitte mal ausgabe von

cat /opt/iobroker/node_modules/alexa-cookie2/lib/formerDataStore.json
cat /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/lib/formerDataStore.json

posten

**Comment by Apollon77** [comment]
bzw falls die Instanz vorher schon mal verbunden war (vor allem mit einer früheren version) dann bitte das existierende File an de Stelle löschen und ggf instanz löschen und neu lnlegen

**Comment by OberstVonGatow** [comment]
Okay jetzt klappt es bei mir wieder.
Das hab ich dafür gemacht
-  /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/lib/formerDataStore.json gelöscht
- /opt/iobroker/node_modules/alexa-cookie2/lib/formerDataStore.json war bei mir nicht vorhanden
- Instanz gelöscht
- nochmal explizit die Version 3.2.8 installiert (war allerdings schon installiert)
- Instanz gestartet und Login im Adapter

Keine Ahnung was das Problem war. Instanz hatte ich auch nach dem update auf 3.2.8. gelöscht und neu gestartet. Vielleicht hat das löschen von formerDataStore.json das Problem gelöst.

Vielen Dank für deine schnelle Hilfe!

**Comment by Apollon77** [comment]
Aber den inhalt der Datei haste nicht mehr? ...

**Comment by OberstVonGatow** [comment]
Nein sorry hab es mit rm gelöscht...
Wäre aber sowieso fraglich ob sich der Aufwand gelohnt hätte das zu analysieren. Hatte ja zwischenzeitlich auch mit manuellen Cookie probiert etc.

**Comment by HouseFox** [comment]
Hallo Apollon77, Hallo in die Runde,

dies kann ich ebenfalls bestätigen.
Keine Verbindung, auch nach Neuinstallation.
Zunächst funktionierte es wieder, dann nicht mehr.

Amazon Alexa möchte ebenso das man ein neues Passwort für Amazon vergibt.

https://github.com/Apollon77/ioBroker.alexa2/issues/514
https://github.com/Apollon77/ioBroker.alexa2/issues/513
https://github.com/Apollon77/ioBroker.alexa2/issues/512 closed?
https://github.com/Apollon77/ioBroker.alexa2/issues/509 closed?

![Anmerkung 2020-07-17 215253](https://user-images.githubusercontent.com/43676945/87849177-ccaacb80-c8e6-11ea-9dd1-fc2a10a22b8f.png)

![Anmerkung 2020-07-17 220336](https://user-images.githubusercontent.com/43676945/87849182-d16f7f80-c8e6-11ea-9a50-0ed34ffc6048.png)

![Anmerkung 2020-07-17 220416](https://user-images.githubusercontent.com/43676945/87849189-d46a7000-c8e6-11ea-9036-3bc4385a1dc6.png)

![Anmerkung 2020-07-18 110646](https://user-images.githubusercontent.com/43676945/87849190-d7656080-c8e6-11ea-8d55-f49f84a43f46.png)

**Comment by Domi920** [comment]
Habe nach wie vor auch das gleiche Problem:
Anmeldung einer neuen Instanz nicht möglich (Fehlermeldung: Geben Sie eine gültige E-Mail Adresse oder Mobilfunknummer ein.)

Bekomme folgende Fehlermeldungen in den LOG:
2020-07-18 17:43:33.814 - error: alexa2.3 (1059) Error:
2020-07-18 17:43:33.815 - error: alexa2.3 (1059) Error: You can try to get the cookie manually by opening http://192.168.1.4:43219/ with your browser.

2020-07-18 17:49:23.982 - error: alexa2.3 (1101) Error:
2020-07-18 17:49:23.984 - error: alexa2.3 (1101) Error: You can try to get the cookie manually by opening http://192.168.1.4:39851/ with your browser.

2020-07-18 17:53:45.327 - error: alexa2.3 (1124) Error:
2020-07-18 17:53:45.328 - error: alexa2.3 (1124) Error: You can try to get the cookie manually by opening http://192.168.1.4:46077/ with your browser.

Immer eine andere Fehlermeldung.
Wenn ich die Adresse manuell im Browser öffne, erscheint die gleiche Fehlermeldung.

Was kann ich tun?

**Comment by OberstVonGatow** [comment]
Also neues Passwort sollte ich auch vergeben. Das hab ich dann auch gemacht. Ansonsten auf die Version 3.2.8 habt ihr über Adapter über GitHub Updaten habt ihr gemacht? Falls das nichts hilft Instanzen löschen und stoppen und auch mal die beiden Files die Apollon geschrieben hat verschieben. Und Instanzen neu starten.

**Comment by OberstVonGatow** [comment]
Ach ja und ich hab mich noch davor einmal manuell bei https://alexa.amazon.de angemeldet aber keine Ahnung ob das notwendig ist.

**Comment by HouseFox** [comment]
Hallo, was ich getan habe.

1. /opt/iobroker/node_modules/alexa-cookie2/lib/formerDataStore.json bei mir vorhanden und gelöscht


pi@raspberrypi-ioBroker:~ $ cd /opt/iobroker/node_modules/alexa-cookie2/lib
pi@raspberrypi-ioBroker:/opt/iobroker/node_modules/alexa-cookie2/lib $ ls
formerDataStore.json  proxy.js
pi@raspberrypi-ioBroker:/opt/iobroker/node_modules/alexa-cookie2/lib $ sudo rm formerDataStore.json
pi@raspberrypi-ioBroker:/opt/iobroker/node_modules/alexa-cookie2/lib $ ls
proxy.js
pi@raspberrypi-ioBroker:~ $

2. /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/lib/formerDataStore.json bei mir NICHT vorhanden

pi@raspberrypi-ioBroker:~ $ cd /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/lib
-bash: cd: /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/lib: Datei oder Verzeichnis nicht gefunden
pi@raspberrypi-ioBroker:~ $


3. Einmal manuell bei https://alexa.amazon.de angemeldet


4. Anschließend die Instanz neu gestartet
-"Klicken Sie hier, um sich einmal in Ihrem Amazon-Konto anzumelden und die Adapterverbindung zu Ihren Alexa-Geräten zu aktivieren."
-Angemeldet "Unusual sign-in attempt detected" Genehmigt
-Amazon Alexa Cookie successfully retrieved. You can close the browser.


Log Auszug;
alexa2.0	2020-07-19 00:22:49.581	info	(2450) Subscribing to states...
alexa2.0	2020-07-19 00:22:24.987	info	(2450) Alexa-Push-Connection established. Disable Polling
alexa2.0	2020-07-19 00:22:20.012	info	(2450) Proxy IP not set, use first network interface (192.168.178.11) instead
alexa2.0	2020-07-19 00:22:19.857	info	(2450) starting. Version 3.2.8 in /opt/iobroker/node_modules/iobroker.alexa2, node: v12.18.2, js-controller: 3.1.6
alexa2.0	2020-07-19 00:22:13.188	info	(2079) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
alexa2.0	2020-07-19 00:22:13.185	info	(2079) terminating
alexa2.0	2020-07-19 00:22:13.184	info	(2079) Alexa-Push-Connection Error: Error: WebSocket was closed before the connection was established
alexa2.0	2020-07-19 00:22:13.178	info	(2079) Got terminate signal TERMINATE_YOURSELF
alexa2.0	2020-07-19 00:22:13.083	info	(2079) Update cookie in adapter configuration ... restarting ...
alexa2.0	2020-07-19 00:20:37.644	error	(2079) Error: You can try to get the cookie manually by opening http://192.168.178.11:37207/ with your browser.
alexa2.0	2020-07-19 00:20:37.643	error	(2079) Error:
alexa2.0	2020-07-19 00:20:36.213	info	(2079) Proxy IP not set, use first network interface (192.168.178.11) instead
alexa2.0	2020-07-19 00:20:36.025	info	(2079) starting. Version 3.2.8 in /opt/iobroker/node_modules/iobroker.alexa2, node: v12.18.2, js-controller: 3.1.6


Alexa-Cookies sind aktuell und zuletzt aktualisiert am 19.07.2020

So wie es aussieht funktioniert der Adapter.
Werde es beobachten, ggf. hier melden.

Danke und Gruß

**Comment by Domi920** [comment]
Hallo,
Bei mir reichte sogar dein Schritt 1 schon aus.

Im LXTerminal (Kommandozeile des Raspberry PI Systems) habe ich dazu folgendes eingegeben:

sudo rm -r /opt/iobroker/node_modules/alexa-cookie2/lib/formerDataStore.json

Nun war die Datei erfolgreich gelöscht.
Nun konnte ich die Instanz neu starten und mich erfolgreich anmelden.

@Apollon77 evtl gibt eins bald eine Benutzerfreundlichere Lösung.
Vielen Dank an alle die Mithelfen!

**Comment by Apollon77** [comment]
Die Lösung mit dem Löschen der Datei sollte schon lange nicht mehr nötig sein. Die Nutzerfreundliche lösung ist: Instanz löschen und neu anlegen

**Comment by Apollon77** [comment]
Bitte ggf 3.3.0 versuchen falls noch nicht behoben ... da sollte auch das oben genannte nicht nötig sein
