### ISSUE TITLE
States Music-Provider.TuneIn vs. Player.TuneIn-Direct

### ISSUE THREAD

**Issue by Mic-M** [Apollon77/ioBroker.alexa2#51]
Use case is to provide the TuneIn station ID to a certain Alexa device (or multi room), so that the device/multi room plays this station.

It works well if state "alexa2.0.Echo-Devices.xxx.Player.TuneIn-Direct" is set, but it does not work if using state "alexa2.0.Echo-Devices.xxx.Music-Provider.TuneIn". 

I think the naming of these aforementioned states and/or having two different states for TuneIn is confusing and this could be simplified - or at least further explanation could be provided in the documentation.

Thanks!

**Comment by Apollon77** [comment]
0.4.0
