### ISSUE TITLE
Command Speak is working fine for every Alexa device, but not for Sonos Move.

### ISSUE THREAD

**Issue by TonyDom** [Apollon77/ioBroker.alexa2#511]
**Check if the Bug maybe is with Amazon**  
The adapter is using the same API as the Alexa mobile App. This means:
* If you can not do this what you want with the App then the Adapter also can not do it!
* Also if the App can do it please test if the same effect then the bug also happens with the App (e.g. a speak command do not work on a certain device ... can you do a speak via Alexa App? If not - Amazon problem!)

**Describe the bug**  
A clear and concise description of what the bug is. Especially describe what you verified using the Alexa App (see above).

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by TonyDom** [comment]
Command Speak is working fine for every Alexa device, but not for Sonos Move, but Sonos Move was speaking already in the past.

**Comment by Apollon77** [comment]
Is a Routine working? Can you select Sonos there? Last Info is that Amazon and Sonos broke it some time ago ... sorry
