### ISSUE TITLE
alexa2.0 Instanz verbindet sich nicht mehr mit Amazon Alexa

### ISSUE THREAD

**Issue by HouseFox** [Apollon77/ioBroker.alexa2#512]
Hallo Apollon77, 
ich habe seit heute 17.07.2020 folgendes Problem;
Die alexa2.0 Instanz verbindet sich nicht mehr mit Amazon Alexa.
Ich bin sogar von Amazon aufgefordert worden das Amazon Passwort zu ändern.
Habe es zigfach ausprobiert. Email ist richtig, ebenso Passwort.
Dennoch bekomme ich folgendes im Anmeldefenster zurück;

Ein Problem ist aufgetreten:
Geben Sie eine gültige E-Mail-Adresse oder Mobiltelefonnummer ein.

Gleiches passiert wenn ich den link aus dem log benutze.

Ist dies bereits als Fehler bekannt?
Ich benutze die Version 3.2.8, muss jedoch bereits mit der 3.2.7 nicht mehr funktioniert haben.
Gruß

![Anmerkung 2020-07-17 215253](https://user-images.githubusercontent.com/43676945/87826000-6ab37d00-c878-11ea-85eb-655771308534.png)

![Anmerkung 2020-07-17 220336](https://user-images.githubusercontent.com/43676945/87826556-676cc100-c879-11ea-9c9a-f5f559b981fb.png)

![Anmerkung 2020-07-17 220416](https://user-images.githubusercontent.com/43676945/87826591-79e6fa80-c879-11ea-91df-21a655588bda.png)

**Comment by Apollon77** [comment]
Please use v3.2.8!

**Comment by HouseFox** [comment]
Hello Apollon77, i´m using v3.2.8.
_Ich benutze die Version 3.2.8, muss jedoch bereits mit der 3.2.7 nicht mehr funktioniert haben._

**Comment by Apollon77** [comment]
3.2.5/6/7 waren alles versuche es zu fixen ... von daher :-) Es tat nicht mehr Seitd Datum X wo amazon dfinge geändert hat und alles vor 3.2.8 ist damit betroffen es sei denn eine Verbindung besteht bereits

**Comment by Apollon77** [comment]
Bitte ggf 3.3.0 versuchen falls noch nicht behoben
