### ISSUE TITLE
Probleme nach Update auf  3.2.8

### ISSUE THREAD

**Issue by chrischom** [Apollon77/ioBroker.alexa2#513]
Hallo,
bei mir erscheinen Fehlermeldungen seit dem Update auf 3.2.8.

> host.raspberrypi	2020-07-17 13:46:15.780	error	instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi	2020-07-17 13:46:15.779	error	Caught by controller[0]: }
host.raspberrypi	2020-07-17 13:46:15.779	error	Caught by controller[0]: ]
host.raspberrypi	2020-07-17 13:46:15.779	error	Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.alexa2/main.js'
host.raspberrypi	2020-07-17 13:46:15.778	error	Caught by controller[0]: '/opt/iobroker/node_modules/virtual-device-sdk/lib/src/Index.js',
host.raspberrypi	2020-07-17 13:46:15.778	error	Caught by controller[0]: '/opt/iobroker/node_modules/virtual-device-sdk/lib/src/VirtualDevice.js',
host.raspberrypi	2020-07-17 13:46:15.778	error	Caught by controller[0]: requireStack: [
host.raspberrypi	2020-07-17 13:46:15.778	error	Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.raspberrypi	2020-07-17 13:46:15.778	error	Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1026:19) {
host.raspberrypi	2020-07-17 13:46:15.777	error	Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:879:14)
host.raspberrypi	2020-07-17 13:46:15.777	error	Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:986:32)
host.raspberrypi	2020-07-17 13:46:15.777	error	Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
host.raspberrypi	2020-07-17 13:46:15.777	error	Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
host.raspberrypi	2020-07-17 13:46:15.776	error	Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/virtual-device-sdk/lib/src/VirtualDevice.js:41:23)
host.raspberrypi	2020-07-17 13:46:15.776	error	Caught by controller[0]: at require (internal/modules/cjs/helpers.js:72:18)
host.raspberrypi	2020-07-17 13:46:15.776	error	Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1026:19)
host.raspberrypi	2020-07-17 13:46:15.776	error	Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:842:27)
host.raspberrypi	2020-07-17 13:46:15.775	error	Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
host.raspberrypi	2020-07-17 13:46:15.775	error	Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.alexa2/main.js
host.raspberrypi	2020-07-17 13:46:15.775	error	Caught by controller[0]: - /opt/iobroker/node_modules/virtual-device-sdk/lib/src/Index.js
host.raspberrypi	2020-07-17 13:46:15.775	error	Caught by controller[0]: - /opt/iobroker/node_modules/virtual-device-sdk/lib/src/VirtualDevice.js
host.raspberrypi	2020-07-17 13:46:15.774	error	Caught by controller[0]: Require stack:
host.raspberrypi	2020-07-17 13:46:15.774	error	Caught by controller[0]: Error: Cannot find module 'https-proxy-agent'
host.raspberrypi	2020-07-17 13:46:15.774	error	Caught by controller[0]: ^
host.raspberrypi	2020-07-17 13:46:15.773	error	Caught by controller[0]: throw err;
host.raspberrypi	2020-07-17 13:46:15.773	error	Caught by controller[0]: internal/modules/cjs/loader.js:969

Der Alexa Adapter lässt sich auch nicht mehr starten.
Selbst bei einem Downgrade auf die ältere und zuvor funktionierende Version funktioniert nicht mehr und es kommen die gleichen Fehlermeldungen.

Interessanter Weise hat das Update auf einem zweiten Raspi mit nahezu den gleichen Adaptern problemlos funktioniert. Beide Raspis sind aktuell.

Vielleicht kann jemand helfen?
Vielen Dank

`

/usr/bin/nodejs
--
  | v12.18.2
  | /usr/bin/node
  | v12.18.2
  | /usr/bin/npm
  | 6.14.5
  | nodejs:
  | Installed: 12.18.2-1nodesource1
  | Candidate: 12.18.2-1nodesource1
  | Version table:
  | *** 12.18.2-1nodesource1 500
  | 500 https://deb.nodesource.com/node_12.x buster/main arm64 Packages
  | 100 /var/lib/dpkg/status
  | 10.21.0~dfsg-1~deb10u1 500
  | 500 http://deb.debian.org/debian-security buster/updates/main arm64 Packages
  | 10.19.0~dfsg1-1 500
  | 500 http://deb.debian.org/debian buster/main arm64 Packages

`

**Comment by Apollon77** [comment]
Bitte nochmals installieren, scheinbar ist da bei dir lokal irgendwas beim Install kaputt gegangen (was an sich nicht sein sollte).

ins ioBroker Verzeichnis wechseln und

npm install iobroker.alexa2@3.2.8 --production

ausführen. Geht es dann?

**Comment by Apollon77** [comment]
Bitte ggf 3.3.0 versuchen falls noch nicht behoben

**Comment by MischaI** [comment]
3.3.0 hilft nicht. 
![image](https://user-images.githubusercontent.com/34452995/88425702-1a946780-cdf0-11ea-864e-d97d230a0b54.png)
manuelle installation 3.2.8 zeigt keine Instanz. Im Log sieht man, dass sich was tut, aber keine sichtbare Instanz, auch keine Objekte zu sehen

**Comment by Apollon77** [comment]
Bitte install log der installation zeigen. Hattest du vor der manuellen Installation die instanz gelöscht und so? Dann musst du eine neue Instanz anlegen und ggf vorher „iobroker upload alexa2“ ausführen. Sorry aber die Infos die du schreibst sind echt dürftig :-(

**Comment by MischaI** [comment]
OK. Folgendes. Manuell aus terminal installiert 3.2.8, gehe in die Instanzen, sehe die alexa Instanz nicht.
Gehe in Adapter, sehe dass installierte version 3.2.8 und update auf 3.3 steht.
Mache ein update, sehe die Instanz nicht. 
Instanz gelöscht, adapter 3.3 installiert, wieder die gleiche Fehlermeldung. Wieder Instanz gelöscht. 
Wieder manuelle Installation, Update auf 3.3 und so gelassen. Nach einiger Zeit reingeschaut, Instanz ist da, und alles funktioniert. Es heißt ich müsste einfach Zeit lassen, damit die Instanz wieder sichtbar ist. 
Also alles funktioniert, man muss halt gedultig sein
