### ISSUE TITLE
Nach Upgrade auf 3.2.8 startet die Instance nicht mehr

### ISSUE THREAD

**Issue by Bibo13** [Apollon77/ioBroker.alexa2#514]
Nachdem ich Alexa2 auf 3.2.8 gehoben habe startet die Instance nicht mehr.

Ich habe mal die Snapshots angehängt.

![Alexa2_1](https://user-images.githubusercontent.com/45422390/87847794-feb63080-c8da-11ea-8b56-2d620374241d.JPG)

![Alexa2_Start](https://user-images.githubusercontent.com/45422390/87847799-0bd31f80-c8db-11ea-8143-f4eedb56b149.JPG)

Im Iobroker Forum haben auch andere von dem Problem berichtet.

Gruß

**Comment by chrischom** [comment]
funktioniert leider nicht nach der Anleitung

**Comment by Apollon77** [comment]
Bitte nochmals installieren, scheinbar ist da bei dir lokal irgendwas beim Install kaputt gegangen (was an sich nicht sein sollte).

ins ioBroker Verzeichnis wechseln und

npm install iobroker.alexa2@3.2.8 --production 

ausführen. Geht es dann?

**Comment by chrischom** [comment]
Das war´s - jetzt funktioniert es wieder. Vielen Dank!

**Comment by Bibo13** [comment]
Läuft wieder DANKE. Auf was muss man beim nächsten mal achten. Oder was ist schief gegangen?

**Comment by Apollon77** [comment]
Da ist irgendwas bei Dir lokel schieff gegangen. Da bräuchte man jetzt das Install log vom initialen install... Sollte an sich nicht passieren

**Comment by Apollon77** [comment]
Bitte ggf 3.3.0 versuchen falls noch nicht behoben

**Comment by IchBinSmart** [comment]
Hallo,

ich habe exakt das gleiche Problem. Habe NodeJs auf 12.18.3 upgedated. Danach kommt immer die lästige Fehlermeldung von oben. Habe dann versucht den Adapater zu deinstallieren und anschließend wieder zu installieren. Leider ohne Erfolg. Der Befehl npm install iobroker.alexa2@3.3.1 --production führt zu folgendem (Berechtigungs-) Fehler, bei dem ich nicht weiß wie ich ihn lösen soll:
``
pi@raspberrypi:/home/iobroker $ npm install iobroker.alexa2@3.3.1 --production
npm WARN checkPermissions Missing write access to /home/iobroker/node_modules/iobroker.alexa2
npm WARN checkPermissions Missing write access to /home/iobroker/node_modules
npm WARN enoent ENOENT: no such file or directory, open '/home/iobroker/package.json'
npm WARN iobroker No description
npm WARN iobroker No repository field.
npm WARN iobroker No README data
npm WARN iobroker No license field.

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /home/iobroker/node_modules/iobroker.alexa2
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/home/iobroker/node_modules/iobroker.alexa2'
npm ERR!  [Error: EACCES: permission denied, access '/home/iobroker/node_modules/iobroker.alexa2'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/iobroker/node_modules/iobroker.alexa2'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-08-10T16_36_31_262Z-debug.log

''

Wäre über jeden Tip dankbar :-)!

**Comment by Apollon77** [comment]
Wie machst Denn bitte hier updates? Und dann noch im fdalschen Verzeichnis?
Noitte iobroker admin nutzen oder die iobroekr Befehle wie "iobroekr upgrade alexa2" nutzen!!

**Comment by IchBinSmart** [comment]
> Wie machst Denn bitte hier updates? Und dann noch im fdalschen Verzeichnis?
> Noitte iobroker admin nutzen oder die iobroekr Befehle wie "iobroekr upgrade alexa2" nutzen!!

Das habe ich natürlich als erstes Versucht. Da der Adapter bereits auf der neusten Version war, kann ich ihn darüber nicht updaten. Ein Re-Install hat dort auch nichts gebracht. 

Was ich gemacht hatte war: 
```
sudo curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
sudo apt-get install -y nodejs
```

und: 

```
iobroker stop
iobroker upgrade self
iobroker start
```

Seit dem kommt diese Meldung im Log:

**Comment by Apollon77** [comment]
iobroker fix

Irgendwas ist an den rechten verbogen

**Comment by Apollon77** [comment]
Und der letzt Post updated nur den Controller. Wenn es wirklich so ist dann ist bei dir was ganz komisch. 

Versuch mal

cd /opt/iobroker
npm i iobroker.alexa2 --production

Dann?
