### ISSUE TITLE
Löschen von Items aus shopping Liste funktioniert nicht!

### ISSUE THREAD

**Issue by lwalpurgis** [Apollon77/ioBroker.alexa2#515]
In der aktuellen Alexa2.0 Adapter Version 3.2.8 kann man Items aus der Shoppingliste löschen, jedoch werden diese erst nach einem manuellen Neustart des Alexa2.0 Adapters aus der Liste gelöscht. Ich habe die Push Verbindung beim Adapter aktiviert. Andere Daten aktualisieren sich, aber nicht die gelöschten aus der Shoppingliste nicht.

**Comment by Apollon77** [comment]
Bitt Edebug Log aktivieren und Log posten von einem versuch das zu löschen

**Comment by lwalpurgis** [comment]
Hallo @Apollon77 ich habe das ganze mal noch etwas analysiert.
Im Log wird alles wie erwartet geloggt und gelöscht und hinzugefügt.
![Log](https://user-images.githubusercontent.com/10418543/87905808-af4e3c80-ca61-11ea-8b3c-72a83151d96e.JPG)
Bei den Objekten kommen beim hinzufügen auch die neuen hinzu, aber die gelöschten werden nur ausgegraut, aber nicht die Ordner gelöscht. Die Ordner bleiben mit den alten Daten bestehen. Dementsprechend passt die Numerierung mit den List Items auch nicht mehr und es gibt 2 mal das Item 1.
![Objekte](https://user-images.githubusercontent.com/10418543/87905940-f3d9d800-ca61-11ea-9abe-131c7d1ee031.JPG)

**Comment by Apollon77** [comment]
Hast Du den Objekte Tab mal neu geladen? Nicht das die weg sind aber Admin es nicht korrekt anzeigt? Bitte mal Loglevel auf debug stellen und neu log zeigen beim löschen

**Comment by Apollon77** [comment]
PS: Debug Log ... Instanzen - Expertenmodus - Spalte "Logstufe"

**Comment by lwalpurgis** [comment]
Hallo,
Nach dem aktualisieren der Objekte sind die alten Ordner immer noch da!
Im Javascript findet er auch die Ordner --> Sie sind definitiv noch da.

Danke für den Hinweis zur Debug Ausgabe.
Hier das Bild dazu:
![Unbenannt2](https://user-images.githubusercontent.com/10418543/87934811-200c4d80-ca90-11ea-8193-770c9a27dca9.JPG)

Der Ordner war danach immer noch in den Objekten zu sehen und auch in Javascript gefunden...

**Comment by liv-in-sky** [comment]
hi, - mttlerweile in beiden listen - nutzt man den delete button wir zwar in der alexa app der eintrag gelöscht, aber die datenpunkte in iobroker bleiben alle erhalten

ein neustart des adapters löscht die datenpukte nach einiger zeit

falls log nötig - nur über mail - zuviele id's und namen drin

**Comment by liv-in-sky** [comment]
Hallo ingo,

habe entdeckt, dass man mittlerweile eigene listen anlegen kann - diese werden auch abgeholt und als datenpunkte angelegt - ich wollte nur mal vorsichtig nachfragen, ob  du bei dem #delete thema schon eine idee hast - die einträge werden in der app gelöscht , die datenpunkte dazu werden aber erst gelöscht nach adapter neustart

**Comment by Apollon77** [comment]
noch keine Zeit gehabt reinzuschauen

**Comment by liv-in-sky** [comment]
ohne nerven zu wollen - nur eine kleine erinnerung, wenn du mal wieder im adapter-inneren unterwegs bist :-)

**Comment by canim60** [comment]
Dito , die funktion wäre mega :)

**Comment by jniclas** [comment]
Hey, ich habe jetzt auch den Issue in meinem Setup entdeckt. Kann ich vllt. irgendwo helfen? Was wäre ein guter Einstiegspunkt?

**Comment by Apollon77** [comment]
@jniclas effektiv Adapter im Debug Log starten und dann log anschauen und mit code verbinden. Alternativ Adapte rin einer IDE im Debugger starten, dann kannst Du im Code strukturierter durchgehen. Der Adapter code liegt in /opt/iobroker/node_modules/iobroker.alexa2/main.js. Wenn DU da s editierst und weiteres Log einbaust kann du schauen

**Comment by jniclas** [comment]
Hey, I updated to the last version 3.3.5. Now item deletion works again.

**Comment by Pocky2507** [comment]
Nee nee, da works nix again...

**Comment by liv-in-sky** [comment]
bei mir auch nix mit der neuen version - ab und an klappt es mal - so alle 30 mal oder so - aber das war auch vorher schon so

**Comment by Apollon77** [comment]
Naja ... ich hab an dem Thema in der 3.4.0 auch nicht gearbeitet, sorry guys

**Comment by m0uh85** [comment]
Friendly reminder :) wenn ich bei irgendwas helfen kann... logfiles o.ä. lasst es mich wissen. Fehler besteht ja leider nach wie vor :(

**Comment by h3llh0und** [comment]
Ja das wäre super, ich nutze die Einkaufslisten gerne und habe mir nun ein Script gebastelt was mir alle offenen Einträge ausdruckt. Diese lösche ich dann nach dem Drucken mittels #delete was auch super funktioniert. Leider müllt es dann halt schon mit der Zeit zu.

**Comment by Apollon77** [comment]
Bitte neues Debug log als text bereittstellen

**Comment by liv-in-sky** [comment]
frisch gemacht - datenpunkte noch da - aber in alexa app ist die liste leer


[debug.txt](https://github.com/Apollon77/ioBroker.alexa2/files/6602976/debug.txt)

**Comment by Apollon77** [comment]
Ok, Bitte GitHub Version Installieren, adapter neu starten (am besten wieder debug modus). Dann nochmal checken und Log zeigen ... Danke!

**Comment by liv-in-sky** [comment]
leider gleiches ergebnis - die datenpunkte werden erst nach neustart des adapters gelöscht

[debug-neu.txt](https://github.com/Apollon77/ioBroker.alexa2/files/6603738/debug-neu.txt)

**Comment by techducks** [comment]
Ich mag das Thema nochmal aufgreifen. In der aktuellen Github Version besteht das Problem immer noch. Erst nach einem Neustart des Adapters werden die Datenpunkte entfernt.

**Comment by majornaese** [comment]
Hi zusammen, ich wollte gestern auch die TODO bzw. Shopping-Liste von Alexa in meinen iobroker über Jarvis integrieren. Anfänglich hat das ganz gut funktioniert, bis zu dem Punkt, wo ich Einträge gelöscht hatte. Ab dann gab es keine Updates mehr. 
Erschwerend kommt jetzt dazu, dass ich nun gar keine Push-Updates mehr bekomme. Beim subscribing to states scheint er hängen zu bleiben. Ein Retry über mehrere Stunden brachte auch keinen Erfolg. Ich vermute, dass meine Tests mit dem Löschen von TODO-Einträgen mit diesem Problem zusammenhängt.
Ich habe die Instanz und den Adapter gelöscht und neu installiert -> Problem bleibt bestehen.
Habt ihr eine Idee, wie ich das korrigieren könnte? Kann es sein, dass der Push-Service irgendwie geblockt wurde? Aber ich hatte die Nacht den Adapter extra abgeschaltet. Heute morgen bestand das Problem immer noch.
Danke!

**Comment by Apollon77** [comment]
Aktuell hat Amazon die Push Connection kaputt gemacht ... daher kommen keine Updates mehr rein ... wir sind dran ... aber 1-2 Tage dauert es bestimmt noch

**Comment by majornaese** [comment]
Hi zusammen. Ich habe ein paar Push-Tests ausgeführt:
- Listeneintrag per App angelegt/auf erledigt gesetzt -> funzt
- Listeneintrag per App gelöscht -> funzt
- Echo Dot per Sprachbefehl angesteuert-> Daten werden in der History aktualisiert
- Amazon Steckdose per App geschaltet -> powerState wird nicht aktualisiert, ich meine das war vorher anders, bin mir aber nicht ganz sicher.
Mehr schaffe ich heute nicht, aber danke @Apollon77 für die schnelle Korrektur!

**Comment by liv-in-sky** [comment]
vielen dank - schaut sehr gut aus im moment lassen sich alle items löschen

**Comment by Apollon77** [comment]
fixed in 3.11.0
