### ISSUE TITLE
Authentifizierung funktioniert nicht nach Update auf 3.2.8

### ISSUE THREAD

**Issue by hwd1967** [Apollon77/ioBroker.alexa2#516]
Hallo,
nach dem Upgrade vom .7 hatte ich erstmal ähnliche Probleme wie in anderen Post beschrieben (Keine Instanz).
Nach manuellem Löschen und Neuinstallation des Adapters ist die Instanz jetzt da.

Verbindung zum Alexa-Account funktioniert aber nicht. Der Adapter bleibt in "gelb" hängen und spamt das Log voll:

![image](https://user-images.githubusercontent.com/68302534/87880187-dcfa9d80-c9ef-11ea-9760-294fd829af56.png)

Die Adapter-Config-Seite:

![image](https://user-images.githubusercontent.com/68302534/87880227-45497f00-c9f0-11ea-8886-41d504d26c59.png)

Versions:
 - JS-Controller version: 3.1.6
 - Node version: 12.18.1

Sowohl die Alexa-Seite als auch die Amazon-App laufen ohne Probleme mit meinem Login.

Da bin  ich aktuell am Ende mit meinem Latein...

**Comment by Apollon77** [comment]
Bitte instanz löschen und neu anlegen und dann neu per Proxy verbinden

**Comment by Gre4t0ne** [comment]
Bei mir das gleiche - wobei ich die Alexa Instanz nicht entfernen kann bleibt immer hängen!?

Wie verbinde ich mich per PROXY?

**Comment by Gre4t0ne** [comment]
Instanz gelöscht (obwohl ich ihn bei 200 Items left abbrechen musste)
cd /opt/iobroker
iobroker stop
npm install iobroker.alexa2@3.2.8 --production
iobroker start

musste aber danach trotzdem Instanz neu installieren ABER dann funktionierte der Login

**Comment by Apollon77** [comment]
Bitte ggf 3.3.0 versuchen falls noch nicht behoben

**Comment by hwd1967** [comment]
> Instanz gelöscht (obwohl ich ihn bei 200 Items left abbrechen musste)
> cd /opt/iobroker
> iobroker stop
> npm install iobroker.alexa2@3.2.8 --production
> iobroker start
> 
> musste aber danach trotzdem Instanz neu installieren ABER dann funktionierte der Login

Habe es so auch gemacht, allerdings noch ein reboot hinten dran und jetzt fluppt es!
THX an Appolon77 für den Riesenjob mit dem Adapter!
