### ISSUE TITLE
Sonos BEAM Integration

### ISSUE THREAD

**Issue by Xanon1** [Apollon77/ioBroker.alexa2#52]
Hallo,
ich habe diverse Alexas, diverse Sonos PLAY1 und den neuen Sonos BEAM (**mit Alexa**) Zuhause im Einsatz.
Alle Sonos Lautsprecher sind an dem Beam per Multiroom verbunden.
Nun hatte ich gehofft, dass ich über den Adapte auch den BEAM zum sprechen bekomme, weil die Sprachqualität echt gut ist.
Und da die anderen Sonos Lautsprecher ja sowieso mit dem Beam verbunden sind, würde ich die durchsagen halt im ganzen Haus hören. 

Leider fehlt aber genau bei diesem Lautsprecher das Object SPEAK in der Liste.
Kannst du dies in den Adapter Integrieren?

Hatte dies auch schon mal im Forum gefragt
[https://forum.iobroker.net/viewtopic.php?f=37&t=15547&p=166076#p166076](url)

**Comment by Apollon77** [comment]
Dann brauche ich bitte von dem beam device den devicetype und die capabilities (beides bei dem device in den Objekten unter „Infos“. 

Und bitte sicherstellen das du per alexa app auch eine Routine mit Sprachausgabe anlegen kannst die auf diesem Beam etwas ausgibt.

**Comment by Xanon1** [comment]
Okay,
hier die Infos:
**capabilities**
`AMAZON_MUSIC,AUDIBLE,TIMERS_AND_ALARMS,I_HEART_RADIO,REMINDERS,PEONY,CHANGE_NAME,TUNE_IN,AUDIO_PLAYER,MICROPHONE,VOLUME_SETTING,SLEEP,GOLDFISH,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,DEREGISTER_DEVICE,KINDLE_BOOKS,PERSISTENT_CONNECTION,DREAM_TRAINING`

**devicetype**
`A3NPD82ABCPIDP`

Zu den Routinen und deren Sprachausgaben:
Wenn ich eine Routine mit Sprachausgabe über den BEAM starte, sagt Alexa 
"Audioaktionenen werden derzeit auf diesem Gerät nicht unterstützt"
danach startet Sie die Routine und **spicht** doch dass, was ich zuvor in der Routine eingetragen habe.

**Comment by Apollon77** [comment]
check 0.4.0 from GitHub and https://forum.iobroker.net/viewtopic.php?f=37&t=16095

**Comment by Xanon1** [comment]
Funktioniert!
Danke !!!
TopArbeit
