### ISSUE TITLE
Routinen nicht mehr vorhanden

### ISSUE THREAD

**Issue by Blackmytj** [Apollon77/ioBroker.alexa2#520]
Alexa Routinen sind unter den Amazon Geräten nicht mehr vorhanden.

Unter den Objekten alexa2.0.Echo-Devices.AleaGerät fehlt der Ordner Routins.

Gibt es derzeit Probleme ? Problem besteht auch mit der Version 3.3.0

Danke und Grüße

**Comment by Apollon77** [comment]
Adapter mal neu gestartet? bei mir ist noch alles da

**Comment by Blackmytj** [comment]
Ja auch schon neu installiert. Hast du mal den komplette ioBroker neu gestartet ob es danach vielleicht weg ist ?ü

**Comment by Apollon77** [comment]
Und der Adapter ist grün nach dem Restart? Auch mal Admin neu geladen? Routinen sind in der Alexa App noch alle da?

Sag mal device type und capabilities von dem wo es fehlt

Bei mir ist noch alles da

Sonst hilft nur ein Debug Log vom Start mir als Email (iobroker@fischer-ka.de) mit verweis auf dieses Issue.

**Comment by Blackmytj** [comment]
Adapter ist grün.
Admin und komplettes System wurden neu gestartet. 

Routinen sind in der Alexa App vorhanden habe auch als Test neue angelegt.

DeviceType:  A7WXQPH584YP
Capabillities: AMAZON_MUSIC,DIALOG_INTERFACE_VERSION,PERSISTENT_CONNECTION,AUDIO_CONTROLS,TUPLE_CATEGORY_A,TAHOE_BYOD,ASCENDING_ALARM_VOLUME,SUPPORTS_SOFTWARE_VERSION,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,SLEEP,DEREGISTER_FACTORY_RESET,REMINDERS,DREAM_TRAINING,REQUIRES_OOBE_FOR_SETUP,MICROPHONE,KINDLE_BOOKS,DS_VOLUME_SETTING,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,AUDIBLE,ACTIVE_AFTER_FRO,GUARD_EARCON,EARCONS,UPDATE_WIFI,VOLUME_SETTING,LEMUR_ALPHA,SUPPORTS_LOCALE_SWITCH,MUSIC_SKILL,SUPPORTS_LOCALE,CUSTOM_ALARM_TONE,SALMON,EQUALIZER_CONTROLLER_BASS,PAIR_BT_SINK,TIMERS_AND_ALARMS,AUDIO_PLAYER,ALEXA_PRESENCE,VOICE_TRAINING,FLASH_BRIEFING,EQUALIZER_CONTROLLER_TREBLE,TUNE_IN,DEREGISTER_DEVICE,PAIR_REMOTE,FAR_FIELD_WAKE_WORD,CHANGE_NAME,GOLDFISH,SUPPORT_CALENDAR_ALERT,POPTART,SOUND_SETTINGS,PAIR_BT_SOURCE,SET_LOCALE,EQUALIZER_CONTROLLER_MIDRANGE,TUPLE,PANDORA,I_HEART_RADIO,GADGETS

Logfile geht auch gleich raus.

Danke schon mal für deine Mühe

**Comment by Apollon77** [comment]
Wieviele Routinen hast du? Amazon braucht über 10s um die zurückzugeben und daher gibts keine

**Comment by Blackmytj** [comment]
60 Stück, hab ich aber schon ca. Ein halbes Jahr.
An den Routinen hatte ich schon ewig nichts mehr geändert

**Comment by Apollon77** [comment]
Dann ist Amazon gerade irgendwie langsam. Ich kann in einem nächsten Update mal den Timeout erhöhen ... dann sehen wir weiter

**Comment by Blackmytj** [comment]
Alles klar danke vielleicht geht es auch die nächsten Tage wieder. Bekomm ich ne Mail wenn es das Update gibt ? Schreibst du es dann nochmal ins issuse?

**Comment by Apollon77** [comment]
jupp, ich kommentiere da issue. vllt heute abend

**Comment by Blackmytj** [comment]
Super Danke :-)

**Comment by Blackmytj** [comment]
Problem besteht nicht mehr, Routinen sind auch wieder verfügbar.
Was mir aufgefallen ist, das Update auf die Adapter in iobroker war ebenfalls temporär nicht möglich.

Vielleicht bestand darin ein Zusammenhang ?!

Trotzdem vielen Dank für deine Hilfe und Mühe

**Comment by Apollon77** [comment]
Vllt lokal bei dir Netzwerkprobleme oder so. Ich erhöhe mal timeout aber dann ists ja nicht mehr so dringend :-)
