### ISSUE TITLE
Sprachausgabe auf Handy App

### ISSUE THREAD

**Issue by Siggi0904** [Apollon77/ioBroker.alexa2#523]
Hallo,

ich würde gern eine Blockly Sprachausgabe auf die Alexa App im Android Handy machen.
Nur hat ThisDevice kein Commands. Was ist da der Hintergrund?
Sorry, falls das schon per issue durch ging, ich hatte keinen gefunden.

In der Handy-App per Button kann man was fragen und bekommt es beantwortet,
nur Ausgaben vom iobroker können nicht weiter gegeben werden.

Großen Dank.

**Comment by Apollon77** [comment]
Einfache Antwort: weil es nicht geht. Oder kannst du inzwischen per Alexa App eine Routine definieren und dort sein Handy als Sprachausgabe Ziel angeben? Ging bisher nicht.

**Comment by Siggi0904** [comment]
Ja, geht leider nicht.

Ich hatte mich als newby gewundert, dass man ans Handy nichts schicken kann, obwol ja die Ausgaben selbst funktionieren.
