### ISSUE TITLE
Speak command stopped working on FireTV Cube

### ISSUE THREAD

**Issue by CC1337** [Apollon77/ioBroker.alexa2#525]
**Describe the bug**  
I am using the "speak" command by writing scripts into it in scripts. This once worked for the Cube AND an Echo Show 5. Now only Echo show 5 works, but on the FireTV cube there there is no output. I also tried the "announcement" or "notification". The last sends a notification to the alexa app on my phone. None do any sound output on the Cube. I also checked with connected and running TV, nothing displayed there as well.
If I execute "funcfact" command, the cube speaks: 
> Ich kann den Song "Tell me a funfact" nicht in deiner Musikbibliothek finden.
(cannot find "Tell me a funfact" in you music library)
If I execute "joke" it tells a joke.
Routines are also being triggered in the adapter's states if I start them via voice.

It seems that the overall connection / communication works but propably the protocol changed.

I also deleted the instance and recreated it. Echo show still / again works properly.

**To Reproduce**  
Go to alexa2 adapter states for the FireTV Cube in objects, write some text into commands/speak

**Expected behavior**  
TTS output - but there is only silence.

**Screenshots & Logfiles**  
No error nor debug log entry when executing a command.
Log on adapter startup shows:
```
alexa2.0 | 2020-08-07 22:54:59.131 | info | (28450) Alexa-Push-Connection established. Disable Polling
-- | -- | -- | --
alexa2.0 | 2020-08-07 22:54:58.908 | info | (28450)     Device-type:A2JKHJ0PX4J3L3  (MICROPHONE,SUPPORTS_LOCALE,FLASH_BRIEFING,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,FAR_FIELD_WAKE_WORD,ACTIVE_AFTER_FRO,CHANGE_NAME,AUDIBLE,MUSIC_SKILL,EARCONS,TUNE_
alexa2.0 | 2020-08-07 22:54:58.908 | info | (28450) Report to developer as GitHub issue with details for device.  Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-08-07 22:54:58.907 | info | (28450) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-08-07 22:54:55.880 | info | (28450) Use Override IP 192.168.0.90 for Proxy
alexa2.0 | 2020-08-07 22:54:55.594 | info | (28450) starting. Version 3.3.1 in /opt/iobroker/node_modules/iobroker.alexa2, node: v10.21.0, js-controller: 3.1.6
```
(the DeviceType matches the FireTV Cube in adapter states)
Looks similar to #493 

**Versions:**  
 - Adapter version: 3.3.1
 - JS-Controller version: 3.1.6
 - Node version: 10.21.0
 - Operating system: docker @ Raspbian @ Pi 4

**Additional context**  
I cannot tell if maybe Amazon changed something on their side / how to find the exact issue best. I can support finding out, some developer experience is available and postman is installed :)

**Comment by Apollon77** [comment]
Verify please by trying to do it as routine via Alexa App ... is that working?

**Comment by CC1337** [comment]
Ah right, did not think of that, was not sure how to trigger speak via app...
So, that's not working as well if I select the Cube as output device -> silence. 
If I select the Echo Show, even when starting the routine at the cube -> works.
I guess it's a case for the amazon support if you have no other idea... and yes, I have tried turning it off and on again :)

**Comment by Apollon77** [comment]
Thennit seems amazon changed things ... sorry. I can not do anything
