### ISSUE TITLE
"clearOwnMessages" nicht mehr möglich

### ISSUE THREAD

**Issue by Phillipp83** [Apollon77/ioBroker.alexa2#527]
HI, Ich stelle letzter zeit fest. Wenn ich über den ioBrocker eine Text nachricht schicke, kann ich die nicht über den Butten clearOwnMessages löschen. 

Adapter Ver. 3.3.1
Node.js: v12.18.3
NPM: 6.14.6
Debian GNU/Linux x64

Ich habe Log debug daten aber die wollte ich nicht hier preisgeben wie finde ich deine E-Mail Adresse raus. 

Gruß Phillipp

**Comment by Apollon77** [comment]
Email Steht im GitHub Profil ;-)

**Comment by Phillipp83** [comment]
Ich habe mir dein Profil angeschaut aber irgend wie finde ich das nicht.  Peinlich :-)

Ich habe was neues herausgefunden. 
Wenn ich eine eine Nachricht schicke und Alexa frage, liest sie meine Nachricht vor.
Aber wenn ich eine Nachricht schicke und den "clearOwnMessages" drücke bleibt der Ring aber sie weiß von keiner Nachricht. 

Ich vermute das es ein Fehler von Amazon ist.

**Comment by Apollon77** [comment]
iobroker@fischer-ka.de ... ALso wo ist die Message noch da nach clearOwn?

**Comment by Phillipp83** [comment]
Genau die Nachricht ist weg nach dem clearOwn. Aber dir Gelbe Ring bleibt.

**Comment by Apollon77** [comment]
Ok, dann kann ich da nix machen ... bzw wie ist es denn wenn DU nur per Alexa App arbeitest und löschst  - ist der Ring dann auch noch da? Wenn ja dann Amazon issue
