### ISSUE TITLE
Registrierung von Statusupdates geht nach Wiederherstellung der Alexa-Push-Connection verloren

### ISSUE THREAD

**Issue by stefan-franke** [Apollon77/ioBroker.alexa2#528]
Ich habe ein Script, welches auf Änderungen verschiedener Statusobjekte reagiert (z.B. alexa2.0.History.creationTime). Nach dem Start des Adapters funktioniert das wunderbar. Die Änderung wird erkannt und der Code in meinem Script wird entsprechend ausgeführt.

Allerdings gibt es über den Tag hinweg immer wieder Zeitpunkte, wo die Alexa-Push-Connection neu aufgebaut werden muss (24-Stunden-DSL-Disconnect und zu weiteren Zeiten, die wahrscheinlich von Amazon ausgelöst werden?). Das sieht dann im Log so aus:

> alexa2.0 | 2020-08-14 12:42:51.945 | info | (7460) Alexa-Push-Connection established. Disable Polling
> alexa2.0 | 2020-08-14 12:42:36.234 | info | (7460) Alexa-Push-Connection disconnected - retry: Retry Connection in 15s

Nach einem solchen Wiederherstellen der Alexa-Push-Connection bekommt mein Script keine Benachrichtigung von Statusänderungen mehr mitgeteilt. Ich vermute, dass folgende Funktion fehlt, die beim Starten des Adapters zusätzlich ausgeführt wird:

>**_alexa2.0 | 2020-08-14 13:21:15.028 | info | (8851) Subscribing to states..._**
>alexa2.0 | 2020-08-14 13:21:02.191 | info | (8851) Alexa-Push-Connection established. Disable Polling
>alexa2.0 | 2020-08-14 13:20:56.706 | info | (8851) Proxy IP not set, use first network interface ... instead
>alexa2.0 | 2020-08-14 13:20:56.374 | info | (8851) starting. Version 3.3.1 in /opt/iobroker/node_modules/iobroker.alexa2, node: v10.19.0, js-controller: 3.1.6

Wenn ich mir den Source Code anschaue, dann werden bei "Subscribing to states..." folgende Statements ausgeführt (Zeile 2815f):

> adapter.log.info('Subscribing to states...');
> adapter.subscribeStates('*');
> adapter.subscribeObjects('*');
> initDone = true;

Ist das plausibel, dass die Weitergabe der Statusänderung an diesen beiden Zeilen hängen - und diese bei der Wiederherstellung der Alexa-Push-Connection nicht ausgeführt werden? Oder gibt es andere Erklärungen für dieses Verhalten (zum Beispiel Time-outs der Registrierung)?

**Comment by Apollon77** [comment]
"subscribe to States" ist genau anders rum: Erst wenn alles initialisieet ist reagiert der Adapter auf Änderungen von States aus ioBroker. Ist also hier exakt irrelevant.

Schalte den Adapter doch mal auf debug - ja da wird dann einiges geloggt. Die Frage ist wie sieht das debug log aus nachdem er dann mal automatisch die verbindung wiederhergestellt hat - kommen Push infos weiterhin an oder nicht? Das Debug log wäre mal interessant

**Comment by stefan-franke** [comment]
Danke für die schnelle Antwort. Ich habe den Adapter jetzt in den Debug-Mode gesetzt und warte mal ab, wenn die Statusänderungen wieder nicht weitergegeben werden.

**Comment by stefan-franke** [comment]
Ich habe jetzt den Debug-Mode in der Fehlersituation genutzt. Wenn ich Alexa einen Sprachbefehl gebe, dann kommen folgende Zeilen im Log:

> alexa2.0 | 2020-08-17 09:26:14.976 | debug | (9180) State changed alexa2.0.Echo-Devices....WT4.Player.muted: 
>alexa2.0 | 2020-08-17 09:26:14.974 | debug | (9180) Alexa-Remote WS-MQTT: Command PUSH_EQUALIZER_STATE_CHANGE: 
>alexa2.0 | 2020-08-17 09:26:14.969 | debug | (9180) State changed alexa2.0.Echo-Devices....WT4.Player.volume: 
>alexa2.0 | 2020-08-17 09:26:14.960 | debug | (9180) Alexa-Push-Connection Device Volume change for ...WT4 -> 10/false
>alexa2.0 | 2020-08-17 09:26:14.959 | debug | (9180) Alexa-Remote WS-MQTT: Command PUSH_VOLUME_CHANGE: 
>alexa2.0 | 2020-08-17 09:26:14.759 | debug | (9180) State changed alexa2.0.Echo-Devices....WT4.Player.muted: 
>alexa2.0 | 2020-08-17 09:26:14.751 | debug | (9180) State changed alexa2.0.Echo-Devices....WT4.Player.volume: 
>alexa2.0 | 2020-08-17 09:26:14.738 | debug | (9180) Alexa-Push-Connection Device Volume change for ...WT4 -> 10/false
alexa2.0 | 2020-08-17 09:26:14.737 | debug | (9180) Alexa-Remote WS-MQTT: Command PUSH_VOLUME_CHANGE: 
>alexa2.0 | 2020-08-17 09:26:14.732 | debug | (9180) Alexa-Remote WS-MQTT: Command PUSH_EQUALIZER_STATE_CHANGE: 
>alexa2.0 | 2020-08-17 09:26:14.462 | debug | (9180) State changed alexa2.0.Echo-Devices....WT4.Player.muted: 
>alexa2.0 | 2020-08-17 09:26:14.457 | debug | (9180) State changed alexa2.0.Echo-Devices....WT4.Player.volume: 
>alexa2.0 | 2020-08-17 09:26:14.448 | debug | (9180) Alexa-Remote WS-MQTT: Command PUSH_EQUALIZER_STATE_CHANGE: 
>alexa2.0 | 2020-08-17 09:26:14.444 | debug | (9180) Alexa-Push-Connection Device Volume change for ...WT4 -> 10/false
>alexa2.0 | 2020-08-17 09:26:14.444 | debug | (9180) Alexa-Remote WS-MQTT: Command PUSH_VOLUME_CHANGE: 
>alexa2.0 | 2020-08-17 09:26:14.302 | debug | (9180) State changed alexa2.0.Echo-Devices....WT4.Player.muted: 
>alexa2.0 | 2020-08-17 09:26:14.298 | debug | (9180) State changed alexa2.0.Echo-Devices....WT4.Player.volume: 
>alexa2.0 | 2020-08-17 09:26:14.290 | debug | (9180) Alexa-Remote WS-MQTT: Command PUSH_ACTIVITY: 
>alexa2.0 | 2020-08-17 09:26:14.288 | debug | (9180) Alexa-Push-Connection Device Volume change for ...WT4 -> 10/false
>alexa2.0 | 2020-08-17 09:26:14.288 | debug | (9180) Alexa-Remote WS-MQTT: Command PUSH_VOLUME_CHANGE: 
>alexa2.0 | 2020-08-17 09:26:14.274 | debug | (9180) Alexa-Remote WS-MQTT: Command PUSH_EQUALIZER_STATE_CHANGE: 
>alexa2.0 | 2020-08-17 09:26:13.251 | debug | (9180) State changed alexa2.0.Echo-Devices....WT4.Player.muted: 
>alexa2.0 | 2020-08-17 09:26:13.247 | debug | (9180) State changed alexa2.0.Echo-Devices....WT4.Player.volume: 
>alexa2.0 | 2020-08-17 09:26:13.230 | debug | (9180) Alexa-Push-Connection Device Volume change for ...WT4 -> 10/false
>alexa2.0 | 2020-08-17 09:26:13.230 | debug | (9180) Alexa-Remote WS-MQTT: Command PUSH_VOLUME_CHANGE: 
>alexa2.0 | 2020-08-17 09:26:13.224 | debug | (9180) Alexa-Remote WS-MQTT: Command PUSH_EQUALIZER_STATE_CHANGE:
>alexa2.0 | 2020-08-17 09:26:12.859 | debug | (9180) State changed alexa2.0.Echo-Devices....WT4.Player.muted: 
>alexa2.0 | 2020-08-17 09:26:12.854 | debug | (9180) State changed alexa2.0.Echo-Devices....WT4.Player.volume: 
>alexa2.0 | 2020-08-17 09:26:12.835 | debug | (9180) Alexa-Remote WS-MQTT: Command PUSH_EQUALIZER_STATE_CHANGE: 
>alexa2.0 | 2020-08-17 09:26:12.833 | debug | (9180) Alexa-Push-Connection Device Volume change for ...WT4 -> 10/false
>alexa2.0 | 2020-08-17 09:26:12.832 | debug | (9180) Alexa-Remote WS-MQTT: Command PUSH_VOLUME_CHANGE:

Da ist viel Lautstärkeregelung dabei, womit mein Kommando aber nichts zu tun hatte. Diese Lautstärke-Zeilen kommen auch regelmäßig im Log, auch wenn man Alexa nicht anspricht. Hier nun der Log nach dem Restart des Adapters:

>alexa2.0 | 2020-08-17 09:40:06.519 | debug | (13970) State changed alexa2.0.Echo-Devices....WT4.Player.muted: 
>alexa2.0 | 2020-08-17 09:40:06.517 | debug | (13970) State changed alexa2.0.Echo-Devices....WT4.Player.volume: 
>alexa2.0 | 2020-08-17 09:40:06.507 | debug | (13970) State changed alexa2.0.History.json:
>alexa2.0 | 2020-08-17 09:40:06.505 | debug | (13970) State changed alexa2.0.History.answerText: 
>alexa2.0 | 2020-08-17 09:40:06.497 | debug | (13970) State changed alexa2.0.History.cardJson: 
>alexa2.0 | 2020-08-17 09:40:06.496 | debug | (13970) State changed alexa2.0.History.cardContent: 
>alexa2.0 | 2020-08-17 09:40:06.494 | debug | (13970) State changed alexa2.0.History.domainApplicationName: 
>alexa2.0 | 2020-08-17 09:40:06.492 | debug | (13970) State changed alexa2.0.History.domainApplicationId: 
>alexa2.0 | 2020-08-17 09:40:06.491 | debug | (13970) State changed alexa2.0.History.creationTime: 
>alexa2.0 | 2020-08-17 09:40:06.489 | debug | (13970) State changed alexa2.0.History.status: 
>alexa2.0 | 2020-08-17 09:40:06.485 | debug | (13970) Alexa-Remote WS-MQTT: Command PUSH_EQUALIZER_STATE_CHANGE: 
>alexa2.0 | 2020-08-17 09:40:06.482 | debug | (13970) Alexa-Push-Connection Device Volume change for ...WT4 -> 10/false
>alexa2.0 | 2020-08-17 09:40:06.481 | debug | (13970) Alexa-Remote WS-MQTT: Command PUSH_VOLUME_CHANGE: 
>alexa2.0 | 2020-08-17 09:40:06.471 | debug | (13970) State changed alexa2.0.History.summary: 
>alexa2.0 | 2020-08-17 09:40:06.469 | debug | (13970) State changed alexa2.0.History.serialNumber: 
>alexa2.0 | 2020-08-17 09:40:06.456 | debug | (13970) State changed alexa2.0.History.name: 
>javascript.0 | 2020-08-17 09:40:06.453 | info | (630) script.js.productive.DeviceManagement: History Change
>alexa2.0 | 2020-08-17 09:40:06.431 | debug | (13970) Alexa-Remote: 0 entries left in activity queue
>alexa2.0 | 2020-08-17 09:40:06.427 | debug | (13970) device-activity: 
>alexa2.0 | 2020-08-17 09:40:06.425 | debug | (13970) Alexa-Remote: Activity found 0 for Activity ID 
>alexa2.0 | 2020-08-17 09:40:06.423 | debug | (13970) Alexa-Remote: Response: 
>alexa2.0 | 2020-08-17 09:40:06.204 | debug | (13970) Alexa-Remote: Sending Request with 
>alexa2.0 | 2020-08-17 09:40:06.202 | debug | (13970) Alexa-Remote: No authentication check needed (time elapsed 340854)

Es kommen zusätzlich auch noch die gleichen Lautstärkemeldungen wie oben mit hoch, die ich jetzt aber hier weggelassen habe. Wenn ich die beiden Logs vergleiche, fehlt offensichtlich die Push-Benachrichtung der Statusänderung. Ich hatte am Freitag noch weiter ausprobiert und den DSL-Router ein paar mal neu gestartet, um die Situation nachzustellen. Da hat sich aber der Fehler nicht eingestellt. Das heißt, in einer gewissen Zeit nach dem Neustart des Adapters bleibt die Verbindung der Push-Benachrichtigungen bestehen, auch wenn das Internet einige Minuten ausfällt. Erst nach einer längeren Periode (meistens über Nacht), kommen die Benachrichtigungen nicht mehr an. Hat Amazon einen Timeout für die Registrierung von Push-Events, die man dann wieder aufbauen muss?

**Comment by Apollon77** [comment]
Wenn die Push Verbindung weg wäre würden die ganzen PUSH* Meldungen alle nicht kommen. Über die gleiche Methode kommen auch infos zu ACTIVITY (das ist in deinem zweiten "Log nach Adapter restart" nicht dabei muss aber kurz über den ganzen history Meldungen kommen.

Die Frage ist also jetzt eher warum Dir Amazon keine Push Meldungen mehr sendet ... Du bist bisher der einzige der das berichtet ... hm ...

**Comment by stefan-franke** [comment]
Ich habe jetzt alle anderen Skripte ausgeschaltet. Siehe da, es funktioniert auch nach einem Tag noch. Ich habe ein paar alte Skripte, die Requests an die Alexa-API schicken (https://layla.amazon.de/api/). Ich vermute jetzt, dass eines von diesen den fehlerhaften Zustand auslöst. Ich werde also diejenigen, die ich noch benötige auf den Adapter umstellen (was hoffentlich möglich sein wird). Dann sollte eigentlich alles klappen. Danke Apollon für Deine Hilfe!
