### ISSUE TITLE
Virtuelles Gerät "ALL"

### ISSUE THREAD

**Issue by ZZMajor** [Apollon77/ioBroker.alexa2#53]
Im zugrundeliegenden [Script von Thorsten Gehrig](https://github.com/thorsten-gehrig/alexa-remote-control) gibt es die Möglichkeit, Befehle an ein virtuelles Gerät "ALL" zu schicken um somit alle Echo-Geräte anzusprechen ohne extra eine Multiroom-Gruppe in Alexa erstellen zu müssen. Ist so etwas für diesen Adapter auch denkbar?
Wäre z.B. praktisch um Sprachausgaben an alle Echos zu senden, ohne jeden einzelnen in ioBroker separat auswählen zu müssen.

Gruss, Jürgen

**Comment by Apollon77** [comment]
Hm ... technisch ja, ob es Sinn macht bin ich nicht sicher. Kann man einfach selbst mir Skripten lösen. Muss ich mal nachdenken.

**Comment by ZZMajor** [comment]
Kein Problem, ist ja auch eher ein Feature Request als ein Issue. Fiel mir nur auf, als ich vom Script nun komplett auf Deinen, im Übrigen, hervorragenden Adapter umgestiegen bin und keinen Datenpunkt für meinen bisherige "AlexaSpeakALL" fand. :-)

Wie Du sagst, mit Skripten auch lösbar...

Gruss, Jürgen

**Comment by ZZMajor** [comment]
Jo, eigentlich auch kein Aufwand, einfach in der Alexa App eine Multiroomgruppe mit allen Echos erstellen. Hast recht, dann braucht am Adapter nichts geändert werden.
Wegen mir kann das Issue dann geschlossen werden (BTW, mangels Erfahrung in Github, kann ich das auch, ich teste mal unten das "Close and comment?)

Und nochmal Danke für die tolle Arbeit und Dein Einbringen generell in ioBroker.

Gruss, Jürgen

**Comment by Apollon77** [comment]
Perfekt ;-)
