### ISSUE TITLE
Alexa Sprachsteuerung und App - fährt HMIP Rollos bei 0% UND 100% ganz nach unten.

### ISSUE THREAD

**Issue by JuergenHorvath** [Apollon77/ioBroker.alexa2#531]
Iobroker mit Alexa2 Instanz auf Raspi4.
Raspberrymatic auf 2tem Raspi4.
beide Systeme komplett aktuell.

Alle Froll HMIP Aktoren richtig in der Raspberrymatic drin.
Alle Aktoren richtiger Kanal in IoT eingebunden.
Alexa findet alles richtig.

Allerdings sagt man Alexa, Wohnzimmerrollo 100% - fährt sie den Rollo ganz nach unten.
Gleiches macht sie bei 0% - sie fährt den Rollo ganz runter.
Die anderen Werte fährt sie richtig an.

Steuerung in der Raspberrymatic läuft richtig. 100% ist oben, 0% ist unten.
Setzt man den Wert in Iobroker in den Objekten bei den Rollos in der HM Instanz, dann setzt sie auch alles richtig um.
Setzt man den Wert in den Objekten in der Alexa Instanz unter Smart Home Devices - tritt der Fehler auf.
Sprich 100% UND 0 % fahren ganz runter.

**Comment by Apollon77** [comment]
Und was hat das mit Alexa2 zu tun? Der Alexa 2 Adapter erlaubt es die Alexa Geräte direkt zu steuern. 

Oder ist es eher ein Thema für den iot Adapter und den iobroker Smart Home skill?

**Comment by Apollon77** [comment]
Aahh nochmal gelesen: was macht denn die alexa App? Ist es da korrekt? Der Alexa2 sendet nur Werte zu Amazon wie die App. Daher hat der Adapter keinen echten Einfluss

**Comment by JuergenHorvath** [comment]
Ich dachte das ist ein Problem des Alexa Adapters. Sorry.
Also es passiert das gleiche mit Sprachansage als auch wenn ich in der App das Rollo ein oder ausschalte.

**Comment by Apollon77** [comment]
Dann ist es eher ein iot Thema

**Comment by JuergenHorvath** [comment]
Danke und sorry für den falschen issue.
