### ISSUE TITLE
Einbinden der Doorbell API 

### ISSUE THREAD

**Issue by peoples0815** [Apollon77/ioBroker.alexa2#532]
Hi, 

ich wollte anfragen ob es angedacht ist die Doorbell Api mit einzubinden. So wäre es wie in einigen Videos zu sehen möglich Alexa als Türklingel-Lautsprecher klingeln zu lassen?

**Comment by Apollon77** [comment]
Was ist die Doorbell API? Welche Videos? Der Adapter kann aktuell das was die Alexa App kann ...

**Comment by peoples0815** [comment]
https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-doorbelleventsource.html

Hier ist der Link. 

Wenn ich das richtig verstanden habe gibt es einen "DoorbellPress Event" welcher dann ein Klingeln und wenn gewünscht eine zusätzliche Ansage abspielt. Evtl. wäre das ja über einen weiteren Button realisierbar.

Wenn ich das Video wieder finde poste ich den Link noch dazu

**Comment by Apollon77** [comment]
Ok das ist wenn ein Issue für den iot Adapter. Nicht Alexa2
