### ISSUE TITLE
Datenpunkte für Player und Musik-Provider für Fire HD 10

### ISSUE THREAD

**Issue by Ridesa** [Apollon77/ioBroker.alexa2#54]
Hi mir ist gerade aufgefallen das für das Fire HD 10 noch die Datenpunkte Player und Musik-Provider fehlen, könntest du die noch hinzufügen bitte.

Fire HD 10
device-type A3R9S4ZZECZ6YL
capabilities
{
  "from": "system.adapter.alexa2.0",
  "ts": 1532958172857,
  "common": {
    "name": "capabilities",
    "role": "text",
    "type": "string",
    "def": "ASCENDING_ALARM_VOLUME,REMINDERS,MICROPHONE,ASX_TIME_ZONE,VOLUME_SETTING,PEONY,SUPPORTS_SOFTWARE_VERSION",
    "write": false,
    "read": true
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "alexa2.0.Echo-Devices.G000N6078203072D.Info.capabilities",
  "type": "state"
}

**Comment by Apollon77** [comment]
Versuch mal aktuellsten GitHub stand ... ?!

**Comment by Ridesa** [comment]
hab ich da sind nur die Datenpunkte für Commands dazu gekommen

**Comment by Apollon77** [comment]
Hm ... wenn ich die capabilities so ansehe fehlt da AUDIO_PLAYER und so und deswegen fehlen die datenpunkte.

Kannst du per alexa app dort Musik abspielen oder Routinen anlegen die Musik von einem der Provider dort abspielen? Ich würde erwarten das nein. ....

**Comment by Ridesa** [comment]
über die Alexa app gehts nicht, aber mit Routinen lässt es sich starten auf dem Tablet.

**Comment by Apollon77** [comment]
check 0.4.0
