### ISSUE TITLE
Alexa-Push-Connection Unknown Command PUSH_DEVICE_SETUP_STATE_CHANGE - send to Developer:

### ISSUE THREAD

**Issue by m0rph2k** [Apollon77/ioBroker.alexa2#540]
Hi

Bekomme hin und wieder folgende Info im Log
Alexa-Push-Connection Unknown Command PUSH_DEVICE_SETUP_STATE_CHANGE - send to Developer: {"destinationUserId":"A0530574PBRRZXYLKB43","state":"DISCOVERED","eventSuccess":true,"deviceType":null

js-controller 3.1.6
alexa2: 3.3.1 

LG

**Comment by canim60** [comment]
bekomm ich ebenfals seit gestern


`

alexa2.0 | 2020-09-24 11:14:45.919 | info | (1255) Alexa-Push-Connection Unknown Command  PUSH_DEVICE_SETUP_STATE_CHANGE - send to Developer:  {"destinationUserId":"A1PT5EBRCA41TF","state":"DISCOVERED","eventSuccess":true,"deviceType":"A1RABVCI4
-- | -- | -- | --


`

**Comment by WaJoWi** [comment]
Bei mir auch.

`Alexa-Push-Connection Unknown Command PUSH_DEVICE_SETUP_STATE_CHANGE - send to Developer: {"destinationUserId":"A32TW4JJLN57E8","state":"DISCOVERED","eventSuccess":true,"deviceType":null,"deviceSerialNumber":null,"productIndex":"FZdX","reconnectSession":false,"sessionToken":"95177e61-b939-4d6d-96b4-ca3b465d4483","timestamp":null}`

**Comment by jNk89** [comment]
Ich habe ebenfalls die selbe Info im Log.

**Comment by Apollon77** [comment]
kommt in nächster verison
