### ISSUE TITLE
Smart-Home-Devices deleteAll and discoverDevices not usable after another

### ISSUE THREAD

**Issue by thost96** [Apollon77/ioBroker.alexa2#542]
**Describe the bug**  
Hi, I wanted to implement a way how I can delete all Alexa Smart Home Devices and scan for new ones after the deleteAll has finished, but as deleteAll gets pushed, the whole Smart-Home-Devices folder gets removed. So it's not possible to use discoverDevices after that, as it isn't available anymore. Waiting for the adapter to recreate them takes a long time and might require some instance restart, which isn't a solution to me.

It would be nice to only delete all devices from the Smart-Home-Devices folder except for deleteAll and discoverDevices buttons.

Thanks!

**Versions:**  
 - Adapter version: 3.3.1
 - JS-Controller version: 3.1.1 
 - Node version: 12.19.0
 - Operating system: docker/ubuntu:20.04

**Comment by thost96** [comment]
Problem still there.

**Comment by thost96** [comment]
@Apollon77 Hi, why is this issue closed without any comment? Thanks!

**Comment by Apollon77** [comment]
The comment is there ... 

Apollon77 closed this in 0e383db 14 hours ago 

Bitte version 3.4.0 versuchen
