### ISSUE TITLE
"funfact" funktioniert nicht

### ISSUE THREAD

**Issue by k1ngstire** [Apollon77/ioBroker.alexa2#546]
Wenn ich im Adapter den Button "funfact" anklicke dann sagt Alexa nur "Ich kann den Song 'tell me a funfact' nicht in deiner Musikbibliothek finden".
  

 - Adapter version: 3.3.1
 - JS-Controller version: 3.1.6
 - Node version: 12.18.4
 - Operating system: Ubuntu 20.04 minimal LXC

**Comment by Apollon77** [comment]
Was passiert wenn du eine Funfact Ansage über eine Routine machst? Geht das?

**Comment by k1ngstire** [comment]
> Was passiert wenn du eine Funfact Ansage über eine Routine machst? Geht das?

Ich kann innerhalb einer Routine nicht "funfact" auswählen.
Ich habe unter "Alexa sagt..." zur Auswahl:
"Benutzerdefiniert", "Erzähl mir eine Geschichte", "Erzähl mir einen Witz", "Guten Morgen", "Sätze...", "Singe einen Song".
[Hier ein Bild davon.](https://imgur.com/a/a8MGNks)

Wenn ich manuell zu Alexa sage "tell me a funfact" oder einfach "funfact" das jedenfalls funktioniert.

**Comment by Apollon77** [comment]
jupp, ich glaube funfact ist einfach in deutsch nicht verfügbar ... bestimmt nur in USA

**Comment by Apollon77** [comment]
added to Readme
