### ISSUE TITLE
Smart Home Devices lassen sich nicht schalten...

### ISSUE THREAD

**Issue by bclucki** [Apollon77/ioBroker.alexa2#55]
beim Versuch die Geräte zu schalten passiert rein gar nichts oder Sie werden gelöscht und ich muss den Adapter aktualisieren … :(

**Comment by Apollon77** [comment]
Ja schalten geht noch nicht. Löschen passiert wenn man den deleted Punkt auf true setzt ;-)

Duplicate zu #23
