### ISSUE TITLE
unknown device Echo Auto

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.alexa2#556]
Echo Auto
`2020-10-15 08:57:29.310  - info: alexa2.0 (7026)     Device-type:A1ETW4IXK2PYBP (CHANGE_NAME,AUDIBLE,TIMERS_AND_ALARMS,REMINDERS,AUDIO_PLAYER,SUPPORTS_LOCALE,DEREGISTER_DEVICE,AMAZON_MUSIC,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,MUSIC_SKILL,I_HEART_RADIO,SET_LOCALE,CUSTOM_ALARM_TONE,SET_TIME_ZONE,TUNE_IN,MICROPHONE,PERSISTENT_CONNECTION,KINDLE_BOOKS,DREAM_TRAINING,SOUND_SETTINGS,GOLDFISH,VOLUME_SETTING,SUPPORTS_LOCALE_SWITCH,SLEEP)
2020-10-15 08:57:29.315  - info: alexa2.0 (7026) Unknown Device, but enabling commands, Try it and report back if commands work.
2020-10-15 08:57:29.316  - info: alexa2.0 (7026) Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
`

**Comment by Apollon77** [comment]
and what works? commands? speak? ssml?

**Comment by Ilovegym66** [comment]
Thank you for this gread Adapter! 
I've tested, the adapter created every objects like an echo dot, but the commands (everythin in this folder) don't work. 
Here the capabilities:
`ACTIVE_AFTER_FRO,TUNE_IN,LAMBDA_DOWNCHANNEL,MICROPHONE,SUPPORTS_LOCALE,CHANGE_NAME,EARCONS,FAR_FIELD_WAKE_WORD,AUDIBLE,REQUIRES_OOBE_FOR_SETUP,SUPPORTS_LOCALE_SWITCH,PANDORA,SUPPORTS_CONNECTED_HOME,FLASH_BRIEFING,KINDLE_BOOKS,SUPPORTS_SOFTWARE_VERSION,PAIR_BT_SINK,REMINDERS,I_HEART_RADIO,AUDIO_PLAYER,VOLUME_SETTING,AMAZON_MUSIC,AUDIO_CONTROLS,FACTORY_RESET_DEVICE,DEREGISTER_DEVICE`

Device Type:
A303PJF6ISQ7IC

If you need more informations, give feedback, please.

**Comment by Apollon77** [comment]
SO Echo Auto already with two devicetype ids? A3.. and A1... ?!

**Comment by Ilovegym66** [comment]
looks like so.. I have only one.. with this Device Type..
