### ISSUE TITLE
Support für RangeController Interface 

### ISSUE THREAD

**Issue by ToGe3688** [Apollon77/ioBroker.alexa2#560]
Ich fände es ein ganz cooles Feature falls man für die Smarthome Devices auch das RangeController Interface implementieren könnte um diese über den Adapter zu steuern. Es gibt mittlerweile einige Skills für Heizungsanlagen welche das RangeController Interface nutzen um diese (oder zumindest einige Schaltpunkte) über Alexa steuerbar zu machen. (z.B. Wolff Lüftungs und Heizungsanlagen) Der ioBroker könnte somit über einen relative einfachen Umweg diese Anlagen steuern ohne einen eigenen Adapter zu benötigen.

**Comment by Apollon77** [comment]
Falscher Adapter! Alexa2 interagiert mit Alexa Geräten, du willst das beim iot Adapter anlegen
