### ISSUE TITLE
Echo-Devices zeigt einfach keine Geräte an

### ISSUE THREAD

**Issue by FreewareFire** [Apollon77/ioBroker.alexa2#565]
Hallo, einen schönen Abend wünsche ich. Nach zwei Tagen verzweifelter suche und mindesten 20 Neuinstallationen wende ich mich jetzt an euch. Ich habe mittlerweile 20 Seiten mit verschiedenen Anleitungen rauf und runter gespielt und komme einfach nicht mehr weiter. Mein Problem ist, dass ich einfach unter dem Adapter bei Echo-Devices meine beiden Echo Dot 3 nicht angezeigt bekomme. Das bleibt einfach leer. Zuerst habe ich mir das neuste Raspbian lite auf meinen PI4 installiert. Dann ioBroker und den Adpater. Dann im Adapter mir das Cookie geholt indem ich auf die Webseite gewechselt bin die dort angezeigt wurde. Cookie hat er sich dann auch schön brav geholt. Dann gespeichert und der Adapter ist grün. Supi habe ich gedacht. Auch keine Fehlermeldungen im Log...

Das sieht eigentlich immer so aus:

alexa2.0 | 2020-11-04 23:02:40.314 | info | (270816) Subscribing to states...
-- | -- | -- | --
alexa2.0 | 2020-11-04 23:02:39.433 | info | (270816) Alexa-Push-Connection established. Disable Polling
alexa2.0 | 2020-11-04 23:02:36.928 | info | (270816) starting. Version 3.3.1 in D:/Program Files/iobroker/SmartHome/node_modules/iobroker.alexa2, node: v10.17.0, js-controller: 3.1.6
host.DESKTOP-NU8BA74(SmartHome) | 2020-11-04 23:02:36.409 | info | instance system.adapter.alexa2.0 started with pid 270816

und das war es dann auch. Ich habe mittlerweile soviel probiert (auch mal unter Cookie im Adapter base url usw. auf Amiland etc. umgestellt). Leider ohne Erfolg. Was übersehe ich nur? Die beiden Echos sind beide im WLAN drin, funktionieren ja auch tadelos. Was für Infos benötigt ihr noch? Habe ich bei der Einrichtung etwas falsch gemacht? Raspbian, dann Update durchgeführt, neueste nodejs drauf, IOBroker drauf, dann den Adpater... Weiß jemand vielleicht warum die Echos nicht angezeigt werden? Gibt es bei Amazon Probleme das es aktuell nicht geht?

Vielen Dank für die Hilfe, wenn noch fragen offen sind, ich Antworte so schnell es geht!

**Comment by Apollon77** [comment]
Also um es genau zu checken bräuchte man ein Debug Log.

Aber eine Frage: Kann es sein das die Geräte irgendwie in anderen Amazon Accounts registriert und geshared sind oder so?

**Comment by FreewareFire** [comment]
> Also um es genau zu checken bräuchte man ein Debug Log.
> 
> Aber eine Frage: Kann es sein das die Geräte irgendwie in anderen Amazon Accounts registriert und geshared sind oder so?

Hi, ich versuche das ganze nochmal am Wochenende und hänge dann mal das Log an. Die Geräte sind nur in einem Account drin, genau mit dem wo ich mir das Cookie dann auch hole. Evtl. schaffe ich es auch vorher. Danke für die Rückmeldung!

**Comment by FreewareFire** [comment]
Hi Apollon77,

anbei mal die Log. Frisch installierter ioBroker, dann den Adapter drauf und das Cookie über die Webseite wie im Log steht geholt. Alles "Grün" beim Adapter. Nach wie vor aber keine Dots zu finden. Hoffe du kannst mir helfen.

Vielen Dank für deine Mühe!!

Gruß Ralf
[iobroker.current.log](https://github.com/Apollon77/ioBroker.alexa2/files/5543202/iobroker.current.log)

**Comment by Apollon77** [comment]
Was ist denn das fpr ein Log? Ist html?

**Comment by FreewareFire** [comment]
Ja, irgendwie hat er mir die Log so runtergeladen. Weiß auch nicht genau wieso o_O

**Comment by Apollon77** [comment]
runtergeladen? Wie? 

Bitte per ssh machen

**Comment by FreewareFire** [comment]
Runtergeladen hatte ich das über den Button im ioBroker. Habe jetzt aber die Log nochmal via SSH gezogen. Habe einfach mal eine komplette Neuinstallation des Adapters inkl. Logging gemacht. Vielleicht hatte ich ja schon vorher einen Fehler... Hier die Installation als Bild und die passende Log Datei (via SSH).
![2020-11-16 17_03_17-pi@iobroker_ ~](https://user-images.githubusercontent.com/73968953/99278364-3b654a80-282f-11eb-9a56-49ed5ad2112d.jpg)
![2020-11-16 17_03_37-pi@iobroker_ ~](https://user-images.githubusercontent.com/73968953/99278372-3d2f0e00-282f-11eb-8cf5-79c2dad2fadb.jpg)
![2020-11-16 17_03_44-pi@iobroker_ ~](https://user-images.githubusercontent.com/73968953/99278378-3f916800-282f-11eb-86e9-c2969dda0e46.jpg)
[iobroker.2020-11-16.log](https://github.com/Apollon77/ioBroker.alexa2/files/5547793/iobroker.2020-11-16.log)

**Comment by Apollon77** [comment]
ALso ich kann hier nur eins sagen. Das Log zeigt das der angegebene Accounts nur "Apps" verbunden hat und kein einziges echtes Gerät. Auch das comucicationStatus DEPROVISIONED is sehr komisch. Also an der Stelle ... Bitte unbedingt prüfen das der korrekte Amazon Account genutzt wurde wo auch wirklich die Geräte drüber eingerichtet sind
