### ISSUE TITLE
Datenpunkt history.serialNumber erhält falsche Seriennummer

### ISSUE THREAD

**Issue by Matzebhv** [Apollon77/ioBroker.alexa2#574]
Ich habe ein Script gebaut, welches anhand des o.g. Datenpunktes das angesprochene Echo-Device per Datenpunkt speak beschreibt. Hierbei ist aufgefallen, es antwortet nie das angesprochene Device sondern immer ein anderes und das wechselweise.
Ich spreche beim testen immer das selbe Gerät an, der Datenpunkt history.serialNumber enthält im Anschluss aber nicht die Seriennummer des angesprochenen Gerätes sondern immer eine andere. Sogar Nummern von ausgeschalteten Devices.

Gruß
Matthias

**Comment by Apollon77** [comment]
Wie genau nutzt du es? Wie sieht das Javascript aus? Wichtig: Bitte im JS auf den json datenpunkt reagieren und die werte daraus lesen - sonst kann es dazu kommen das die Seriennummer schon von einem anderen kommando neu gesetzt ist wenn Du es liesst.

**Comment by Matzebhv** [comment]
Moin Apollon,
ich habe das vorhin quick & dirty in einem Blockly zusammengeprügelt. Ich bau das mal auf den json-DP um, bin grad auch nicht mehr sicher ob nicht das falsche Gerät mitgelauscht hat. Ich werde Morgen berichten und bei Bedarf den Fall schließen.

**Comment by Matzebhv** [comment]
Ich hatte einen Bug im Script und trotz leise sprechen haben diverse Geräte gelauscht.
