### ISSUE TITLE
History: Datenpunkt mit aktuell ausgeführter Routine (Echo-Device übergreifend) hinzufügen

### ISSUE THREAD

**Issue by PatrickDa87** [Apollon77/ioBroker.alexa2#576]
Hi @Apollon77 

Ist es möglich in der History einen Datenpunkt hinzuzufügen, welcher die ID der Routine ausgibt, welche gerade ausgeführt wurde (Geräte-unabhängig)?

Ich würde gerne eine existierende "leere" Routine (Aktion: 5s warten) über einen Sprachbefehl ausführen --> Beispiel: "Alexa, wie viel Reichweite habe ich noch". Die Routine führt nun keine Aktion aus, sondern wartet nur.. Jedoch kann nun die KI von Alexa genutzt werden und man muss nicht über History.Summary einen Textwert vergleichen, welcher 100% exakt übereinstimmen muss, sondern nur auf true/false prüfen.

Im Blockly-Skript soll dann ein Trigger auf die Veränderung des oben genannten Datenpunkts gesetzt werden. Falls eine Veränderung erkannt wurde, soll abgefragt werden, ob der Wert einer bestimmten "Routine ID" entspricht. Falls ja, soll Alexa per Speak Befehl die Antwort ausgeben.

**Comment by Apollon77** [comment]
work already via trigger on routine states
