### ISSUE TITLE
switch into low energy mode  

### ISSUE THREAD

**Issue by zokkai** [Apollon77/ioBroker.alexa2#578]
If you press&hold command mode button and tap microfon button twice echo gets into low energy mode.  

wondering if you can set the "low power mode" for echo.dot by alexa adapter.

thx in advance

**Comment by Apollon77** [comment]
Can you do it via Alexa App? I never saw that there ... if not then also adapter has no chance. Please reopen when Alexa App can do it

**Comment by Apollon77** [comment]
Check 3.4.0 with textCommand
