### ISSUE TITLE
Cannot read property 'password' of undefined

### ISSUE THREAD

**Issue by xmace** [Apollon77/ioBroker.alexa2#58]
Somehow this happens occasionally

> alexa2.0 | 2018-08-07 08:20:46.442 | info | Proxy IP not set, use first network interface (10.0.0.3) instead
> -- | -- | -- | --
> alexa2.0 | 2018-08-07 08:20:46.429 | info | starting. Version 0.3.8 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.11.2
> host.iobroker-n8 | 2018-08-07 08:20:45.657 | info | instance system.adapter.alexa2.0 started with pid 10092
> host.iobroker-n8 | 2018-08-07 08:20:15.638 | info | Restart adapter system.adapter.alexa2.0 because enabled
> host.iobroker-n8 | 2018-08-07 08:20:15.637 | error | instance system.adapter.alexa2.0 terminated with code 0 (OK)
> Caught | 2018-08-07 08:20:15.637 | error | by controller[1]: at TCP.done [as _onclose] (_tls_wrap.js:356:7)
> Caught | 2018-08-07 08:20:15.637 | error | by controller[1]: at _handle.close (net.js:557:12)
> Caught | 2018-08-07 08:20:15.637 | error | by controller[1]: at TLSSocket.emit (events.js:211:7)
> Caught | 2018-08-07 08:20:15.637 | error | by controller[1]: at emitOne (events.js:121:20)
> Caught | 2018-08-07 08:20:15.637 | error | by controller[1]: at TLSSocket.socketCloseListener (_http_client.js:363:9)
> Caught | 2018-08-07 08:20:15.637 | error | by controller[1]: at ClientRequest.emit (events.js:211:7)
> Caught | 2018-08-07 08:20:15.637 | error | by controller[1]: at emitOne (events.js:116:13)
> Caught | 2018-08-07 08:20:15.637 | error | by controller[1]: at ClientRequest. (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:377:24)
> Caught | 2018-08-07 08:20:15.637 | error | by controller[1]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:392:16
> Caught | 2018-08-07 08:20:15.637 | error | by controller[1]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:283:53
> Caught | 2018-08-07 08:20:15.637 | error | by controller[1]: TypeError: Cannot read property 'password' of undefined
> Caught | 2018-08-07 08:20:15.636 | error | by controller[0]: at _combinedTickCallback (internal/process/next_tick.js:138:11)
> Caught | 2018-08-07 08:20:15.636 | error | by controller[0]: at emitErrorNT (internal/streams/destroy.js:64:8)
> Caught | 2018-08-07 08:20:15.636 | error | by controller[0]: at TLSSocket.emit (events.js:211:7)
> Caught | 2018-08-07 08:20:15.636 | error | by controller[0]: at emitOne (events.js:116:13)
> Caught | 2018-08-07 08:20:15.636 | error | by controller[0]: at TLSSocket.socketErrorListener (_http_client.js:387:9)
> Caught | 2018-08-07 08:20:15.636 | error | by controller[0]: at ClientRequest.emit (events.js:211:7)
> Caught | 2018-08-07 08:20:15.636 | error | by controller[0]: at emitOne (events.js:116:13)
> Caught | 2018-08-07 08:20:15.636 | error | by controller[0]: at ClientRequest. (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:377:24)
> Caught | 2018-08-07 08:20:15.636 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:392:16
> Caught | 2018-08-07 08:20:15.636 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:283:53
> Caught | 2018-08-07 08:20:15.635 | error | by controller[0]: TypeError: Cannot read property 'password' of undefined
> alexa2.0 | 2018-08-07 08:20:15.609 | warn | Exception: TypeError: Cannot read property 'password' of undefined
> alexa2.0 | 2018-08-07 08:20:15.609 | error | at TCP.done [as _onclose] (_tls_wrap.js:356:7)
> alexa2.0 | 2018-08-07 08:20:15.609 | error | at _handle.close (net.js:557:12)
> alexa2.0 | 2018-08-07 08:20:15.609 | error | at TLSSocket.emit (events.js:211:7)
> alexa2.0 | 2018-08-07 08:20:15.609 | error | at emitOne (events.js:121:20)
> alexa2.0 | 2018-08-07 08:20:15.609 | error | at TLSSocket.socketCloseListener (_http_client.js:363:9)
> alexa2.0 | 2018-08-07 08:20:15.609 | error | at ClientRequest.emit (events.js:211:7)
> alexa2.0 | 2018-08-07 08:20:15.609 | error | at emitOne (events.js:116:13)
> alexa2.0 | 2018-08-07 08:20:15.609 | error | at ClientRequest. (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:377:24)
> alexa2.0 | 2018-08-07 08:20:15.609 | error | at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:392:16
> alexa2.0 | 2018-08-07 08:20:15.609 | error | at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:283:53
> alexa2.0 | 2018-08-07 08:20:15.609 | error | TypeError: Cannot read property 'password' of undefined
> alexa2.0 | 2018-08-07 08:20:15.609 | error | uncaught exception: Cannot read property 'password' of undefined
> alexa2.0 | 2018-08-07 08:20:15.605 | warn | Exception: TypeError: Cannot read property 'password' of undefined
> alexa2.0 | 2018-08-07 08:20:15.603 | error | at _combinedTickCallback (internal/process/next_tick.js:138:11)
> alexa2.0 | 2018-08-07 08:20:15.603 | error | at emitErrorNT (internal/streams/destroy.js:64:8)
> alexa2.0 | 2018-08-07 08:20:15.603 | error | at TLSSocket.emit (events.js:211:7)
> alexa2.0 | 2018-08-07 08:20:15.603 | error | at emitOne (events.js:116:13)
> alexa2.0 | 2018-08-07 08:20:15.603 | error | at TLSSocket.socketErrorListener (_http_client.js:387:9)
> alexa2.0 | 2018-08-07 08:20:15.603 | error | at ClientRequest.emit (events.js:211:7)
> alexa2.0 | 2018-08-07 08:20:15.603 | error | at emitOne (events.js:116:13)
> alexa2.0 | 2018-08-07 08:20:15.603 | error | at ClientRequest. (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:377:24)
> alexa2.0 | 2018-08-07 08:20:15.603 | error | at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:392:16
> alexa2.0 | 2018-08-07 08:20:15.603 | error | at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:283:53
> alexa2.0 | 2018-08-07 08:20:15.603 | error | TypeError: Cannot read property 'password' of undefined
> alexa2.0 | 2018-08-07 08:20:15.602 | error | uncaught exception: Cannot read property 'password' of undefined

**Comment by Apollon77** [comment]
duplicate zu #57
