### ISSUE TITLE
Echo Show 5 hat keine Commands Möglichkeiten

### ISSUE THREAD

**Issue by Bastler1971** [Apollon77/ioBroker.alexa2#580]
Es fehlen leider sämtliche Commands, leider auch speak somit

**Comment by Apollon77** [comment]
Wie lautet die deviceType und capabilities? Was steht so im Log wenn der Adapter startet?

**Comment by Bastler1971** [comment]
bei capabilities:

DREAM_TRAINING,DS_VOLUME_SETTING,TIDAL,AUDIBLE,TIMERS_AND_ALARMS,I_HEART_RADIO,PAIR_BT_SINK,ALEXA_PRESENCE,CUSTOM_ALARM_TONE,FAR_FIELD_WAKE_WORD,VOICE_TRAINING,PANDORA,EQUALIZER_CONTROLLER_MIDRANGE,VOLUME_SETTING,SLEEP,EFDCARDS,AMAZON_MUSIC,KINDLE_BOOKS,ASCENDING_ALARM_VOLUME,EQUALIZER_CONTROLLER_BASS,SALMON,SHARKNADO,SUPPORTS_LOCALE,PERSISTENT_CONNECTION,MUSIC_SKILL,DEEZER,AUDIO_CONTROLS,MULTI_WAKEWORDS_SUPPORTED,REMINDERS,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,MICROPHONE,SOUND_SETTINGS,DIALOG_INTERFACE_VERSION,SIRIUSXM,SET_LOCALE,EARCONS,FLASH_BRIEFING,APPLE_MUSIC,LEMUR_ALPHA,FACTORY_RESET_DEVICE,SUPPORT_CALENDAR_ALERT,SUPPORTS_SOFTWARE_VERSION,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,SUPPORTS_LOCALE_SWITCH,AUDIO_PLAYER,CHANGE_NAME,TUNE_IN,GOLDFISH,GUARD_EARCON,EQUALIZER_CONTROLLER_TREBLE

bei deviceType:

A4ZP7ZC4PI6TO

**Comment by Bastler1971** [comment]
Kann geschlossen werden....
Habe Adapter neu gestartet und alles war da!
