### ISSUE TITLE
Echo Dot 4. Generation not working with Alexa2 => Unkown Device

### ISSUE THREAD

**Issue by lastoks** [Apollon77/ioBroker.alexa2#584]
Hi,
Echo Dot Gen. 4 is listen as unkown device.
The State online is false. The device objects are created but have no function.

Here is the Log:
`
alexa2.0 | 2020-12-02 12:35:53.078 | info | (31066)      Device-type:XXXXXXXXXXXX  (ACTIVE_AFTER_FRO,SLEEP,TAHOE_BYOD,SALMON,GOLDFISH,EQUALIZER_CONTROLLER_TREBLE,PERSISTENT_CONNECTION,KINDLE_BOOKS,SET_LOCALE,APPLE_MUSIC,AUDIO_PLAYER,SUPPORTS_LO
-- | -- | -- | --
alexa2.0 | 2020-12-02 12:35:53.078 | info | (31066)  Report to developer as GitHub issue with details for device. Please  grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-12-02 12:35:53.078 | info | (31066) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-12-02 12:35:53.074 | info | (31066)      Device-type:XXXXXXXXXXXXXX  (CUSTOM_ALARM_TONE,REMINDERS,MICROPHONE,SOUND_SETTINGS,ASX_TIME_ZONE,PERSISTENT_CONNECTION,SUPPORTS_SOFTWARE_VERSION,VOLUME_SETTING,SUPPORTS_LOCALE_SWITCH,SUPPOR
alexa2.0 | 2020-12-02 12:35:53.074 | info | (31066)  Report to developer as GitHub issue with details for device. Please  grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-12-02 12:35:53.074 | info | (31066) Unknown Device, but enabling commands, Try it and report back if commands work.
`

**Comment by Apollon77** [comment]
Closed why? Working now?

**Comment by lastoks** [comment]
Yes, it is working. Was my mistake. I chosse the wrong device with the same name.
