### ISSUE TITLE
Echo-Devices.xyz.Music-Provider.  is invalid. Ids are not allowed to end in "."

### ISSUE THREAD

**Issue by JanWeskamp** [Apollon77/ioBroker.alexa2#585]
alexa2.0 | 2020-12-03 03:14:03.979 | error | at processImmediate (internal/timers.js:461:21)
-- | -- | -- | --
alexa2.0 | 2020-12-03 03:14:03.979 | error | at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2354:71)
alexa2.0 | 2020-12-03 03:14:03.979 | error | at /opt/iobroker/node_modules/iobroker.alexa2/main.js:352:25
alexa2.0 | 2020-12-03 03:14:03.979 | error | at Adapter.setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1817:40)
alexa2.0 | 2020-12-03 03:14:03.979 | error | (5396) The "Echo-Devices.xyz.Music-Provider." is invalid. Ids are not allowed to end in "."

**Comment by Apollon77** [comment]
Interesting. I will catch that case ... but still do not udnerstand why a music provider is present with an empty name :-)

**Comment by ds-1982** [comment]
Wird nicht viel helfen: Ich habe auch das Problem.

Gestern hatte ich die Meldung nur bei zwei Geräten. Jetzt erscheint die Fehlermeldung bei allen Geräten im Log.

**Comment by Speedbreaker12** [comment]
Bei mir dasselbe und ich kann keine Smarthome devices mehr steuern.

**Comment by Apollon77** [comment]
Dann klingt das eher mal wieder nach nem Amazon fuckup ... Wie gesgt den einen Fehler prüfe ich ... 
Ansonsten: Geht die Steuerung der Geräte per alexa App noch?

**Comment by Speedbreaker12** [comment]
> 
> 
> Dann klingt das eher mal wieder nach nem Amazon fuckup ... Wie gesgt den einen Fehler prüfe ich ...
> Ansonsten: Geht die Steuerung der Geräte per alexa App noch?

Gerade getestet, du hast recht das sieht wirklich wieder nach Amazon Fuckup aus! Geräte an und aus funktioniert zwar in der App, aber Szenen schalten auch nicht mehr.

**Comment by Apollon77** [comment]
Dan last mal nen tag warten ... und meldet den Fehler an amazon (also den w as in der App net geht). :-)

**Comment by M1cS0w** [comment]
Wollte gestern bereits aufmachen. Dasselbe Problem bei mir:
Und dieser für einen Echo der nun seit 5 Tagen nicht mehr online ware, weil vom Strom. Bisher nur bei den beiden die Meldung.
`(1094) The "Echo-Devices.G090VC0784072220.Music-Provider." is invalid. Ids are not allowed to end in "." at Adapter.setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1817`
Dieser Eintrag ist für Überall
`(1094) The "Echo-Devices.xxxxxxxxxxxxxxxxxxxxxxxxx.Music-Provider." is invalid. Ids are not allowed to end in "." at Adapter.setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib`

**Comment by rnc11** [comment]
Ich hab dasselbe Problem.

**Comment by kthofmann** [comment]
Habe das Problem ebenfalls seit heute. Falls notwendig kann ich gern weiteren Input liefern.

**Comment by Speedbreaker12** [comment]
Ich nehm zurück was ich heute morgen geschrieben habe, in der Alexa App funktioniert es Szenen zu aktivieren, über den Alexa2 Adapter nicht mehr. Es passiert einfach garnichts und es steht auch nichts im log, außer der Fehler hier in der Beschreibung.
![szene](https://user-images.githubusercontent.com/18654629/101025927-88a72300-3576-11eb-9bee-b9a3f860e12c.JPG)

**Comment by Evilghost12** [comment]
Selbe Problem. Hab auf dem Hyper-V Debian laufen. Gott sei dank hab ich mir einen Snapshot gemacht. Wenn ich den Alexa2.0 Adapter neu starte und er die Cookies von heute abholt - geht nichts mehr. Keine Routine ansteuerbar - eben nichts. Wenn ich den Snapshot Rückspiele wo die Cookies vom 27.11. sind funktioniert alles wunderbar. Vielleicht hilf das jemanden

**Comment by m0rph2k** [comment]
gleicher fehler beim Starten des adapters

**Comment by kthofmann** [comment]
> Selbe Problem. Hab auf dem Hyper-V Debian laufen. Gott sei dank hab ich mir einen Snapshot gemacht. Wenn ich den Alexa2.0 Adapter neu starte und er die Cookies von heute abholt - geht nichts mehr. Keine Routine ansteuerbar - eben nichts. Wenn ich den Snapshot Rückspiele wo die Cookies vom 27.11. sind funktioniert alles wunderbar. Vielleicht hilf das jemanden. Version Alexa2.0 3.3.1

Wo ich das grad lesen ... ich glaub das Problem ist bei mir auch erst nach dem manuellen Neustart des Alexa Adapters aufgetreten. Es fehlte ein neu in Alexa angelerntes Device im ioBroker und durch einen Neustart wollte ich die aktuelle Deviceliste ziehen lassen - im Anschluss trat oben gemeldeter Fehler auf.

**Comment by Evilghost12** [comment]
> > Selbe Problem. Hab auf dem Hyper-V Debian laufen. Gott sei dank hab ich mir einen Snapshot gemacht. Wenn ich den Alexa2.0 Adapter neu starte und er die Cookies von heute abholt - geht nichts mehr. Keine Routine ansteuerbar - eben nichts. Wenn ich den Snapshot Rückspiele wo die Cookies vom 27.11. sind funktioniert alles wunderbar. Vielleicht hilf das jemanden. Version Alexa2.0 3.3.1
> 
> Wo ich das grad lesen ... ich glaub das Problem ist bei mir auch erst nach dem manuellen Neustart des Alexa Adapters aufgetreten. Es fehlte ein neu in Alexa angelerntes Device im ioBroker und durch einen Neustart wollte ich die aktuelle Deviceliste ziehen lassen - im Anschluss trat oben gemeldeter Fehler auf.

Genau... Habe auch versucht den Adapter komplett zu löschen und neu anzulegen.  - Dann zieht er nur ein paar Devices aber lang nicht alles. Das muss der Entwickler des Adapters bitte mal ansehen. 👍

**Comment by thriwb** [comment]
Auch ich kann das Problem bestätigen. Nach Neuinstallation des Adapters fehlen alle Echo Geräte und auch der History Eintrag. Witzigerweise funktionieren meine Skripte noch, die auf alexa2.0.History.summary zugreifen, auch wenn ich den Datenpunkt nicht mehr auswählen kann.

**Comment by ToBro14** [comment]
Ich habe auch den selben Fehler mit der Meldung bezgl. Music Provider seit ich meinen Raspberry Pi Heute neugestartet habe.

**Comment by skue-hash** [comment]
ebenfalls :(

**Comment by Stefan592** [comment]
Vorschlag für schnelle Hilfe: Füge unter Zeile 1600 eine Prüfung auf länge hinzu:
`if (musicProviders[p].length <= 0) continue;`

Ich hoffe es ist die richtige Zeile, habe den Code nur überflogen. Ansonsten gute Arbeit, nutze den Adapter seit einigen Monaten ohne Probleme (Bis auf dieses jetzt :D)

**Comment by Speedbreaker12** [comment]
> 
> 
> Vorschlag für schnelle Hilfe: Füge unter Zeile 1600 eine Prüfung auf länge hinzu:
> `if (musicProviders[p].displayName.length <= 0) continue;`
> 
> Ich hoffe es ist die richtige Zeile, habe den Code nur überflogen. Ansonsten gute Arbeit, nutze den Adapter seit einigen Monaten ohne Probleme (Bis auf dieses jetzt :D)

Das unterdrückt zwar den Fehler im Log, ändert aber nichts daran, dass der gesamte Adapter nicht mehr funktioniert. :-(
Irgendwas stimmt da von Amazon Seite ganz gewaltig nicht.

**Comment by Apollon77** [comment]
fixed in 3.3.5

**Comment by Apollon77** [comment]
Also bei mir tut speak und so noch, aber ja Smart Devices eher nicht

**Comment by Speedbreaker12** [comment]
> 
> 
> Also bei mir tut speak und so noch, aber ja Smart Devices eher nicht

Seit 0 Uhr funktioniert bei mir auch alles wieder, inklusive alles Smarthome Geräte!

**Comment by thriwb** [comment]
Alle Echo-Geräte und der History-Eintrag sind wieder da. Speak und die anderen Echo-Kommandos funktionieren nach Update auf 3.3.5 wieder. Vielen Dank an @Apollon77!

**Comment by Evilghost12** [comment]
Ja kann ich bestätigen.. mit 3.3.5 alles wieder wie gewohnt... Vielen DANK @Apollon77  👍

**Comment by mcbirne** [comment]
Bei mir funktioniert es noch nicht wieder. Ich habe den neuen Adapter installiert. Aber Sprachausgaben Funktion ieren noch nicht.

**Comment by Apollon77** [comment]
Wo ausgaben nicht funktionieren ... normale devices oder Sonos? Gibt Berichte das Sonos mal wieder nicht tut ... wäre dann mal wieder Amazon. Also bei mir tuen die ausgaben

**Comment by m0rph2k** [comment]
Danke, funktioniert wieder alles auch die Sprachausgabe

**Comment by mcbirne** [comment]
Bei mir ist es ein Echo Studio. Habt ihr noch etwas gemacht, außer den neuen Adapter installiert?

**Comment by m0rph2k** [comment]
> 
> 
> Bei mir ist es ein Echo Studio. Habt ihr noch etwas gemacht, außer den neuen Adapter installiert?

Nur geupdatet

**Comment by Evilghost12** [comment]
Ebenfalls nur Update eingespielt...

**Comment by Evilghost12** [comment]
> Bei mir ist es ein Echo Studio. Habt ihr noch etwas gemacht, außer den neuen Adapter installiert?

Was heisst neu installiert... Du gehst auf die Adapter dann auf die kleine GitHub Katze dort Alexa2 auswählen installieren fertig... Du brauchst den "alten" Adapter nicht vorher löschen... Nachher siehst du unter den Adaptern installiert 3.3.5 - verfügbar 3.3.1

**Comment by M1cS0w** [comment]
Super schnelle Leistung. Respekt und vielen Dank es lüppt wieder auch speak funktioniert nun über ssml :)

**Comment by mcbirne** [comment]
Klappt bei mir jetzt auch wieder. Danke für das schnelle Update.
