### ISSUE TITLE
Hisense 55U8QF TV - device report

### ISSUE THREAD

**Issue by pandel** [Apollon77/ioBroker.alexa2#586]
(4786) Device-type:A3FLQ0Q75I0GEG (PERSISTENT_CONNECTION,SIRIUSXM,DREAM_TRAINING,AMAZON_MUSIC,TIMERS_AND_ALARMS,VOLUME_SETTING,SLEEP,REMINDERS,SOUND_SETTINGS,CUSTOM_ALARM_TONE,DEEZER,TIDAL,I_HEAR

**Comment by Apollon77** [comment]
What can it do? Are Commands working?
