### ISSUE TITLE
Device.Music-Provider. is invalid

### ISSUE THREAD

**Issue by JBehnke87** [Apollon77/ioBroker.alexa2#587]
Hallo,

seit einem Neustart des ioBrokers habe ich Probleme mit dem Adapter. Der Adapter war verbunden, hat aber keine Commands mehr ausgeführt (speak, music-provider, etc.), hat aber Signale empfangen wenn per Sprache bedient wurde. Danach habe ich versucht die Cookies zu erneuern, anschließend habe ich den ganzen Adapter gelöscht und neuinstalliert. Jetzt bekomme ich folgende Meldung, welche auch schon vor dem Reset vorkam, allerdings werden jetzt zusätzlich nichtmehr alle Geräte importiert und es können weiterhin keine Commands an die beiden Geräte gesendet werden.

alexa2.0 | 2020-12-04 11:08:12.568 | error | at process.topLevelDomainCallback (domain.js:126:23)
-- | -- | -- | --
alexa2.0 | 2020-12-04 11:08:12.568 | error | at processImmediate (timers.js:658:5)
alexa2.0 | 2020-12-04 11:08:12.568 | error | at tryOnImmediate (timers.js:676:5)
alexa2.0 | 2020-12-04 11:08:12.568 | error | at runCallback (timers.js:705:18)
alexa2.0 | 2020-12-04 11:08:12.568 | error | at Immediate.callback.function.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2354:71)
alexa2.0 | 2020-12-04 11:08:12.568 | error | at adapter.getObject (/opt/iobroker/node_modules/iobroker.alexa2/main.js:352:25)
alexa2.0 | 2020-12-04 11:08:12.568 | error | at Adapter.setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1817:40)
alexa2.0 | 2020-12-04 11:08:12.568 | error | (20307) The "Echo-Devices.G090P3.....04WH.Music-Provider." is invalid. Ids are not allowed to end in "."
alexa2.0 | 2020-12-04 11:08:09.158 | error | at process.topLevelDomainCallback (domain.js:126:23)
alexa2.0 | 2020-12-04 11:08:09.158 | error | at processImmediate (timers.js:658:5)
alexa2.0 | 2020-12-04 11:08:09.158 | error | at tryOnImmediate (timers.js:676:5)
alexa2.0 | 2020-12-04 11:08:09.158 | error | at runCallback (timers.js:705:18)
alexa2.0 | 2020-12-04 11:08:09.158 | error | at Immediate.callback.function.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2354:71)
alexa2.0 | 2020-12-04 11:08:09.158 | error | at adapter.getObject (/opt/iobroker/node_modules/iobroker.alexa2/main.js:352:25)
alexa2.0 | 2020-12-04 11:08:09.158 | error | at Adapter.setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1817:40)
alexa2.0 | 2020-12-04 11:08:09.158 | error | (20307) The "Echo-Devices.G09....51625SC.Music-Provider." is invalid. Ids are not allowed to end in "."
alexa2.0 | 2020-12-04 11:07:59.764 | info | (20307) Alexa-Push-Connection established. Disable Polling
alexa2.0 | 2020-12-04 11:07:59.744 | info | (20307) Device-type:A1ZB65LA390I4K (REMINDERS,NO_TIME_ZONE_SETTING,ASX_TIME_ZONE,ASCENDING_ALARM_VOLUME,DIALOG_INTERFACE_VERSION,VOLUME_SETTING,SUPPORTS_LOCALE_SWITCH,MICROPHONE,TIMERS_AND_ALARMS
alexa2.0 | 2020-12-04 11:07:59.743 | info | (20307) Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-12-04 11:07:59.742 | info | (20307) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-12-04 11:07:59.733 | info | (20307) Device-type:AVU7CPPF2ZRAS (MICROPHONE,TIMERS_AND_ALARMS,PERSISTENT_CONNECTION,REMINDERS,NO_TIME_ZONE_SETTING,SUPPORTS_SOFTWARE_VERSION,ASX_TIME_ZONE,VOLUME_SETTING)
alexa2.0 | 2020-12-04 11:07:59.732 | info | (20307) Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-12-04 11:07:59.731 | info | (20307) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-12-04 11:07:59.727 | info | (20307) Device-type:A265XOI9586NML (FLASH_BRIEFING,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,REMINDERS,CHANGE_NAME,ASCENDING_ALARM_VOLUME,DIALOG_INTERFACE_VERSION,VOLUME_SETTING,SUPPORTS_LOCALE_SWITCH,M
alexa2.0 | 2020-12-04 11:07:59.726 | info | (20307) Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-12-04 11:07:59.725 | info | (20307) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-12-04 11:07:56.615 | info | (20307) Proxy IP not set, use first network interface (192.168.178.54) instead
alexa2.0 | 2020-12-04 11:07:56.489 | info | (20307) starting. Version 3.3.1 in /opt/iobroker/node_modules/iobroker.alexa2, node: v10.23.0, js-controller: 3.1.6

**Comment by JBehnke87** [comment]
Das Problem taucht anscheinend bei verschiedenen Geräten auf, ich habe die Geräte aus Alexa entfernt, jetzt werden andere Geräte erkannt, mit dem gleichen Fehler. Aber es werden trotzdem wieder nicht alle Geräte importiert.

**Comment by JBehnke87** [comment]
Also ich war gerade mal so mutig und habe die neueste Version von Github gezogen, ich hoffe es geht dadurch nichts anderes schief. Die Geräte sind alle wieder da. Es taucht trotzdem diese Meldung im Log auf:

alexa2.0 | 2020-12-04 12:37:37.199 | info | (5515) Device-type:A1ZB65LA390I4K (DIALOG_INTERFACE_VERSION,CUSTOM_ALARM_TONE,SOUND_SETTINGS,ASCENDING_ALARM_VOLUME,REMINDERS,TIMERS_AND_ALARMS,MICROPHONE,ASX_TIME_ZONE,SUPPORTS_LOCALE_SWITCH,SUPP
-- | -- | -- | --
alexa2.0 | 2020-12-04 12:37:37.198 | info | (5515) Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-12-04 12:37:37.197 | info | (5515) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-12-04 12:37:37.192 | info | (5515) Device-type:AVU7CPPF2ZRAS (TIMERS_AND_ALARMS,MICROPHONE,ASX_TIME_ZONE,SUPPORTS_SOFTWARE_VERSION,NO_TIME_ZONE_SETTING,PERSISTENT_CONNECTION,REMINDERS,VOLUME_SETTING)
alexa2.0 | 2020-12-04 12:37:37.191 | info | (5515) Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-12-04 12:37:37.190 | info | (5515) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-12-04 12:37:37.184 | info | (5515) Device-type:A265XOI9586NML (DIALOG_INTERFACE_VERSION,ACTIVE_AFTER_FRO,CUSTOM_ALARM_TONE,SOUND_SETTINGS,ASCENDING_ALARM_VOLUME,REMINDERS,TIMERS_AND_ALARMS,FLASH_BRIEFING,SUPPORTS_CONNECTED_H
alexa2.0 | 2020-12-04 12:37:37.184 | info | (5515) Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2020-12-04 12:37:37.183 | info | (5515) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2020-12-04 12:37:37.014 | info | (5515) Alexa-Push-Connection established. Disable Polling
alexa2.0 | 2020-12-04 12:37:34.150 | info | (5515) Proxy IP not set, use first network interface (192.168.178.54) instead
alexa2.0 | 2020-12-04 12:37:34.057 | info | (5515) starting. Version 3.3.5 in /opt/iobroker/node_modules/iobroker.alexa2, node: v10.23.0, js-controller: 3.1.6

**Comment by lastoks** [comment]
Kann mich @JBehnke87 nur anschließen. Hatte das gleiche Problem, mit der aktuellen Version von GitHub funktioniert es wieder.

**Comment by MartinSchlender** [comment]
Bei mir auch das Problem, dass seit heute nichts mehr an Alexa gesendet werden kann (Speak, Announcement etc. sind tot)

Hier das Log:

2020-12-05 13:20:53.359 - error: alexa2.0 (25665) The "Echo-Devices.f2516e3160ee41159586367bc1238148.Music-Provider." is invalid. Ids are not allowed to end in "."
--
at Adapter.setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1817:40)
at /opt/iobroker/node_modules/iobroker.alexa2/main.js:352:25
at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2354:71)
at processImmediate (internal/timers.js:456:21)
2020-12-05 13:20:54.153 - error: alexa2.0 (25665) The "Echo-Devices.G2A1A60304240907.Music-Provider." is invalid. Ids are not allowed to end in "."
at Adapter.setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1817:40)
at /opt/iobroker/node_modules/iobroker.alexa2/main.js:352:25
at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2354:71)
at processImmediate (internal/timers.js:456:21)

Gruß
Martin

**Comment by MartinSchlender** [comment]
Ahhh - gerade kam die Meldung dass es ein Adapter Update gibt :-) Danke für den schnellen Fix...
Gruß
Martin
