### ISSUE TITLE
4.Generation

### ISSUE THREAD

**Issue by crunchip77** [Apollon77/ioBroker.alexa2#590]
Nachdem ich im Forum gelesen habe https://forum.iobroker.net/post/532045, war ich mal so frei, hoffe es passt
![amazon-echo-4](https://user-images.githubusercontent.com/41550245/101262930-416d8d80-3742-11eb-9fa2-d4d0eff980dc.jpg)
![amazon-echo-dot-mit-uhr-blaugrau](https://user-images.githubusercontent.com/41550245/101262931-42062400-3742-11eb-885e-a7f7da6ecbd9.jpg)

Habe einen Echo 4 mit Uhr, das wäre

A2H4LV5GIZ1JFT

**Comment by Apollon77** [comment]
Can you send the capabilities too please

**Comment by crunchip77** [comment]
ACTIVE_AFTER_FRO,SLEEP,TAHOE_BYOD,DISPLAY_ADAPTIVE_BRIGHTNESS,EQUALIZER_CONTROLLER_MIDRANGE,SALMON,VOLUME_SETTING,GOLDFISH,MULTI_WAKEWORDS_SUPPORTED,ALEXA_PRESENCE,PERSISTENT_CONNECTION,KINDLE_BOOKS,SET_LOCALE,APPLE_MUSIC,AUDIO_PLAYER,AMAZON_MUSIC,DS_VOLUME_SETTING,SUPPORTS_LOCALE,MOTION_DETECTION,EQUALIZER_CONTROLLER_BASS,SIRIUSXM,MICROPHONE,MUSIC_SKILL,DEEZER,AUDIO_CONTROLS,POPTART,CUSTOM_ALARM_TONE,SUPPORTS_LOCALE_SWITCH,PAIR_BT_SINK,DREAM_TRAINING,EARCONS,DIALOG_INTERFACE_VERSION,BT_PAIRING_FLOW_V2,DEREGISTER_DEVICE,EFDCARDS,TIMERS_AND_ALARMS,REQUIRES_OOBE_FOR_SETUP,EQUALIZER_CONTROLLER_TREBLE,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,SUPPORT_CALENDAR_ALERT,CLOCK_FORMAT_24_HR,TUNE_IN,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,TUPLE,ALEXA_GESTURES,DISPLAY_BRIGHTNESS_ADJUST,UPDATE_WIFI,TUPLE_CATEGORY_A,SET_TIME_ZONE,ASCENDING_ALARM_VOLUME,PAIR_BT_SOURCE,GADGETS,CHANGE_NAME,VOICE_TRAINING,REMINDERS,SOUND_SETTINGS,I_HEART_RADIO,DISPLAY_POWER_TOGGLE,AUDIBLE,FLASH_BRIEFING,GUARD_EARCON,SUPPORTS_SOFTWARE_VERSION,FAR_FIELD_WAKE_WORD,PANDORA,TIDAL,LEMUR_ALPHA

**Comment by Lucifor1976** [comment]
Und das ganze freigestellt. Ich bin allerdings kein freistellexperte!
PNG und PDF

![AmzEcho4Gen](https://user-images.githubusercontent.com/67290625/101273947-5249ed80-379a-11eb-9c62-92f8cec8b992.png)
[AmzEcho4Gen.pdf](https://github.com/Apollon77/ioBroker.alexa2/files/5648406/AmzEcho4Gen.pdf)

**Comment by Apollon77** [comment]
Danke!!
