### ISSUE TITLE
Ring Adapter Fehlermeldung

### ISSUE THREAD

**Issue by Jeba0815** [Apollon77/ioBroker.alexa2#591]
Logfile von Ring Doorbell Adapter

27244) Error: Could not get devices in getAllRingsDevices(). Error: Could not get all doorbell devices in getAllRingsDeviceObjects(). Error: Could not get device i

 - Adapter version: 3.5.5
 - JS-Controller version: 12.20.0
 - Node version: 6.14.8
 - Operating system: Raspian auf Rock64

**Comment by Apollon77** [comment]
wrong adapter for this issue?!
