### ISSUE TITLE
Fehlermeldung beim Ändern der Laustärke

### ISSUE THREAD

**Issue by mcbirne** [Apollon77/ioBroker.alexa2#592]
Wenn ich die Lautsärtke ändere, wird dies gemacht, aber es erscheinen Fehlermeldungen im Logfile.
![logfile](https://user-images.githubusercontent.com/38691204/101277335-fee49900-37b3-11eb-9ce1-b273b6b02df3.PNG)

Das Skript sieht so aus. Eigentlich sollte damit eine Zahl und kein String übergeben werden.
![Skript](https://user-images.githubusercontent.com/38691204/101277359-35baaf00-37b4-11eb-8745-612e32c37ecd.PNG)

**Comment by Apollon77** [comment]
Naja wenn der Adapter sagt das ein String anstelle einer Zahl ankommt ist das erstmal so.

Zeige mal das Javacript was dein blockly generiert ... aber wenn eher ein Blockly bug.
(bzw warum du einen strsing in eine zahl castest anstelle gleich einen Zahlen Baustein zu nehmen versteh ich auch nicht :-)

**Comment by mcbirne** [comment]
Stimmt, unter Mathe gibt es auch die Möglichkeit direkt eine Zahl einzugeben. Damit funktioniert es auch. Danke.
