### ISSUE TITLE
Add Reminder date field

### ISSUE THREAD

**Issue by RoFrie** [Apollon77/ioBroker.alexa2#593]
alexa2.0.Echo-Devices.Serialnumber.Reminder.**date**

The reminder in Alexa needs two fields to enter time AND **date**.
The adapter has no field to see or enter the date information analog to the existing time field.

**_Please add the date field._**

Already defined time field:
| time| Time for reminder. Overwrite the time for existing reminder to set a new time | Time Input | In case you have an existing reminder you can change the time here by simply overwrite the time in format hh:mm:ss, seconds are not needed to set |

Missing date field:
| date| Date for reminder. Overwrite the date for existing reminder to set a new date| Date Input | In case you have an existing reminder you can change the date here by simply overwrite the date in format YYYY/mm/dd|

Thx
Rolf Friedrich

**Comment by Apollon77** [comment]
Missing is relative :-) The feature was implemented whewre Reminders where not to set for longer then 24h, so no "Date" was needed". So it is a feature request.

**Comment by RoFrie** [comment]
Sorry, didn't know that. Thx a lot.

**Comment by Apollon77** [comment]
The next version should have something more ... check then out again... I post when I release

**Comment by Apollon77** [comment]
have fun https://forum.iobroker.net/post/824793
