### ISSUE TITLE
Echo-Dot3 und Echo-Dot4 Unterschiedliche Anzeige

### ISSUE THREAD

**Issue by guergen1** [Apollon77/ioBroker.alexa2#595]
Hallo,

beim Echo 3 sind die Selben DP anders gefüllt:
Echo3:
![grafik](https://user-images.githubusercontent.com/34395245/101942986-ae719f00-3bea-11eb-9f98-2471d666a327.png)
Echo 4:
![grafik](https://user-images.githubusercontent.com/34395245/101943059-c517f600-3bea-11eb-9065-50bf627811c1.png)

In der V 3.3.5 war es ebenso wie jetzt in der V3.4.0

**Comment by Apollon77** [comment]
Honestly ... then Amazon is returnng the values differently on these devices. Sorry, but I can not do anything against that.

Is the display in the Alexa App the same?

**Comment by guergen1** [comment]
Ok, i´ve checked it, in the Alexa-App this is the same!
