### ISSUE TITLE
Push Verbindung sehr langsam

### ISSUE THREAD

**Issue by Wlad2288** [Apollon77/ioBroker.alexa2#596]
Hallo @Apollon77,

Erstmal vielen Dank für die Arbeit!

Ich nutze das alexa2.0.History.summary Feld, um in meinem Heimnetz Automatisierungen zu steuern.
Seit ca. 2 Wochen habe ich jedoch festgestellt, dass die Push-Verbindung sehr langsam geworden ist.
Es dauert immer 5-8 Sekunden, bis das alexa2.0.History.summary Feld aktualisiert wird.

Im Log sehe ich keine Errors:
![image](https://user-images.githubusercontent.com/76042387/102215544-23d6bb80-3eda-11eb-9cfd-c23280d89132.png)

Ich nutze den Adapter in ioBroker auf einem Synology NAS via Docker.
Lief immer problemlos.

Woran könnte das liegen?

Vielen Dank im Voraus,
Wlad

**Comment by Apollon77** [comment]
Naja die Daten kommen von Amazon rein ... DU kannst gern den Adapter auf Debug Log stellen, dann siehst Du sehr genau was wann ankommt. Der adaoter aktualisiert quasi sofort sobald Daten Ankommen.
