### ISSUE TITLE
Support "speak" for fire tv stick (*non* 4K) and mobile phone

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#598]
Both support speak from within a routine, but canot be controlled by the adapter, as there us no "commands" folder with the "speak" object.

Fire tv stick
A2LWARUGJLBYEW
ACTIVE_AFTER_FRO,ARTHUR_TARGET,CHANGE_NAME,MICROPHONE,CUSTOM_ALARM_TONE,REMINDERS,SOUND_SETTINGS,SUPPORTS_LOCALE_SWITCH,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,PERSISTENT_CONNECTION,FLASH_BRIEFING,SUPPORTS_SOFTWARE_VERSION,SUPPORTS_LOCALE,DIALOG_INTERFACE_VERSION,TIMERS_AND_ALARMS,ASCENDING_ALARM_VOLUME,VOLUME_SETTING

Mobile phone (aka "this device")
A2TF17PFR55MTB
MICROPHONE,DIALOG_INTERFACE_VERSION,CUSTOM_ALARM_TONE,TIMERS_AND_ALARMS,REMINDERS,SOUND_SETTINGS,VOLUME_SETTING

**Comment by crunchip77** [comment]
Fire TV Stick **V1**
device Type: **ADVBD696BHNV5**
capabilities:
REMINDERS,CUSTOM_ALARM_TONE,VOLUME_SETTING,SUPPORTS_LOCALE_SWITCH,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,DIALOG_INTERFACE_VERSION,SUPPORTS_SOFTWARE_VERSION,SOUND_SETTINGS,PERSISTENT_CONNECTION,MICROPHONE,SUPPORTS_LOCALE,FLASH_BRIEFING,ACTIVE_AFTER_FRO,ARTHUR_TARGET,ASCENDING_ALARM_VOLUME,CHANGE_NAME,TIMERS_AND_ALARMS

Fire TV Stick **V2**
device Type: **A2LWARUGJLBYEW**
capabilities:
SOUND_SETTINGS,CHANGE_NAME,ARTHUR_TARGET,PERSISTENT_CONNECTION,DIALOG_INTERFACE_VERSION,ASCENDING_ALARM_VOLUME,VOLUME_SETTING,MICROPHONE,TIMERS_AND_ALARMS,SUPPORTS_LOCALE,CUSTOM_ALARM_TONE,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,ACTIVE_AFTER_FRO,FLASH_BRIEFING,REMINDERS,SUPPORTS_LOCALE_SWITCH,SUPPORTS_SOFTWARE_VERSION

**Comment by padrino-x** [comment]
@Apollon77 
Thank you, works like a charm now. =)
Any chance for the "commands" for mobile device, too?
(as said, speak via routine on the phone works)

**Comment by Apollon77** [comment]
If the Alexa App on your mobile can not do it then adapter also not

**Comment by padrino-x** [comment]
You asked the same in the forum.
I said "what do you mean, from the app no speech can be send to any device".
You said, I should try creating a routine to speak on the device.
I did and it worked, which I told you.
And above I wrote it again, it works for a/my phone, too.
So, sorry, I don't seem to understand what you are asking for. :(

**Comment by Apollon77** [comment]
I'm asking for exactly that ... I did not know that the "this device" mobile apps also support stuff ... the problem is that there can be many many of em and no way to know which mobile it is because they all get the same ID :-( ... and in regard to the adapter the adapter itself is "my device" because it mimics an alexa app, so I fear I can not do that

**Comment by padrino-x** [comment]
Can't the serial number be used?
I mean when I watch history objects, where serial number normally is something like G090... when I talk to my Echos, it's 86b64... when I talk to my phone.
So the adapter recognizes that the "echo 'mobile phone'" is the active one.

As I write, I just noticed, this serial is identical to the one in the objects tree of "this device", which, if I understood correctly, should be the adapter itself?
Then why are they sharing the same serial number?
Puzzling, at least to as noob like me. O:)

**Comment by Apollon77** [comment]
try with two mobile devices ... at least in the past as we checked last it was kind of "the same for all mobile devices.

Also would be interesting if a routine configured to output something on "this device" and triggered by an lexa device would really bring it on this one mobile (and only this one)

**Comment by padrino-x** [comment]
Luckily... hm, eigentlich können wir uns auch auf Deutsch unterhalten, oder? 😅
Also, ich hab zum Glück noch ein altes 5er Android Handy hier, mit dem ich testen konnte - ansonsten habe ich nicht so die Massen von Handies. 🤣
Ich kann sagen, dass eine Routine auf Handy1 mit Sprachausgabe auf "This device" auf Handy1 "ertönt" und eine zweite Routine auf Handy2 erstellt mit Ausgabe auf "this device" nur auf Handys erklingt - auch wenn sie von einem meiner Echos aufgerufen wurde. ☺

**Comment by Apollon77** [comment]
Ok, wenn DU das jetzt schon so eingerichtet hast bitte Adapter im Debug Log starten und mit komplettes start log zuschicken per email an iobroker@fischer.ka.de ... aber Log vom File auf Platte und nicht Admin. Dann schaue ich mal

(und was ausser "speak" geht noich von den commands?) ... und am besten einnneues Issue anlegen und das dann in email verlinken

**Comment by padrino-x** [comment]
Ok, to be continued in... https://github.com/Apollon77/ioBroker.alexa2/issues/602 ;)
