### ISSUE TITLE
Integration "Feature" Spotify

### ISSUE THREAD

**Issue by mikiline** [Apollon77/ioBroker.alexa2#6]
Ist es möglich Spotify zu integrieren?

**Comment by Apollon77** [comment]
Was gensau ist damit gemeint? 

Muss mal schauen ob ein anderer das hat :-)

**Comment by mikiline** [comment]
Im Prinzip wie im Adapter Spotify.....
Ich muss mal testen wie das ist. Hatte den Issue bzw. das Feature halt gleich mit eröffnet wegen der Umbenennung......

**Comment by Apollon77** [comment]
Habe bisher keine Infos oder APIs zu Alexa und Spotify gefunden

**Comment by mikiline** [comment]
das hier evtl. ?
https://developer.spotify.com/documentation/

**Comment by Apollon77** [comment]
Aber was hat die Spotify api mit Alexa zu tun? Es gibt Fisch schon eigenen Adapter für Spotify ... ich versteh es nicht. Sorry ;-) 

Was genau ist gewünscht?

**Comment by mikiline** [comment]
ich dachte da es einen Skill in Alexa gibt zu spotify und gerade der Alexa Adapter bearbeitet wird, könnte man da eine Verbindung schaffen. Sollte ich da auf dem Holzweg sein ist das kein Problem wenn es nicht zum Thema passt.

Danke jedenfalls für die Mühe die Du investierst

Gruss
mikiline

**Comment by Apollon77** [comment]
Ich hab bisher api technisch nichts gefunden was da geht. 

Skills triggern geht noch nicht :-(

Muss man mal schauen wenn die nächste Version dann playerinfos hat was da so steht.

**Comment by Apollon77** [comment]
sehe gerade keinen weg, sorry

**Comment by Apollon77** [comment]
Bitte mal in 0.3.0 (kommt gleich) checken ob spotify bei den Musik-Providern dabei ist
