### ISSUE TITLE
Shuffle state switches back to false if set to true

### ISSUE THREAD

**Issue by Mic-M** [Apollon77/ioBroker.alexa2#60]
Once the shuffle state (alexa2.0.Echo-Devices.xxx.Player.controlShuffle) is set to true, it is immediately being set back to false -- while shuffle keeps being turned on in the Spotify app.
Suggestion is to keep the state "true" once turned on (for visualization of the shuffle status, etc.).
Thanks.

**Comment by Apollon77** [comment]
Please try with latest GitHub version. This was a bug and us fixed there already. Please verify.
