### ISSUE TITLE
Device-type:A1Q7QCGNMXAKYW

### ISSUE THREAD

**Issue by testit2020** [Apollon77/ioBroker.alexa2#600]
Device-type:A1Q7QCGNMXAKYW (MICROPHONE,CUSTOM_ALARM_TONE,REMINDERS,SOUND_SETTINGS,DIALOG_INTERFACE_VERSION,ASX_TIME_ZONE,SUPPORTS_LOCALE,PERSISTENT_CONNECTION,VOLUME_SETTING,SUPPORTS_SOFTWARE_VERSION,TIMERS_AND_ALARMS,ASCENDING_ALARM_VOLUME,SUPPORTS_LOCALE_SWITCH,NO_TIME_ZONE_SETTING)

**Comment by Apollon77** [comment]
Whats this? WHats possible? Are Commands workding?
More information needed please

**Comment by testit2020** [comment]
Es handelt sich hierbei um ein Fire7 Tablet (9. Generation). Die Commands funktionieren nur teilweise. Hatte den anderen Post geschlossen, da ich feststellte, daß Amazon das Hauptproblem mit den Notifications noch nicht gelöst hat.
Beschrieben in : https://forum.iobroker.net/topic/39598/alexa2-3-4-0-killer-feature-textcommand/54
Dieser Post war nur um den Type des Gerätes mit anzugeben. Kann auch geschlossen werden, da man sowieso nicht weiterkommt.
Jegliche Notification ist bei dem Geräte nicht möglich. Was funktioniert und was nicht steht in dem Link (Forum ioBroker).
