### ISSUE TITLE
Alexa Fire Kids

### ISSUE THREAD

**Issue by MotschaM** [Apollon77/ioBroker.alexa2#601]
Wird es irgendwann die Möglichkeit geben über den iObroker Alexa Fire Tablet für Kinder zu steuern? 
Ich würde es mega finden!!

**Comment by Apollon77** [comment]
Was genau ist die Frage? Der Alexa2 Adapter kann exakt das tun was die Alexa Mobile App kann (steht auch so im Readme und in den Issue templates) ... was gernau geht nicht? Was genau sollte tun? Mehr details bitte

**Comment by MotschaM** [comment]
Ich kann hier nichts steuern, und es steht unten als offline? Das Kinder Dashboard kann man nicht über den Biobroker regeln oder? Aber auch sonst geht hier nichts? Vielleicht liegt es ja an mir?? Meine Echo dot lässt sich prima damit steuern

[](
<img width="1147" alt="Bildschirmfoto 2020-12-29 um 21 56 58" src="https://user-images.githubusercontent.com/55258616/103313599-d7829400-4a20-11eb-94a2-7249fea747cb.png">

**Comment by Apollon77** [comment]
Naja was steht im Log wenn der Adapter startet? Ich tippe es steht da, das das Gerät unbekannt ist und man checken soll was geht und das zurückmelden soll. korrekt?

Am Ende kannst Du versuchen bei Alexa App Routinen anzulegen die Dinge auf/mit dem Gerät tun ... wenn das nicht geht oder das Gerät gar nicht verfügbar ist zur Auswahl dann kann das wohl auch nichts. Dann sorry. Dann wären die Infos aus dem Log interessant das ich im Adapter die Commands rausnehmen kann.

**Comment by MotschaM** [comment]
ok ich habe es verstanden. Danke für Ihre Hilfe. Es ist auch nicht über die App verfügbar. Dann geht das mit dem Kindertablet nicht. Es gibt noch eine Amazon Kids+ App für diese Dinger. Kann man hier auch einen Adapter für den iObroker schreiben?

**Comment by Apollon77** [comment]
> Kann man hier auch einen Adapter für den iObroker schreiben?

Keine Ahnung... muss man sich ansehen. Am besten leg einen Request unter https://github.com/ioBroker/AdapterRequests/issues an
