### ISSUE TITLE
Support "commands" for mobile phone / app / "this device"

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#602]
related to: https://github.com/Apollon77/ioBroker.alexa2/issues/598

As sending text to differnt phones from different routines works, I assume there could be a way for Alexa2 to handle it... ;)

**Comment by Apollon77** [comment]
I checked into it: The main issue here is to separate real Apps from "virtual apps that are in fact this adapter" (and especially from the past there can be maaaaaaaaany of those adapter-virtual devices ..." need to dig deeper

**Comment by padrino-x** [comment]
Hm, here I have 3 entries under alexa2 showing the "APPS" logo.
1. "This Device" with deviceType A2TF17PFR55MTB, which is my Phone.
2. "Alexa App for PC" with DeviceType A1RTAM01W29CUP,  which probably is the app on win10 ;)
3. "Alexa App" with deviceType A1DL2DVDQVK3Q, where I don't know what it is or where it comes from, thought this might be the adapter. 🤷‍♂️

When I install the app on another phone I get another "This Device" with the deviceType A2TF17PFR55MTB, all the same as in "1." - with a different serial number of course. ;)

I don't see more here. 8-)

**Comment by Apollon77** [comment]
Done in next verison
