### ISSUE TITLE
Speak Command isn't working on first request.

### ISSUE THREAD

**Issue by Lixlx19** [Apollon77/ioBroker.alexa2#606]
Hey,
I ran into a problem since the last update of the adapter.
If I try to use the speak command, my Alexa only speaks at the second or third time.
I tried reinstallation but that didn't helped :(

**To Reproduce**  
1. Go to 'Objects'
2. Click on 'alexa2.0'
3. Click on 'Echo-Devices'
4. Click on 'Device name'
5. Click on commands
7. Scroll down to 'speak'
8. Enter some text

**Expected behavior**  
Obviously I expected Alexa to speak.

**Screenshots & Logfiles**  
If needed, I will add those later :)

**Versions:**  
 - Adapter version: <3.5.0>
 - JS-Controller version: <3.1.6> 
 - Node version: <v10.22.1> 
 - Operating system: linux

**Additional context**  
Problems occurr when I type some text in by hand and if it runs by a script...

**Comment by Apollon77** [comment]
When you setup a routine that speaks something and start that on the same device by the app ... is it then working always or the same issue? If the same issue then it is clearly an amazon issue.
If not: please set loglevel to debug and star adapter and send debug log of such a speak try
