### ISSUE TITLE
Control Amazon Prime Video play with ioBroker

### ISSUE THREAD

**Issue by Mathias2803** [Apollon77/ioBroker.alexa2#609]
There are no settings for the video playing of an Amazon Echo. So you cannot see if a video is playing, you cannot stop it or see the current played video.

In the mobile app you can see some of this information.

Maybe it is possible to add this. Thanks a lot and kind regards Mathias

**Consider the Reality**  
The adapter is using the same API as the Alexa mobile App. This means:

If you can not do this what you want with the App then the Adapter also can not do it! Also a feature rewuest most likely will not be possible.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Apollon77** [comment]
DO you zhave some screenshots what APp shows please? I do not have Amazon Prime, so I don't know
