### ISSUE TITLE
alexa2 v0.4.0 Echo Dot 2.Gen. bei Mute bzw. Volume auf 0 keine Statusänderung

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#61]
`alexa2.0	2018-08-13 12:54:10.897	info	Alexa-Push-Connection Device Volume change for GXXXT -> 0/null`

man sieht unter Objekte, dass er aktualisiert wird (wird kurz grün) aber der wert bleibt weiterhin auf "false"
(habe push aktiviert, aber ohne push das selbe)

https://forum.iobroker.net/viewtopic.php?p=168994#p168994

**Comment by Apollon77** [comment]
Ich habe an meinem Echo Dot 2.Gen einen Mute Button, aber es wird weder als Notify gesendet noch als Info beim media oder player abfrage. jetzt muss man "Muted" also noch mit anderen Geräten testen

**Comment by Matten-Matten** [comment]
Ich habe nur 4 Tasten 
- lauter
- leiser
- Microfon AUS/EIN
- Interaktion Sprachannahme
wo hast du denn die Taste MUTE?

**Comment by Apollon77** [comment]
Aaahhhh ... stimmt ... mist verwechselt ... war Mikrofon An/Aus ;-(

**Comment by Matten-Matten** [comment]
Der Adapter mit "Push-Connection" funktioniert wirklich gut!
Ich habe aber noch zwei Fragen zur Umsetzung, mache gegebenfalls ein neues issue auf, 
- in der Original APP wird bei multiroom Wiedergabe, auf allen Echo devices auch angezeigt was Multiroom abspielt. im Adapter ist das nicht so.
- Und ist es möglich, wenn bei einem device, die Objekte nach einer weile sowohl 'play' als auch 'pause' false anzeigt (also lange nix auf dem Gerät abgespielt wird)  die Objekte currentAlbum,currentTitle,currentArtist,... zu leeren?

**Comment by Apollon77** [comment]
Bitte zwei neue issues auf machen dafür und am besten den letzten kommentar löschen bitte ;-)

**Comment by Apollon77** [comment]
wenn ich meinen Echo Plus per App die lautstärke auf 0 setze kommt volume=0, muted=true ... muss mal mit meinem echo versuchen ...

**Comment by Apollon77** [comment]
Also muss man bei mediola mal ein iobroker Plugin anfragen? :-)

**Comment by Matten-Matten** [comment]
Hab ich schon ;-) ! machen sie nicht, Die wollen die selben Plugins ja für Geld verkaufen.
Ich werde höchstens man anfragen ob man eine Webseite aus einer CCU2 Variable (Zeichenkette) heraus öffnen lässt, oder so. Ich musste mir In VIS eine Seite bauen die nur die göße von **_media.cover_** hat, und rufe sie als Webseite in meiner Visu auf. 
Das geht natürlich bei VIS besser.

**Comment by Apollon77** [comment]
Ich hab sie auch mal angeschrieben ... von mir aus sollen Sie das iobroker-Plugin doch dann verkaufen? oder ?! (aber ist hier off topic) :-)

**Comment by Matten-Matten** [comment]
Ja klar sollen sie auch, aber die haben ja sehr viel plugins was iobroker auch als adapter hat. So meine ich das. Wenn was gut ist und funktioniert bezahle hab ich keine Probleme dafür was zu zahlen.
