### ISSUE TITLE
alexa2.0.Echo-Devices.G070VM1493820JQQ.Player.muted

### ISSUE THREAD

**Issue by Grothesk242** [Apollon77/ioBroker.alexa2#612]
alexex2 3.5.1 still shows 

warn: alexa2.0 (753) State "alexa2.0.Echo-Devices.G070VM1493820JQQ.Player.muted" has no existing object, this might lead to an error in future versions

But these warnings only show seldom now.

**Comment by Apollon77** [comment]
can I see a debug log excerpt please?

**Comment by Pocky2507** [comment]
Moin Ingo, wo möchtest Du das hingeschickt bekommen.
Diesen Log möchte ich hier nicht Posten.
Sensible Daten drin.

**Comment by Apollon77** [comment]
iobroker@fischer-ka.de

**Comment by Apollon77** [comment]
Will be fixed in coming 3.5.2 tonight
