### ISSUE TITLE
has no existing object nach Js-Controller upgrade 3.2.x

### ISSUE THREAD

**Issue by crunchip77** [Apollon77/ioBroker.alexa2#614]
betrifft device **G070L81491031UQW**
`

alexa2.0 | 2021-01-16 12:37:33.351 | warn | (25013) State "alexa2.0.Echo-Devices.G070L81491031UQW.Player.muted" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
alexa2.0 | 2021-01-16 12:37:33.351 | warn | (25013) State "alexa2.0.Echo-Devices.G070L81491031UQW.Player.volume" has no existing object, this might lead to an error in future versions

`

**Comment by Apollon77** [comment]
Welche Adapter Version?

**Comment by Apollon77** [comment]
Und bitte mal die capabilities des devices posten

**Comment by crunchip77** [comment]
Version 3.5.1
Fire TV Stick V2
TIMERS_AND_ALARMS,ASCENDING_ALARM_VOLUME,ACTIVE_AFTER_FRO,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,CUSTOM_ALARM_TONE,MICROPHONE,SOUND_SETTINGS,REMINDERS,SUPPORTS_SOFTWARE_VERSION,VOLUME_SETTING,FLASH_BRIEFING,PERSISTENT_CONNECTION,ARTHUR_TARGET,SUPPORTS_LOCALE,DIALOG_INTERFACE_VERSION,CHANGE_NAME,SUPPORTS_LOCALE_SWITCH

Am Sa., 16. Jan. 2021 um 16:03 Uhr schrieb Ingo Fischer <
notifications@github.com>:

**Comment by Apollon77** [comment]
will be fixed in coming 3.5.2 (somewhen tomight)
