### ISSUE TITLE
Feature request: Listen after Speak / Aufmerksamkeitsmodus nach Sprachausgabe

### ISSUE THREAD

**Issue by Supermicha81** [Apollon77/ioBroker.alexa2#615]
It would be nice, if the Alexa2-Adapter could enable the listening-function after a speak output.

I think the usecase is quite clear: To set another command right after an answer from iobroker.

If this is possible:
it would be nice to a button in the "commands" to activate the listening and/or
activate the listening after a speak command automaticly by giving a flag after the speak command.

**Comment by Apollon77** [comment]
Did you read the questions in the issue termplate? So: I do not know any way to achieve this with the Alexa App, so - sorry to say it - not possible
