### ISSUE TITLE
speak option via Handy Alexa App

### ISSUE THREAD

**Issue by xXHamtaroXx** [Apollon77/ioBroker.alexa2#616]
Can you please add the function: Speak over the alexa Smartphone app?

Thank's Jamie

**Comment by Apollon77** [comment]
duplicate #602

**Comment by padrino-x** [comment]
@xXHamtaroXx 
Maybe you want to give a "+1" here

https://github.com/Apollon77/ioBroker.alexa2/issues/602

to get this issue more attention/value? 🤓
