### ISSUE TITLE
"doNotDisturb" Alexa-App-Status wird im Adapter nicht übertragen

### ISSUE THREAD

**Issue by JHD47804** [Apollon77/ioBroker.alexa2#617]
Mir ist aufgefallen, dass seit einiger Zeit funktioniert die Übertragung des Alexa-App-Zustand "doNotDisturb" im Adapter nicht.
Vorgang: wenn ich in der App "Bitte nicht stören"-Modus aktiviere, wird in dem Adapter dieser Zustand nicht übertragen. Umgekehrt funktioniert bis jetzt immer.
Wenn ich auch den Adapter neustarte, ändert sich der Zustand im Adapter nicht, in der App bleibt wie gehabt.
Im Log erscheint kein Fehlermeldung.

**Versions:**  
 - Adapter version: <3.5.0>
 - JS-Controller version: <3,1,6>
 - Node version: <12.20.1>
 - Operating system: <os-name>

**Comment by Apollon77** [comment]
Das ist leider aktuell "by design" ... die Daten werden nur beim Start gelesen.

**Comment by Apollon77** [comment]
it will be updated with the player data from next verison on ... so delay is some minutes

**Comment by Apollon77** [comment]
see https://forum.iobroker.net/post/823454
