### ISSUE TITLE
Routines are empty

### ISSUE THREAD

**Issue by fbeister** [Apollon77/ioBroker.alexa2#618]
Starting today, without me doing anything, routines stopped working. States look like this - also after remove and re-add of adapter instance.

**Screenshots & Logfiles**  
![20210127_224552](https://user-images.githubusercontent.com/7522238/106058539-ab2a6800-60f1-11eb-94f8-bbcfb374aecb.jpg)

**Versions:**  
 - Adapter version: 3.5.2 - 3.5.6
 - Operating system: Ubuntu

Will add further version info if required - currently on mobile.
.

**Comment by Apollon77** [comment]
Then restart adapter please because then no routines were read on start ...

**Comment by fbeister** [comment]
tried that twice already

**Comment by Apollon77** [comment]
Then I need full debug log of adapter on start ... Instances - expert mode - column "log level". YOu can send it with reference to this github issue WITH issue number to iobroker@fischer-ka.de

**Comment by Apollon77** [comment]
PS: before you do it check in alexa app if routines are still listed there ... if not - amazon broke something ... wait 1-2 days ... if still there in alexa app ... try again with adapter and send log

**Comment by fbeister** [comment]
Routines are still there in alexa app. Will send dbg log tomorrow.

**Comment by fbeister** [comment]
I added a little bit of logging myself and the problem seems to be, that the API call returns 404 with an empty body
```
2021-01-28 07:46:51.546  - debug: alexa2.0 (15933) Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/behaviors/automations?limit=2000","method":"GET","timeout":30000,"headers":{}}
2021-01-28 07:46:51.704  - debug: alexa2.0 (15933) Alexa-Remote: Raw reply: status=404 - body=""
2021-01-28 07:46:51.706  - debug: alexa2.0 (15933) Alexa-Remote: Response: No body
2021-01-28 07:46:51.709  - debug: alexa2.0 (15933) Result of getAutomationRoutines: err={}, routines=null
```

**Comment by Apollon77** [comment]
Ok, no need for log, I now have the same issue ... Will look into it

**Comment by fbeister** [comment]
I fear that AWS rolled out an update that invalidates/deletes that API route. Is there any kind of documentation for that API so I could help looking into this?

**Comment by Apollon77** [comment]
> Is there any kind of documentation for that API 

HAHA :-))

No ,,, I will later check with proxy what the new call is

**Comment by fbeister** [comment]
`https://alexa.amazon.de/api/behaviors/v2/automations?limit=25`

Who would have guessed ...

```json
  {
    "@type": "com.amazon.alexa.behaviors.model.Automation",
    "automationId": "amzn1.alexa.automation.XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "name": "NAME",
    "triggers": [
      {
        "payload": {
          "customerId": "XXXXX",
          "utterance": "was macht die Waschmaschine",
          "locale": "de-DE",
          "marketplaceId": "XXX"
        },
        "id": "amzn1.alexa.trigger.XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
        "type": "CustomUtterance",
        "skillId": "amzn1.ask.1p.customutterance",
        "timeLapse": null,
        "presentationDataList": null,
        "imageUrl": null,
        "clientData": null,
        "context": null
      }
    ],
    "sequence": {
      "@type": "com.amazon.alexa.behaviors.model.Sequence",
      "sequenceId": "amzn1.alexa.sequence.XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
      "startNode": {
        "@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
        "nodeState": null,
        "name": null,
        "type": "Alexa.System.Wait",
        "skillId": null,
        "operationPayload": {
          "waitTimeInSeconds": 5
        },
        "presentationDataList": null,
        "clientData": null,
        "context": null,
        "tag": null
      }
    },
    "owner": {
      "@type": "OwnerId",
      "ownerType": "CUSTOMER",
      "id": "XXX"
    },
    "clientAlias": null,
    "condition": null,
    "status": "ENABLED",
    "creationTimeEpochMillis": 1606565609894,
    "lastUpdatedTimeEpochMillis": 1606565609894
  }
```

**Comment by fbeister** [comment]
Just verified that adding `v2` to the URL works as expected.

**Comment by Apollon77** [comment]
please try 3.6.0  or github version ... basically brings that change
