### ISSUE TITLE
Use new getAllDeviceVolumes call to initialize volumes on start

### ISSUE THREAD

**Issue by Apollon77** [Apollon77/ioBroker.alexa2#619]
getAllDeviceVolumes

**Comment by Hant0r** [comment]
setAllDeviceVolumes
setPreviousVolumes

**Comment by Apollon77** [comment]
??? What you mean by that? The initial topic is implemented in 3.8.1 since yesterday

**Comment by Hant0r** [comment]
I think, the functions setAllDeviceVolumes and setPreviousVolumes are usefull too.

So i can "getAllDeviceVolumes" to save the volumes, "setAllDeviceVolumes" to a fix value to set a speak message (p.a.) and then use "setPreviousVolumes" to return to all prevoius volumes on all speakers.

**Comment by Apollon77** [comment]
What was meaned here was annew API endpoj t we discovered that Aazon uses. There are no other.

and the functions you mentin are not usefull. All devices alreayd have a way to specify a custom and device specific speak-volume and if this is used or if volume is given on speak command the volume is set to that level before the speak and returned to old one already
