### ISSUE TITLE
Bei multiroom Wiedergabe, auf allen Echo devices wieder geben

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#62]
- in der Original APP wird bei multiroom Wiedergabe, auf allen Echo devices auch angezeigt was Multiroom abspielt. im Adapter ist das nicht so.

**Comment by Apollon77** [comment]
Frage dazu siehe Forum

**Comment by Matten-Matten** [comment]
**_Option 2_** wäre dann wie in der App, es ist dann einheitlich mit der Amazon eigenen App. ich bin für Option 2, da man auf diesen devices eh nichts abspielen kann, wenn Multiroom Musik läuft.

**Comment by sigalou** [comment]
Hello and thank you for this subject.
I saw in 2.6.0 (2019-07-21):
     (Apollon77) change announcement and ssml to send commands

But I can not, the volume changes everywhere but not the speak or annoucement.

When using the Android app Amazon Alexa, you can make an announcement for all devices. That's how it works?

Thank you
![announcement](https://user-images.githubusercontent.com/26350534/65380534-a378d900-dcdd-11e9-8884-96fef8843648.png)

**Comment by Apollon77** [comment]
Is Do not disturb diabled? Because else Announcement will not work. Does it work via App?
Please set Adapter to debug and send debug log from such a iobroker initialted announce.
Or ask in ioBroker Forum

**Comment by Apollon77** [comment]
Ok, I implemented an info for dvices if they play ina groui and in which ... I decided against updating all player states on all devices becase these are toooo many state updates. Will come in next version

**Comment by Apollon77** [comment]
see https://forum.iobroker.net/post/823454
