### ISSUE TITLE
History status is updated for command "speak" but not for commands "announcement" and "curatedtts"

### ISSUE THREAD

**Issue by JayVee2** [Apollon77/ioBroker.alexa2#622]
Great adapter, great work.

I use it to "speak" lots of error messages. Works nicely with command "speak".  I use "json" from "History" to find out, when text has been completed in order to send next message to speak. 

This doesn't work for "announcement" or "curatedtts" as I didn't find any way to get an updated status after completion.
If the adapter could update the History status after those commands would be great.

By the way: Is there any possibility to change the "ding" in announcement in order to distinguish spoken errors from warnings and info messages?

Thanks

-jayvee.

**Comment by Apollon77** [comment]
History entries are pushed from Amazon ... so if it is not there then amazon is not pushing anything. SOrry Adapter can not do anything.
Also "ding" is not changeable. infact speak, annoucement and ssml do things differently ... use whatever makes sense ...

**Comment by JayVee2** [comment]
Thanks für responsive and great support!!
-jayvee
