### ISSUE TITLE
alexa timer sofort auslösen - geht leider nicht ;(

### ISSUE THREAD

**Issue by moschnetwork** [Apollon77/ioBroker.alexa2#624]
Servus,

habe gesehen das der timer getriggert werden kann mit false / true was bei mir leider nichts auslöst.

Ist es denn irgendwie möglich aus den Datenpunkten "trigger timer" von Alexa unter den Echo devices bei den Objekten einen oder alle Echo Dots auszulösen?

Danke für diesen großartigen Adapter

**Comment by Apollon77** [comment]
Was meinst Du mit "das der Timer getriggert werden kann"? Der State geht auf true wenn ein Timer auslöst - anders rum - also schreibend - ist hier nichts möglich
