### ISSUE TITLE
Routinen zwar da, aber werden nicht mehr getiggert

### ISSUE THREAD

**Issue by detafun** [Apollon77/ioBroker.alexa2#629]
Hi, 
die Routinen sind zwar da und werden auch geladen, aber wenn ich die Routine Anspreche, dann passiert nix. 
Ich frag meine Sensoren immer ab, aber es schweigt sich aus.. Irgendwo hat wohl Amazon wieder was geschraubt.

Und wie andere schon gesagt haben, Historry geht auch nicht.

cu Deta

**Comment by detafun** [comment]
Hier mal was aus dem Debug Log, hört gar nicht damit auf.
`

alexa2.0 | 2021-02-02 15:50:00.827 | debug | (12561) Alexa-Remote: Response: No/Invalid JSON
-- | -- | -- | --
alexa2.0 | 2021-02-02 15:50:00.749 | debug | (12561) Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/activities?startTime=&size=4&offset=1","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2021-02-02 15:50:00.747 | debug | (12561) Alexa-Remote: No authentication check needed (time elapsed 285048)
alexa2.0 | 2021-02-02 15:50:00.546 | debug | (12561) Alexa-Remote: Response: No/Invalid JSON
alexa2.0 | 2021-02-02 15:50:00.479 | debug | (12561) Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/activities?startTime=&size=4&offset=1","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2021-02-02 15:50:00.477 | debug | (12561) Alexa-Remote: No authentication check needed (time elapsed 284778)
alexa2.0 | 2021-02-02 15:50:00.276 | debug | (12561) Alexa-Remote: Response: No/Invalid JSON
alexa2.0 | 2021-02-02 15:50:00.201 | debug | (12561) Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/activities?startTime=&size=4&offset=1","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2021-02-02 15:50:00.200 | debug | (12561) Alexa-Remote: No authentication check needed (time elapsed 284501)
alexa2.0 | 2021-02-02 15:49:59.998 | debug | (12561) Alexa-Remote: Response: No/Invalid JSON
alexa2.0 | 2021-02-02 15:49:59.928 | debug | (12561) Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/activities?startTime=&size=4&offset=1","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2021-02-02 15:49:59.927 | debug | (12561) Alexa-Remote: No authentication check needed (time elapsed 284228)
alexa2.0 | 2021-02-02 15:49:59.725 | debug | (12561) Alexa-Remote: Response: No/Invalid JSON
alexa2.0 | 2021-02-02 15:49:59.654 | debug | (12561) Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/activities?startTime=&size=4&offset=1","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2021-02-02 15:49:59.652 | debug | (12561) Alexa-Remote: No authentication check needed (time elapsed 283953)
alexa2.0 | 2021-02-02 15:49:59.447 | debug | (12561) Alexa-Remote: Response: No/Invalid JSON
alexa2.0 | 2021-02-02 15:49:59.377 | debug | (12561) Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/activities?startTime=&size=4&offset=1","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2021-02-02 15:49:59.375 | debug | (12561) Alexa-Remote: No authentication check needed (time elapsed 283676)
alexa2.0 | 2021-02-02 15:49:59.174 | debug | (12561) Alexa-Remote: Response: No/Invalid JSON
alexa2.0 | 2021-02-0

`

**Comment by Apollon77** [comment]
duplicate #628
