### ISSUE TITLE
currentAlbum,currentTitle,currentArtist,... Nach langer Wiedergabe Pause leeren

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#63]
-  ist es möglich, wenn bei einem device, die Objekte nach einer weile sowohl 'play' als auch 'pause' false anzeigt (also lange nix auf dem Gerät abgespielt wird)  die Objekte currentAlbum,currentTitle,currentArtist,... zu leeren?

**Comment by Apollon77** [comment]
frage dazu siehe Forum ... lass erstmal Da die Details klären

**Comment by Matten-Matten** [comment]
Es sind exakt **2 Stunden**, dann ist eine Wiedergabe eines zuvor Pausierten Titels oder Senders nicht mehr möglich. nach den 2 Stunden sollte dann auch in den Adapter-Objekten keine Werte **_currentAlbum, currentTitle, currentArtist.._**. zsw. stehen und auch **_controlPlay_** sollte dann auf **_false_** wechseln.

Gruß
Matten Matten

**Comment by Apollon77** [comment]
cool, damit kann ich arbeiten. hatte die Idee einfach alle 30 minuten wenn es nicht "PLAYING" ist dennoch ein update zu machen ... also quasi "verlängerte polling zeit trotz push verbindung" aber mit der 2h info vllt noch länger :-)
Was denkst Du?

**Comment by Matten-Matten** [comment]
Das Update alle 2 Stunden ist okay.

**Comment by Apollon77** [comment]
ist in 0.5.0 (heute abend oder spätestens morgen) drin
