### ISSUE TITLE
Alexa Adapter doesn't get JSON request

### ISSUE THREAD

**Issue by IchBinSmart** [Apollon77/ioBroker.alexa2#630]
**Describe the bug**  
The alexa adapter doesn't recognize what was spoken to my alexas anymore. Alexa adapater is green all cookies seem to be up to date and the URL https://alexa.amazon.de/api/activities?startTime=&size=3&offset=1 is returning the following:

`
{"activities":[{"_disambiguationId":null,"activityStatus":"SUCCESS","creationTimestamp":1612290428836,"description":"{\"summary\":\"\",\"firstUtteranceId\":\"A1RABVCI4QCIKC:1.0/2021/02/02/18/G090XG07938519CK/27:08::TNIH_2V.amzn1.alexa.skillConnections.tzullz.873a7a24-32c9-4984-996f-f2f5ebddb54cLPM\",\"firstStreamId\":null}","domainAttributes":"{\"allowAnalysis\":true,\"applicationMetadata\":{\"applicationId\":\"amzn1.ask.skill.fbc8bd0f-13ee-48c3-8f88-0deee48c5740\",\"applicationName\":\"Simon Says EU\",\"vendorId\":\"MFA1URM5Z2P1S\",\"initiator\":\"arn:alexa:amazon:softwareapplication/AlexaBlueprintsService\",\"privacyAndComplianceMetadata\":null},\"card\":null,\"redacted\":false}","domainType":null,"feedbackAttributes":null,"id":"A2GU4XXFQ5JAJ2#1612290428836#A1RABVCI4QCIKC#G090XG07938519CK","intentType":null,"providerInfoDescription":"Diese Anfrage wurde an Simon Says EU gesendet","registeredCustomerId":"A2GU4XXFQ5JAJ2","sourceActiveUsers":null,"sourceDeviceIds":[{"deviceAccountId":null,"deviceType":"A1RABVCI4QCIKC","serialNumber":"G090XG07938519CK"}],"utteranceId":"A1RABVCI4QCIKC:1.0/2021/02/02/18/G090XG07938519CK/27:08::TNIH_2V.amzn1.alexa.skillConnections.tzullz.873a7a24-32c9-4984-996f-f2f5ebddb54cLPM","version":1},{"_disambiguationId":null,"activityStatus":"SUCCESS","creationTimestamp":1612290428006,"description":"{\"summary\":\"gemütlich\",\"firstUtteranceId\":\"A1RABVCI4QCIKC:1.0/2021/02/02/18/G090XG07938519CK/27:06::TNIH_2V.c2fa248d-2cfa-4c2a-8519-b76b5df617adLPM/1\",\"firstStreamId\":\"A1RABVCI4QCIKC:1.0/2021/02/02/18/G090XG07938519CK/27:06::TNIH_2V.c2fa248d-2cfa-4c2a-8519-b76b5df617adLPM\"}","domainAttributes":null,"domainType":null,"feedbackAttributes":null,"id":"A2GU4XXFQ5JAJ2#1612290428006#A1RABVCI4QCIKC#G090XG07938519CK","intentType":null,"providerInfoDescription":null,"registeredCustomerId":"A2GU4XXFQ5JAJ2","sourceActiveUsers":null,"sourceDeviceIds":[{"deviceAccountId":null,"deviceType":"A1RABVCI4QCIKC","serialNumber":"G090XG07938519CK"}],"utteranceId":"A1RABVCI4QCIKC:1.0/2021/02/02/18/G090XG07938519CK/27:06::TNIH_2V.c2fa248d-2cfa-4c2a-8519-b76b5df617adLPM","version":1},{"_disambiguationId":null,"activityStatus":"DISCARDED_NON_DEVICE_DIRECTED_INTENT","creationTimestamp":1612290426965,"description":"{\"summary\":\"alexa\",\"firstUtteranceId\":\"A1RABVCI4QCIKC:1.0/2021/02/02/18/G090XG06929200BX/27:06::TNIH_2V.bc2cb62d-fa94-4027-a560-1fc2a1f89ffdLPM/0\",\"firstStreamId\":\"A1RABVCI4QCIKC:1.0/2021/02/02/18/G090XG06929200BX/27:06::TNIH_2V.bc2cb62d-fa94-4027-a560-1fc2a1f89ffdLPM\"}","domainAttributes":"DEVICE_ARBITRATION","domainType":null,"feedbackAttributes":null,"id":"A2GU4XXFQ5JAJ2#1612290426965#A1RABVCI4QCIKC#G090XG06929200BX","intentType":null,"providerInfoDescription":null,"registeredCustomerId":"A2GU4XXFQ5JAJ2","sourceActiveUsers":null,"sourceDeviceIds":[{"deviceAccountId":null,"deviceType":"A1RABVCI4QCIKC","serialNumber":"G090XG06929200BX"}],"utteranceId":"A1RABVCI4QCIKC:1.0/2021/02/02/18/G090XG06929200BX/27:06::TNIH_2V.bc2cb62d-fa94-4027-a560-1fc2a1f89ffdLPM","version":1}],"endDate":1612290428836,"startDate":1612290426965}
`

The adpater log nevertheless returns in debug mode: 

`
alexa2.0	2021-02-02 19:43:33.340	debug	(30393) Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/activities?startTime=&size=9&offset=1","method":"GET","timeout":10000,"headers":{}}
alexa2.0	2021-02-02 19:43:33.339	debug	(30393) Alexa-Remote: No authentication check needed (time elapsed 390311)
alexa2.0	2021-02-02 19:43:33.138	debug	(30393) Alexa-Remote: Response: No/Invalid JSON
`

**To Reproduce**  
1. Push Connection is activated. 
2. Click on #trigger button doesn't help.
3. Deleting the cookie from the adapter config didn't make any difference
4. history state doesn't refresh

**Expected behavior**  
history state should refresh when I speak with my alexa :-).

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: 3.6.0
 - JS-Controller version: 3.1.6
 - Node version: v12.12.1
 - Operating system: debian

**Additional context**  
Worked until lunchtime today and stopped working all of a sudden...

Any help on what I can try to fix this issue is appreciated.

**Comment by Apollon77** [comment]
duplicate #628
