### ISSUE TITLE
Bekomme nur ich keine History Objekte mehr wie Echo Device etc ??

### ISSUE THREAD

**Issue by m0rph2k** [Apollon77/ioBroker.alexa2#631]
Bekomme ich nur seit heute keine History Objekte wie Echo Device name nicht mehr ??

**Comment by Domi920** [comment]
Habe das selbe Problem.
Ein Neustart des Adapters bringt keine Besserung.
Wenn man das Aktualisierungsintervall manuell einstellt kommt auch nichts an.

**Comment by systemofapwne** [comment]
Kann ich bestätigen. Habe das selbe Problem. Kam ohne Update des Adapters irgendwann heute auf. Heute gegen 9h vormittags war noch alles ok. Ein Update auf den neusten Adapter verhalf nicht. Ich nehme an, dass Amazon was am Backend verhunzt hat und daher der Adapter nun spinnt.

**Comment by Apollon77** [comment]
duplicate #628
