### ISSUE TITLE
3-5 Queries/ Sekunde gegen alexa.amazon.de

### ISSUE THREAD

**Issue by Tekklab** [Apollon77/ioBroker.alexa2#632]
Ich bekomme seit heute plötzlich 3-5 Queries/Sekunde gegen alexa.amazon.de in Pi-hole angezeigt.
Ja, ich habe heute mein Amazon Passwort geändern, ich hab jedoch danach den Adapter komplett gelöscht und neu installiert, damit auch den "Login mit neuem Cookie" Prozess gemacht etc. Instanz ist grün, keine Fehler im iobroker Log, Pihole zeigt weiterhin 4300 Aufrufe/pro 10 Minuten in der Übersicht an. Erst wenn ich von Push auf 300s Intervall gehe, sinken die Queries in Pihole schlagartig.

**Comment by Apollon77** [comment]
duplicate #628
