### ISSUE TITLE
Additional DP for Alexa2 Adapter (example History.summary)

### ISSUE THREAD

**Issue by haselchen** [Apollon77/ioBroker.alexa2#636]
It is currently the case that the data point is filled briefly and then deleted again.
As a result, you can no longer see the last command.
However, this might be important for the user as to how Alexa understood the spoken word.
Accordingly, many users assemble their Blocklys.
Upper and lower case is important for the data point.
Please add an additional data point to the adapter for the last command.

**Comment by Apollon77** [comment]
I think the better approach is to llow a configuration to "Ignore history entries with empty summary"

**Comment by haselchen** [comment]
Perfect!  New version of the adapter fixes the "problem".  THX.
