### ISSUE TITLE
"This Device" nicht auflisten und abfragen

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#64]
Kannst du eventuell die Auflistung und abfrage von **_This Device_** unterbinden?
Oder ein Objekt mit **_disable_** erstellen, das man einige ungenutzte devices deaktivieren kann?

> alexa2.0 | 2018-08-14 12:29:45.394 | info | Alexa-Push-Connection Device Volume change for This Device -> 67/false
> -- | -- | -- | --
> alexa2.0 | 2018-08-14 12:29:44.903 | info | Alexa-Push-Connection Device Connection change for This Device -> ONLINE
> 
> 
> alexa2.0 | 2018-08-14 12:25:10.973 | info | Alexa-Push-Connection Device Connection change for This Device -> OFFLINE
> -- | -- | -- | --
> 

jedes mal wenn ich die Alexa app öffne kommt das immer im Log. Wahrscheinlich werden diese Infos demnächst eh ins debug level verschoben.

**Comment by Apollon77** [comment]
Das Logging ist aktuell noch eher verbose um zu sehen was die Push-COnnection tut.

Anhand vom Namen eines Devices dieses komplett auszuschliessen halte ich für keine gute Idee. Daher bleiben die. Aber ja das Logging wird verschwinden
