### ISSUE TITLE
Volume Control for Speaker Groups does not work

### ISSUE THREAD

**Issue by Marty56** [Apollon77/ioBroker.alexa2#640]
if "haus" is a group of Alexa speakers (having the identifier xx in the statement below), the command
setState("alexa2.0.Echo-Devices.xx.Commands.speak.Commands.speak", '50;Test');

does not set the volume of the related speakers.
All speakers in the "haus" group use the volume they have previously set to.

Workarround: issue command for each speaker and do not use speaker groups.

Version of Alexa Adapter 3.8.1

**Comment by Apollon77** [comment]
Do the devices have a speak-volume defined? Please provide a debug log (from logfile) from such a call

**Comment by Marty56** [comment]
No speak-volume was not defined, I was using "50;test" format in the "Commands.speak" data point

**Comment by Marty56** [comment]
I made sure whether all speaker have a speak volume set. But still some speakers are not reacting.
I have noted that when I repeat the command, then more speakers are "speaking".
I have 6 Echos. 2 Echo flex, 2 Echo V 1, 1 Echo V2 and 1 Echo V3.

**Comment by Apollon77** [comment]
Debug log is needed - how many devices are in your group? Maybe it is just rate limiting hitting and then "duplicate of #510 "

**Comment by Marty56** [comment]
[debug.txt](https://github.com/Apollon77/ioBroker.alexa2/files/6011678/debug.txt)

**Comment by Marty56** [comment]
Just a clarification after reading my initial statement.
One speaker did not issue any sound.
If I am repeating the same phrase, then this speaker is working again.
