### ISSUE TITLE
Add support for play data of prime video app

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#641]
As the latest version of the "prime video app" supports/shows data on current playback on the connected fire device, I wonder if this data could be added to the adapter?
Guess it could be useful in automation. :D 

![Screenshot_20210218-032205_Prime Video](https://user-images.githubusercontent.com/40962599/108296548-0b18a980-719a-11eb-98a0-926602147493.png)

![Screenshot_20210218-032902_Prime Video](https://user-images.githubusercontent.com/40962599/108296562-11a72100-719a-11eb-8a5b-6938001fe722.png)

**Comment by Apollon77** [comment]
The videoprime app doesnt matter. Can the Amazon Alexa App do that? If yes then we might have a way, if not then not

**Comment by padrino-x** [comment]
Ok, then this can be closed. :(
Just thought it might be possible to track net traffic of the prime app just as with the alexa app and include it in th

**Comment by Apollon77** [comment]
This would be then an own adaspter request with maybe an own adapter ...
