### ISSUE TITLE
Unknown Device - Fire HD 8 (10. Generation)

### ISSUE THREAD

**Issue by WaJoWi** [Apollon77/ioBroker.alexa2#642]
Device-type:AVU7CPPF2ZRAS (VOLUME_SETTING,SUPPORTS_SOFTWARE_VERSION,REMINDERS,PERSISTENT_CONNECTION,NO_TIME_ZONE_SETTING,DIALOG_INTERFACE_VERSION,TIMERS_AND_ALARMS,SOUND_SETTINGS,CUSTOM_ALARM_TONE,ASX_TIME_ZONE,ASCENDING_ALARM_VOLUME,MICROPHONE)

Commands funktionieren **nicht**.

**Comment by Apollon77** [comment]
will be in next verison

**Comment by Redsun1978** [comment]
Unter der 3.11.2 gehts leider noch nicht?? @Apollon77

**Comment by Apollon77** [comment]
Dann idealerweise logfile von beiden Versionen von so einer Aktion und adapterstart per email bitte.

**Comment by Apollon77** [comment]
Oder es kann es halt nicht. Geht es per Routine anlegen in der Alexa App? Wenn nicht dann geht's halt nicht

**Comment by t509** [comment]
[https://github.com/Apollon77/ioBroker.alexa2/issues/817#issue-1094753266](url)

**Comment by active-intelligence** [comment]
Hey,
ich habe das gleiche Problem.
Ich hatte erst ein Fire HD 8, mit dem ich den Alexa Adapter mit den Commands Folder nicht hinbekomme habe.
Ich habe mir dann noch ein Fire HD 10 bestellt, bei dem es automatisch funktioniert hatte.
Dachte mir wudnerbar, schicke ich das Fire HD 8 zurück.

Ein paar Tage später wird das Fire HD 10 auch weider nur als Alexa Typ Apps (A1DL2DVDQVK3Q) erkannt und somit funktioniert der commands Folder nicht mehr.

Technisch ging ja alles, aber es kann doch nicht sein, dass das 1. Gerät nicht erkannt wird aber alle folgenden.
Siehe selbiges Problem hier:
https://github.com/Apollon77/ioBroker.alexa2/issues/426

Gibt es dazu irgend ein Update?

**Comment by Apollon77** [comment]
DIe Fargen wie im anderen Thread sind die gleichen: Was geht denn mit dem Gerät? Wenn Commands nicht gehen machen auch keine Commands Folder sinn.

ALso bitte mal Infos zu Device type und capabilities und was per Alexa App geht ...  und dann bitte NEUE Issues erstellen und nicht an seit 2 Monaten geschlossene Posten bitte
