### ISSUE TITLE
Button ohne Aktion wieder zurücksetzen und bestätigen

### ISSUE THREAD

**Issue by Siggi0904** [Apollon77/ioBroker.alexa2#644]
Hallo,

wie ist es in einem Blockly-Skript möglich die Buttons in z.B. Commands zu setzen und
dann ohne Aktionsauslösung wieder zurück zusetzen? Denn normal sollten die doch alle auf false stehen.

Wenn ich z.B. .Commands.flashbriefing mit "steuere" auf "true" setze wird die Aktion auch ausgelöst.
Der Button bleibt aber auf true, also denkt man die Nachrichten würden noch vorgelesen werden.
Hier wäre ein zurücksetzen des Buttons super.

Des Weiteren finde ich keinen Weg den Wert am Button als bestätigt zu setzen.
Sollte nicht der Adapter mit dem Bestätigt-Flag antworten, wenn der Befehl am Alexa-Device angekommen ist?

Großen Dank für den tollen Adapter.

**Comment by Apollon77** [comment]
Du kannst mit "aktualisiere" den wert zurücksetzen.

Ein Button ist ein  Taster ... Dein Wandtaster sendet auch nur einen Impuls und dann passieren Dinge. Ob die wirklich klaufen oder nicht siehst DU den Schalter nicht an. Daher ist ein Button auch Formal nicht lesbar weil der Status "gelesen" keine Bedeutung hat. Also eine UI die den Button Status anzeigt ist nicht sinnvoll. :-)

**Comment by Siggi0904** [comment]
Hallo,

ein Taster setzt sich selbst zurück und einem Schalter sieht man seine Stellung wohl an.

Du meinst, "aktualisiere" mit falsch funktioniert?

**Comment by Apollon77** [comment]
Die Grundkonzepte und definitionen - und hier ist es an Homematic angelehnt - ist, das ein "Button" nur ein trigger ist der "true" triggert und sich danach nicht zurücksetzt ... Aber ja aus Usersicht kann ich es verstehen.
Aber für alle Buttons hier ein auto reset to false einzubauen ist so eine sache ...

**Comment by Siggi0904** [comment]
Okay, da kommt das her.
Aber fast alle Addons gehen den Weg eines triggers, der den Erhalt und die Verarbeitung mit dem Flag "bestätigt" bestätigen.

Könnte man dann auch auf false triggern und die nicht bestätigte Aktualisierung löst die Aktion aus?

**Comment by Apollon77** [comment]
> Könnte man dann auch auf false triggern und die nicht bestätigte Aktualisierung löst die Aktion aus?

Wenn ein Adapter Dev es gescheit programmiert hat nicht :-)) ABer hier hängt es sehr vom Adapter ab. In meiner welt "sollte" es mit false nicht triggern

**Comment by Siggi0904** [comment]
Hi,

er triggert auch auf false. Gerade mal im blockly geändert.
Also hat scheinbar das "nicht bestätigt" Flag eine Auswirkung.

![grafik](https://user-images.githubusercontent.com/4992106/109036153-9bd71400-76c9-11eb-900d-6cd430b9f001.png)

**Comment by Apollon77** [comment]
Dann muss ich mal chauen ... sollte an sich nicht ... aber naja :-)

**Comment by Siggi0904** [comment]
Dann sag bitte Bescheid, wenn du das änderst.  :-)
Dann muss ich das Skript anpassen. Danke.

**Comment by Apollon77** [comment]
sagen wir so: ich würde aktuell eher keine änderung planen :-)
