### ISSUE TITLE
New State - Any alarm triggered

### ISSUE THREAD

**Issue by Mr-Markus** [Apollon77/ioBroker.alexa2#645]
Hi there,

I tried to create a script that i can use my Hue switch to stop Alexa alarm if it was triggered. But if you have different alarm times you have multiple objects and each of it some states like triggered. So I have to modifiy my script if a new alarm time was created, which is not comfortable.

I think it shoul be possible to add a state under alarm with name like "Triggered" that would be true if any alarm time object has an active alarm (triggered)

This would help me a lot. I would also support you and send you a PR if you would tell me where to find that piece of code

Best
Markus

**Comment by padrino-x** [comment]
@Mr-Markus 
Hi, I don't think you really need an extra global entry there, this can be accomplished by using wild cards, I guess. :)

Here's an example on how I handle it in a little Blockly:

![20210312_005234](https://user-images.githubusercontent.com/40962599/110870926-b2868900-82cd-11eb-86c4-54b77968d143.png)

**Comment by padrino-x** [comment]
I know my example is for timers, but it could be adjusted for alarms as well

The object to trigger would be accordingly

alexa2.0.Echo-Devices.*.Alarm.*.triggered

or, to be precise 8-)

alexa2\.0\.Echo-Devices\..*\.Alarm\..*\.triggered

**Comment by Apollon77** [comment]
have fun https://forum.iobroker.net/post/824793
