### ISSUE TITLE
Bei Multiroom Betrieb Volumefehler

### ISSUE THREAD

**Issue by sigi2345** [Apollon77/ioBroker.alexa2#65]
Hallo,

wenn ich im Multiroom Betrieb auf NEXT klicke, dann wird der Wert von Volume auf null gestellt, die Dots spielen aber normal weiter.

Beitrag von 
[https://forum.iobroker.net/viewtopic.php?f=37&t=16095&start=20#p169433](url)

Log habe ich dir schon gesendet....

Sigi

**Comment by Apollon77** [comment]
Am Ende liegt das daran das Multiroom an sich gar kein Volume hat. Man kann den Datenpunkt super nutzen zum setzen, aber danach ist der Wert ggf nicht mehr aktuell. 

Ich mache jetzt folgendes: Volume-Werte die 0 sind werden bei  multiroom devices icht mehr geupdated.

Kommt in 0.5.0 denke morgen
