### ISSUE TITLE
Objekt Say oder ssml meldet bei Verwendung Fehler simonsays eu skill

### ISSUE THREAD

**Issue by realwax** [Apollon77/ioBroker.alexa2#652]
Wenn ich speak damit versorge dann klappte es bisweilen, oder eben ssml da markup - klappte auch.

<speak> Du hörst gerade <lang xml:lang="en-US"> Cooldown</lang> , von <lang xml:lang="en-US"> Blacksseds </lang> , aus dem Album <lang xml:lang="en-US">  Test </lang> </speak>

Aktuell bekomme ich einen Fehler dass es Probleme mit dem simonsay Eu Adapter gibt von Alexa erzählt. 
Das passiert wenn man say verwendet. ssml bleibt stumm. Dabei geht es nur darum, dass <lang xml:lang="en-US"> test </lang> enthalten ist. sobald as raus ist klappt es. Ging aber die ganze Zeit. 

Ist bei Amazon was down?

was kann ich tun? 

lexa2.0 | 2021-03-06 18:48:08.813 | info | (779) Subscribing to states...
-- | -- | -- | --
alexa2.0 | 2021-03-06 18:47:47.124 | info | (779) Device-type:A1WAR447VT003J (VOLUME_SETTING,AMAZON_MUSIC,PANDORA,AUDIO_PLAYER,TIDAL,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,LAMBDA_DOWNCHANNEL,APPLE_MUSIC,CHANGE_NAME,SIRIUSXM,DEEZER,MUSIC_SKILL,
alexa2.0 | 2021-03-06 18:47:47.123 | info | (779) Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2021-03-06 18:47:47.123 | info | (779) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2021-03-06 18:47:46.682 | info | (779) Alexa-Push-Connection established. Disable Polling
alexa2.0 | 2021-03-06 18:47:43.448 | info | (779) Proxy IP not set, use first network interface (10.0.0.20) instead

Danke Ingo!

**Comment by realwax** [comment]
Relativ spannend.... Ohne zutun ein wenig später klappt es wieder auch mit den Tags, aber die Funktion wird ignoriert. Sprich sie spricht die englischen Worte deutsch aus.

**Comment by Apollon77** [comment]
Naja ziemlich sicher ist bei Amazon da was faul.
