### ISSUE TITLE
Alexa announcement möchte nun einen state haben anstatt einen string?!?

### ISSUE THREAD

**Issue by Matze021986** [Apollon77/ioBroker.alexa2#664]
Hallo zusammen,

ich habe mir gerade meinen Log im ioBroker mal angeschaut und da wirft er mir folgende Warnung aus:

`(30272) You are assigning a string to the state "alias.0.Haus.AlexaAnnouncement.ACTUAL" which expects a state. Please fix your code to use a state or change the state type to string. This warning might become an error in future versions.
--
`
Das grundsätzliche Problem verstehe ich schon. Er will jetzt nen boolean haben anstatt nen string, aber wohin schreibe ich dann meinen Announcement?

Grundsätzlich gibt es ja noch den speak, aber der ist ohne "bing" vorher!

Natürlich steht da, das ich den Datentyp auch ändern kann, aber ich will da eigentlich so nicht eingreifen, weil ich nicht weiß, ob das ohne Trouble funktioniert und ob es in einem späteren Update nicht wieder überschrieben wird?!?

**Comment by Apollon77** [comment]
ÄÄäähhhmmm ... wo kommt denn der Alias her? Wie ist der definiert? Hat mit dem Adapter nichts zu tun

**Comment by Flacedoo** [comment]
At least from usage side I experience the same issue. I can easily send the "speak" command a string, but when I send it to announcement nothing happens. If I include the volume setting into the string send to announcement (e.g. leading "10;text"), I can hear the volume change - but no message is spoken?

**Comment by Apollon77** [comment]
@Flacedoo the issue is about something complete different! 
Is maybe the DND (do not disturb) mode activated on your device? Else please open a new issue and add debig log from the action. Provide log from file on disk in /opt/iobroekr/log/...

**Comment by Flacedoo** [comment]
Sorry, that was actually the reason why it wasn't working - thanks for the hint! I though it's not working at all anymore because I'm not sending a state as Matze indicated above there's a warning that it should receive a state... But obviously I just haven't checked my DND state..
