### ISSUE TITLE
Unable to send commands any more

### ISSUE THREAD

**Issue by Jadefalcon100** [Apollon77/ioBroker.alexa2#666]
Since the last update I cannot send any commands to my echo devices. Version 3.8.1

After editing the datapoint it blinks red for a while (signaling  a unconfirmed change) but then returns to the previous state. iobroker log is empty. The problem exists in all categories, e.g. neither setting an alarm nor controlloing the player volume works.

Data downstream to iobroker is ok.

**Comment by Apollon77** [comment]
Please create new Cookie and try again. Nothing is known or has changed that could cause this. ELse: Enable Debug log in adapter and provide details. best ask in Forum

**Comment by Jadefalcon100** [comment]
New Cookie solved the issue. The "old" one was created yesterday. 
Maybe it is still worth an investiation, because Iobroker believed the cookie was still valid ...
![image](https://user-images.githubusercontent.com/82337294/114319686-c7e01480-9b12-11eb-89f3-75b6787c0b87.png)

**Comment by Apollon77** [comment]
The adapter only checks the ageof the cookie ... we cn not really do more. This is a very rare case. Could it be that you changed the password of your Amazon account or logged everything out or such?
