### ISSUE TITLE
Some properties are missing from SmartHome devices

### ISSUE THREAD

**Issue by LastCodeDE** [Apollon77/ioBroker.alexa2#667]
Hello,

i am using version 3.8.1 and I am new at iobroker. 

In my setup are some aqara window door sensors and motion detecor. They are added by aqara home skill to alexa. The screenshot shows that i miss an property like open or motion detected. I added one aqara window door sensor to xiaomi mi home and added it by mi home skill to alexa. Unfortunately it's same. I made a screenshot to show you how the device will be displayed in iobroker. Is there something missing in my setup or is this an issue of the alexa adapter?

Regards

LastCodeDE 

![missing property](https://user-images.githubusercontent.com/15675686/114416698-3c699080-9bb1-11eb-9002-226af114698f.PNG)

**Versions:**  
JS controller 3.2.16
OS: win32

**Comment by Apollon77** [comment]
Why you think there is something missing? Is the Alexa app showing more?

**Comment by Apollon77** [comment]
is the Alexa Adapter log showing anything?

**Comment by LastCodeDE** [comment]
I thought when the alexa app can tell me that the window door sensor is open or closed the adapter can too. In the alexa app I can see to all the devices if motion was detected or that the window is open.

Do you need a screenshot of this?

**Comment by Apollon77** [comment]
The App is doing this by pulling the data from the server once per second (and only when you are on that page of the sensor). The adapter can not do that. Only option is to create a virtual "switch" device state in ioBroker and integrate that with iot as kind of device and then create a routine that switches this device and then react in ioBroker on changes
