### ISSUE TITLE
The function "deviceStop" isn't working in the current version. (In version "3.7.0" it is running.)

### ISSUE THREAD

**Issue by Mathias2803** [Apollon77/ioBroker.alexa2#668]
I am using the command "deviceStop = True" to stop any Skills or Audio play on my Alexa device.
This was working without any problems. But since the Alexa-Adapter updates this command is not working any more.

To test there is no problem on my Alexa or my settings / code I changed back to an old Alexa-Adapter version (3.7.0) and there it was working again without any problem.

This is the command that is sent to stop playing any skills:
"setStateDelayed("alexa2.0.Echo-Devices.G090LF1174320P4V.Commands.deviceStop"/*deviceStop*/, true, 1000, false);"

Can you please check the issue?

Thanks a lot, kind regards Mathias

**Comment by Apollon77** [comment]
No change was done to this functionality ...It would be gtreat if you could set adapter to debug with 3.7.0 and call the command and get debug log, then update to 3.8.1 and do the same. Then I can compare the commands. Please get the log from logfile on disk at /opt/iobroker/log/...

**Comment by Mathias2803** [comment]
Sure I will try to help you, but can you explain me how to make the debug file?
What adapter do I have to change to debug (Echo Dot or ioBroker?). How to get into the debug mode and how to get the debug file?
Thanks a lot, Mathias

**Comment by Apollon77** [comment]
Debug: Admin - Instances - Expert mode - column loglevel on adapter alexa2

**Comment by Mathias2803** [comment]
Ok, I hope you can do something with the log files, there are sooo much data running down. Good luck.

Here is the first log file with the version where the command is still working:

[Working Version 3.7.0 .log](https://github.com/Apollon77/ioBroker.alexa2/files/6299837/Working.Version.3.7.0.log)

**Comment by Mathias2803** [comment]
Here you can see the script that is stopping the Skill:

![image](https://user-images.githubusercontent.com/77450176/114463188-66887600-9be4-11eb-929c-abc190a1fc90.png)

The skill I was using to test it is called "Tausend Melodien".

**Comment by Mathias2803** [comment]
Oh, the strange thing is that it is working now even with the new version. So after downgrade and upgrade it is working.
I did not change anything in the scrip, all I have done was downgrade and upgrade and now all works. I am very sorry for this!
So we can close the issue. I am Sorry.

**Comment by Apollon77** [comment]
All good
