### ISSUE TITLE
unknown command...

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.alexa2#67]
Hi,
seit heute morgen (anscheinend hat Amazon n Update gemacht? ) steht hier folgendes im Log:
`

alexa2.0 | 2018-08-16 08:16:48.344 | info | Alexa-Push-Connection  Unknown Command - send to Developer:  {"destinationUserId":"A3NT1OXG4QHVPX","mediaReferenceId":"b86ab87f-c51e-41de-978d-bb7d1de4483d:1","dopplerId":{"deviceSerialNumber":"G000JN05
-- | -- | -- | --
alexa2.0 | 2018-08-16 08:16:48.254 | info | Alexa-Push-Connection  Unknown Command - send to Developer:  {"destinationUserId":"A3NT1OXG4QHVPX","bass":2,"treble":2,"dopplerId":{"deviceSerialNumber":"G000JN0573370K82","deviceType":"A1NL4BVLQ4L3N3"}
alexa2.0 | 2018-08-16 08:16:48.254 | info | Alexa-Push-Connection Device Volume change for G000JN0573370K82 -> 40/false

`
Habe weder an Software ( Alexa2 Version 0.4.0 ), noch an iobroker was geändert. ( npm 4.6.1, node 8.11.3 ). Das einzige, was gestern dazu kam, war ein zweites Xiaomi-Gateway, aber das sollte damit nichts zu tun haben.. :-)

**Comment by Apollon77** [comment]
Das ist erstmal nichts schlimmes, einfach nur ein "Kommando" über die Push-Verbindung das der Adapter nicht kennt :-) aber welch ein Zufall: hatte ich gestern auch  mit meinem neuen Echo Plus :-)

kommt in die 0.5.0.
