### ISSUE TITLE
speak & textCommand funktioniert nach einer Zeit nicht mehr

### ISSUE THREAD

**Issue by Domi920** [Apollon77/ioBroker.alexa2#672]
Leider funktioniert das speak Komando nach einer Zeit (ohne Adapterneustart) nicht mehr.
Hier der Auszug aus dem Debug Log:

alexa2.0 | 2021-04-19 19:21:38.250 | debug | (21901) Alexa-Remote WS-MQTT: Received Pong
-- | -- | -- | --
alexa2.0 | 2021-04-19 19:21:38.135 | debug | (21901) Alexa-Remote WS-MQTT: Send Ping
alexa2.0 | 2021-04-19 19:20:50.492 | debug | (21901) Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/behaviors/preview","method":"POST","timeout":10000,"headers":{}} and data={"behaviorId":"PREVIEW","sequenceJson":"{\"
alexa2.0 | 2021-04-19 19:20:50.492 | debug | (21901) Alexa-Remote: Authentication check successfull
alexa2.0 | 2021-04-19 19:20:50.491 | debug | (21901) Alexa-Remote: Response: {"authentication":{"authenticated":true,"canAccessPrimeMusicContent":true,"customerEmail":"meine.email@server.com","customerId":"A1PWGD9IWYF7E5","customerName":"
alexa2.0 | 2021-04-19 19:20:50.326 | debug | (21901) Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/bootstrap?version=0","method":"GET","timeout":10000,"headers":{}}
alexa2.0 | 2021-04-19 19:20:50.322 | debug | (21901) State changed alexa2.0.Echo-Devices.G2A0P308833204WX.Commands.speak: {"val":"das hat funktioniert","ack":false,"ts":1618852850318,"q":0,"from":"system.adapter.admin.0","user":"system.user.adm

Wenn ich das Objekt textCommand ansteuere funktioniert es ebenfalls nicht & das Debug Log sieht so aus:

alexa2.0 | 2021-04-19 19:25:33.842 | debug | (21901) Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/behaviors/preview","method":"POST","timeout":10000,"headers":{}} and data={"behaviorId":"PREVIEW","sequenceJson":"{\"
-- | -- | -- | --
alexa2.0 | 2021-04-19 19:25:33.841 | debug | (21901) Alexa-Remote: No authentication check needed (time elapsed 283349)
alexa2.0 | 2021-04-19 19:25:33.840 | debug | (21901) State changed alexa2.0.Echo-Devices.G2A0P308833204WX.Commands.textCommand: {"val":"Monitor ein","ack":false,"ts":1618853133835,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin"

Wenn ich den Adapter neu starte und ca. 1 Minute warte (bis alles aktualisiert ist) funktioniert alles wieder.
Habe 2 Alexa Konten in 2  verschiedenen Instanzen verknüpft. Bei beiden ist das gleiche Problem.

Woran kann das liegen?

Gruß Dominik

**Comment by JayVee2** [comment]
Ich kann bestätigen, dass das seit dem Wochenende wieder merkwürdig ist.
Es erinnert ein wenig an #628, denn History Updates kommen nach einer Weile auch nicht mehr.
Nach Restart des Alexa Adapters ist es wieder OK. Möglichweise sind gerade serverseitig wieder Änderungen im Gange.
-jayvee

**Comment by Apollon77** [comment]
Wird im FOrum auch gerade diskutiert ... ggf mal da ranhängen.

Es können Amazon änderungen sein die scheintbar die COokie laufzeit beeinflussen, ein Restart holt sich neue Cookies und mit denen geht es wieder. Müssen rausfinden was genau los ist. Wenn man halt Cookies ab jetzt täglichen holen muss auch ok :-)

Update alexa2 von gestern verringert Cookie Refresh-Interval von 7 auf 4 Tage. Mal schauen ob es damit besser ist
