### ISSUE TITLE
Steuerung Echo Spot Wecker über ioBroker

### ISSUE THREAD

**Issue by htrecksler** [Apollon77/ioBroker.alexa2#674]
Ich nutze den Alexa2 Adapter in der aktuellen stable Version 3.8.1.
Die einzige Aufgabe des Adapters besteht darin Schalter/Datenpunkte mit dem Echo Spot zu syncronisieren. Das allerdings funktioniert nur noch in eine Richtung.

Wenn ich in der Amazon App meine Wecker einschalte, dann wird dieses im zugehörigen Datenpunkt im Adapter ebenfalls umgestellt. Soweit funktioniert es.

Wenn ich jetzt aber den Datenpunkt in den Objekten des Adapters umstelle, kommt das in der Amazon App und somit auch beim Echo Spot nicht an.

In der Version 3.6.0 ist die Funktion noch vorhanden

**Comment by Supermicha81** [comment]
Habe ein ähnliches Problem.

Ich lasse meinen Wecker automatisch stellen,
Ich habe einen Dienstplan als SQL-Datenbank und nutze die Simple RESTful API um darüber, je nach Arbeitszeit, den Alexa-Adapter anzuweisen, meinen Wecker zu stellen.

Bis vor einiger Zeit klappte das super und sehr zuverlässig, ungefähr seit dem Problem mit den leeren Routinen hackt es auch mit dem Wecker stellen.

Im Adapter wird angezeigt, das der Wecker gestellt ist, er ist es aber nicht.
(Ich kann grade nicht nachvollziehen, ob der ACK-Status auf true steht, da mir meine Frau immer zuvorkommt und den Wecker per "Hand" stellt)

Adapter-Neustarts helfen oft für ein paar Tage, aber dann setzt es wieder aus.

Ich habe auch noch keine Ahnung woran es liegt, habe soeben auf die 3.8.2 aktualisiert, vielleicht hilt es, wenn der Cookie alle 4 Tage aktualisiert wird...
Das Log ist übrigens komplett leer... (zumindest keine Errors)

**Comment by Apollon77** [comment]
Leute ... ich kapiere nur bedingt was das genaue Issue ist. Könnt ihr es bitte nachstellen und mir in einer "schritt für schritt" anleitung hier geben?

Am besten auch mal Log auf Debug stellen und schauen was kommt. Wenn in der Alexa-App/Gerät ein wecker gestellt wird sollte das als "Push" info reinkommen und dso sichtbar sein. Wenn man im Adapter was tut dann sollten Requests vom Adapter zu Amazon rausgehen die man such sieht.

Gern auch Log laufen lassen und dinge tun und mit Zeitstempel aufschreiben und mir diese Info schicken und Logfile auch - am besten immer 30s pause lassen oder so

**Comment by Supermicha81** [comment]
@Apollon77 
momentan tritt das Problem nicht auf, da ich den Adapter beim letzten Update neu gestartet habe, ich muss wahrscheinlich ein paar Tage warten, bis es wieder passiert.

Nochmal zu den Grundlagen:
Ich nutze ein PHP-Script, welches mir einmal täglich erst alle Alarme auf dem Echo-Dot ausliest und dann entscheidet, wenn der gewünschte Alarm schon existiert, ihn auf true zu stellen ansonsten einen neuen Alarm anzulegen. Dazu nutze ich einen Call über die REST-Api um die Werte an ioBroker zu übergeben.
Das funktioniert grundsätzlich einwandfrei, der Alexa-Adapter empfängt die Werte auch, aber es passiert ebend leider regelmäßig, das der Alexa-Adapter den gestellten Alarm zwar als true anzeigt, er aber nicht auf dem Echo ankommt.

Ich versuche die nächsten Tage ein paar Logs zu kriegen und melde mich wieder.

**Comment by Apollon77** [comment]
Ok, wenn es nur auftritt wenn es eh Cookie Probleme gibt (dann geht auch ggf speak nicht), dann fixen wir das aber nix extra mit Wecker :-)

**Comment by Supermicha81** [comment]
Schließ das bitte mal noch nicht, ich weiß nicht, ob es an den Cookies liegt. War bisher nur eine Vermutung

**Comment by Supermicha81** [comment]
@Apollon77 Problem ist bisher noch nicht wieder aufgetreten, hing also allem Anschein nach, mit dem Cookie-Problem zusammen und kann hier doch geschlossen werden, falls @htrecksler nichts dagegen hat.
