### ISSUE TITLE
ioBroker -> Alexa geht nicht mehr, wenn alexa2.0.Lists "Used invalid characters"

### ISSUE THREAD

**Issue by Basti189** [Apollon77/ioBroker.alexa2#676]
alexa2.0 | 2021-04-24 14:04:05.987 | warn | (881) Used invalid characters: alexa2.0.Lists.💑Zusammen-Einkaufen.items changed to alexa2.0.Lists._Zusammen-Einkaufen.items
-- | -- | -- | --
alexa2.0 | 2021-04-24 14:04:05.981 | warn | (881) Used invalid characters: alexa2.0.Lists.💑Zusammen-Einkaufen.json changed to alexa2.0.Lists._Zusammen-Einkaufen.json
alexa2.0 | 2021-04-24 14:04:04.488 | warn | (881) Used invalid characters: alexa2.0.Lists.🏡Möbel-Kosten.items changed to alexa2.0.Lists._Möbel-Kosten.items
alexa2.0 | 2021-04-24 14:04:04.482 | warn | (881) Used invalid characters: alexa2.0.Lists.🏡Möbel-Kosten.json changed to alexa2.0.Lists._Möbel-Kosten.json
alexa2.0 | 2021-04-24 14:03:57.518 | error | at processImmediate (internal/timers.js:463:21)
alexa2.0 | 2021-04-24 14:03:57.518 | error | at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.alexa2/main.js:361:25)
alexa2.0 | 2021-04-24 14:03:57.518 | error | at Adapter.setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1846:40)
alexa2.0 | 2021-04-24 14:03:57.518 | error | (881) The id "Lists.Ich-packe-meinen-Koffer-und-bringe-mit-..." is invalid. Ids are not allowed to end in "."
alexa2.0 | 2021-04-24 14:03:57.410 | warn | (881) Used invalid characters: alexa2.0.Lists.🏡Möbel-Kosten.listId changed to alexa2.0.Lists._Möbel-Kosten.listId
alexa2.0 | 2021-04-24 14:03:57.404 | warn | (881) Used invalid characters: alexa2.0.Lists.🏡Möbel-Kosten.id changed to alexa2.0.Lists._Möbel-Kosten.id
alexa2.0 | 2021-04-24 14:03:57.398 | warn | (881) Used invalid characters: alexa2.0.Lists.🏡Möbel-Kosten.version changed to alexa2.0.Lists._Möbel-Kosten.version
alexa2.0 | 2021-04-24 14:03:57.392 | warn | (881) Used invalid characters: alexa2.0.Lists.🏡Möbel-Kosten.updatedDate changed to alexa2.0.Lists._Möbel-Kosten.updatedDate
alexa2.0 | 2021-04-24 14:03:57.386 | warn | (881) Used invalid characters: alexa2.0.Lists.🏡Möbel-Kosten.name changed to alexa2.0.Lists._Möbel-Kosten.name
alexa2.0 | 2021-04-24 14:03:57.378 | warn | (881) Used invalid characters: alexa2.0.Lists.🏡Möbel-Kosten.listReorderVersion changed to alexa2.0.Lists._Möbel-Kosten.listReorderVersion
alexa2.0 | 2021-04-24 14:03:57.372 | warn | (881) Used invalid characters: alexa2.0.Lists.🏡Möbel-Kosten.defaultList changed to alexa2.0.Lists._Möbel-Kosten.defaultList
alexa2.0 | 2021-04-24 14:03:57.364 | warn | (881) Used invalid characters: alexa2.0.Lists.🏡Möbel-Kosten.customerId changed to alexa2.0.Lists._Möbel-Kosten.customerId
alexa2.0 | 2021-04-24 14:03:57.357 | warn | (881) Used invalid characters: alexa2.0.Lists.🏡Möbel-Kosten.createdDate changed to alexa2.0.Lists._Möbel-Kosten.createdDate
alexa2.0 | 2021-04-24 14:03:57.350 | warn | (881) Used invalid characters: alexa2.0.Lists.🏡Möbel-Kosten.archived changed to alexa2.0.Lists._Möbel-Kosten.archived
alexa2.0 | 2021-04-24 14:03:57.341 | warn | (881) Used invalid characters: alexa2.0.Lists.🏡Möbel-Kosten.#New changed to alexa2.0.Lists._Möbel-Kosten.#New
alexa2.0 | 2021-04-24 14:03:57.334 | warn | (881) Used invalid characters: alexa2.0.Lists.🏡Möbel-Kosten changed to alexa2.0.Lists._Möbel-Kosten
alexa2.0 | 2021-04-24 14:03:57.326 | warn | (881) Used invalid characters: alexa2.0.Lists.💑Zusammen-Einkaufen.listId changed to alexa2.0.Lists._Zusammen-Einkaufen.listId
alexa2.0 | 2021-04-24 14:03:57.320 | warn | (881) Used invalid characters: alexa2.0.Lists.💑Zusammen-Einkaufen.id changed to alexa2.0.Lists._Zusammen-Einkaufen.id
alexa2.0 | 2021-04-24 14:03:57.312 | warn | (881) Used invalid characters: alexa2.0.Lists.💑Zusammen-Einkaufen.version changed to alexa2.0.Lists._Zusammen-Einkaufen.version
alexa2.0 | 2021-04-24 14:03:57.305 | warn | (881) Used invalid characters: alexa2.0.Lists.💑Zusammen-Einkaufen.updatedDate changed to alexa2.0.Lists._Zusammen-Einkaufen.updatedDate
alexa2.0 | 2021-04-24 14:03:57.298 | warn | (881) Used invalid characters: alexa2.0.Lists.💑Zusammen-Einkaufen.name changed to alexa2.0.Lists._Zusammen-Einkaufen.name
alexa2.0 | 2021-04-24 14:03:57.291 | warn | (881) Used invalid characters: alexa2.0.Lists.💑Zusammen-Einkaufen.listReorderVersion changed to alexa2.0.Lists._Zusammen-Einkaufen.listReorderVersion
alexa2.0 | 2021-04-24 14:03:57.283 | warn | (881) Used invalid characters: alexa2.0.Lists.💑Zusammen-Einkaufen.defaultList changed to alexa2.0.Lists._Zusammen-Einkaufen.defaultList
alexa2.0 | 2021-04-24 14:03:57.275 | warn | (881) Used invalid characters: alexa2.0.Lists.💑Zusammen-Einkaufen.customerId changed to alexa2.0.Lists._Zusammen-Einkaufen.customerId
alexa2.0 | 2021-04-24 14:03:57.268 | warn | (881) Used invalid characters: alexa2.0.Lists.💑Zusammen-Einkaufen.createdDate changed to alexa2.0.Lists._Zusammen-Einkaufen.createdDate
alexa2.0 | 2021-04-24 14:03:57.261 | warn | (881) Used invalid characters: alexa2.0.Lists.💑Zusammen-Einkaufen.archived changed to alexa2.0.Lists._Zusammen-Einkaufen.archived
alexa2.0 | 2021-04-24 14:03:57.254 | warn | (881) Used invalid characters: alexa2.0.Lists.💑Zusammen-Einkaufen.#New changed to alexa2.0.Lists._Zusammen-Einkaufen.#New
alexa2.0 | 2021-04-24 14:03:57.244 | warn | (881) Used invalid characters: alexa2.0.Lists.💑Zusammen-Einkaufen changed to alexa2.0.Lists._Zusammen-Einkaufen

Durch den "Error" bleibt der Adapter zwar Grün, aber alles was von ioBroker -> Alexa geht, kommt nicht mehr an. Alles was von Alexa -> ioBroker geht, wird normal angezeigt. Dies hat zur Folge, dass eben "speak" ausfällt oder alle anderen Funktionen. Das Problem mit dem "speak" hatte ich seit Tagen und erst jetzt, wo ich die Listen gelöscht habe, funktioniert alles wieder normal. 
Die folgenden Ausgabe erscheint nicht, wenn der "error" oben auftritt.

alexa2.0 | 2021-04-24 14:07:45.626 | info | (1063) Subscribing to states...
-- | -- | -- | --

Node.js: v12.22.1 & v12.22.0
NPM; 6.14.12
Adapter: 3.8.1 & 3.8.2

**Comment by Apollon77** [comment]
h ... Ok, what are that characters? Did you used some icons in the alexa app? Seems we need to filter the name ... grmpf

**Comment by Apollon77** [comment]
Can you remove these stupdi characters in the List names in the app in the meantime until I find time to fix it?

**Comment by Basti189** [comment]
I used a skill to import Microsoft ToDo lists with emoticons  and the log above is the result. I deleted the emoticons from name as a workaround. So when you strip out the emoticons, the bug will be fixed.

**Comment by ChristophsMowL** [comment]
I found out that Alexa2 isnt working when using list with special characters. 
They have to be removed^^

**Comment by Apollon77** [comment]
fxied in next version finally
