### ISSUE TITLE
Drop-In lässt sich nicht beenden

### ISSUE THREAD

**Issue by Andy-sgh** [Apollon77/ioBroker.alexa2#677]
Hi Apollon77,

zunächst mal vielen Dank für deine Arbeit. Ich nutze den Adapter via iObroker seit geraumer Zeit und die Vielfältigkeit ist einfach nur genial, wirklich tolle Arbeit.

Seit längerem hänge ich an einem Problem:
Ich möchte aktuell 2 Echo Dots als eine Art Gegensprechanlage miteinander Verbinden (zur Haustür). 
Der Rufaufbau / -abbruch soll va Drop-In über einen Button realisiert werden.
Ich bekomme den Rufaufbau via Drop-In ohne Probleme über den TextCommand realisiert ("z.B. "Dropin Haustür"), allerdings lässt sich der Drop-In nicht via TextCommand beenden (z.B. "Anruf beenden"), es kommt bei dem TextCommand immer die Echo-Ansage "es gibt keinen aktiven Anruf".
Spreche ich stattdessen einen der beteiligten Echos aber an, mit dem gleichen Sprachbefehl "Anruf beenden", wird der Drop-In beendet.
Hab schon alles probiert, verschiedener Syntax, selbst mit Routinen etc., finde aber keinen Workarround.

Hast du eine Idee, woran das liegen kann oder ggf.  sogar einen Lösungsansatz?

Ich hoffe ich konnte das Problem anschaulich beschreiben, sonst liefer ich gern nach.
Beim googeln ist mir das Problem nicht so häufig begegnet, aber hier z.B. https://forum.iobroker.net/topic/39598/alexa2-3-4-0-killer-feature-textcommand/109?_=1619294192076&lang=de

Vielen herzlichen Dank vorab!
Andy

**Comment by Apollon77** [comment]
Ich denke der Anruf kann nur bei dem Gerät beendet werden der Ihn auch gerade hat ... das "ioBroker" Gerät ist es ja nicht. Von daher ... wenn es die Alexa App nicht kann ... no idea

**Comment by Andy-sgh** [comment]
Hi und danke für das Feedback! 
Hab noch etwas rumprobiert.
So ganz verstehe ich in dem Kontext nicht, wie der Drop-In von dem jeweils gewählten Echo (object) aus ioBroker heraus zu einem anderen Echo gestartet wird. 
Ich wüsste nicht, wie ein Anruf zw. 2 beliebigen Echos aus der App heraus aufgebaut wird (bekomme das nur zw. App/Gerät und einem Echo hin). 
Start und Ende müsste doch dann der gleiche Workflow sein. Mir fehlt da glaub ich die Tiefe...
Dennoch toller Adapter und nochmals Danke für die Arbeit :-)
