### ISSUE TITLE
uncaught exception: Cannot read property 'alexaCookie' of undefined

### ISSUE THREAD

**Issue by peterbaumert** [Apollon77/ioBroker.alexa2#68]
Ich bekomme nach der Installation und Konfiguration via username und passwort ( beides definitiv richtig ;) ) folgende Fehler im Log:

host.ioBroker | 2018-08-16 16:01:21.848 | error | instance system.adapter.alexa2.0 terminated with code 0 (OK)
-- | -- | -- | --
alexa2.0 | 2018-08-16 16:01:21.838 | warn | Exception: TypeError: Cannot read property 'alexaCookie' of undefined
alexa2.0 | 2018-08-16 16:01:21.836 | error | at process._tickCallback (internal/process/next_tick.js:98:9)
alexa2.0 | 2018-08-16 16:01:21.836 | error | at _combinedTickCallback (internal/process/next_tick.js:74:11)
alexa2.0 | 2018-08-16 16:01:21.836 | error | at endReadableNT (_stream_readable.js:926:12)
alexa2.0 | 2018-08-16 16:01:21.836 | error | at IncomingMessage.emit (events.js:185:7)
alexa2.0 | 2018-08-16 16:01:21.836 | error | at emitNone (events.js:91:20)
alexa2.0 | 2018-08-16 16:01:21.836 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/alexa-cookie2/alexa-cookie.js:107:33)
alexa2.0 | 2018-08-16 16:01:21.836 | error | at request (/opt/iobroker/node_modules/alexa-cookie2/alexa-cookie.js:162:25)
alexa2.0 | 2018-08-16 16:01:21.836 | error | at /opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:88:29
alexa2.0 | 2018-08-16 16:01:21.836 | error | TypeError: Cannot read property 'alexaCookie' of undefined
alexa2.0 | 2018-08-16 16:01:21.835 | error | uncaught exception: Cannot read property 'alexaCookie' of undefined

Neuinstallation aus git habe ich schon probiert und hat nichts geholfen.

Viele Grüße
Peter

**Comment by Apollon77** [comment]
bekannt. und ist heute abend/morgen in 0.5.0 gefixt. Bitte im Forum den 0.4er Thread im Auge behalten
