### ISSUE TITLE
js-controller 3.3.6 - ....

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.alexa2#683]
with js-controller 3.3.6 the adapters stop with this error:
![grafik](https://user-images.githubusercontent.com/36229898/116825276-d4dea980-ab8e-11eb-965a-cfcc14bc973f.png)

**Comment by Apollon77** [comment]
known, DOwngrade js.controller to 3.3.5 or wait for 3.3.7 "soon" (see in forum thread)
