### ISSUE TITLE
Datapoint announcment not working with Sonos Roam / Announcement funktioniert nicht mit Sonos Roam

### ISSUE THREAD

**Issue by mac89muc** [Apollon77/ioBroker.alexa2#684]
Hello, thanks a lot for your effort to make the adapter available.

Today i received my Sonos Roam Speaker with Alexa Support.
I've noticed that the announcement datapoint isn't working all other dp's working as expected (calendar, sing a song, joke e.g.) also the speak command is working.

May be the reason due to a lack of adaptation, as the device is still very new..?

All of my other Sonos speakers (beam, move,one) are working without any problems concerning the announcement function.

Regards
-----------------

Vielen Dank für euren Einsatz zur Bereitstellung des Adapters.

Nachdem ich heute meinen Sonos Roam Speaker mit Alexa Support geliefert bekommen habe, ist mir aufgefallen, dass der announcment Datenpunkt beim Sonos Roam nicht funktioniert. Alle anderen Datenpunkte im Command Bereich funktionieren (joke, Kalender, sing a song usw.) - auch das speak command.

Alle anderen Sonos Speaker funktionieren ohne Probleme in Verbindung mit dem announcment Datenpunkt, liegt das evtl. an einer fehlenden Anpassung, da der Speaker noch recht neu auf dem Markt ist?

Gibts einen Vorschlag, wie ich das beheben kann, oder kann ich irgendwie unterstützen?

Gruß

**Versions:**  
 - Adapter version: <3.8.1>
 - JS-Controller version: <3.2.16>
 - Node version: <6.14.11> 
 - Operating system: <osx>

**Additional context**

**Comment by Apollon77** [comment]
Naja die erste Frage - und vor allem bei Sonos: Geht es über die Alexa App in einer Routine? Wenn nicht dann geht es nicht. Sonos unterstützt scheinbar nicht alle Features.

**Comment by mac89muc** [comment]
Danke für die schnelle Antwort.

Weder für meinen länger existierenden Sonos Move, noch für den neuen Sonos Roam werden mir beim erstellen einer Routine in der Alexa App die beiden Speaker für die Announcment Ausgabe angezeigt/vorgeschlagen. 

Beim Sonos Move funktioniert das aber dennoch über den Datenpunkt in iobroker, nur beim Sonos Roam eben nicht.

Auch wenn ich die Alexafunktion irgendeines meiner Sonos Boxen per Spracheingabe mit "_Alexa, Ankündigung an alle - Testnachricht_" triggere, wird das Announcement auf allen Lautsprechern inkl. des Sonos Roam korrekt ausgegeben.

Also die Funktion ist nach meinem Verständnis beim Sonos Roam damit grundsätzlich gegeben, zusätzlich funktioniert es ja beim Move auch trotz mangelnder Anzeige in der Routinenerstellung in der Alexa App.

Hast Du noch irgendwelche Tipps, oder Lösungsansätze, oder ist das dann ein Problem, was komplett in der Hand von Amazon liegt und grundsätzlich nichts mit dem Adapter zu tun hat?

Gruß

**Comment by Apollon77** [comment]
Leider habe ich da keine Idee. Der Adapter nutzt die gleichen APIs wie die Alexa App, damit kann er exakt so viel/wenig wie die. Ein paar Dinge die die App nicht anbietet aber die API erlaubt (wie bei Sonos Geräten) geht dann manchmal auch wenn es die App nicht kann, aber was und wie lange und wann es kaputt geht ist immer so ein ein Thema. Sonos geht gern bei diesen "unsupported" Funktionen mal kaputt und irgendwann tuts vllt wieder.

Alles bei Amazon. SOrry
