### ISSUE TITLE
No Login while pairing Alexa Skill with iobroker

### ISSUE THREAD

**Issue by meden01** [Apollon77/ioBroker.alexa2#685]
there is no login possible to get Alexa paired with iobroker! Second screen with direct iobroker login works fine, but not via Alexa site with "add skill" dialog. (with popup for login). Pls support!

**Comment by Apollon77** [comment]
What this has to do with alexa2 adapter?

YOu used the correct skill "iobroker iot"? Please refer to Forum and check the Cloud/IOT FAQ https://forum.iobroker.net/topic/18517/anleitung-iot-pro-cloud-assistenten-service-iobroker-iot
