### ISSUE TITLE
alexa local funktioniert nicht mehr......

### ISSUE THREAD

**Issue by stmiko** [Apollon77/ioBroker.alexa2#686]
Node Red flow mit alexa local funktioniert seit einigen Tagen bei mir nicht mehr.

Config:
alexa2 - 3.8.2
admin - 5.0.13
js-controller - 3.3.7

Leider kann ich nicht mehr sagen ab wann der Fehler genau auftrat.

Wenn ich einen Befehl sende, erscheint im log:

alexa2.0 | 2021-05-03 22:35:58.455 | info | undefined is not a valid state value for alexa2.0.History.status
-- | -- | -- | --

Das entsprechende Objekt (alexa2.0.History.status) enthält keinen Wert.

**Comment by Apollon77** [comment]
Was hat "alexa local node-red" mit dem Adapter zu tun?

Das Status Objekt ist seit 3.7.x nicht mehr gefüllt. Siehe Changelog

Was genau ist das issue?

**Comment by stmiko** [comment]
Na wenn die Funktion alexa-local nicht mit dem alexa2-Adapter zu tun hat, gibts kein Problem.......und sorry für mein Unverständnis!!!
