### ISSUE TITLE
Eins nach dem anderen

### ISSUE THREAD

**Issue by pdmetze** [Apollon77/ioBroker.alexa2#69]
Erstmal danke für den klasse Adapter.

Vorschlag, wenn möglich: Es wäre klasse, wenn Alexa eine Sprachausgabe erst beendet, bevor sie die Nächste startet. Bsp: ich habe ein Skript mit mehreren Sprachausgaben; derzeit spricht Alexa dann nur die letzte aus. 
Workaround in diesem Fall ist natürlich das sammeln der einzelnen Sätze in eine Variable und erst am Schluss ausgeben, aber schöner wäre es, wenn Alexa das selbst macht.

**Comment by Apollon77** [comment]
Da kann der Adapter nichts tun. Der Adapter weiss nicht wann die Sprachausgabe fertig ist. Wenn muss das das aufrufende Skript regeln.

**Comment by Apollon77** [comment]
siehe 0.7.x ... Jetzt können mehrere texte mit ; getrennt angegeben werden die nacheinander ausgesprochen werden

**Comment by pdmetze** [comment]
Hört sich gut an! Das probier ich heute Abend oder die nächsten Tage dann mal was. Und vielen Dank, dass du das hier nochmal kommentiert hast!
