### ISSUE TITLE
Fehler bei States von SmarthomeDevices (Number / Boolean)

### ISSUE THREAD

**Issue by saschaabraham** [Apollon77/ioBroker.alexa2#697]
Ich habe den Adapter neu aufgesetzt, nachdem mir aufgefallen ist, dass Änderungen der SmarthomeDevices nicht richtig übermittelt wurden.
Bsp. keine Info ob Licht an oder aus, Auch Änderungen vom Adapter Richtung Alea gingen nicht mehr (Änderung der Helligkeit einer Lampe)

Nach dem neu installieren der Instanz (3.9.0) erscheint nun dieses im Log:
(7828) State value to set for "alexa2.0.Smart-Home-Devices.9208bbff-6a77-46ee-8486-d707cc41aaef.brightness" has to be type "number" but received type "boolean"

Diese Meldung kommt z.Bsp. für alle Number Einträge. Auch Temperatur usw.

Im State steht dann bei z.Bsp. Brightnes "false %" drin.

In der Zustand der Geräte stimmt auch nicht. Ob An oder AUS wird nicht übermittelt.
Alexa2 ist 3.9.0
JS Controller ist 3.3.10

**Comment by Apollon77** [comment]
Das Log ist nur eine Info und hat keine Funktionale auswirkung.

Bitte die Daten ggf mit "#qzery" neu abholen (die werden ja nicht selbstständig aktualisiert)

Wenn es immer noch nicht geht bitte Adapter in Debug Log schalten und Debug log von einem Abrufen der daten senden

**Comment by saschaabraham** [comment]
OK. Nach dem Query stimmen die Werte, vorher sieht das recht wild aus ;-)

**Comment by Apollon77** [comment]
An sich  werden alle Serte einmalig beim start geladen. Danach nur auf anfrage
