### ISSUE TITLE
Ampel nur auf gelb

### ISSUE THREAD

**Issue by mcchickents** [Apollon77/ioBroker.alexa2#70]
Guten Abend,

versuche seit zwei Tagen Alexa 2 auf dem Iobroker zum laufen zu bekommen. Leider bekomme ich die Ampel nur auf gelb "Verbunden mit Alexa2 falsch" habe schon einen zweiten Pi am laufen mit neu aufgespieltem Iobroker hier ist jedoch genau das gleiche Fehlerbild. Hat jemand eine Idee was ich testen kann? Gruß Julian

**Comment by timae146** [comment]
ist bereits bekannt apollo ist dran. heute abend oder morgen kommt vorraussichtlich version 0.5 mit einem fix

**Comment by mcchickents** [comment]
ok ist das dann bei allen? gibt es eine möglichkeit den bug zu umgehen?

**Comment by Apollon77** [comment]
"Ampel Gelb" und ohne egliche Log-Infos kann ich erstmal nichts sagen weil es mehrere gründe geben kann. Der "Bug" von dem gesprochen wird, der aktuell in 0.4 besteht ist in 0.5 gefixt, würde aber zu einem Adapter-Crash führen, also eher "Rot".

Ich kann jetzt mit meiner Glaskugel nur vermuten das Dein Cookie nicht gelesen werden konnte und du im Log einen Link findest ...

**Comment by mcchickents** [comment]
hab es versucht kommt leider bei E-mail sowie handynummer folgende meldung 

Looking for Something?
We're sorry. The Web address you entered is not a functioning page on our site.

**Comment by Apollon77** [comment]
Interessant ... 0.5.0 vom Github bitte versuchen.
Wenn immer noch Adapter-Instanz auf Debug Loglevel stellen und komplettes Log vom Start UND einem Versuch dich per Proxy einzuloggen schicken

**Comment by mcchickents** [comment]
Ok wenn ich im iobroker den Adapter von Github installieren will bekomme ich diese Meldung. Vielleicht liegt es aber auch an meiner Unwissenheit und der falschen Anwendung


$ ./iobroker url "https://github.com/Apollon77/ioBroker.alexa2/tarball/master" alexa2
install https://github.com/Apollon77/ioBroker.alexa2/tarball/master
npm install https://github.com/Apollon77/ioBroker.alexa2/tarball/master --production --save --prefix "/opt/iobroker" (System call)
/bin/sh: 1: npm: not found
ERROR: host.raspberrypi Cannot install https://github.com/Apollon77/ioBroker.alexa2/tarball/master: 127
ERROR: process exited with code 25

**Comment by mcchickents** [comment]
0.5.0 hat nichts gebracht gleiche Fehlermeldung hab dann aber bei Amazon auf die zweifache Zertifikat umgestellt und jetzt klappt es grüne Ampel danke für die Hilfe

**Comment by Apollon77** [comment]
strange aber ok :-)

**Comment by reloxx13** [comment]
seit dem letzten update habe ich nun auch das problem.


alexa2.0 | 2018-11-25 01:43:35.957 | warn | Alexa-Cookie:  Password entered on Login Page via Proxy differs from set email! You  should use the same password to allow automatic cookie retrieval.
-- | -- | -- | --
alexa2.0 | 2018-11-25 01:43:35.954 | warn | Alexa-Cookie:  Email entered on Login Page via Proxy differs from set email! You  should use the same email to allow automatic cookie retrieval.
alexa2.0 | 2018-11-25 01:43:32.916 | warn | Alexa-Cookie:  Password entered on Login Page via Proxy differs from set email! You  should use the same password to allow automatic cookie retrieval.
alexa2.0 | 2018-11-25 01:43:32.915 | warn | Alexa-Cookie:  Email entered on Login Page via Proxy differs from set email! You  should use the same email to allow automatic cookie retrieval.

alexa2.0 1.1.3

**Comment by Apollon77** [comment]
Was heißt „dieses Problem“? Nach Proxy Nutzung sollte es tun. Diese Meldungen sagen nur das die eingegebenen Login Daten via Proxy andere sind als im Adapter hinterlegt. Proxy sollte dennoch gehen. 

Support bitte im Forum. Bitte Threads suchen, keine neuen anlegen.
