### ISSUE TITLE
Cookie kann nicht bezogen werden

### ISSUE THREAD

**Issue by ChrisWoehrle** [Apollon77/ioBroker.alexa2#709]
Hallo zusammen,

ich habe zur Zeit Probleme mit meiner Alexa-Verbindung zum Broker. Das Cookie kann nicht bezogen werden.

![image](https://user-images.githubusercontent.com/68493209/121799446-7516fc00-cc2c-11eb-86d3-2a289fb2e7fd.png)

Installierte Versionen: 
Alexa2 3.9.1
Node.js v12.22.1
js-controller 3.2.16
NPM 7.11.2
IOT Adapter: 1.8.16

Den Troubleshooting-Ansatz aus der Github Readme habe ich bereits versucht. Hat nicht funktioniert. 
Deaktivieren und Aktivieren der Instanz ebenfalls.
Wäre sehr dankbar wenn mir jemand eine Lösung hätte.

**Comment by Apollon77** [comment]
Was passiert denn wenn Du die Seite aufrufst?

**Comment by ChrisWoehrle** [comment]
Welche Seite meinst du?

**Comment by Apollon77** [comment]
Naja lies mal den Screenshot bzw die Logmeldung genau durch. Da steht eine URL. die Musst DU im Browseröffnen und Dich bei AMazton einloggen. Das ganze geht viel komfortabler über die Admin Konfigseite des adapters

**Comment by ChrisWoehrle** [comment]
Achso, ja, da war ich natürlich.
Was ich aber erst jetzt kapiert habe war, dass ich den Link aus der SMS öffnen muss. Hat geklappt und ist wieder alles grün ✌️😀 danke
