### ISSUE TITLE
V0.5.1 - keine Funktion bei Speak

### ISSUE THREAD

**Issue by Rambo79** [Apollon77/ioBroker.alexa2#71]
Update / Neu-Installation (beides getestet) läuft problemlos durch. Instanz lässt sich erstellen und wird aktiv (User-PW) - Lampe grün. Alle Echos werden unter Objekte aufgelistet. Auch erneut nach löschen des Ordners unter Objekte. Funktion (Datenpunkt) ist vorhanden und erhält auch entsprechenden Texteintrag aus Script. Ausgabe auf den Echos erfolgt jedoch nicht. Ebenfalls bei Traffic & Weather keine Sprachausgabe auf den Echos.

**Comment by Apollon77** [comment]
Bitte log im Debug Loglevel bereitstellen. Am besten vom Adapterstart und dann einer solchen Aktion

**Comment by Rambo79** [comment]
![bildschirmfoto 2018-08-17 um 11 29 23](https://user-images.githubusercontent.com/42409118/44259108-df0abf00-a210-11e8-866b-8c92fa6d2d52.png)

Was heißt "dem alle weg nehmen" - soll sich das auf "Ausführung" auf die Endgeräte beziehen ? - Mit der 0.3.8 funktionierte es ja :-(

Im Facebook melden mehrere die fehlende Funktion bei der 0.5.1.

**Comment by Apollon77** [comment]
an sich sich daran seit 0.3.8 nichts geändert. 

Was sind die ganzen "terminating" da in deinem Log-Screenshot? Warst DU das oder was ist da passiert?

Also dann brauche ich jetzt folgendes:
1.) Lege eine Routine an die eine Sprachausgabe auf dem gerät macht um was es geht und checke das das tut. Routine speichern!
2.) Loglevel auf Debug vom Adapter
3.) Log vom Adapterstart (bitte als Text direkt aus der Logdatei unter /opt/iobroker/log
4.) dann einmal per Adapter versuchen den "speak" zu machen (der der nicht tut)
5.) Auch davon das Log

**Comment by Apollon77** [comment]
PS: Schön das User es im Facebook melden ... da sehe ich es nicht

**Comment by Rambo79** [comment]
Nein, das war ich nicht :-(

By the way: Ich habe drei Geräte und es funktioniert keins. Nur falls das bis jetzt anders rüber gekommen ist.

Probiere ich gern aus, allerdings etwas später.

Was genau meinst Du mit Routine anlegen. Kenne ich bisher nur aus der eigentlichen Alexa-App.

Dort eine Routine mit Sprachausgabe als Ergebnis, richtig ?

**Comment by Rambo79** [comment]
Unter der Annahme, das ich alles gemäß deiner Anleitung korrekt wie folgt gemacht habe das Ergebnis:

1) Routine in der Alexa App mit Sprachausgabe erstellt. Erscheint kurze Zeit später in den Objekten und kann von dort mit simuliertem Tastendruck ausgelöst werden. Sprachausgabe erfolgt SOFORT und ohne jegliche Probleme

2) getan
3) 2018-08-17 12:05:40.108  - ^[[32minfo^[[39m: host.iobserver instance system.adapter.alexa2.0 started with pid 21735
2018-08-17 12:05:40.897  - ^[[32minfo^[[39m: alexa2.0 starting. Version 0.5.1 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.11.3

4) passiert nix
5) nach meiner Auffassung kein neuer Log-Eintrag ???

:-( :-(

**Comment by Matten-Matten** [comment]
@Rambo79 

![nvidia geforce overlay-17 08 2018_12_21_37](https://user-images.githubusercontent.com/32074970/44261653-97883100-a218-11e8-95b2-8f7b08445744.png)

**Comment by Rambo79** [comment]
Feedback zur anderen Frage:

Das war es !!!! - Frau aus dem Haushalt gelöscht und es funktioniert auf Anhieb mittels Auslösung per Script.

**Comment by Rambo79** [comment]
Auch mit allen 3 Geräten funktioniert es jetzt. Dann bleibt die Frau eben .... ;-)
Danke für den Support

**Comment by Apollon77** [comment]
ne du fügst Sie bitte wieder dazu und versuchst die 0.5.2 vom Github

**Comment by Rambo79** [comment]
Ja, ich teste gerne weiter, finde deine Arbeit nämlich SUPER!

Leider geht das hinzufügen erst nach einer Wartezeit von 180 Tagen. - AmazonRichtlinie :-(

Sorry

Aber so konnte der Fehler ja auch was eingegrenzt werden

**Comment by Apollon77** [comment]
180 Tage? Naja Scheidung ist halt mit Wartezeit *lol*

Aber vllt sag es in Facebook und die die auch Probleme haben können es verifizieren?!

**Comment by Rambo79** [comment]
Ich schmeiß mich weg !!!

Mach ich gern :-)

**Comment by Apollon77** [comment]
Thx. Gern hier Feedback auch wenn ich zu mache
