### ISSUE TITLE
History not updating

### ISSUE THREAD

**Issue by patrickbs96** [Apollon77/ioBroker.alexa2#719]
**Describe the bug**  
History stopped updating itself. A restart of the adapter doesn't help. The logs response message is saying "Service not available".
In the Alexa App I can see the last history entry.

**Screenshots & Logfiles**  
2021-07-03 13:41:22.705  - Alexa-Remote: Sending Request with {"host":"www.amazon.de","path":"/alexa-privacy/apd/rvh/customer-history-records?startTime=1625226082704&endTime=1625398882704&recordType=VOICE_HISTORY&maxRecordSize=13","method":"GET","timeout":10000,"headers":{}}
2021-07-03 13:41:22.810  - Alexa-Remote: Response: Status: 503

**Versions:**  
 - Adapter version: <3.9.1>
 - JS-Controller version: <3.3.14> 
 - Node version: <14.15.3> 
 - Operating system: <debian>

**Comment by Slider-Override** [comment]
same for me,

**Comment by IchBinSmart** [comment]
Yes I can confirm that...

**Comment by mpffh1** [comment]
I can confirm that too
cu

**Comment by m0rph2k** [comment]
same

**Comment by Apollon77** [comment]
I will check later what Amazon has done this time ... or it still could be an outage on their side ...

**Comment by Apollon77** [comment]
For all that post things like "same" or "+1" or such ... please do not do that because it helps noone and makes the Issue near to unreadable for all. Just do a "thumbs up" on first post. Thank you

**Comment by Apollon77** [comment]
Forum Thread ioBroker: https://forum.iobroker.net/topic/45449/alexa2-aktualisiert-history-nur-noch-unzuverl%C3%A4ssig

**Comment by Apollon77** [comment]
Is it always not working or just sometimes?

**Comment by padrino-x** [comment]
It's never working here =)

**Comment by padrino-x** [comment]
@Apollon77 
It just started working again, 10 minutes ago, still dead. 😅

**Comment by Apollon77** [comment]
verifed, so was an Amazon outage

**Comment by Slider-Override** [comment]
It's back to normal 😃

Ingo Fischer ***@***.***> schrieb am So., 4. Juli 2021, 00:05:
