### ISSUE TITLE
Antwort auf anderen Echo wenn Musik spielt

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.alexa2#72]
Hi,
mir ist folgendes aufgefallen:
ich lasse im Wohnzimmer auf dem Echo Musik abspielen ( Planet, TuneIn ), und frage in der Küche, ob die Waschmaschine fertig ist, die Routine antwortet in der Küche und der Iobroker im Wohnzimmer ..

Ich denke, das hängt damit zusammen, dass der Echo im Wohnzimmer gerade Musik spielt? 
Wäre schön, wenn man beim Trigger beachten könnte, ob Musik spielt, falls das Amazon möglich macht.. sonst antwortet immer nur der, der die Musik spielt .. 

Ist das bei euch auch so ?

Kann leider kein Logfile dazu beifügen, da seit Admin3.5.2 keins mehr erzeugt wird.. ( garkeins..)

**Comment by Apollon77** [comment]
Die Sprachausgabe sollte exakt auf dem device kommen wo du es in ioBroker absendest egal ob Musik spielt oder nicht. 

Log gibt es immer auch auf Platte unter /opt/iobroker/log und für alexa2 ist das auch das einzig hilfreiche weil Admin abschneidet. 

Admin issue aufmachen und sicherstellen das Admin in nur einem Browser und tab offen ist!!!

**Comment by Apollon77** [comment]
Bei Routinen kannst du an sich bei der Einstellung sagen ob der Echo antworten soll der gefragt wurde oder immer ein spezieller.

**Comment by Ilovegym66** [comment]
Hi, ja, bei den Routinen ist das ja auch richtig.. 

oha, hab grad die Logs gesehen, ich zieh den kompletten iobroker mal in die proxmox-vm um.. alles andere hat keinen Sinn, wenn man testet. 
Gibt ne Neuinstallation, und dann sehen wir weiter, ich glaub, da ist irgendwas durcheinander..

meine Alexa sagt so alle 30min "huhu".. ( hatte ich vorgestern mal beim Multiroom eingegeben..) das ist auch nicht mehr in den Objekten, aber der Tante scheints zu gefallen.. 
Glaub, mein NPM 4.61 verträgt sich nicht mit node 8.11.4... seitdem ist das alles komisch..

Habe jetzt in der Küche Radio laufen, und Wohnzimmer antwortet, wenn ich nach der WM frage.. 
Umgekehrt funktioniert es nicht, wenn im Wohnzimmer Radio läuft, und ich frage in der Küche, dann antwortet immer Wohnzimmer und das steht dann auch im Trigger..

**Comment by Ilovegym66** [comment]
3h later... :-)
iobroker komplett neu aufgesetzt, proxmox ist ja geil. 
Problem ist gelöst, anscheinend war irgendwas durcheinander gekommen.
Thema kann geschlossen werden, sorry.
