### ISSUE TITLE
DP summary, serialNumber und name im Zweig History werden nicht gefüllt, wenn ein Befehl vom Echo Auto empfangen wurde

### ISSUE THREAD

**Issue by ELK169** [Apollon77/ioBroker.alexa2#722]
Nur beim Echo Auto werden die Datenpunkte nicht gefüllt.
(Edit:)
Die genannten Datenpunkte enthalten ja den letzten empfangenen Sprachbefehl, die Seriennummer und den Namen des genutzten Gerätes. Wenn ich also einem Echo sage "schalte das Licht an", finde ich die Daten in den Datenpunkten so lange, bis ein neuer Befehl gegeben wird. 

Wenn ich jedoch den Befehl per Echo Auto oder über die Alexa-App gebe, werden die Werte der Datenpunkte nicht geändert. Die Werte vom vorangegangenen Befehl stehen dort also unverändert.

Da ich (zum Beispiel!) per Echo Auto-Befehl eine Routine starten kann, die einen Status im ioBroker ändert, gehe ich davon aus, dass es bei mir keine grundsätzlichen Kommunikationsprobleme gibt.

**Comment by Apollon77** [comment]
Hm ... Liess bitte mal was Du geschrieben hast und versetze dich in meine Lage ... was würdest Du da lesen?
Ich kapiere geade nur Bahnhof.

mehr details, Screenshots, Logs, bitte

**Comment by ELK169** [comment]
ok, sehe ich ein… war ein Schnellschuss.
Ich bessere nach…

**Comment by Apollon77** [comment]
Und eins noch: Woran machst Das fest das es nicht gefüllt wird? Blockly bekommt nichts oder Admin zeugt nichts an? Ggf ist eun neuer Wert sehr schnell nach einem anderen da das Admin das gar nicht wirklich anzeigt. Der Adapter hat auch eine EInstellung "leere" history eintröge zu unterdrücken ... also am bestne nur schena was im blockly ankommt und dort loggen.

ggf auch Debug log einschalten und selbst schauen was an Daten von Amazon wann kommt ... vllt ists ja einfach nicht drin weil Amazon es nicht liefert. An sich unterschlägt der Adapter nichts was da ist.

**Comment by ELK169** [comment]
Debug log hatte ich jetzt mal an und wurde überrollt von gefühlt tausenden von Einträgen. Bei einem Befehl vom Echo Auto aus passiert nicht sehr viel und der Text meines Befehls erscheint auch nicht. Sieht also wirklich danach aus, dass die Information nicht bis zum Adapter vordringt. (Soweit ich das laienhaft von außen beurteilen kann...)

**Comment by Apollon77** [comment]
Das kann durchaus sein. AM Ende kannst Du in der Alexa App in den EInstellungen vom Account macl schauen. Da gibt es die Übersicht der SPrachaufanahmen und so ... ists da dabei?

**Comment by ELK169** [comment]
Hallo!
Danke sehr für die Anteilnahme, nachdem ich so ungeschickt angefangen habe… Bin vorhin erst zum Ausprobieren gekommen.
In den Sprachaufnahmen ist der Befehl mit dabei (und auch abspielbar), Quelle ist „Andreas‘ Amazon Alexa on iOS“. Im Log sehe ich wieder nur die Reaktion auf den Befehl (senden einer Telegram-Message), aber keinen Hinweis auf den Befehl selbst. Sieht also irgendwie danach aus, als ob die Information nicht bis zum ioBroker vordringt.
Da im Sprachverlauf der Hinweis auf iOS zu finden ist, könnte ich mir vorstellen, dass eigentlich die Alexa-App den Befehl weiterleitet und dass das Echo Auto-Dingsi im Prinzip egal ist und nur als besseres Mikrofon verwendet wird.
MfG Andreas

**Comment by Apollon77** [comment]
Ok, also akzeptieren wirs und machen hier zu?
