### ISSUE TITLE
Instanz verbindet sich nicht

### ISSUE THREAD

**Issue by mandre1904** [Apollon77/ioBroker.alexa2#73]
Hallo,

ich bekomme die Instanz nicht zum laufen. Ich bekomme die Fehlermeldung im Log:

alexa2.0 | 2018-08-18 17:57:44.362 | warn | Exception: TypeError: Cannot read property 'alexaCookie' of undefined
-- | -- | -- | --
alexa2.0 | 2018-08-18 17:57:44.358 | error | at process._tickCallback (internal/process/next_tick.js:180:9)
alexa2.0 | 2018-08-18 17:57:44.358 | error | at _combinedTickCallback (internal/process/next_tick.js:138:11)
alexa2.0 | 2018-08-18 17:57:44.358 | error | at endReadableNT (_stream_readable.js:1064:12)
alexa2.0 | 2018-08-18 17:57:44.358 | error | at IncomingMessage.emit (events.js:208:7)
alexa2.0 | 2018-08-18 17:57:44.358 | error | at emitNone (events.js:111:20)
alexa2.0 | 2018-08-18 17:57:44.358 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/alexa-cookie2/alexa-cookie.js:107:33)
alexa2.0 | 2018-08-18 17:57:44.358 | error | at request (/opt/iobroker/node_modules/alexa-cookie2/alexa-cookie.js:162:25)
alexa2.0 | 2018-08-18 17:57:44.358 | error | at /opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:88:30
alexa2.0 | 2018-08-18 17:57:44.358 | error | TypeError: Cannot read property 'alexaCookie' of undefined
alexa2.0 | 2018-08-18 17:57:44.357 | error | uncaught exception: Cannot read property 'alexaCookie' of undefined
alexa2.0 | 2018-08-18 17:57:38.468 | info | starting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.11.1
alexa2.0 | 2018-08-18 17:57:38.297 | info | States connected to redis: 127.0.0.1:6379

Cookies hab ich bereits gelöscht und es erneut versucht.
Kann mir jemand helfen? Danke

**Comment by timae146** [comment]
update mal auf die aktuelle version 5.2. dann sollte es wieder funktionieren.

**Comment by Apollon77** [comment]
0.5.2 vom GitHub is the way to go!
