### ISSUE TITLE
Option um Listen nicht zu snchronisieren und Datenpunkte anzulegen

### ISSUE THREAD

**Issue by Rushmed** [Apollon77/ioBroker.alexa2#732]
Hallo,

ich nutze die Listen (ToDo; Shopping...)mit Alexa intesiv, jedoch mit ioBroker garnicht.
Der Adapter generiert mir jedoch zu allen Listeneninträgen Datenpunkte in der DB. Das sind bei mir aktuell etwa 5k.
Ich wäre sehr froh über eine Checkbox in den alexa2 Adaptereinstellungen mit der ich die Synchronistion der Listeneintrage aktivieren/deaktivieren kann.
Evtl. wäre für Leute die es brauchen auch eine Auswahl welche Listen zu synchronisieren sind und welche nicht hilfreich.

Grüße und vielen Dank vorab.

**Comment by Apollon77** [comment]
Will be in next version

**Comment by Apollon77** [comment]
see https://forum.iobroker.net/post/823454

**Comment by Rushmed** [comment]
Vielen Dank, das bringt meine Objecs Liste von 16k auf 11k Einträge.
