### ISSUE TITLE
 Datenpunkt "indicator.reachable" wird nicht aktualisiert

### ISSUE THREAD

**Issue by DickenSerm** [Apollon77/ioBroker.alexa2#734]
Hey, bei mir aktualisiert sich der Datenpunkt "indicator.reachable" von den einzelnen Echo-Devices leider nicht.

Push-Verbindung verwenden ist eingeschaltet.

Wenn ich die Instanz von Alexa2 aber einmal stoppe und wieder starte wird mir im Anschluss der richtige Wert angezeigt.

**Versions:**  
 - Adapter version: 3.9.3
 - JS-Controller version: 3.3.15
 - Node version: 12.20.0
 - Operating system: Ubuntu

**Comment by Apollon77** [comment]
Wie heisst denn der Datneountk genau. "indicator.reachable" ist eine Rolle, nicht der Name

Falls es um den State "online" der Echo-geräte geht dann wird der aktualisiert wenn eine Offline meldung von Amazon kommt. Das kann länger dauern. Am besten mal Debug einschalten und man sieht sehr genau was an Push-Infos reinkommt. Ggf bitte Debug Log bereitstellen

**Comment by DickenSerm** [comment]
Ja, ich Trottel... Natürlich mein ich "online".... hab in der falschen Spalte geguckt. 
Ok, dann is der Datenpunkt wohl eher nicht gedacht zur Anzeige auf dem VIS, ob der Echo im Netz ist oder nicht.

Bin dann jetzt einen Umweg über den TR-064-Adapter gegangen um meine Idee zu realisieren.

Danke für die schnelle Hilfe :)

**Comment by Apollon77** [comment]
Hm ... ok ... willstr Du noch Logs schauen um zu sehen warum es nicht geht oder ok fpr dich? Dann bitte Issue schliessen

**Comment by DickenSerm** [comment]
Alles gut :) ich schließe dann.
