### ISSUE TITLE
Tunein Sender Eingabe funktioniert nicht mehr

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#736]
Moin, 

wenn ich im Datenpunkt `alexa2.0.Echo-Devices.XXXX.Player.TuneIn-Station` einen Sender (sXXXX) Eintrage passiert nix.
nur zur info (bei Nodered das selbe)

[node-red-contrib-alexa-remote2-applestrudel](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/issues/10)

[iobroker Forum](https://forum.iobroker.net/topic/46746/alexa-2-adapter-probleme-bei-musikwiedergabe/31?page=2)

Gruß
Matten Matten

**Comment by Matten-Matten** [comment]
Ich denke Amazon hat sich da mal wieder selbst ein Bug eingebaut....

**Comment by vaaarg** [comment]
schliesse mich an. funktioniert leider nicht mehr

**Comment by rmp63526** [comment]
Leider bei mir das gleich Problem!

**Comment by sigi2345** [comment]
Geht nicht mehr mit den Stationsnummern.

Sendername eingeben bei diesen DP:

![Screenshot (4226)_LI](https://user-images.githubusercontent.com/41079106/131256122-43a8ec99-4212-4596-b9f7-992406744556.jpg)

**Comment by rmp63526** [comment]
@sigi2345 Super, hat geklappt. Danke

**Comment by Matten-Matten** [comment]
Hallo, habe gesehen das hier zu gemacht wurde, funktioniert es wieder?

Gruß
Matten Matten

**Comment by Matten-Matten** [comment]
Ok. Denke auch das wird nicht mehr behoben seitens Amazon. Die wollten sich eigentlich bei mir melden das war im September, seit dem hab ich nichts mehr gehört. Klar geht das auch via Eingabe des Sender Namen aber konkreter war der Sender Schlüssel schon.

Kurze andere frage, mir ist aufgefallen das bei den sender icon links von tunein in letzter Zeit,  immer wieder die Anfrage auf den links nur ein request error erscheint und somit das Senderlogo nicht angezeigt werden kann (auch in der alexa app so, dort wird aber eine musikraute darauf hin als logo angezeigt)

Ist es möglich das irgendwie zu überprüfen ob der request ok ist, dann das logo sonst ein link zu einem anderen Zeichen?

Ich hoffe ich hab mich etwas verständlich ausgedrückt.

**Comment by Apollon77** [comment]
Machst Du bitte ein eigenes Issue auf mit entsprechendem Log ausschnitt bzw details?

**Comment by Matten-Matten** [comment]
Ja, ok mache ich.

**Comment by Apollon77** [comment]
Vllt hab ich ne  idee :-)

https://github.com/thorsten-gehrig/alexa-remote-control/pull/139/files#diff-d1de8cabb9ec3ce099eecfe35b4c43163d1e069bf6758c267925c56e5a525923R724

**Comment by djmarc75** [comment]
Moin.
Da Tante Alexa viele Radiosender nicht erkennt wenn man den Sendernamen in den Datenpunkt "Phrase to play with TuneIn" schreibt, habe ich es in meinem Fall folgend gelöst:
Ich scheibe per Blockly in den Datenpunkt des Echos (egal welcher Echo) "textCommand" den Wert "starte *Sendername* auf *echo*" - in meinem Fall "starte sunshine live auf surround"
Beste Grüße und ein  schönes WE
DerMarc

**Comment by Apollon77** [comment]
Next verison will support again s* ad t* as Station Id
