### ISSUE TITLE
Summary updates

### ISSUE THREAD

**Issue by daniel-lo** [Apollon77/ioBroker.alexa2#738]
Hi, ich wundere mich grad darüber, dass der Zeitstempel von "Summary" aktualisiert wird, obwohl Alexa keine Kommandos erhält. 
Muss das so?

VG

**Comment by daniel-lo** [comment]
Das Ereignis ist Stunden her .. 

![grafik](https://user-images.githubusercontent.com/4311558/130356967-fb1e37da-1930-4bda-ada1-afc9c6468d38.png)

**Comment by Apollon77** [comment]
Ohne Debug Log kann ich nur raten

**Comment by daniel-lo** [comment]
Bekome von einem Skript mit "aktualisieren" .. genau all 5 Minuten eine Pushover-Nachricht .. Debug folgt.

**Comment by daniel-lo** [comment]
[iobroker.2021-08-22.zip](https://github.com/Apollon77/ioBroker.alexa2/files/7027710/iobroker.2021-08-22.zip)


![grafik](https://user-images.githubusercontent.com/4311558/130362439-c738d78e-2198-498d-b009-07f1577c5764.png)

**Comment by daniel-lo** [comment]
Hilfe .. schon blöd wenn man vergisst was man in anderen Skripten so veranstaltet .. SORRY!

**Comment by daniel-lo** [comment]
Der Vollständigkeit halber: Das Problem war, dass ich in textCommand .. alle 5 Minuten was reinschreibe .. und es dann auch bei Summary erscheint.
Nur so ein Gedanke .. könnte man auch ein textCommandSilent einführen .. bei dem die Kommandos ausgeführt werden .. aber nicht in Summary erscheinen?

**Comment by Apollon77** [comment]
Also jetzt wirds schon sehr speziell. Die meisten wollen ggf genaudie Antwoeten von textCommands haben ...

**Comment by daniel-lo** [comment]
Vielleicht verstehen wir uns falsch ...
Ich schreibe alle 5 Minuten in textCommand, dass beim Show5 der Bildschirm ausgehen soll. Funktioniert auch.
Muss der Wert denn auch in Summary erscheinen, damit es funktioniert?

Deshalb war mein Vorschlag 2 Felder zu haben .. textCommand und TextCommandSilent, damit man entscheiden kann ob der Wert in "Summary" auftaucht oder nicht.

Es ist mir auch nicht klar, ob sich mein skriptgesteurtes textCommand mit einem Sprachkommando beißen kann, wenn ich das Summary-Objekt sonstwo als Trigger verwende.

**Comment by Apollon77** [comment]
> Muss der Wert denn auch in Summary erscheinen, damit es funktioniert?

Nein aber er kommt von Amazon zurück in summary. Der adapter müsste sich jetzt merken das "kurz vorher" ein tectcommand gesendet wurde, das dann vergleichen um ggf so eine summary meldung zu unterdrücken - wil es halt in der API von Amazon als Aktion auftauchst fie auch eine ggf textuelle Antwort hat.

Und mit der Frequenz mit der AMazon DInge ändert kann das nur kaputt gehen und daher würd eich den AUfwand sowas zu implementieren und danach lauffähig zu halten gern vermeiden.

**Comment by Apollon77** [comment]
PS: Und wen zufälltig das gleiche textCommand auch per Sprache gesagt wurde kann der Adapter das in den "History Meldungen" nicht unterscheiden.

**Comment by daniel-lo** [comment]
Danke für die Info :-)
