### ISSUE TITLE
Ändern von Multiroom-Zuordnungen | Change of Multiroom-Assignment

### ISSUE THREAD

**Issue by The-Big-M** [Apollon77/ioBroker.alexa2#74]
Es wäre großartig Echo´s aus Multiroom-Gruppen zu entfernen und in Gruppen einzubinden.
||
It would be awesome to remove echo´s from and attach echo´s into multiroom-groups

**Comment by The-Big-M** [comment]
The usecase is simple.
When you have multiple echos and you want to play on a situation-based set of them in multiroom mode. 
Example: I have 1 Echo in the upper floor, 4 in the ground floor and one in the basement.
Situation A: At morning i want to play radio on all 6 speakers.
Situation B: When i sit in the livingroom i want to play on 2 speakers, living and Diningroom
Situation C: When we have a party i want to play music only in the ground Floor
Situation D: In business-times i want to play in the office, the kitchen and the guest-bath

a new id sounds bad…

it would be so easy, when multiple Group-memberships are made possible :(

**Comment by Apollon77** [comment]
What I could possibly do is allow to edit the "members" of an existing ultiroom group but this would mean that one device will always be different according to the current members ... I do not know if this  is really possible to handle (and also remember what the current status is) ...

**Comment by The-Big-M** [comment]
ok, but that sounds interesting.
is in your programming-interface a membership from one echo in multiple groups possible?

**Comment by Apollon77** [comment]
I expect that Alexa-APIs will not allow this to be set, so no

**Comment by The-Big-M** [comment]
after the last update of the alexa-app the problem is solved. now every device can be member of multiple groups.

**Comment by Apollon77** [comment]
I love self-solving issues ;-)
