### ISSUE TITLE
Echo Button Routine Name unknown

### ISSUE THREAD

**Issue by botak13** [Apollon77/ioBroker.alexa2#747]
Hallo.

Im Beitrag #332 gab es das Problem das die Routinen als unknown angezeigt wurden und nicht funktionierten.

Ich weiß das Problem ist schon etwas länger gelöst aber kann es sein das es bei einer Routine die als Auslöser den Echo Button hat immer noch das Problem besteht?
Wenn ich z.B. eine Routine erstelle welche ein Sprachbefehl als Auslöser hat funktioniert alles perfekt..

Viele Grüße.

**Comment by Apollon77** [comment]
So etwas gab es damals noch nicht.

Bitte Adapter Loglevel auf Debug setzen dann neu starten. Von dem Neustart bitte das Log aus dem Logfile auf Disk holen (/opt/iobroker/log/...) und mit per email an iobroker@fischer-ka.de unter nennung dieses Issues senden.
Bitte Details angeben wie zb was diese Echo-Button Routine tut oder so das ich sie finden kann.

Danke

**Comment by botak13** [comment]
Hallo

Die Routine soll über Blockly (Echo alles aus) wenn der Wert sich ändert (Button betätigen) den Toggle vom enigma2 Adapter steuern.

Vielen Dank und Gruß.


Von: Ingo Fischer
Gesendet: Montag, 6. September 2021 23:49
An: Apollon77/ioBroker.alexa2
Cc: botak13; Author
Betreff: Re: [Apollon77/ioBroker.alexa2] Echo Button Routine Name unknown(#747)

So etwas gab es damals noch nicht.
Bitte Adapter Loglevel auf Debug setzen dann neu starten. Von dem Neustart bitte das Log aus dem Logfile auf Disk holen (/opt/iobroker/log/...) und mit per email an ***@***.*** unter nennung dieses Issues senden.
Bitte Details angeben wie zb was diese Echo-Button Routine tut oder so das ich sie finden kann.
Danke
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Apollon77** [comment]
Ahhb das heisst Du möchtest in ioBroker darauf reagieren können wenn die Routine ausgelöst wurde? Das wird so nicht funktionieren!

Bei den Stimmgesteuerten Routinen funktioniert es so das sich der Adapter die Stimmkommandos merkt und dann  wenn ein Sprachkommando mit gleichem Text in der Sprach-History erkannt wurde annimmt das jetzt die Routine gelaufen ist und damit auch das Flag setzt. Das ist am Ende eine Annahme und Raten. Das kann auch schieff gehen.

Der Echo Button hat keinen text und daher kann das nicht erkannt werden.

Also ja das Log wäre interessant um hie was anderes als "Unbekannt" anzeigen zu können - aber das wird nicht ermöglichen das der Trigger erkannt wird.

Workaround hier wäre ein Smart-Home device als Button zu definieren und über den iot Adapter anzubieten in Alexa und dann die Routine diesen Button drücken zu lassen. Dann hat man einen State Change in ioBroker und kann darauf reagieren.

**Comment by botak13** [comment]
Hallo

So habe nun eine Variable erstellt welche in der Alexa App als Smart Device gefunden wird und habe ein kleines Blockly erstellt welches den TV Receiver togglet sobald die Variable aktualisiert wurde. Da ich keine Möglichkeit in der Alexa App gefunden habe zu togglen. Entweder An oder Aus aber egal mit der Aktualisierung konnte ich da Problem lösen.

Vielen Dank für deinen Denkanstoß.


Von: Ingo Fischer
Gesendet: Dienstag, 7. September 2021 07:28
An: Apollon77/ioBroker.alexa2
Cc: botak13; Author
Betreff: Re: [Apollon77/ioBroker.alexa2] Echo Button Routine Name unknown(#747)

Ahhb das heisst Du möchtest in ioBroker darauf reagieren können wenn die Routine ausgelöst wurde? Das wird so nicht funktionieren!
Bei den Stimmgesteuerten Routinen funktioniert es so das sich der Adapter die Stimmkommandos merkt und dann wenn ein Sprachkommando mit gleichem Text in der Sprach-History erkannt wurde annimmt das jetzt die Routine gelaufen ist und damit auch das Flag setzt. Das ist am Ende eine Annahme und Raten. Das kann auch schieff gehen.
Der Echo Button hat keinen text und daher kann das nicht erkannt werden.
Also ja das Log wäre interessant um hie was anderes als "Unbekannt" anzeigen zu können - aber das wird nicht ermöglichen das der Trigger erkannt wird.
Workaround hier wäre ein Smart-Home device als Button zu definieren und über den iot Adapter anzubieten in Alexa und dann die Routine diesen Button drücken zu lassen. Dann hat man einen State Change in ioBroker und kann darauf reagieren.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Apollon77** [comment]
SHould be fixed in next version

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/56021/alexa2-adapter-3-13-0-beta
