### ISSUE TITLE
Bei jeden Raspberry Neustart setzt Alexa Instanz neue Wecker Echo Show

### ISSUE THREAD

**Issue by djlex83** [Apollon77/ioBroker.alexa2#748]
Hallo

Hab das Problem das bei jeden Neustart von Raspberry Pi4 die Alexa Instanz stündlich neue Wecker Alexa Echo Show 8 2. Generation stellt.
Bei Neustart der Alexa Instanz werden keine neue Wecker gestellt.

Es wird auch auf Alexa show 8 1.Gen gestellt da ich im Netzwerk 2 Alexas hab. Aber unterschiedliche Accounts. Mit 2 verschieden Instanzen.

Log Datei:
Poste ich hier nicht gerne das private Daten enthalten sind.

Adapter version 3.9.3
JS Controller 3.3.17
Node 12.22.6

Raspberry Pi4

**Comment by Apollon77** [comment]
Der Adapter macht rein gar nichts. Kann es sein das irgendein Skript von Dir beim Start DInge tut? Das ist bestimmt wahrscheinloicher.

Checke das mal indem du zb die javascript instanz der die relevanten skripte neu startest
