### ISSUE TITLE
Echo Flex keine Befehle Möglich?

### ISSUE THREAD

**Issue by StephanWagner87** [Apollon77/ioBroker.alexa2#749]
Hi,

wieso fehlen bei dem Echo Flex die "Commands" in der Struktur? Also bei dem Echo Dot tauchen die auf aber beim Flex nicht. Also aus der App raus kann der ja auch Speak und Alarm usw. machen

<img width="514" alt="image" src="https://user-images.githubusercontent.com/49068001/134646426-15483915-d2e3-42f8-b920-85b56a90d94f.png">

**Comment by Pocky2507** [comment]
Mal den Ordner öffnen?

**Comment by StephanWagner87** [comment]
> Mal den Ordner öffnen?

unter dem "Echo Flex" gibt es nur den "Info" Ordner. Der Ordner Command den man im Screenshot sieht gehört ja zu dem Echo Dot. Dort passt auch alles und genau den Ordner habe ich halt auch unter dem Echo Flex erwartet.

**Comment by Apollon77** [comment]
Welche device-ID und welche capabilities sind in info gelistet?

**Comment by StephanWagner87** [comment]
hat sich erledigt. habe jetzt mal nen System update gemacht und jetzt taucht die Ordnerstruktur auf. zwar komisch aber egal :) vielen dank
