### ISSUE TITLE
unknown command Push_Media_Change

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.alexa2#75]
Hab den hier im Log:

 alexa2.0 Alexa-Push-Connection Unknown Command PUSH_MEDIA_CHANGE - send to Developer: {"destinationUserId":"A3NT1OXG4QHVPX","mediaReferenceId":
"71c4d721-0e94-4b3e-b912-e1f27fcebba1:1","dopplerId":{"deviceSerialNumber":"G000JN0573370K82","deviceType":"A1NL4BVLQ4L3N3"}}

**Comment by Apollon77** [comment]
Thank you. Will be handled by next version.

**Comment by Apollon77** [comment]
Was war denn die Aktion davor?

**Comment by Ilovegym66** [comment]
tja.. wenn ich das wüsste.. heute nichts mehr davon im log... die Funktionen sind die gleichen wie gestern...  ich behalt es im Auge und schau, ob ich n Script oder was auch immer damit in Verbindung bringen kann...

**Comment by Ilovegym66** [comment]
Radio eingeschaltet, und schon kam der Fehler.. 
Schreibe 
s2627 in alexa2.0.Echo-Devices.G000JN0573370K82.Player.TuneIn-Station
und schon kommt der Logeintrag.
ist ein Echo Show.

**Comment by Apollon77** [comment]
Vllt ist es was der Show im Display anzeigen soll ... aber egal. nächste Version kennt es dann und reagiert darauf mit einem Player-Update :-)
