### ISSUE TITLE
Alexa-Remote WS-MQTT: Retry Connection in [XX] seconds

### ISSUE THREAD

**Issue by roesthod** [Apollon77/ioBroker.alexa2#751]
Hi all,
I'm facing since a few days connection/authentification issues with ioBroker.alexa2 adapter.

Details:
Environment: 3 seperate amazon accounts, each account support one instance of the adapater supporting one device
Adapter and instances have been recreated and new cockies have been re-created - all successfull

Issue:
Adapter debug log shows:
Alexa-Remote WS-MQTT: Open: https://dp-gw-na.amazon.de/?x-amz-device-type=ALEGCNGL9K0HM&x-amz-device-serial=262-9895388-3492023-XXXXXXXXXX
Alexa-Remote WS-MQTT: Initialization Msg 1 sent
Alexa-Remote WS-MQTT: Close: 1005:
Alexa-Remote WS-MQTT: Retry Connection in 15s

I tried URL and got authentification issue.
What can I do ???

Many thanks for your support in advanced,
Thorsten

**Comment by Apollon77** [comment]
duplicate #570
