### ISSUE TITLE
Triggeren von Alarm wird nicht aktualisiert bei neue Wecker

### ISSUE THREAD

**Issue by gcaruso73** [Apollon77/ioBroker.alexa2#76]
Wenn über echo eine neue Wecker gestellt wird, wird das Objekt Triggered nicht automatisch mit true aktualisiert wenn der Wecker klingelt.

Bei manuelle Änderung der Weck zeit und Aktivierung der Wecker über iobroker dann wird das Objekt Triggered automatisch aktualisiert.

Hier ein debug log von nicht aktualisierte Triggered beim klingeln:
[Debug Log - Nicht aktualisierte Triggered.txt](https://github.com/Apollon77/ioBroker.alexa2/files/2306415/Debug.Log.-.Nicht.aktualisierte.Triggered.txt)

Hier ein debug log von aktualisierte Triggered nach manuelle Änderung des Weckers:
[Debug Log - Aktualisierte Triggered.txt](https://github.com/Apollon77/ioBroker.alexa2/files/2306419/Debug.Log.-.Aktualisierte.Triggered.txt)

**Comment by Apollon77** [comment]
Reason found, solution will come with 0.6.0 in some days

**Comment by gcaruso73** [comment]
Bei version 0.6.1 geht wieder einwandfrei.
