### ISSUE TITLE
Support for Lenovo Smart Tab M10

### ISSUE THREAD

**Issue by ahnungsbefreit** [Apollon77/ioBroker.alexa2#760]
Lenovo Smart Tab M10 (Android Tablet with Docking Station supporting Alexa when docked as Screen Saver) is not supported by the Adapter today. This is what I get from the log:

`2021-10-01 09:50:31.645 - info: alexa2.0 (2367) Device-type:A3V88YODYKUDL4 (SET_LOCALE,SALMON,EARCONS,ASCENDING_ALARM_VOLUME,DEEZER,SUPPORTS_LOCALE_SWITCH,I_HEART_RADIO,GADGETS,KINDLE_BOOKS,AUDIBLE,CUSTOM_ALARM_TONE,PERSISTENT_CONNECTION,SHARKNADO,NO_TIME_ZONE_SETTING,SUPPORTS_LOCALE,SLEEP,REMINDERS,SIRIUSXM,ADAPTIVE_LISTENING,TIMERS_AND_ALARMS,APPLE_MUSIC,DREAM_TRAINING,MICROPHONE,FLASH_BRIEFING,GOLDFISH,MUSIC_SKILL,TUNE_IN,POPTART,PANDORA,FAR_FIELD_WAKE_WORD,TIDAL,SOUND_SETTINGS,VOICE_TRAINING,AUDIO_PLAYER,CHANGE_NAME,AMAZON_MUSIC,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,VOLUME_SETTING)`

Could you please include this in one of the next versions? Many thanks!

**Comment by Apollon77** [comment]
Are commands working whyn pyu create them via Routines?

**Comment by ahnungsbefreit** [comment]
No, that's what I am missing

**Comment by Apollon77** [comment]
The question is: SAre Commands working when you try to do them on the device with the Alexa Handy App and Routines?

IF they are not working using the Alexa App there is no point to add it to the adapter because it will also not working. Thin it is a limitation of the device

**Comment by ahnungsbefreit** [comment]
When using other Alexa devices e.g. echo, they do work. Not sure this answers your question...

**Comment by Apollon77** [comment]
No. Please open the Alexa App, create a routine and use "speak a text" or such and see if you can selecxt the device in question as the target. and test it. If you can not select that device for the routine then the device (your Lenovo Smart Tab) do not support it

**Comment by ahnungsbefreit** [comment]
Understood. I cannot select the device in the app. However, if I let Alexa answer from the device that has been asked, it works.
