### ISSUE TITLE
Alarm - affected days

### ISSUE THREAD

**Issue by Bias313** [Apollon77/ioBroker.alexa2#763]
Currently there is no way to find out via the adapter which alarms are pending TODAY. The enabled flag is not useful for this, as repeating alarms (e.g. weekdays or every Monday) are enabled even on unaffected days.
In the Alexa app, there is a label for each alarm that informs how much time is left until the next ring. This information would also be helpful in ioBroker to be able to start routines depending on the alarm clock. Alternatively, the information could be used to calculate and output a DateTime for the next ring.

Use case: Start morning routines even before the Alexa alarm rings. E.g. light alarm, coffee machine, shutters, air purifiers etc..

**Comment by Apollon77** [comment]
Please provide a screenshot which label you mean

**Comment by Bias313** [comment]
![20211106_191636](https://user-images.githubusercontent.com/5166272/140619889-70c0925e-1040-497b-a7fa-56e3a7b34093.jpg)
![20211106_191742](https://user-images.githubusercontent.com/5166272/140619892-e58efa7e-add1-44fa-97f6-48e71c407e98.jpg)

**Comment by Bias313** [comment]
Feature still not implemented. This ticket is not outdated

**Comment by Bias313** [comment]
Feature still not implemented. This ticket is not outdated

**Comment by Apollon77** [comment]
Nexzt verison will contain more states on info for the alarms and also a nextTriggerTimestamp with a calculated value when this alarm triggers next

**Comment by Bias313** [comment]
> 
Sounds great – thank you very much!

**Comment by Apollon77** [comment]
have fun https://forum.iobroker.net/post/824793
