### ISSUE TITLE
speak funktioniert nicht auf allen EchoDevices

### ISSUE THREAD

**Issue by RTO74** [Apollon77/ioBroker.alexa2#767]
Ich versuche Sprachausgabe auf verschiedenen Echos / Echodots über den Adapter zu bekommen. Ein EchoDot funktioniert. Ein Echo und ein anderer EchoDot schweigen.
Ich habe die Version 3.11.2 des Adapters installiert.

Was kann man tun, damit auch die anderen Echos den Text als Sprache ausgeben?

Anbei ein Auszug aus dem Debug Log.
Dabei hab ich in dem Objekt eines Echodots den Wert "nichtssagend" in das speak Feld eingegeben. Es kommt aber keinerlei Ton raus.
[Alexa2.0 Debug Log](https://github.com/Apollon77/ioBroker.alexa2/files/7365307/Alexa2.0.Debug.Log)

**Comment by DL84RTO** [comment]
Ich hab das jetzt noch mal auf 3 verschiedenen Geräten getestet.
2 geben keinen Muks aus und bei einem geht es. Bei dem kommen auch ganz viele Log Einträge aber bei den anderen Beiden kommt nichts mehr. 
Vielleicht liegt das an den verschiedenen Typen?
Typ 1 ist ein Echo Dot 3.Gen (Speak= "Sag was")
Typ 2 ist ein Echo 2.Gen (Speak = "Test")
Typ 3 ist ein Echo Dot 3.Gen (Speak = "Hier geht es")
Und wie ich das grad so aufschreibe, fällt mir auf, das 1 und 3 die gleichen Typen sind, also kann es das ja eigentlich nicht sein.

Ich hab auch schon den Adapter komplett gelöscht und wieder installiert. Ohne Erfolg.
Was kann das sein?
[debug-log2.txt](https://github.com/Apollon77/ioBroker.alexa2/files/7367850/debug-log2.txt)

**Comment by DL84RTO** [comment]
Ich hab noch eine Vermutung.
Vielleicht liegt es an verschiedenen Konten. Der Echo und der EchoDotKeller sind auf meine Frau angemeldet und da geht die Sprachausgabe nicht. Der eine, der geht, ist auf mich angemeldet. Der Adapter läuft auch auf meinen Login. Könnte das eine Lösung sein? Mir ist auch aufgefallen, dass ich in dem Adapter keine Routinen sehe. In der alexa App sind aber Routinen drin. Hängt vielleicht auch mit den Konten zusammen.

**Comment by Apollon77** [comment]
Dann nehm ich trotzdem gern das Log von 1..3 ... vllt sehe ich ja was :-)

**Comment by Apollon77** [comment]
Bitte mal die GitHub Version versuchen ... geht die besser?

**Comment by Apollon77** [comment]
Next try please

**Comment by Apollon77** [comment]
Fixed in next version
