### ISSUE TITLE
Feature  FireTV steuern

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.alexa2#77]
besteht die Möglichkeit, die FireTV zu steuern, wie es der FireTV Adapter kann, wenn er funktioniert...
:-)
Die haben ja über die Debugfunktion und ADB ne direkte Schnittstelle.. 
Da die FireTV sowieso im Alexa Adapter angezeigt werden, dachte ich, könnte man das kombinieren und den FireTV-Adapter dann entsorgen..

**Comment by Apollon77** [comment]
Nein wir mischen keine Funktionen.

Alexa-Adapter kann das was Alexa-App bzw Alexa APIs können.

**Comment by sigi2345** [comment]
[https://forum.iobroker.net/viewtopic.php?f=37&t=15547&hilit=tv&start=500#p168346](url)

**Comment by Apollon77** [comment]
schau mal ... vllt jetzt? https://forum.iobroker.net/viewtopic.php?f=37&t=16095&p=173376#p173376
