### ISSUE TITLE
state volume is not updated 

### ISSUE THREAD

**Issue by MotschaM** [Apollon77/ioBroker.alexa2#771]
- Adapter version: 3.9.3
 - JS-Controller version: 3.3.18
 - Node version: v16.13.0
 - Operating system: Linux (Raspberry 4) 

since a short time the state volume is not updated anymore. 
When I change the volume on the Echo device. Previously, this worked. 
But if I change the value itself, then the volume is really changed.

**Comment by Apollon77** [comment]
Update adapter
