### ISSUE TITLE
Smarthome Status wird bei Sprachbefehl nicht aktualisiert

### ISSUE THREAD

**Issue by millenium1980** [Apollon77/ioBroker.alexa2#777]
Ich habe mehrere smarte Steckdosen. Diese werden auch alle aufgelistet, und ich kann sie mit den Werten "true/false" problemlos schalten. Wenn ich nun aber die Steckdose per Sprachbefehl einschalte, wird der Wert "power state" in iobroker nicht auf true gesetzt..

Lässt sich das realisieren?

**Comment by Apollon77** [comment]
Nope, siehe Readme ... Smart device status changes werden nicht gepusht, können also nur gepollt werden ...
