### ISSUE TITLE
Echo Flex  : Unknown Device, but enabling commands

### ISSUE THREAD

**Issue by sigi2345** [Apollon77/ioBroker.alexa2#779]
Hallo,

Meldung:
Unknown Device, but enabling commands

device: Echo Flex

deviceType:
A3VRME03NAXFUB
(TIMERS_AND_ALARMS,MICROPHONE,DIALOG_INTERFACE_VERSION,SHARKNADO,CHANGE_NAME,PERSISTENT_CONNECTION,ARTHUR_TARGET,BT_PAIRING_FLOW_V2,FLASH_BRIEFING,SOUND_SETTINGS,MULTI_WAKEWORDS_SUPPORTED,VOLUME_SETTING,PAIR_BT_SINK,CUSTOM_ALARM_TONE,SPEECH_RECOGNIZER_USS,SUPPORTS_LOCALE_SWITCH,ASCENDING_ALARM_VOLUME,SUPPORTS_SOFTWARE_VERSION,SUPPORTS_LOCALE,ADAPTIVE_LISTENING,EARCONS,ACTIVE_AFTER_FRO,REMINDERS,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY)

Alexa2  : Installierte Version: 3.12.0

System:
Plattform: Windows
RAM: 16 GB 
Node.js: 12.22.7
NPM: 6.14.15
JS Controller: 3.3.18
Admin: 5.1.28
Web: 3.4.13

**Comment by Apollon77** [comment]
Please reinstall ... the code shows that the device is in the list and there was nothign added after 3.12.0 release

**Comment by Apollon77** [comment]
https://github.com/Apollon77/ioBroker.alexa2/blob/master/main.js#L140

**Comment by sigi2345** [comment]
> Please reinstall ... the code shows that the device is in the list and there was nothign added after 3.12.0 release

Meldung kommt noch immer

**Comment by Apollon77** [comment]
Schaust du mal in node_modules/iobroker.alexa2/package.json das dich richtige Version drin ist und in main.js ob der String  device Type) vorkommt?

**Comment by sigi2345** [comment]
> Schaust du mal in node_modules/iobroker.alexa2/package.json das dich richtige Version drin ist und in main.js ob der String device Type) vorkommt?

1: ja
2: nein

**Comment by Apollon77** [comment]
Also wenn ich die iobroker.alexa2 3.12.0 installiere ist die Zeile bei mir drin ... whaat?

**Comment by sigi2345** [comment]
> Also wenn ich die iobroker.alexa2 3.12.0 installiere ist die Zeile bei mir drin ... whaat?

Jetzt drinnen, aber noch da

**Comment by Apollon77** [comment]
dann restarte mal adapter ..

**Comment by sigi2345** [comment]
> dann restarte mal adapter ..

`<html>
<body>


alexa2.0 | 2021-11-16 14:56:00.390 | info | Device-type:A3EVMLQTU6WL1W (SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,CHANGE_NAME,SHARKNADO,ACTIVE_AFTER_FRO,PERSISTENT_CONNECTION,VOLUME_SETTING,FLASH_BRIEFING,MICROPHONE,SUPPORTS_LOCALE,SOUND_SETTINGS,REMINDERS,BT_PAIRING_FLOW_V2,SPEECH_RECOGNIZER_USS,CUSTOM_ALARM_TONE,EARCONS,ARTHUR_TARGET,SUPPORTS_LOCALE_SWITCH,MULTI_WAKEWORDS_SUPPORTED,SUPPORTS_SOFTWARE_VERSION,PAIR_BT_SINK,ASCENDING_ALARM_VOLUME,TIMERS_AND_ALARMS,DIALOG_INTERFACE_VERSION,ADAPTIVE_LISTENING)
-- | -- | -- | --
alexa2.0 | 2021-11-16 14:56:00.390 | info | Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2021-11-16 14:56:00.389 | info | Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2021-11-16 14:55:59.762 | info | Alexa-Push-Connection (macDms = true) established. Disable Polling
alexa2.0 | 2021-11-16 14:55:56.811 | info | Proxy IP not set, use first network interface (192.168.178.20) instead
alexa2.0 | 2021-11-16 14:55:56.678 | info | starting. Version 3.12.0 in C:/Program Files/iobroker/Home/node_modules/iobroker.alexa2, node: v12.22.7, js-controller: 3.3.18
alexa2.0 | 2021-11-16 14:55:51.859 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
alexa2.0 | 2021-11-16 14:55:51.858 | info | terminating
alexa2.0 | 2021-11-16 14:55:51.856 | info | Got terminate signal TERMINATE_YOURSELF


</body>
</html>`

**Comment by Apollon77** [comment]
Ja bitte ... wtf ... Das darf an such nicht kommen wenn der deviceTyp in der Liste im main.js ist

**Comment by sigi2345** [comment]
> Ja bitte ... wtf ... Das darf an such nicht kommen wenn der deviceTyp in der Liste im main.js ist

Kommt noch, aber eine anderer device Typ

A3EVMLQTU6WL1W

**Comment by Apollon77** [comment]
ahhhh ... also ists gar nicht der Flex ... ok ... und was geht mit dem? Commands?

**Comment by H0Krab** [comment]
Hi kann mir einer sagen wo hier das Problem ist? 
Ich finde den A19VUBUHBHGZ2  auc nicht in  https://github.com/Apollon77/ioBroker.alexa2/blob/master/main.js#L140
Adapter habe ich bereits neu installiert. Muss dazu sagen , es handelt sich um eine 2. Instanz

Dazu kommt auch noch der folgende Hinweis:  
(30779) Alexa-Push-Connection disconnected - retry: Retry Connection in 45s

Sowie:
(30779) Device-type:A19VUBUHBHGZ2 (I_HEART_RADIO,VOLUME_SETTING,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,AUDIO_PLAYER,MICROPHONE,DREAM_TRAINING,APPLE_MUSIC,MUSIC_SKILL,SLEEP,ADAPTIVE_LISTENING,DEEZER,TU
--

**Comment by Apollon77** [comment]
@H0Krab Wenn er ein Device als unbekannt meldet ist das ganz normal ...  diene ID wurde auch hier noch gar nicht genannt. Frage: gehen comands auf dem gerät? Was ist es denn?

Wegen Retry ... Ist die 3.11/12.0 installiert?

**Comment by sigi2345** [comment]
> ahhhh ... also ists gar nicht der Flex ... ok ... und was geht mit dem? Commands?

So wie der normale Fire TV Stick nur mit wifi 6

Es gibt 4 Versionen:

![Screenshot (4445)](https://user-images.githubusercontent.com/41079106/142185812-ebfd8460-d16c-4520-9e4a-865731a4ea7f.png)

**Comment by Apollon77** [comment]
@H0Krab missing info still what device type A19VUBUHBHGZ2 is ... please report in new issue

Flex and Echo Show 8 fixed in next version
