### ISSUE TITLE
alexy 2.0/History/name nicht aktuell

### ISSUE THREAD

**Issue by mandre1904** [Apollon77/ioBroker.alexa2#78]
Hallo,

ich gehe davon aus, dass unter alexy 2.0 -> History -> name das Echo Device eingetragen sein sollte, welches zuletzt angesprochen wurde.
Dies ist allerdings leider nicht der Fall.

Deute ich die Variable falsch oder handelt es sich hier um einen Bug/Fehler?

Es geht darum, dass ich die Antwort von Alexa auf meine Frage natürlich auf dem Gerät ausgeben lassen möchte, welches ich frage.

Danke

/erledigt
Datenaktualisierungsintervalle anpassen

**Comment by Apollon77** [comment]
So solved for you?

Viel besser als die Intervalle ist die Push-Verbindung. Dann ist es immer aktuell!!
In der konfig einschalten.

**Comment by Apollon77** [comment]
Bitte neu öffnen wenn noch offen.
