### ISSUE TITLE
Lists.SHOPPING_LIST.items.*.listName has no existing object + TO_DO

### ISSUE THREAD

**Issue by Alex71w** [Apollon77/ioBroker.alexa2#781]
This bug has been mentioned in [Issue 655](https://github.com/Apollon77/ioBroker.alexa2/issues/655), but the thread is closed. I encounter the same issue since 15.11.21 18:57 for the To Do and the Shopping list.

<html>
<body>

Quelle | Zeit | debug | Nachricht
-- | -- | -- | --
alexa2.0 | 2021-11-18 10:01:41.835 | warn | State "alexa2.0.Lists.TO_DO.items.952292d4-606d-4eb5-879a-e544dea60975.listName" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:01:41.834 | warn | State "alexa2.0.Lists.TO_DO.items.952292d4-606d-4eb5-879a-e544dea60975.#delete" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:01:41.832 | warn | State "alexa2.0.Lists.TO_DO.items.952292d4-606d-4eb5-879a-e544dea60975.index" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:01:41.831 | warn | State "alexa2.0.Lists.TO_DO.items.952292d4-606d-4eb5-879a-e544dea60975.version" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:01:41.830 | warn | State "alexa2.0.Lists.TO_DO.items.952292d4-606d-4eb5-879a-e544dea60975.value" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:01:41.829 | warn | State "alexa2.0.Lists.TO_DO.items.952292d4-606d-4eb5-879a-e544dea60975.updatedDateTime" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:01:41.827 | warn | State "alexa2.0.Lists.TO_DO.items.952292d4-606d-4eb5-879a-e544dea60975.shoppingListItem" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:01:41.826 | warn | State "alexa2.0.Lists.TO_DO.items.952292d4-606d-4eb5-879a-e544dea60975.listId" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:01:41.825 | warn | State "alexa2.0.Lists.TO_DO.items.952292d4-606d-4eb5-879a-e544dea60975.id" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:01:41.824 | warn | State "alexa2.0.Lists.TO_DO.items.952292d4-606d-4eb5-879a-e544dea60975.customerId" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:01:41.822 | warn | State "alexa2.0.Lists.TO_DO.items.952292d4-606d-4eb5-879a-e544dea60975.createdDateTime" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:01:41.820 | warn | State "alexa2.0.Lists.TO_DO.items.952292d4-606d-4eb5-879a-e544dea60975.completed" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:00:20.209 | warn | State "alexa2.0.Lists.SHOPPING_LIST.items.dc037af6-5a21-4b88-9be8-60cafc36f462.listName" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:00:20.208 | warn | State "alexa2.0.Lists.SHOPPING_LIST.items.dc037af6-5a21-4b88-9be8-60cafc36f462.#delete" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:00:20.207 | warn | State "alexa2.0.Lists.SHOPPING_LIST.items.dc037af6-5a21-4b88-9be8-60cafc36f462.index" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:00:20.206 | warn | State "alexa2.0.Lists.SHOPPING_LIST.items.dc037af6-5a21-4b88-9be8-60cafc36f462.version" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:00:20.206 | warn | State "alexa2.0.Lists.SHOPPING_LIST.items.dc037af6-5a21-4b88-9be8-60cafc36f462.value" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:00:20.205 | warn | State "alexa2.0.Lists.SHOPPING_LIST.items.dc037af6-5a21-4b88-9be8-60cafc36f462.updatedDateTime" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:00:20.204 | warn | State "alexa2.0.Lists.SHOPPING_LIST.items.dc037af6-5a21-4b88-9be8-60cafc36f462.shoppingListItem" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:00:20.203 | warn | State "alexa2.0.Lists.SHOPPING_LIST.items.dc037af6-5a21-4b88-9be8-60cafc36f462.listId" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:00:20.202 | warn | State "alexa2.0.Lists.SHOPPING_LIST.items.dc037af6-5a21-4b88-9be8-60cafc36f462.id" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:00:20.201 | warn | State "alexa2.0.Lists.SHOPPING_LIST.items.dc037af6-5a21-4b88-9be8-60cafc36f462.customerId" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:00:20.200 | warn | State "alexa2.0.Lists.SHOPPING_LIST.items.dc037af6-5a21-4b88-9be8-60cafc36f462.createdDateTime" has no existing object, this might lead to an error in future versions
alexa2.0 | 2021-11-18 10:00:20.198 | warn | State "alexa2.0.Lists.SHOPPING_LIST.items.dc037af6-5a21-4b88-9be8-60cafc36f462.completed" has no existing object, this might lead to an error in future versions

</body>
</html>

The functionality, adding items via echo to the lists, still works fine.

I already tried to delete the object tree within the iobroker, and after restarting the Alexa-adapter the object tree has been created new - but with the same entrys and the same log warn-entries show up.
I also see, that the object "UpdatedDate" has the value "Wed Apr 21 2021 20:16:59 GMT+0200 (Mitteleuropäische Sommerzeit)", but I added entries today, so this value seems to be invalid.

I am using these lists since many month and never had such problems, so I think whether there was a change on Amazons side, or in the adapter.

Alexa adapter version: 3.11.2, updated on 13.11.21
JS-Controller: 3.3.18
Node.js: v12.22.7
NPM: 6.14.15
Modell: Raspberry ARMv7 Processor rev 4 (v7l)

First encounter of the issue: 15.11.21 18:57, since then with every usage of echo to add list items.

I can attach the corresponding logfiles, if helpfull.
As the alexa debug log contains many sensible infos I do not attach it here, but I can provide it if necessary.

**Comment by Apollon77** [comment]
Please check with 3.12.0 becsusde eas fixed tehre

**Comment by Alex71w** [comment]
Thanks, yes, it fixed the issue! Great work, many thanks for your support and effort for iobroker!
