### ISSUE TITLE
New state for 'remaining playtime'

### ISSUE THREAD

**Issue by oberstel** [Apollon77/ioBroker.alexa2#784]
As a power user, I woulkd like to have a state which shows the remaining playtime of the active media.
Something like...: _mediaRemainingStr_ =  _mediaLengthStr_ - _mediaProgressStr_ in the format (hh:)mm:ss

Would be nice if you guys could implement an appropriate state to make my VIS nice and fancy ;-)

**Comment by Apollon77** [comment]
done in next version
