### ISSUE TITLE
Commands für Alexa App Geräte (Android/iPhone)

### ISSUE THREAD

**Issue by lammy000** [Apollon77/ioBroker.alexa2#785]
Hi,

ich möchte gerne die Sprachausgabe auf meiner Alexa App meines Handys nutzen. Könnt ihr das möglich machen?

Besten dank!

**Comment by Apollon77** [comment]
DIe Frage ist ob das überhaupt geht ...

**Comment by Apollon77** [comment]
Done in next version

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/56021/alexa2-adapter-3-13-0-beta
