### ISSUE TITLE
DND mode value is not pushed/pulled to the adapter state if set by Alexa app or voice

### ISSUE THREAD

**Issue by Diginix** [Apollon77/ioBroker.alexa2#786]
If I set the DND mode of my Echo Dot 3 in Alexa app or by voice, the state "alexa2.0.Echo-Devices.???.Commands.doNotDisturb" value isn't updated. Even an adapter restart doesn't solve this.
Either Amazon's API doesn't support this or it is simply missing.

alexa2 3.12.0
JS-Controller 3.3.19
nodejs 14.18.1

**Comment by Apollon77** [comment]
duplicate #617
