### ISSUE TITLE
Fire HD 10 2021 Unknown Device, but enabling commands

### ISSUE THREAD

**Issue by TomoAZ** [Apollon77/ioBroker.alexa2#787]
Hallo,

Meldung:
Unknown Device, but enabling commands

device: Fire HD 10 2021

Device-type:ATNLRCEBX3W4P (SOUND_SETTINGS,ASCENDING_ALARM_VOLUME,MICROPHONE,EARCONS,SUPPORTS_SOFTWARE_VERSION,REMINDERS,ADAPTIVE_LISTENING,SPEECH_RECOGNIZER_USS,NO_TIME_ZONE_SETTING,MULTI_WAKEWORDS_SUPPORTED,SUPPORTS_LOCALE,ASX_TIME_ZONE,VOLUME_SETTING,CUSTOM_ALARM_TONE,SUPPORTS_LOCALE_SWITCH,DIALOG_INTERFACE_VERSION,PERSISTENT_CONNECTION,TIMERS_AND_ALARMS)

Alexa2 : Installierte Version: 3.12.0

System:
Plattform: Linux Debian 11
RAM: 4 GB
Node.js: v14.18.1
NPM: 6.14.15
JS Controller: 3.3.19
Admin: 5.1.28
Web: 3.4.16

**Comment by Apollon77** [comment]
Und, funktionieren commands?

**Comment by TomoAZ** [comment]
Ich hänge mich mal an den anderen Bug diesbezüglich mir ran, bei mir funktioniert auch kein einizges Speak, Commands kann ich daher aktuell nicht prüfen.

**Comment by Apollon77** [comment]
Dann bitte Downgrade (nach loig zeiehen) auf die 3.11x

**Comment by TomoAZ** [comment]
Downgrade auf 3.11 erfolgt, Logs per Email gesendet. Commands funktioniert (Speak getestet)

**Comment by Redsun1978** [comment]
Das selbe Problem hat mein Fire HD 8 auch. 3.11 Commands da.... alles läuft! Update und der Ordner Commands ist weg?!

**Comment by Apollon77** [comment]
fixed in next version

**Comment by Apollon77** [comment]
Ok, do the device now support commands or not???

**Comment by TomoAZ** [comment]
Mit der neuen Version 3.13.0 bzw Git ist das Tablet nicht mehr verfügbar:
3.11.2:
![grafik](https://user-images.githubusercontent.com/91433553/177197896-a84b5620-f4ce-469d-886c-30574200eaa4.png)
3.13.0:
![grafik](https://user-images.githubusercontent.com/91433553/177198028-5910e0f9-c9b6-4005-90f7-096bb854b10a.png)

**Comment by Apollon77** [comment]
Bitte changelog lesen. Apps müssen nun in der Konfig ggf eingeschaltetwerden das Sie generiert werden

**Comment by Apollon77** [comment]
Please use 3.14 soon for a new log if relevant

**Comment by Apollon77** [comment]
https://forum.iobroker.net/post/823454
