### ISSUE TITLE
Set AUX socket ECHO Gen4

### ISSUE THREAD

**Issue by timae146** [Apollon77/ioBroker.alexa2#789]
**Is your feature request related to a problem? Please describe.**
I use an ECHO Gen 4. on the PC for sound playback by setting the AUX jack to "Line-IN". however, it sometimes happens that the ECHO hangs up when you trigger another audio playback via voice command.

If you stop the direct audio playback on the device, it is unfortunately not automatically switched back to the sound from the "Line-In" (PC).

**Describe the solution you'd like**
The only way to change this is to go into the app and set the AUX jack to "Line-Out" and back to "Line-In".

The less smart alternative would be to disconnect the power supply or the AUX socket of the Alexa device for a short time.

**Additional context**

**Comment by Apollon77** [comment]
Challenge is that thisAPI call to retieve/set this is not yet discovered ... and I do not have such a device :-( We need to see if someone has such - or else you would need to sniff the app traffic - or give me temporary access to the account somehow that I can snif it

**Comment by timae146** [comment]
I can probably provide you with the test account! :)

**Comment by Apollon77** [comment]
Good news ... got today a new Echo and it is also in there, so I could sniff all relevant myself. WIll look into it next days

**Comment by Apollon77** [comment]
will be in next version

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/56437/alexa2-adapter-3-18-x-beta
