### ISSUE TITLE
Volume Echo Dot 3

### ISSUE THREAD

**Issue by andreas0022** [Apollon77/ioBroker.alexa2#791]
Hallo,
habe gesehen, dass sich der Volume-Wert in den Objekten (Player-Volume) nicht ändert, wenn am Echo manuell per + und - das Volume geändert wird. 
Wenn ich den Wert in den Objekten setze, dann wird die richtige Lautstärke an den Dot übertragen.

Das Problem ist nur beim Echo-Dot-3. Beim Echo show 5 funktioniert es, wie gewünscht.

möglicherweise ein Amazon-Problem...

Danke

**Comment by Apollon77** [comment]
Wenn es mit Adapter 3.11.x bei einem Gerätz tut und bei einem anderen nicht kanns erstmal eher nicht am adapter liegen. Wenn auch ein neustart des adapters nicht hilft dann bitte mal debug log aktivieren da sind die "Volume change" events die kommen zu sehen. dort schauen was reinkommt

**Comment by andreas0022** [comment]
Hallo, vielen Dank für die rasche Antwort. 
wenn ich morgens an den Arbeitsplatz komme, dann schalten sich 5 Echos (1x show5 + 4x Dot3) mit einem bestimmten Sender und alle mit volume 40 ein. nun wollte ich, sobald ich das Volume an einem Dot3 ändere (mit + und - Taste am Gerät), sich auch das Volume der anderen Dots ändert (über JS, blockly). aber die Änderung des volumes kommt nicht in den Objekten an, es bleibt immer die anfangs eingestellten 40. es handelt sich um die Geräte mit den Endungen N6F, DUS, A5K, TLT und 12P. siehe screenshot anbei. debug log ist auch dabei. habe während der Debug-log Aufzeichung die volumes an den Geräten N6F und A5K geändert.
Danke

[debug-log01_12_21_alexa2.txt](https://github.com/Apollon77/ioBroker.alexa2/files/7631412/debug-log01_12_21_alexa2.txt)
![screenshot_objects](https://user-images.githubusercontent.com/54526221/144184912-5f47a3c2-80fa-4eec-8b7d-7173a79d0ecd.jpg)

**Comment by BatmanN8** [comment]
Hallo,
ich habe genau das gleiche Problem. Gibts da mittlerweile eine Lösung?
Änderungen die über Sprache oder manuell direkt am Echo geändert werden, werden in den Objekten unter Player-> Volume nicht geändert. Der weg anders rum funktioniert ohne Probleme. Das habe ich mit zwei Dot 3 und einem Dot 2 reproduzieren können. Starte ich den Adapter neu werden die in dem Moment vorhandenen Lautstärken übrigens richtig gesetzt. Getest mit 3.11.2 und 3.12.0

**Comment by Apollon77** [comment]
Bitte Loglevel auf Debug stellen und Log von so einer Volume Änderung per Sprache zeigen ... bzw auch beim Start nach Logs mit "wsmqtt" schauen

**Comment by BatmanN8** [comment]
nach dem ich den Adapter zum zweimal neu installiert habe funktioniert alles!

**Comment by Apollon77** [comment]
Assumed fixed?
