### ISSUE TITLE
FireHD 10 (2021) Tablet, keine Commands gelistet

### ISSUE THREAD

**Issue by stony2k** [Apollon77/ioBroker.alexa2#792]
Adapter Version 3.11.2, sowie die Github Version 3.12.0 getestet.

Bei meinem Fire HD 10 (2021) sind keine Commands gelistet. Das Tablet selber hat einen Alexa und auch Show Modus. Besteht die Chance, dass Commands implementiert werden können? Beim Echo Show konnte ich sehr viel steuern, hier kann ich jetzt leider so gut wie gar nichts mehr einstellen.

Die gelisteten capabilities sind leider auch weniger:

`MICROPHONE,VOLUME_SETTING,ADAPTIVE_LISTENING,PERSISTENT_CONNECTION,NO_TIME_ZONE_SETTING,ASX_TIME_ZONE,CUSTOM_ALARM_TONE,MICROPHONE,ASCENDING_ALARM_VOLUME,SUPPORTS_SOFTWARE_VERSION,SUPPORTS_LOCALE,SOUND_SETTINGS,VOLUME_SETTING,EARCONS,MULTI_WAKEWORDS_SUPPORTED,TIMERS_AND_ALARMS,SPEECH_RECOGNIZER_USS,ADAPTIVE_LISTENING`
![Screenshot 2021-11-29 134419](https://user-images.githubusercontent.com/16526471/143870422-03704c62-5258-4e2c-a0c5-67496496e1e2.png)

**Comment by oberstel** [comment]
+1

**Comment by oberstel** [comment]
Bei meinem "recht alten" Fire HD 10 (7. Generation) werden mir die Commands angezeigt

Und Capabilities sind bei mir folgende:
`ASX_TIME_ZONE,ADAPTIVE_LISTENING,TIMERS_AND_ALARMS,SUPPORTS_LOCALE_SWITCH,SUPPORTS_SOFTWARE_VERSION,VOLUME_SETTING,REMINDERS,PERSISTENT_CONNECTION,DIALOG_INTERFACE_VERSION,SUPPORTS_LOCALE,NO_TIME_ZONE_SETTING,CUSTOM_ALARM_TONE,SOUND_SETTINGS,MICROPHONE,ASCENDING_ALARM_VOLUME `

**Comment by D3ltorohd** [comment]
Ich habe das selbe Problem, war auch schon sehr oft mit dem Support in Kontakt, das witzige ist, wenn ich ein zweites FireHD10 anmelde bekomme ich für das zweite angemeldete die Commans, lösche ich dann das erste sind die wieder weg. Das Spielchen kann man im Wechsel betreiben. Immer das als zweites angemeldete Tablet bekommt die Commands mit dazu. Bis jetzt gab es keine Lösung dafür, der Support ist auch ratlos.

**Comment by D3ltorohd** [comment]
Problem besteht immer noch, das FireHD10 neuste Gen. hat keinen Commands.

**Comment by stony2k** [comment]
Gleich Problem bei mir auch noch.

**Comment by Apollon77** [comment]
Es möge bitte mal jemand "Devce Type" posten ... dann kann ichs checken

**Comment by stony2k** [comment]
> Es möge bitte mal jemand "Devce Type" posten ... dann kann ichs checken

Bei mir wäre das A1DL2DVDQVK3Q

**Comment by Apollon77** [comment]
Sollte in nächster version kommands haben. müsst schauen was geht

**Comment by stony2k** [comment]
Einfach auf das nächste Update im iobroker warten oder die Github Version
installieren?

Ingo Fischer ***@***.***> schrieb am Sa. 2. Juli 2022 um
11:01:

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/56021/alexa2-adapter-3-13-0-beta

**Comment by stony2k** [comment]
Commands werden nun gelistet, aber am Gerät nicht ausgeführt. Z. B. Speak, Annouchment oder Weather, da passiert leider nichts am Tablet. Hier der Debug Log Auszug. Persönliche Daten durch ein ***** ersetzt.

> 2022-07-03 13:43:05.433 - debug: alexa2.0 (164525) State changed alexa2.0.Echo-Devices.*****.Commands.weather: {"val":true,"ack":false,"ts":1656848585432,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1656847547160}
> 2022-07-03 13:43:05.434 - debug: alexa2.0 (164525) Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/bootstrap?version=0","method":"GET","timeout":10000,"headers":{}}
> 2022-07-03 13:43:05.822 - debug: alexa2.0 (164525) Alexa-Remote: Response: {"authentication":{"authenticated":true,"canAccessPrimeMusicContent":true,"customerEmail":"*****","customerId":"*****","customerName":"*****"}}
> 2022-07-03 13:43:05.822 - debug: alexa2.0 (164525) Alexa-Remote: Authentication check successfull
> 2022-07-03 13:43:05.822 - debug: alexa2.0 (164525) Alexa-Remote: Sending Request with {"host":"alexa.amazon.de","path":"/api/behaviors/preview","method":"POST","timeout":10000,"headers":{}} and data={"behaviorId":"PREVIEW","sequenceJson":"{\"@type\":\"com.amazon.alexa.behaviors.model.Sequence\",\"startNode\":{\"@type\":\"com.amazon.alexa.behaviors.model.SerialNode\",\"name\":null,\"nodesToExecute\":[{\"@type\":\"com.amazon.alexa.behaviors.model.ParallelNode\",\"name\":null,\"nodesToExecute\":[{\"@type\":\"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\",\"operationPayload\":{\"deviceType\":\"*****\",\"deviceSerialNumber\":\"*****\",\"locale\":\"de-DE\",\"customerId\":\"*****\"},\"type\":\"Alexa.Weather.Play\"}]}]}}","status":"ENABLED"}

**Comment by Apollon77** [comment]
Tja, dann kann das Gerät die vllt auch nicht?? Sieht wohl eher danach aus ... Ich dachte es war verifiziert das COmmands gehen? Nur deswegen hab ich die aktiviert ... Also gehen die nun oder nicht?

**Comment by stony2k** [comment]
Ich bin Anwender und kann sagen, dass es sich um ein Amazon Fire Tablet handelt. Ob Commands funktionieren konnte ich ja nicht sagen, dass im Adapter keine Datenpunkte vorhanden waren. Kann ich das denn noch anders testen oder funktionieren die Commands definitiv nicht, wenn beim Tablet nichts getriggert wird? Was kann ich mache, um das zu 100 % heraus zu finden, damit wir Gewissheit haben?

**Comment by Apollon77** [comment]
Kannst Du eine Routine in der Alexa App erstellen die eine Sprachausgabe macht und dort dieses Gerät als Ziel auswählen? Wenn nicht UND wenn es jetzt so nicht geht mit Adapter dann gehts einfach nicht und ich nehme die Commnds wieder raus

**Comment by stony2k** [comment]
Ja das klappt. Ich habe eine Routine erstellt, die auf dem Tablet eine Sprachausgabe macht. Ich kann diese manuell über die App starten oder mit einem Sprachbefehl an das Tablet gerichtet.

**Comment by Apollon77** [comment]
Und mit der 3.13. bzw GitHub version gehts nicht?

**Comment by HeXaN-Prime** [comment]
Mit der Version 3.13.1 von Github sind die Commands vorhanden, aber meine beiden Tablets als offline gekennzeichnet.

**Comment by stony2k** [comment]
Github Version 3.13.1 installiert. Gerät im Datenpunkt online wird als false angezeigt, Speak Command wird nicht ausgeführt. Auch bei mir wird beim Datenpunkt Name nicht der Name übernommen, den ich beim Gerät individuell vergeben habe (Adapter zur Bestätigung nochmal neu gestartet).

**Comment by Apollon77** [comment]
see https://forum.iobroker.net/post/823454

**Comment by HeXaN-Prime** [comment]
Auch in der 3.14 keine Änderung. Bei Tablets offline, falscher Name und Commands gehen nicht. Brauchst du von uns Logs?

**Comment by stony2k** [comment]
3.14: Tablet ist dauerhaft an, Datenpunkt wechselt aber nicht auf online. Egal ob ich es einschalte, per Hotword wecker oder Fragen stelle. Log kommt per Mail.

**Comment by HeXaN-Prime** [comment]
Bei mir das genau das selbe! 
Mein Logs habe ich ebenfalls gesendet. 

Vielen Dank schon mal.

**Comment by HeXaN-Prime** [comment]
Auch in der Version 3.15.2 noch keine Änderung. Immer noch der gleiche Stand. Beide Tabletts haben den selben Namen und sind Offline.

**Comment by Apollon77** [comment]
Kannst bitte nochmal log mit der 3.15.2 senden? und nochmal genau sagen welche Geräte es sind (Namen). Dann kann ich nochmal detailliert schauen

**Comment by HeXaN-Prime** [comment]
> Ich meine mit der 3.17.4

Ich versuche dir die Logs bis Ende der Woche zu zusenden.

**Comment by HeXaN-Prime** [comment]
Die Datei habe ich dir gesendet.
Das eine Tablett hat den Namen "wohnzimmer" und das andere "kueche". Beide werden als "wohnzimmers's Alexa Apps" angezeigt und sind offline.

**Comment by Apollon77** [comment]
Ok, for "apps" there is no online status reported in the config, so it can not be determined. There might be that online/offlune comes via "push info" - and this is the reson why there is an online field ... but for apps the meaning is "Meehh". Sorry but nothing I can do against that (except remiving the "online" flag

**Comment by HeXaN-Prime** [comment]
Aber es wir doch erst zu „Apps“ wenn das 2. Tablett dazu kommt. 

> Ich habe das selbe Problem, war auch schon sehr oft mit dem Support in Kontakt, das witzige ist, wenn ich ein zweites FireHD10 anmelde bekomme ich für das zweite angemeldete die Commans, lösche ich dann das erste sind die wieder weg. Das Spielchen kann man im Wechsel betreiben. Immer das als zweites angemeldete Tablet bekommt die Commands mit dazu. Bis jetzt gab es keine Lösung dafür, der Support ist auch ratlos. Ich habe auch die neuste Generation, da scheint das Probleme zu geben.

**Comment by stony2k** [comment]
Habe in der Alexa Appeine Routine erstellt , die auf dem Tablet per
Sprachausgabe einen Satz spricht. Generell hat das Tablet also schon mal
die Möglichkeit dazu.

Wie kann ich dich nun unterstützt damit es auch per Adapter funktioniert?

**Comment by Apollon77** [comment]
@stony2k Neues issue öffnen und nicht auf ein geschlossenes Antworten wäre der erste Schritt :-) Dann diese Info posten mit Angabe der info.capabilities und info.deviceType

**Comment by stony2k** [comment]
> @stony2k Neues issue öffnen und nicht auf ein geschlossenes Antworten wäre der erste Schritt :-) Dann diese Info posten mit Angabe der info.capabilities und info.deviceType

Den Post hatte ich im Juli abgesetzt. Wieso der jetzt hier gerade mal 1 h alt sein soll, kann ich mir nicht erklären. Jedenfalls ist das hier ein Fehler von Github :)

**Comment by Schnecke8** [comment]
@D3ltorohd @stony2k @HeXaN-Prime 
Probiert mal die aktuelle Git-Version, hatte hier auch Probleme mit zwei FireHD10, was nun behoben wurde:
https://github.com/Apollon77/ioBroker.alexa2/issues/994

Falls es nicht funktioniert, war es einen Versuch wert ;)

Gruß

**Comment by Apollon77** [comment]
geht gerade auch als 3.23.2 ins beta

**Comment by HeXaN-Prime** [comment]
Hallo zusammen, toll das es hier weitergeht. 

Jetzt geht zumindest 1 der beiden Tabletts. Das zweite wird immer noch als Alexa Apps gelistet. Das erste als Fire HD 10.

**Comment by Apollon77** [comment]
Dann gern bitte vollständiges Debug log vom Start bereitstellen per Email an iobroker@fischer-ka.de mit referenz zu dem Issue und die ID des relevanten geräts und so liefern
