### ISSUE TITLE
Fehler wegen ID mit "." am Ende mit Version 3.11.2

### ISSUE THREAD

**Issue by crissiloop** [Apollon77/ioBroker.alexa2#799]
Nach dem Update auf Version 3.11.2 wird der Adapter nach mehrmaligen Fehlermeldungen beendet.
Laut Log:

`<html><body>

alexa2.0 | 2021-12-01 18:58:28.295 | warn | (18961) Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
alexa2.0 | 2021-12-01 18:58:28.259 | error | (18961) The id "Echo-Devices.G090VC09846527GP.Music-Provider." is invalid. Ids are not allowed to end in "."
alexa2.0 | 2021-12-01 18:58:28.258 | error | at processImmediate (internal/timers.js:463:21)
alexa2.0 | 2021-12-01 18:58:28.258 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/main.js:370:21)
alexa2.0 | 2021-12-01 18:58:28.258 | error | at handleValue (/opt/iobroker/node_modules/iobroker.alexa2/main.js:388:32)
alexa2.0 | 2021-12-01 18:58:28.258 | error | at /opt/iobroker/node_modules/iobroker.alexa2/main.js:371:44
alexa2.0 | 2021-12-01 18:58:28.258 | error | at /opt/iobroker/node_modules/iobroker.alexa2/main.js:398:16
alexa2.0 | 2021-12-01 18:58:28.258 | error | at processObjectQueue (/opt/iobroker/node_modules/iobroker.alexa2/main.js:357:21)
alexa2.0 | 2021-12-01 18:58:28.258 | error | at /opt/iobroker/node_modules/iobroker.alexa2/main.js:2922:65
alexa2.0 | 2021-12-01 18:58:28.258 | error | at Adapter.delObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3075:17)
alexa2.0 | 2021-12-01 18:58:28.258 | error | at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:537:23)
alexa2.0 | 2021-12-01 18:58:28.258 | error | (18961) Error: The id "Echo-Devices.G090VC09846527GP.Music-Provider." is invalid. Ids are not allowed to end in "."
alexa2.0 | 2021-12-01 18:58:28.227 | error | (18961) unhandled promise rejection: The id  "Echo-Devices.G090VC09846527GP.Music-Provider." is invalid. Ids are not  allowed to end in "."
alexa2.0 | 2021-12-01 18:58:28.223 | error | (18961) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().

</body>
</html>`

Node.js: v12.22.7
NPM: 6.14.15
JS controller
Installiert: 3.3.21

**Comment by Apollon77** [comment]
Please prodvide a full debug log from start via email to iobroker@fischer-ka.de because I need to find out from where such an empty value comes from ... should never happen

**Comment by crissiloop** [comment]
Hallo,
Logfile vom Start des Adapters wurde per Mail versandt. Ich hoffe, es ist richtig so?
Habe auch nochmals den Downgrade auf Version 3.9.1 probiert. Denn von da bin ich ja gekommen. Aber auch hier kommt jetzt der gleiche Fehler. Neustart des Echos hat leider auch nichts gebracht.
Vielleicht hilft ja diese Information.
Sollte noch etwas benötigt werden, bitte einfach Bescheid geben.

Christian

**Comment by crissiloop** [comment]
Hallo,
nachdem sich der Datenpunkt: "Echo-Devices.G090VC09846527GP.Music-Provider." , welcher ja anscheinend den Fehler verursacht, nicht löschen lies, habe ich den gesamten Baum Alexa2 gelöscht. Somit war auch der "böse" Datenpunkt weg. Nach dem Neustart des Adapters kam dieser Datenpunkt auch nicht wieder.
Nun läuft der Adapter wieder problemlos ohne Fehlermeldungen und der EchoDot gibt auch wieder die Speak-Befehle aus.

**Comment by Apollon77** [comment]
Lass mal offen :-)

**Comment by Apollon77** [comment]
should be fixed in next version
