### ISSUE TITLE
Amazon Cookie lokal speichern für andere Scripts zwischenspeichernd

### ISSUE THREAD

**Issue by mikewolf** [Apollon77/ioBroker.alexa2#8]
Hallo , wäre es möglich das cookie innerhalb von iobroker verfügbar zu machen,
sodass auch andere Anw/scripte damit arbeiten können  ?

**Comment by Apollon77** [comment]
cookie alleine inkl. csrf oder zwei datenpunkte für cookie und csrf getrennt?

**Comment by mikewolf** [comment]
Hallo ,sorry , Du hast recht 
2 Datenpunkte -- einer Cookie und einer csrf !
hatte ich leider vergessen genauer zu beschreiben mein Fehler.

Danke

**Comment by Erti1337** [comment]
JA das wäre super :)
Vor allem da in deinem Aktuellen Adapter, es nicht so klappt mit der History :)))))
Und wie im Forum ja bereits erwähnt ist das mit dem Rollladen Script für mich nicht so einfach.
Daher 2 Datenpunkte mit dem cookie und csrf und ich mach Freudensprünge !

Weiter so !

**Comment by Apollon77** [comment]
Was klappt nicht so mit der History? Da ist alles super

ich bastel dir das skript mal um das es den adapter nutzen kann

**Comment by Erti1337** [comment]
Das wäre ja super, kannst mir ja im Forum ne PN schicken dann.
Bei mir wird die History nur geupdated wenn ich den Trigger drücke.. oder ist das nur das visuelle ? und der Datenpunkt selber mit dem Serienummer etc ist sofort aktuell wenn ich mit einem Device rede ?
Hau rein.

**Comment by Apollon77** [comment]
Es gibt von Alexa kein" push"-Infos. damit muss man immer de Daten abholen wenn man Sie will. Dazu ist der "#trigger" Datenpunkt da.
Also das läuft exakt so wie es gewollt ist. Auch das Skript macht aktuell nichts anderes.

Wenn Du nur mit einem gerät redest bekommt weder der Adapter noch irgendein Skript was mit.

Nächste Adapterversion hat aber hier Intervalle die man einstellen und so regelmäßig abfragen kann. Ob das für History sinn macht ist was anderes (ich wäre da lieber bei triggern)

Ich poste es im Forum in den Thread.

**Comment by Erti1337** [comment]
Alles klar, dann freu ich mich im vorraus :)
