### ISSUE TITLE
Adapter listet keine Wecker in den Datenpunkten

### ISSUE THREAD

**Issue by Schmakus** [Apollon77/ioBroker.alexa2#800]
Es werden keine Wecker in den Objekten angezeigt. Alexa Cookie wurde erneuert, Adapter mehrmals neu gestartet.

**Screenshots & Logfiles**  
<img width="1422" alt="Bildschirmfoto 2021-12-02 um 13 28 51" src="https://user-images.githubusercontent.com/8231359/144422629-6141cb4d-e7e5-4ff1-83ae-a2a233e61868.png">
![IMG_FCF3BA069208-1](https://user-images.githubusercontent.com/8231359/144422645-12f39131-b518-499b-bda8-9b1b24710236.jpeg)

**Versions:**  
 - Adapter version: 3.11.2
 - JS-Controller version: 3.3.20
 - Node version: v14.18.1
 - Operating system: debian

**Comment by Apollon77** [comment]
Pleaas provide a debug log from adapter start  - or from when setting/activating an alarm in the app ... there should be a push message for it

**Comment by Schmakus** [comment]
no push msg by setting/activating an alarm.

`

alexa2.0 | 2021-12-02 14:37:31.641 | info | Device-type:AVN2TMX8MU2YM (AUDIO_PLAYER,MUSIC_SKILL,REMINDERS,LAMBDA_DOWNCHANNEL,CHANGE_NAME,APPLE_MUSIC,TIDAL,VOLUME_SETTING,SIRIUSXM,AMAZON_MUSIC,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,DEEZER,I_HEART_RADIO,PANDORA,TUNE_IN,ADAPTIVE_LISTENING)
-- | -- | -- | --
alexa2.0 | 2021-12-02 14:37:31.641 | info | Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2021-12-02 14:37:31.641 | info | Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2021-12-02 14:37:31.627 | info | Device-type:A2WFDCBDEXOXR8 (AUDIO_PLAYER,DIALOG_INTERFACE_VERSION,REMINDERS,PERSISTENT_CONNECTION,SLEEP,MICROPHONE,TIDAL,VOLUME_SETTING,SIRIUSXM,AMAZON_MUSIC,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,DEEZER,I_HEART_RADIO,TUNE_IN,ADAPTIVE_LISTENING,MUSIC_SKILL,DREAM_TRAINING,CUSTOM_ALARM_TONE,CHANGE_NAME,APPLE_MUSIC,SOUND_SETTINGS,TIMERS_AND_ALARMS,AUDIBLE,GOLDFISH,DEREGISTER_DEVICE,KINDLE_BOOKS)
alexa2.0 | 2021-12-02 14:37:31.627 | info | Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2021-12-02 14:37:31.626 | info | Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2021-12-02 14:37:31.375 | info | Alexa-Push-Connection (macDms = true) established. Disable Polling
alexa2.0 | 2021-12-02 14:37:28.957 | info | starting. Version 3.11.2 in /opt/iobroker/node_modules/iobroker.alexa2, node: v14.18.1, js-controller: 3.3.20
alexa2.0 | 2021-12-02 14:37:28.910 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
host.ioBroker-Master | 2021-12-02 14:37:27.803 | info | instance system.adapter.alexa2.0 started with pid 950
host.ioBroker-Master | 2021-12-02 14:37:25.467 | info | instance system.adapter.alexa2.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.ioBroker-Master | 2021-12-02 14:37:24.719 | info | stopInstance system.adapter.alexa2.0 send kill signal
alexa2.0 | 2021-12-02 14:37:24.697 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
alexa2.0 | 2021-12-02 14:37:24.694 | info | terminating
alexa2.0 | 2021-12-02 14:37:24.692 | info | Got terminate signal TERMINATE_YOURSELF
host.ioBroker-Master | 2021-12-02 14:37:24.559 | info | stopInstance system.adapter.alexa2.0 (force=false, process=true)

`

**Comment by Apollon77** [comment]
Yes because it's no debug log :-)

Admin -> Instances - >Enable Export Mode -> expand the alexa2 instance. CHange loglebel from "info" to "debug". Then adapter restarts.

Then please grab log from logfile in /opt/iobroker/logs/... and not from admin

**Comment by Schmakus** [comment]
Problem solved, but I don't no how. :-)
