### ISSUE TITLE
Alexa Adapter - FireTV Videoplayer Infos Videocontent VIS

### ISSUE THREAD

**Issue by nikmaier** [Apollon77/ioBroker.alexa2#801]
Hallo,
gibt es irgendeine Möglichkeit über den Alexa Adapter auch Infos von einem Film oder Serie abzurufen bei einem FireTV Stick/Cube?
Würde gerne den Filmtitel oder Laufzeit visualisieren?

Oder ist das nur bei Musik möglich?

Vielen Dank im Voraus.

**Comment by Apollon77** [comment]
Wenn es die Alexa Handy App anzeigt dann vllt. Bisher war dies aber nie der Fall

**Comment by nikmaier** [comment]
Stimmt da wird es gar nicht angezeigt. Dann ist klar das der Adapter das auch nicht kann.
Vielen Dank für die Info.
