### ISSUE TITLE
Report to developer as GitHub issue with details for device

### ISSUE THREAD

**Issue by e-p-s** [Apollon77/ioBroker.alexa2#802]
Device-type:A2N49KXGVA18AR (ASX_TIME_ZONE,ADAPTIVE_LISTENING,PERSISTENT_CONNECTION,REMINDERS,TIMERS_AND_ALARMS,MICROPHONE,NO_TIME_ZONE_SETTING,SUPPORTS_SOFTWARE_VERSION,VOLUME_SETTING)

Device-type:A2Y04QPFCANLPQ (I_HEART_RADIO,DEREGISTER_DEVICE,KINDLE_BOOKS,TIMERS_AND_ALARMS,CHANGE_NAME,AMAZON_MUSIC,AUDIBLE,TIDAL,SIRIUSXM,MICROPHONE,VOLUME_SETTING,GOLDFISH,TUNE_IN,ADAPTIVE_LISTENING,PERSISTENT_CONNECTION,AUDIO_PLAYER,MUSIC_SKILL,DREAM_TRAINING,APPLE_MUSIC,SLEEP,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,DEEZER)

Installierte Version: 3.12
Admin 5.21

![image](https://user-images.githubusercontent.com/42796829/145353076-f80c33a7-4969-420a-8754-20cb54e4a352.png)

Eigentlich war ich am schauen, warum das Alexa TTS nicht mehr geht. Coockies sind aktuell.

**Comment by Apollon77** [comment]
Ok, und was sind das jeeils für Geräte? gehen per Alexa App die Kommandos wie sprachausgaben oder so?

**Comment by Apollon77** [comment]
@e-p-s ?
