### ISSUE TITLE
keine Sprachausgabe mit Version 3.12.0

### ISSUE THREAD

**Issue by polocup100** [Apollon77/ioBroker.alexa2#803]
Hallo

ich habe mit der Version 3.12.0 das Problem, das keine Kommandos angenommen werden.
Historydatenpunkte werden aktualisiert.
Mit dem zweiten Amazonzugang ist es genau andersrum.
nach dem Downgrade auf V 3.11.2 geht es wieder.

Ist da ein BUG in der neuen Version oder muß ich an den Einstellungen etwas ändern?

Vielen Dank für den sonst super funktionierenden Adapter!

VG
Sascha

**Comment by Apollon77** [comment]
Heisst das du hast zwei Amazon Accounts und Geräte "übergreifend" da drin? AN sich war die 3.12. der Versuch das besser zu machen. Ein Debug Log würde helfen. geht es auf allen Geräten nicht oder nur auf manchen?

AM besten eins mit 3.11.2 wo es geht und eins mit 3.12 wo es nicht geht.

Bitte unter Admin - Expertenmodus aktivieren - Instanzen - Bei der Inatanz das Loglevel von info auf debug stellen.

Dann Adapter starten und ein Kommando senden. Dann das als Logfile von /opt/iobroker/logs/... rausholen und mir per email senden iobroker@fischer-ka.de und die Issue nummer  von dieem Isseue mit dazuschreiben

Danke

**Comment by coolerkerl** [comment]
same issue as "alexa2.0.Echo-Devices.[dev_id].Commands not working in 3.12.0"?

**Comment by Baenker** [comment]
habe das gleiche Problem. Nach Downgrade auf die Vorversion geht es wieder Habe nur einen Amazon Account. 

Problem tritt bei einen Sonos One auf und auf einen Dot der ersten Generation (nutze die Sprache aber auch nur selten und nur auf den beiden Geräten.

Nutze den speak-State

**Comment by Fatmax1982** [comment]
Selbes Problem, bei 3.12. geht die Sprachausgabe nicht mehr.

**Comment by Frischubau** [comment]
Hallo, ich habe das gleiche Problem.
Alle Commands unter "Commands" können auf allen Echo Geräten nicht ausgeführt werden. 
Dabei handelt es sich um Gen. 2, 3 + 4.
Downgrade ich den Adapter auf die Version 3.11.2 funktionierten wieder alle.

Werden noch Log-Dateien benötigt? Bitte bescheid geben, ich stelle diese dann gerne zur Verfügung.

**Comment by actionbyte** [comment]
Bei mir ebenso. 
Speek und Commands funktionieren nicht bei o.g. Echos und auch nicht auf Echo Show. Scheint Hardwareunabhängig zu sein.
Log ist mit Issue Nr verschickt.

**Comment by ddsak** [comment]
Dito - hier auch.
Nach Downgrade wieder in Funktion.

**Comment by benny000004** [comment]
Same here. Gilt auch für announcements und andere Ankündigungen. Downgrade auf 3.11.2 und Funktionsfähigkeit wiederhergestellt :)

**Comment by Tomtheripper** [comment]
@Apollon77 
hast Du die gewünschten Logs schon bekommen?
btw. bei mir gleiches Problem mit der Sprachausgabe bei 3.12

**Comment by actionbyte** [comment]
@Tomtheripper 
hatte ihm die Logs zugeschickt.
Ich hoffe die waren zur Analyse aussagekräftig genug für Apollon77.

**Comment by e-p-s** [comment]
Bei mir ging auch TTS nicht mehr. Ich bin zurück auf 3.10.4
da geht alles.

**Comment by actionbyte** [comment]
Mit der V3.11.2 (Beta) ist auch noch alles i.O.

**Comment by Apollon77** [comment]
Ich hab Euch nicht vergessen ... bin bald an dem Thema dran

**Comment by realhagie** [comment]
mit 3.12.0 gehen keine commands, kann ich auch bestätigen. Downgrade zur letzten Beta davor hat geholfen.

**Comment by Diginix** [comment]
Merkwürdig, ich habe keine Probleme mit 3.12.0 und den Objekten unterhalb alexa2.0.Echo-Devices.*.Commands.
Nutze mehrfach täglich announcement, speak und ssml auf 4 Echo Dots.

**Comment by Apollon77** [comment]
Genau das muss ich in der Tiefe analysieren. Die 3.12. sollte an sich Verbesserungen bringen für user die "gemische Devices von mehreren Amazon-Accounts" haben ... aber scheinbar ist da doch irgendwas nicht so einfach.  Da muss ich tief reinschauen in dei Logs. Kommt als nächstes dran jetzt wo der Controller 4.0 langsam ruhiger wird

**Comment by Tomtheripper** [comment]
Nein, der Fehler besteht immer noch:
Mir **3.12.0 keine Sprachausgabe**,
mit 3.11.2 alles ok!

**Comment by SirTom72** [comment]
Hallo,

ich habe gerade Iobroker neu aufgesetzt und die Alexa2-Version 3.11.2 installiert. Und mich gewundert, weil meine Javascripte nicht mehr funktionieren. Nach einigem Herumprobieren habe ich festgestellt, dass die <say-as interpret-as > Kommandos innerhalb der <speak> Kommandos dazu führen, dass keine Sprachausgabe erfolgt.

Ohne geht es.

Evtl. haben o.g. Problemschilderungen damit auch zu tun? Wurde diesbzgl. Etwas geändert?
Vielleicht hilft mein Hinweis weiter.

**Comment by Apollon77** [comment]
Das sind SSML Tags .. die gehem "per Definition" nur im xxml State ... enn Sie vorher taten war das halt glück und wenn ein Change bei Amazon

**Comment by Apollon77** [comment]
Bitte mal die GitHub version versuchen ob dort wieder alle speaks auf allen Devices und so gehen.
(PS Bedenkt: GitHub installs mit npm 6 können aktuell 10üMinuten dauern. Einfach warten
Danke

**Comment by Frischubau** [comment]
Alles funktioniert mit der 3.12.1 was die Sprachbefehle angeht. 
Getestet auf einem Echo Dot Gen 2,3 und 4.

Good Job!

**Comment by Frischubau** [comment]
Hey zurück ;)

Habe eben noch aktualisiert, jetzt geht es nicht mehr. 
Setze ich das object speak  wird nichts ausgegeben. 

Beim Einzelgerät nicht und auch im Multiroom nicht.

**Comment by Apollon77** [comment]
Ja, das liegt daran das scheinbar bei dir eine Library mnicht von GitHub aktualisiert wurde.

Entweder: Warten oder "node_modules/alexa-remote2 Verzeichnis löschen und nochmal installieren

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/56021/alexa2-adapter-3-13-0-beta

**Comment by Tomtheripper** [comment]
Hi, gestern 3.12.1 hat funktioniert, und heute mit 3.13 funktioniert's auch!
Prima gemacht, danke!!!

**Comment by Frischubau** [comment]
So nachdem ich es jetzt mit der neusten GitHub Version installiert habe geht es auch wieder.
Hatte gestern das Modul gelöscht und neu installiert, ergab aber keine Besserung. 

Heute wie eben geschrieben neu installiert den Adapter und schon läuft es.
