### ISSUE TITLE
Falsches recurringPattern für Erinnerungen mit "Wiederholung Benutzerdefiniert"?

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#804]
Inzwischen kann man in der App Erinnerungen ja auch zu bestimmten Tagen wöchentlich einstellen, über "Wiederholung benutzerdefiniert".
Allerdings scheint der adapter Probleme mit dem korrekten recurringPattern zu haben (oder aber amazon liefert keinen korrekten Rückgabewert 😇).
Mit dieser Einstellung "benutzerdefiniert" ist recurringPattern immer "0".
Ich habe mal eine email mit debug Infos geschickt, Betreff "recurringPattern und Wiederholung benutzerdefiniert".

Dabei bin ich wie folgt vorgegangen:
1. Alexa, erinnere mich jeden Montag um 13 Uhr an Test eins
recurringPattern = XXXX-WXX-1
2. In der App, neue Erinnerung 13 uhr, Test zwei, Wiederholung benutzerdefiniert Montag
recurringPattern = 0

**Comment by Apollon77** [comment]
Der Recurring pattern wird nur angezeigt. Ich glaube es ist KEINE Logik drin den recurring pattern zu setzen. Kann es sein das das das missverständnis ist?

**Comment by Apollon77** [comment]
Ok, dann bräuchte ich mal ein Debug log ... die "0" wird reingerschrieben wenn kein recurring pattern da ist was er verarbeiten kann.

Gern Debug Log an mich als email (vom Logfile nicht admin) und dazu schreiben wie der betroffene Erinnerung heisst

**Comment by padrino-x** [comment]
Hmm, müsst ich doch gemacht haben? 🤔
Steht so im ersten Post. 😅

**Comment by Apollon77** [comment]
Ok, dann muss nur ich zeit finden meine Mails zu lesen ;-)

**Comment by Apollon77** [comment]
Sollte mit nächster version gefxt sein ... auch jeden Fall reverify

**Comment by Apollon77** [comment]
have fun https://forum.iobroker.net/post/824793
