### ISSUE TITLE
Alexa active Datenpunkt

### ISSUE THREAD

**Issue by Marty56** [Apollon77/ioBroker.alexa2#807]
Ein Datenpunkt, aus dem der Nutzer ablesen kann, ob Alexa aktiv irgendetwas ausgibt, wäre wünschenswert.

Derzeit gibt es Situation, bei denen er Nutzer nicht ermitteln kann, ob Alexa irgendetwas spielt oder nicht.
z.B.

1. Wenn Musik abgespielt, kann passieren, dass das Musikstück zu Ende ist, aber der Progress Bar noch keine 100 % erreicht hat. Dieser Fall könnte umständlich durch Hilfsscript des Nutzers abgefangen werden, indem gecheckt wird, ob der alexa2.0.Echo-Devices.Gxxxxxx.Player.mediaProgressStr sich noch verändert.

2. Werden Musik/Töne von einem Skill abgespielt, z.B. dem Skill für Bayern3, dann gibt es keinerlei Infos, dass dieser Skill aktiv ist. Auch der mediaProgressStr ist inaktiv. 
Sehr umständlich, könnte man das Nutzerkommando für Start des Skills über history.summary abfangen und dann wieder auf das Nutzerkommando, das den Skill stoppt triggern. Das funktioniert aber leider nicht sehr zuverlässig.

**Comment by Apollon77** [comment]
leider nicht möglich weil quasi unbekannt, sorry
