### ISSUE TITLE
Sprachmeldungen hintereinander ausgeben

### ISSUE THREAD

**Issue by urdl** [Apollon77/ioBroker.alexa2#808]
**_Userstory_**
Als User des Alexaadapters möchte ich, dass es die Möglichkeit gibt Sprachausgaben hintereinander ausgeben zu können, damit sich Alexa dabei nicht  selbst unterbricht.

**Acceptance Criteria**
- Alexa wartet bis eine Ausgabe beendet ist und startet dann die neue Sprachausgabe
- Es können  mittels eines Kennzeichen Prioritäten in der Stabelverarbeitung von Sprachausgaben vergeben werden. Dadurch ist es möglich, eine Ausgabe mit höherer Priorität vor die anderen Ausgaben zu reihen.

**Kontext**
Wenn man mittels Speak der Alexa Sprachausgaben mitteilt, kann es vorkommen, dass Sprachausgaben von der Alexa nicht fertig gesprochen werden, da eine weitere Sprachausgabe die vorangegange Sprachausgabe unterbricht.

**Comment by Apollon77** [comment]
Es ist  nicht sinnvoll möglich zu erkennen wann eine Ausgabe vorbei ist, also geht dies nicht verlässlich. Ist zu großem Teil raten.

Bitte bedenken das der Adapter nur das nutzen kann was die Alexa-App-Schnittstellen anbieten und denen ist soetwas vollständig egal.
