### ISSUE TITLE
objekte zerschossen version 0.7.0

### ISSUE THREAD

**Issue by arteck** [Apollon77/ioBroker.alexa2#81]
![unbenannt](https://user-images.githubusercontent.com/6681528/44944879-df918100-adde-11e8-8bab-cff95a7c383c.JPG)

direkt nach dem update...

habe das alexa2.0.Smart-Home-Devices Objekt gelöscht und neu erzeugen lassen.. 
sieht gut aus... solltest du mal im Adapter einbinden.. erst alles löschen dann neu erzeugen

**Comment by Apollon77** [comment]
Was genau war zerschossen? Hast du mal die Objekte im Admin neue Läden gehabt?

Der Adapter hat genau die Logik drin nur etwas selektiver. Jedes Objekt wird verglichen und ggf aktualisiert oder gelöscht oder neu angelegt 

Da kann was sein das der Admin nicht alle Änderungen bekommt (vor allem bei den farblisten wie im Fall von 0.6->0.7) und man Objekte und ggf Admin reloaden muss.

**Comment by Apollon77** [comment]
Und was ist jetzt genau das Problem? Das er Farbthemen bei dem Falschen Gerät einsortiert?

Debug Log bitte!!!!

**Comment by arteck** [comment]
das Problem war dass die Objekte durcheinander waren..kein aufklappen bzw. ansteuern möglich..
 Log hab ich nicht mehr.. sry.. schon aufgeräumt..
wenn nur ich das Problem hatte.. dann mach zu hier.. wollte ich es dir nur wissen lassen

**Comment by Apollon77** [comment]
Ok, also jetzt alles ok ?!
Ich will explizit Objekte nicht löschen weil Leute dafür History o.ä. aktiviert haben könnten und das sonst verschwinden würde.
Wenn jetzt alles geht dann mache ich hier zu
