### ISSUE TITLE
State of Smart-Home-Devices is not updated

### ISSUE THREAD

**Issue by Floatcher** [Apollon77/ioBroker.alexa2#815]
**Describe the bug**  
The  state of smarthome devices arent updated anymore, when you change the status by Alexa (voice, app...). 
Not by push, not by the 300s cycle. 
 i.E.  for this datapoint alexa2.0.Smart-Home-Devices.xxxxxxx.powerState

Only when you restart the adapter the right values are set again at this point one time.

No warnings or errors in the log with debug level. When I change the state by voice, there a also 0 entries in the log about this. I looks like Amazon does not "inform" the adapter. But also the 300s cycle  did not get the correct state later. 

In the Alexa App on the smartphone the status is displayed correct.

Other commands (i.e. tell a joke) are still working from the alexa2 adapter. Also turning on/off the light by using the alexa2 switch datapoint for the lamp.

Also installed latest version from the beta repository. Didn't helped. 

**To Reproduce**  
Change the state of a lamp with your voice with Alexa. State will not be updated in the Alexa2 Object tree.

**Comment by Apollon77** [comment]
Hm ... they were NEVER automatically updated. They are updated when you start the adapter and when yu trigger the relevant #query object. This is thins way since the relase of this feature some years ago.
Also the update cycle never updated smart home device states (just player infos and such stuff)

**Comment by Floatcher** [comment]
I just started using the adapter and was pretty sure it did. Then I did a restart of the adapter at the right time, that it looks for my like it did...

Can I request such a feature? This would be a big advantage for devices which are connected to the Echo Plus Zigbee Gateway directly. This devices need to be integrated and controlled to/by the iobroker through the adapter. So it would also be greate to have the correct current status of it (i.e. if it is on or off). Like it is displayed in the alexa app. Also for Groups and Rooms.

**Comment by Apollon77** [comment]
Yes on start the data are updated once.

And no you can not request it (sorry) because the App API is not suitable for "update all states". This will create a lot of requests and also costs for the skills and so the companies that offer your the skill integration for the devices - especially because then people start to update them every 5s 8and even this is not "realtime enough" for a door sensor or such ... so it will not really work in practice and has a big risk of Amazon blocking us that feature at all

**Comment by Apollon77** [comment]
For Zigbee honestly ... use iobroker zigbee adapter and then ofer the devices by iobroker cloud to Alexa ecosystem. This is better

**Comment by Floatcher** [comment]
Ok, got it. Thanks for the fast response.

**Comment by Floatcher** [comment]
Sorry for bothering again. I was googling for a solution and just found this information from the openhab alexa adapter/binding. 

https://www.openhab.org/addons/bindings/amazonechocontrol/

They do the state update every 60 Seconds. Not just on the start.  Maybe it is not that critical and it would be really a big advantage. Even when it is just updated fixed i.e. all 5 minutes, not configurable. Instead of just at the start.

**Comment by Floatcher** [comment]
I miss understand the query button... Now i got how to update the state... this is not so obviouse/selfexplaining for a newbie of the Adapter, because iobroker acts normally the otherway. Maybe a line "Smartphone devices states need to be updated manual by the object query button" in the instance config will help others in future.

Thx for this great Adapter!

**Comment by Floatcher** [comment]
I miss understand the query button... Now i got how to update the state... this is not so obviouse/selfexplaining for a newbie of the Adapter, because iobroker acts normally the otherway. Maybe a line "Smartphone devices states need to be updated manual by the object query button" in the instance config will help others in future.

Thx for this great Adapter!

**Comment by Apollon77** [comment]
Please check out the GitHub version ... and check rteadme for changes in that upcoming version!
