### ISSUE TITLE
Alexa2-Adapter führt Deaktivierung der Geräte nicht nach

### ISSUE THREAD

**Issue by Siggi0904** [Apollon77/ioBroker.alexa2#816]
Hallo,
ich deaktiviere Smarthome-Geräte in der Alexa-App, die ich nicht benötige.
Diese Geräte werden z.B. durch Anbindungen über Skills angelegt.

Nun musste ich feststellen, dass im IOBroker im Objektbaum des Alexa2-Adpaters alle Smarthome-Geräte den Datenpunkt alexa2.0.Smart-Home-Devices.xxxx.#enabled auf true stehen haben, obwohl diese in der App deaktiviert sind.

Kann das einer bestätigen?
Gibt es dazu eine Lösung?

Siehe ggf. auch dazu das Forum: https://forum.iobroker.net/topic/50937/alexa2-adapter-f%C3%BChrt-deaktivierung-der-ger%C3%A4te-nicht-nach

Danke.

**Comment by Apollon77** [comment]
Ja, die Lösung ist: Adapter neu starten. Smart Home device Informationen werden nicht gepusht von Amazon ... Ja man könnte einen "poll" mechanismus einbauen, dann könnte diese Info verzögert nachgezogen werden ...

**Comment by Siggi0904** [comment]
Ja, bitte einen Poll einbauen, dass das sauber nachgeführt wird.
Wenn ich das aus dem iobroker-Adapter heraus ändere, kommt das aber im Alexa an?

Das ist dann sicher auch das Problem, dass die Routinen im iobroker nicht richtig nachgeführt werden, oder?

**Comment by Apollon77** [comment]
Alles alles immer alle x minuten neu zu laden ist eine ganze Menge an Daten ... Bisher war es nie ein Thema. Aber ja "ansauernd smart home devoces und routinen ein und auszuschalten per alexa app" ist damit nicht kompatibel. Warum machst Du das nicht alles per alexa2 Adapter? Dann wären die Daten immer aktuell

**Comment by Siggi0904** [comment]
Wie meinst du das? Routinen im Alexa2-Adapter deaktivieren?
Aber wo? die hängen ja an mehreren Geräten, werden zumindest unter mehreren Geräten angezeigt.

**Comment by Apollon77** [comment]
see https://forum.iobroker.net/post/823454
