### ISSUE TITLE
deviceStop ohne Funktion

### ISSUE THREAD

**Issue by iPhilBln** [Apollon77/ioBroker.alexa2#818]
Hej, ich bastel grade an einem Skript mit eigenen Kommandos. Diese werden zwar auch einwandfrei erkannt und ausgeführt, allerdings plaudert der Echo Dot trotzdem der DP deviceStop mit wahr gesteuert wird, munter drauf los.

**Comment by Apollon77** [comment]
Ich schaue gern mal rein die Tage, aber "devcieStop" bezieht sich vor allem auf Musik und solche Dinge. Keine Ahnung ob auch SPrachausgaben o.ä. gestoppt werden ...

**Comment by iGodPhil** [comment]
Ah ok, ich hatte das nur so in einem Tutorial so gesehen und mich gewundert, wieso das nicht funktioniert. Erstaunlicherweise hat es einmal bei einem Witz probeweise funktioniert. Meistens jedoch funktioniert es nicht. Auch nicht für 15s die Sprachausgabe auf 0 zu setzen. Alexa versucht trotzdem die Smarthomegeräte zu steuern und gibt dann eine Fehlermeldung aus, wenn das Gerät die Funktion nicht unterstützt.

Ich musste das logfile nochmal überarbeiten. Daher hier das aus der Konsole in eine Datei geschriebene log des Alexa Adapters. Ganz am Ende gegen 21:05 Uhr sollte der Sprachbefehl zu finden sein.
[alexa.log](https://github.com/Apollon77/ioBroker.alexa2/files/7824504/alexa.log)

**Comment by iGodPhil** [comment]
Hej. Wollte doch mal hören, ob du mittlerweile noch etwas rausgefunden hast? 
Ich konnte in der Zwischenzeit herausfinden, dass wenn man eine Routine mit demselben Wortlaut, wie im ioBroker abgefragt wird, die Sprachausgabe unterbunden werden kann. Ist natürlich äußerst umständlich alles doppelt einzugeben, aber vielleicht lässt sich ja darauf etwas aufbauen?
