### ISSUE TITLE
Neues Gerät wird erkannt aber DP werden erst nach Neustart Instanz erstellt

### ISSUE THREAD

**Issue by mcuiobroker** [Apollon77/ioBroker.alexa2#819]
`Version 3.12.0`
Bei neuen `App for PC` -Echo-Devices werden diese zwar erkannt, aber die zugehörigen DPs werden erst angelegt, wenn man die Instanz neustartet.
![image](https://user-images.githubusercontent.com/84818934/148670246-d1336455-ec2e-4db8-acd2-6014a2729d4e.png)
Entsprechend kommen dann einmalig Warnmeldungen im Log:
![image](https://user-images.githubusercontent.com/84818934/148670281-b3e582c1-adc9-41a8-86b9-de10d35cebd3.png)

**Comment by Apollon77** [comment]
Yes , currently you need to restart the adapter when adding a new device. WIl be fixed

**Comment by Apollon77** [comment]
should be fixe din next version ... no automatic restart happens buit another log
