### ISSUE TITLE
Blocky Iobroker mehrere Alexas

### ISSUE THREAD

**Issue by mcchickents** [Apollon77/ioBroker.alexa2#82]
Guten Abend Zusammen,

bin auch seit ein paar Tagen fleißig am testen. Hin und wieder habe ich folgendes Problem. Ich Spreche die Alexa an "Wie viel Strom habe ich heute verbraucht" Sie sagt OK und meine anderen Alexas beantworten die Frage. Doch zu der Alexa wo die Frage gestellt worden ist beleiben stumm. Habe im Blocky schon versucht Multiroom oder jede Alexa einzeln anzusteuern.  Hat jemand eine Idee?

Gruß Julian

**Comment by Apollon77** [comment]
Das ist das im ersten Schritt eher eine Forums frage. Falls dort ein Adapter bug rauskommt macht issue Sinn. 
Im Forum bitte mit mehr Infos wie dem blockly Skript und so.
