### ISSUE TITLE
FireTV player commands and information

### ISSUE THREAD

**Issue by oberstel** [Apollon77/ioBroker.alexa2#824]
As for now, there is now way to identify if an Amazon Fire TV device is in use or not.

For Amazon Alexa devices, certain _[device].player_ attributes and control command are given.
Objects like _.player.currentState, player.currentTitel_ or _player.control.Play, player.controlPause_ etc.

As an Amazon Prime Video and Amazon Audio Unlimited user, I would like to have those objects for my FireTV 4k Max as well.
The current version of this adapter provides only a limited set on information and commands.

As a workaround, I'm using the _[firetv_device].Commands.textCommand_ object, to send a command like "Turn TV Off" or "Play Kika" to my FireTV. This is not perfect but it works ;-)
However, I couldn't find a way to identify if my FireTV is doing anything...playing Netflix, playing Music, doing nothing or being in standby. 

I couldn't check if the Amazon Alexa API is given those information and commands for FireTV devices in general.
It would be nice if somebody could look into this topic and could work on an appropriate implementation?

**Comment by Apollon77** [comment]
Did you read the infos in the issue template? Seems not ...

The adapter can do what the Alexa Mobile App can do ... can these things that you miss be done using the Alexa APp? I would not know how. I think your workaround s the only way right now, Sorry

**Comment by oberstel** [comment]
Yes, you're right Apollon77 - It's not possible to see those information or control Fire TV using the Alexa App, sadly :-(
 
Does anybody know a workaround to identify what FireTV is doing? 
It would be enough for me to have a state which represents if FireTV is doing something or not (beeing in standy)?
