### ISSUE TITLE
JS-controller 3.2.2

### ISSUE THREAD

**Issue by Horgul123** [Apollon77/ioBroker.alexa2#826]
Bei mir wirft der Adapter sekündlich Fehler:

alexa2.0 | 2022-01-22 12:51:42.130 | warn | State "alexa2.0.Echo-Devices.G090XG12149401FM.Player.muted" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
alexa2.0 | 2022-01-22 12:51:42.129 | warn | State "alexa2.0.Echo-Devices.G090XG12149401FM.Player.volume" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-01-22 12:48:06.304 | warn | State "alexa2.0.Echo-Devices.G09183089526023V.Player.muted" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-01-22 12:48:06.302 | warn | State "alexa2.0.Echo-Devices.G09183089526023V.Player.volume" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-01-22 12:46:18.526 | warn | State "alexa2.0.Echo-Devices.90F0081872120DAS.Player.mediaProgressPercent" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-01-22 12:46:18.525 | warn | State "alexa2.0.Echo-Devices.90F0081872120DAS.Player.mediaProgressStr" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-01-22 12:46:18.524 | warn | State "alexa2.0.Echo-Devices.90F0081872120DAS.Player.mediaProgress" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-01-22 12:46:18.524 | warn | State "alexa2.0.Echo-Devices.90F0081872120DAS.Player.mediaLengthStr" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-01-22 12:46:18.524 | warn | State "alexa2.0.Echo-Devices.90F0081872120DAS.Player.mediaLength" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-01-22 12:46:18.523 | warn | State "alexa2.0.Echo-Devices.90F0081872120DAS.Player.miniArtUrl" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-01-22 12:46:18.523 | warn | State "alexa2.0.Echo-Devices.90F0081872120DAS.Player.mainArtUrl" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-01-22 12:46:18.522 | warn | State "alexa2.0.Echo-Devices.90F0081872120DAS.Player.currentAlbum" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-01-22 12:46:18.522 | warn | State "alexa2.0.Echo-Devices.90F0081872120DAS.Player.currentArtist" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-01-22 12:46:18.521 | warn | State "alexa2.0.Echo-Devices.90F0081872120DAS.Player.currentTitle" has no existing object, this might lead to an error in future versions

Brauchst Du da noch andere Logs?

**Comment by Apollon77** [comment]
Welche Adaptervesion?

**Comment by Horgul123** [comment]
Sorry....
3.12.0

Ingo Fischer ***@***.***> schrieb am Sa., 22. Jan. 2022,
19:54:

**Comment by Apollon77** [comment]
Auch noch nach einem Neustart des Adapters?

**Comment by Horgul123** [comment]
Problem tritt mittlerweile nicht mehr auf.
