### ISSUE TITLE
Alexa Sprachbefehle funktionieren Teilweise nicht mehr

### ISSUE THREAD

**Issue by Henny4184** [Apollon77/ioBroker.alexa2#828]
Moin, habe es gestern festgestellt das meine Alexa einige Sprachbefehle zum steuern von Shellys nicht mehr nimmt. Antwort: Gerät oder Gruppe gibt es nicht.  Einige Geräte kann ich so steuernaber einige gar nicht mehr da kommt die Ansage. 
Kann da einer weiter helfen? In Facebook gibt es auch noch weitere Nutzer die das Problem seit gestern haben. Neustart Adapter und Login neu alles kommt zu keiner Lösung. 

node 12.22.9, NPM: 6.14.15, Admin: 5.2.3, Alexa 3.11.2, Shelly 4.0.7. Js: 3.3.22

**Comment by Henny4184** [comment]
> Moin, habe es gestern festgestellt das meine Alexa einige Sprachbefehle zum steuern von Shellys nicht mehr nimmt. Antwort: Gerät oder Gruppe gibt es nicht. Einige Geräte kann ich so steuernaber einige gar nicht mehr da kommt die Ansage. Kann da einer weiter helfen? In Facebook gibt es auch noch weitere Nutzer die das Problem seit gestern haben. Neustart Adapter und Login neu alles kommt zu keiner Lösung.
> 
> node 12.22.9, NPM: 6.14.15, Admin: 5.2.3, Alexa 3.11.2, Shelly 4.0.7. Js: 3.3.22
 oder Gerät unterstützt das nicht kommt auch vor.

**Comment by Apollon77** [comment]
ääähm Stop ... das ist was ganz anderes ... Steuerung ist iot Adapter (odr Shelly skill??) Hat nichts mit ALexa1 zu tun

**Comment by Henny4184** [comment]
Hallo, ich habe die Geräte ja im IOT Adpater und möchte diese via Alexa steuern. Teilweise reagieren Geräte andere nicht. Bin ich hier falsch? Shelly Skill ist nicht aktiv.

**Comment by Apollon77** [comment]
Ja, der Alexa2 Adapter ist dazu da im Alexa Geräte zu steuern ... issues mit "iot Adapter "bitte dort melden oder besssser im Forum
