### ISSUE TITLE
seperated text with semicolons don't talk first part

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.alexa2#83]
Hi,
bei "ach herrjeee; oh Gott; ui uiuiui" in Command wird nur "oh Gott, ui" ausgesprochen :-)
Alexa mag da kein ach herrjeee...

**Comment by Apollon77** [comment]
Please install current 0.7.1 from GitHub from today. Is in final testing. 

Or do you already have this?

**Comment by Ilovegym66** [comment]
sorry, sure, it's 0.7.1 installed 2h ago direct from github.

**Comment by Apollon77** [comment]
Ok, will check before publishing 0.7.1 im Forum ;-)) thank you. First kids into bed

**Comment by Apollon77** [comment]
fixed by 0.7.2 on github. Please retest

**Comment by Ilovegym66** [comment]
geht, wenn man am Anfang auch ein Semikolon setzt ( oder muss das generell dann sein? , dann war der Bug der vor dem PC,....)

**Comment by Apollon77** [comment]
gggrrrrr ... jetzt aber ... nochmal Github bitte

**Comment by Ilovegym66** [comment]
jep! ;-) geht! 
Wenn zuerst ein semikolon steht, kommt "undefined" :-) aber das weiss ja keiner ;-)
texte getrennt mit Semikolon geht , sogar mehrere und lange und die Tante macht ne Pause.
Kann es sein, dass sie seit 0.7.x schneller spricht?

**Comment by Apollon77** [comment]
Ok, undefined sollte mit 0.7.3 von GitHub weg sein :-)

magst Du nochmal checken bitte? Danke!

**Comment by Ilovegym66** [comment]
die gute Nachricht: es ist anders! und das Undefined ist weg.
die schlechte Nachricht: mit Semikolon am Anfang sagt se gar nichts..  egal was hinterher kommt..

**Comment by Apollon77** [comment]
Ok fixe ich morgen. Scheiss regex ;-)

**Comment by sigi2345** [comment]
Geht bei mir...........

**Comment by Apollon77** [comment]
bei mir geht ;tester;tester;test beispielsweise auch ... kannst Du Bitte github nochmal installieren - UND NEU STARTEN nicht vergessen danach!!

**Comment by Ilovegym66** [comment]
Hi,
vor jedem Update mach ich n Snapshot, beende die Instanz, (bei ganz neuen Adaptern lösche ich die sogar gern) Update von Git über Admin ( oder per npm ) mach anschliessend zur Sicherheit noch n Upload, und starte dann die Instanz neu.

Aber jetzt die endlich gute Nachricht, es geht!! Supi! Danke!

**Comment by Apollon77** [comment]
Perfekt!

**Comment by Ilovegym66** [comment]
sorry.. hast du das mal bei Multiroom Speak probiert? da stottert se sich einen ab.. und machts dann.. :-(

**Comment by Apollon77** [comment]
ne noch nicht probiert ... aber an sich sollte es "nur" der gleiche befehl sein der halt an alle geräte einzeln gesendet wird ... also synchron war das nie ... falls Du das meinst ... 

Also pro Gerät sollte es sauber ablaufen ... nur halt nicht synchron

**Comment by Ilovegym66** [comment]
nee meine leider nicht syncron, das ist klar, dass die Echos das der Reihe nach abspielen, aber mein Echo Show und der Echo Dot zum Beispiel stottern das so ab: T, T, T, Tester, Tester, Test

**Comment by Apollon77** [comment]
Das komische ist: ich habe nichts wirklich gemacht ... hhhhmmmm ........... naja wenns tut :-)

**Comment by Ilovegym66** [comment]
Das nennt man Praxis! Es geht, und keiner weiß, warum.
:-)
