### ISSUE TITLE
js-controller 4

### ISSUE THREAD

**Issue by Pocky2507** [Apollon77/ioBroker.alexa2#839]
Moin Ingo,
mit dem neuen Controller habe ich bei all meinen Geräten diese Fehlermeldung:

`

(90262) Object Echo-Devices.90F0071865310GRK.Commands.speak-volume is invalid: obj.common.min is only allowed on obj.common.type "number", received "mixed"
--

<br class="Apple-interchange-newline">`

**Comment by Apollon77** [comment]
Schaue ich mir an ... der js.controller wird da aber auch was ändern. Danke!

**Comment by Apollon77** [comment]
should be fixed in next version
