### ISSUE TITLE
Textcommand scheint defekt

### ISSUE THREAD

**Issue by daniel-lo** [Apollon77/ioBroker.alexa2#840]
Ich bin der festen Überzeugung das hat mal funktionert .. und dann irgendwann aufgehört .. wollte das schon länger mal schreiben.
Versuch von "steuere" auf "aktualisiere" umzustellen hat nichts gebracht.

![grafik](https://user-images.githubusercontent.com/4311558/152340602-aae6e168-b535-40db-8931-50716619c0de.png)

Ich vermute ohne Logs geht es nicht weiter .. kann ich auch machen .. aber vielleicht ist das ja auch schon bekannt?

**Comment by daniel-lo** [comment]
Das hier hingegen funktioniert:

![grafik](https://user-images.githubusercontent.com/4311558/152340987-890211a4-7ef3-4a89-9ee3-8bacfc7510cc.png)

**Comment by Apollon77** [comment]
Geht es per Alexa App noch?

**Comment by daniel-lo** [comment]
Hab die App dafür noch nie benutzt.

**Comment by Apollon77** [comment]
Dann verifiziere es bitte weil der Adapter nur das tut was die App macht. Wenn also die App unter Routinen nicht tut bei einem Gertät oder so dann kann der Adapter auch nichts tun :-) Dann müsstest Du dich an Amazon wenden. Zuletzt als ich textCommand getestet habe tat es bei mir

**Comment by daniel-lo** [comment]
Bin grad nicht sicher wie Du das meinst .. also Routinen benutze ich mit iobroker .. aber eher mit Objekten die ich IOT anlege. Schubs mich mal in die richtige Richtung bitte.

**Comment by Apollon77** [comment]
gehe in die Alexa App, erzeuge eine neue Routine und nutze darin auch die Option einen kommandostring zu senden, Danach diese routine testen und schauen ob es geht. wenn nicht dann ists nichts vom adatper

**Comment by daniel-lo** [comment]
Danke .. hatte ich noch nie gemacht .. funktioniert 1a. Muss also an was anderem liegen dass der Bildschirm immer an ist wenn ich ins Schlafzimmer schaue .. hab jetzt mal die adaptive Helligkeit ausgeschaltet.
