### ISSUE TITLE
Link zur Anmeldung schwer ersichtlich

### ISSUE THREAD

**Issue by unstressable** [Apollon77/ioBroker.alexa2#842]
Hab gerade mein Amazon Passwort geändert und muss mich daher auch neu beim Alexa Adapter neu anmelden:
<img width="775" alt="image" src="https://user-images.githubusercontent.com/50423935/152588858-5bce82e6-5e8e-4a2f-973e-985996121218.png">

Der link ist im rot eingekreisten Bereich, bitte diesen hervorheben, zumal davor steht im "folgenden Link" der ist gar nicht so einfach zu finden ;)

Zudem funktioniert er bei mir nicht, da muss ich noch suchen, woran das liegt.
Er öffnet da ne andere IP Adresse im neuen Tab als mein iobroker, hier findet er aber keine Webseite zum anmelden.
->Adapter neu installiert, dieses Problem ist gelöst.

Edit: Sehe gerade in einem Youtube Video, dass das mal farbig war:
![image](https://user-images.githubusercontent.com/50423935/152590447-7676a152-cbac-4faa-ab56-f6d69118f084.png)

**Comment by Apollon77** [comment]
fixed in next version

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/56021/alexa2-adapter-3-13-0-beta
