### ISSUE TITLE
Announcement funktioniert nicht wie beschrieben

### ISSUE THREAD

**Issue by thomke67** [Apollon77/ioBroker.alexa2#846]
Hallo zusammen,

Ich meine, früher ging das mal genauso wie gewollt. Und zwar mit dem Adapter. Aber seit einigen Monaten, kommt manchmal der Sound vorher laut (manchmal nicht) und Gong und Ankündigung dann wieder leise. 

Ich hätte gerne die Announcement so gesteuert: "**50;Dies ist eine Ankündigung**"
Die Ankündigung soll einfach mehr Aufmerksamkeit bekommen! Einerseits durch den Gong und andererseits durch die höhere Lautstärke, die aber nicht die normale Musiklautstärke beinflussen soll...... Also kein Anheben der Lautstärke bevor der Gong kommt.

Ich denke, so wollen es die meisten hier.

Laut Beschreibung sollte es so gehen, wie oben beschrieben:
Zitat: "_Detailed information Speak and Announcement: Type in here what you want Alexa to say. You can also adjust the volume of Alexa by giving a percentage before your text. Example: 10;Alexa is saying Alexa with 10% volume, while 100;Alexa is 100% volume._"

Gruß,
Thomas

**Comment by padrino-x** [comment]
Duplikat von #780?

**Comment by Apollon77** [comment]
yes

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/56021/alexa2-adapter-3-13-0-beta
