### ISSUE TITLE
Falscher StrukturType?

### ISSUE THREAD

**Issue by mcuiobroker** [Apollon77/ioBroker.alexa2#849]
Sollten nicht alle Elemente unterhalb vom device -> channel sein?
Hier ist es mal device und mal channel?
device - channel - state?
Alarm, Reminder und Timer müssten channel sein?
![image](https://user-images.githubusercontent.com/84818934/154074702-00e8eaf0-fa9c-4fcb-a626-f5e3b55b573e.png)

**Comment by Apollon77** [comment]
Am Ende geht es hier darum ws noch untendrunter kommt und da wo channel ist ist es nur eine ebene, bei denen mit Device sind 2 Ebenen drunter.. Das passt soweit wie möglich, aber ja da ist ein Graubereich
