### ISSUE TITLE
Multiroom speak don't speak if TuneIn play radio

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.alexa2#85]
Gerade aufgefallen, dass in meinem Multiroom speak steht "der Wäschetrockner wurde angeschaltet" aber mein Echo Show fleissig Planet Radio spielt und das mal komplett unterschlagen hat...
Alexa Adapter 0.7.3 - aktuelle Version von 11.00 Uhr heute
Also vom Script wurde der Wert reingeschrieben, aber nicht ausgeführt.
Wenn ich per Hand etwas in das Objekt schreibe, gehts.

**Comment by Ilovegym66** [comment]
send per PN too big

**Comment by Apollon77** [comment]
in worstcase zip it and change extention to .zip.txt and forum will accept upload :-)

**Comment by Apollon77** [comment]
auch fixed?
