### ISSUE TITLE
Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted

### ISSUE THREAD

**Issue by skokarl** [Apollon77/ioBroker.alexa2#850]
Echo Show 15 verursacht fogenden Eintrag im LOG

  | 2022-02-18 19:53:22.080 | info | Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
-- | -- | -- | --
alexa2.0 | 2022-02-18 19:53:22.079 | info | Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2022-02-18 19:53:21.820 | info | Alexa-Push-Connection (macDms = true) established. Disable Polling
alexa2.0 | 2022-02-18 19:53:18.896 | info | starting. Version 3.12.0 in /opt/iobroker/node_modules/iobroker.alexa2, node: v14.18.2, js-controller: 4.0.8

**Comment by Apollon77** [comment]
Please add the lines after/before them .... they contain the relevant infos and they are missing :-)

**Comment by skokarl** [comment]
Echo Show 15
Command's works.
calendar, goodmorning, jokes, speak, tunein, volume

**Comment by Apollon77** [comment]
will be added in next verison
