### ISSUE TITLE
alexa2.0.Smart-Home-Devices

### ISSUE THREAD

**Issue by skvarel** [Apollon77/ioBroker.alexa2#851]
Hallo @Apollon77 

Wofür wird der 'alexa2.0.Smart-Home-Devices' Ordner gebraucht? Es tauchen immer wieder Fragen/Problme auf, wenn User darüber smarte Geräte steuern. Es funktioniert einfach nicht sauber, was nicht am Adapter liegt!

Kann man das Verzeichnis nicht komplett entfernen?

Gruß, Sven.

**Comment by Apollon77** [comment]
"Es funktioniert nicht sauber"? Dazu kenne ich keine Berichte - die einzige Verwirrung die oft besteht ist das die Werte dort in echtzeit aktualisiert werden was nicht korrekt ist. Steuern und über #query updaten geht. Oder übersehe ich etwas?

**Comment by n3ucr0n** [comment]
Ich kann nur für mich sprechen, aber ich nutze diese Daten schon.
Zugegeben selten aber ich freue mich durchaus schon, dass es sie gibt.

Beispielsweise habe ich noch alte Gosund WLAN Steckdosen, welche mit der richtigen SmartLife App Version zwar über einen eigenen Adapter gesteuert werden können, in meinem Fall aber über die Alexa2 SmartHome Devices genutzt werden, da ich nicht die richtige App Version habe…

**Comment by JayVee2** [comment]
Seit etwa einer Woche ist der Ordner alexa2.0.Smart-Home-Devices bei mir in der Stable Version V 3.11.2 leer.
Ich habe den Ordner auf Änderungen überwacht, weil Alexa gelegentlich eines meiner registrierten 120 Geräte "verloren" hat und fand den Ordner sehr ganz praktisch.
Ist das jetzt Bug, Feature oder nur bei? Kann ich den Ordner irgendwo wieder aktivieren?
Grüße
-jayvee

**Comment by Apollon77** [comment]
see #920 ... is also pinned in "issues" ...
