### ISSUE TITLE
Playlist Wiedergabe auf multiroom scheitert

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#86]
wenn ich bei

> alexa2.0.Echo-Devices.xxx.Music-Provider.Amazon-Music-Playlist

den Playlist namen bspw. **_"Matze"_** eingebe, wird in **_alexa2.0.History.summary_**
folgendes ausgegeben:

> spiel Playlist Matze auf MULTIROOM music von amazon music

Dann sagt alexa nur das sie **_"Matze"_** nicht in meiner Musik Bibliothek finden kann.

Wenn ich aber auf einem einzelnen Device bei Amazon-Music 
**_Playlist Matze auf multiroom_** 

eingebe, wird folgendes ausgespuckt 

> spiel Playlist Matze auf multiroom von amazon music

sobald ich also meine Devicegruppe "MULTIROOM" klein schreibe wird es erkannt.

Kannst du das irgendwie fixen?

Gruß
Matten Matten

**Comment by Matten-Matten** [comment]
Ach ja, wenn ich auf der **_Multiroom Device Gruppe_** meine _playlist_ wiedergebe, dann auf einem einzelnen Device meine _playlist_ wiedergebe, wird die _playlist_ einfach wieder auf _**multiroom**_ wiedegegeben.

**Comment by Apollon77** [comment]
Ok, jetzt ists strange ...
Debug log davon bitte als PN, am besten basierend auf der 1.7.4 uf Github (von vor paar mins, bitte auch das Lautstärke-zurücksetzen thema aus dem Forum damit retesten).

Der Code tut folgendes:

Der Playlist State packt auf das was man reinschreibt nur "playlist " davor und macht dann das gleiche wie der normale Provider-State.

Wenn es ein Multiroom-Device ist wird " auf " + device._name + " music" hinten dran gehängt. Also wenn dann änder bitte den Namen von dem Multiroom device und schreibe es klein

**Comment by Matten-Matten** [comment]
0.7.4 installiert, neu geladen.

1. ok, du hast jetzt multiroom speak volume gelöscht. 

2. **_MULTIROOM_** nach **_Multiroom_** umbenannt 
bei

> alexa2.0.Echo-Devices.xxx.Music-Provider.Amazon-Music-Playlist

den Playlist namen bspw. "Matze" eingebe, wird in alexa2.0.History.summary
folgendes ausgegeben:

> spiel Playlist Matze auf Multiroom music von amazon music

und wieder sagt Alexa das sie die Playlist nicht finden kann.

log wird als pn geschickt.

**Comment by Apollon77** [comment]
ich hab ne vermutung ... die reihenfolge... er sucht garantiert die playlist nicht bei Amazon music ... weil die reihenfolge verdreht ist

**Comment by Apollon77** [comment]
Amazon baut den String teilweise selbst zusammen. Die erwarten glaube ich nicht das im "Titel" zusatzinfos wie "auf Multiroom" drin ist :-(

Tu mir mal bitte einen gefallen und versuch eine Routine in der Alexa-App anzulegen und versuch ob Du es dort schaffst mit playlist und "auf Multiroom". Wenn Du eine Textkombi hast die geht sag mal welche :-)
Ich kann da frühestens heute Abend rumspielen weil ich gerade nicht daheim bin

**Comment by Matten-Matten** [comment]
mich wundert da immer das, wenn es klein geschrieben wird, auch abgespielt wird?!

**Comment by Matten-Matten** [comment]
mit 0.7.5 funktioniert es vielen Dank!

**Comment by Matten-Matten** [comment]
das einzige ist MULTIROOM muss nach Multiroom umbenannt bleiben, sonst wird die playlist wieder nicht abgespielt

**Comment by Apollon77** [comment]
Zum Namen: Strange. Wüsste aber nicht was ich da tun kann. Bei mir heißt die Gruppe zb Erdgeschoss ... ich habe nur keine Playlisten zum testen :-(

Zum zweiten bitte mal debug log. 

Passiert das gleiche wenn du es per stimme zum Echo sagst oder per App und Routine machst?

**Comment by Matten-Matten** [comment]
OK, wenn ich das über eine Routine starte, ist genau das selbe. ich schreibe mir sonst ein Blockly Programm die, die Wiedergabe bei Multiroom erst stoppt und dann die Wiedergabe auf dem einzelnen Device startet. Wenns in der Routine genau so ist, ist es ja kein Fehler von deinem Adapter, sondern ein Amazon Bug.
Trotzdem danke
Gruß
Matze

**Comment by Apollon77** [comment]
Alles klar. mir war die Klärung wichtig. Also kann ich da grad nix tun. Perfekt!

**Comment by Matten-Matten** [comment]
Jetzt hat's Klick gemacht bei mir, das weiterhin auf Multiroom abgespielt wird ist vermutlich Absicht, denn wenn man einzelne Songs oder Interpreten zu Alexa (einem einzelnen Device) spricht, bzw im Adapter eingibt, soll Alexa ja nicht aus dem Multiroom Modus verschwinden, sondern einfach den nächsten angesagten Song auf der Multiroom Gruppe abspielen.
