### ISSUE TITLE
Routinen vom Typ "Geräuscherfassung" bleiben namenlos

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#862]
Wenn ich eine Routine vom Typ Geräuscherfassung anlege, dann steht in den Datenpunkten unter Name nur "Unknown".
Ist jetzt nicht tragisch, aber es ist mir aufgefallen. =)

In meinem Fall sollte da eigentlich stehen "Husten erfasst".

`{"@type":"com.amazon.alexa.behaviors.model.Automation","automationId":"amzn1.alexa.automation.8b26e7e3-73b5-49e8-89e9-e1ed21a76da8","name":"Husten erfasst","triggers":[{"payload":{"customerId":"A1TI0E9SQ466JG","value":"DETECTED","target":"7965e641-3160-4031-923b-0d0c7008484f","sensorSchedule":{"recurrence":"P1D","startTime":"090000","endTime":"200000","timeZoneId":"Europe/Berlin"},"sensorSuppression":{"occurrence":1,"durationInSeconds":300}},"id":"amzn1.alexa.trigger.3285182b-9ee4-41ec-b5cb-db351c567918","type":"Alexa.Trigger.AED.coughDetectionState","skillId":"amzn1.ask.1p.aed","timeLapse":null,"presentationDataList":null,"imageUrl":null,"clientData":null,"context":null}],"sequence":{"@type":"com.amazon.alexa.behaviors.model.Sequence","sequenceId":"amzn1.alexa.sequence.ffd135c4-66b0-4b30-9ea1-bf59e8108986","startNode":{"@type":"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode","nodeState":null,"name":null,"type":"DoNothing","skillId":"noop","operationPayload":{"doNothing":[]},"presentationDataList":null,"clientData":null,"context":null,"tag":null}},"owner":`

**Comment by TheNaga** [comment]
@padrino-x Funktioniert bei dir die Aktualiserungen der Routienen Datenpunkte? Bzw. werden diese getriggert?

Die Routine wird zwar bei mir mit "Unknown" angelegt, wird aber bei Aktivierung nicht getriggert.

**Comment by djmarc75** [comment]
@TheNaga 
Diese Routinen können nicht per ioBroker getriggert werden, da sie zeitgesteuert in der App aktiviert werden und tatsächlich nur auf Geräusche reagieren wenn aktiv.

**Comment by TheNaga** [comment]
@djmarc75 Sorry, hab mich vlt falsch ausgedrückt. 
Die Routinen werden bei mir im iobroker vom Adapter nicht gesetzt bzw. aktualisiert. Sprachbefehle werden erkannt. Habs sowohl mit der "recommended" Version, als auch der "latest" Version probiert.  

Habe jetzt als Workarround einen unbenutzten Kanal in einem Alexa-fähigen Schalter mit der Routine gesetzt.

**Comment by padrino-x** [comment]
Also, die Routinen können schon getriggert, wenn/indem man "true" setzt.
Ich schätze er aber mal, das muss innerhalb der festgelegten Zeitspanne passieren. =)
Ob der Datenpunkt sich allerdings aktualisiert, kann ich grad nicht testen, da mein Echo sich weigert auf meinen Husten zu reagieren, sprich die Routine auszulösen. ;)

**Comment by djmarc75** [comment]
Richtig, können doch per true getriggert werden. Bei mir hat mein Show eben aufs Husten reagiert aber den Datenpunkt hat er nicht auf true gesetzt. Habe dann einfach mal 5-6 Routinen über die App ausgeführt aber es änderte sich kein Datenpunkt auf true.

**Comment by TheNaga** [comment]
@djmarc75 genau, das ist mein Problem. Versuche über die Wassergeräusche "Duschen" zu erkennen. Der Datenpunkt wird nicht aktualisiert.

**Comment by djmarc75** [comment]
@TheNaga Ich löse das schon lange über NodeRed. Jede Routine steuert bei mir einen eigenen Datenpunkt über NodeRed, aber ich denke das sollten wir im iobroker-forum diskutieren, nicht dass wir hier vom eigentlichen Issue ablenken :)

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/56021/alexa2-adapter-3-13-0-beta
