### ISSUE TITLE
Feature (preset alarm volume)

### ISSUE THREAD

**Issue by timae146** [Apollon77/ioBroker.alexa2#87]
is it possible make the alarm/reminder/musik-alarm volume presetable. like the speak-volume for commands?

**Comment by Apollon77** [comment]
What you exacty mean? What is your usecase? Setting the alarm/reminder/Notification Volume is possible in the Alexa App ...

**Comment by timae146** [comment]
puh, das aber auf deutsch. 

ich meine ob es möglich wäre die alarm/ wecker/ errinnerungslautstärke für jeden bestehenden Alarm seperat einstellen zu können. wie es bei dem speak befehl der fall ist.

in der app kann man ja nur die lautstärke für alle wecker gleichzeitig einstellen.
in meinem fall benutze ich meinen "haupt" wecker quasi nur als trigger missbrauche um ein script zu starten welches erst ein licht langsam hochdimmt und nach 20 minuten das radio einschaltet.

wenn ich jetzt allerdings spontan andere wecker per sprachbefehl einstelle und vergesse die lautstärke hochzustellen, bzw danach wieder runterzustellen, werde ich entweder garnicht geweckt, oder 20 minuten zu früh. 😴 
(wenn ich den wecker per script auf lautstärke 0 weckt er mich mit in der app vorgestellten lautstärke und schaltet sich dann 1-3 sekunden erst auf "stumm") - also müsste man die weckerlautstärke quasi vor dem triggern auf 0 stellen, wie bei den sprachbefehl commands.

-------------------------------------------------------------------------------------------------------
die laustärke des reminders ist glaubich immer die grade eingestellte im player. (in der app bisher glaubich nicht einstellbar) also wenn der echo grade auf lautstärke 1/10 ist, ist die errinnerung auch dementsprechend leise.

wären halt alles mehr oder weniger komfort funktionen.

**Comment by timae146** [comment]
bzw für jeden wecker die lautstärke seperat- und für die reminder eine einheitliche lautstärke voreinzustellen oder so ähnlich. ;)

**Comment by Apollon77** [comment]
Ich überlege mal.

**Comment by padrino-x** [comment]
This would be very useful (to me) ;)
I like to auto adjust volumes, e.g. when a window is open or the air fryer is running 🤣.
Especially for the last I then like to use timers which I don't hear. 😅

**Comment by Apollon77** [comment]
In fact yes it is technically possible to set the "Wecker/Timer/Benachrichtigungen" Volume via adapter. One isue is tat any change via ap will not be synced back to the adapter. On the other hand the question is WHEN to set the volume? The whole "when an alarm happens" is a bit difficult ... so yes 5-10s earlier we could adjust the volume and later change back again ... hopefully clocks are in sync and nothing else happens the adapter do not know of :-)

How to configure that for alarms or Timer or Notifications (yes Reminders is not innthe list?) is a second "I have no idea" :-)

So how you would use that? What makes sense?

**Comment by padrino-x** [comment]
Well, maybe I don't understand the problem, but why do you need to time the setting or get feedback from the app?
As I understand it, the adapter should change the permanent setting, just like the app would, through

Mehr/Wecker und Timer/Gerätenamen/Einstellungen 
or
Mehr/Einstellungen/Geräteeinstellungen/Gerätenamen/Zahnrad/Töne

and not "on the fly"?
And for the feedback.
I see no reason for reading the current value, just setting it.
And there are other settings to, that don't get a refresh from the app, no? =)

**Comment by Apollon77** [comment]
Ok, just allowing to set the vale is "easy". I understood above wishes a "depending on a single alarm set a different volume" ... so set the alarm volume depending on  the alarm triggered

> bzw für jeden wecker die lautstärke seperat- ... voreinzustellen

**Comment by padrino-x** [comment]
Ah, ok, now I got it, after re-reading. 😅
I guess, if the value can be set via the adapter this could already help.
As with a script alarms can be monitored, and if triggered, the volume kann be re-set.
In @timae146s case...
Check if the "silent" alarm goes from false to true, then set alarm volume to zero. If silent alarm is triggered re-set volume accordingly.
Well, at least this might be a first step. :D

**Comment by Apollon77** [comment]
next version will allow to edit the alarnm volume itself in a preferences section. So first step.

I also experimented around with "alarm specific volumes". The volume also changes while the alarm is "ringing". So what could work is the following:
* 5s before the alarm the adapter could set a custom alarm volume
* AFTER the alarm has been acknowledged ( so in fact after the stae with the id is clearig ...) we could set the alarm volume back to the level from before

This will break when mukltiple alarms overlap at the same time or such stuff ... but else it should work ... maybe I add that in next version,. Will think about it

**Comment by Apollon77** [comment]
Ok, you will get it in next version ... customVolume :-)

**Comment by Apollon77** [comment]
have fun https://forum.iobroker.net/post/824793
