### ISSUE TITLE
Echo Buds Ordnerstruktur

### ISSUE THREAD

**Issue by djmarc75** [Apollon77/ioBroker.alexa2#875]
Hallo.
Habe eben meine Echo Buds (inEars) mit Alexa verbunden.
Diese werden in der Ordnerstruktur aber falsch eingeordnet.

`alexa2.0.Echo-Devices.amzn1.dgroup.8cc018df0d9da0783d06488xxxxxxxxxx`

Ob man dies korrigieren könnte?

Besten Dank und frohe Ostern.

**Comment by Apollon77** [comment]
Dann bitte vollständiges Debug log vom adapterstart holen (Loglevel der instanz vor aher auf debug setzen) und an iobroker@fischer-ka.de senden mit referenz auf dieses Issue.

Andere Frage ist: Was genau ist denn daran falsch? sieht aus als ob es wie eine "Lautsprechergruppe" abgebildet ist?!

**Comment by djmarc75** [comment]
Issue kann quasi weg weil ich eigentlich dachte die Echo Buds 2 haben Alexa onBoard.
Dem ist nicht so und beim ersten anmelden der Buds werden diese wohl, wie Du geschrieben hast, als Gruppe angelegt... ich hab mein To-Do anders gelöst.
Thanx
