### ISSUE TITLE
2. Fire HD 10 wird immer als Alexa App angezeigt

### ISSUE THREAD

**Issue by HeXaN-Prime** [Apollon77/ioBroker.alexa2#876]
Hallo,

vielleicht kann mir jemand helfen! Ich habe immer das Problem sobald ich ein 2. Fire HD 10 Tablet einbinde, wird das erste 1. Tablet von der normalen Geäte ID zu einem Alexa App Gerät abgeändert. Wenn nur ein Fire HD 10 integriert ist funktionieren Commands usw. tadellos. Wird das 2. Tablet angemeldet, verschwinden die Commands des 1. , es wird als offline angezeigt und das Gerät ist kein Fire HD 10 mehr. Hat jemand ähnliche Probleme?

Viele Grüße und Danke im Voraus.

**Comment by Apollon77** [comment]
Bitte die relevanten Szenarien mal nachstellen und jeweils bitte ein Debug Log (also vorher Loglevel auf Debug stellen) erstellen und mir per email an iobroker@fischer-ka.de senden. Logfile von der Platte nehmen (/opt/iobroker/log/...)

**Comment by HeXaN-Prime** [comment]
> Bitte die relevanten Szenarien mal nachstellen und jeweils bitte ein Debug Log (also vorher Loglevel auf Debug stellen) erstellen und mir per email an [iobroker@fischer-ka.de](mailto:iobroker@fischer-ka.de) senden. Logfile von der Platte nehmen (/opt/iobroker/log/...)

Hallo und danke für die Unterstützung!
Ich musste leider feststellen, dass es nicht an ioBroker liegt, sondern direkt an Amazon. Dort wird schon sobald ich das 2. Tablett hinzufüge das erste auf Alexa Apps geändert :(
