### ISSUE TITLE
*.timer.triggered not working anymore

### ISSUE THREAD

**Issue by quotschmacher** [Apollon77/ioBroker.alexa2#877]
i'm using the adapter version v3.12.0 and until 3 or 4 days my trigger on the datapoint "*.timer.triggered" used to work - when a timer alarm started it went to true and when the alarm was stopped it siwtched to false.
now it does not update anymore on my both echo dots.

is this known? did amazon change something?

**Comment by Apollon77** [comment]
Nothing known so far. Please set loglevel of the insdtance to debug and start adapter, then set a timer and wait until it should trigger. Pleas esend the logfiles form disk from this

**Comment by Apollon77** [comment]
Closed no answer, assumed working
