### ISSUE TITLE
Funktion in Alexa App vorhanden, jedoch nicht in ioBroker

### ISSUE THREAD

**Issue by m0rph3u** [Apollon77/ioBroker.alexa2#878]
Hallo,

Ich habe meinen Robotersauger via Alexa angebunden. Zugegebenermaßen das Alexa Skill vom Hersteller ist absolut schlecht.
Neben Ein/Aus finden sich in der Alexa App nur noch die zwei Punkte Charge und Delicates (Siehe Screenshot).

Leider wird mir im Alexa2 Adapter in ioBroker nur Ein/Aus angezeigt, jedoch nicht die zwei extra Punkte.?

Woran könnte das liegen? An dem schlecht Programmierten Alexa Skill? Oder wird diese Funktionalität nicht vom Adapter unterstützt? Gibt es eine Möglichkeit die Punkte dennoch in ioBroker irgendwie zugänglich zu machen?

Viele Grüße
![Screenshot_20220423-100530_Amazon Alexa](https://user-images.githubusercontent.com/73857179/164886615-482f948b-b6d8-4091-930a-f676a856c3b2.jpg)
#

**Comment by Apollon77** [comment]
Bitte den Loglevel des Alexa2 Instanz unter Instanzen (mit aktiven expertenmodus) von info auf debug stellen. Dann startet der Adapter neu. Das komplette Log vom Start bitte aus dem Logfile auf Platte holen (/opt/iobroker/log/...) und mit per Email mit Verweis auf dieses Issue an iobroker@fischer-ka.de senden. Muss ich schauen

**Comment by Apollon77** [comment]
Plesse try GitHub version and report back
