### ISSUE TITLE
MAC-Adresse als Datenpunkt

### ISSUE THREAD

**Issue by djmarc75** [Apollon77/ioBroker.alexa2#879]
Servus,
da man ja in der APP die MAC-Adresse des jeweiligen Gerätes sehen kann, wäre es denn auch machbar diese als Datenpunkt zu integrieren ?
Merci

**Comment by Apollon77** [comment]
Will be in next version

**Comment by djmarc75** [comment]
fixed in 3.14.0 - thanks
