### ISSUE TITLE
Alexa2 Adapter Warn

### ISSUE THREAD

**Issue by Andi19851985** [Apollon77/ioBroker.alexa2#88]
Hallo,
seit einigen Tagen kriege ich folgende Warnungen im Log für den Alexa2 Adapter.
Ich habe versucht den Adapter neu zu installieren doch leider bleibt es bei den Warnungen.
Ich kann leider mit den Meldungen nicht anfangen.
Vielleicht kann mir da jemand helfen diese weg zu kriegen.

Gruß
Andreas 

[iobroker.2018-09-05.log](https://github.com/Apollon77/ioBroker.alexa2/files/2350585/iobroker.2018-09-05.log)

**Comment by Apollon77** [comment]
Danke. Bitte schau mal deine Geräte durch welches unter Info.deviceType AMW12B274RAL7 stehen hat. 

Was ist das für ein Gerät?
Kannst du per alexa App Routinen anlegen und auf dem Gerät zb sprache ausgeben?

**Comment by Apollon77** [comment]
Ps:weiterhin willst in den adaptereinstellungen vllt die Push Verbindung einschalten.

**Comment by Andi19851985** [comment]
Vielen Dank für die schnelle Antwort.
Ich habe das Gerät jetzt gefunden und entfern.
Die Meldung scheint jetzt weg zu bleiben.
Es war nur eine Alexa App (PFM-Alexa) die ich mir zum testen runtergeladen hatte.

Danke nochmal für deine Support

**Comment by Apollon77** [comment]
kannst Du aber bitte nochmal die "Capabilities "von dem Device schicken ?! Dann baue ich ein das es erkannt wird. Das Log kann ich irgendwie nicht lesen wenn ich drauf klicke
