### ISSUE TITLE
Add Smart Home Device: Levoit Classic 300S

### ISSUE THREAD

**Issue by apper13** [Apollon77/ioBroker.alexa2#880]
I am using the Levoit Classic 300S Air Humidifier. It is connected to Alexa and the easiest way to use it in iobroker is to use the smart home function of Alexa2 adapter.
Switching on and off already works. But there are some more functions and it would be great if these would also work.

The available data points are:

- Humidifier.Mode (Off, Automatic, Manual)
- Humidifier.Light (Off, Dimmed, On)
- Humidifier.Display (Off/On)
- Humidifier.Mist (for automatic mode - turns on under this threshold)

Thank you.

**Comment by m0rph3u** [comment]
Hello,
it seems to be a similar problem as in this post here
[https://github.com/Apollon77/ioBroker.alexa2/issues/878](https://github.com/Apollon77/ioBroker.alexa2/issues/878)

**Comment by apper13** [comment]
Thank you. I already mailed logs regarding this Humidifier to Apollon77.

**Comment by Apollon77** [comment]
Plesse try GitHub version and report back
