### ISSUE TITLE
New Devices report to developer

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.alexa2#889]
Adapter reports at start this: ( firstdevice Echo Show 5, second LG TV with Alexa Support (A2IS7199CJBT71) )

`alexa2.0 | 2022-05-06 08:31:11.920 | info | Device-type:A1XWJRHALS1REP (SUPPORTS_LOCALE,GOLDFISH,SUPPORT_CALENDAR_ALERT,TIDAL,AUDIO_PLAYER,TUNE_IN,KINDLE_BOOKS,GUARD_EARCON,BT_PAIRING_FLOW_V2,EQUALIZER_CONTROLLER_BASS,MULTI_WAKEWORDS_SUPPORTED,PAIR_BT_SINK,LIVE_VIEW,DIALOG_INTERFACE_VERSION,SET_LOCALE,APPLE_MUSIC,DEEZER,LEMUR_ALPHA,EQUALIZER_CONTROLLER_MIDRANGE,FAR_FIELD_WAKE_WORD,FLASH_BRIEFING,I_HEART_RADIO,CHANGE_NAME,SIRIUSXM,ALEXA_PRESENCE,DREAM_TRAINING,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,EQUALIZER_CONTROLLER_TREBLE,AUDIBLE,REMINDERS,SHARKNADO,SPEECH_RECOGNIZER_USS,EARCONS,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,TIMERS_AND_ALARMS,CLOCK_FORMAT_24_HR,DEREGISTER_DEVICE,SLEEP,AMAZON_MUSIC,SALMON,ALEXA_VOICE,AUDIO_CONTROLS,DS_VOLUME_SETTING,MICROPHONE,SOUND_SETTINGS,MUSIC_SKILL,PERSISTENT_CONNECTION,SUPPORTS_LOCALE_SWITCH,CUSTOM_ALARM_TONE,SUPPORTS_SOFTWARE_VERSION,ASCENDING_ALARM_VOLUME,VOLUME_SETTING,EFDCARDS,ADAPTIVE_LISTENING,PANDORA,VOICE_TRAINING,WAKE_WORD_SENSITIVITY)
-- | -- | -- | --
alexa2.0 | 2022-05-06 08:31:11.920 | info | Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2022-05-06 08:31:11.920 | info | Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2022-05-06 08:31:11.900 | info | Device-type:A2IS7199CJBT71 (SUPPORTS_LOCALE,GOLDFISH,REMINDERS,TIDAL,AUDIO_PLAYER,TUNE_IN,KINDLE_BOOKS,SPEECH_RECOGNIZER_USS,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,TIMERS_AND_ALARMS,EARCONS,MULTI_WAKEWORDS_SUPPORTED,DEREGISTER_DEVICE,SLEEP,AMAZON_MUSIC,DIALOG_INTERFACE_VERSION,SET_LOCALE,MICROPHONE,APPLE_MUSIC,DEEZER,TOUCH_INITIATED,SOUND_SETTINGS,MUSIC_SKILL,PERSISTENT_CONNECTION,SUPPORTS_LOCALE_SWITCH,CUSTOM_ALARM_TONE,I_HEART_RADIO,CHANGE_NAME,SIRIUSXM,SET_TIME_ZONE,VOLUME_SETTING,ASCENDING_ALARM_VOLUME,DREAM_TRAINING,ADAPTIVE_LISTENING,AUDIBLE,WAKE_WORD_SENSITIVITY)
alexa2.0 | 2022-05-06 08:31:11.900 | info | Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 | 2022-05-06 08:31:11.896 | info | Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 | 2022-05-06 08:31:11.301 | info | Alexa-Push-Connection (macDms = true) established. Disable Polling
alexa2.0 | 2022-05-06 08:31:04.133 | info | starting. Version 3.12.0 in /opt/iobroker/node_modules/iobroker.alexa2, node: v16.14.2, js-controller: 4.0.23`

**Comment by Apollon77** [comment]
For the TV: Are commands working when send via iobroker or routines?

**Comment by Apollon77** [comment]
added I think
