### ISSUE TITLE
Ansagen nacheinander

### ISSUE THREAD

**Issue by Zippolighter** [Apollon77/ioBroker.alexa2#89]
https://forum.iobroker.net/viewtopic.php?p=176127#p176127

Es wäre sinnvoll wenn man mehrere Commandos nacheinander abspielen könnte.
Auch in der Kombination von Command und Speak

**Comment by Apollon77** [comment]
Die IDee hier wäre eine Message zu unterstützen wo man die Kommndos als Array übergeben kann mit Daten wenn nötig und so flexibel SequenceCommands aneinanderreihen kann.

**Comment by mkraemer0** [comment]
Die Funktion "alexa.sendMultiSequenceCommand" sendet ja schon mehrere Befehle nacheinander. Gäbe es hier eine Möglichkeit als Abschlußbefehl einen speziellen Datenpunkt im Echo-Device zu setzen, so daß man im Skript reagieren kann, wenn eine Ansage beendet wurde?

Prinzipiell geht das ja schon mit "speak-volume" und dem "volume"-Datenpunkt, nur muß man da jedesmal etwas basteln und ganz zuverlässig ist das auch nicht. Aber generell gibt es wohl das Problem, daß bei einem Abbruch durch den Anwender die nachfolgenden Befehle nicht ausgeführt werden.

**Comment by Apollon77** [comment]
Man kann nur senden. Es gibt keine Rückmeldung wenn etwas fertig ist. Sorry

**Comment by mkraemer0** [comment]
Doch, über den "volume"-Datenpunkt geht das ja derzeit, nur eben nicht so schön:

Man setze "speak-volume" auf den gewünschten Wert und setze "volume" ggf. auf einen anderen Wert. Nach dem Ende der Ansage wird dann "volume" auf den anderen Wert zurückgesetzt, worauf man reagieren kann. Das hat bei mir auch ganz gut funktioniert, allerdings hätte ich gerne einen eigenen Datenpunkt nur dafür.

Was für Befehle kann man denn an Alexa absetzen? Da wäre ja schon mal die Sprachausgabe und die Lautstärkeregelung. Kann man eventuell so auch ein Smarthome-Gerät (also einen Datenpunkt) einschalten? Über "bespoken" ginge das ja, aber ich weiß nicht, inwieweit diese Befehle kombinierbar sind.

**Comment by Apollon77** [comment]
Faktisch kannst du alles machen was über Routinen in der Alexa App geht.

**Comment by mkraemer0** [comment]
Auch über die o. g. Funktion "alexa.sendMultiSequenceCommand"? Dann könnte man ja nach der Ansage einen Befehl der Art "Schalte MeinDatenpunkt aus" absetzen, der wie das Zurücksetzen der Lautstärke nach dem Ende der Ansage ausgeführt wird.

**Comment by nathan1312** [comment]
Hallo, das Thema hatte ich auch mal im iobroker-Forum angesprochen. Wäre super wenn es da jetzt eine Lösung für gäbe!

**Comment by Apollon77** [comment]
Das Problem wird sein das generisch hinzubekommen. Da sehe ich das Problem drin.

**Comment by Apollon77** [comment]
sollte inzwixhen gefixt sein. Semikolon = mehrere texte
