### ISSUE TITLE
Alexa App Commands in History

### ISSUE THREAD

**Issue by Wlad2288** [Apollon77/ioBroker.alexa2#893]
Hi,

Ist es möglich, Kommandos, die man am Smartphone direkt in die Alexa App spricht, in der History.summary anzuzeigen?
Ich steuere darüber meine Automatisierungen und es wäre super, wenn ich auch mein Smartphone als "Alexa" nutzen könnte.

Mit der Ferbedienung des Fire TV Sticks funktioniert es.

Besten Dank,
Wlad

**Comment by Apollon77** [comment]
WIll be in next version
