### ISSUE TITLE
media progress update

### ISSUE THREAD

**Issue by liv-in-sky** [Apollon77/ioBroker.alexa2#9]
folgendes szenario (kleine priorität):
habe routine gestarttet - diese spielt ein lied auf einem bestimmten echo (aus der amazon bibliothek). media progress wird richtig angezeigt! 

sage nun mitten im lied - Stop.

current state bleibt auf playing und alle media anzeigen sagen weiterhin, das gespielt wird.

erst wenn das lied (zeitlich!) aus ist - obwohl der echo gar kein lied mehr spielt - werden die objekte richtig gesetzt. auch wenn ich den echo mit einem anderen befehl (mündlich oder mit adapter) ausführe bleibt die media anzeige bis die länge des liedes abgelaufenb ist.

ich weiß nicht, ob das nicht ein alexa fehler sein könnte

**Comment by Apollon77** [comment]
Wie schon in dem einen Forum Thread beschrieben: Alles von Alexa ist "pull" - also der Adapter muss Fragen und bekommt dann den Status.
Echo meldet sich nicht beim Adater wenn isich etwas ändert

Wenn Du also "am Adapter vorbei" Dinge tust (wie dein "Stop") dann bekommt das der Adapter erst dann mit wenn er das nächste mal den Status abfragt. Daher jetzt die Option update-Intervalle zu nutzen, so kannst Du z.B. minütlich bei Amazon fragen und hast damit maximal eine Minute diese "Fehleinschätzung" des Adapters.

Damit kann ich da nichts tun. sorry. Müsste aber beim "Hauke-Skript" auch so gewesen sein ...

**Comment by liv-in-sky** [comment]
ok - verstehe bzw.  auch wenn ich mit dem adapter z.b.tunein einschalte! wird dann keine status abgefragt bevor er das spielt?

**Comment by Apollon77** [comment]
Bei allen Aktionen über den Adapter werden 3sk danach automatisch alle States aktualisiert (damit er genau sowas erkennt).

**Comment by liv-in-sky** [comment]
gäbe es einen adapter-award für iobroker programmierer - du wärst nomminiert !

**Comment by Apollon77** [comment]
:-) Danke
