### ISSUE TITLE
Smarthome Device brightness false = 100

### ISSUE THREAD

**Issue by MarcoBonn** [Apollon77/ioBroker.alexa2#91]
Hallo :)

Ich benutze das HQ Widget bei dem ein Button auch eine Dim Funktion besitzt.
Hier konnte ich feststellen das der Datenpunkt Device.brightness  nach dem ausschalten wieder auf 100 gesetzt wird. So wird meine Anzeige leider immer an angezeigt.

PS: Vielen Dank für die gute Arbeit!

**Comment by Apollon77** [comment]
Naja da brauche ich bitte ein paar Details ... Was genau schreibt das Widget denn in den Datenpunkt? Das ist ein Zahlen-Datenpunkt der 0...100 annehmen kann. 
Am besten Alexa2 Adapter auf debug Loglebel stellen, dann maö per Widget ändenr und log anhängen von den "state changed" meldungen

**Comment by MarcoBonn** [comment]
Habe bedenken damit hier offentlich zuviel Preis zu geben. Aber ich habe mich auch unverständlich ausgedrückt denn das Problem tritt unabhänig vom Wiget auf.

Hier villt etwas verständlicher:
Wenn ich im Alexa2 Adapter bei der Lampe den Wert von 
brightness   manuell auf 100 setze 
wechselt powerState von false auf true.
Bis dahin alles ok.

Wenn ich nun den Wert 0 bei "brightness" eingebe,
wechselt auch der powerState  von true auf false

Nun kommt das Problem:
Kurze Zeit später (so 3 sek) wechselt der Wert ### **automatisch** "brightness" wieder auf 100 und powerstate bleibt auf false. 

Ich denke er sollte auf 0 bleiben oder ist das falsch ?

Vielen Dank für deine Zeit

**Comment by Apollon77** [comment]
Der Ablauf ist folgendermaßen: du änderst was, adapter sendet das zu Amazon. Nach Antwort werden (wenn unterstützt) 2s später die aktuellsten werte von Amazon abgefragt. Und aktualisiert. 

In dem ist es also Amazon was diese Änderung macht. Der Adapter zeigt es nur an. 

Also alles wie es sein soll.
