### ISSUE TITLE
Commands.speak-volume auch für Lautsprechergruppen

### ISSUE THREAD

**Issue by Marty56** [Apollon77/ioBroker.alexa2#912]
Es wäre schön, wenn es "Commands.speak-volume" auch für Lautsprechergruppen geben würde.
Ich kann nicht beurteilen, ob das aufgrund von Limitierungen des Amazon API möglich ist oder nicht.

**Comment by Apollon77** [comment]
Vollständiges debuglog bitte mit Info was eine Lautsprechergruppe ist bei Dir bitte an iobroker@fischer-ka.de Und bitte Zeigen welche States so eine Gruppe heute hat

**Comment by Marty56** [comment]
Ich wollte im Haus auf allen Lautsprechern einen Text mit derselben Lautstärke sprechen lassen.
Aber ich kann deine Bedenken verstehen.

Es müsste halt so gemacht werden, dass jedesmal, wenn man einen Text oder Ton aus einer Lautsprechergruppe ausgeben will, erst alle Lautstärken der einzelnen Lautsprecher zwischengespeichert werden, dann mit der Lautstärke der Gruppe überschrieben werden. Danach wird der Text ausgegeben und wieder danach wieder die vorher gespeicherten Lautstärken auf die Mitglieder der Gruppe zurückgeschrieben werden.

Ok, dass ist kompliziert. Lassen wir es lieber. Ich mache das händisch im meinem Script.

**Comment by Apollon77** [comment]
> auf allen Lautsprechern einen Text mit derselben Lautstärke sprechen lasse

Da sist halt meie Behauptung: ein Echo Dot 1 und ein Echo plus oder SHow ... selbst wenn du dort sagst 50% ist die Laustärke immer eine andere... Speak-Volue ist ja schon  die Idee wenigstens das so angleichen zu können das es sinn macht.

Aber Danke für dein verständnis :-)
