### ISSUE TITLE
State value to set for "..." has to be type "number" but received type "string" <-- ist aber eine Nummer

### ISSUE THREAD

**Issue by Flyor** [Apollon77/ioBroker.alexa2#913]
Seit dem latest Update, bekomme ich alle 2 Sekunden von 2 meiner Geräte (Midea Klimaanlage) eine Protokoll Fehlermeldung, dass der Typ des Objekts "Nummer" sein soll, aber "Zeichenkette" erhalten hat - was jedoch falsch ist. 

Es geht im speziellen Fall um die Punkte:
alexa2.0.Smart-Home-Devices.ab92baca-647c-4442-b07c-6344de37791a.targetSetpoint
alexa2.0.Smart-Home-Devices.f8cdd33a-7393-4b1c-9470-76ae642e028a.targetSetpoint

Hier ein Screenshot des Objektbaums: 
![image](https://user-images.githubusercontent.com/64526892/178081780-68d8c4e5-e0a5-4768-8427-03da462c66ef.png)

Hinter oder vor dem Wert ist auch kein Leerzeichen o.ä.
![image](https://user-images.githubusercontent.com/64526892/178081838-d0158aef-1339-49c6-90ba-e6c3ea6fb0a3.png)

Ich habe alle Smart Home Geräte im Objektbaum bereits gelöscht, den Adapter neu installiert etc. Es kommt immer der gleiche Fehler bei diesem Gerät. 

Adapter: 3.14.0
Node: 14.16.0
js: 4.0.23

**Comment by Apollon77** [comment]
Bitte Loglevel der Instanz auf Debug setzen und vollständiges log vom Adapterstart biw diee Meldung kommt von der Platte nehmen (/opt/iobroker/log/...) und mir per E-Mail unter referenz auf dieses issue an iobroker@fischer-ka.de senden

**Comment by Flyor** [comment]
Erledigt. @Apollon77

**Comment by Apollon77** [comment]
Ja, soooo klar ... das Gerät meldet den Wert auch als String  obwohl es eine Zahl sein sollte ... grmppff. Formal wäre das ein Bugreport an den Skill-Owner ;-) Aber auf der Ebene ist ja ausser uns hier keiner unterwegs. Ich schaue mal ob ich das sinnvoll konvertiert bekomme

**Comment by Apollon77** [comment]
Bitte GitHub version versuchen. Ists da weg und kommt der korrekte Wert an?

**Comment by Apollon77** [comment]
PS: Ich habe eben (16:59) GitHub nochmal aktualisiert weil ich in Deinem Log noch zweo Battery Zustände gefundennhabe die aktuell nicht unterstützt waren.

Das ganze beim "Nuki Smart Lock".

Also wenn Du checks bitte die neue letzte Versionn nehmen und danach schauen ob wu beim Nuki Smart Lock in den Objekten batteryHealthState und batteryChargingHealthState hast und Werte sollten beide true sein ... Danke!

**Comment by Flyor** [comment]
Er will irgendwie nicht. 
![image](https://user-images.githubusercontent.com/64526892/178113666-d78cfbe4-0435-45c0-bd34-675dd03209e3.png)
Läuft seit 10min. Mach ich was falsch? Github Link vom adapter, adapter installieren benutzerdef. URL probiert und über den Github Reiter.

**Comment by Apollon77** [comment]
Github Installs mit nopm 6 daaaauuueeerrn aktuel wegen nem bug inn npm6 ... aloso warten ... ja 10 mins keine seltenheit

**Comment by Flyor** [comment]
<html>
<body>


alexa2.0 | 2022-07-09 18:36:00.921 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
alexa2.0 | 2022-07-09 18:36:00.921 | info | terminating
alexa2.0 | 2022-07-09 18:36:00.912 | error | Cannot read property 'id' of null
alexa2.0 | 2022-07-09 18:36:00.912 | error | TypeError: Cannot read property 'id' of null at createNotificationStates (/opt/iobroker/node_modules/iobroker.alexa2/main.js:2919:60) at /opt/iobroker/node_modules/iobroker.alexa2/main.js:2027:37 at processObjectQueue (/opt/iobroker/node_modules/iobroker.alexa2/main.js:383:21) at /opt/iobroker/node_modules/iobroker.alexa2/main.js:425:16 at /opt/iobroker/node_modules/iobroker.alexa2/main.js:398:44 at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/main.js:419:32) at processImmediate (internal/timers.js:463:21)
alexa2.0 | 2022-07-09 18:36:00.912 | error | uncaught exception: Cannot read property 'id' of null
alexa2.0 | 2022-07-09 18:36:00.911 | warn | Exception: TypeError: Cannot read property 'id' of null
alexa2.0 | 2022-07-09 18:35:58.001 | info | Alexa-Push-Connection (macDms = true) established. Disable Polling
alexa2.0 | 2022-07-09 18:35:54.098 | info | Proxy IP not set, use first network interface (192.168.178.193) instead
alexa2.0 | 2022-07-09 18:35:54.017 | info | starting. Version 3.15.0 (non-npm: Apollon77/ioBroker.alexa2) in /opt/iobroker/node_modules/iobroker.alexa2, node: v14.16.0, js-controller: 4.0.23


</body>
</html>

Der adapter geht nur kurz auf grün, danach direkt Neustart Loop

**Comment by Apollon77** [comment]
Fix auf GitHub ... 3.15.1 auf dem Weg

**Comment by Apollon77** [comment]
Bitte nochmal neu installieren

**Comment by Flyor** [comment]
Perfekt, keine Meldungen mehr. Vielen Dank für deine Arbeit!
Und das mit Nuki:
leider werden nur die folgenden Objekte erstellt:

![image](https://user-images.githubusercontent.com/64526892/178115804-3a10e5dd-1d67-4c7d-9dc6-d87fb4a17b8e.png)

**Comment by Apollon77** [comment]
Haste dann bitte nochmal ein Debug log?

**Comment by Flyor** [comment]
Ist gesendet.

**Comment by Apollon77** [comment]
Mist, da war wohl ein Bug in der veersion ... kannste bitte nochmal GitHub machen und das log senden? Sorry

**Comment by Apollon77** [comment]
(bzw checke mal ob es dann nicht tut) :-)

**Comment by Flyor** [comment]
Jetzt sieht es besser aus :) 
![image](https://user-images.githubusercontent.com/64526892/178118782-ea33fca9-3f79-4502-bcdf-5ae71043df40.png)
Brauchst noch das Log? Sollte aber soweit sogar über das issue hinaus perfekt umgesetzt sein.

**Comment by Apollon77** [comment]
Ja bitte weil die werte bei den beiden "health" sollten 1 true sein ;-(

**Comment by Flyor** [comment]
Die Werte wären aber korrekt :D 92% steht auch in der App und kommt hin da neue Batterien. Ich sende dir das Log.

**Comment by Apollon77** [comment]
Ja, aber die beiden "healthState" müssten "true" sein :-)

**Comment by Grothesk242** [comment]
Ich kaper den Thread mal... :-) 
Ist das hier ein ähnlicher Fall? 

```
info: alexa2.0 (264687) State value to set for "alexa2.0.Smart-Home-Devices.48750f11-1811-4dc9-8968-7fe27e1694c9.powerLevelType" has to be type "string" but received type "number"
```
Das ist auch ein Device aus einem Skill (xiaomi SmartHome). 

<img width="760" alt="image" src="https://user-images.githubusercontent.com/57298681/178119478-fe16a2a0-cc0c-44a6-af5e-78885a04a28a.png">

**Comment by Flyor** [comment]
Mail ist raus mit neuem Log.

**Comment by Apollon77** [comment]
@Grothesk242 Wenn mit 3.15.2 dann Debug log bitte :-)

**Comment by Apollon77** [comment]
Ich denke haben wir jetzt ,,... 3.17.0

**Comment by Apollon77** [comment]
3.15.1
