### ISSUE TITLE
Speak gibt keine Ausgabe / Routinen starten nicht bei Version >3.1.4

### ISSUE THREAD

**Issue by holofury** [Apollon77/ioBroker.alexa2#915]
Moin,

es sind alte Problem ist mit den Versionen > 3.1.4 wieder aufgetaucht:

- Im Datenpunkt "speak" eingetragene Werte werden nicht wiedergegeben.
- Routinen werden nicht ausgelöst.

Version 3.1.4 funktioniert dagegen einwandfrei.

**Comment by Apollon77** [comment]
Wir testen gerade 3.17.1 ... Bitte diese Beta version testen und Issue neu anlegen wenn nötig.
