### ISSUE TITLE
Commands.announcement mit Übergabe der Lautstärke durch "volume;text" analog zu speak

### ISSUE THREAD

**Issue by Diginix** [Apollon77/ioBroker.alexa2#916]
Aktuell wird bei einem String "volume;text" in alexa2.*.Echo-Devices.*.Commands.announcement die Lautstärke kurz vor der Sprachausgabe zwar auf den Wert vor dem Semikolon gesetzt. Zumindest zeigt das der LED Ring vom Echo Dot so an.
Die Ausgabe selbst erfolgt aber dann trotzdem mit der Lautstärke aus alexa2.*.Echo-Devices.*.Player.volume.
Anscheinend ignoriert Amazon bei announcements das was bei speak wunderbar funktioniert.
Ein Workaround könnte sein Player.volume kurz vor announcement Ausgabe auf den Sollwert zu setzen und kurz nach Ausgabe wieder zurück auf den alten Volumewert.

Erfolglos bisher getestet mit Adapter v3.17.x und Echot Dot Gen. 2+3

**Comment by Apollon77** [comment]
3.15.1

**Comment by Diginix** [comment]
You mean 3.17.1 ;-)

**Comment by Apollon77** [comment]
yes :-)) these fast version increases make me crazy ;-)

Pleas everify and report back here or in forum please!

**Comment by Diginix** [comment]
Seems to be working fine with 3.17.3. Thanks
