### ISSUE TITLE
type should be string but received type object

### ISSUE THREAD

**Issue by daniel-lo** [Apollon77/ioBroker.alexa2#918]
Heute das erste Mal gesehen 3.15.2

<html><body>

alexa2.0 | 2022-07-12 17:56:47.109 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
-- | -- | -- | --
alexa2.0 | 2022-07-12 17:56:42.421 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:56:37.604 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:56:32.753 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:56:28.124 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:56:23.396 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:56:18.664 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:56:13.952 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:56:09.279 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:56:04.353 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:55:59.470 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:55:54.728 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:55:49.876 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:55:45.104 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:55:40.425 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:55:35.760 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:55:31.000 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:55:26.334 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:55:21.698 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:55:16.840 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"
alexa2.0 | 2022-07-12 17:55:12.044 | info | State  value to set for  "alexa2.0.Smart-Home-Devices.06b1f4bf-bda3-4946-a972-5d4f01c7b4f9.connectivity-reason"  has to be type "string" but received type "object"

</body>
</html>

**Comment by gitknd** [comment]
Bekomme ich nun auch alle paar Sekunden mit der 3.17.2

State value to set for "alexa2.0.Smart-Home-Devices.xxxxxxxxxxxxxxxxxxxxxxxxbf3f0d2f.connectivity-reason" has to be type "string" but received type "object"

**Comment by reloxx13** [comment]
This is spamming my pihole to death, 20k request today

**Comment by reloxx13** [comment]
Some more logging for both errors



alexa2.0 | 2022-07-12 20:31:49.409 | silly | States  user redis pmessage  io.alexa2.0.*/io.alexa2.0.Smart-Home-Devices.eeffda27-3e2e-4e2f-bad8-fce2305ec2dd.colorRgb:{"val":{"hue":180,"saturation":1,"brightness":1},"ack":true,"ts":1657650707470,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":1657650707470}
-- | -- | -- | --







alexa2.0 | 2022-07-12 20:32:11.661 | debug | State  changed  alexa2.0.Smart-Home-Devices.eeffda27-3e2e-4e2f-bad8-fce2305ec2dd.connectivity-reason:   {"val":{"value":"OK"},"ack":true,"ts":1657650727070,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":1657649350100}
-- | -- | -- | --
alexa2.0 | 2022-07-12 20:32:11.650 | silly | States  user redis pmessage  io.alexa2.0.*/io.alexa2.0.Smart-Home-Devices.eeffda27-3e2e-4e2f-bad8-fce2305ec2dd.connectivity-reason:{"val":{"value":"OK"},"ack":true,"ts":1657650727070,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":1657649350100}

**Comment by Apollon77** [comment]
please check 3.17.3 just on it's way and verify that all is back ok there

**Comment by daniel-lo** [comment]
Bei mir wieder ok .. vielen Dank!

**Comment by reloxx13** [comment]
Errors are gone, but there are still alot of request to `eu-api-alexa.amazon.de`, as it would ignore poll times.

![grafik](https://user-images.githubusercontent.com/14855001/178661975-75855cce-6c2d-479a-803b-eb7861606cf4.png)


![grafik](https://user-images.githubusercontent.com/14855001/178661830-b47f225f-bc20-4713-8095-0327d5a095f6.png)


in logs those are reoccuring entries

```
<html><body>
<!--StartFragment-->

Alexa-Remote:  Sending Request with  {"host":"eu-api-alexa.amazon.de","path":"/api/phoenix/state","method":"POST","timeout":15000,"headers":{}}   and  data={"stateRequests":[{"entityId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjhhNjYzMDNjLTI3NWUtNDUzYy1iN2ViLWUxMjllMTE2YjZlOCIsInN0YWdlIjoibGl2ZSJ9_D8F15BD6C2FA","entityType":"APPLIANCE"},{"entityId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjhhNjYzMDNjLTI3NWUtNDUzYy1iN2ViLWUxMjllMTE2YjZlOCIsInN0YWdlIjoibGl2ZSJ9_C82B964018BB","entityType":"APPLIANCE"},{"entityId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjVlMTU3MjhiLTFhOGUtNGRmZS1hODJiLTRjMTQyMGNhNmU2YiIsInN0YWdlIjoibGl2ZSJ9_1iNRDJYyKtfj8qUCJ7PqCn","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00181983","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0079C59D","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0032ABCA","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00DBCF5E","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00D5C12B","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00D49741","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00D45C7C","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_9a19a806-b45f-3755-88c8-44d4883581a8","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0013C52B","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00A333BC","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_bcd86b49-b58c-39b8-92bc-43dd18bb9ccc","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0073ECB4","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K000FC177","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K005D5F25","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0087426B","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0045B3F7","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0045ABDB","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00459224","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0042EF9D","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K003B6544","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00DBE491","entityType":"APPLIANCE"},{"entityId":"AlexaBridge_G091JJ13151703EW@A2H4LV5GIZ1JFT_G091JJ13151703EW","entityType":"APPLIANCE"}]}
--
alexa2.0 | 2022-07-13 08:07:52.573 | debug | Alexa-Remote:  Sending Request with  {"host":"eu-api-alexa.amazon.de","path":"/api/phoenix?includeRelationships=true&_=1657692472573","method":"GET","timeout":30000,"headers":{}}
alexa2.0 | 2022-07-13 08:07:45.140 | debug | Alexa-Remote:  Sending Request with  {"host":"eu-api-alexa.amazon.de","path":"/api/phoenix/state","method":"POST","timeout":15000,"headers":{}}   and  data={"stateRequests":[{"entityId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjhhNjYzMDNjLTI3NWUtNDUzYy1iN2ViLWUxMjllMTE2YjZlOCIsInN0YWdlIjoibGl2ZSJ9_D8F15BD6C2FA","entityType":"APPLIANCE"},{"entityId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjhhNjYzMDNjLTI3NWUtNDUzYy1iN2ViLWUxMjllMTE2YjZlOCIsInN0YWdlIjoibGl2ZSJ9_C82B964018BB","entityType":"APPLIANCE"},{"entityId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjVlMTU3MjhiLTFhOGUtNGRmZS1hODJiLTRjMTQyMGNhNmU2YiIsInN0YWdlIjoibGl2ZSJ9_1iNRDJYyKtfj8qUCJ7PqCn","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00181983","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0079C59D","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0032ABCA","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00DBCF5E","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00D5C12B","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00D49741","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00D45C7C","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_9a19a806-b45f-3755-88c8-44d4883581a8","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0013C52B","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00A333BC","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_bcd86b49-b58c-39b8-92bc-43dd18bb9ccc","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0073ECB4","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K000FC177","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K005D5F25","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0087426B","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0045B3F7","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0045ABDB","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00459224","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0042EF9D","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K003B6544","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00DBE491","entityType":"APPLIANCE"},{"entityId":"AlexaBridge_G091JJ13151703EW@A2H4LV5GIZ1JFT_G091JJ13151703EW","entityType":"APPLIANCE"}]}
alexa2.0 | 2022-07-13 08:07:44.785 | debug | Alexa-Remote:  Sending Request with  {"host":"eu-api-alexa.amazon.de","path":"/api/phoenix?includeRelationships=true&_=1657692464785","method":"GET","timeout":30000,"headers":{}}
alexa2.0 | 2022-07-13 08:07:37.247 | debug | Alexa-Remote:  Sending Request with  {"host":"eu-api-alexa.amazon.de","path":"/api/phoenix/state","method":"POST","timeout":15000,"headers":{}}   and  data={"stateRequests":[{"entityId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjhhNjYzMDNjLTI3NWUtNDUzYy1iN2ViLWUxMjllMTE2YjZlOCIsInN0YWdlIjoibGl2ZSJ9_D8F15BD6C2FA","entityType":"APPLIANCE"},{"entityId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjhhNjYzMDNjLTI3NWUtNDUzYy1iN2ViLWUxMjllMTE2YjZlOCIsInN0YWdlIjoibGl2ZSJ9_C82B964018BB","entityType":"APPLIANCE"},{"entityId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLjVlMTU3MjhiLTFhOGUtNGRmZS1hODJiLTRjMTQyMGNhNmU2YiIsInN0YWdlIjoibGl2ZSJ9_1iNRDJYyKtfj8qUCJ7PqCn","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00181983","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0079C59D","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0032ABCA","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00DBCF5E","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00D5C12B","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00D49741","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00D45C7C","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_9a19a806-b45f-3755-88c8-44d4883581a8","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0013C52B","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00A333BC","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_bcd86b49-b58c-39b8-92bc-43dd18bb9ccc","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0073ECB4","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K000FC177","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K005D5F25","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0087426B","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0045B3F7","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0045ABDB","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00459224","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K0042EF9D","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K003B6544","entityType":"APPLIANCE"},{"entityId":"AAA_SonarCloudService_uuid:Socket-1_0-201612K00DBE491","entityType":"APPLIANCE"},{"entityId":"AlexaBridge_G091JJ13151703EW@A2H4LV5GIZ1JFT_G091JJ13151703EW","entityType":"APPLIANCE"}]}

<!--EndFragment-->
</body>
</html>
```

**Comment by Apollon77** [comment]
YOu found a bug when 0 is set to disable smart home device query. Fix will come in next version, for now just enter 3600 or such for hourly there instead of 0

**Comment by Apollon77** [comment]
3.117.4 will fix this .... on it's way

**Comment by Apollon77** [comment]
@reloxx13 please also have a look at 3.18.1+ see also details https://forum.iobroker.net/topic/56437/alexa2-adapter-3-18-x-beta
