### ISSUE TITLE
Unknown device 'Device-type:A25OJWHZA1MWNB'

### ISSUE THREAD

**Issue by todde99** [Apollon77/ioBroker.alexa2#919]
Just found the following log entry after updating the (_really awesome!_) adapter this morning:
`Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
Device-type:A25OJWHZA1MWNB - John's 2021 Samsung QLED TV W/ Far-field Voice (2021 Samsung QLED TV W/ Far-field Voice) (2021 Samsung QLED TV W/ Far-field Voice) (AMAZON_MUSIC,ASCENDING_ALARM_VOLUME,TIMERS_AND_ALARMS,HANDS_FREE,TUNE_IN,MULTI_WAKEWORDS_SUPPORTED,I_HEART_RADIO,DEEZER,PERSISTENT_CONNECTION,KINDLE_BOOKS,DREAM_TRAINING,SUPPORTS_LOCALE_SWITCH,DIALOG_INTERFACE_VERSION,VOLUME_SETTING,ADAPTIVE_LISTENING,GOLDFISH,SOUND_SETTINGS,SLEEP,CHANGE_NAME,MUSIC_SKILL,DEREGISTER_DEVICE,SPEECH_RECOGNIZER_USS,TIDAL,REMINDERS,SUPPORTS_LOCALE,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,AUDIBLE,FAR_FIELD,SET_LOCALE,EARCONS,SET_TIME_ZONE,CUSTOM_ALARM_TONE,APPLE_MUSIC,AUDIO_PLAYER,TOUCH_INITIATED,MICROPHONE,SIRIUSXM)`

It is a Samsung TV Neo QLED 4K QN95A (2021) with Alexa activated.

**Comment by Apollon77** [comment]
Are commands possible for what works on this device?

**Comment by todde99** [comment]
Yes, the commands are working. I tested now nearly all (also speak-volume) of them.

**Comment by Apollon77** [comment]
thank you, will be integrated in next version
