### ISSUE TITLE
Möglichkeit um Sounds abzuspielen vor/nach Sprachdurchsage

### ISSUE THREAD

**Issue by MiJo112** [Apollon77/ioBroker.alexa2#92]
Hi,
ich suche eine Möglichkeit um einen Alarmsound bei einer Sprachdurchsage abzuspielen, da sonst die Durchsage schonmal überhört wird.
Über die Amazon SoundLibrary sind auch gute Sounds zu finden, nur werden die <audio> Tags in dem Speak Datenpunkt nicht berücksichtigt.

https://developer.amazon.com/de/docs/custom-skills/scifi-sounds.html#
Muss ich eine andere Syntax verwenden, oder ist dies nicht möglich?

**Comment by Apollon77** [comment]
Geht nicht, sorry. Wenn du es mit Routinen in der alexa app hinbekommst kann es der Adapter sich sonst nicht. Sorry

**Comment by Apollon77** [comment]
vllt per ssml ... https://forum.iobroker.net/viewtopic.php?f=37&t=19110&p=218008#p218008

**Comment by MiJo112** [comment]
Über SSML kann ich nun jede menge Komandos schicken (Verschiedene Sprecher, Geschwindigkeit...) nur die Audio ssml funktionieren bei mir nicht.
Im Debug Log ist nichts auffälliges. Hier die Demo von Amazon:
`<speak>
    This is Alexa's regular speech, followed by the sound effect "scifi air escaping (1)".
    <audio src='soundbank://soundlibrary/scifi/amzn_sfx_scifi_air_escaping_01'/>
</speak>
`
Ne idee warum?

**Comment by Apollon77** [comment]
Bisherige weitere tests bestätigen das. geht aktuell nicht ....

**Comment by nukleuz80** [comment]
Ist das immer noch so, dass die Audiofiles nicht über SSML abgespielt werden können?

Danke :)

**Comment by Apollon77** [comment]
Laut Berichten geht wohl das hier https://developer.amazon.com/en-US/docs/alexa/custom-skills/ask-soundlibrary.html ... aber nichts eigenes
