### ISSUE TITLE
IMPORTANT: Smart Home devices partially no longer available in adapter!

### ISSUE THREAD

**Issue by Apollon77** [Apollon77/ioBroker.alexa2#920]
Hi,

because of an Bug introduced in Beta 3.14 and fixed in 3.17.4 the adapter did sometimes too many communication calls to the Amazon Systems.

Amazon seemed to have reacted with an addition rate limit to protect their systems and customers which is a completely valid response.

Because of this most likely smart home devices are not sysnced by the adapter for now.
We are in communication, but the most important is that all users that use an affected version update to 3.17.4 or higher!

**Comment by fuchs-1978** [comment]
Bei mir waren auch keine Objekte mehr im Adapter vorhanden. Ich bin einfach nur auf die Webseite alex.amazon.de gegangen und habe dort unter den Geräten die Suche angestoßen. Danach waren wieder alle Objekte vorhanden. Ich habe vorher nichts gelöscht

**Comment by mactwin** [comment]
Just updated to 3.17.4, but again nothing works....

**Comment by mactwin** [comment]
I've read it, maybe too much call to Amazon service.... sigh, is a disaster because nothing works in my domotic ....

Again tnx for fast support

**Comment by Apollon77** [comment]
It was a bug in a beta version of the adapter introduced by me ... so Amazon only reacted to that to prptect their systems (especially now with prime Day and such ... so "perfect" timepoint for that fuckup :-((

We need to wait until the users that got the affected buggy versions updated to the fixed once ... with every of them the situation should become better for all.

**Comment by DennjoOyola** [comment]
Same Problem here. After deleting Alexa2 within iobroker i can just reinstall Alexa2 v3.11.2 and it will not show me any kind of smart home devices. Will this be fixed within v3.17.5 and at what time this update will be available inside of iobroker?

**Comment by rhigma** [comment]
> Same Problem here. After deleting Alexa2 within iobroker i can just reinstall Alexa2 v3.11.2 and it will not show me any kind of smart home devices. Will this be fixed within v3.17.5 and at what time this update will be available inside of iobroker?

3.17.5 is available in beta repository. No upgrade will bring back your smart home devices, though. Amazon has to flip a switch.

**Comment by NAmeierhofer** [comment]
also normal, that no data is shown from the devices there are still avail? i get everytime (null) %?

**Comment by Apollon77** [comment]
Simply change NOTHING if you use an other version then 3.14-3.17.3 ... yes it can be that devices disappear (if you restart the adapter) or that values are missing and data are empty. All of this is cause by the rate limits of Amazon. We need to waiit for the functionality to restore, sorry

**Comment by BenS89** [comment]
Hi all, so when updated to 3.17.5, there is currently no chance to retrieve the Smart Home Devices once they disappeared from the Object tree? What if Amazon keeps the API restriction?

**Comment by JWSchumacher** [comment]
Hi, everyone. 
After disabling alexa2 last night i restarted it this morning.
All my smart home devices were restored instantly.
Unfortunately, all states are still filled with (null).
Can you confirm that it is still a problem with amazon or is it a problem with my local installation?

**Comment by actionbyte** [comment]
Yesterday I switched from the beta version to version v3.10.4 and was able to add my DP through the Alexa search. After that, all instructions seemed to work again. But today, although the DPs are still there, they no longer work. Is that possible despite the V3.10.4?

**Comment by JWSchumacher** [comment]
> Yesterday I switched from the beta version to version v3.10.4 and was able to add my DP through the Alexa search. After that, all instructions seemed to work again. But today, although the DPs are still there, they no longer work. Is that possible despite the V3.10.4?

I think all versions of the application are affected as it is a data limitation from Amazon

**Comment by Apollon77** [comment]
@BenS89
>  What if Amazon keeps the API restriction?

About what if we think about when it stay problematic after the issue is solved. ... no need to have horror visions now ... We will find ways in worst case ...

@JWSchumacher Yes this is the current issue. Sometimes you get values, someties not ... so simple let it run and be happy when you have the devices and sometimes there might come also values. Sorry for now

**Comment by beandi** [comment]
Seems to work again (in my case) - all devices visible and controllable

**Comment by Sehstern** [comment]
> Seems to work again (in my case) - all devices visible and controllable

As Apollon77 said, some requests could go through. In my Case, there still aren't any Smart Home Devices. So you maybe just had luck.

**Comment by beandi** [comment]
> > Seems to work again (in my case) - all devices visible and controllable
> 
> As Apollon77 said, some requests could go through. In my Case, there still aren't any Smart Home Devices. So you maybe just had luck.

Sure, but i'm quite positive. There was no device listed for 2 days, and suddenly all of them reappeared. Didn't change a thing (v3.17.5).

**Comment by HerbertJoos** [comment]
> 

It is normal. that the devices appear again. But that doesn't change the problem!

**Comment by HerbertJoos** [comment]
> > > Seems to work again (in my case) - all devices visible and controllable
> > 
> > 
> > As Apollon77 said, some requests could go through. In my Case, there still aren't any Smart Home Devices. So you maybe just had luck.
> 
> Sure, but i'm quite positive. There was no device listed for 2 days, and suddenly all of them reappeared. Didn't change a thing (v3.17.5). Maybe they are removing the limitations incrementally.

It is normal. that the devices appear again. But that doesn't change the problem!

**Comment by Apollon77** [comment]
Ok we have roughly 400 installations left that are potentially problematic but also the limitations are hitting less as I experienced (sttill here and there, es, but not that often anymore)

**Comment by WaldemarCichon** [comment]
I have the same problems with 3.11.2. Should an update to mentioned 3.17 beta help?
Can you see something in the logs?

Regards

Waldemar

**Comment by WaldemarCichon** [comment]
Sorry, it took some time, but now they appeared

**Comment by inidona** [comment]
@Apollon77 yesterday all my devices were lost again. Today after adapter restart it is working again.

**Comment by Apollon77** [comment]
Yes, there are still roughly 300 version affected out there. The new 3.18 should optimize here too, but still Beta

**Comment by JayVee2** [comment]
Still on stable V3.11.2:
When performing an Device Search in the Alexa App, smart-home.devices gets refilled after a while.
When rebooting, smart-home.devices are deleted again.
