### ISSUE TITLE
Alexa plugin doesn't work anymore

### ISSUE THREAD

**Issue by mactwin** [Apollon77/ioBroker.alexa2#922]
**Check if the Bug maybe is with Amazon**  
Alexa mobile app works, I can control any items in my network

**Describe the bug**  
I recently changed my msh network, but everything still works last night. This morning I notice that my automations no longer work. Alexa responded to the commands, the switches respond from the alexa app, but from iobroker I immediately noticed that all the "alexa2.0.Smart-Home-Devices" were gone. After updating iobroker in todo, I managed to request the list of devices, but despite everything they do not respond to the "powerState" change, which was previously possible directly from menu items.
I also tried to download a new Doker depot (buanet latest release), installed Alexa adapter, configured and .... nothing, not even download the device list. After a "search command" the device list has been downloaded, but again...I can't control any device (like turn on a light)

The commands to the Alexa devices work fine (I tried an ad), but I can no longer control the various devices.
What can I check and check?

**Expected behavior**  
obviously I would like to verify and change the state of the Alexa devices

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <3.11.2>
 - JS-Controller version: <4.0.23> 
 - Node version: <v16.16.0> 
 - Operating system: <Raspy Debian OR Doker version on Synology>

**Comment by Apollon77** [comment]
see #920 which is pinned to hopefully have attention ;-)
