### ISSUE TITLE
Unknown Device

### ISSUE THREAD

**Issue by DrBakterius** [Apollon77/ioBroker.alexa2#923]
`Device-type:A1NQ0LXWBGVQS9 - Samsung QLED TV (2021 Samsung QLED TV) (2021 Samsung QLED TV) (2021 Samsung QLED TV) (2021 Samsung QLED TV) (2021 Samsung QLED TV) (DEREGISTER_DEVICE,AUDIO_PLAYER,SLEEP,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,GOLDFISH,MUSIC_SKILL,AUDIBLE,SPEECH_RECOGNIZER_USS,SOUND_SETTINGS,ASCENDING_ALARM_VOLUME,TIMERS_AND_ALARMS,SUPPORTS_LOCALE,CHANGE_NAME,DEEZER,CUSTOM_ALARM_TONE,SET_TIME_ZONE,TUNE_IN,AMAZON_MUSIC,SIRIUSXM,EARCONS,PERSISTENT_CONNECTION,TIDAL,APPLE_MUSIC,SET_LOCALE,DIALOG_INTERFACE_VERSION,REMINDERS,MICROPHONE,TOUCH_INITIATED,MULTI_WAKEWORDS_SUPPORTED,I_HEART_RADIO,VOLUME_SETTING,DREAM_TRAINING,HANDS_FREE,ADAPTIVE_LISTENING,SUPPORTS_LOCALE_SWITCH,KINDLE_BOOKS)`

It's a "Samsung The Frame QE50LS03A" and commands are working.

**Comment by Apollon77** [comment]
Will be included in next version
