### ISSUE TITLE
Settings für Equalizer 

### ISSUE THREAD

**Issue by padrino-x** [Apollon77/ioBroker.alexa2#924]
Nachts sind die Echos mir selbst ganz leise zu laut, da hilft etwas, wenn man Bass und Mitten raus nimmt.
Wäre es möglich, dass man den Equalizer pro Gerät, wie in der App, einstellen könnte?
Dann könnte man das automatisieren? :D

**Comment by Apollon77** [comment]
ALready working on it ... will come with next version

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/56437/alexa2-adapter-3-18-x-beta
