### ISSUE TITLE
Rückmeldung einer korrekten Anfrage

### ISSUE THREAD

**Issue by BenAhrdt** [Apollon77/ioBroker.alexa2#925]
Wenn man Alexa etwas fragt / sagt, was nicht als routine hinterlegt ist, so antwortet sie entweder darauf, oder kann damit nichts anfangen.
Trotzdem kann man ja in der summary entsprechend auf den text reagieren.
Idee: Kann man Alexa irgendwie zurück melden, dass der text ok ist und verarbeitet wird (wie eine routine)?

Somit könnte man routinen innerhalb eines skriptes selbst bestätigen und verwalten. (und flexibler reagieren)

Eventuell bietet amazon ja hier ein flag? (wahrscheinlich leider nicht)

**Comment by Apollon77** [comment]
Nein. Optionen sind routinen, bei denen man die reaktion definieren kann (zb nur "wait 1s") oder der custom skill

**Comment by BenAhrdt** [comment]
OK, aber bei einer Routine wird es schwierig bspw. eine % Angabe mit ein zu bauen ;-)
was ist der custom skill?
Auf seiten von alexa, oder dem Adapter?

**Comment by Apollon77** [comment]
https://forum.iobroker.net/topic/56304/wie-spricht-man-mit-iobroker-iobroker-custom-skill-2022
