### ISSUE TITLE
3.81 again problem...

### ISSUE THREAD

**Issue by mactwin** [Apollon77/ioBroker.alexa2#926]
having seen the other post closed and the indications regarding the new 3.18.1 I proceeded to install, I do not speak German so I am forced to write here.

Initially I had a problem where after installation I could not find the instance to configure.
I uninstalled, reinstalled the old version with bugs, and installed over the new 3.18.1.
Now from the adapters screen 3.18.1 is installed, and there is the instance to be configured with the various parameters (cookies etc).

It seemed to me that you can only include items with a parameter (#includeInIntervalQuery state) which I didn't understand where to insert.

I hope I haven't asked any silly questions and thank you as always for the support.

-----

solved...
no dependency is created, and after a search I have found the command (with terminal)

iobroker add iobroker.alexa2

**Comment by Apollon77** [comment]
Then you installed from Github ... and yes then no instance is created automatically ... but you do not need GitHub installs ... just use normal Admin ... and then you also have a "+" button on "Adapter"
