### ISSUE TITLE
Homematic IP Access Point via Alexa2. nur Einwegkommunikation

### ISSUE THREAD

**Issue by anrada73** [Apollon77/ioBroker.alexa2#93]
Hallo, erstmal Danke super Script.
Lediglich die Push Aktualisierung läuft nicht. Also manuell geschaltete Zustände werden nicht übertragen, weder Push noch die manuelle Abfrage alle 15 Sekunden funktioniert. Also Alexa2 kann die HMIP Zustände nicht auswerten. nur Einwegkommunikation. Kann man es ändern? 
pi@ioBroker-RasPi:~ $ node -v
v8.11.1
https://www.facebook.com/groups/HomematicIP/permalink/234842630523266/

**Comment by Apollon77** [comment]
Abfrage alle 15s? Was tust du da?
Was genau fragst du alle 15s alles ab? QueryAll? Auch ioBroker skill aktiviert?

Ansonsten bitte debug einschalten beim Adapter und log EINER Abfrage von so einem Gerät senden. Oder vllt von 2 oder 3 mit verschiedenen wertetypen. 

Ob Abfrage implementiert ist hängt vom skill ab. Kannst alexa nach den Werten per stimmbefehl fragen und bekommst du einen korrekten Wert als Antwort?

**Comment by anrada73** [comment]
Das Licht ist AN, zeigt aber false, wenn ich auf false drücke, dann geht das Licht AUS, wenn true schreibe ,dann AN. wenn ich danach den Schaler LICHT manuel betätige, dann bleibt die Wert true, soll aber false sein. (Licht ist aber Aus)

**Comment by Apollon77** [comment]
Ich zitiere selbst den ersten Satz aus meinem letzten Post:
> Push geht nicht für SMart-Home-Device-Stati weil die nicht aktiv gemeldet werden.
Der Status in alexa2 wird also automatisch NIE dem echten Wert entsprechen. Geht immer nur wenn Du manuell auf query tust das du vllt den aktuellen Wert bekommst.

Und bitte nicht auf die Idee kommen alle Xs den Status abzufragen! Das mag Amazon definitiv nicht
