### ISSUE TITLE
"Add new Alarm" funktioniert nicht mehr

### ISSUE THREAD

**Issue by Jannis9595** [Apollon77/ioBroker.alexa2#932]
Hallo Zusammen,

ich habe schon seit einer Weile den "Add new Alarm"-Datenpunkt genutzt, um meine Wecker automatisch (je nach Schicht) zu stellen.
Dafür habe ich einen Steuer Logik block genutzt gefolgt vom Datenpunkt und einem Textbaustein in dem die Uhrzeit stand.
Das hat nun über 1 Jahr problemlos funktioniert, aber seit neustem werden die Wecker nicht mehr gestellt. Egal auf welcher Art und Weise ich den Datenpunkt anspreche oder eben direkt in der Objektliste, die Wecker werden nicht mehr übernommen.

Mache ich etwas falsch oder liegt hier ein Fehler vor?

Vielen Dank für eure tolle Arbeit!

Gruß Jannis

**Comment by Apollon77** [comment]
Welche Version? Beta 3.19 bzw 3.18 sollte problemlos tun. Stable 3.11 kann sein weil es Änderungen bei Amazon gab...

**Comment by Jannis9595** [comment]
3.18.6

**Comment by Apollon77** [comment]
Ok, was schreibst Du in den Datenpunkt rein? Bitte adapter auf debug log stellen. Warten bis er fertig ist und dann eine solche Aktion machen, dann auszug des Debug logs davon posten

**Comment by Jannis9595** [comment]
Habe vorhin mal noch auf 3.19.1 geupdated, dort besteht das Problem aber auch.
Ansteuerung sowie Log siehe Anhang.

![Schicht](https://user-images.githubusercontent.com/46874336/183112241-fda6e34d-37d6-4cf1-8fd5-fbdecb41037e.JPG)
[logs.txt](https://github.com/Apollon77/ioBroker.alexa2/files/9269969/logs.txt)

**Comment by Apollon77** [comment]
Das Problem ist das Du nur eine Uhrzeit setzt ... damit nimmt Amazon "den gleichen Tag" ... aber diese Zeit ist bereits abgelaufen. Deswegen gibt es den Fehler "Scheduled time cannot be in past".

Ich kann mal schauen ob ich das parsen kann und den nächsten tag setze

**Comment by Apollon77** [comment]
wird in 3.19.2 gefixt sein

**Comment by Jannis9595** [comment]
Habe gerade das Update durchgeführt, tausend dank, funktioniert perfekt. 
Vielen herzlichen Dank für deine unermüdliche Arbeit und die schnelle behebung des Problems!
