### ISSUE TITLE
Der textCommand "zeige Startbildschirm" (um den Bildschirm dann bspw morgens wieder einzuschalten) funktioniert leider nicht

### ISSUE THREAD

**Issue by MichaelSchaaf999** [Apollon77/ioBroker.alexa2#934]
Nochmal ich hier, sorry.

Im LiesMich zu dem Adapter steht dies:
![grafik](https://user-images.githubusercontent.com/53481090/185191817-efcf42a8-b225-4604-97c4-4160c297f159.png)

Aber das ist nicht mehr ganz aktuell, oder?

Der textCommand "Display aus" funktioniert nämlich einwandfrei.

Der textCommand "zeige Startbildschirm" (um den Bildschirm dann bspw morgens wieder einzuschalten) funktioniert leider nicht:

State changed alexa2.0.History.json: {"val":"{"name":"WoZi Echo Show 8 2nd Gen","serialNumber":"G091GM07123303XX","summary":"zeige startbildschirm","creationTime":1660316207031,"domainApplicationId":"","domainApplicationName":"","cardContent":"","card":"","answerText":"Da bin ich mir leider nicht sicher.","utteranceType":"ROUTINES_OR_TAP_TO_ALEXA","domain":"Knowledge","intent":"QAIntent"}","ack":true,"ts":1660316208636,"q":0,"from":"system.adapter.alexa2.0","user":"system.user.admin","lc":1660316208636}

Ich vermute mal stark, dass das kein Adapter-Issue ist: Aber was kann man tun, via textCommand, um den Bildschirm wieder einzuschalten? Wenn ich in das Device "Echo" reinbrülle, dann geht der Bildschirm ordnungsgemäß an.
Wenn ich dies Schlüsselwort "Echo" in das Objekt textCommand einstelle, dann kommt die o.a. Meldung "Da bin ich mir leider nicht sicher".

Mache ich etwas falsch?

LG
Michael

**Comment by Apollon77** [comment]
Keine AHnung was das für eine veraltete Reame ist ... die auf GitHub ist aktuell und sagt nichts von USA. Ja das tut, aber wie man bildschirm gemau einschaltet -> ist besser ein Forum Thema. Suuch dort mal ... Ein Adapter Issue ists in keinem Fall weil der Adapter den text an Amazon weitergibt ... abert das Problem ist das das Gerät von dem der Befehl kommt (der Adapter) keinen Bildschirm hat! Wenn du mit dem Gerät mit dem Bildschirm redest geht natürlich der Bildschirm des geräts an. Wenn Du das über den Adapter tust sagt Amazon "nix Bildschirm, geh weg" ...
