### ISSUE TITLE
Gerätebenarichtigungen im DP anzeigen

### ISSUE THREAD

**Issue by Hant0r** [Apollon77/ioBroker.alexa2#935]
Wenn Amazon, eine Skill oder wer auch immer einen eine Benachrichtigung schickt, wird dies ja mittels eines gelben Rings angezeigt.
In der App habe ich gesehen, dass dort dann "1 neue Gerätebenachrichtigungen" angezeigt wird.

Könnte man diese "Benachrichtigung" bzw den Hinweis dazu auch über alexa2 abrufen/einsehen?
Dann könnte ich automatisiert, z. B. bei Bewegung im Raum, die Benachrichtungen von der Alexa vorlesen lassen, ohne immer "Alexa, was sind meine Benachrichtigungen?" sagen zu müssen.

Gruß

**Comment by Apollon77** [comment]
geht nur per "polling" .. also wäre nicht echtzeit

**Comment by Hant0r** [comment]
Besser als nichts. 
Dann könnte man als Beispiel bei Bewegung abfragen, ob es was gibt und wenn ja abspielen lassen. 
Oder alle 5 min abfragen...

**Comment by Apollon77** [comment]
Es hat sich leider nichts geändert das das maximal per polling verfügbar wäre - und mit den aktuellen rate limit themen u.ä. würde ich gern global davon absehen.
Daher mache ich hier zu. Alternative ist Routine die darauf reagiert und ein iot gerät schaltet ... das kommt dann per iot Adapter als virtuelles gerät ...
