### ISSUE TITLE
Beliebiges Dautm per Sprachausgabe übermitteln

### ISSUE THREAD

**Issue by Wernercus** [Apollon77/ioBroker.alexa2#936]
Ich möchte gerne ein Datum per Sprachausgabe über Alexa ausgeben lassen. Das funktioniert auch soweit, allerdings wandelt er den ersten Punkt vom Datum in ein Komma um. Das sorgt natürlich dafür, die Sprachausgabe des Datums nicht optimal ist. Hier die Codezeile:

 setState("alexa2.0.Echo-Devices."+ getState("alexa2.0.History.serialNumber").val +".Commands.speak"/*speak*/, ('50;Der nächste Termin ist am 28.05.2022'));

Version: v3.11.2

**Comment by Apollon77** [comment]
Nicht "er" wandelt das um ... sondern Amazon spricht es so ... Finde entweder heraus wie der text aussehen muss oder nimm den ssml State und schau wie du in ssml es so angebeb kannst das es rauskommt wie Du es brauchst.
