### ISSUE TITLE
Player.currentState keine push-Aktualisierung

### ISSUE THREAD

**Issue by gemsli** [Apollon77/ioBroker.alexa2#942]
Die Werte für

Echo-Devices.*.Player.currentState

werden bei aktivierter Push-Verbindung nicht (mehr) auf false geändert, wenn das Gerät keine Medien mehr abspielt. Aktualisierung auf true funktioniert hingegen. Eine Aktualisierung scheint es erst  nach ca. 60 Minuten stattzufinden wohl wegen

"Wenn die Push-Connection festgestellt wird, wird das Update-Intervall auf 60 Minuten eingestellt, wenn es aktiviert ist."

**Comment by Apollon77** [comment]
Ja, scheinbar hat Amazon etwas kaputt gemacht. Funktioniert bei dir die Audio steuerung und Status-anzeige in der Alexa App korrekt? Bei mir nicht ... Aktuell gehen wir von einem Bug bei Amazon aus und erwarten das die das wieder fixen ... Vo daher werde ich noch warten bevor ich Aufwand investiere

**Comment by gemsli** [comment]
Statusanzeige in der App ist korrekt und synchronisiert sofort.

**Comment by tchristian1103** [comment]
Bei mir funktioniert aktuell weder die Steuerung noch die Anzeige in der App korrekt.

Die Player die (über ioBroker) gestartet werden stoppen nicht mehr, auch nicht manuell über die App.
"Anhalten nicht möglich. Bitte versuche es später erneut".
 Hier hilft aktuell nur Lautstärke runterdrehen. Ich tippe auch auf einen größeren Bug bei Amazon.

**Comment by Apollon77** [comment]
Please check GitHub version. I implemented a workaround. Report here or in https://forum.iobroker.net/topic/57725/alexa2-echo-currentstate

**Comment by Apollon77** [comment]
fixed in 3.19.9

**Comment by Apollon77** [comment]
It also seems that Amazon fixed something ... could be worth a retest
