### ISSUE TITLE
Abspielen über Tunein-Station funktioniert nicht mehr

### ISSUE THREAD

**Issue by derdaene** [Apollon77/ioBroker.alexa2#943]
Seit etwa einer Woche funktioniert das Abspielen über die Tunein-Station ID nicht mehr. Ebenso spielt die Musik nach Ende der Aktion einfach weiter. Also „Conrolpause“ wird nicht (immer) übermittelt.
Am Script habe ich nichts geändert. Ist das Problem bekannt und gibt es bereits eine Lösung?

**Comment by Apollon77** [comment]
duplicate #942 ... wit nehmen Amazon Bug an, da auch die Alexa App und Sprache betroffen ist
