### ISSUE TITLE
Error Meldung Datatype

### ISSUE THREAD

**Issue by Instanz1** [Apollon77/ioBroker.alexa2#944]
Hallo

ich lasse über den Device Reminder eine Alexa benachrichtung sagen wenn die Waschmaschine gestartet oder beendet wird.

Sobald aber die Sprache kommt erhalte im Log folgende Meldung:

Datatype for Echo-Devices.G0911B0594820X91.Commands.speak-volume differs from expected, ignore state change! Please write correct datatype (number)

Liegt es am Adapter oder am Device Reminder?

Gruß

**Comment by Apollon77** [comment]
> Device Reminder!
