### ISSUE TITLE
<voice> SSML tag for announcements is ignored

### ISSUE THREAD

**Issue by Kaldesh84** [Apollon77/ioBroker.alexa2#945]
When I try to use a different voice in "Commands.announcement", this seem to be ignored.
Other SSML tags seem to work properly.
Also, the voice change works for "Commands.speak".

Example :
`<speak><voice name='Vicki'>This is a test</voice></speak>`
-> will use the regular Alexa voice when put into "Commands.announcement"
-> will use the specified voice "Vicki" if put into "Commands.speak"

`<speak>This is a<amazon:effect name="whispered">test</amazon:effect></speak>`
-> will correctly whisper the word "test" for both "Commands.announcement" and "Commands.speak"

On the other hand:
if I use 
`<speak><voice name='Vicki'>This is a<amazon:effect name="whispered">test</amazon:effect></voice></speak>`
in "Commands.speak", the voice is used, but the word "test" is not whispered. But that seems to be connected to the "Vicki" voice itself. The whisper part works for other voices.

**Comment by Apollon77** [comment]
Hm ...enable Debug log for the instance please, do that sml state change, check that the message is correctly sent to amazon from the "SSML" ... and If this is the case (what I assume) then it is an AMazon effect that it is not working ... We just send the data over to them ... what they do we have no control over, sorry

**Comment by Apollon77** [comment]
No answer, closed
