### ISSUE TITLE
Instanz wird nicht aktualisiert

### ISSUE THREAD

**Issue by Siggi0904** [Apollon77/ioBroker.alexa2#946]
Hallo,
mein IOBroker zeigt unter Adapters an, dass ich die Version 3.19.9 schon hätte.
Gehe ich dann in die Instanzeinstellungen des Adapters wird mir 3.11.2 angezeigt.

Ist das richtig, kann ich das irgendwie korrigieren?

Danke.

Adapter:
![grafik](https://user-images.githubusercontent.com/4992106/191057343-228a1729-c0bb-43ca-8519-90ac3e4a01ea.png)

Instanz:
![grafik](https://user-images.githubusercontent.com/4992106/191057487-aac3e3aa-db80-4f41-a524-0c43a1350eca.png)

**Comment by Apollon77** [comment]
Hast Du vllt mehrere Hosts? Dann bitte im Admin unter ADapter den korrekten Host oben wählen. Stimmt das die Version?
SOnst auf dem Host einmalig "iob upload alexa2" ausführen

**Comment by Apollon77** [comment]
Gute rage ... da müsste man jetzt mal das Logfile in /opt/iobroker/log/... raussuchen wo das update drin ist
