### ISSUE TITLE
clearOwnMessages is not working

### ISSUE THREAD

**Issue by ChristopherGier** [Apollon77/ioBroker.alexa2#948]
When pressing clearOwnMessages nothing happens. The message is still on unread and can be played via alexa.

**To Reproduce**  
1. Go to '(Contacts.? (self))'
2. Click on '#clearOwnMessages'
3. See nothing happens

**Expected behavior**  
Messages should be deleted

**Versions:**  
 - Adapter version: v3.19.9
 - JS-Controller version: 4.0.23
 - Node version: v16.17.0

**Comment by ChristopherGier** [comment]
Minor addition: In 'info' logging mode nothing appears. In 'silly' mode its concluding with:
Alexa-Remote: Response: {"status":404,"message":"Something went wrong"}

**Comment by Apollon77** [comment]
Hm ... I can not find the function in the Alexa App anymore ... you? If yes, where?
If no,  I will remove it from the adapter

**Comment by ChristopherGier** [comment]
Not sure if it's the correct function: but if you swipe the chat to the left, a remove action is triggered in my app. Is that the same that should be triggered with the clearOwnMessages?
For me it would absolutely solve the issue, deleting the messages without reading them out loud :)

**Comment by Apollon77** [comment]
Where you can swipe?

**Comment by ChristopherGier** [comment]
On the communication screen - this is also possible for all open chats
![Screenshot_20221030-171733](https://user-images.githubusercontent.com/37614209/198889570-e73990f3-a902-4c50-930f-97fa9f2c64fb.jpg)

**Comment by Apollon77** [comment]
Aaah da ... ja genau das sollte an sich der Adapter tun. Checke

**Comment by ChristopherGier** [comment]
Super, danke! :)

**Comment by Apollon77** [comment]
Bitte GitHub version versuchen und Feedback geben

**Comment by ChristopherGier** [comment]
Funktioniert!
