### ISSUE TITLE
Echo Ultraschall Bewegungserfassung

### ISSUE THREAD

**Issue by Rushmed** [Apollon77/ioBroker.alexa2#949]
Hallo,

habegerade festgestellt dass mein Echo 4G folgendes Menü für Bewegungserfassung hat:
![Screenshot_20220923-190820_Amazon Alexa](https://user-images.githubusercontent.com/59259796/192017118-653ffe9e-4e7c-4c89-9688-0e09fb575c1a.png)
Das funktioniert soweit auch per Routine.

Leider finde ich keinen Datenpunkt im Adapter der den Erkennungssstatus meldet. Übersehe ich etwas oder besteht die Möglichkeit den hinzuzufügen?

**Comment by Apollon77** [comment]
Solche Dinge können nicht erkannt werden weil es keine Push meldungen dafür gibt und damit kann man nur pollen und dann ists längst vorbei.

Workaround: Routine anlegen die einen eigenen State via iot steuert wenn es triggert

**Comment by Rushmed** [comment]
Ok, danke.
