### ISSUE TITLE
Das Ende einer Alexa Sprachausgabe triggern

### ISSUE THREAD

**Issue by stefan230561** [Apollon77/ioBroker.alexa2#950]
gibt es eine Möglichkeit das Ende eines variablen Text den Alexa ausspricht per Blockly Script zu triggern?
Beispiel: Ich möchte mir das Wetter von Wetter.com ansagen lassen und im Anschluss daran die Werte meiner Wettersensoren ansagen lassen.
Da aber der Text von Wetter.com variabel ist und somit auch die Dauer der Ansage variabel ist muss ich wissen, wann die Ansage von Wetter.com zu Ende ist um dann die Ansage meiner Sensorwerte zu starten.

Es gibt aber auch noch andere Szenarien in denen es nützlich sein kann das Ende einer Alexa Sprachausgabe zu kennen.

**Comment by Apollon77** [comment]
Ja und nein... EInzige Möglichkeit ist über message (siehe https://github.com/Apollon77/ioBroker.alexa2#send-alexa-device-command-sequences-via-messages) eine sequenz an nachrichten sprechen zu lassen, dann regelt Amazon das "nacheinander". Um sowas mal zu machen am besten im Forum mal fragen
