### ISSUE TITLE
Alexa Routinen funktionieren sehr verzögert bis gar nicht ..

### ISSUE THREAD

**Issue by GameWatchProjects** [Apollon77/ioBroker.alexa2#951]
Alexa Routinen, welche in Kombination mit Java/Blockly bisher problemlos funktionierten, reagieren seit dem letzten Update extrem verzögert bis gar nicht mehr.

Beispiel: Habe eine Routine, welche bei der Frage, welche Fenster geöffnet sind, über Blockly geprüft hat, welche Fenetserkontakte geöffnet sind und hat diese dann über Alexa zurück gegeben. Aktuell kommt die Antwort viele Minuten später oder gar nicht mehr.

Dieses Phänomen konnte ich bisher nur bei den Routinen feststellen, alles andere (Gerätesteuerung über Alexa) funktioniert einwandfrei.

**Comment by Apollon77** [comment]
GGf bitte rüfen das die "Push connection" Verbunden ist und keine Fehler im Log stehen, weil sonst kommt halt nichts an. Gggf versuchen neu zu starten nach kurzer wartezeit.

Sonst bitte Loglevel auf Debug stellen und nachstellen und dann davon mit Zeitangaben bitte Log bereitstellen. Und log mit anganbe dieses Issues per email an iobroker@fischer-ka.de
