### ISSUE TITLE
Alexa Shoppingliste wird nicht aktualisiert, oder erst sehr spät

### ISSUE THREAD

**Issue by MiRo1310** [Apollon77/ioBroker.alexa2#952]
Ich habe es in der App verglichen, dort wird es aktualisiert nur im Adapter nicht. Nach Neustart werden auch da der Datenpunkt aktualisiert.

**Comment by Apollon77** [comment]
Wurde gestern im Forum bereist diskutiert. Scheinbar liefert Amazon aktuell nicht alle Pubsh-Infos oder stark verzögert oder manchmal gar nicht und dann mit einer zweiten Änderung zusammen später. Amazon-Issue
