### ISSUE TITLE
Status der Datenpunkte in Alexa-App nicht sichtbar

### ISSUE THREAD

**Issue by Siggi0904** [Apollon77/ioBroker.alexa2#953]
Hallo,

in den Release Informationen und in dem geschlossenen Bug https://github.com/Apollon77/ioBroker.alexa2/issues/816 hattest du geschrieben, dass die App bzw. Alexa jetzt den aktuellen Status der Variablen nachgeführt bzw. in der App angezeigt werden.

Leider sehe ich bei allen Datenpunkten aus dem IOT Adapter in der Alexa App ohne aktuellen Status.
Weder bei boolschen Variablen, noch bei den real Variablen.

Muss ich im IOBroker (Alexa2-Adapter, IOT-Adapter etc.) noch zusätzlich etwas einstellen, dass die Daten in der Alexa-App aktualisiert werden? Muss ggf. an den Datenpunkten in den RAW-Daten etwas ergänzt werden?

Danke im Voraus.

**Comment by Apollon77** [comment]
Der aktuelle ioboroker iot Skill unterstützt das nicht. Update kommt.Issue dafür im iot Repo ist offen. Kein Alexs2 Thema
