### ISSUE TITLE
Error while checking Authentication: Error: 401 Unauthorized

### ISSUE THREAD

**Issue by pzystorm** [Apollon77/ioBroker.alexa2#959]
**Describe the bug**  
The alexa2 adapter is not willing to work. On the settings page of the fresh installed adapter I click on the link to get forwarded to Amazon to get the cookie. I login and enter my 2nd factor auth. After this, the cookie is retreived by the adapter and can be seen in the second tab "cookie" of the alexa2 adapter in iobroker. But if I then start the adapter, the adapter always switches to red. If I look at the settings, it looks like this:
![grafik](https://user-images.githubusercontent.com/765650/193458798-4dcdc3bc-d41b-4d0f-b9e7-590c272df6a2.png)

For a very short moment I have two green ticks:
![grafik](https://user-images.githubusercontent.com/765650/193458853-1725018b-c476-4e4b-9189-5714cd01dcfe.png)
But then all three immediately change to red.

The debug logs looks like this:
![grafik](https://user-images.githubusercontent.com/765650/193458902-e2b9ebf6-bd1e-4485-88d1-28b0db943bd1.png)

I don't know why there is an "unauthorized" error message, as my login to Amazon was succesful and afterwards it stated that the cookie could be read and I can close the window.

**To Reproduce**  
1. Install alexa2 adapter in iobroker.
2. Follow the link to Amazon, enter credentials and 2nd factor
3. Close Amazon window, go back to alexa2 adapter. click save & close.
4. Start the adapter.

**Expected behavior**  
The alexa2 instance should go to green state, not red state.

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: v3.19.9
 - JS-Controller version: 4.0.23
 - Node version: v14.20.1
 - Operating system: Synology DSM 6 --> Docker version 18.09.8, build bfed4f5 --> iobroker/iobroker:latest Image

**Comment by Apollon77** [comment]
It is a german amazon account or from any other region?

**Comment by pzystorm** [comment]
Yes, German Amazon account. But does this matter?
I can login with my German Amazon Account also to amazon.co.uk or amazon.com

**Comment by Apollon77** [comment]
>  I can login with my German Amazon Account also to amazon.co.uk or amazon.com

Yes, but there are also other eregions (US is one of them) where APIcalls need to use different domains. But ok when not relevant for you.

Please enable debug logging of the alexa2 instance and get the cookies again via the proxy and send me the fiull debug log from this from disk at /opt/iobroker/log/... with reference to this issue to iobroker@fischer-ka.de 

You are the first that report this error right now, so no idea what happens there in your case

**Comment by Apollon77** [comment]
No response ... close

**Comment by pzystorm** [comment]
Sorry. I was extremely busy these weeks and had no time for iobroker.

But, there are good news:
I dont know why, but it seems that my alexa account is connected to the UK. I realised this, after I called alexa.amazon.de in the browser and after the login getting forwarded to https://alexa.amazon.co.uk

So these settings are working now and the adapter is green:
![grafik](https://user-images.githubusercontent.com/765650/211439488-8b3b29fd-188d-4a86-8cdf-346650ce4e35.png)

**Comment by Apollon77** [comment]
This is great news, Is also the "push connection" working for you?

**Comment by pzystorm** [comment]
The push connection checkbox is ticked. But - i dont know if its working. How can I check that?
At least I can control my Alexa and let it talk something via the functions:
https://github.com/Apollon77/ioBroker.alexa2/blob/master/README.md#alexa20echo-devicesserialnumbercommands
and all other objects are read and can be seen in the iobroker gui.

**Comment by Apollon77** [comment]
If oush works and you interact with a device you will see a hostory entry "kind of immediately" (1-2s later) ... and the logfile should not contain  errors
