### ISSUE TITLE
two-factor authentication

### ISSUE THREAD

**Issue by daniel-lo** [Apollon77/ioBroker.alexa2#96]
Hallo, dass mit dem ablaufenden Cookie ist anstrengend .. kann ich mich irgendiwe anders - mit 2-factor - anmelden? VG

**Comment by arteck** [comment]
kurz und knapp NEIN

**Comment by daniel-lo** [comment]
danke .. und schade

**Comment by Apollon77** [comment]
Am besten 2fa ausschalten. Oder für alexa einen anderen Amazon Account nutzen wo das aus ist. 

Sorry. Selbst wenn man einen Weg finden würde zu erkennen wenn er den Code haben will so ist das „irgendwann“ und dann ist Dienstage wann man online muss und ob es nicht am Ende aufs gleiche rauskommt.

**Comment by daniel-lo** [comment]
2fa ausschalten oder ein zweiter Amazon Account ist für mich leider keine Option. Nett wäre es, wenn man proaktiv auf ein Cookie-Ablauf hingewiesen werden könnte .. damit man es nicht erst bemert (und ggf. lange rumsucht) wenn was nicht funktioniert.

**Comment by daniel-lo** [comment]
danke .. dann strick ich mir mal einen reminder :-)

**Comment by daniel-lo** [comment]
Ich muss nochmal bohren .. die 2-Faktor abzuschalten .. also mein Konto unsicherer zu machen, um Smart-Home zu betreiben finde ich noch immer unsympathisch. <brainstorming>Bluefox greift doch mit seinem Skill-Token auch dauerhaft auf Alexa zu. Kann sich dieser Adapter nicht irgendiwe an den Token dranhängen .. oder kann Bluefox nicht einen zweiten für diesen Adapter bereit stellen? </brainstorming>

**Comment by daniel-lo** [comment]
Du schaffst es auch in einer ;-)

Freut mich, dass es eine potenzielle Lösung gibt!!!
