### ISSUE TITLE
Support for Amazon air quality sensor (Luftgütesensor)

### ISSUE THREAD

**Issue by cactus-online** [Apollon77/ioBroker.alexa2#960]
I am using the new air quality sensor from Amazon. However, it is not listed as an Echo device or as an IoT device in the object tree. It would be nice if this device could be supported as well.

**Comment by Apollon77** [comment]
Do you have restarted the adapter? New devices are just added on start

**Comment by cactus-online** [comment]
Nope, but now. Now the air quality sensor is listed at tree Smart-Home-Devices. But value is allways (null)

11-toggleState (null)
4-rangeValue (null) %
5-rangeValue (null) 
6-rangeValue (null) µg/m³ 
7-rangeValue (null) 
8-rangeValue (null) ppm
9-rangeValue (null)

**Comment by Apollon77** [comment]
Did you set the state on the device that data are also queried and do you use a "smart home device polling interval"?

**Comment by cactus-online** [comment]
I'm not 100% sure what you mean.

This for a device value?

```
common": {
    "name": "6-rangeValue",
    "type": "number",
    "read": true,
    "write": true,
    "role": "level",
    "min": 0,
    "max": 500,
    "step": 1,
    "unit"
```

Or this for the adapter?

```
  "native": {
    "usePushConnection": true,
    "historyIgnoreEmptySummary": false,
    "synchronizeSmartHomeDevices": true,
    "synchronizeLists": true,
    "includeAppDevices": false,
    "updateStateInterval": 300,
    "updateHistoryInterval": 300,
    "updateSmartHomeDevicesInterval": 300,
    "updateConfigurationInterval": 3600,
    "resetCookies": false,
    "cookie": "session-id=<removed>; session-id-time=<removed>; ubid-acbde=<removed>; x-acbde=<removed>; at-acbde=<removed>; sess-at-acbde=>removed>; csrf=<removed>",
    "alexaServiceHost": "",
    "userAgent": "",
    "acceptLanguage": "",
    "cookieLoginUrl": "",
    "proxyOwnIp": "<removed>",
    "proxyPort": 0,
    "proxyListenBind": "0.0.0.0",
    "proxyOverrideIp": ""
  }
```

**Comment by Apollon77** [comment]
And #includeInIntervalQuery is set to true on that "device"??

**Comment by cactus-online** [comment]
Like this ?

alexa2.0.Smart-Home-Devices.36f37b01-1150-41c1-a12a-xxxxxxd80939


{
  "type": "channel",
  "#includeInIntervalQuery": true,
  "common": {
    "name": "Luftqualitätsmonitor",
    "role": "channel",
    "read": true,
    "write": false
  },
  "native": {
    "friendlyDescription": "Amazon Indoor Air Quality Monitor",
    "friendlyName": "Luftqualitätsmonitor",
    "modelName": "",
    "additionalApplianceIds": null,
    "object": "AAA_SonarCloudService_00QARAjy4rXp8HDR3bq4_w7yGa1CwBICX2UXZO1m1XPxxxxxxxxxTYFgiiAIM_aLs4ib8fybtbRtGRyvKFSBU5",
    "manufacturerName": "Amazon"
  },
  "_id": "alexa2.0.Smart-Home-Devices.36f37b01-1150-41c1-a12a-xxxxxxd80939",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1664961657463
}

**Comment by Apollon77** [comment]
You think wax to complex just open "Object" in admin and in the "folder" of that air quality device there is one state called that way

![Bildschirmfoto 2022-10-05 um 11 48 48](https://user-images.githubusercontent.com/11976694/194032392-c72b2776-0881-444b-bdd9-b9de4c7cb8d5.png)

**Comment by Apollon77** [comment]
(false in my casde in that examople. set to true

**Comment by cactus-online** [comment]
OK. thank you. These objects occurred, after I created a new_state object (which I can't delete anymore). Has #query to be set to true also ?

**Comment by Apollon77** [comment]
With #query you initiate ONE manual query of the data, so set to true and one time will be updated

**Comment by cactus-online** [comment]
OK, except temperature (Amazon issue), now all values updated. Thank you very much for the adapter and the great support.
