### ISSUE TITLE
TextCommand defekt

### ISSUE THREAD

**Issue by holofury** [Apollon77/ioBroker.alexa2#961]
Moin,

seit ein paar Tagen funktioniert der Datenpunkt "textCommand" nicht mehr.

Der eingetragene Befehl taucht korrekt unter History auf, Alexa antwortet aber "Das weiß ich leider nicht".
Selbst eingesprochen funktioniert der Befehl ganz normal und auch in einer Routine als benutzerdefinierter Befehl funktioniert alles.

**Comment by Apollon77** [comment]
Adapter verwchselt!!
duplicate: https://github.com/ioBroker/ioBroker.iot/issues/472 ... ich habe noch kein Log erhalten.

**Comment by holofury** [comment]
Nein, nicht verwechselt!
Es geht um den Datenpunkt "alexa2.Echo-Devices.[device].Commands.textCommand".
Nicht um den iot / text2command Adapter.

**Comment by Apollon77** [comment]
Ok, sag mal einen beispielsatz bzw versuch mal alles klein zu schreiben und ohne satzzeichen. geht es dann wieder? Das wurde im Forum berichtet. Adapterfix kommt bald dafür

**Comment by Apollon77** [comment]
PS: bei mir geht es (egal ob gross oder klein oder satzzeichen) ... Mal Adapter neu gestartet?

**Comment by holofury** [comment]
"Spiel Radio Bob" - geht nicht.
"spiel radio bob" - geht tatsächlich - danke!

Adapter hab ich mal neu gestartet, klar.
Hab meine Scripte schon mal angepasst, aber schön, dass der Fix bald kommt.

**Comment by railin** [comment]
Kleinschreibung hat bei mir leider nichts gebracht.
Ich bleibe erst einmal auf der Version 1.11.19.

Danke für die Mühe.

**Comment by Apollon77** [comment]
1.11.19???? An textCommand hat sich seit ewigkeiten nichts geändert. Also Wenn da wa nicht geht liegt es entweder am Gerät oder an was anderem und muss man anders schauen

**Comment by s0n1c** [comment]
Ich muss/kann das Problem bestätigen. 

1. Groß und Kleinschreibung haben keinen Einfluss auf das Problem.
2. Adapter neu mit Alexa verknüpft, hat auch nicht geholfen.

Ich teste nun ein Downgrade…

**Comment by s0n1c** [comment]
Downgrades haben auch keinen Einfluss. Anscheinend hat sich etwas im Eingemachten von Amazon geändert.

**Comment by Apollon77** [comment]
Ok @s0n1c was GENAU versuchst du denn zu tun/steuern?

**Comment by s0n1c** [comment]
> Ok @s0n1c was GENAU versuchst du denn zu tun/steuern?

"alexa2.Echo-Devices.[device].Commands.textCommand"

**Comment by Apollon77** [comment]
Welchen Text versuchst du da reinzuschreiben??

**Comment by Apollon77** [comment]
Dann verifiziert bitte das wenn ihr das in der Alexa App eintippt anstelle sprecht ebenfalls nicht geht Bzw als routine ... und wenn das so ist -> Amazon support und meckern das DAS nicht geht (nix vom Adapter erzählen bitte).

**Comment by ThetaGamma** [comment]
OK, ausprobiert. Funktioniert sowohl als getipptes Kommando als auch als Routine in der Alexa App.
Mittlerweile hab ich es bei allen mir verfügbaren Gerätetypen ausprobiert (Echo, diverse Versionen vom Dot, Sonos) überall das gleiche Ergebnis.

**Comment by manuelwolfcgm** [comment]
Hab das gerade auch eben bei mir nachvollziehen können -> Alexa2 v3.19.9. Aufgefallen ist mir dass da was nicht (mehr) passt, weil einige Buttons meiner Visualisierung nicht mehr funktionieren (z.b. Echo-Devices - xxx - textCommand = Zeige Klingel). Das hat alles schon mal funktioniert, aber aktuell funktioniert "Zeige Klingel" nicht mehr, "zeige klingel" funktioniert tadellos. Unabhängig von der Vis auch testbar direkt im Datenpunkt (an mehreren Echo-Devices) mit 08/15 commans wie "Wieviel Uhr ist es" <> "wieviel uhr ist es" --> für mich keine große Sache, den befehl in der visualisierung anpassen, aber wie gesagt: irgendwas scheint sich schon verändert zu haben innerhalb der...keine ahnung...letzten wochen.

**Comment by Apollon77** [comment]
Von welchem Adapter sprichst du? Alexa2 ist aktuell in Version 3.19.9 (!!) 1.x sollte schon seit ewig gar nicht mehr tun - in jedem Fall hatte diese Version niemals textCommand. 3.19.9 ist die Version die tut ... bei mir und bei anderen

**Comment by funky4t** [comment]
Hi Apollon,
ich hab auch die Befürchtung dass der DP TextCommand derzeit nicht ganz sauber läuft. Kann dir leider nur beschreiben, wie es sich bei mir äußert.

Ich erzeuge per Zigbee Button an meinem Nachttisch ein Zufallsvariable und schreibe diese dann als Text in den TextCommand Datenpunkt meines Fire 8 Tablets. Der genaue Text im DP lautet dann `Spiele die 3 Fragezeichen Folge (erstellte Variable)`. Das lief jetzt bestimmt 1,5 Jahre super. Seit geraumer Zeit (ungefähr ne Woche oder zwei) wird bei diesem Befehl aber nicht mehr Amazon Music gestartet, sondern die Amazon Suche. In der Suche selbst findet sich exakt der obige Text in der Suchzeile.

Ich hab jetzt den Text geändert auf `spiele die 3 fragezeichen folge (Variable)`. Nun kommt auf dem Fire Tab statt der Amazon Websuche der akustische Hinweis: "Ich habe das auf Amazon Music nicht gefunden." In der Tat geht der Befehl mit der Kleinschreibung in die Richtung Amazon Music, aber leider ohne konkretes Ergebnis sprich die Folge wird nicht gefunden.

Starte ich das ganze per gesprochenem Befehl alla: "Alexa, spiele die 3 Fragezeichen Folge XY" läuft es reibungslos!

Ich hab auch mal in den TextCommand gezielt `spiele die 3 fragezeichen folge (Variable) auf amazon music` geschrieben, leider heißt es auch dann wieder "Ich habe das auf Amazon Music nicht gefunden."

Im Script selbst habe ich definitiv nix geändert. Ansonsten arbeite ich mit 3.19.9 aus dem stable...und hab am System die letzten 4 Wochen nix verändert. Adapter hab ich neu gestartet, Fire Tab ebenso...leider erfolglos.

Falls ich weitere Sachen testen soll, gib Bescheid, würd mich freuen, wenn ich helfen kann und sei es nur durch weitere Tests. Und wie immer 1000 Dank für die Entwicklung und den Support des Adapters! 👍🏼 
VG Sven

**Comment by Apollon77** [comment]
mal versucht die 3 also drei zu senden in textCommand?

**Comment by Apollon77** [comment]
ich kann am Ende nur sagen "ich mache alles lowercase" und in der Readme sage ich das man alles ausschreiben muss ... dasliegt bei euch. SOnst müsste ich ja in allen relevanten Sprachen sämtliches kennen und ersetzen (Folge einhundertsiebenundsiebzig) ... also ich würde gern sowas nicht einbauen :-)

Also für den "gesendeten content" sied schon Ihr verantwortlich :-)) Ich kann vllt nach gewissen bösen zeichen suchen und ggf was loggen ala "wenns nicht geht mach mal weg" aber auch das nervt ggf wieder wenns plötzlich doch geht

**Comment by funky4t** [comment]
> ich kann am Ende nur sagen "ich mache alles lowercase" und in der Readme sage ich das man alles ausschreiben muss ... dasliegt bei euch. SOnst müsste ich ja in allen relevanten Sprachen sämtliches kennen und ersetzen (Folge einhundertsiebenundsiebzig) ... also ich würde gern sowas nicht einbauen :-)
> 

mmmhhh.... grundsätzlich bin ich voll bei dir, was den Aufwand und die zuständige Seite betrifft. :) 
Bei den Zahlen hatte ich aber echt gehofft, dass da nen Bug zwischen Amazon und dem Adapter liegt. Letztendlich ist die Ziffer in den meisten Sprachen ja gleich, leichter zu verarbeiten und lief ja auch lange Zeit tiptop. 

Klar ist der Aufwand alle Zahlen (also mindestens 1x bis Unendlich ;) ) in allen Sprachen in den Adapter zu bringen keinesfalls dein Aufwand....aber warum Amazon in der API ewig Zahlen als Ziffer im Text akzeptiert und auf einmal nicht mehr, wird wahrscheinlich auch nur Amazon erklären können. :(

Ich google schon, ob es im Broker nicht eine Funktion/Blockly gibt, die Ziffer automatisch in Text zu wandeln. Bin da leider zu 99% eher Anwender. Was ich seltsam finde, ist dass Ziffern z.B. "30; Text" beim Speak Befehl ausgewertet werden und somit die Lautstärke variierbar ist, beim Textbefehl die API aber tatsächlich in zig Landessprachen ausgeschrieben verlangt wird. Auch irgendwie strange... Am Ende wird es ja für jeden der eine Variable reinschreiben will nen Mordsaufwand, da sind 217 Folgen angesichts von irgendwelchen anderen Werten mit Komma ja echt noch überschaubar... 😎😂

**Comment by Apollon77** [comment]
Wie kann es ein Bug sein wenn der Adapter nur den text zu Amazon sendet so als wenn du es in der Alexa App als routine angeben würdest? Ich kann nochmal schauen was die da tun, aber ich glaube du überschätzt hier was der adapter tun kann ...  Und wenn Amazon was ändert dann ändern Sie was, das ist nichts was in irgendeiner Forum "gesichert" wäre was wir hier tun ...

Bei Speak mit "30;text" ist was ganz anderes weil das was spezielles ist und hier der Adapter eh volume changes getrennt von texten verpacken muss weil das alles halt nicht so geht wie wir es auch convenience gründen haben :-).

**Comment by Apollon77** [comment]
I have one idea … let me try something. Will inform on updates.

**Comment by funky4t** [comment]
Moin, 
das mit dem Bug war nicht auf den Adapter bezogen sondern, wie du schon schreibst, auf eine mögliche Änderung auf Seiten Amazons. Sorry falls das falsch ankam. Ich bin in der Tat nicht im Bilde, wie der Adapter "unter der Haube" funktioniert. Sonst würde ich ja auch versuchen dir besser zu helfen 🙈 

Aber ich drücke alle verfügbaren Daumen, dass du noch eine Option oder Workaround zu dem Thema findest.🍀👍🏼

**Comment by ThetaGamma** [comment]
Believe it or not - seit heute morgen funktioniert es wieder („fenster timer auf 90 Sekunden“) und ich habe auf meiner Seite nix geändert. Ich würde sagen, der Verdacht erhärtet sich dass die Kollegen bei Amazon am rumschrauben sind?! Oder hat Appollon77s Idee von heute Nacht gefruchtet?

**Comment by Apollon77** [comment]
Meine Idee von heute nacht ... Da ich Die hatte kurz bevor bei mir die Augen zugegangen sind, vllt maximal als Strossgebet Richtung Amazon ;-)

**Comment by funky4t** [comment]
Ich bin noch unterwegs aber kann es heut Abend nochmal testen 🤞🏼 vielleicht wurde das Stoßgebet beim großen A ja erhört 😎🤣

**Comment by funky4t** [comment]
Alles läuft wieder reibungslos, sowohl die als Ziffer angegebene Nummer UND das lower case Thema ist bei mir auch behoben! @Apollon77 Kannst Du bitte schnell nen Stoßgebet senden, dass ich Freitag im Lotto gewinne? Dann füll ich schnell noch nen Schein aus 😂

**Comment by Apollon77** [comment]
*stoßgebeten* ... Kriege aber was ab wenns gewirkt hat *gg*

**Comment by funky4t** [comment]
@Apollon77 aber sicher! 👍🏼🍀✌🏼

**Comment by Apollon77** [comment]
@funky4t uund? ;-)))
