### ISSUE TITLE
Alexa-Push-Connection error: connection refused

### ISSUE THREAD

**Issue by sargonphin** [Apollon77/ioBroker.alexa2#962]
**Describe the bug**  
Multiples appearances in the logs of a certain connection refused error with Push connection.

![image](https://user-images.githubusercontent.com/85966195/195171748-1aa0424e-8baf-4882-bb6e-ad6a9b1bdb81.png)

I don't know where this is originating from. After a while, it stops. I don't know why it tries to connect to 0.0.0.0, maybe a config issue? I searched for a while and couldn't find anything relevant.

**To Reproduce**  
1. Install Alexa2 adapter & create an instane
2. Configure everything
3. See the error in the logs

**Expected behavior**  
No connection error

**Screenshots & Logfiles**  
See above

**Versions:**  
 - Adapter version: 3.19.9
 - JS-Controller version: 4.0.23
 - Node version: 16.17.1
 - Operating system: RaspberryOS on Compute Module 4

**Additional context**

**Comment by Apollon77** [comment]
Pihole or such in use? Something seems to do the DNS lookup incorrectly for an amazon domain and returns 0.0.0.0 whoch mostly is pihole or any other "DNS blocker "or such
