### ISSUE TITLE
Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted

### ISSUE THREAD

**Issue by iThieler** [Apollon77/ioBroker.alexa2#963]
Wie schon im Betreff erwähnt, wurde ich durch mein ioBroker Log angewiesen den nachfolgenden Text  hier zu posten mit Details zum Gerät. ;-)

Hier findest du das Gerät: https://www.amazon.de/xiaomi-f2-43-smart-fire-tv/dp/B09XXZZ3RW

Device-type:AHCEDGRIFN5RP - FireTVWohnen (DREAM_TRAINING,AMAZON_MUSIC,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,CUSTOM_ALARM_TONE,SUPPORTS_CONNECTED_HOME_ALL,ARTHUR_TARGET,SALMON,VOLUME_SETTING,I_HEART_RADIO,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,SUPPORTS_LOCALE,REMINDERS,AUDIO_PLAYER,ADAPTIVE_LISTENING,KINDLE_BOOKS,TAHOE_BYOD,EARCONS,FLASH_BRIEFING,AUDIO_CONTROLS,PANDORA,SET_LOCALE,TIMERS_AND_ALARMS,SPEECH_RECOGNIZER_USS,PERSISTENT_CONNECTION,AUDIBLE,MICROPHONE,REQUIRES_OOBE_FOR_SETUP,TIDAL,SIRIUSXM,SHARKNADO,CHANGE_NAME,EQUALIZER_CONTROLLER_MIDRANGE,SUPPORTS_LOCALE_SWITCH,DEEZER,MUSIC_SKILL,SLEEP,SUPPORTS_SOFTWARE_VERSION,APPLE_MUSIC,MULTI_WAKEWORDS_SUPPORTED,DIALOG_INTERFACE_VERSION,VOICE_TRAINING,ACTIVE_AFTER_FRO,TUNE_IN,ASCENDING_ALARM_VOLUME,SOUND_SETTINGS,TIMEZONE)

**Comment by shiot** [comment]
Falls für dich interessant, hier noch die URL zum Bild des Device:
https://m.media-amazon.com/images/G/01/digital/fiona/myx/anna.jpg

**Comment by Apollon77** [comment]
Die große Frage ist jetzt ... was kann das Teil denn? Gehen sprachausgaben? Wetterbericht? Alle diese "Commands"? oder gehen SIe nicht?

**Comment by iThieler** [comment]
Hi, habe jetzt alles durchgetestet. Ich würde sagen, Es funktioniert alles. Der TV reagiert auf alle Knöpfe unter Commands, FireTVCommands, Player (nur Musikwiedergabe).

- Alarm kann ein neuer angelegt werden
- die werte unter Info werden alle befüllt ausgegeben, nur bei deviceTypeString steht Unknown
- Music-Provider funktionieren auch alle

Im Prinzip ist die Software auf dem TV kein AndroidTV sondern FireTV in der Version 23656613252. Allerdings von Amazon etwas aufgebohrt. Man kann LiveTV steuern von den eingebauten DVB-S2 oder DVB-C Tuner.

Ich hoffe ich konnte weiterhelfen, wenn nicht, bin gerne weiterhin behilflich 😄

**Comment by Apollon77** [comment]
next version
