### ISSUE TITLE
Wiederherstellen der Lautstärke nach Text2Speech schlägt fehl bei Lautsprechergruppen

### ISSUE THREAD

**Issue by Marty56** [Apollon77/ioBroker.alexa2#966]
Ich habe meine Alexas Lautsprecher Lautsprechergruppen zugeordnet, die nach der Definition der Gruppen auch im Adapter als Datenpunkte auftauchen.

Wenn ich jetzt text2speech in den Lautsprechergruppen starte, wird korrekt der Text auf allen Alexas der Gruppe im Haus ausgegeben.
Leider wird danach nicht mehr die ursprüngliche Lautstärke wiederhergestellt, sondern es wird die Lautstärke der text2speech Ausgabe beibehalten.

**Comment by Apollon77** [comment]
Was genau ist denn "text2speech"? Den Datenpunkt gibt es nicht.
Wie wird die Lautstätke angegeben? Im text Spring oder über "speakVolume" bei den einzelnen Geräten?
Haben die betroffenene Geräte die nicht zurückgesetzt werden den korrekten Wert in "Player.volume" stehen?

**Comment by Marty56** [comment]
Mit "text2speech" meinte ich alexa2.0.Echo-Devices.xxxx.Commands.speak.
Ich kann den "speakVolume" Datenpunkt gar nicht angegeben, weil die (virtuellen) Lautsprechergruppen- Geräte diesen Datenpunkt nicht haben.
Wenn ich jetzt in einem Gruppen Device den  "Commands.speak" Datenpunkt setze, wird die Lautstärke lauter (mir ist unklar woher der Wert kommt), dann der gesprochene Text ausgegeben  und danach bleibt sie laut und stellt sich NICHT mehr auf den Wert ein, den sie vorher hatte.

Ich habe es jetzt einen Workarround implementiert, bei dem  ich keine Lautsprechergruppen mehr verwende, sondern die einzelne Alexa Lautsprecher nacheinander aufrufe. Bei den einzelnen Lautsprechern funktioniert das Wiederherstellen der Lautstärke ohne Probleme.

**Comment by Apollon77** [comment]
speakVolume existiert nur auf Ebene der Devices, weil ggf unterschiedliche Gerte unterschiedlich laut sein könnten.
Ist also bei den Geräten speakVolume gesetzt? Was steht bei den einzelnen Geräten bei "volume"?

**Comment by Marty56** [comment]
Ich habe es bei einem Gerät überprüft.
alexa2.0.Echo-Devices.G090LV03717501KP.Player.volume steht auf 70
alexa2.0.Echo-Devices.G090LV03717501KP.Commands.speak-volume 20

Die anderen Geräte habe auch gesetzte alexa2.0.Echo-Devices.G090LV03717501KP.Commands.speak-volume (s).

**Comment by Apollon77** [comment]
Ok, dann sollte dies an sich tun.

Bitte bei der Alexa2 Instanz das Loglevel auf Debug ändern und dann so ein Gruppen "Speak" machen und den Logausschnitt aus dem Logfile unter /opt/iobroker/log/... hier posten

**Comment by Apollon77** [comment]
Noch relevant? Hab bisher kein Log erhalten ...

**Comment by Marty56** [comment]
Oh, Entschuldigung. Aber ich bin derzeit unterwegs und komme frühestens am Dienstag dazu.
