### ISSUE TITLE
Unknown Device - Amazon Alexa Car Integration

### ISSUE THREAD

**Issue by RK62** [Apollon77/ioBroker.alexa2#967]
**Meldung im Log**
```
alexa2.0 (31907) starting. Version 3.19.9 in /opt/iobroker/node_modules/iobroker.alexa2, node: v14.19.3, js-controller: 4.0.23
alexa2.0 (31907) Unknown Device, but enabling commands, Try it and report back if commands work.
alexa2.0 (31907) Report to developer as GitHub issue with details for device. Please grab full next line pot. from logfile on disk if cutted
alexa2.0 (31907)     Device-type:A3BW5ZVFHRCQPO - Ralf's BMW Group – Amazon Alexa Car Integration (BMW Group – Amazon Alexa Car Integration) (KINDLE_BOOKS,GOLDFISH,DEEZER,TUNE_IN,SLEEP,MICROPHONE,MUSIC_SKILL,VOLUME_SETTING,HANDS_FREE,TIMERS_AND_ALARMS,ADAPTIVE_LISTENING,DREAM_TRAINING,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,DEREGISTER_DEVICE,APPLE_MUSIC,CHANGE_NAME,PEONY,I_HEART_RADIO,SIRIUSXM,TIDAL,REMINDERS,PERSISTENT_CONNECTION,AUDIO_PLAYER,AUDIBLE,AMAZON_MUSIC)

```
Anbindung mit dem Adapter funktioniert .

Gruß, Ralf

**Comment by Apollon77** [comment]
Funktionieren auch Commnds wie Sprachausgaben, Wetterbericht triggern oder so?

**Comment by RK62** [comment]
Läuft alles wunderbar, allerdings gibt Alexa keine Antwort bei der Verwendung von Alexa-Routinen und behauptet, sie hätte mich nicht verstanden. Bei meinen gebuchten Skills (Müll, Heizung, etc.) funktioniert das Antworten, genauso wie bei Alexa-Standard Diensten (Wetter, Sonnenaufgang, etc.). Die Alexa-Routinen werden zwar ausgeführt, aber es erfolgt keine Sprachausgabe. Bei der Verwendung auf meinem Mobilgerät geben die Alexa-Routinen ebenfalls ohne Probleme Antworten, über den BMW jedoch nicht. Habe das bei BMW mal als Frage eingekippt, scheint eher ein Problem auf deren Seite zu sein. Und Bilderanzeige vom Amazon-Konto wird nicht unterstützt.

**Comment by Apollon77** [comment]
Dann sag mal was die ANtwort ist. Es geht zu wenig um es offiziell im Adapter zu aktivieren, sonst erwarten User das zuviel geht
