### ISSUE TITLE
Smart-Home-Devices - nach update auf von 3.11.2 auf 3.19.9: Temperatursensoren zeigen keine Werte

### ISSUE THREAD

**Issue by einhinz** [Apollon77/ioBroker.alexa2#968]
Hallo,
nach dem Update von 3.11.2 auf 3.19.9 zeigen bei mir die Temperatursensoren, die direkt am Echo registriert sind keine werte mehr an, sondern nur enabled un delete. In der Alexa App geht noch alles.

**Comment by Apollon77** [comment]
Hm ... also in 3.11.2 waren da noch nie werte drin ... Was bedeutet "Temperatursenseoren die direkt am Echo registriert sind"? Die die im Gerät direkt drin sind?

Bitte mal screenshot der Objekte zeigen

**Comment by einhinz** [comment]
Mann kann ja z.B. exteren Sensoren, wei ein Zigbee-Sonoff oder Zigbee-Aquera Temperatursensor direkt am passenden Echo registrieren. Die sahen vor dem Update so auf wie im Screenshoot. Nach dem Update war nur noch "#delete" und "#eneabled" verfügbar. Während z.b. ein Temp-Sensor (WLan) über Smart-Live App auch weiterhin sichtabr ist und auch das neue "#includeInIntervalQuery" hat.
Ich hab jetzt mal wieder den 3.11.2 installiert und die Sensoren sind wieder da.
![grafik](https://user-images.githubusercontent.com/116629312/197779360-16ae1fb9-29b6-46c5-8373-7c1615e64b6b.png)

**Comment by einhinz** [comment]
Bzw hier das Objekt, jetzt in der Version 3.11.2
{
  "type": "channel",
  "common": {
    "name": "Second device",
    "role": "channel",
    "read": true,
    "write": false
  },
  "native": {
    "friendlyDescription": "TUYATEC-riuj5xzs intelligentes Gerät",
    "friendlyName": "Second device",
    "modelName": "",
    "additionalApplianceIds": null,
    "object": "AAA_SonarCloudService_60:A4:23:FF:FE:3C:DA:1C",
    "manufacturerName": "TUYATEC-riuj5xzs"
  },
  "from": "system.adapter.alexa2.0",
  "user": "system.user.admin",
  "ts": 1666689300410,
  "_id": "alexa2.0.Smart-Home-Devices.1ac7a958-353c-40c4-8c52-f2289ffaf3eb",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by Apollon77** [comment]
Dann bitte Instanz auf Debug Log stellen, dann starte adapter neu. Dannbitte komplettes Start Log (so lange warten bis alles durch ist mit initialisierung, kann länger dauern!) mit Referent auf dieses Ticket  an iobroker@fischer-ka.de senden. Muss ich mir auf der Datenebene ansehen

**Comment by Apollon77** [comment]
BTW_: Geht es mit 3.20? Falls ja lag es am rate Limit von Amazon, Falls nein bitte Log

**Comment by phillfoxi** [comment]
Hallo zusammen,

habe ein ähnliches Problem, nach dem update von 3.11.2 auf 3.19.9 werden meine Smart HOme geräte nicht mehr angezeigt.
Die rate liegt bei mir auf 600s.

![grafik](https://user-images.githubusercontent.com/116956515/198832111-d5a33ca9-a52f-49d9-923f-a5d1438bf67b.png)

**Comment by Apollon77** [comment]
-> 3.20.0

**Comment by einhinz** [comment]
Nein, die 3 Sensoren haben immer noch nur die beiden Einträge wir im Screenshot. Debug log mit der 3.20 hab ich dir geschickt.

**Comment by Apollon77** [comment]
@einhinz Bitte versuch mal die GitHub version. Geht es da jetzt?

**Comment by MosizZ** [comment]
Moin in die Runde,
ich habe das selbe Problem keine Geräte mehr in SmartHomeDevices Verzeichniss. Eben auf V.3.20.0 gewechselt und siehe da, alles wieder beim alten. Ware natürlich prikelt wenn das bald die Stable Version wird :D

**Comment by Apollon77** [comment]
Ja ganz langsam ... die version ist nicht mal einen halben Tag alt ...

**Comment by MosizZ** [comment]
Das soweiso :D ich bin froh das es wieder geht 👍  , da ist mir auch eine Beta recht. Danke dir und ich wollte dir damit nicht auf die Füße treten

**Comment by einhinz** [comment]
Hallo,
hab die GitHub Version installiert. 
Die drei Temperatur Sensoren gehen immer noch nicht. Haben nach wie vor nur  die Datenpunkte
#delete
#enabled
Der Temperatursensor im Echo plus geht übrigens.
Alle anderen SHDs scheinen auch zu gehen.
Hab dir das debug log geschickt.

**Comment by Apollon77** [comment]
Ahhh ... ok  hab noch eine Stelle übersehen ... Bitte nochmal von GitHub versuchen und auch wenn es klappt bitte einmal log senden. Danke

**Comment by einhinz** [comment]
Jetzt ist wieder alles da und die Werte lassen sich abfragen. Das debug log reich ich morgen nach

**Comment by Apollon77** [comment]
Danke!

**Comment by KronenbergSmarthome** [comment]
Hatte auch die 3.21.0 installiert und bei mir wurden auch keine SmartHomeDevices angezeigt. Der Log zeigte nur unter Info: No devices to discover. Habe danach 3.19.9 installiert, Problem existierte immer noch. Danach 3.20.0 installiert und alle SmartHomeDevices sind wieder vorhanden

**Comment by Apollon77** [comment]
Ja weil scheinbar das Rate limit manchmal passiert und manchmal nicht ... AM ENde ist aktuell die 3.21.0 am "besten" ... und "No devices to discover"? WAs genau tust du? "der Button "Discover devices" führt die Alexa Gerätesiuche aus ... das ist was gaaanz anderes!

**Comment by KronenbergSmarthome** [comment]
Hab die Stelle im Log doch gefunden.

2022-11-10 17:44:50.415  - [32minfo[39m: alexa2.0 (2988) No smart home devices to query

Hab dir die komplette Log mal angehangen

[Log 2022_11_10.xlsx](https://github.com/Apollon77/ioBroker.alexa2/files/9983525/Log.2022_11_10.xlsx)

**Comment by Apollon77** [comment]
Jupp, teilweise gabs bei dir rate limit fehler. Warum ist noch unklar.
Und "No smart home devices to quer" liegt daran das entweder keine geräte da sind oder bei keinen Geräten der tate gesetzt ist das das geröt bei "alles lesen" abzufragen ist

**Comment by KronenbergSmarthome** [comment]
> Jupp, teilweise gabs bei dir rate limit fehler. Warum ist noch unklar.
> Und "No smart home devices to quer" liegt daran das entweder keine geräte da sind oder bei keinen Geräten der tate gesetzt ist das das geröt bei "alles lesen" abzufragen ist

Ich habe mehr als genug Geräte bei Alexa und wenn ich die Version 3.20.0 benutze liest der Adapter auch alle Geräte ein und ich kann sie steuern usw. Aber wenn ich 21.0.0 benutze und die Objekte unter SHD so belasse kann ich sie nicht steuern. Wenn ich die Objekte lösche, werden sie auch nicht mehr neu eingelesen.

**Comment by Apollon77** [comment]
Dann bitte volles Debug log vom Start von am besten beiden versionen ink. einem versuch der steuerung an mich senden.

**Comment by KronenbergSmarthome** [comment]
Hier das log mit der Version mit der Ansteuerung eines Alexa Devices. Power On und Power Off
[iobroker.current.Alexa_20.0.0.log](https://github.com/Apollon77/ioBroker.alexa2/files/9995376/iobroker.current.Alexa_20.0.0.log)

Log für 21.0.0 folgt noch

**Comment by Apollon77** [comment]
Ok, im Log für die 3.20.0 sieht man das das Kommando generell geklappt hat aber amazon meldet:

> 2022-11-12 16:48:42.863  - [34mdebug[39m: alexa2.0 (851) Alexa-Remote: Sending Request with {"host":"eu-api-alexa.amazon.de","path":"/api/phoenix/state","method":"PUT","timeout":10000,"headers":{}}  and data={"controlRequests":[{"entityId":"517c9a46-68ae-427d-b4f9-d99e3078755b","entityType":"GROUP","parameters":{"action":"turnOn"}}]}
> 2022-11-12 16:48:44.710  - [34mdebug[39m: alexa2.0 (851) Alexa-Remote: Response: {"controlResponses":[],"errors":[{"entity":{"entityId":"517c9a46-68ae-427d-b4f9-d99e3078755b","entityType":"GROUP"},"code":"GROUP_CONTROL_PARTIALLY_SUCCESSFUL","message":"Group Control was only partially successful","data":null}]}

**Comment by KronenbergSmarthome** [comment]
> Ok, im Log für die 3.20.0 sieht man das das Kommando generell geklappt hat aber amazon meldet:
> 
> > 2022-11-12 16:48:42.863  - �[34mdebug�[39m: alexa2.0 (851) Alexa-Remote: Sending Request with {"host":"eu-api-alexa.amazon.de","path":"/api/phoenix/state","method":"PUT","timeout":10000,"headers":{}}  and data={"controlRequests":[{"entityId":"517c9a46-68ae-427d-b4f9-d99e3078755b","entityType":"GROUP","parameters":{"action":"turnOn"}}]}
> > 2022-11-12 16:48:44.710  - �[34mdebug�[39m: alexa2.0 (851) Alexa-Remote: Response: {"controlResponses":[],"errors":[{"entity":{"entityId":"517c9a46-68ae-427d-b4f9-d99e3078755b","entityType":"GROUP"},"code":"GROUP_CONTROL_PARTIALLY_SUCCESSFUL","message":"Group Control was only partially successful","data":null}]}

Ja, aber da scheint bei Amazon selber irgendwas mit der Gruppe selber nicht zu stimmen. Muss die Gruppe nochmal löschen und neu anlegen. Bei Alexa sind in der Gruppe vier Geräte drin, aber manchmal reagieren nur drei Geräte

**Comment by Apollon77** [comment]
genau ... nichts wo der Adapter etwas tun kann oder der Adapter in 3.21 was anders im vergleich zu 3.20. tut

**Comment by KronenbergSmarthome** [comment]
Hi, hier mal die Log´s. Das erste Log (iobroker.current.20.0.0.log) ist vom Start der Instanz bis "2022-11-13 11:23:51.278  - [32minfo[39m: alexa2.0 (20504) Initialization Done ..." Danach steuere ich direkt ein SHD den powerState auf false und dann wieder auf true.
Das zweite Log (iobroker.current.20.0.0.-.21.0.0.log) beinhaltet auch das erste Log.
Bei 2022-11-13 11:25:46.812 upgrade ich die Instanz von 20.0.0 auf 21.0.0, Dort warte ich wieder bis "2022-11-13 11:28:37.217  - [32minfo[39m: alexa2.0 (20767) Initialization Done ..." Danach steuere ich direkt ein SHD den powerState auf false und dann wieder auf true. Dann habe ich die Instanz gestoppt und den kompletten Ordnerbaum 0 unterhalb des Alexa2 Adapters gelöscht und die Instanz bei "2022-11-13 11:30:30.093  - [32minfo[39m: host.QNAP-TS251A "system.adapter.alexa2.0" enabled" wieder gestartet. Bei "2022-11-13 11:32:02.585  - [32minfo[39m: alexa2.0 (20954) Initialization Done ..." ist alles abgeschlossen.
Komischerweise wurden alle SmartHomeDevices jetzt auf einmal, nur durch das Update der Version auf 21.0.0, ohne dass ich danach noch irgendwelche Änderungen an den Einstellungen vorgenommen habe, wieder in den Objekten angezeigt und das steuern funktioniert jetzt auch mit 21.0.0.

[iobroker.current.20.0.0.log](https://github.com/Apollon77/ioBroker.alexa2/files/9996960/iobroker.current.20.0.0.log)
[iobroker.current.20.0.0 - 21.0.0.log](https://github.com/Apollon77/ioBroker.alexa2/files/9996961/iobroker.current.20.0.0.-.21.0.0.log)

**Comment by blaumsass** [comment]
iÍch habe das auch! Erst wurden nach update erst keine Aktualisierungen angezeigt. Dann habe ich die Instanz gelöscht und die Github version installiert, seitdem gibt es keine Smart Home Geräte mehr. Nur noch 2 Datenpunkte (löschen, und suchen). Weiß jetzt nicht mehr weiter...

**Comment by Apollon77** [comment]
@blaumsass Mal ganz frecjh gefragt: WER hat Dir gesagt Du sollst von GitHub installieren? Sei frpoh das es aktiuell der gleiche Stand ist wie auch in Beta mit dem letzten Release aber das ist NICHT sichergestellt. EInfach lassen und AUSSCHLIESLICH auf Anweisung tun. Danke

Warten auf 3.22

**Comment by KronenbergSmarthome** [comment]
> Ich habe das auch! Erst wurden nach update erst keine Aktualisierungen angezeigt. Dann habe ich die Instanz gelöscht und die Github version installiert, seitdem gibt es keine Smart Home Geräte mehr. Nur noch 2 Datenpunkte (löschen, und suchen). Weiß jetzt nicht mehr weiter...
> 
> Version jetzt 3.21 (keine Fehlermeldung)
> 
> 
> 
> update unter 3.19.10 alle Geräte sofort da.

Wenn dir die GitHub Version holst, dann kann es sein dass du nen Stand hast der völlig undefiniert ist.

**Comment by Apollon77** [comment]
So, es gibt eine neue Alpha Version (GitHub) ... Bitte versuchen https://forum.iobroker.net/topic/60369/test-adapter-alexa2-3-23-0

**Comment by blaumsass** [comment]
Läuft perfekt! Danke euch/dir! Bei mir ging es um einzelne Geräte Gruppen verwende ich nicht!

Gruß

**Comment by Werner303** [comment]
Ich habe gerade die 3.23.1 Version installiert.  Leider wird "Smart-Home-Device" nicht angezeigt.
![image](https://user-images.githubusercontent.com/37148641/204103484-ceaa09b6-26e9-4676-8140-aa5d51aaa5d4.png)
Ich habe den neuen Echo Dot - Version gekauft. In der Alexa App kann ich die Temperatur anzeigen lassen und auch über die Sprachabfrage ausgeben.

**Comment by Apollon77** [comment]
Hast Du "Smart Home Devices" in der Konfig auch eingeschaltet?

**Comment by KronenbergSmarthome** [comment]
Läuft perfekt! Vielen Dank für die unermüdliche Arbeit 👍 Vergesst nicht zu sponsoren Leude!!!

**Comment by Werner303** [comment]
https://github.com/Apollon77
Vielen Dank für die schnelle Antwort. Ich habe viel gesucht und ausprobiert.... und es war so einfach.
Noch einen schönen und erholsamen Advent
Werner
