### ISSUE TITLE
History aktualisierung dauert sehr lange

### ISSUE THREAD

**Issue by Streit187** [Apollon77/ioBroker.alexa2#969]
Hallo Apollon, 
ich weiß nicht genau seit wann aber derzeit dauert die Aktualisierung des History Ordners (alexa2.0.History) sehr lange sprich zwischen ca. 1 und 5 Minuten oder in seltenen Fällen auch mehr. 
In der App kann ich den aufgezeichneten Sprachbefehl sofort finden. 
Wenn ich den Trigger (alexa2.0.History.#trigger) nutze werden die Einträge sofort aktualisiert. 
Im Log sind keine Einträge, dass Push nicht funktionieren würde bzw. auch sonst keine Auffälligkeiten. 

 - Adapter version: v3.19.9
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: Linux 10

Danke und viele Grüße
Streit

**Comment by Apollon77** [comment]
Bitte Log prüfen ob die Push Verbindung aktiv ist oder ob es da Fehler gibt. Wenn Fehler dann bitte Adapter mal neustarten. Wenn immer noch fehler dann bitte mal zeigen

**Comment by Streit187** [comment]
Also tatsächlich konnte ich nun die Einträge mit "Alexa-Push-Connection disconnected - retry: Retry Connection in 60s" finden. 
Ich bin sicher du möchtest gerne mehr vom Log sehen. Nachdem dieser aber ja in Sekunden etliche Zeilen schreibt, kannst du den Bedarf etwas eingrenzen?

**Comment by Apollon77** [comment]
Also wenn diese Meldungen dauerhaft kommen dann mal Mit Debug Log schauen ob da noch mehr Infos zu sehen sind. Ansonsten -> https://github.com/Apollon77/ioBroker.alexa2#push-connections-do-not-connect

**Comment by Streit187** [comment]
https://github.com/Apollon77/ioBroker.alexa2#push-connections-do-not-connect hat das Problem gelöst. Vielen Dank
