### ISSUE TITLE
Ausgabe über angesprochenen Echo.

### ISSUE THREAD

**Issue by Bijou-Ham-Ham** [Apollon77/ioBroker.alexa2#97]
Kurz zu Anfang der Adapter ist super Hut ab an die/den Entwickler.
Allerdings wäre es schön wenn es möglich wäre den Echo den Text ausgeben zu lassen, welchen man gefragt hat.

LG
Hamtaro

**Comment by Apollon77** [comment]
Das geht indem du Die History Datenpunkt nutzt und diese mit einem kleinen JavaScript entsprechend auswertest.

**Comment by xXHamtaroXx** [comment]
Im History Punkt stet aber kein dot oder der gleichen drin wenn ich ihn
ansprecher...das Feld belibt leer :(

Mit freundlichem Gruß

Jamie Albring

Ingo Fischer <notifications@github.com> schrieb am Di., 18. Sep. 2018,
06:29:
