### ISSUE TITLE
History wird nicht aktualisiert und Commands funktionieren auch nicht?

### ISSUE THREAD

**Issue by polocup100** [Apollon77/ioBroker.alexa2#973]
Hallo, plötzlich macht der Adapter nichts mehr.
Alle drei Häkchen sind auf grün, neustes Update ändert auch nichts, Cookie ist auch schon erneuert (manuell)
Im Log gibt es auch keine Fehler? Raspberry auch schon neu gestartet.

Was kann das sein?

VG Serge

**Comment by uwe72** [comment]
Wir haben das gleiche Problem!

**Comment by ChristopherGier** [comment]
Hier ebenfalls

**Comment by uwe72** [comment]
Wobei ich 2 Systeme habe, bei einem gehts noch beim anderen nicht. Sehr strange

**Comment by Apollon77** [comment]
Dann habt Ihr die 3.19.x Kleiner 3.19.10 und den adapter neu gestartet. itte auf 3.19.10 updaten wie Euch an Sich eine Admin Info hätte sagen sollen.

**Comment by uwe72** [comment]
ich habe die 3.19.10 heute morgen installiert, da es mit 3.19.9 (auch) nicht funktionierte 
![image](https://user-images.githubusercontent.com/61848539/198530726-e14a6fe4-7392-4614-9487-6b89fddce50c.png)

**Comment by Apollon77** [comment]
Mit der 3.19.10 sollte alles wieder gehen - ausser ggf Smart-Home-Device Steuerung weil Amazon das aktuell blockiert

**Comment by Apollon77** [comment]
PS: Aber auch mit der 3.19.10 bitte warten das im Log nach demStart ein "Initialization done" kommt, das kann je nach Anzahl der Geräte ggf paar Minuten dauern! Erst danach gehen Steuerungen

**Comment by uwe72** [comment]
Funktioniert, danke!!

**Comment by Apollon77** [comment]
Ja das kann sein weil immer noch von Amazon geblockt

**Comment by polocup100** [comment]
Habe jetzt nen Backup mit 3.18.6 zurückgespielt, Alexa2 läuft damit.
Dann 3.19.10 installiert und 5min gewartet, jetzt geht es auch damit!?
Hatte vorher schon mal den Adapter deinstalliert und den *.json file gelöscht wie beschrieben, leider ohne Erfog.

**Comment by flapman** [comment]
Gleiches Problem ist bei mir jetzt aus dem nichts auch gekommen. Vor ein paar Tagen ging es noch.

**Comment by Apollon77** [comment]
@flapman sorry, but lol? There is a pinned post with  all details and you comment to a nearly one year old closed issue? (No I do not expect an answer) :-)

**Comment by Apollon77** [comment]
> Neue Issues aufmachen mit der gleichen Überschrift sehe ich als Sinnfrei an. 

Ok dann sei erwähnt: Closed ist closed. Closed > paar Tage ist an sich "ignore". Also wenn duhilfe willst dann ja bitte lege neue Issues an weil es dann voraussichtlich auch ein anderes Problem ist als das ursprüngliche issue - das wäre ja nicht closed wenn es nicht gefixt wäre.

> Github hat pinned messages? Hast du einen Link, ich sehe keine angepinnten.

Ja unter "issues" direkt ganz oben
