### ISSUE TITLE
No Smart-Home-Devices (It worked before a few days)

### ISSUE THREAD

**Issue by undeat** [Apollon77/ioBroker.alexa2#976]
I have got a new issue during the last few days and mabye it came with the last stable update. Now i use v3.19.10. Before that update i had the older stable version. Maybe the issue came with that update but i am not sure because i do not use it every day.

I use the Alexa2 Adapter to control some Smarthome device i could not connect to iobroker on an other way. In that case some WiFi RGB controller but i have the same issue with all Samrat-Home-Devices from the Alexa2 Adapter. 

No device reacts to controls from io broker
io broker do now show the actual state of any device
i deleted the complete Smart-Home-Devices folder from Object tree and the adapter only creates the "delete all" and "discover devices" states.

I tried it for a few days
I tried to re load the cookie
I installed a new instance from Alexa2 und stopped the first one

Nothing is helping.

**Comment by undeat** [comment]
I have got it. I did not see the last issues. Update to 3.20.1 helped for me, too.

That version is not show in my iob broker admin instance. Not as stable and not as beta.
That update must be installed by

iob upgrade alexa2@3.20

**Comment by Apollon77** [comment]
Beta it shpuld be since earlier. Maybe you need to reload the repo?
