### ISSUE TITLE
 New Device: Echo Dot Gen 5

### ISSUE THREAD

**Issue by Golgarath** [Apollon77/ioBroker.alexa2#978]
Hi, it seems like, a new device, Echo Dot Gen 5, needs to be added -- https://www.amazon.de/echo-dot-2022/dp/B09B8X9RGM 

alexa2.0 | 2022-10-30 19:55:45.383 | info | Device-type:A4ZXE0RM7LQ7A - XXXXXX (SET_LOCALE,GUARD_EARCON,DEREGISTER_DEVICE,REQUIRES_OOBE_FOR_SETUP,SUPPORTS_SOFTWARE_VERSION,VOLUME_SETTING,BT_PAIRING_FLOW_V2,REMINDERS,TAHOE_BYOD,SLEEP,ACTIVE_AFTER_FRO,PAIR_BT_SINK,ALEXA_PRESENCE,MUSIC_SKILL,CHANGE_NAME,SPEECH_RECOGNIZER_USS,LOCALIZATION,SET_TIME_ZONE,PAIR_BT_SOURCE,TAP_GESTURES_RESUME_MEDIA,TEMPERATURE_SENSOR,TIMERS_AND_ALARMS,SUPPORTS_LOCALE_SWITCH,MOTION_DETECTION,SUPPORT_CALENDAR_ALERT,CUSTOM_ALARM_TONE,EQUALIZER_CONTROLLER_BASS,PERSISTENT_CONNECTION,KINDLE_BOOKS,LEMUR_ALPHA,SUPPORTS_LOCALE,GADGETS,I_HEART_RADIO,DIALOG_INTERFACE_VERSION,TIDAL,EFDCARDS,WAKE_WORD_SENSITIVITY,EQUALIZER_CONTROLLER_TREBLE,SALMON,PANDORA,TAP_GESTURES_SINGLE_TAP,TIMERS_ALARMS_NOTIFICATIONS_VOLUME,VOICE_TRAINING,EQUALIZER_CONTROLLER_MIDRANGE,AUDIO_PLAYER,TUPLE,SIRIUSXM,TUPLE_CATEGORY_A,TUNE_IN,AUDIBLE,DS_VOLUME_SETTING,ASCENDING_ALARM_VOLUME,FLASH_BRIEFING,DEEZER,POPTART,TAP_GESTURES,UPDATE_WIFI,MOTION_SENSOR_RANGE_STRING,ALEXA_VOICE,SOUND_SETTINGS,GOLDFISH,ADAPTIVE_LISTENING,DREAM_TRAINING,APPLE_MUSIC,SUPPORTS_CONNECTED_HOME_CLOUD_ONLY,MULTI_WAKEWORDS_SUPPORTED,EARCONS,FAR_FIELD_WAKE_WORD,AMAZON_MUSIC,MICROPHONE,AUDIO_CONTROLS)

**Comment by Apollon77** [comment]
thx, will be added in next version
