### ISSUE TITLE
Optimize the "what's new" info in IOBroker

### ISSUE THREAD

**Issue by derrapf** [Apollon77/ioBroker.alexa2#979]
Als ich den Alexa2 Adapter heute auf 3.20.1 upgedatet habe konnte ich Folgendes lesen:

"• achten sie darauf, dass cache mit mehreren instanzen des adapters korrekt funktioniert"

Frage: Wie!? soll ich genau darauf achten, dass der Cache (Welcher Cache?) mit mehreren Instanzen des Adapters funktioniert?
Bitte genauer erklären oder Link posten in dem steht was zu tun ist.

" Erhöhen Sie das Mindestintervall für die Anforderung von Smart-Home-Gerät-Daten auf 15 Minuten (900s) wegen Amazon-Rate Grenzen. "

Auch hier:
Wie erhöhe ich das Mindestintervall? Wo genau muss ich was einstellen? Auch  hier wären mehr Details oder ein Link hilfreich.

*"Bitte versuchen Sie nicht, um es zu arbeiten!"
Den Satz verstehe ich nicht.
Soll es ev. heissen: Bitte versuchen Sie nicht etwas (was? Das Mindestintervall?) zu  umgehen? Dazu müsste man wissen, wie man es überhaupt einstellt.

*"Cache Smart Home Geräteliste und Daten, um zu viele Anfragen beim Neustart von Adapter in kurzen Intervallen zu verhindern und gelöschte Smart Home-Geräte auch bei weiteren Geschwindigkeitsbeschränkungen zu verhindern"

Ich nehme an damit ist gemeint, dass ein Cache für SmartHome Geräte und Daten hinzugefügt wurde?

Vorschlag:
Entweder die Beschreibungen von einem Muttersprachler prüfen lassen oder bitte in Englisch zur Verfügung stellen.

Wenn man als User nicht tief in der Materie steckt, ist unklar ob man nun was machen muss, oder ob nur die Übersetzung so falsch ist, dass es klingt als ob der User etwas tun müsste.

Mir ist das immer noch unklar. Gerade die ersten Sätze. Muss ich nun was tun oder nicht? Und wenn ja was und wie?

Gruss Ralf

**Comment by Apollon77** [comment]
Kann ich gern korrigieren. Im Admin können die Changelogs aber über das Weltkugelsymbol im Changelog Overlay auch auf englisch umgeschaltet werden

**Comment by derrapf** [comment]
Ah. Super.
Ich habe schon bei anderen Adaptern solch ein schräges Deutsch gefunden. Speziell mit "tun Sie" Syntax ("Erhöhen Sie..., Optimieren sie... usw.) 
Wäre es nicht besser (wenn man davon ausgeht, dass keine Zeit da ist diese Texte richtig zu übersetzen) ,dass man das einfach grundsätzlich in Englisch macht? Ich denke dann gibt es da weniger Verwirrung.

PS: Muss ich jetzt tatsächlich was machen oder ist das wirklich nur schlecht übersetzt?

Gruss Ralf

**Comment by Apollon77** [comment]
Das ist automatisch ünersetzt und nicht gegengelesen ... so kann man es sagen. ja :-)

**Comment by derrapf** [comment]
Kein Wunder. Was nehmt ihr? Google oder Deepl?   
Das ist dann wie mit den chinesischen Anleitungen. Da muss man auch jeden Satz cerebral interpolieren.

Ich gehe jetzt mal davon aus (das weiss ich immer noch nicht), dass "Erhöhen Sie das Mindestintervall " und  "achten sie darauf, dass cache "  keine Aufgaben für mich sind, richtig?

Gruss Ralf

**Comment by Apollon77** [comment]
Korrekt ist eher ein "wurde erhöht".

**Comment by derrapf** [comment]
Ok. Dann hab ich es also doch falsch verstanden. 
Aber gut: 
D.h. ich muss nicht aktiv werden und irgendwas erhöhen oder auf irgendwas achten.
Danke!
