### ISSUE TITLE
Alexa stellt licht bei Ausbefehl auf 0%

### ISSUE THREAD

**Issue by BenAhrdt** [Apollon77/ioBroker.alexa2#983]
Seit der Version 3.20.1 stellt Alexa bei dem Befehl "Alexa Licht aus" den STate auf false und die Brigthnes meiner Zigbee Lampen auf 0%.
Werden diese dann wieder über ein Script im state auf true gesetzt, so gehen sie nur mit 50% an.
Vor dem Update war dies, so meine ich, nicht so.

Kann das sein?

**Comment by Apollon77** [comment]
Ok wovon reden wir? Geäte über den iot Adapter? Dann hat das mit Alexa2 nichts zu tun, sondenr mit iot ... vllt auch da aktualisiert? Ist die 50% da vllt eingestellt bzw ist vllt nicht eingestellt das er den letzten Wert erinnern soll?

**Comment by BenAhrdt** [comment]
Ja darum geht es. ich stelle dann dort ein issu rein

**Comment by Apollon77** [comment]
Puuh ... jetzt überlagern sich ggf Logiken des iopt mit anderen Adaptersn ... Debug log bitte ... und genau sagen was wann wie warum passiert mit reihenfolge und iot Log ... dann sieht man mal weiter

**Comment by BenAhrdt** [comment]
Hier mein Log:
1. Alexa soll das licht ausmachen. 
2. durch ein script wird über den selector das licht mit state = true wieder aktiviert (Allerdings ist es nur auf 50%.

[iobroker.current.log](https://github.com/Apollon77/ioBroker.alexa2/files/9939373/iobroker.current.log)

**Comment by Apollon77** [comment]
iot issue bitte ... wenn müsste man gfg ändern das wenn eine lampe einen Switch hat man bei off  das brightness nicht auf 0 setzt.
