### ISSUE TITLE
Release 3.21.0 Geräte und Sprachsteuerung

### ISSUE THREAD

**Issue by TomsEleven** [Apollon77/ioBroker.alexa2#984]
Hi,
erstmal vielen Dank fürs Programmieren und super schnelle Weiterentwickeln des Alexa Adapters. Ich wollte Dir mal schildern wie's bei mir gerade läuft. Vll hilft Dir das ja.
Mein System: Adapter 3.21.0   ///   Node.js: v14.20.1   ///   NPM: 6.14.17   ///   auf Linux VM

* Meine Smart-Home-Devices lassen sich mit dem neuen Update wieder steuern

* ich habe (s. Screenshot Schalter) einige "virtuelle" Geräte in 0_userdata angelegt. Wenn ich die per Sprache ein-/ausschalten möchte sagt Alexa "ich bin mir leider nicht sicher" oder "das weiß ich leider nicht". Wenn ich diese Geräte per Handy-App starte funktionierts :-) [hat früher super funktioniert]

* im Screenshot Steckdosen siehst Du einige Tasmota Geräte, die per Belkin WeMo Emulation in Alexa integriert sind. Diese zeigen zwar "Server reagiert nicht" funktionieren aber per Sprache und per App [gab früher keine Fehlermeldungen]

Ich habe auch ein Debug Log erstellt - falls Dir das hilft sende ich Dir das gerne per Mail.

Viele Grüße
Tom

![Bildschirmfoto 2022-11-06 um 11 04 11](https://user-images.githubusercontent.com/117567938/200175078-d76b0128-13b8-4fe1-9266-eb77113b0db1.png)
![Bildschirmfoto 2022-11-06 um 14 29 05](https://user-images.githubusercontent.com/117567938/200175079-ccd8634b-f115-44e7-80d9-95f6d831ec29.png)

**Comment by Apollon77** [comment]
Virtuelle Geräte unter 0_userdata.0 haben mit Alexa2 nichts zu tun, sondern iot ... aber wenn es bisher tat und jetzt nicht dann besser schauen was Alexa in den "Sprach Protokoll erkannt hat" ... und schaue ob es überlappungen gibt. ggf Alexa Geräte neu suchen lassen.
