### ISSUE TITLE
Smartlife problem...devices visible but not receiving commands

### ISSUE THREAD

**Issue by mactwin** [Apollon77/ioBroker.alexa2#985]
Using last version (3.21.00) I can see all smart-device in object tab, but the smartlife devices doesn't work anymore.
Alexa can activate or deactivate while I can't do the same using iobroker.
All other devices (aquaria, ewelink...) works fine.

**Comment by Apollon77** [comment]
Please provide a debug level log of a try to do such a control.
ANd ideally please consider using Tuya 3.8.1 instead of Alexa control for Tuya/Smartlife devices because with the new version the proxy stuff is not longer needed and should be the morepractical way!

**Comment by mactwin** [comment]
Great, solved with new tuya add in, stunning!! more fast, simple.....perfect!

tnx
