### ISSUE TITLE
Music Provider Issue

### ISSUE THREAD

**Issue by freakyfreaky** [Apollon77/ioBroker.alexa2#986]
Im Zusammenhang mit der Diskussion im Forum anbei die Debug Logs.
Wenn mehr benötigt wird, bitte melden. ID´s und Accounts wurden mit xxx ersetzt

ECHO Profil 1 - Account verknüpft (geht)
`2022-11-13 09: 45: 38.034 - debug: alexa2.0 (109781) State changed alexa2.0.Echo-Devices.G2A1xxxxxxxxxxxxxx.Music-Provider.TuneIn: {
    "val": "big fm",
    "ack": false,
    "ts": 1668329138031,
    "q": 0,
    "from": "system.adapter.admin.0",
    "user": "system.user.admin",
    "lc": 1668329138031
}
2022-11-13 09: 45: 38.034 - debug: alexa2.0 (109781) Alexa-Remote: No authentication check needed (time elapsed 108811)
2022-11-13 09: 45: 38.034 - debug: alexa2.0 (109781) Alexa-Remote: Sending Request with {
    "host": "eu-api-alexa.amazon.de",
    "path": "/api/behaviors/operation/validate",
    "method": "POST",
    "timeout": 10000,
    "headers": {}
} and data={
    "type": "Alexa.Music.PlaySearchPhrase",
    "operationPayload": "{\"deviceType\":\"A3FX4UWTP28V1P\",\"deviceSerialNumber\":\"G2A1xxxxxxxxxxxxxx\",\"locale\":\"de-DE\",\"customerId\":\"ARXxxxxxxxxxxxxxxx\",\"musicProviderId\":\"TUNEIN\",\"searchPhrase\":\"big fm\"}"
}
2022-11-13 09: 45: 38.393 - debug: alexa2.0 (109781) Alexa-Remote: Response: {
    "operationPayload": {
        "deviceType": "A3FX4UWTP28V1P",
        "sanitizedSearchPhrase": "big f. m.",
        "searchPhrase": "big fm",
        "customerId": "ARXxxxxxxxxxxxxxxx",
        "locale": "de-DE",
        "musicProviderId": "TUNEIN",
        "deviceSerialNumber": "G2A1xxxxxxxxxxxxxx"
    },
    "result": "VALID"
}
2022-11-13 09: 45: 38.394 - debug: alexa2.0 (109781) Alexa-Remote: No authentication check needed (time elapsed 109171)
2022-11-13 09: 45: 38.394 - debug: alexa2.0 (109781) Alexa-Remote: Sending Request with {
    "host": "eu-api-alexa.amazon.de",
    "path": "/api/behaviors/preview",
    "method": "POST",
    "timeout": 10000,
    "headers": {}
} and data={
    "behaviorId": "PREVIEW",
    "sequenceJson": "{\"@type\":\"com.amazon.alexa.behaviors.model.Sequence\",\"startNode\":{\"type\":\"Alexa.Music.PlaySearchPhrase\",\"operationPayload\":{\"deviceType\":\"A3FX4UWTP28V1P\",\"sanitizedSearchPhrase\":\"big f. m.\",\"searchPhrase\":\"big fm\",\"customerId\":\"ARXxxxxxxxxxxxxxxx\",\"locale\":\"de-DE\",\"musicProviderId\":\"TUNEIN\",\"deviceSerialNumber\":\"G2A1xxxxxxxxxxxxxx\"},\"@type\":\"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\"}}",
    "status": "ENABLED"
}
2022-11-13 09: 45: 38.560 - debug: alexa2.0 (109781) Alexa-Remote: Response: No body
2022-11-13 09: 45: 38.561 - debug: alexa2.0 (109781) Schedule new Player Update in 5000ms`

ECHO Profil 2 - Haushalt (geht nicht)
`2022-11-13 09: 45: 59.786 - debug: alexa2.0 (109781) State changed alexa2.0.Echo-Devices.G091xxxxxxxxxxxxxx.Music-Provider.TuneIn: {
    "val": "big fm",
    "ack": false,
    "ts": 1668329159784,
    "q": 0,
    "from": "system.adapter.admin.0",
    "user": "system.user.admin",
    "lc": 1668329159784
}
2022-11-13 09: 45: 59.786 - debug: alexa2.0 (109781) Alexa-Remote: No authentication check needed (time elapsed 130563)
2022-11-13 09: 45: 59.786 - debug: alexa2.0 (109781) Alexa-Remote: Sending Request with {
    "host": "eu-api-alexa.amazon.de",
    "path": "/api/behaviors/operation/validate",
    "method": "POST",
    "timeout": 10000,
    "headers": {}
} and data={
    "type": "Alexa.Music.PlaySearchPhrase",
    "operationPayload": "{\"deviceType\":\"A2H4LV5GIZ1JFT\",\"deviceSerialNumber\":\"G091xxxxxxxxxxxxxx\",\"locale\":\"de-DE\",\"customerId\":\"A16xxxxxxxxxxxxxxx\",\"musicProviderId\":\"TUNEIN\",\"searchPhrase\":\"big fm\"}"
}
2022-11-13 09: 46: 00.125 - debug: alexa2.0 (109781) Alexa-Remote: Response: {
    "operationPayload": {
        "deviceType": "A2H4LV5GIZ1JFT",
        "sanitizedSearchPhrase": "big f. m.",
        "searchPhrase": "big fm",
        "customerId": "A16xxxxxxxxxxxxxxx",
        "locale": "de-DE",
        "musicProviderId": "TUNEIN",
        "deviceSerialNumber": "G091xxxxxxxxxxxxxx"
    },
    "result": "VALID"
}
2022-11-13 09: 46: 00.125 - debug: alexa2.0 (109781) Alexa-Remote: No authentication check needed (time elapsed 130902)
2022-11-13 09: 46: 00.125 - debug: alexa2.0 (109781) Alexa-Remote: Sending Request with {
    "host": "eu-api-alexa.amazon.de",
    "path": "/api/behaviors/preview",
    "method": "POST",
    "timeout": 10000,
    "headers": {}
} and data={
    "behaviorId": "PREVIEW",
    "sequenceJson": "{\"@type\":\"com.amazon.alexa.behaviors.model.Sequence\",\"startNode\":{\"type\":\"Alexa.Music.PlaySearchPhrase\",\"operationPayload\":{\"deviceType\":\"A2H4LV5GIZ1JFT\",\"sanitizedSearchPhrase\":\"big f. m.\",\"searchPhrase\":\"big fm\",\"customerId\":\"A16xxxxxxxxxxxxxxx\",\"locale\":\"de-DE\",\"musicProviderId\":\"TUNEIN\",\"deviceSerialNumber\":\"G091xxxxxxxxxxxxxx\"},\"@type\":\"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\"}}",
    "status": "ENABLED"
}
2022-11-13 09: 46: 00.303 - debug: alexa2.0 (109781) Alexa-Remote: Response: {
    "message": "Input failed to validate."
}
2022-11-13 09: 46: 00.303 - debug: alexa2.0 (109781) Schedule new Player Update in 5000ms`

**Comment by Apollon77** [comment]
ok, ich brauche bitte ein vollständiges log vom Start und dann wenn alles initialisiert ist so eine aktion. Bitte per E-Mail an iobroker@fischer-ka.de
