### ISSUE TITLE
Bug? - Shuffle funktioniert nicht

### ISSUE THREAD

**Issue by HeadCrash78** [Apollon77/ioBroker.alexa2#987]
Ich verwende den alexa2 Adapter (v3.21.0) im ioBroker (js-controller 4.0.23, Node.js 16.17.0) und versuche eine Amzon Music Playlist im Shuffle Modus wiederzugeben. Egal welche Playlist ich verwende (eigene oder von Amazon erstellt), allowShuffle ist immer false und controlShuffle zeigt keine Wirkung.

Gibt es hier etwas spezielles zu beachten? Stimmt etwas mit dem Adapter nicht? In der Amazon Music App lässt sich Shuffle für alle Playlists aktivieren.

**Comment by HeadCrash78** [comment]
Das scheint ein Timing Issue zu sein. Nach dem setzen der Playlist dauert es eine Weile, bis diese gespielt wird. In der Zwischenzeit "verpuffen" alle weitere Commands wie controlShuffle und/oder controlNext. Wartet man lange genug, funktioniert controlShuffle + controlNext, auch wenn allowShuffle false ist.

Mein Workaround für zufällige Wiedergabe einer Playlist ist jetzt, den Titel der Playlist um den String "zufällige Wiedergabe" zu erweitern. Dann spielt Alexa gleich von Anfang an in einer zufälligen Reihenfolge.

**Comment by Apollon77** [comment]
allowShuffly kommt vom Player zurück wenn die Musik gestartet ist - korrekt. No other way

**Comment by HeadCrash78** [comment]
Das war kein Vorwurf an Dich, nur der Hinweis, dass das Property ganz offensichtlich falsch zurückgemeldet wird 😉

**Comment by Apollon77** [comment]
Ok, wenn innder Mobile App für ein laufendes Play ein shuffle erlaubt ist dann bitte mal ein Debug log vom Alexa2 Adapter vom starten der Musik und so posten ... weil an sich kommt die Info von Amazon
