### ISSUE TITLE
status auslesen wenn man ein Titel oder Song weiter machen kann?

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#99]
wie bzw. wo kann ich den status auslesen wenn man ein Titel oder Song weiter machen kann? ich will mir wie in der app die weiter und zurück button grau (deaktiv) bzw weiß (aktiv) anzeigen lassen.

**Comment by Apollon77** [comment]
Gute Frage. Hier wären Debug Logs von "media/player abfragen" und deren Antworten für beide Fälle interessant.
