### ISSUE TITLE
Speak-Command does work when the text is entered manually but not when set via MQTT

### ISSUE THREAD

**Issue by rettet-die-stille** [Apollon77/ioBroker.alexa2#991]
**Describe the bug**  
When I manually enter a speak command in the Objects View the echo device plays it nicely! 
Also I can use the MQTT publish command to set the speak object with the desired text. 
I can see the desired text in the object tree as I would have entered it manually. 
Only problem: Now Alexa does not speak it. So it seems that a manual entry in the speak field is triggering the echo device to speak (when pressing "Set Value" in the Write Value dialog). But not when the object tree receiving the exact same value via MQTT.

**To Reproduce**  
1. Go to 'alexa2.0.Echo-Devices.xxx.Commands.speak'
2. Click on the value field and enter "This is a test"
3. Press "Set Value" in the Write Value dialog
4. You can hear the echo device say "This is a test"
5. Publish the text "This is a second test" to alexa2/0/Echo-Devices/xxx/Commands/speak
6. You can see the new text "This is a second test" in the value field of 'alexa2.0.Echo-Devices.xxx.Commands.speak' in the objects catalog in iobroker.
7. But the echo device does not play it
8. Click on the value field and submit the existing value with "Set Value" in the Write Value dialog
9. Now you hear the device saying "This is a second test"

**Expected behavior**  
The Echo Device should speak "This is a second test" directly after publish the text "This is a second test" to the topic 'alexa2/0/Echo-Devices/xxx/Commands/speak' using MQTT

**Versions:**  
 - Adapter version: 3.21.0
 - JS-Controller version: 4.0.23
 - Node version: 12.22.12
 - Operating system: Raspian

**Additional context**  
-

**Comment by Apollon77** [comment]
How does MQTT set the state? it needs to be set with "ack=false" to be a command which is processed. When mqtt id setting it with "ack=true" (Ack===Bestätigt) then the adapter will not react on it as it should be.

This can be the only thing

**Comment by rettet-die-stille** [comment]
Thank you for the very quick reply! I am using the IOBroker MQTT Broker/Client Instance (4.0.7) in Broker mode. 

I need help how to change the settings there in order to get it working. I do not seem to have a way to set ack=false. 

Unchecking the option 'Send states (ack=true)' does not help. 

I also played around with all other settings. Did not help either. 

All other instances (e.g. km200, e3dc.rscp) work fine and can be controlled via MQTT with this settings (by publishing the changes from any MQTT client)

This are my settings in the MQTT Instance. Any help is very appreciated.

![image](https://user-images.githubusercontent.com/65538429/203805844-5f9fbd84-6425-40ce-9f9b-3b62522834c5.png)

**Comment by Apollon77** [comment]
Honestly ... I can not help you with this. bestis to ask in forum maybe.

But yes for mqtt with "incoming data" it always handles them as" final data", so they are never commands (ack=false) - from what I know! I did not checked mqtt adapter for that topic! No idea if "use different topic names for get/set" would change that ... 

maybe you need to use own states and then hava s small javascript that sets the real states as you need them
