### ISSUE TITLE
Commands FireHD10 funktionieren nicht, da Devices als Apps erkannt

### ISSUE THREAD

**Issue by Schnecke8** [Apollon77/ioBroker.alexa2#994]
Es geht darum, dass ich meine zwei Fire HD10 Tablets nicht via Commands über den Adapter steuern kann. Grundsätzlich war ja die Info, dass alles was über z.B. Routinen innerhalb der Alexa App funktioniert, auch über den Adapter tun sollte. In beiden Fällen kann ich via Routine speak od. Aktionen wie joke, singasong etc. auslösen. Über den Adapter funktioniert es nicht (Wert wird rot und es tut sich nichts).

Der Adapter liest beide Geräte als Apps ein...
Capatebilities:
MICROPHONE,ADAPTIVE_LISTENING,VOLUME_SETTING,PERSISTENT_CONNECTION,VOLUME_SETTING,TIMERS_AND_ALARMS,SPEECH_RECOGNIZER_USS,SUPPORTS_SOFTWARE_VERSION,NO_TIME_ZONE_SETTING,CUSTOM_ALARM_TONE,ASCENDING_ALARM_VOLUME,DIALOG_INTERFACE_VERSION,ADAPTIVE_LISTENING,REMINDERS,SOUND_SETTINGS,EARCONS,ASX_TIME_ZONE,SUPPORTS_LOCALE_SWITCH
Device Family:
AMAZONMOBILEMUSIC_IOS
DEvice Type:
A1DL2DVDQVK3Q
Device Type String:
Apps

Das komische ist, dass wenn ich die Seriennummern im Debug Log suche, teilweise das für mich richtige Device (A1ZB65LA390I4K --> Fire HD 10 lt. main.js) kommt, nur der Adapter setzt es falsch weil es einmal so und einmal so kommt?

Das Log wurde am 26.11.22 um 13:05 per E-Mail versendet:
Bsp: G00XXXXXXXXXXEVH
Log Line 42:
..."deviceSerialNumber":"G00XXXXXXXXXXEVH","deviceType":"A1ZB65LA390I4K"
--> Das wäre der richtige Device Type für das Fire HD10
Log Line 48:
..."deviceSerialNumber":"G00XXXXXXXXXXEVH","deviceType":"A1ZB65LA390I4K"
--> Das wäre der richtige Device Type für das Fire HD10
Log Line 392: Response:
{"deviceSerialNumber":"G00XXXXXXXXXXEVH","deviceType":"A1DL2DVDQVK3Q"...
--> Das wäre Apps und m.E. falsch

Über einen Fix würde ich mich freuen.

VG

**Comment by Apollon77** [comment]
Grund ist das die serialnumber einmal als Gerät und einmal als App gemeldet wurde ... hab ich so nochnie gesehen. Bitte GitHub version versuchen, dort sollte das gefixt sein

**Comment by Schnecke8** [comment]
Funktioniert 1A, Devices werden richtig erkannt, Commands funktionieren.
Besten Dank für die Umsetzung und generell für deinen Einsatz am Adapter!

PS: Ich meine hier waren noch andere FIreHD10 Issues wo es als Apps erkannt wurde, vielleicht hilft das dort auch, ich schau mal, dass ich darunter noch kommentiere.

LG

**Comment by Apollon77** [comment]
Release geht gleich noch raus, danke! Aber ja das kann echt sein ... iiiiinteressant
