### ISSUE TITLE
Echo Buds (Gen 2) 

### ISSUE THREAD

**Issue by vaaarg** [Apollon77/ioBroker.alexa2#997]
Adapter does not recognize this device yet. Would be nice to see this supported somehow

`<html>
<body>

alexa2.0 | 2022-12-10 06:27:05.766 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaLengthStr" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
alexa2.0 | 2022-12-10 06:27:05.765 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaRemaining" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.764 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaProgressPercent" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.764 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaProgressStr" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.763 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaProgress" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.763 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaLengthStr" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.762 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaLength" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.762 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.miniArtUrl" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.761 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mainArtUrl" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.761 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.currentAlbum" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.760 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.currentArtist" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.759 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.currentTitle" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.758 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.currentState" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.758 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.playingInGroupId" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.756 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.playingInGroup" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.754 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.allowShuffle" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.749 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.allowRepeat" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.749 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.allowPrevious" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.748 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.allowPlayPause" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.748 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.allowNext" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.747 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.qualitySampleRate" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.747 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.qualityDataRate" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.746 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.qualityCodec" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.746 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.quality" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.745 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.queueId" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.745 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaId" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.745 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.imageURL" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.744 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.controlPlay" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.744 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.controlPause" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.743 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.contentType" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.742 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.service" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.742 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.radioStationId" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.741 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.providerId" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:27:05.740 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.providerName" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:26:46.109 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Preferences.connectedSpeaker" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:26:46.098 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Preferences.ringNotificationsEnabled" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:26:46.050 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Info.deviceFamily" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:26:46.038 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Info.name" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:26:46.033 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Info.serialNumber" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:26:46.029 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Info.deviceTypeString" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:26:46.023 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Info.deviceType" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:26:46.019 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Info.isMultiroomMember" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:26:46.013 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Info.isMultiroomDevice" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:26:46.002 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Info.softwareVersion" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:26:45.997 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Info.capabilities" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:26:45.991 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.online" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:08:40.766 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Preferences.ringNotificationsEnabled" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 06:08:40.097 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Commands.doNotDisturb" has no existing object, this might lead to an error in future versions
zigbee.0 | 2022-12-10 05:48:04.376 | warn | Device '0x0017880103e54b5a' announced itself
alexa2.0 | 2022-12-10 05:26:37.006 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaRemaining" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:37.005 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaProgressPercent" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:37.005 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaProgress" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:37.006 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaLengthStr" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:37.004 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaLengthStr" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:37.005 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaProgressStr" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:37.004 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaLength" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:37.003 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.miniArtUrl" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:37.003 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mainArtUrl" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:37.002 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.currentAlbum" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:37.002 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.currentArtist" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:37.001 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.currentTitle" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:37.001 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.currentState" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:36.996 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.playingInGroupId" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:36.996 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.playingInGroup" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:36.995 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.allowRepeat" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:36.994 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.allowPrevious" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:36.995 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.allowShuffle" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:36.994 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.allowPlayPause" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:36.993 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.allowNext" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:36.993 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.qualitySampleRate" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:36.991 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.qualityDataRate" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:36.991 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.qualityCodec" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:36.988 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.quality" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:36.987 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.queueId" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:36.987 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.mediaId" has no existing object, this might lead to an error in future versions
alexa2.0 | 2022-12-10 05:26:36.986 | warn | State "alexa2.0.Echo-Devices.amzn1.dgroup.fac25fd90392f041e604f8200aa0e6a0c793.Player.imageURL" has no existing object, this might lead to an error in future versions

</body>
</html>`

**Comment by Apollon77** [comment]
Please provide a full debug log from adapterstart and send to me via email to iobroker@fischer-ka.de with reference to this issue

**Comment by Pocky2507** [comment]
`2022-12-10 08:26:39.003 - info: alexa2.0 (402300) Device-type:A15QWUTQ6FSMYX - Achim's Echo Buds (2. Generation) (AUDIBLE,FLASH_BRIEFING,LAMBDA_DOWNCHANNEL,FAR_FIELD_WAKE_WORD,ACTIVE_AFTER_FRO,I_HEART_RADIO,KINDLE_BOOKS,AMAZON_MUSIC,CHANGE_NAME,MICROPHONE,ADAPTIVE_LISTENING,EARCONS,AUDIO_PLAYER,VOLUME_SETTING,SUPPORTS_SOFTWARE_VERSION,SUPPORTS_CONNECTED_HOME,TUNE_IN,DEREGISTER_DEVICE,FACTORY_RESET_DEVICE,REQUIRES_OOBE_FOR_SETUP,AUDIO_CONTROLS,PANDORA)`

**Comment by Apollon77** [comment]
If the errors come back again after an adapter restart I really need a FULL Debug log as stated above

**Comment by Pocky2507** [comment]
Ok, then @vaaarg has to do it.
I only have the messages from the unknown device.
dgroup messages do not appear with me.

**Comment by vaaarg** [comment]
one second, trying to fetch this

**Comment by vaaarg** [comment]
> If the errors come back again after an adapter restart I really need a FULL Debug log as stated above

mail sent thx
